-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:5000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:0.1
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=5000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3429397/1692555657_060196744', seed=42, img_per_thread=277)
will save 5000 patches in /scratch-local/sunnys.3429397/1692555657_060196744/single_img_crops/crops
5000 took 0.09min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 20:21:53,258 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 20:21:53,259 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3429397/1692555657_060196744/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3429397/1692555657_060196744/cifar-10-python.tar.gz to /scratch-local/sunnys.3429397/1692555657_060196744
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=0.1, 10 classes): [406 964   0 336   0   0  53   0  17 724]
INFO flwr 2023-08-20 20:22:07,595 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 20:22:10,100	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-20 20:22:11,681 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'CPU': 18.0, 'accelerator_type:A100': 1.0, 'node:145.136.62.62': 1.0}
INFO flwr 2023-08-20 20:22:11,681 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 20:22:11,681 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 20:22:11,681 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 20:22:26,291 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-20 20:22:26,292 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 20:22:29,758 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1155594)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1155589)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:23:54,186 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-20 20:23:54,293 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-20 20:23:54,388 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1155589)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1155595)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1155590)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1155521)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1155593)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1155594)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1155596)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1155597)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1155595)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1155593)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1155597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1155590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1155521)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1155596)[0m double free or corruption (fasttop)
E0820 20:23:58.394880420 1338474 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-20 20:25:17,431 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:25:17,432 | fed_df.py:547 | Average fusion training loss : 0.011827951229643077, val accuracy : 0.2359, best val accuracy : 0.2608
INFO flwr 2023-08-20 20:25:17,433 | common.py:35 | Avg. local train loss : 4.237981427647173, train acc : 0.8333319444444445
INFO flwr 2023-08-20 20:25:19,897 | server.py:116 | fit progress: (1, 2.0666628540039063, {'server_test_acc': 0.2678}, 173.6056829309091)
INFO flwr 2023-08-20 20:25:19,898 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 20:25:23,283 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1492623)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:26:47,067 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1492629)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:26:47,211 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1492621)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1492627)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1492629)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1492623)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1492628)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1492624)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1492625)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1492626)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1492628)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1492621)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1492624)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1492626)[0m corrupted size vs. prev_size in fastbins
E0820 20:26:48.134996940 1340773 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=1492627)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1492625)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:28:10,163 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:28:10,164 | fed_df.py:547 | Average fusion training loss : 0.02560914094373584, val accuracy : 0.23596, best val accuracy : 0.2416
INFO flwr 2023-08-20 20:28:10,165 | common.py:35 | Avg. local train loss : 3.7832491751760244, train acc : 0.8792930555555557
INFO flwr 2023-08-20 20:28:12,662 | server.py:116 | fit progress: (2, 2.5896642639160157, {'server_test_acc': 0.2315}, 346.37022160878405)
INFO flwr 2023-08-20 20:28:12,662 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 20:28:15,997 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1826201)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1826131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1826275)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:29:37,871 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-20 20:29:38,014 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1826131)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1826201)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1826203)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1826274)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1826272)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1826275)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1826202)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1826273)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1826202)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1826272)[0m malloc_consolidate(): invalid chunk size
E0820 20:29:38.489231998 2001073 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=1826274)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1826273)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1826203)[0m malloc_consolidate(): invalid chunk size
E0820 20:30:06.227674141 2052180 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-20 20:31:02,192 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:31:02,192 | fed_df.py:547 | Average fusion training loss : 0.02835034564882517, val accuracy : 0.25602, best val accuracy : 0.2788
INFO flwr 2023-08-20 20:31:02,193 | common.py:35 | Avg. local train loss : 3.585603880509734, train acc : 0.8975597222222222
INFO flwr 2023-08-20 20:31:04,706 | server.py:116 | fit progress: (3, 1.9889527893066405, {'server_test_acc': 0.2896}, 518.4144236599095)
INFO flwr 2023-08-20 20:31:04,706 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 20:31:08,093 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2162111)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:32:29,595 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-20 20:32:29,738 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2162140)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2162111)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2162139)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2162070)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2162145)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2162143)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2162142)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2162144)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2162143)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2162140)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2162144)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2162139)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2162145)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2162070)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2162142)[0m malloc_consolidate(): invalid chunk size
E0820 20:32:33.786995932 2342101 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-20 20:33:54,227 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:33:54,227 | fed_df.py:547 | Average fusion training loss : 0.01293695240560919, val accuracy : 0.36436, best val accuracy : 0.3856
INFO flwr 2023-08-20 20:33:54,229 | common.py:35 | Avg. local train loss : 3.54298505038023, train acc : 0.9035083333333332
INFO flwr 2023-08-20 20:33:56,749 | server.py:116 | fit progress: (4, 1.849094482421875, {'server_test_acc': 0.3835}, 690.4573549730703)
INFO flwr 2023-08-20 20:33:56,749 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 20:34:00,142 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2526653)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2526650)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2526658)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:35:21,120 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2526657)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:35:21,228 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-20 20:35:21,322 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2526653)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2526650)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2526658)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2526657)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2526668)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2526669)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2526659)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2526660)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2526660)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2526659)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2526668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2526669)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:36:45,617 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:36:45,617 | fed_df.py:547 | Average fusion training loss : 0.01975054752640426, val accuracy : 0.31357999999999997, best val accuracy : 0.3402
INFO flwr 2023-08-20 20:36:45,618 | common.py:35 | Avg. local train loss : 3.567899854667485, train acc : 0.9019319444444444
INFO flwr 2023-08-20 20:36:48,135 | server.py:116 | fit progress: (5, 1.9739566345214843, {'server_test_acc': 0.3368}, 861.8433249518275)
INFO flwr 2023-08-20 20:36:48,135 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 20:36:51,528 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 20:38:12,289 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-20 20:38:12,434 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2861892)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2861894)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2861893)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2861899)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2861898)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2861897)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2861895)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2861896)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2861897)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2861899)[0m double free or corruption (fasttop)
E0820 20:38:12.964744249 2347315 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=2861896)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861894)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2861893)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861895)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861898)[0m double free or corruption (fasttop)
E0820 20:38:38.358161560 3035413 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
E0820 20:38:57.947969318 3084450 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
E0820 20:39:28.353990408 3119891 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-20 20:39:36,806 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:39:36,806 | fed_df.py:547 | Average fusion training loss : 0.011029520359355956, val accuracy : 0.24924, best val accuracy : 0.2662
INFO flwr 2023-08-20 20:39:36,808 | common.py:35 | Avg. local train loss : 3.432229597307742, train acc : 0.9152236111111111
INFO flwr 2023-08-20 20:39:39,325 | server.py:116 | fit progress: (6, 2.0704108947753905, {'server_test_acc': 0.2704}, 1033.0329953329638)
INFO flwr 2023-08-20 20:39:39,325 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 20:39:42,700 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3197960)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:41:02,841 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-20 20:41:02,986 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3197964)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3197960)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3197887)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3197963)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3197961)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3197965)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3197962)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3197959)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3197961)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3197963)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3197962)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3197965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3197964)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3197887)[0m malloc_consolidate(): invalid chunk size
E0820 20:41:04.764350857 3174823 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3197959)[0m double free or corruption (fasttop)
E0820 20:41:08.705358715 3380381 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
E0820 20:41:33.994499294 3427361 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-20 20:42:28,220 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:42:28,220 | fed_df.py:547 | Average fusion training loss : 0.011850832268595695, val accuracy : 0.3123, best val accuracy : 0.3388
INFO flwr 2023-08-20 20:42:28,221 | common.py:35 | Avg. local train loss : 3.486211290769279, train acc : 0.9131541666666667
INFO flwr 2023-08-20 20:42:30,729 | server.py:116 | fit progress: (7, 1.8892552642822265, {'server_test_acc': 0.332}, 1204.4375155670568)
INFO flwr 2023-08-20 20:42:30,729 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 20:42:34,114 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 20:43:54,058 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3533689)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:43:54,204 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3533618)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3533620)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3533692)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3533690)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3533619)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3533691)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3533689)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3533637)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3533690)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533619)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3533691)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3533618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533637)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=3533692)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533620)[0m malloc_consolidate(): invalid chunk size
E0820 20:43:56.305048667 3428191 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
E0820 20:44:09.421099032 3734502 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-20 20:45:18,615 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:45:18,615 | fed_df.py:547 | Average fusion training loss : 0.010732374280691147, val accuracy : 0.42588, best val accuracy : 0.4406
INFO flwr 2023-08-20 20:45:18,617 | common.py:35 | Avg. local train loss : 3.5619719196110964, train acc : 0.9060833333333334
INFO flwr 2023-08-20 20:45:21,132 | server.py:116 | fit progress: (8, 1.722602719116211, {'server_test_acc': 0.4356}, 1374.8401719317771)
INFO flwr 2023-08-20 20:45:21,132 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 20:45:24,527 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3867979)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:46:44,874 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3867907)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:46:45,019 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3867870)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3867908)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3867905)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3867976)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3867977)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3867907)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3867979)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3867978)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3867978)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3867908)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3867905)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3867977)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3867870)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3867976)[0m malloc_consolidate(): invalid chunk size
E0820 20:46:47.362614962 3735173 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0820 20:47:35.717786569 4133169 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0820 20:48:00.435624854 4134810 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 20:48:09,834 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:48:09,835 | fed_df.py:547 | Average fusion training loss : 0.011806575316935778, val accuracy : 0.39827999999999997, best val accuracy : 0.4054
INFO flwr 2023-08-20 20:48:09,836 | common.py:35 | Avg. local train loss : 3.32929311171174, train acc : 0.9283125
INFO flwr 2023-08-20 20:48:12,367 | server.py:116 | fit progress: (9, 1.881831707763672, {'server_test_acc': 0.4058}, 1546.075603529811)
INFO flwr 2023-08-20 20:48:12,367 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 20:48:15,772 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=13692)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13683)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:49:36,822 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-20 20:49:36,927 | fed_df.py:365 | Warm start at round 10
[2m[36m(launch_and_fit pid=13703)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:49:37,021 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=13692)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=13702)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=13670)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=13701)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=13697)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=13703)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=13683)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=13700)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=13670)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=13701)[0m double free or corruption (fasttop)
E0820 20:49:38.889712785 4178728 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 20:50:06.089931798  265460 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 20:51:01,956 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:51:01,957 | fed_df.py:547 | Average fusion training loss : 0.016950119828805326, val accuracy : 0.33022, best val accuracy : 0.3486
INFO flwr 2023-08-20 20:51:01,958 | common.py:35 | Avg. local train loss : 3.4997765781357884, train acc : 0.9133
INFO flwr 2023-08-20 20:51:04,520 | server.py:116 | fit progress: (10, 1.9016169006347656, {'server_test_acc': 0.3663}, 1718.2279351740144)
INFO flwr 2023-08-20 20:51:04,520 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 20:51:07,918 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=375016)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:52:27,144 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=375005)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:52:27,288 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=375016)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=375005)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=375017)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=375020)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=375018)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=375021)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=375006)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=375019)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=375018)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=375021)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=375019)[0m malloc_consolidate(): invalid chunk size
E0820 20:52:28.386544801  266498 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=375020)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=375017)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=375006)[0m malloc_consolidate(): invalid chunk size
E0820 20:52:29.310654070  543598 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 20:52:41.398513946  571893 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 20:53:11.741573392  572426 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 20:53:52,334 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:53:52,334 | fed_df.py:547 | Average fusion training loss : 0.009599908391479403, val accuracy : 0.34386, best val accuracy : 0.3526
INFO flwr 2023-08-20 20:53:52,335 | common.py:35 | Avg. local train loss : 3.379402869753539, train acc : 0.9204291666666666
INFO flwr 2023-08-20 20:53:54,895 | server.py:116 | fit progress: (11, 1.9823665466308593, {'server_test_acc': 0.3459}, 1888.6037916820496)
INFO flwr 2023-08-20 20:53:54,896 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 20:53:58,296 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 20:55:18,115 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 20:55:18,261 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=709264)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=709262)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=709261)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=709263)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=709257)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=709260)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=709258)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=709259)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=709264)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=709258)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=709263)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=709259)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=709257)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=709262)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=709260)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=709261)[0m malloc_consolidate(): invalid chunk size
E0820 20:55:20.693180576  627861 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 20:56:43,615 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:56:43,615 | fed_df.py:547 | Average fusion training loss : 0.007326892124954611, val accuracy : 0.39462, best val accuracy : 0.4028
INFO flwr 2023-08-20 20:56:43,616 | common.py:35 | Avg. local train loss : 3.190218062326312, train acc : 0.9400902777777778
INFO flwr 2023-08-20 20:56:46,123 | server.py:116 | fit progress: (12, 1.9527618225097656, {'server_test_acc': 0.3995}, 2059.8317291457206)
INFO flwr 2023-08-20 20:56:46,124 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 20:56:49,501 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1044866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1044796)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:58:10,338 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1044792)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:58:10,485 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1044795)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1044866)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1044865)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1044792)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1044794)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1044796)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1044864)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1044793)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1044865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1044864)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1044794)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1044793)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1044795)[0m double free or corruption (fasttop)
E0820 20:58:13.500544974  879811 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 20:59:36,320 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:59:36,321 | fed_df.py:547 | Average fusion training loss : 0.005626511669717729, val accuracy : 0.38294, best val accuracy : 0.3992
INFO flwr 2023-08-20 20:59:36,322 | common.py:35 | Avg. local train loss : 3.4345963725820186, train acc : 0.9179541666666667
INFO flwr 2023-08-20 20:59:38,842 | server.py:116 | fit progress: (13, 1.9700646728515625, {'server_test_acc': 0.3874}, 2232.550440222025)
INFO flwr 2023-08-20 20:59:38,842 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 20:59:42,247 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1383410)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1383552)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:01:01,375 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-20 21:01:01,519 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1383410)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1383480)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1383481)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1383482)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1383551)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1383479)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1383535)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1383552)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1383479)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1383551)[0m malloc_consolidate(): invalid chunk size
E0820 21:01:02.580882919 1218944 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1383480)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1383482)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1383481)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1383535)[0m double free or corruption (fasttop)
E0820 21:02:04.878221045 1550441 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:02:27,595 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:02:27,596 | fed_df.py:547 | Average fusion training loss : 0.022102211436256767, val accuracy : 0.30988000000000004, best val accuracy : 0.331
INFO flwr 2023-08-20 21:02:27,597 | common.py:35 | Avg. local train loss : 3.488174138590693, train acc : 0.9109083333333333
INFO flwr 2023-08-20 21:02:30,143 | server.py:116 | fit progress: (14, 2.038236590576172, {'server_test_acc': 0.3299}, 2403.8512106677517)
INFO flwr 2023-08-20 21:02:30,143 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 21:02:33,534 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1719458)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1719387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1719460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1719388)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1719389)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:03:53,897 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-20 21:03:54,004 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 21:03:54,100 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1719387)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1719460)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1719388)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1719458)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1719389)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1719459)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1719386)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1719457)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1719459)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1719457)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1719386)[0m malloc_consolidate(): invalid chunk size
E0820 21:03:55.991977609 1889425 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:05:20,821 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:05:20,822 | fed_df.py:547 | Average fusion training loss : 0.03144941597804427, val accuracy : 0.28896, best val accuracy : 0.3046
INFO flwr 2023-08-20 21:05:20,823 | common.py:35 | Avg. local train loss : 3.5729774042963984, train acc : 0.9029819444444444
INFO flwr 2023-08-20 21:05:23,331 | server.py:116 | fit progress: (15, 2.1350074462890625, {'server_test_acc': 0.2979}, 2577.0392711837776)
INFO flwr 2023-08-20 21:05:23,331 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 21:05:26,728 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2085095)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2084994)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2084993)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:06:46,468 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 21:06:46,613 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2085072)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2084994)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2085073)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2085075)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2085095)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2085096)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2084992)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2084993)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2085075)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2084992)[0m double free or corruption (fasttop)
E0820 21:06:47.136536766 1890804 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2085072)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2085096)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2085073)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:08:11,938 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:08:11,939 | fed_df.py:547 | Average fusion training loss : 0.022140688244253397, val accuracy : 0.27714, best val accuracy : 0.292
INFO flwr 2023-08-20 21:08:11,940 | common.py:35 | Avg. local train loss : 3.34681981485337, train acc : 0.9262861111111113
INFO flwr 2023-08-20 21:08:14,467 | server.py:116 | fit progress: (16, 2.1321518310546876, {'server_test_acc': 0.2944}, 2748.1754106921144)
INFO flwr 2023-08-20 21:08:14,467 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 21:08:17,954 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2415517)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:09:37,442 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 21:09:37,586 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2415502)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2415517)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2415504)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2415515)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2415503)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2415518)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2415514)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2415516)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2415502)[0m double free or corruption (fasttop)
E0820 21:09:38.086517234 2249634 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2415518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2415514)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2415504)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2415503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2415516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2415515)[0m malloc_consolidate(): invalid chunk size
E0820 21:09:39.382341859 2575716 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:09:45.282192157 2591383 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:11:03,813 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:11:03,813 | fed_df.py:547 | Average fusion training loss : 0.007776092901825905, val accuracy : 0.3611, best val accuracy : 0.374
INFO flwr 2023-08-20 21:11:03,815 | common.py:35 | Avg. local train loss : 3.428904416039586, train acc : 0.9213625000000001
INFO flwr 2023-08-20 21:11:06,335 | server.py:116 | fit progress: (17, 1.9768064819335938, {'server_test_acc': 0.3656}, 2920.043332940899)
INFO flwr 2023-08-20 21:11:06,335 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 21:11:09,740 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2750893)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:12:29,977 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 21:12:30,124 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2750893)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2750891)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2750894)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2750892)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2750962)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2750963)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2750965)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2750964)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2750892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2750962)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2750964)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2750965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2750963)[0m double free or corruption (fasttop)
E0820 21:12:31.242574799 2739375 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2750891)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2750894)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:13:55,380 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:13:55,380 | fed_df.py:547 | Average fusion training loss : 0.005531456395518035, val accuracy : 0.37046, best val accuracy : 0.3884
INFO flwr 2023-08-20 21:13:55,381 | common.py:35 | Avg. local train loss : 3.2808118887245654, train acc : 0.9336625
INFO flwr 2023-08-20 21:13:57,931 | server.py:116 | fit progress: (18, 1.9421542541503907, {'server_test_acc': 0.3827}, 3091.6396839260124)
INFO flwr 2023-08-20 21:13:57,932 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 21:14:01,348 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3086047)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3086124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3086041)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3086122)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3086040)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:15:22,387 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3086123)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:15:22,532 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3086041)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3086047)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3086040)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3086122)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3086123)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3086124)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3086045)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3086046)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3086046)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3086045)[0m malloc_consolidate(): invalid chunk size
E0820 21:15:27.007614960 3255347 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:15:41.919794197 3256308 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:16:48,334 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:16:48,334 | fed_df.py:547 | Average fusion training loss : 0.0033523565316572784, val accuracy : 0.3731400000000001, best val accuracy : 0.392
INFO flwr 2023-08-20 21:16:48,335 | common.py:35 | Avg. local train loss : 3.1752589739859105, train acc : 0.9438069444444445
INFO flwr 2023-08-20 21:16:50,878 | server.py:116 | fit progress: (19, 1.8647386291503907, {'server_test_acc': 0.3916}, 3264.5862219999544)
INFO flwr 2023-08-20 21:16:50,878 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 21:16:54,278 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3422502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3422571)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:18:14,007 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 21:18:14,113 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-20 21:18:14,208 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3422571)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3422501)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3422574)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3422502)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3422644)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3422573)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3422632)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3422643)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3422632)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3422573)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3422643)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3422644)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3422501)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3422574)[0m malloc_consolidate(): invalid chunk size
E0820 21:18:16.777513150 3583915 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:19:40,684 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:19:40,684 | fed_df.py:547 | Average fusion training loss : 0.014183780553750695, val accuracy : 0.34286000000000005, best val accuracy : 0.3572
INFO flwr 2023-08-20 21:19:40,686 | common.py:35 | Avg. local train loss : 3.3751570532098416, train acc : 0.9274736111111112
INFO flwr 2023-08-20 21:19:43,243 | server.py:116 | fit progress: (20, 2.065842279052734, {'server_test_acc': 0.3585}, 3436.9513094327413)
INFO flwr 2023-08-20 21:19:43,243 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 21:19:46,821 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3763722)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:21:06,318 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 21:21:06,464 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3763615)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3763492)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3763611)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3763472)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3763610)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3763722)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3763687)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3763721)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3763615)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3763472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3763721)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3763610)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3763687)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3763611)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3763492)[0m malloc_consolidate(): invalid chunk size
E0820 21:21:08.942942106 3946387 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:22:32,694 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:22:32,695 | fed_df.py:547 | Average fusion training loss : 0.0036963957329280675, val accuracy : 0.34736, best val accuracy : 0.359
INFO flwr 2023-08-20 21:22:32,696 | common.py:35 | Avg. local train loss : 3.486986111104488, train acc : 0.9171069444444445
E0820 21:22:34.213486399 4113430 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:22:35,240 | server.py:116 | fit progress: (21, 2.171424401855469, {'server_test_acc': 0.362}, 3608.9487132020295)
INFO flwr 2023-08-20 21:22:35,241 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 21:22:38,628 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4121179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4121261)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4121177)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4121262)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:23:58,372 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4121259)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:23:58,518 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4121177)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4121179)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4121259)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4121261)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4121270)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4121266)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4121262)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4121263)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4121266)[0m double free or corruption (fasttop)
E0820 21:23:59.409215481 4114783 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4121270)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4121263)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 21:25:25,249 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:25:25,250 | fed_df.py:547 | Average fusion training loss : 0.002607651243451983, val accuracy : 0.44048, best val accuracy : 0.4578
INFO flwr 2023-08-20 21:25:25,251 | common.py:35 | Avg. local train loss : 3.5145784551277752, train acc : 0.9170222222222222
INFO flwr 2023-08-20 21:25:27,777 | server.py:116 | fit progress: (22, 2.100901745605469, {'server_test_acc': 0.4525}, 3781.4856772497296)
INFO flwr 2023-08-20 21:25:27,778 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 21:25:31,167 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=263619)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:26:50,653 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=263722)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:26:50,798 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=263619)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=263713)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=263722)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=263700)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=263724)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=263721)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=263723)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=263698)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=263721)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=263713)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=263700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=263698)[0m corrupted size vs. prev_size in fastbins
E0820 21:26:52.133410132   84333 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=263724)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=263723)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:28:18,953 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:28:18,954 | fed_df.py:547 | Average fusion training loss : 0.002610481736948714, val accuracy : 0.44294, best val accuracy : 0.4502
INFO flwr 2023-08-20 21:28:18,955 | common.py:35 | Avg. local train loss : 3.2651833569630986, train acc : 0.9398513888888888
INFO flwr 2023-08-20 21:28:21,487 | server.py:116 | fit progress: (23, 2.0639463134765625, {'server_test_acc': 0.452}, 3955.1950151771307)
INFO flwr 2023-08-20 21:28:21,487 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 21:28:24,895 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=599428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=599426)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:29:45,008 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-20 21:29:45,157 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=599356)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=599354)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=599355)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=599425)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=599426)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=599427)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=599428)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=599357)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=599427)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=599354)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=599356)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=599355)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=599357)[0m malloc_consolidate(): invalid chunk size
E0820 21:29:46.610471047  753580 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:31:11,604 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:31:11,605 | fed_df.py:547 | Average fusion training loss : 0.0026294376362347976, val accuracy : 0.35609999999999997, best val accuracy : 0.3672
INFO flwr 2023-08-20 21:31:11,606 | common.py:35 | Avg. local train loss : 3.454691525176167, train acc : 0.9192611111111112
INFO flwr 2023-08-20 21:31:14,138 | server.py:116 | fit progress: (24, 2.1028648803710936, {'server_test_acc': 0.3529}, 4127.846400354058)
INFO flwr 2023-08-20 21:31:14,138 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 21:31:17,630 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 21:32:37,294 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-20 21:32:37,402 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-20 21:32:37,498 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=933637)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=933778)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=933635)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=933707)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=933708)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=933779)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=933710)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=933709)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=933707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=933778)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=933709)[0m malloc_consolidate(): invalid chunk size
E0820 21:32:38.359452352  754147 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=933779)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=933637)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=933635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=933710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=933708)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 21:34:03,700 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:34:03,700 | fed_df.py:547 | Average fusion training loss : 0.003355259313597344, val accuracy : 0.4262, best val accuracy : 0.4508
INFO flwr 2023-08-20 21:34:03,701 | common.py:35 | Avg. local train loss : 3.452803988009691, train acc : 0.9215930555555557
INFO flwr 2023-08-20 21:34:06,249 | server.py:116 | fit progress: (25, 2.1089309143066406, {'server_test_acc': 0.445}, 4299.957210605964)
INFO flwr 2023-08-20 21:34:06,249 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 21:34:09,654 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1270653)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1270655)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:35:28,944 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-20 21:35:29,088 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1270726)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1270723)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1270724)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1270725)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1270655)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1270727)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1270653)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1270654)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1270725)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1270724)[0m malloc_consolidate(): invalid chunk size
E0820 21:35:30.229941951 1430359 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1270727)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1270726)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1270654)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1270723)[0m malloc_consolidate(): invalid chunk size
E0820 21:35:47.214635710 1474199 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:36:11.927140244 1534863 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:36:56,142 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:36:56,142 | fed_df.py:547 | Average fusion training loss : 0.003248690820299089, val accuracy : 0.40396, best val accuracy : 0.4152
INFO flwr 2023-08-20 21:36:56,144 | common.py:35 | Avg. local train loss : 3.5374265490099788, train acc : 0.9162208333333332
INFO flwr 2023-08-20 21:36:58,706 | server.py:116 | fit progress: (26, 2.079850177001953, {'server_test_acc': 0.4139}, 4472.414288619999)
INFO flwr 2023-08-20 21:36:58,706 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 21:37:02,114 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1634915)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1634918)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:38:22,107 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 21:38:22,252 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1634917)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1634918)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1634916)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1634847)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1634915)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1634779)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1634919)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1634920)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1634917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1634779)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1634916)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1634919)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1634920)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1634847)[0m malloc_consolidate(): invalid chunk size
E0820 21:38:24.260515994 1785467 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:39:50,054 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:39:50,054 | fed_df.py:547 | Average fusion training loss : 0.0022418795003322886, val accuracy : 0.40902000000000005, best val accuracy : 0.42
INFO flwr 2023-08-20 21:39:50,056 | common.py:35 | Avg. local train loss : 3.4070973856374622, train acc : 0.9258152777777776
INFO flwr 2023-08-20 21:39:52,596 | server.py:116 | fit progress: (27, 2.0360279357910156, {'server_test_acc': 0.4154}, 4646.304630525876)
INFO flwr 2023-08-20 21:39:52,596 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 21:39:56,012 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1968327)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1968398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1968324)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1968396)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1968326)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:41:16,620 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-20 21:41:16,764 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1968324)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1968327)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1968326)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1968398)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1968395)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1968396)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1968399)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1968397)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1968399)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1968397)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1968395)[0m malloc_consolidate(): invalid chunk size
E0820 21:41:20.886854207 1785754 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:41:43.314501269 2126437 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:42:43,665 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:42:43,666 | fed_df.py:547 | Average fusion training loss : 0.0022449784867931157, val accuracy : 0.42623999999999995, best val accuracy : 0.4416
INFO flwr 2023-08-20 21:42:43,667 | common.py:35 | Avg. local train loss : 3.279538024403155, train acc : 0.9385597222222222
INFO flwr 2023-08-20 21:42:46,241 | server.py:116 | fit progress: (28, 1.9584291137695313, {'server_test_acc': 0.4436}, 4819.949827938806)
INFO flwr 2023-08-20 21:42:46,242 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-20 21:42:49,666 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2303587)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:44:08,784 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-20 21:44:08,931 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2303725)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2303727)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2303587)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2303726)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2303656)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2303728)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2303585)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2303657)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2303725)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2303728)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2303585)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2303726)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2303657)[0m double free or corruption (fasttop)
E0820 21:44:10.667947717 2176790 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2303656)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2303727)[0m malloc_consolidate(): invalid chunk size
E0820 21:44:18.976700488 2453369 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:45:37,006 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:45:37,007 | fed_df.py:547 | Average fusion training loss : 0.0048112534747924655, val accuracy : 0.32182, best val accuracy : 0.333
INFO flwr 2023-08-20 21:45:37,008 | common.py:35 | Avg. local train loss : 3.3267972351983186, train acc : 0.9331416666666666
INFO flwr 2023-08-20 21:45:39,552 | server.py:116 | fit progress: (29, 1.9998167358398438, {'server_test_acc': 0.3323}, 4993.259890083689)
INFO flwr 2023-08-20 21:45:39,552 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 21:45:42,948 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2639111)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639113)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639254)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:47:02,226 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 21:47:02,333 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 21:47:02,427 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2639111)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2639184)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2639113)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2639135)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2639183)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2639253)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2639252)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2639254)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2639183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639184)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639252)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639253)[0m malloc_consolidate(): invalid chunk size
E0820 21:47:05.002453443 2472002 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:47:40.036718328 2866956 chttp2_transport.cc:1079]             ipv4:145.136.62.62:56607: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:48:30,409 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:48:30,409 | fed_df.py:547 | Average fusion training loss : 0.008708959565032273, val accuracy : 0.3326, best val accuracy : 0.3436
INFO flwr 2023-08-20 21:48:30,410 | common.py:35 | Avg. local train loss : 3.474581086449325, train acc : 0.9177555555555557
INFO flwr 2023-08-20 21:48:32,941 | server.py:116 | fit progress: (30, 2.083012976074219, {'server_test_acc': 0.332}, 5166.649141225964)
INFO flwr 2023-08-20 21:48:32,941 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 21:48:32,941 | server.py:144 | FL finished in 5166.64947989909
INFO flwr 2023-08-20 21:48:32,941 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 21:48:32,942 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 21:48:32,942 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 2.0666628540039063), (2, 2.5896642639160157), (3, 1.9889527893066405), (4, 1.849094482421875), (5, 1.9739566345214843), (6, 2.0704108947753905), (7, 1.8892552642822265), (8, 1.722602719116211), (9, 1.881831707763672), (10, 1.9016169006347656), (11, 1.9823665466308593), (12, 1.9527618225097656), (13, 1.9700646728515625), (14, 2.038236590576172), (15, 2.1350074462890625), (16, 2.1321518310546876), (17, 1.9768064819335938), (18, 1.9421542541503907), (19, 1.8647386291503907), (20, 2.065842279052734), (21, 2.171424401855469), (22, 2.100901745605469), (23, 2.0639463134765625), (24, 2.1028648803710936), (25, 2.1089309143066406), (26, 2.079850177001953), (27, 2.0360279357910156), (28, 1.9584291137695313), (29, 1.9998167358398438), (30, 2.083012976074219)]
INFO flwr 2023-08-20 21:48:32,943 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.2678), (2, 0.2315), (3, 0.2896), (4, 0.3835), (5, 0.3368), (6, 0.2704), (7, 0.332), (8, 0.4356), (9, 0.4058), (10, 0.3663), (11, 0.3459), (12, 0.3995), (13, 0.3874), (14, 0.3299), (15, 0.2979), (16, 0.2944), (17, 0.3656), (18, 0.3827), (19, 0.3916), (20, 0.3585), (21, 0.362), (22, 0.4525), (23, 0.452), (24, 0.3529), (25, 0.445), (26, 0.4139), (27, 0.4154), (28, 0.4436), (29, 0.3323), (30, 0.332)]}
double free or corruption (fasttop)
srun: error: gcn62: task 0: Aborted
srun: Terminating StepId=3429397.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3429397
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 02:56:23
CPU Efficiency: 11.14% of 1-02:23:06 core-walltime
Job Wall-clock time: 01:27:57
Memory Utilized: 49.85 GB
Memory Efficiency: 41.54% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
