-----BEGIN-----
-----SETTINGS-----
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:pathmnist
PARTITION_ALPHA:10.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.05
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:colonpath_sample.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:50
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.5
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:True
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/colonpath_sample.jpg', targetpath='/scratch-local/sunnys.3203533/1690968061_265907000', seed=42, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3203533/1690968061_265907000/single_img_crops/crops
100000 took 1.36min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-02 11:22:38,533 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-02 11:22:38,533 | simulate.py:55 | Reading args from argument parser
Downloading https://zenodo.org/record/6496656/files/pathmnist.npz?download=1 to /scratch-local/sunnys.3203533/1690968061_265907000/pathmnist.npz
Generating unified pathmnist dataset
Class histogram for 0-th partition (alpha=10.0, 9 classes): [490 604 231 501 464 620 475 540 575]
INFO flwr 2023-08-02 11:23:51,553 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-02 11:23:54,330	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-02 11:23:55,335 | app.py:179 | Flower VCE: Ray initialized with resources: {'object_store_memory': 61847529062.0, 'GPU': 1.0, 'CPU': 18.0, 'memory': 103079215104.0, 'node:145.136.62.67': 1.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-02 11:23:55,335 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-02 11:23:55,336 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-02 11:23:55,336 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-02 11:24:01,228 | server.py:91 | initial parameters (loss, other metrics): 2.1845225108367154, {'server_test_acc': 0.11030640668523677}
INFO flwr 2023-08-02 11:24:01,228 | server.py:101 | FL starting
DEBUG flwr 2023-08-02 11:24:09,948 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=770390)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=770394)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:25:08,681 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-02 11:25:08,901 | fed_df.py:351 | Warm start at round 1
INFO flwr 2023-08-02 11:25:09,013 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=770392)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=770397)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=770391)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=770390)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=770396)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=770394)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=770398)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=770395)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=770392)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=770396)[0m malloc_consolidate(): invalid chunk size
E0802 11:25:09.881833696  874994 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=770398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=770391)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=770395)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=770397)[0m double free or corruption (fasttop)
E0802 11:25:11.103186375  876503 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-02 11:25:40,345 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:25:40,346 | fed_df.py:523 | Average fusion training loss : 0.5297561111450195, val accuracy : 0.39124055135615826, best val accuracy : 0.40673632725655845
Average local training loss : 9.861865033209323
Average local training accuracy : 0.6195817901234567
INFO flwr 2023-08-02 11:25:41,243 | server.py:116 | fit progress: (1, 5.298423531194915, {'server_test_acc': 0.42590529247910863}, 100.01480874908157)
INFO flwr 2023-08-02 11:25:41,243 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-02 11:25:50,460 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=912707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=912705)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:26:42,857 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=912712)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:26:43,078 | fed_df.py:351 | Warm start at round 2
INFO flwr 2023-08-02 11:26:43,203 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=912707)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=912705)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=912711)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=912709)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=912710)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=912718)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=912712)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=912719)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=912718)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=912709)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=912719)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=912711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=912710)[0m malloc_consolidate(): invalid chunk size
E0802 11:26:45.644952450  876738 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-02 11:27:16,942 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:27:16,943 | fed_df.py:523 | Average fusion training loss : 0.5123224099874496, val accuracy : 0.4728323699421965, best val accuracy : 0.5003334815473544
Average local training loss : 8.237321319431066
Average local training accuracy : 0.7146898148148149
INFO flwr 2023-08-02 11:27:17,846 | server.py:116 | fit progress: (2, 6.283704598301965, {'server_test_acc': 0.38662952646239557}, 196.61736378306523)
INFO flwr 2023-08-02 11:27:17,846 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-02 11:27:27,266 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1041148)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1041279)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:28:19,291 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-02 11:28:19,512 | fed_df.py:351 | Warm start at round 3
INFO flwr 2023-08-02 11:28:19,623 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1041148)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1041279)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1041283)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1041281)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1041284)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1041287)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1041285)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1041286)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1041281)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1041285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1041284)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1041287)[0m malloc_consolidate(): invalid chunk size
E0802 11:28:20.814883448 1100180 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=1041283)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1041286)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:28:54,082 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:28:54,083 | fed_df.py:523 | Average fusion training loss : 0.5418135366439819, val accuracy : 0.4753445975989329, best val accuracy : 0.5011116051578479
Average local training loss : 8.012704960256814
Average local training accuracy : 0.7291820987654323
INFO flwr 2023-08-02 11:28:54,983 | server.py:116 | fit progress: (3, 3.847280095347455, {'server_test_acc': 0.5013927576601671}, 293.7546076870058)
INFO flwr 2023-08-02 11:28:54,983 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-02 11:29:04,535 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1166203)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:29:56,794 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-02 11:29:57,015 | fed_df.py:351 | Warm start at round 4
[2m[36m(launch_and_fit pid=1166278)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:29:57,127 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1166199)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1166204)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1166203)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1166201)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1166202)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1166278)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1166279)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1166280)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1166202)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1166204)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1166280)[0m malloc_consolidate(): invalid chunk size
E0802 11:29:58.650276764 1101033 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=1166279)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1166201)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:30:32,629 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:30:32,630 | fed_df.py:523 | Average fusion training loss : 0.5245648684501648, val accuracy : 0.5572476656291685, best val accuracy : 0.630613606047132
Average local training loss : 7.101180407404899
Average local training accuracy : 0.7874151234567902
INFO flwr 2023-08-02 11:30:33,590 | server.py:116 | fit progress: (4, 4.478048811516722, {'server_test_acc': 0.4967966573816156}, 392.3620492510963)
INFO flwr 2023-08-02 11:30:33,591 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-02 11:30:43,176 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1290776)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:31:36,075 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-02 11:31:36,297 | fed_df.py:351 | Warm start at round 5
[2m[36m(launch_and_fit pid=1290781)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:31:36,410 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1290776)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1290781)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1290784)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1290780)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1290916)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1290915)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1290774)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1290782)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1290916)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290784)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290915)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1290782)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290774)[0m malloc_consolidate(): invalid chunk size
E0802 11:31:38.662655386 1354869 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-02 11:32:11,950 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:32:11,951 | fed_df.py:523 | Average fusion training loss : 0.5263986963033677, val accuracy : 0.5625611382836817, best val accuracy : 0.6174966651845265
Average local training loss : 6.260971781611443
Average local training accuracy : 0.8405987654320988
INFO flwr 2023-08-02 11:32:12,872 | server.py:116 | fit progress: (5, 4.617031377138866, {'server_test_acc': 0.5135097493036211}, 491.64347305404954)
INFO flwr 2023-08-02 11:32:12,872 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-02 11:32:22,571 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1403933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1403935)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:33:15,506 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1403940)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:33:15,727 | fed_df.py:351 | Warm start at round 6
INFO flwr 2023-08-02 11:33:15,839 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1403933)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1403934)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1403940)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1403932)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1403935)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1403954)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1403947)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1403955)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1403932)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1403954)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1403934)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1403955)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1403947)[0m double free or corruption (fasttop)
E0802 11:33:18.151157406 1484311 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-02 11:33:49,328 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:33:49,328 | fed_df.py:523 | Average fusion training loss : 0.4753630611896515, val accuracy : 0.6090484659848822, best val accuracy : 0.6681858603823921
Average local training loss : 5.602467956021429
Average local training accuracy : 0.8812098765432101
INFO flwr 2023-08-02 11:33:50,236 | server.py:116 | fit progress: (6, 4.006847188731754, {'server_test_acc': 0.5211699164345404}, 589.007120867027)
INFO flwr 2023-08-02 11:33:50,236 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-02 11:33:59,911 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1514556)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1514555)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:34:55,741 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1514286)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:34:55,962 | fed_df.py:351 | Warm start at round 7
INFO flwr 2023-08-02 11:34:56,071 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1514288)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1514286)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1514553)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1514552)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1514554)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1514557)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1514555)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1514556)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1514553)[0m malloc_consolidate(): invalid chunk size
E0802 11:34:56.853845541 1607630 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1514557)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1514288)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1514554)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1514552)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:35:28,173 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:35:28,173 | fed_df.py:523 | Average fusion training loss : 0.44651333475112914, val accuracy : 0.6210093374833259, best val accuracy : 0.6537349933303691
Average local training loss : 5.43474644832313
Average local training accuracy : 0.8915787037037038
INFO flwr 2023-08-02 11:35:29,115 | server.py:116 | fit progress: (7, 3.6320857239300826, {'server_test_acc': 0.525766016713092}, 687.8865998610854)
INFO flwr 2023-08-02 11:35:29,115 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-02 11:35:38,425 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1644898)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1644897)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:36:31,171 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-02 11:36:31,394 | fed_df.py:351 | Warm start at round 8
INFO flwr 2023-08-02 11:36:31,510 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1644898)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1644902)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1644897)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1644901)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1644894)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1644900)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1644899)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1644903)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1644903)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644902)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1644900)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644901)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644899)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644894)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:37:10,464 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:37:10,464 | fed_df.py:523 | Average fusion training loss : 0.39398153352737425, val accuracy : 0.6293241440640285, best val accuracy : 0.71776345042241
Average local training loss : 5.160374872758984
Average local training accuracy : 0.9091512345679013
INFO flwr 2023-08-02 11:37:11,370 | server.py:116 | fit progress: (8, 3.3341462815372394, {'server_test_acc': 0.7415041782729805}, 790.1412037231494)
INFO flwr 2023-08-02 11:37:11,370 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-02 11:37:20,729 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1760755)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:38:15,125 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-02 11:38:15,348 | fed_df.py:351 | Warm start at round 9
INFO flwr 2023-08-02 11:38:15,459 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1760616)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1760754)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1760755)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1760756)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1760759)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1760760)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1760761)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1760752)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1760616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1760756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1760754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1760760)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1760752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1760759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1760761)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:38:46,860 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:38:46,860 | fed_df.py:523 | Average fusion training loss : 0.40499437487125395, val accuracy : 0.5697198755002224, best val accuracy : 0.6527345486883059
Average local training loss : 4.964534351974725
Average local training accuracy : 0.920516975308642
INFO flwr 2023-08-02 11:38:47,778 | server.py:116 | fit progress: (9, 5.756511477308353, {'server_test_acc': 0.4764623955431755}, 886.5498218489811)
INFO flwr 2023-08-02 11:38:47,778 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-02 11:38:57,172 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:39:49,159 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-02 11:39:49,381 | fed_df.py:351 | Warm start at round 10
INFO flwr 2023-08-02 11:39:49,494 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1882844)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1882842)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1882846)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1882845)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1882850)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1882852)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1882848)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1882847)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1882844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1882846)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1882845)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1882847)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1882852)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1882842)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1882850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1882848)[0m double free or corruption (fasttop)
E0802 11:39:53.371516256 1851117 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
E0802 11:40:11.938321877 1979707 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-02 11:40:22,981 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:40:22,982 | fed_df.py:523 | Average fusion training loss : 0.39562965416908263, val accuracy : 0.5455980435749221, best val accuracy : 0.6024899955535794
Average local training loss : 4.861955092102289
Average local training accuracy : 0.9274737654320988
INFO flwr 2023-08-02 11:40:23,900 | server.py:116 | fit progress: (10, 5.166859208109651, {'server_test_acc': 0.3334261838440111}, 982.6713849860243)
INFO flwr 2023-08-02 11:40:23,900 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-02 11:40:33,318 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2006863)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:41:30,996 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-02 11:41:31,219 | fed_df.py:351 | Warm start at round 11
INFO flwr 2023-08-02 11:41:31,332 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2006823)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2006863)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2006860)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2006862)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2006864)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2006867)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2006865)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2006866)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2006865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2006823)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2006862)[0m malloc_consolidate(): invalid chunk size
E0802 11:41:32.317516566 1980043 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=2006860)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2006864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2006866)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2006867)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:42:04,593 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:42:04,594 | fed_df.py:523 | Average fusion training loss : 0.41565519058704375, val accuracy : 0.6188750555802579, best val accuracy : 0.7000889284126278
Average local training loss : 4.587453248538076
Average local training accuracy : 0.9433657407407408
INFO flwr 2023-08-02 11:42:05,519 | server.py:116 | fit progress: (11, 3.91294124651088, {'server_test_acc': 0.5467966573816156}, 1084.2906324439682)
INFO flwr 2023-08-02 11:42:05,519 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-02 11:42:14,878 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2154867)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:43:07,670 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-02 11:43:07,893 | fed_df.py:351 | Warm start at round 12
INFO flwr 2023-08-02 11:43:08,006 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2154599)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2154734)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2154867)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2154866)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2154865)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2154872)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2154873)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2154733)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2154866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2154873)[0m double free or corruption (fasttop)
E0802 11:43:08.741175300 2220851 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=2154734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2154733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2154865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2154872)[0m double free or corruption (fasttop)
E0802 11:43:12.453004311 2221122 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-02 11:43:40,996 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:43:40,997 | fed_df.py:523 | Average fusion training loss : 0.38463790440559387, val accuracy : 0.5543797243219208, best val accuracy : 0.6050466874166296
Average local training loss : 4.574154725857079
Average local training accuracy : 0.9443842592592592
INFO flwr 2023-08-02 11:43:41,933 | server.py:116 | fit progress: (12, 4.118107672454919, {'server_test_acc': 0.46295264623955434}, 1180.7046392860357)
INFO flwr 2023-08-02 11:43:41,933 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-02 11:43:51,360 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2255105)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:44:46,677 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-02 11:44:46,899 | fed_df.py:351 | Warm start at round 13
INFO flwr 2023-08-02 11:44:47,011 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2255119)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2255106)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2255105)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2255120)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2255254)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2255121)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2255251)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2255123)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2255251)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2255119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2255106)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2255121)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2255254)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2255120)[0m malloc_consolidate(): invalid chunk size
E0802 11:44:48.495207154 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495276632 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495286765 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495295093 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495303135 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495310763 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495318295 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495326026 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495333842 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0802 11:44:48.495341613 2342967 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=2255123)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:45:19,850 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:45:19,850 | fed_df.py:523 | Average fusion training loss : 0.3757632616758347, val accuracy : 0.47730102267674523, best val accuracy : 0.5702534459759894
Average local training loss : 4.366427450068295
Average local training accuracy : 0.956320987654321
INFO flwr 2023-08-02 11:45:20,765 | server.py:116 | fit progress: (13, 2.990864265728794, {'server_test_acc': 0.45306406685236766}, 1279.5364471601788)
INFO flwr 2023-08-02 11:45:20,765 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-02 11:45:30,069 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2389553)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2389475)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2389555)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2389554)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:46:23,127 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-02 11:46:23,347 | fed_df.py:351 | Warm start at round 14
INFO flwr 2023-08-02 11:46:23,458 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2389475)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2389477)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2389483)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2389552)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2389554)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2389484)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2389553)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2389555)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2389483)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2389484)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2389552)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2389477)[0m malloc_consolidate(): invalid chunk size
E0802 11:46:27.106819234 2445081 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0802 11:46:53.254431184 2480926 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-02 11:46:55,828 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:46:55,828 | fed_df.py:523 | Average fusion training loss : 0.3896562126874924, val accuracy : 0.4635615829257448, best val accuracy : 0.5582481102712317
Average local training loss : 4.4032207215204835
Average local training accuracy : 0.9538966049382717
INFO flwr 2023-08-02 11:46:56,726 | server.py:116 | fit progress: (14, 3.909747319234779, {'server_test_acc': 0.45167130919220055}, 1375.4972211080603)
INFO flwr 2023-08-02 11:46:56,726 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-02 11:47:06,223 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:48:00,859 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2495810)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2496084)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:48:01,083 | fed_df.py:351 | Warm start at round 15
[2m[36m(launch_and_fit pid=2496082)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:48:01,196 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2496075)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2495810)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2495943)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2496082)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2495942)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2496075)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2496084)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2496079)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2496081)[0m Fitting Client 19
E0802 11:48:02.277907634 2580687 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2495943)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2495942)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2496081)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2496079)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:48:32,253 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:48:32,253 | fed_df.py:523 | Average fusion training loss : 0.4143220456838608, val accuracy : 0.5002445531347266, best val accuracy : 0.5930413517118719
Average local training loss : 4.234582276083529
Average local training accuracy : 0.9638240740740741
INFO flwr 2023-08-02 11:48:33,129 | server.py:116 | fit progress: (15, 2.9836339453800806, {'server_test_acc': 0.5050139275766017}, 1471.9007038259879)
INFO flwr 2023-08-02 11:48:33,129 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-02 11:48:42,390 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2614053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2614052)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:49:34,501 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-02 11:49:34,723 | fed_df.py:351 | Warm start at round 16
INFO flwr 2023-08-02 11:49:34,837 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2614053)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2614052)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2614056)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2614055)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2614057)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2614059)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2614058)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2614060)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2614058)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2614059)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2614056)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2614060)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2614055)[0m double free or corruption (fasttop)
E0802 11:49:36.128730688 2582639 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2614057)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:50:07,678 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:50:07,679 | fed_df.py:523 | Average fusion training loss : 0.3504072091579437, val accuracy : 0.5457759004001779, best val accuracy : 0.6072698977323254
Average local training loss : 4.20187738891691
Average local training accuracy : 0.9658842592592591
INFO flwr 2023-08-02 11:50:08,580 | server.py:116 | fit progress: (16, 2.707925934114164, {'server_test_acc': 0.500974930362117}, 1567.3514352540951)
INFO flwr 2023-08-02 11:50:08,580 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-02 11:50:17,836 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 11:51:11,171 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-02 11:51:11,393 | fed_df.py:351 | Warm start at round 17
INFO flwr 2023-08-02 11:51:11,509 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2704700)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2704703)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2704704)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2704705)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2704702)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2704706)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2704708)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2704707)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2704702)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2704703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2704705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2704704)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2704708)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2704706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2704707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2704700)[0m malloc_consolidate(): invalid chunk size
E0802 11:51:14.318306671 2775670 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 11:51:49,488 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:51:49,489 | fed_df.py:523 | Average fusion training loss : 0.32003062987327574, val accuracy : 0.5072032014228547, best val accuracy : 0.5495775900400178
Average local training loss : 4.198329480551183
Average local training accuracy : 0.9661388888888888
INFO flwr 2023-08-02 11:51:50,396 | server.py:116 | fit progress: (17, 1.9609930848676846, {'server_test_acc': 0.47311977715877435}, 1669.1674814070575)
INFO flwr 2023-08-02 11:51:50,396 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-02 11:51:59,787 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2820885)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:52:53,157 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2820888)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:52:53,381 | fed_df.py:351 | Warm start at round 18
INFO flwr 2023-08-02 11:52:53,493 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2820880)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2820885)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2820891)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2820886)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2820884)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2820889)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2820890)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2820888)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2820880)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2820891)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2820884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2820889)[0m double free or corruption (fasttop)
E0802 11:52:54.750208626 2776882 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2820886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2820890)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:53:25,582 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:53:25,583 | fed_df.py:523 | Average fusion training loss : 0.366733194231987, val accuracy : 0.5251000444642063, best val accuracy : 0.5763672743441529
Average local training loss : 4.171949446760118
Average local training accuracy : 0.967783950617284
INFO flwr 2023-08-02 11:53:26,487 | server.py:116 | fit progress: (18, 2.2688284015921165, {'server_test_acc': 0.49428969359331476}, 1765.258727913024)
INFO flwr 2023-08-02 11:53:26,487 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-02 11:53:35,976 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2927666)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:54:27,625 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-02 11:54:27,848 | fed_df.py:351 | Warm start at round 19
INFO flwr 2023-08-02 11:54:27,971 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2927666)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2927669)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2927738)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2927739)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2927716)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2927742)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2927741)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2927740)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2927738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2927741)[0m malloc_consolidate(): invalid chunk size
E0802 11:54:28.496188776 2982933 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2927669)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2927716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2927742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2927740)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2927739)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:55:01,131 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:55:01,132 | fed_df.py:523 | Average fusion training loss : 0.36835637521743775, val accuracy : 0.5396843041351712, best val accuracy : 0.6012672298799466
Average local training loss : 4.175783608295023
Average local training accuracy : 0.9679182098765432
INFO flwr 2023-08-02 11:55:02,038 | server.py:116 | fit progress: (19, 2.253201657882308, {'server_test_acc': 0.5591922005571031}, 1860.8096652249806)
INFO flwr 2023-08-02 11:55:02,038 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-02 11:55:11,510 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3028696)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:56:06,935 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3028967)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3028966)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3028964)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:56:07,161 | fed_df.py:351 | Warm start at round 20
INFO flwr 2023-08-02 11:56:07,274 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3028696)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3028963)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3028695)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3028968)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3028967)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3028966)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3028962)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3028964)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3028695)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3028963)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3028962)[0m malloc_consolidate(): invalid chunk size
E0802 11:56:08.302293045 3125358 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3028968)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:56:40,023 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:56:40,024 | fed_df.py:523 | Average fusion training loss : 0.3708106776475906, val accuracy : 0.5095820364606493, best val accuracy : 0.5423521565140063
Average local training loss : 4.155366064235569
Average local training accuracy : 0.9691172839506174
INFO flwr 2023-08-02 11:56:40,929 | server.py:116 | fit progress: (20, 1.9987182000885435, {'server_test_acc': 0.5086350974930363}, 1959.7010625931434)
INFO flwr 2023-08-02 11:56:40,930 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-02 11:56:50,289 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3161707)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3161711)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 11:57:42,677 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3161713)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:57:42,901 | fed_df.py:351 | Warm start at round 21
[2m[36m(launch_and_fit pid=3161712)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:57:43,017 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3161697)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3161708)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3161707)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3161709)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3161710)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3161713)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3161712)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3161711)[0m Fitting Client 3
E0802 11:57:43.584628267 3125694 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3161709)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3161697)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3161708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3161710)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:58:20,070 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:58:20,070 | fed_df.py:523 | Average fusion training loss : 0.3676151332855225, val accuracy : 0.4921076033792796, best val accuracy : 0.5174522009782125
Average local training loss : 4.056733853556216
Average local training accuracy : 0.9743842592592592
INFO flwr 2023-08-02 11:58:20,986 | server.py:116 | fit progress: (21, 2.930226515661043, {'server_test_acc': 0.41350974930362117}, 2059.7577126489487)
INFO flwr 2023-08-02 11:58:20,986 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-02 11:58:30,245 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3241192)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 11:59:22,064 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3241197)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 11:59:22,289 | fed_df.py:351 | Warm start at round 22
[2m[36m(launch_and_fit pid=3241195)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 11:59:22,403 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3241192)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3241197)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3241195)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3241193)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3241199)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3241198)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3241200)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3241201)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3241193)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3241198)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3241201)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3241200)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3241199)[0m malloc_consolidate(): invalid chunk size
E0802 11:59:24.459781589 3289828 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 11:59:54,188 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 11:59:54,189 | fed_df.py:523 | Average fusion training loss : 0.36292833149433135, val accuracy : 0.5280346820809249, best val accuracy : 0.575255669186305
Average local training loss : 4.080325436592102
Average local training accuracy : 0.9732700617283951
INFO flwr 2023-08-02 11:59:55,098 | server.py:116 | fit progress: (22, 2.526195823913829, {'server_test_acc': 0.5493036211699165}, 2153.8695684091654)
INFO flwr 2023-08-02 11:59:55,098 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-02 12:00:04,355 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-02 12:00:55,940 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3314103)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3314114)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:00:56,165 | fed_df.py:351 | Warm start at round 23
INFO flwr 2023-08-02 12:00:56,277 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3314105)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3314103)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3314114)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3314115)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3314116)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3314118)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3314117)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3314119)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3314116)[0m malloc_consolidate(): invalid chunk size
E0802 12:00:56.705756162 3361753 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3314105)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3314115)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3314118)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3314119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3314117)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 12:01:28,319 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:01:28,320 | fed_df.py:523 | Average fusion training loss : 0.3812217825651169, val accuracy : 0.4917296576256113, best val accuracy : 0.5036682970208982
Average local training loss : 4.074134205654263
Average local training accuracy : 0.9738719135802469
INFO flwr 2023-08-02 12:01:29,285 | server.py:116 | fit progress: (23, 2.1843777595456264, {'server_test_acc': 0.46963788300835657}, 2248.056815619115)
INFO flwr 2023-08-02 12:01:29,285 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-02 12:01:38,649 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3387504)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-02 12:02:30,733 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3387506)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 12:02:30,958 | fed_df.py:351 | Warm start at round 24
INFO flwr 2023-08-02 12:02:31,090 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3387506)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3387504)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3387510)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3387511)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3387514)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3387513)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3387512)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3387515)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3387511)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3387514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3387510)[0m double free or corruption (fasttop)
E0802 12:02:31.887109339 3435226 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3387512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3387513)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3387515)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:03:03,299 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:03:03,299 | fed_df.py:523 | Average fusion training loss : 0.43263831758499144, val accuracy : 0.4756780791462873, best val accuracy : 0.5095598043574923
Average local training loss : 3.998834361881017
Average local training accuracy : 0.9777685185185185
INFO flwr 2023-08-02 12:03:04,220 | server.py:116 | fit progress: (24, 2.4985264807358427, {'server_test_acc': 0.3605849582172702}, 2342.9913677391596)
INFO flwr 2023-08-02 12:03:04,220 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-02 12:03:13,586 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3460357)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3460374)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3460375)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:04:05,648 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-02 12:04:05,871 | fed_df.py:351 | Warm start at round 25
INFO flwr 2023-08-02 12:04:05,986 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3460357)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3460375)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3460374)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3460373)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3460376)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3460372)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3460377)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3460378)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3460376)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3460377)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3460372)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3460373)[0m malloc_consolidate(): invalid chunk size
E0802 12:04:07.385155053 3435421 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3460378)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:04:37,775 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:04:37,776 | fed_df.py:523 | Average fusion training loss : 0.36089484226703644, val accuracy : 0.4602489995553579, best val accuracy : 0.48421520675855934
Average local training loss : 4.02351909428835
Average local training accuracy : 0.9765509259259259
INFO flwr 2023-08-02 12:04:38,675 | server.py:116 | fit progress: (25, 2.272388110785099, {'server_test_acc': 0.45571030640668525}, 2437.446709946962)
INFO flwr 2023-08-02 12:04:38,675 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-02 12:04:47,930 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3533862)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:05:39,778 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3533869)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:05:40,002 | fed_df.py:351 | Warm start at round 26
INFO flwr 2023-08-02 12:05:40,116 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3533862)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3533864)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3533866)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3533867)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3533871)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3533870)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3533869)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3533868)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3533864)[0m malloc_consolidate(): invalid chunk size
E0802 12:05:40.673268365 3581292 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3533868)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3533866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533871)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533870)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533867)[0m double free or corruption (fasttop)
E0802 12:05:42.293021775 3582368 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 12:06:12,123 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:06:12,124 | fed_df.py:523 | Average fusion training loss : 0.455153663277626, val accuracy : 0.5190529124055135, best val accuracy : 0.5393508225878169
Average local training loss : 3.990044141747057
Average local training accuracy : 0.9782885802469136
INFO flwr 2023-08-02 12:06:13,022 | server.py:116 | fit progress: (26, 2.101886656556621, {'server_test_acc': 0.46754874651810585}, 2531.7934621120803)
INFO flwr 2023-08-02 12:06:13,022 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-02 12:06:22,366 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3607088)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:07:14,245 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3607005)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:07:14,470 | fed_df.py:351 | Warm start at round 27
[2m[36m(launch_and_fit pid=3607003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3607007)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:07:14,585 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3607003)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3606996)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3607005)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3607006)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3607152)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3607088)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3607007)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3607081)[0m Fitting Client 14
E0802 12:07:15.012360470 3653845 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3606996)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3607152)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3607081)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3607006)[0m malloc_consolidate(): invalid chunk size
E0802 12:07:16.618573032 3654226 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-02 12:07:46,653 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:07:46,653 | fed_df.py:523 | Average fusion training loss : 0.4504632931947708, val accuracy : 0.4414406402845709, best val accuracy : 0.45453534904401954
Average local training loss : 3.9584928242489696
Average local training accuracy : 0.980111111111111
INFO flwr 2023-08-02 12:07:47,580 | server.py:116 | fit progress: (27, 3.4190973438592343, {'server_test_acc': 0.3997214484679666}, 2626.3513001701795)
INFO flwr 2023-08-02 12:07:47,580 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-02 12:07:56,877 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3680064)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:08:48,159 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-02 12:08:48,382 | fed_df.py:351 | Warm start at round 28
INFO flwr 2023-08-02 12:08:48,526 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3680064)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3680070)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3680071)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3680072)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3680073)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3680074)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3680067)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3680068)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3680072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3680074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3680070)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3680071)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3680068)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3680073)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3680067)[0m double free or corruption (fasttop)
INFO flwr 2023-08-02 12:09:25,443 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:09:25,444 | fed_df.py:523 | Average fusion training loss : 0.37802526021003724, val accuracy : 0.45071142730102265, best val accuracy : 0.4722098710538017
Average local training loss : 3.961788346804678
Average local training accuracy : 0.9798209876543209
INFO flwr 2023-08-02 12:09:26,344 | server.py:116 | fit progress: (28, 5.51011866619992, {'server_test_acc': 0.3711699164345404}, 2725.115629913984)
INFO flwr 2023-08-02 12:09:26,344 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-02 12:09:36,010 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3753294)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3753292)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:10:29,171 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-02 12:10:29,398 | fed_df.py:351 | Warm start at round 29
[2m[36m(launch_and_fit pid=3753295)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:10:29,561 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3753294)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3753292)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3753297)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3753296)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3753295)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3753298)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3753291)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3753299)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3753297)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3753296)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3753299)[0m malloc_consolidate(): invalid chunk size
E0802 12:10:30.365379545 3655704 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3753298)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3753291)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:11:01,906 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:11:01,907 | fed_df.py:523 | Average fusion training loss : 0.3854994181394577, val accuracy : 0.5216318363717207, best val accuracy : 0.5770342374388617
Average local training loss : 3.926403857581317
Average local training accuracy : 0.9819197530864198
INFO flwr 2023-08-02 12:11:02,810 | server.py:116 | fit progress: (29, 3.053239772445976, {'server_test_acc': 0.5672701949860725}, 2821.5814413991757)
INFO flwr 2023-08-02 12:11:02,810 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-02 12:11:12,296 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3854570)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-02 12:12:03,868 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-02 12:12:04,094 | fed_df.py:351 | Warm start at round 30
INFO flwr 2023-08-02 12:12:04,241 | fed_df.py:439 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3854570)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3854572)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3854574)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3854577)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3854575)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3854576)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3854579)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3854578)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3854572)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3854574)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3854577)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3854575)[0m malloc_consolidate(): invalid chunk size
E0802 12:12:05.512811684 3902495 chttp2_transport.cc:1079]             ipv4:145.136.62.67:42841: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3854579)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3854578)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3854576)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-02 12:12:36,555 | fed_df.py:516 | Distillation training stopped at step number : 250
INFO flwr 2023-08-02 12:12:36,555 | fed_df.py:523 | Average fusion training loss : 0.3694952827692032, val accuracy : 0.5051800800355712, best val accuracy : 0.5136727434415296
Average local training loss : 3.9348596310243016
Average local training accuracy : 0.9817067901234567
INFO flwr 2023-08-02 12:12:37,484 | server.py:116 | fit progress: (30, 3.5941640311961054, {'server_test_acc': 0.533983286908078}, 2916.2557631649543)
INFO flwr 2023-08-02 12:12:37,484 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-02 12:12:37,484 | server.py:144 | FL finished in 2916.256118216086
INFO flwr 2023-08-02 12:12:37,485 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-02 12:12:37,486 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-02 12:12:37,486 | app.py:204 | app_fit: losses_centralized [(0, 2.1845225108367154), (1, 5.298423531194915), (2, 6.283704598301965), (3, 3.847280095347455), (4, 4.478048811516722), (5, 4.617031377138866), (6, 4.006847188731754), (7, 3.6320857239300826), (8, 3.3341462815372394), (9, 5.756511477308353), (10, 5.166859208109651), (11, 3.91294124651088), (12, 4.118107672454919), (13, 2.990864265728794), (14, 3.909747319234779), (15, 2.9836339453800806), (16, 2.707925934114164), (17, 1.9609930848676846), (18, 2.2688284015921165), (19, 2.253201657882308), (20, 1.9987182000885435), (21, 2.930226515661043), (22, 2.526195823913829), (23, 2.1843777595456264), (24, 2.4985264807358427), (25, 2.272388110785099), (26, 2.101886656556621), (27, 3.4190973438592343), (28, 5.51011866619992), (29, 3.053239772445976), (30, 3.5941640311961054)]
INFO flwr 2023-08-02 12:12:37,486 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.11030640668523677), (1, 0.42590529247910863), (2, 0.38662952646239557), (3, 0.5013927576601671), (4, 0.4967966573816156), (5, 0.5135097493036211), (6, 0.5211699164345404), (7, 0.525766016713092), (8, 0.7415041782729805), (9, 0.4764623955431755), (10, 0.3334261838440111), (11, 0.5467966573816156), (12, 0.46295264623955434), (13, 0.45306406685236766), (14, 0.45167130919220055), (15, 0.5050139275766017), (16, 0.500974930362117), (17, 0.47311977715877435), (18, 0.49428969359331476), (19, 0.5591922005571031), (20, 0.5086350974930363), (21, 0.41350974930362117), (22, 0.5493036211699165), (23, 0.46963788300835657), (24, 0.3605849582172702), (25, 0.45571030640668525), (26, 0.46754874651810585), (27, 0.3997214484679666), (28, 0.3711699164345404), (29, 0.5672701949860725), (30, 0.533983286908078)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn67: task 0: Aborted
srun: Terminating StepId=3203533.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3203533
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:00:10
CPU Efficiency: 12.25% of 16:21:18 core-walltime
Job Wall-clock time: 00:54:31
Memory Utilized: 59.79 GB
Memory Efficiency: 49.83% of 120.00 GB
