-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:10000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:50
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.5
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=10000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3339011/1692092719_031971150', seed=84, img_per_thread=555)
will save 10000 patches in /scratch-local/sunnys.3339011/1692092719_031971150/single_img_crops/crops
10000 took 0.14min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 11:45:44,087 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 11:45:44,087 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3339011/1692092719_031971150/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3339011/1692092719_031971150/cifar-10-python.tar.gz to /scratch-local/sunnys.3339011/1692092719_031971150
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [225 194 247 272 217 251 256 333 258 247]
INFO flwr 2023-08-15 11:46:12,152 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 11:46:14,963	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-15 11:46:16,111 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.25': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'accelerator_type:A100': 1.0, 'GPU': 1.0, 'CPU': 18.0}
INFO flwr 2023-08-15 11:46:16,111 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 11:46:16,111 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 11:46:16,111 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 11:46:26,817 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-15 11:46:26,818 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 11:46:31,445 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1969829)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:47:26,983 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-15 11:47:27,195 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-15 11:47:27,321 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1969917)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1969905)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1969927)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1969839)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1969831)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1969925)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1969829)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1969926)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1969839)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1969925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969926)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969905)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969927)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1969831)[0m malloc_consolidate(): invalid chunk size
E0815 11:47:31.317373714 1955036 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-15 11:47:59,833 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:47:59,833 | fed_df.py:547 | Average fusion training loss : 0.024811589993536474, val accuracy : 0.38588, best val accuracy : 0.413
INFO flwr 2023-08-15 11:47:59,835 | common.py:35 | Avg. local train loss : 8.8480154722929, train acc : 0.3769555555555556
INFO flwr 2023-08-15 11:48:02,611 | server.py:116 | fit progress: (1, 1.5908738830566407, {'server_test_acc': 0.4163}, 95.79316065320745)
INFO flwr 2023-08-15 11:48:02,611 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 11:48:07,338 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:48:59,912 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-15 11:49:00,120 | fed_df.py:365 | Warm start at round 2
[2m[36m(launch_and_fit pid=2137956)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:49:00,249 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2137954)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2137956)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2137958)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2137957)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2137953)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2137960)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2137959)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2137961)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2137953)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137960)[0m malloc_consolidate(): invalid chunk size
E0815 11:49:01.495833541 2085303 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2137957)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2137958)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137959)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137961)[0m malloc_consolidate(): invalid chunk size
E0815 11:49:02.370975325 2233637 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=2137954)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:49:32,760 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:49:32,760 | fed_df.py:547 | Average fusion training loss : 0.013071761060506105, val accuracy : 0.5744400000000001, best val accuracy : 0.5834
INFO flwr 2023-08-15 11:49:32,762 | common.py:35 | Avg. local train loss : 7.182235902547836, train acc : 0.5595972222222223
INFO flwr 2023-08-15 11:49:35,563 | server.py:116 | fit progress: (2, 1.3021219818115235, {'server_test_acc': 0.5827}, 188.7451843228191)
INFO flwr 2023-08-15 11:49:35,563 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 11:49:40,214 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:50:34,078 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2286272)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286268)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:50:34,287 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 11:50:34,429 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2286266)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2286268)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2286270)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2286269)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2286267)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2286271)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2286273)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2286272)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2286271)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2286267)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2286269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286266)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286270)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:51:07,005 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:51:07,006 | fed_df.py:547 | Average fusion training loss : 0.015600496044382453, val accuracy : 0.62876, best val accuracy : 0.6422
INFO flwr 2023-08-15 11:51:07,008 | common.py:35 | Avg. local train loss : 6.145397227630019, train acc : 0.6717499999999998
INFO flwr 2023-08-15 11:51:09,756 | server.py:116 | fit progress: (3, 1.2149516052246094, {'server_test_acc': 0.6403}, 282.9382462762296)
INFO flwr 2023-08-15 11:51:09,756 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 11:51:14,448 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2434194)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:52:08,429 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-15 11:52:08,637 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 11:52:08,944 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2434192)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2434188)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2434187)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2434193)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2434194)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2434195)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2434197)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2434196)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2434193)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2434197)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2434196)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2434188)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2434195)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2434192)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2434187)[0m double free or corruption (fasttop)
E0815 11:52:12.714326464 2235008 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-15 11:52:41,466 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:52:41,467 | fed_df.py:547 | Average fusion training loss : 0.016914503591135145, val accuracy : 0.65408, best val accuracy : 0.6618
INFO flwr 2023-08-15 11:52:41,469 | common.py:35 | Avg. local train loss : 5.58512710146606, train acc : 0.728636111111111
INFO flwr 2023-08-15 11:52:44,219 | server.py:116 | fit progress: (4, 1.2006502227783202, {'server_test_acc': 0.6555}, 377.4013027199544)
INFO flwr 2023-08-15 11:52:44,219 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 11:52:48,915 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2581587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581880)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2581590)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:53:45,241 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2581582)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581588)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:53:45,454 | fed_df.py:365 | Warm start at round 5
[2m[36m(launch_and_fit pid=2581586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581589)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:53:45,595 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2581582)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2581586)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2581587)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2581588)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2581880)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2581590)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2581589)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2581879)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2581879)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:54:18,136 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:54:18,136 | fed_df.py:547 | Average fusion training loss : 0.014049872322008014, val accuracy : 0.68876, best val accuracy : 0.6942
INFO flwr 2023-08-15 11:54:18,138 | common.py:35 | Avg. local train loss : 5.224117374047636, train acc : 0.7634861111111111
INFO flwr 2023-08-15 11:54:20,830 | server.py:116 | fit progress: (5, 1.2496689880371095, {'server_test_acc': 0.6874}, 474.0124653838575)
INFO flwr 2023-08-15 11:54:20,830 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 11:54:25,462 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2729769)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:55:17,522 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-15 11:55:17,731 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 11:55:17,858 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2729755)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2729764)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2729765)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2729767)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2729768)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2729770)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2729771)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2729769)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2729755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2729770)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2729764)[0m malloc_consolidate(): invalid chunk size
E0815 11:55:19.123534640 2824840 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2729768)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2729771)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2729765)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:55:50,472 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:55:50,472 | fed_df.py:547 | Average fusion training loss : 0.014778484678361565, val accuracy : 0.6899599999999999, best val accuracy : 0.7072
INFO flwr 2023-08-15 11:55:50,474 | common.py:35 | Avg. local train loss : 5.019671850651503, train acc : 0.7864055555555556
INFO flwr 2023-08-15 11:55:53,245 | server.py:116 | fit progress: (6, 1.3487034637451172, {'server_test_acc': 0.7036}, 566.4267678400502)
INFO flwr 2023-08-15 11:55:53,245 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 11:55:57,916 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:57:04,495 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2877896)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:57:04,706 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 11:57:04,832 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2877896)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2877905)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2877906)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2877904)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2877908)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2877910)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2877909)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2877907)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2877904)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2877906)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2877909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2877905)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2877908)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2877910)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2877907)[0m double free or corruption (fasttop)
E0815 11:57:08.692684450 2825696 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-15 11:57:37,392 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:57:37,392 | fed_df.py:547 | Average fusion training loss : 0.02493069424200803, val accuracy : 0.6736, best val accuracy : 0.6946
INFO flwr 2023-08-15 11:57:37,394 | common.py:35 | Avg. local train loss : 4.936565148830414, train acc : 0.8003527777777777
INFO flwr 2023-08-15 11:57:40,147 | server.py:116 | fit progress: (7, 1.2959228759765624, {'server_test_acc': 0.6963}, 673.3293482889421)
INFO flwr 2023-08-15 11:57:40,147 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 11:57:44,886 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3026308)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:58:40,264 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3026300)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3026301)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:58:40,475 | fed_df.py:365 | Warm start at round 8
[2m[36m(launch_and_fit pid=3026306)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:58:40,601 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3026183)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3026182)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3026288)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3026301)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3026300)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3026308)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3026306)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3026307)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3026183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3026288)[0m malloc_consolidate(): invalid chunk size
E0815 11:58:41.315209593 2977442 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=3026307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3026182)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:59:13,162 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:59:13,162 | fed_df.py:547 | Average fusion training loss : 0.015658736082725225, val accuracy : 0.70124, best val accuracy : 0.7118
INFO flwr 2023-08-15 11:59:13,164 | common.py:35 | Avg. local train loss : 4.8626585029065605, train acc : 0.8046277777777777
INFO flwr 2023-08-15 11:59:15,901 | server.py:116 | fit progress: (8, 1.3069700561523439, {'server_test_acc': 0.7139}, 769.0833720150404)
INFO flwr 2023-08-15 11:59:15,901 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 11:59:20,549 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:00:14,514 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-15 12:00:14,724 | fed_df.py:365 | Warm start at round 9
[2m[36m(launch_and_fit pid=3174045)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:00:14,853 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3174045)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3174044)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3174051)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3174049)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3174050)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3174054)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3174053)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3174052)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3174049)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174050)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174052)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174054)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3174044)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174051)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:00:47,466 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:00:47,466 | fed_df.py:547 | Average fusion training loss : 0.013027722556144, val accuracy : 0.7036, best val accuracy : 0.72
INFO flwr 2023-08-15 12:00:47,468 | common.py:35 | Avg. local train loss : 4.718072808161378, train acc : 0.8186722222222222
INFO flwr 2023-08-15 12:00:50,243 | server.py:116 | fit progress: (9, 1.4477635040283203, {'server_test_acc': 0.7208}, 863.4254381768405)
INFO flwr 2023-08-15 12:00:50,243 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 12:00:54,896 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3321793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3321813)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:01:51,665 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-15 12:01:51,875 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 12:01:52,004 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3321648)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3321649)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3321793)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3321660)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3321811)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3321813)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3321809)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3321814)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3321648)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3321809)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3321660)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3321814)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3321649)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3321811)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:02:24,842 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:02:24,842 | fed_df.py:547 | Average fusion training loss : 0.011270349945873021, val accuracy : 0.70464, best val accuracy : 0.7278
INFO flwr 2023-08-15 12:02:24,844 | common.py:35 | Avg. local train loss : 4.596496929228306, train acc : 0.8315166666666667
INFO flwr 2023-08-15 12:02:27,616 | server.py:116 | fit progress: (10, 1.4833047027587891, {'server_test_acc': 0.7232}, 960.7984781619161)
INFO flwr 2023-08-15 12:02:27,616 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 12:02:32,339 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3498320)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498323)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:03:29,550 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-15 12:03:29,762 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-15 12:03:29,889 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3498330)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3498320)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3498322)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3498324)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3498323)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3498326)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3498331)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3498328)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3498330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498324)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498326)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498328)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498331)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498322)[0m malloc_consolidate(): invalid chunk size
E0815 12:03:49.347948154 3635527 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-15 12:05:44,613 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:05:44,614 | fed_df.py:547 | Average fusion training loss : 0.011302374792285264, val accuracy : 0.7074, best val accuracy : 0.7382
INFO flwr 2023-08-15 12:05:44,615 | common.py:35 | Avg. local train loss : 4.601164431497455, train acc : 0.835175
INFO flwr 2023-08-15 12:05:47,394 | server.py:116 | fit progress: (11, 1.5255515411376954, {'server_test_acc': 0.7293}, 1160.5761225591414)
INFO flwr 2023-08-15 12:05:47,394 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 12:05:52,122 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3665201)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665196)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3665202)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:06:47,046 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3665198)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:06:47,256 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 12:06:47,380 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3665194)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3665199)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3665197)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3665196)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3665198)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3665201)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3665202)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3665200)[0m Fitting Client 18
E0815 12:06:47.924012890 3638831 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3665194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665200)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3665197)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:07:19,830 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:07:19,830 | fed_df.py:547 | Average fusion training loss : 0.009452022643294186, val accuracy : 0.7125199999999999, best val accuracy : 0.7378
INFO flwr 2023-08-15 12:07:19,832 | common.py:35 | Avg. local train loss : 4.532974042743445, train acc : 0.8450000000000001
INFO flwr 2023-08-15 12:07:22,608 | server.py:116 | fit progress: (12, 1.5582722320556641, {'server_test_acc': 0.7286}, 1255.7901706588455)
INFO flwr 2023-08-15 12:07:22,608 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 12:07:27,282 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3813104)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:08:21,322 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 12:08:21,532 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 12:08:21,664 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3813097)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3813102)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3813103)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3813105)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3813104)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3813096)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3813099)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3813101)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3813099)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3813102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3813103)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3813097)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3813105)[0m double free or corruption (fasttop)
E0815 12:08:23.087846829 3908702 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3813101)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3813096)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:08:54,536 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:08:54,536 | fed_df.py:547 | Average fusion training loss : 0.00897701997961849, val accuracy : 0.7230399999999999, best val accuracy : 0.7444
INFO flwr 2023-08-15 12:08:54,538 | common.py:35 | Avg. local train loss : 4.418630903959275, train acc : 0.8588305555555555
INFO flwr 2023-08-15 12:08:57,274 | server.py:116 | fit progress: (13, 1.6343932373046874, {'server_test_acc': 0.7391}, 1350.4562036488205)
INFO flwr 2023-08-15 12:08:57,274 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 12:09:01,941 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3960965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3960957)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:09:56,096 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-15 12:09:56,305 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 12:09:56,433 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3960955)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3960957)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3960961)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3960960)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3960962)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3960965)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3960963)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3960964)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3960962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3960964)[0m malloc_consolidate(): invalid chunk size
E0815 12:09:57.069357975 3909123 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=3960961)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3960955)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3960963)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3960960)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:10:29,402 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:10:29,403 | fed_df.py:547 | Average fusion training loss : 0.008575860226526856, val accuracy : 0.7209200000000001, best val accuracy : 0.745
INFO flwr 2023-08-15 12:10:29,406 | common.py:35 | Avg. local train loss : 4.434053831547499, train acc : 0.8578972222222222
INFO flwr 2023-08-15 12:10:32,158 | server.py:116 | fit progress: (14, 1.6634981719970703, {'server_test_acc': 0.7344}, 1445.3400308480486)
INFO flwr 2023-08-15 12:10:32,158 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 12:10:36,854 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:11:29,233 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4108864)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:11:29,442 | fed_df.py:365 | Warm start at round 15
[2m[36m(launch_and_fit pid=4108848)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:11:29,572 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4108848)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4108849)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4108856)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4108850)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4108863)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4108865)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4108864)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4108866)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4108850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4108849)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4108856)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4108865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4108866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4108863)[0m malloc_consolidate(): invalid chunk size
E0815 12:11:31.628948377   11318 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-15 12:12:02,424 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:12:02,424 | fed_df.py:547 | Average fusion training loss : 0.008127274786587804, val accuracy : 0.72484, best val accuracy : 0.7508
INFO flwr 2023-08-15 12:12:02,426 | common.py:35 | Avg. local train loss : 4.403496981039644, train acc : 0.8621416666666666
INFO flwr 2023-08-15 12:12:05,342 | server.py:116 | fit progress: (15, 1.6768271514892579, {'server_test_acc': 0.7424}, 1538.5246242228895)
INFO flwr 2023-08-15 12:12:05,343 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 12:12:10,008 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=63587)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:13:03,998 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=63578)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:13:04,333 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-15 12:13:04,461 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=63564)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=63578)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=63586)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=63587)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=63589)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=63591)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=63590)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=63588)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=63589)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=63590)[0m malloc_consolidate(): invalid chunk size
E0815 12:13:04.964533786  157778 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=63586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63591)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:13:37,279 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:13:37,279 | fed_df.py:547 | Average fusion training loss : 0.007517561131622642, val accuracy : 0.7306, best val accuracy : 0.7548
INFO flwr 2023-08-15 12:13:37,281 | common.py:35 | Avg. local train loss : 4.366180478036404, train acc : 0.865825
INFO flwr 2023-08-15 12:13:40,048 | server.py:116 | fit progress: (16, 1.6668324829101562, {'server_test_acc': 0.7528}, 1633.2307033748366)
INFO flwr 2023-08-15 12:13:40,049 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 12:13:44,717 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=211716)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211728)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:14:38,863 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-15 12:14:39,072 | fed_df.py:365 | Warm start at round 17
[2m[36m(launch_and_fit pid=211721)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:14:39,203 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=211721)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=211718)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=211717)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=211715)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=211716)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=211726)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=211728)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=211727)[0m Fitting Client 0
E0815 12:14:39.748264467  158248 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=211726)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211717)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211727)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211715)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211718)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:15:12,127 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:15:12,128 | fed_df.py:547 | Average fusion training loss : 0.008248694087378682, val accuracy : 0.7301599999999999, best val accuracy : 0.7532
INFO flwr 2023-08-15 12:15:12,130 | common.py:35 | Avg. local train loss : 4.308560549840331, train acc : 0.8720750000000002
INFO flwr 2023-08-15 12:15:14,887 | server.py:116 | fit progress: (17, 1.6711086608886718, {'server_test_acc': 0.7474}, 1728.0695915180258)
INFO flwr 2023-08-15 12:15:14,888 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 12:15:19,535 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=359471)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=359475)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=359467)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:16:13,256 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-15 12:16:13,469 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 12:16:13,611 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=359464)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=359467)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=359469)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=359471)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=359476)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=359474)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=359473)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=359475)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=359474)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=359476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=359464)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=359473)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=359469)[0m double free or corruption (fasttop)
E0815 12:16:17.650096134  306940 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-15 12:16:46,740 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:16:46,740 | fed_df.py:547 | Average fusion training loss : 0.007332096538040787, val accuracy : 0.73824, best val accuracy : 0.7584
INFO flwr 2023-08-15 12:16:46,742 | common.py:35 | Avg. local train loss : 4.285936039686203, train acc : 0.8747166666666666
INFO flwr 2023-08-15 12:16:49,563 | server.py:116 | fit progress: (18, 1.6763849304199219, {'server_test_acc': 0.7526}, 1822.744834296871)
INFO flwr 2023-08-15 12:16:49,563 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 12:16:54,234 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=507436)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=507433)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:17:48,641 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=507431)[0m malloc(): unsorted double linked list corrupted
INFO flwr 2023-08-15 12:17:48,851 | fed_df.py:365 | Warm start at round 19
[2m[36m(launch_and_fit pid=507432)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:17:48,978 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=507431)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=507433)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=507430)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=507435)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=507436)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=507429)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=507432)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=507434)[0m Fitting Client 10
E0815 12:17:50.180411884  459652 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=507430)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=507429)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=507434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=507435)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:18:21,974 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:18:21,974 | fed_df.py:547 | Average fusion training loss : 0.007107297121547162, val accuracy : 0.7379200000000001, best val accuracy : 0.7596
INFO flwr 2023-08-15 12:18:21,976 | common.py:35 | Avg. local train loss : 4.27881600484252, train acc : 0.876513888888889
INFO flwr 2023-08-15 12:18:24,776 | server.py:116 | fit progress: (19, 1.715271240234375, {'server_test_acc': 0.752}, 1917.958522181958)
INFO flwr 2023-08-15 12:18:24,777 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 12:18:29,495 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=686860)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=686923)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:19:25,839 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=687720)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:19:26,052 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 12:19:26,181 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=686860)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=687720)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=686923)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=687148)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=687057)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=686924)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=687753)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=687740)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=686924)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=687740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=687753)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=687057)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=687148)[0m double free or corruption (fasttop)
E0815 12:19:28.245424342  616528 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:19:59,370 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:19:59,370 | fed_df.py:547 | Average fusion training loss : 0.00660907197650522, val accuracy : 0.7383599999999999, best val accuracy : 0.76
INFO flwr 2023-08-15 12:19:59,372 | common.py:35 | Avg. local train loss : 4.249777422845363, train acc : 0.8790944444444445
INFO flwr 2023-08-15 12:20:02,145 | server.py:116 | fit progress: (20, 1.6704295776367188, {'server_test_acc': 0.7565}, 2015.3273166511208)
INFO flwr 2023-08-15 12:20:02,145 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 12:20:06,974 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=849186)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=849193)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=849195)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=849191)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=849192)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:21:01,437 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-15 12:21:01,646 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 12:21:01,773 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=849186)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=849190)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=849191)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=849192)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=849193)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=849195)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=849188)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=849194)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=849190)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=849194)[0m malloc_consolidate(): invalid chunk size
E0815 12:21:03.102587129  798584 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=849188)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:21:35,043 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:21:35,043 | fed_df.py:547 | Average fusion training loss : 0.0069305886896327135, val accuracy : 0.75, best val accuracy : 0.7684
INFO flwr 2023-08-15 12:21:35,045 | common.py:35 | Avg. local train loss : 4.192576406896114, train acc : 0.8864638888888889
INFO flwr 2023-08-15 12:21:37,813 | server.py:116 | fit progress: (21, 1.6991063751220703, {'server_test_acc': 0.7653}, 2110.9954963722266)
INFO flwr 2023-08-15 12:21:37,814 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 12:21:42,493 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:22:36,193 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-15 12:22:36,401 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 12:22:36,530 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=997470)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=997472)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=997473)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=997476)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=997474)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=997475)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=997477)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=997478)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=997474)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997473)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=997478)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=997475)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997470)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997477)[0m malloc_consolidate(): invalid chunk size
E0815 12:22:38.875716992  945370 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:23:10,637 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:23:10,637 | fed_df.py:547 | Average fusion training loss : 0.00694860901357606, val accuracy : 0.7553599999999999, best val accuracy : 0.7716
INFO flwr 2023-08-15 12:23:10,639 | common.py:35 | Avg. local train loss : 4.201011806726456, train acc : 0.8846916666666667
INFO flwr 2023-08-15 12:23:13,410 | server.py:116 | fit progress: (22, 1.6830949920654297, {'server_test_acc': 0.7598}, 2206.5919386972673)
INFO flwr 2023-08-15 12:23:13,410 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 12:23:18,083 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:24:10,159 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 12:24:10,373 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 12:24:10,511 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1145216)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1145217)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1145223)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1145233)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1145232)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1145234)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1145236)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1145235)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1145223)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1145235)[0m malloc_consolidate(): invalid chunk size
E0815 12:24:11.982154886 1241111 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1145236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1145216)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1145217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1145232)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1145234)[0m malloc_consolidate(): invalid chunk size
E0815 12:24:13.067599981 1241385 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1145233)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:24:47,636 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:24:47,637 | fed_df.py:547 | Average fusion training loss : 0.006747001742012799, val accuracy : 0.75532, best val accuracy : 0.77
INFO flwr 2023-08-15 12:24:47,639 | common.py:35 | Avg. local train loss : 4.169167309254408, train acc : 0.8872027777777778
INFO flwr 2023-08-15 12:24:50,291 | server.py:116 | fit progress: (23, 1.7062401428222655, {'server_test_acc': 0.7621}, 2303.4728460218757)
INFO flwr 2023-08-15 12:24:50,291 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 12:24:54,886 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1293713)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:25:45,342 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 12:25:45,552 | fed_df.py:365 | Warm start at round 24
[2m[36m(launch_and_fit pid=1293708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1293709)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:25:45,681 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1293714)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1293709)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1293710)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1293715)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1293708)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1293713)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1293717)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1293716)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1293714)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1293715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1293717)[0m malloc_consolidate(): invalid chunk size
E0815 12:25:46.630601621 1243124 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1293716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1293710)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:26:18,599 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:26:18,600 | fed_df.py:547 | Average fusion training loss : 0.006539578064810485, val accuracy : 0.75752, best val accuracy : 0.7716
INFO flwr 2023-08-15 12:26:18,602 | common.py:35 | Avg. local train loss : 4.164185984060168, train acc : 0.8873166666666666
INFO flwr 2023-08-15 12:26:21,377 | server.py:116 | fit progress: (24, 1.698217239379883, {'server_test_acc': 0.7718}, 2394.5588520928286)
INFO flwr 2023-08-15 12:26:21,377 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 12:26:26,196 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1442749)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:27:17,967 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1442754)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:27:18,178 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 12:27:18,303 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1442756)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1442751)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1442755)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1442753)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1442750)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1442749)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1442754)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1442752)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1442750)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1442752)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1442751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1442753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1442755)[0m malloc_consolidate(): invalid chunk size
E0815 12:27:19.727867282 1540741 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 12:27:19.728009961 1540741 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 12:27:19.728029413 1540741 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 12:27:19.728040627 1540741 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1442756)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:27:50,415 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:27:50,415 | fed_df.py:547 | Average fusion training loss : 0.005902929733972996, val accuracy : 0.7558399999999998, best val accuracy : 0.7726
INFO flwr 2023-08-15 12:27:50,417 | common.py:35 | Avg. local train loss : 4.154073627665639, train acc : 0.8881861111111111
INFO flwr 2023-08-15 12:27:53,060 | server.py:116 | fit progress: (25, 1.723656881713867, {'server_test_acc': 0.7731}, 2486.242313559167)
INFO flwr 2023-08-15 12:27:53,060 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 12:27:57,626 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1590863)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1590865)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:28:48,307 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-15 12:28:48,516 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 12:28:48,641 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1590858)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1590860)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1590861)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1590863)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1590865)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1590866)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1590867)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1590868)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1590861)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1590860)[0m double free or corruption (fasttop)
E0815 12:28:49.265018587 1686077 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1590868)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1590858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1590866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1590867)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:29:21,099 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:29:21,100 | fed_df.py:547 | Average fusion training loss : 0.006056980310939253, val accuracy : 0.76164, best val accuracy : 0.7788
INFO flwr 2023-08-15 12:29:21,102 | common.py:35 | Avg. local train loss : 4.120248648896813, train acc : 0.8926138888888889
INFO flwr 2023-08-15 12:29:23,898 | server.py:116 | fit progress: (26, 1.6825486541748047, {'server_test_acc': 0.7765}, 2577.079780015163)
INFO flwr 2023-08-15 12:29:23,898 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 12:29:28,572 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1739685)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1739688)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:30:20,215 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 12:30:20,424 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-15 12:30:20,551 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1739685)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1739688)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1739686)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1739684)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1739690)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1739687)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1739691)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1739689)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1739687)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1739689)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1739690)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1739691)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1739686)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1739684)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:30:53,539 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:30:53,539 | fed_df.py:547 | Average fusion training loss : 0.006205988959409297, val accuracy : 0.7646000000000001, best val accuracy : 0.7818
INFO flwr 2023-08-15 12:30:53,541 | common.py:35 | Avg. local train loss : 4.088670711219311, train acc : 0.8961833333333332
INFO flwr 2023-08-15 12:30:56,311 | server.py:116 | fit progress: (27, 1.6975738677978516, {'server_test_acc': 0.7752}, 2669.4935302510858)
INFO flwr 2023-08-15 12:30:56,312 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 12:31:00,975 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:31:54,939 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1887610)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:31:55,151 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-15 12:31:55,278 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1887610)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1887613)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1887614)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1887609)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1887615)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1887612)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1887611)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1887616)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1887614)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1887615)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1887611)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1887609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1887613)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1887616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1887612)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 12:32:28,381 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:32:28,381 | fed_df.py:547 | Average fusion training loss : 0.006511690687853843, val accuracy : 0.76684, best val accuracy : 0.7798
INFO flwr 2023-08-15 12:32:28,383 | common.py:35 | Avg. local train loss : 4.025636840239168, train acc : 0.9024972222222221
INFO flwr 2023-08-15 12:32:31,221 | server.py:116 | fit progress: (28, 1.6593490600585938, {'server_test_acc': 0.7792}, 2764.4033035640605)
INFO flwr 2023-08-15 12:32:31,221 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 12:32:35,951 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:33:31,053 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 12:33:31,264 | fed_df.py:365 | Warm start at round 29
[2m[36m(launch_and_fit pid=2037632)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:33:31,397 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2037629)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2037632)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2037633)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2037634)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2037635)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2037637)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2037630)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2037636)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2037630)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2037635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2037636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2037637)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2037629)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2037633)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2037634)[0m malloc_consolidate(): invalid chunk size
E0815 12:33:38.753091995 2149082 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:34:05,311 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:34:05,312 | fed_df.py:547 | Average fusion training loss : 0.0059204231761395935, val accuracy : 0.76604, best val accuracy : 0.7732
INFO flwr 2023-08-15 12:34:05,314 | common.py:35 | Avg. local train loss : 4.015136317536236, train acc : 0.9023194444444443
INFO flwr 2023-08-15 12:34:08,100 | server.py:116 | fit progress: (29, 1.673931689453125, {'server_test_acc': 0.7764}, 2861.2826193510555)
INFO flwr 2023-08-15 12:34:08,101 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 12:34:12,831 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2217735)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:35:06,111 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 12:35:06,322 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 12:35:06,451 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2217672)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2217684)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2217610)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2217736)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2217735)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2217917)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2218220)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2218208)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2217610)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2217736)[0m malloc_consolidate(): invalid chunk size
E0815 12:35:07.110614810 2153966 chttp2_transport.cc:1079]             ipv4:145.136.62.25:56714: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2217684)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2217672)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2218220)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2218208)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2217917)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:35:44,605 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:35:44,606 | fed_df.py:547 | Average fusion training loss : 0.005660841103643179, val accuracy : 0.76724, best val accuracy : 0.7814
INFO flwr 2023-08-15 12:35:44,608 | common.py:35 | Avg. local train loss : 4.020652474090457, train acc : 0.9016694444444446
INFO flwr 2023-08-15 12:35:47,358 | server.py:116 | fit progress: (30, 1.683030108642578, {'server_test_acc': 0.7752}, 2960.540307977237)
INFO flwr 2023-08-15 12:35:47,358 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 12:35:47,358 | server.py:144 | FL finished in 2960.540660336148
INFO flwr 2023-08-15 12:35:47,359 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 12:35:47,360 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 12:35:47,360 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.5908738830566407), (2, 1.3021219818115235), (3, 1.2149516052246094), (4, 1.2006502227783202), (5, 1.2496689880371095), (6, 1.3487034637451172), (7, 1.2959228759765624), (8, 1.3069700561523439), (9, 1.4477635040283203), (10, 1.4833047027587891), (11, 1.5255515411376954), (12, 1.5582722320556641), (13, 1.6343932373046874), (14, 1.6634981719970703), (15, 1.6768271514892579), (16, 1.6668324829101562), (17, 1.6711086608886718), (18, 1.6763849304199219), (19, 1.715271240234375), (20, 1.6704295776367188), (21, 1.6991063751220703), (22, 1.6830949920654297), (23, 1.7062401428222655), (24, 1.698217239379883), (25, 1.723656881713867), (26, 1.6825486541748047), (27, 1.6975738677978516), (28, 1.6593490600585938), (29, 1.673931689453125), (30, 1.683030108642578)]
INFO flwr 2023-08-15 12:35:47,360 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4163), (2, 0.5827), (3, 0.6403), (4, 0.6555), (5, 0.6874), (6, 0.7036), (7, 0.6963), (8, 0.7139), (9, 0.7208), (10, 0.7232), (11, 0.7293), (12, 0.7286), (13, 0.7391), (14, 0.7344), (15, 0.7424), (16, 0.7528), (17, 0.7474), (18, 0.7526), (19, 0.752), (20, 0.7565), (21, 0.7653), (22, 0.7598), (23, 0.7621), (24, 0.7718), (25, 0.7731), (26, 0.7765), (27, 0.7752), (28, 0.7792), (29, 0.7764), (30, 0.7752)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn25: task 0: Aborted
srun: Terminating StepId=3339011.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3339011
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:49:48
CPU Efficiency: 11.96% of 15:18:00 core-walltime
Job Wall-clock time: 00:51:00
Memory Utilized: 54.59 GB
Memory Efficiency: 45.49% of 120.00 GB
