-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:10000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.1
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:50
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.5
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=10000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3339003/1692092717_207617525', seed=42, img_per_thread=555)
will save 10000 patches in /scratch-local/sunnys.3339003/1692092717_207617525/single_img_crops/crops
10000 took 0.18min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 11:45:43,665 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 11:45:43,666 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3339003/1692092717_207617525/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3339003/1692092717_207617525/cifar-10-python.tar.gz to /scratch-local/sunnys.3339003/1692092717_207617525
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [256 249 217 265 244 275 235 226 275 258]
INFO flwr 2023-08-15 11:46:10,126 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 11:46:12,756	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-15 11:46:15,958 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'accelerator_type:A100': 1.0, 'memory': 103079215104.0, 'GPU': 1.0, 'node:145.136.62.23': 1.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-08-15 11:46:15,959 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 11:46:15,959 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 11:46:15,959 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 11:46:24,893 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-15 11:46:24,893 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 11:46:29,686 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:47:31,542 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-15 11:47:31,749 | fed_df.py:365 | Warm start at round 1
[2m[36m(launch_and_fit pid=1975769)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 11:47:31,880 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1975752)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1975751)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1975759)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1975758)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1975760)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1975769)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1975768)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1975767)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1975751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975752)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1975768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975760)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975767)[0m malloc_consolidate(): invalid chunk size
E0815 11:47:33.988658254 1966727 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 11:47:33.992217365 1966727 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=1975759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975758)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:48:04,481 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:48:04,484 | fed_df.py:547 | Average fusion training loss : 0.06735185096412898, val accuracy : 0.28496, best val accuracy : 0.3482
INFO flwr 2023-08-15 11:48:04,485 | common.py:35 | Avg. local train loss : 8.68009411394596, train acc : 0.39953611111111104
INFO flwr 2023-08-15 11:48:07,136 | server.py:116 | fit progress: (1, 7.919619067382812, {'server_test_acc': 0.3553}, 102.24332309514284)
INFO flwr 2023-08-15 11:48:07,137 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 11:48:11,833 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:49:08,170 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2197005)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197011)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:49:08,379 | fed_df.py:365 | Warm start at round 2
[2m[36m(launch_and_fit pid=2197006)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:49:08,509 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2197007)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2196997)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2196999)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2197006)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2197012)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2197005)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2197011)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2196996)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2196996)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2196999)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2196997)[0m malloc_consolidate(): invalid chunk size
E0815 11:49:09.928417625 2337972 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0815 11:49:09.928505331 2337972 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0815 11:49:09.928515596 2337972 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0815 11:49:09.928524204 2337972 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2197007)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197012)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:49:40,763 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:49:40,763 | fed_df.py:547 | Average fusion training loss : 0.7238477516174316, val accuracy : 0.36144000000000004, best val accuracy : 0.3932
INFO flwr 2023-08-15 11:49:40,765 | common.py:35 | Avg. local train loss : 8.228965415805579, train acc : 0.44878611111111116
INFO flwr 2023-08-15 11:49:43,380 | server.py:116 | fit progress: (2, 11.732673364257813, {'server_test_acc': 0.3976}, 198.48663825308904)
INFO flwr 2023-08-15 11:49:43,380 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 11:49:47,996 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2417422)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:50:46,012 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-15 11:50:46,221 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 11:50:46,352 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2417422)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2417699)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2417420)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2417417)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2417572)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2417603)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2417419)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2417698)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2417420)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417698)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2417572)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2417417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417699)[0m double free or corruption (fasttop)
E0815 11:50:47.321578633 2339703 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=2417419)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417603)[0m malloc_consolidate(): invalid chunk size
E0815 11:50:53.569444533 2574327 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-15 11:51:18,971 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:51:18,971 | fed_df.py:547 | Average fusion training loss : 0.6728436377048492, val accuracy : 0.42456000000000005, best val accuracy : 0.4454
INFO flwr 2023-08-15 11:51:18,973 | common.py:35 | Avg. local train loss : 8.072614207118749, train acc : 0.4605111111111111
INFO flwr 2023-08-15 11:51:21,652 | server.py:116 | fit progress: (3, 8.344421264648437, {'server_test_acc': 0.4309}, 296.7590945698321)
INFO flwr 2023-08-15 11:51:21,652 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 11:51:26,258 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:52:22,772 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-15 11:52:22,981 | fed_df.py:365 | Warm start at round 4
[2m[36m(launch_and_fit pid=2679744)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:52:23,112 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2679744)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2679748)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2679747)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2679749)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2679752)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2679754)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2679753)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2679751)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2679751)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2679747)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2679749)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2679752)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2679754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2679753)[0m malloc_consolidate(): invalid chunk size
E0815 11:52:24.678440148 2600377 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2679748)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:52:55,909 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:52:55,909 | fed_df.py:547 | Average fusion training loss : 0.6259689230918885, val accuracy : 0.44608, best val accuracy : 0.4686
INFO flwr 2023-08-15 11:52:55,911 | common.py:35 | Avg. local train loss : 7.958901309221982, train acc : 0.47761388888888884
INFO flwr 2023-08-15 11:52:58,547 | server.py:116 | fit progress: (4, 6.378399108886719, {'server_test_acc': 0.4623}, 393.6535005462356)
INFO flwr 2023-08-15 11:52:58,547 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 11:53:03,206 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:53:59,918 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-15 11:54:00,127 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 11:54:00,258 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2912683)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2912686)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2912688)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2912692)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2912693)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2912694)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2912690)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2912691)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2912692)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2912693)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2912690)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2912688)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2912683)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2912694)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2912686)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2912691)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:54:32,536 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:54:32,536 | fed_df.py:547 | Average fusion training loss : 0.5608192707300186, val accuracy : 0.45752, best val accuracy : 0.467
INFO flwr 2023-08-15 11:54:32,538 | common.py:35 | Avg. local train loss : 7.995473208278417, train acc : 0.4768861111111111
INFO flwr 2023-08-15 11:54:35,289 | server.py:116 | fit progress: (5, 5.4124001708984375, {'server_test_acc': 0.458}, 490.39634165680036)
INFO flwr 2023-08-15 11:54:35,290 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 11:54:39,860 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3132748)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:55:37,526 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-15 11:55:37,736 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 11:55:37,864 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3132753)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3132752)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3132747)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3132750)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3132751)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3132749)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3132748)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3132746)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3132746)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132750)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132747)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132749)[0m malloc_consolidate(): invalid chunk size
E0815 11:55:40.954247105 2832870 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-15 11:56:09,951 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:56:09,951 | fed_df.py:547 | Average fusion training loss : 0.5473310425281525, val accuracy : 0.44308, best val accuracy : 0.4658
INFO flwr 2023-08-15 11:56:09,953 | common.py:35 | Avg. local train loss : 8.215657868236304, train acc : 0.4631166666666667
INFO flwr 2023-08-15 11:56:12,593 | server.py:116 | fit progress: (6, 6.65557578125, {'server_test_acc': 0.4555}, 587.7000632937998)
INFO flwr 2023-08-15 11:56:12,593 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 11:56:17,460 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3353511)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:57:13,759 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-15 11:57:13,967 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 11:57:14,100 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3353507)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3353512)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3353513)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3353511)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3353514)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3353515)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3353516)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3353517)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3353514)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3353517)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3353512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353513)[0m malloc_consolidate(): invalid chunk size
E0815 11:57:15.353013660 3278825 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=3353507)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3353516)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:57:46,858 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:57:46,858 | fed_df.py:547 | Average fusion training loss : 0.5512409626245499, val accuracy : 0.41284, best val accuracy : 0.4442
INFO flwr 2023-08-15 11:57:46,860 | common.py:35 | Avg. local train loss : 8.40799492150545, train acc : 0.4520861111111112
INFO flwr 2023-08-15 11:57:49,485 | server.py:116 | fit progress: (7, 13.401976452636719, {'server_test_acc': 0.4455}, 684.5916090621613)
INFO flwr 2023-08-15 11:57:49,485 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 11:57:54,119 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3574398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574390)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574394)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574399)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:58:52,040 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 11:58:52,249 | fed_df.py:365 | Warm start at round 8
[2m[36m(launch_and_fit pid=3574397)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:58:52,377 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3574390)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3574388)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3574394)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3574396)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3574395)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3574397)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3574399)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3574398)[0m Fitting Client 0
E0815 11:58:52.842051138 3714961 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=3574396)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574388)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3574395)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:59:24,583 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:59:24,583 | fed_df.py:547 | Average fusion training loss : 0.5455621795654297, val accuracy : 0.38727999999999996, best val accuracy : 0.4132
INFO flwr 2023-08-15 11:59:24,585 | common.py:35 | Avg. local train loss : 9.03064575791359, train acc : 0.41262777777777776
INFO flwr 2023-08-15 11:59:27,220 | server.py:116 | fit progress: (8, 25.96657724609375, {'server_test_acc': 0.412}, 782.3271474470384)
INFO flwr 2023-08-15 11:59:27,221 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 11:59:31,839 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:00:29,729 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-15 12:00:29,938 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-15 12:00:30,067 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3794510)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3794513)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3794509)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3794517)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3794521)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3794506)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3794515)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3794520)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3794517)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3794509)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794513)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3794506)[0m double free or corruption (fasttop)
E0815 12:00:31.450460261 3938565 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3794515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794521)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794520)[0m double free or corruption (fasttop)
E0815 12:00:32.964124024 3938854 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3794510)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:01:02,168 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:01:02,169 | fed_df.py:547 | Average fusion training loss : 0.5457059147357941, val accuracy : 0.38211999999999996, best val accuracy : 0.3968
INFO flwr 2023-08-15 12:01:02,171 | common.py:35 | Avg. local train loss : 9.90827557295561, train acc : 0.3556722222222222
INFO flwr 2023-08-15 12:01:04,962 | server.py:116 | fit progress: (9, 80.13663388671876, {'server_test_acc': 0.3882}, 880.0688658840954)
INFO flwr 2023-08-15 12:01:04,962 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 12:01:09,704 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4015534)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015538)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:02:07,068 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-15 12:02:07,276 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 12:02:07,404 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4015534)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4015539)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4015520)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4015515)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4015531)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4015538)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4015528)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4015510)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4015520)[0m double free or corruption (fasttop)
E0815 12:02:08.366124881 3942352 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=4015515)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4015528)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015531)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015539)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015510)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:02:39,831 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:02:39,832 | fed_df.py:547 | Average fusion training loss : 0.5500029572248459, val accuracy : 0.33727999999999997, best val accuracy : 0.3506
INFO flwr 2023-08-15 12:02:39,834 | common.py:35 | Avg. local train loss : 10.893093678355216, train acc : 0.2952166666666666
INFO flwr 2023-08-15 12:02:42,476 | server.py:116 | fit progress: (10, 134.4475052734375, {'server_test_acc': 0.3484}, 977.5832614330575)
INFO flwr 2023-08-15 12:02:42,477 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 12:02:47,180 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=43389)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=43359)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:03:45,761 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-15 12:03:45,970 | fed_df.py:365 | Warm start at round 11
[2m[36m(launch_and_fit pid=43357)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=43380)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:03:46,100 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=43389)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=43329)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=43360)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=43357)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=43380)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=43359)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=43330)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=43331)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=43331)[0m double free or corruption (fasttop)
E0815 12:03:46.743862680 4157473 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=43329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=43330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=43360)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 12:06:00,233 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:06:00,233 | fed_df.py:547 | Average fusion training loss : 0.5460363860130311, val accuracy : 0.2748400000000001, best val accuracy : 0.2908
INFO flwr 2023-08-15 12:06:00,235 | common.py:35 | Avg. local train loss : 11.416532958298923, train acc : 0.26184444444444444
INFO flwr 2023-08-15 12:06:02,957 | server.py:116 | fit progress: (11, 217.7630515625, {'server_test_acc': 0.2891}, 1178.0640827720053)
INFO flwr 2023-08-15 12:06:02,957 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 12:06:07,839 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=300371)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=300383)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:07:05,901 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-15 12:07:06,112 | fed_df.py:365 | Warm start at round 12
[2m[36m(launch_and_fit pid=300384)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:07:06,244 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=300383)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=300371)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=300361)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=300370)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=300375)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=300381)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=300382)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=300384)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=300361)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=300375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=300382)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=300370)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=300381)[0m malloc_consolidate(): invalid chunk size
E0815 12:07:08.676042512  186242 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-15 12:07:38,579 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:07:38,580 | fed_df.py:547 | Average fusion training loss : 0.530337034702301, val accuracy : 0.25328, best val accuracy : 0.2656
INFO flwr 2023-08-15 12:07:38,582 | common.py:35 | Avg. local train loss : 12.071652753651144, train acc : 0.21638055555555555
INFO flwr 2023-08-15 12:07:41,280 | server.py:116 | fit progress: (12, 292.83448359375, {'server_test_acc': 0.2625}, 1276.3867219770327)
INFO flwr 2023-08-15 12:07:41,280 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 12:07:45,894 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=538065)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:08:41,561 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 12:08:41,770 | fed_df.py:365 | Warm start at round 13
[2m[36m(launch_and_fit pid=538056)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:08:41,900 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=538058)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=538065)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=538066)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=538063)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=538064)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=538056)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=538060)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=538061)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=538063)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=538064)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=538061)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=538058)[0m malloc_consolidate(): invalid chunk size
E0815 12:08:43.144969260  464626 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=538060)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=538066)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:09:14,333 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:09:14,333 | fed_df.py:547 | Average fusion training loss : 0.5313218224048615, val accuracy : 0.22896, best val accuracy : 0.248
INFO flwr 2023-08-15 12:09:14,335 | common.py:35 | Avg. local train loss : 12.179225187003611, train acc : 0.20809166666666665
INFO flwr 2023-08-15 12:09:16,979 | server.py:116 | fit progress: (13, 311.32755546875, {'server_test_acc': 0.247}, 1372.0858633280732)
INFO flwr 2023-08-15 12:09:16,979 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 12:09:21,591 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=758957)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=758964)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:10:17,289 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=758965)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:10:17,497 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 12:10:17,622 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=758957)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=758960)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=758958)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=758964)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=758965)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=758956)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=758961)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=758963)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=758960)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=758956)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=758963)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=758961)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=758958)[0m malloc_consolidate(): invalid chunk size
E0815 12:10:23.399463493  909040 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-15 12:10:50,382 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:10:50,383 | fed_df.py:547 | Average fusion training loss : 0.5219118437767029, val accuracy : 0.23992, best val accuracy : 0.2576
INFO flwr 2023-08-15 12:10:50,385 | common.py:35 | Avg. local train loss : 12.271524094045162, train acc : 0.20230555555555557
INFO flwr 2023-08-15 12:10:53,072 | server.py:116 | fit progress: (14, 266.0002890625, {'server_test_acc': 0.2578}, 1468.1788352709264)
INFO flwr 2023-08-15 12:10:53,072 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 12:10:57,728 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=981194)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=981476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=981191)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:11:53,398 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=981442)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:11:53,611 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-15 12:11:53,742 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=981191)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=981194)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=981402)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=981401)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=981442)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=981400)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=981476)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=981477)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=981400)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=981477)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=981402)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=981401)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:12:26,760 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:12:26,760 | fed_df.py:547 | Average fusion training loss : 0.5197324305772781, val accuracy : 0.2548, best val accuracy : 0.266
INFO flwr 2023-08-15 12:12:26,762 | common.py:35 | Avg. local train loss : 12.205112762749193, train acc : 0.2059916666666667
INFO flwr 2023-08-15 12:12:29,488 | server.py:116 | fit progress: (15, 251.957351953125, {'server_test_acc': 0.266}, 1564.5949390749447)
INFO flwr 2023-08-15 12:12:29,488 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 12:12:34,251 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:13:30,838 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-15 12:13:31,050 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-15 12:13:31,181 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1202438)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1202440)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1202431)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1202422)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1202439)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1202429)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1202435)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1202441)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1202431)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1202422)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202440)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202441)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202435)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202429)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:14:08,650 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:14:08,650 | fed_df.py:547 | Average fusion training loss : 0.5171080362796784, val accuracy : 0.21783999999999998, best val accuracy : 0.2408
INFO flwr 2023-08-15 12:14:08,652 | common.py:35 | Avg. local train loss : 12.208512446284296, train acc : 0.20679166666666668
INFO flwr 2023-08-15 12:14:11,266 | server.py:116 | fit progress: (16, 334.11681484375, {'server_test_acc': 0.2383}, 1666.3731312411837)
INFO flwr 2023-08-15 12:14:11,267 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 12:14:15,914 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1424254)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1424257)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:15:11,468 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-15 12:15:11,676 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 12:15:11,803 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1424257)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1424254)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1424557)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1424558)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1424559)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1424561)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1424560)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1424562)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1424558)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1424561)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1424560)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1424557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1424559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1424562)[0m double free or corruption (fasttop)
E0815 12:15:18.093967789 1570277 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0815 12:15:18.094123201 1570277 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0815 12:15:18.094139498 1570277 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-15 12:15:43,826 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:15:43,827 | fed_df.py:547 | Average fusion training loss : 0.5152762331962586, val accuracy : 0.23932000000000003, best val accuracy : 0.2478
INFO flwr 2023-08-15 12:15:43,829 | common.py:35 | Avg. local train loss : 12.126046761870386, train acc : 0.210225
INFO flwr 2023-08-15 12:15:46,517 | server.py:116 | fit progress: (17, 352.5262734375, {'server_test_acc': 0.2485}, 1761.6235274309292)
INFO flwr 2023-08-15 12:15:46,517 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 12:15:51,114 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:16:45,697 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-15 12:16:45,906 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 12:16:46,037 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1644901)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1644900)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1644902)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1644903)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1644909)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1644911)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1644912)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1644910)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1644903)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644901)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644902)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1644912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644911)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1644909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644900)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1644910)[0m malloc_consolidate(): invalid chunk size
E0815 12:16:48.584724132 1789697 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:17:18,924 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:17:18,924 | fed_df.py:547 | Average fusion training loss : 0.5253117871284485, val accuracy : 0.24468, best val accuracy : 0.2554
INFO flwr 2023-08-15 12:17:18,926 | common.py:35 | Avg. local train loss : 11.91962699815631, train acc : 0.22256111111111113
INFO flwr 2023-08-15 12:17:21,609 | server.py:116 | fit progress: (18, 349.4927625, {'server_test_acc': 0.2582}, 1856.7156806681305)
INFO flwr 2023-08-15 12:17:21,609 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 12:17:26,239 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1865055)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-15 12:18:24,216 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-15 12:18:24,426 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 12:18:24,580 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1865033)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1865040)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1865036)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1865055)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1865052)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1865047)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1865053)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1865054)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1865036)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865047)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1865033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865052)[0m malloc_consolidate(): invalid chunk size
E0815 12:18:25.689983230 2009124 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1865053)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1865054)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1865040)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:18:57,325 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:18:57,326 | fed_df.py:547 | Average fusion training loss : 0.5338415267467499, val accuracy : 0.2928, best val accuracy : 0.3068
INFO flwr 2023-08-15 12:18:57,327 | common.py:35 | Avg. local train loss : 11.400982441753149, train acc : 0.25545277777777775
INFO flwr 2023-08-15 12:19:00,021 | server.py:116 | fit progress: (19, 221.730433984375, {'server_test_acc': 0.3058}, 1955.1277121729217)
INFO flwr 2023-08-15 12:19:00,021 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 12:19:04,784 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2088471)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2088488)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2088470)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:20:04,273 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 12:20:04,483 | fed_df.py:365 | Warm start at round 20
[2m[36m(launch_and_fit pid=2088466)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:20:04,615 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2088468)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2088471)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2088470)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2088485)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2088488)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2088466)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2088487)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2088486)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2088487)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088485)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088486)[0m double free or corruption (fasttop)
E0815 12:20:08.388921305 2009970 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:20:37,100 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:20:37,101 | fed_df.py:547 | Average fusion training loss : 0.5408751065731049, val accuracy : 0.32648, best val accuracy : 0.3286
INFO flwr 2023-08-15 12:20:37,103 | common.py:35 | Avg. local train loss : 10.750421540439127, train acc : 0.2954388888888889
INFO flwr 2023-08-15 12:20:39,739 | server.py:116 | fit progress: (20, 169.192209765625, {'server_test_acc': 0.3301}, 2054.8456617388874)
INFO flwr 2023-08-15 12:20:39,739 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 12:20:44,399 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2320164)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320310)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:21:42,757 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-15 12:21:42,967 | fed_df.py:365 | Warm start at round 21
[2m[36m(launch_and_fit pid=2319844)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:21:43,101 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2319844)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2320164)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2320310)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2320230)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2320312)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2319982)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2320065)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2320150)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2320150)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320230)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2319982)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2320312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320065)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:22:15,696 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:22:15,697 | fed_df.py:547 | Average fusion training loss : 0.5707355883121491, val accuracy : 0.35976, best val accuracy : 0.3664
INFO flwr 2023-08-15 12:22:15,699 | common.py:35 | Avg. local train loss : 10.02651707828045, train acc : 0.33206388888888894
INFO flwr 2023-08-15 12:22:18,384 | server.py:116 | fit progress: (21, 108.10676640625, {'server_test_acc': 0.3765}, 2153.4908863510936)
INFO flwr 2023-08-15 12:22:18,384 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 12:22:22,984 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2581637)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:23:20,010 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2581779)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:23:20,221 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 12:23:20,349 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2581637)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2581499)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2581708)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2581709)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2581780)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2581849)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2581779)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2581781)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2581708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581781)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581709)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581849)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581499)[0m malloc_consolidate(): invalid chunk size
E0815 12:23:26.070622966 2237543 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:23:53,349 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:23:53,349 | fed_df.py:547 | Average fusion training loss : 0.5818897893428803, val accuracy : 0.37732, best val accuracy : 0.3836
INFO flwr 2023-08-15 12:23:53,351 | common.py:35 | Avg. local train loss : 9.327025761455296, train acc : 0.3784861111111111
INFO flwr 2023-08-15 12:23:56,073 | server.py:116 | fit progress: (22, 63.98915947265625, {'server_test_acc': 0.3868}, 2251.180118924007)
INFO flwr 2023-08-15 12:23:56,074 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 12:24:00,757 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:24:57,513 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 12:24:57,722 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 12:24:57,856 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2804243)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2804249)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2804247)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2804248)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2804254)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2804257)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2804256)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2804252)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2804257)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2804249)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2804248)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2804247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2804243)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2804254)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2804256)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2804252)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:25:30,778 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:25:30,779 | fed_df.py:547 | Average fusion training loss : 0.5453687160015106, val accuracy : 0.37855999999999995, best val accuracy : 0.3822
INFO flwr 2023-08-15 12:25:30,781 | common.py:35 | Avg. local train loss : 9.60659181177616, train acc : 0.3700416666666667
INFO flwr 2023-08-15 12:25:33,452 | server.py:116 | fit progress: (23, 87.058519921875, {'server_test_acc': 0.3842}, 2348.558693116065)
INFO flwr 2023-08-15 12:25:33,452 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 12:25:38,382 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:26:37,660 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 12:26:37,871 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 12:26:37,998 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3024652)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3024644)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3024661)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3024657)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3024654)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3024663)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3024660)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3024653)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3024644)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3024661)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3024663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024660)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024654)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3024652)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3024653)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024657)[0m malloc_consolidate(): invalid chunk size
E0815 12:26:42.238872067 3171481 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:27:10,532 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:27:10,533 | fed_df.py:547 | Average fusion training loss : 0.5449405410289765, val accuracy : 0.38112, best val accuracy : 0.3908
INFO flwr 2023-08-15 12:27:10,534 | common.py:35 | Avg. local train loss : 9.506119540333748, train acc : 0.37502222222222215
INFO flwr 2023-08-15 12:27:13,226 | server.py:116 | fit progress: (24, 78.08081982421875, {'server_test_acc': 0.3952}, 2448.3329422809184)
INFO flwr 2023-08-15 12:27:13,226 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 12:27:17,943 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3246129)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:28:15,298 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-15 12:28:15,508 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 12:28:15,638 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3246136)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3246140)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3246110)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3246126)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3246129)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3246137)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3246069)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3246138)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3246140)[0m malloc_consolidate(): invalid chunk size
E0815 12:28:17.011138783 3386827 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3246110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3246136)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3246137)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3246138)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3246069)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3246126)[0m malloc_consolidate(): invalid chunk size
E0815 12:28:18.518567257 3387365 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:28:48,108 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:28:48,109 | fed_df.py:547 | Average fusion training loss : 0.5365970895290375, val accuracy : 0.37548000000000004, best val accuracy : 0.3784
INFO flwr 2023-08-15 12:28:48,110 | common.py:35 | Avg. local train loss : 9.453662484884262, train acc : 0.3820583333333333
INFO flwr 2023-08-15 12:28:50,757 | server.py:116 | fit progress: (25, 99.7529, {'server_test_acc': 0.3827}, 2545.863383750897)
INFO flwr 2023-08-15 12:28:50,757 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 12:28:55,409 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3466539)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3466544)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:29:53,928 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3466540)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3466542)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3466545)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:29:54,142 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 12:29:54,298 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3466534)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3466539)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3466542)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3466541)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3466540)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3466545)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3466544)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3466546)[0m Fitting Client 12
E0815 12:29:55.623269085 3606987 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3466541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3466546)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3466534)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:30:26,826 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:30:26,826 | fed_df.py:547 | Average fusion training loss : 0.5408022255897522, val accuracy : 0.38428, best val accuracy : 0.3904
INFO flwr 2023-08-15 12:30:26,828 | common.py:35 | Avg. local train loss : 9.320344051718711, train acc : 0.3898166666666667
INFO flwr 2023-08-15 12:30:29,540 | server.py:116 | fit progress: (26, 71.70338896484375, {'server_test_acc': 0.3942}, 2644.6464087041095)
INFO flwr 2023-08-15 12:30:29,540 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 12:30:34,358 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:31:33,248 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3686630)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:31:33,458 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-15 12:31:33,590 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3686632)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3686630)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3686629)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3686631)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3686633)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3686625)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3686641)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3686640)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3686631)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686633)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686629)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686640)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686641)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3686625)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3686632)[0m malloc_consolidate(): invalid chunk size
E0815 12:31:37.658900302 3833227 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:32:06,629 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:32:06,630 | fed_df.py:547 | Average fusion training loss : 0.5263647274971008, val accuracy : 0.38180000000000003, best val accuracy : 0.3948
INFO flwr 2023-08-15 12:32:06,632 | common.py:35 | Avg. local train loss : 9.509741185605526, train acc : 0.37873888888888885
INFO flwr 2023-08-15 12:32:09,382 | server.py:116 | fit progress: (27, 94.48627890625, {'server_test_acc': 0.3905}, 2744.4886867241003)
INFO flwr 2023-08-15 12:32:09,382 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 12:32:14,147 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:33:11,108 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-15 12:33:11,318 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-15 12:33:11,446 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3907884)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3908295)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3908100)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3907838)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3908059)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3907860)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3908109)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3908293)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3908100)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3907838)[0m malloc_consolidate(): invalid chunk size
E0815 12:33:12.924494799 4050623 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3907860)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3907884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3908295)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3908059)[0m malloc_consolidate(): invalid chunk size
E0815 12:33:14.329612738 4050947 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3908293)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3908109)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:33:44,037 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:33:44,038 | fed_df.py:547 | Average fusion training loss : 0.5341006069183349, val accuracy : 0.37884, best val accuracy : 0.3868
INFO flwr 2023-08-15 12:33:44,039 | common.py:35 | Avg. local train loss : 9.494127556681633, train acc : 0.37907222222222225
INFO flwr 2023-08-15 12:33:46,689 | server.py:116 | fit progress: (28, 66.09694384765625, {'server_test_acc': 0.3931}, 2841.7960997000337)
INFO flwr 2023-08-15 12:33:46,689 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 12:33:51,359 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4128585)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:34:49,679 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 12:34:49,889 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-15 12:34:50,020 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4128590)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4128591)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4128585)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4128587)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4128586)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4128588)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4128581)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4128589)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4128590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4128586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4128581)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4128588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4128589)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4128587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4128591)[0m malloc_consolidate(): invalid chunk size
E0815 12:34:52.777476666 4054261 chttp2_transport.cc:1079]             ipv4:145.136.62.23:48721: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:35:23,008 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:35:23,008 | fed_df.py:547 | Average fusion training loss : 0.5341380844116211, val accuracy : 0.38564, best val accuracy : 0.3942
INFO flwr 2023-08-15 12:35:23,010 | common.py:35 | Avg. local train loss : 9.560667368024587, train acc : 0.37520555555555557
INFO flwr 2023-08-15 12:35:25,656 | server.py:116 | fit progress: (29, 95.4302033203125, {'server_test_acc': 0.3974}, 2940.7629499682225)
INFO flwr 2023-08-15 12:35:25,656 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 12:35:30,318 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=155984)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=155978)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=155987)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:36:27,648 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 12:36:27,860 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 12:36:27,991 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=155980)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=155984)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=155986)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=155982)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=155985)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=155978)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=155988)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=155987)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=155985)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=155986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=155982)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=155988)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=155980)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:37:00,717 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:37:00,717 | fed_df.py:547 | Average fusion training loss : 0.5657463681697845, val accuracy : 0.4008, best val accuracy : 0.4116
INFO flwr 2023-08-15 12:37:00,719 | common.py:35 | Avg. local train loss : 9.194129990786314, train acc : 0.40015555555555554
INFO flwr 2023-08-15 12:37:03,447 | server.py:116 | fit progress: (30, 121.618312890625, {'server_test_acc': 0.4135}, 3038.5538492691703)
INFO flwr 2023-08-15 12:37:03,447 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 12:37:03,447 | server.py:144 | FL finished in 3038.5542034721
INFO flwr 2023-08-15 12:37:03,448 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 12:37:03,449 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 12:37:03,449 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 7.919619067382812), (2, 11.732673364257813), (3, 8.344421264648437), (4, 6.378399108886719), (5, 5.4124001708984375), (6, 6.65557578125), (7, 13.401976452636719), (8, 25.96657724609375), (9, 80.13663388671876), (10, 134.4475052734375), (11, 217.7630515625), (12, 292.83448359375), (13, 311.32755546875), (14, 266.0002890625), (15, 251.957351953125), (16, 334.11681484375), (17, 352.5262734375), (18, 349.4927625), (19, 221.730433984375), (20, 169.192209765625), (21, 108.10676640625), (22, 63.98915947265625), (23, 87.058519921875), (24, 78.08081982421875), (25, 99.7529), (26, 71.70338896484375), (27, 94.48627890625), (28, 66.09694384765625), (29, 95.4302033203125), (30, 121.618312890625)]
INFO flwr 2023-08-15 12:37:03,449 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.3553), (2, 0.3976), (3, 0.4309), (4, 0.4623), (5, 0.458), (6, 0.4555), (7, 0.4455), (8, 0.412), (9, 0.3882), (10, 0.3484), (11, 0.2891), (12, 0.2625), (13, 0.247), (14, 0.2578), (15, 0.266), (16, 0.2383), (17, 0.2485), (18, 0.2582), (19, 0.3058), (20, 0.3301), (21, 0.3765), (22, 0.3868), (23, 0.3842), (24, 0.3952), (25, 0.3827), (26, 0.3942), (27, 0.3905), (28, 0.3931), (29, 0.3974), (30, 0.4135)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn23: task 0: Aborted
srun: Terminating StepId=3339003.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3339003
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:50:58
CPU Efficiency: 11.80% of 15:40:12 core-walltime
Job Wall-clock time: 00:52:14
Memory Utilized: 58.95 GB
Memory Efficiency: 49.12% of 120.00 GB
