-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:10000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:50
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.5
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=10000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3339010/1692092717_207617562', seed=42, img_per_thread=555)
will save 10000 patches in /scratch-local/sunnys.3339010/1692092717_207617562/single_img_crops/crops
10000 took 0.18min with 18 threads
---------
Simulating feddf training
srun: Job 3339010 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=3339010.1
INFO simulate 2023-08-15 11:45:43,665 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 11:45:43,666 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3339010/1692092717_207617562/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3339010/1692092717_207617562/cifar-10-python.tar.gz to /scratch-local/sunnys.3339010/1692092717_207617562
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [256 249 217 265 244 275 235 226 275 258]
INFO flwr 2023-08-15 11:46:10,536 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 11:46:12,756	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8267 [39m[22m
INFO flwr 2023-08-15 11:46:16,132 | app.py:179 | Flower VCE: Ray initialized with resources: {'object_store_memory': 61847529062.0, 'GPU': 1.0, 'CPU': 18.0, 'memory': 103079215104.0, 'node:145.136.62.23': 1.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-15 11:46:16,132 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 11:46:16,132 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 11:46:16,132 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 11:46:24,872 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-15 11:46:24,872 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 11:46:29,706 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1975770)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:47:32,589 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-15 11:47:32,799 | fed_df.py:365 | Warm start at round 1
[2m[36m(launch_and_fit pid=1975771)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:47:32,931 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1975753)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1975755)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1975756)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1975763)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1975770)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1975762)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1975771)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1975761)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1975753)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1975761)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975763)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1975762)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1975755)[0m corrupted size vs. prev_size in fastbins
E0815 11:47:38.727473734 2125231 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 11:48:03.018365344 2182153 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-15 11:48:04,555 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:48:04,556 | fed_df.py:547 | Average fusion training loss : 0.01939199022576213, val accuracy : 0.42812, best val accuracy : 0.4448
INFO flwr 2023-08-15 11:48:04,558 | common.py:35 | Avg. local train loss : 8.680946834385393, train acc : 0.39919166666666667
INFO flwr 2023-08-15 11:48:07,207 | server.py:116 | fit progress: (1, 1.5402157348632812, {'server_test_acc': 0.4539}, 102.33447871776298)
INFO flwr 2023-08-15 11:48:07,207 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 11:48:11,879 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:49:08,284 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2197010)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:49:08,495 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-15 11:49:08,625 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2197003)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2197013)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2197014)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2197008)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2197009)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2197016)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2197010)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2197015)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2197014)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197009)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197013)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2197015)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2197008)[0m malloc_consolidate(): invalid chunk size
E0815 11:49:11.478519124 2342915 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-15 11:49:40,883 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:49:40,883 | fed_df.py:547 | Average fusion training loss : 0.01195216673798859, val accuracy : 0.56172, best val accuracy : 0.5728
INFO flwr 2023-08-15 11:49:40,885 | common.py:35 | Avg. local train loss : 7.223871687054634, train acc : 0.5556805555555555
INFO flwr 2023-08-15 11:49:43,482 | server.py:116 | fit progress: (2, 1.3521826202392577, {'server_test_acc': 0.5748}, 198.6098659397103)
INFO flwr 2023-08-15 11:49:43,482 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 11:49:48,148 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2417758)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:50:46,087 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2417726)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:50:46,299 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 11:50:46,425 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2417758)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2417728)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2417756)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2417754)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2417755)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2417726)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2417757)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2417727)[0m Fitting Client 5
E0815 11:50:46.823148718 2571375 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=2417728)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2417757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417754)[0m malloc_consolidate(): invalid chunk size
E0815 11:50:47.602963211 2574202 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2417727)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417755)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2417756)[0m double free or corruption (fasttop)
E0815 11:50:49.111798853 2575027 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-15 11:51:20,815 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:51:20,815 | fed_df.py:547 | Average fusion training loss : 0.01063209692016244, val accuracy : 0.61908, best val accuracy : 0.6238
INFO flwr 2023-08-15 11:51:20,817 | common.py:35 | Avg. local train loss : 6.273272334784269, train acc : 0.6587805555555555
INFO flwr 2023-08-15 11:51:23,498 | server.py:116 | fit progress: (3, 1.3406781555175782, {'server_test_acc': 0.6161}, 298.6257774787955)
INFO flwr 2023-08-15 11:51:23,498 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 11:51:28,226 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2680646)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:52:24,409 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-15 11:52:24,618 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 11:52:24,746 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2680648)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2680646)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2680647)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2680645)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2680818)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2680855)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2680875)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2680733)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2680855)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2680648)[0m double free or corruption (fasttop)
E0815 11:52:25.838343157 2583439 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=2680875)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2680647)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2680645)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2680733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2680818)[0m double free or corruption (fasttop)
E0815 11:52:43.913239225 2874503 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-15 11:52:57,656 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:52:57,657 | fed_df.py:547 | Average fusion training loss : 0.01410369176324457, val accuracy : 0.64084, best val accuracy : 0.6546
INFO flwr 2023-08-15 11:52:57,659 | common.py:35 | Avg. local train loss : 5.701307031512259, train acc : 0.7182361111111112
INFO flwr 2023-08-15 11:53:00,387 | server.py:116 | fit progress: (4, 1.3398211120605468, {'server_test_acc': 0.6476}, 395.51520177489147)
INFO flwr 2023-08-15 11:53:00,388 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 11:53:05,061 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2913203)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:54:01,581 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-15 11:54:01,790 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 11:54:01,924 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2913196)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2913206)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2913205)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2913202)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2913203)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2913204)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2913207)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2913208)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2913196)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2913206)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2913207)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2913205)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2913204)[0m double free or corruption (fasttop)
E0815 11:54:03.909045040 3057500 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=2913208)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2913202)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:54:34,097 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:54:34,098 | fed_df.py:547 | Average fusion training loss : 0.01370176902320236, val accuracy : 0.6746000000000001, best val accuracy : 0.6832
INFO flwr 2023-08-15 11:54:34,100 | common.py:35 | Avg. local train loss : 5.402107619866729, train acc : 0.7494111111111111
INFO flwr 2023-08-15 11:54:36,739 | server.py:116 | fit progress: (5, 1.3619908508300782, {'server_test_acc': 0.6753}, 491.866996854078)
INFO flwr 2023-08-15 11:54:36,739 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 11:54:41,428 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3133229)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3133233)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:55:38,778 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3133236)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:55:38,989 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 11:55:39,116 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3133229)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3133233)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3133235)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3133236)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3133231)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3133234)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3133238)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3133237)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3133235)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3133234)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3133238)[0m double free or corruption (fasttop)
E0815 11:55:40.510348888 3058418 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3133231)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3133237)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:56:11,369 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:56:11,370 | fed_df.py:547 | Average fusion training loss : 0.01422105192579329, val accuracy : 0.68624, best val accuracy : 0.698
INFO flwr 2023-08-15 11:56:11,372 | common.py:35 | Avg. local train loss : 5.131661991402507, train acc : 0.7792111111111112
INFO flwr 2023-08-15 11:56:14,260 | server.py:116 | fit progress: (6, 1.4363565460205079, {'server_test_acc': 0.6932}, 589.387524865102)
INFO flwr 2023-08-15 11:56:14,260 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 11:56:18,935 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3354000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354006)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:57:15,333 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-15 11:57:15,542 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 11:57:15,672 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3354000)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3354006)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3354011)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3354012)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3354007)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3354016)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3354014)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3354015)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3354012)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354014)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354015)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3354011)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354007)[0m double free or corruption (fasttop)
E0815 11:57:18.741353047 3501066 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-15 11:57:48,071 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:57:48,072 | fed_df.py:547 | Average fusion training loss : 0.014197672309353948, val accuracy : 0.6983600000000001, best val accuracy : 0.7128
INFO flwr 2023-08-15 11:57:48,074 | common.py:35 | Avg. local train loss : 5.035275781154632, train acc : 0.7929666666666668
E0815 11:57:49.586109548 3567768 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-15 11:57:50,790 | server.py:116 | fit progress: (7, 1.5053358581542968, {'server_test_acc': 0.7054}, 685.9179155067541)
INFO flwr 2023-08-15 11:57:50,790 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 11:57:55,465 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3574876)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:58:51,520 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 11:58:51,730 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 11:58:51,860 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3574874)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3574876)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3574889)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3574890)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3574893)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3574896)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3574894)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3574895)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3574874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574893)[0m malloc_consolidate(): invalid chunk size
E0815 11:58:54.096911786 3717319 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=3574889)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574894)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3574895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3574896)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:59:24,411 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:59:24,412 | fed_df.py:547 | Average fusion training loss : 0.012619793568272144, val accuracy : 0.70136, best val accuracy : 0.7094
INFO flwr 2023-08-15 11:59:24,414 | common.py:35 | Avg. local train loss : 4.985138387978077, train acc : 0.8007416666666667
INFO flwr 2023-08-15 11:59:27,111 | server.py:116 | fit progress: (8, 1.577997592163086, {'server_test_acc': 0.7033}, 782.2393454001285)
INFO flwr 2023-08-15 11:59:27,112 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 11:59:31,855 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3794503)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:00:29,373 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3794519)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:00:29,598 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-15 12:00:29,728 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3794503)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3794512)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3794519)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3794523)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3794511)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3794518)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3794522)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3794514)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3794518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794523)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3794522)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794512)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3794511)[0m double free or corruption (fasttop)
E0815 12:00:33.546172404 3719225 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-15 12:01:02,138 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:01:02,139 | fed_df.py:547 | Average fusion training loss : 0.012767652303446085, val accuracy : 0.7134, best val accuracy : 0.723
INFO flwr 2023-08-15 12:01:02,141 | common.py:35 | Avg. local train loss : 4.890771784633398, train acc : 0.8118249999999999
INFO flwr 2023-08-15 12:01:04,959 | server.py:116 | fit progress: (9, 1.6214528564453126, {'server_test_acc': 0.7165}, 880.0867656869814)
INFO flwr 2023-08-15 12:01:04,959 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 12:01:09,714 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:02:07,942 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4015544)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:02:08,154 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 12:02:08,284 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4015535)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4015521)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4015530)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4015529)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4015542)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4015544)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4015526)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4015540)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4015521)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015542)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4015530)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015526)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015529)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4015535)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4015540)[0m double free or corruption (fasttop)
E0815 12:02:31.993379751   11104 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-15 12:02:40,808 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:02:40,809 | fed_df.py:547 | Average fusion training loss : 0.012490084221120924, val accuracy : 0.7206, best val accuracy : 0.7338
INFO flwr 2023-08-15 12:02:40,811 | common.py:35 | Avg. local train loss : 4.794856014847756, train acc : 0.8242777777777777
INFO flwr 2023-08-15 12:02:43,512 | server.py:116 | fit progress: (10, 1.590169436645508, {'server_test_acc': 0.7292}, 978.6402445710264)
INFO flwr 2023-08-15 12:02:43,513 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 12:02:48,215 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:03:45,368 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-15 12:03:45,580 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-15 12:03:45,709 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=44112)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=44195)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=44201)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=44202)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=44233)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=44261)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=44231)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=44265)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=44265)[0m malloc_consolidate(): invalid chunk size
E0815 12:03:46.277560628   16300 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=44261)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=44112)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=44233)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=44195)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=44202)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=44231)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=44201)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:06:00,229 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:06:00,230 | fed_df.py:547 | Average fusion training loss : 0.011287714250851422, val accuracy : 0.72444, best val accuracy : 0.7392
INFO flwr 2023-08-15 12:06:00,232 | common.py:35 | Avg. local train loss : 4.675648175925017, train acc : 0.8367194444444445
INFO flwr 2023-08-15 12:06:02,954 | server.py:116 | fit progress: (11, 1.7101100860595704, {'server_test_acc': 0.7265}, 1178.081678306684)
INFO flwr 2023-08-15 12:06:02,954 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 12:06:07,775 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:07:06,966 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=300374)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=300372)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:07:07,179 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 12:07:07,309 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=300369)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=300352)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=300373)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=300362)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=300365)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=300366)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=300372)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=300374)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=300362)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=300373)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=300365)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=300369)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=300352)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=300366)[0m malloc_consolidate(): invalid chunk size
E0815 12:07:11.408710405  185331 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:07:39,641 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:07:39,641 | fed_df.py:547 | Average fusion training loss : 0.01077908141631633, val accuracy : 0.7232000000000001, best val accuracy : 0.739
INFO flwr 2023-08-15 12:07:39,643 | common.py:35 | Avg. local train loss : 4.622484407946468, train acc : 0.8446194444444445
INFO flwr 2023-08-15 12:07:42,338 | server.py:116 | fit progress: (12, 1.7037653350830078, {'server_test_acc': 0.7398}, 1277.465518981684)
INFO flwr 2023-08-15 12:07:42,338 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 12:07:47,063 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=539833)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=539830)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=539831)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=539970)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:08:42,200 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 12:08:42,411 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 12:08:42,541 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=539831)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=539986)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=539970)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=539987)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=539830)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=539833)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=539985)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=539829)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=539986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=539829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=539985)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=539987)[0m malloc_consolidate(): invalid chunk size
E0815 12:08:46.427152592  683062 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:09:15,004 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:09:15,005 | fed_df.py:547 | Average fusion training loss : 0.01141709932172671, val accuracy : 0.7225999999999999, best val accuracy : 0.734
INFO flwr 2023-08-15 12:09:15,007 | common.py:35 | Avg. local train loss : 4.5634785849601025, train acc : 0.8505722222222223
INFO flwr 2023-08-15 12:09:17,686 | server.py:116 | fit progress: (13, 1.6912146209716796, {'server_test_acc': 0.7331}, 1372.8138535739854)
INFO flwr 2023-08-15 12:09:17,686 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 12:09:22,367 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=760049)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:10:18,128 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-15 12:10:18,340 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 12:10:18,472 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=760050)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=760121)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=760123)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=760049)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=759974)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=760051)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=760048)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=760122)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=760123)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=760051)[0m malloc_consolidate(): invalid chunk size
E0815 12:10:19.106801777  686187 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=760121)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=759974)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=760048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=760122)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=760050)[0m malloc_consolidate(): invalid chunk size
E0815 12:10:33.276886445  931308 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:10:51,212 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:10:51,213 | fed_df.py:547 | Average fusion training loss : 0.010979620665311813, val accuracy : 0.7314, best val accuracy : 0.7538
INFO flwr 2023-08-15 12:10:51,215 | common.py:35 | Avg. local train loss : 4.423595076426864, train acc : 0.8614888888888889
INFO flwr 2023-08-15 12:10:53,959 | server.py:116 | fit progress: (14, 1.6873511291503906, {'server_test_acc': 0.7499}, 1469.086531824898)
INFO flwr 2023-08-15 12:10:53,959 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 12:10:58,682 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:11:53,399 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-15 12:11:53,611 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-15 12:11:53,767 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=982616)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=982706)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=982745)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=982749)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=982747)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=982748)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=982615)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=982746)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=982616)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=982749)[0m double free or corruption (fasttop)
E0815 12:11:54.586310030 1120148 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=982745)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=982748)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=982746)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=982706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=982615)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=982747)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:12:26,761 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:12:26,762 | fed_df.py:547 | Average fusion training loss : 0.009958648049738257, val accuracy : 0.7375999999999999, best val accuracy : 0.7544
INFO flwr 2023-08-15 12:12:26,764 | common.py:35 | Avg. local train loss : 4.495801467821002, train acc : 0.8529694444444443
INFO flwr 2023-08-15 12:12:29,499 | server.py:116 | fit progress: (15, 1.7032088500976563, {'server_test_acc': 0.7513}, 1564.6270118588582)
INFO flwr 2023-08-15 12:12:29,499 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 12:12:34,286 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:13:31,285 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1202443)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1202436)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:13:31,498 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-15 12:13:31,631 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1202436)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1202442)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1202427)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1202437)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1202443)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1202445)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1202444)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1202446)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1202442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202446)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202437)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202445)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202444)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1202427)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:14:04,409 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:14:04,409 | fed_df.py:547 | Average fusion training loss : 0.00979852984752506, val accuracy : 0.7334799999999999, best val accuracy : 0.755
INFO flwr 2023-08-15 12:14:04,412 | common.py:35 | Avg. local train loss : 4.334683618322014, train acc : 0.8705361111111111
INFO flwr 2023-08-15 12:14:07,085 | server.py:116 | fit progress: (16, 1.7017422729492186, {'server_test_acc': 0.7512}, 1662.2132614371367)
INFO flwr 2023-08-15 12:14:07,086 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 12:14:11,759 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1422615)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1422924)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:15:07,561 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1422821)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:15:07,772 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 12:15:07,900 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1422615)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1422752)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1422821)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1422822)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1422960)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1422958)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1422959)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1422924)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1422958)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1422959)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1422822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1422960)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1422752)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:15:45,721 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:15:45,721 | fed_df.py:547 | Average fusion training loss : 0.01010522292694077, val accuracy : 0.7382399999999999, best val accuracy : 0.7642
INFO flwr 2023-08-15 12:15:45,723 | common.py:35 | Avg. local train loss : 4.276323276013136, train acc : 0.877938888888889
INFO flwr 2023-08-15 12:15:48,352 | server.py:116 | fit progress: (17, 1.724058773803711, {'server_test_acc': 0.7605}, 1763.4802816119045)
INFO flwr 2023-08-15 12:15:48,353 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 12:15:53,019 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:16:47,260 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1645689)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1645687)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:16:47,474 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 12:16:47,603 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1645687)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1645686)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1645688)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1645689)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1645698)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1645699)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1645701)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1645700)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1645699)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1645698)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1645686)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1645700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1645701)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1645688)[0m malloc_consolidate(): invalid chunk size
E0815 12:16:51.633820065 1794736 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:17:19,817 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:17:19,817 | fed_df.py:547 | Average fusion training loss : 0.010408510585781187, val accuracy : 0.7321200000000001, best val accuracy : 0.756
INFO flwr 2023-08-15 12:17:19,820 | common.py:35 | Avg. local train loss : 4.309135467559099, train acc : 0.8741555555555555
INFO flwr 2023-08-15 12:17:22,534 | server.py:116 | fit progress: (18, 1.6903778503417968, {'server_test_acc': 0.7594}, 1857.6618698337115)
INFO flwr 2023-08-15 12:17:22,534 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 12:17:27,226 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1865991)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:18:24,749 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-15 12:18:24,959 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 12:18:25,089 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1865997)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1865991)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1865989)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1865996)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1866003)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1865997)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1866004)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1866006)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1866005)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1866004)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1865996)[0m malloc_consolidate(): invalid chunk size
E0815 12:18:26.144474862 1796893 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1865989)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1866006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1866003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1866005)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:18:57,715 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:18:57,715 | fed_df.py:547 | Average fusion training loss : 0.00892473961878568, val accuracy : 0.74888, best val accuracy : 0.762
INFO flwr 2023-08-15 12:18:57,717 | common.py:35 | Avg. local train loss : 4.232269112020731, train acc : 0.8817222222222223
INFO flwr 2023-08-15 12:19:00,406 | server.py:116 | fit progress: (19, 1.7056174285888672, {'server_test_acc': 0.7583}, 1955.5338453659788)
INFO flwr 2023-08-15 12:19:00,406 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 12:19:05,141 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:20:03,635 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 12:20:03,846 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 12:20:03,976 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2088491)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2088493)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2088495)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2088501)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2088509)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2088498)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2088505)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2088510)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2088493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088501)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2088509)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088491)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088495)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2088505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2088510)[0m double free or corruption (fasttop)
E0815 12:20:06.751724836 2233769 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2088498)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 12:20:37,124 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:20:37,124 | fed_df.py:547 | Average fusion training loss : 0.008649547710083425, val accuracy : 0.7463199999999999, best val accuracy : 0.7646
INFO flwr 2023-08-15 12:20:37,127 | common.py:35 | Avg. local train loss : 4.186127515509725, train acc : 0.88455
INFO flwr 2023-08-15 12:20:39,827 | server.py:116 | fit progress: (20, 1.6994690124511718, {'server_test_acc': 0.7651}, 2054.95527988486)
INFO flwr 2023-08-15 12:20:39,828 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 12:20:44,545 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:21:43,126 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-15 12:21:43,338 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 12:21:43,466 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2320192)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2320453)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2320392)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2320599)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2320217)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2320621)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2320521)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2320635)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2320192)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320392)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320453)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320521)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2320217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320599)[0m double free or corruption (fasttop)
E0815 12:21:45.807386288 2234175 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2320635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2320621)[0m malloc_consolidate(): invalid chunk size
E0815 12:22:10.100718116 2497236 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:22:21,222 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:22:21,223 | fed_df.py:547 | Average fusion training loss : 0.008480761461891233, val accuracy : 0.75892, best val accuracy : 0.77
INFO flwr 2023-08-15 12:22:21,225 | common.py:35 | Avg. local train loss : 4.228378157317638, train acc : 0.8809138888888889
INFO flwr 2023-08-15 12:22:23,928 | server.py:116 | fit progress: (21, 1.6690241729736328, {'server_test_acc': 0.7716}, 2159.05552825192)
INFO flwr 2023-08-15 12:22:23,928 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 12:22:28,630 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:23:22,192 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-15 12:23:22,403 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 12:23:22,534 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2585018)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2585025)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2585016)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2585024)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2585027)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2585026)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2585029)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2585028)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2585018)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2585025)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2585027)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2585029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2585024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2585016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2585026)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2585028)[0m malloc_consolidate(): invalid chunk size
E0815 12:23:25.047035310 2732396 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:23:55,015 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:23:55,015 | fed_df.py:547 | Average fusion training loss : 0.007878283624071628, val accuracy : 0.7589599999999999, best val accuracy : 0.7718
INFO flwr 2023-08-15 12:23:55,017 | common.py:35 | Avg. local train loss : 4.1200099181383845, train acc : 0.890225
INFO flwr 2023-08-15 12:23:57,750 | server.py:116 | fit progress: (22, 1.7094560394287108, {'server_test_acc': 0.7639}, 2252.877808544785)
INFO flwr 2023-08-15 12:23:57,750 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 12:24:02,377 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:24:57,839 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 12:24:58,049 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 12:24:58,179 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2805236)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2805237)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2805240)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2805238)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2805241)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2805242)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2805244)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2805243)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2805236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2805240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2805243)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2805237)[0m malloc_consolidate(): invalid chunk size
E0815 12:25:00.445477194 2732799 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2805241)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2805238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2805242)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2805244)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:25:30,904 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:25:30,904 | fed_df.py:547 | Average fusion training loss : 0.008763029817957431, val accuracy : 0.7620800000000001, best val accuracy : 0.7762
INFO flwr 2023-08-15 12:25:30,906 | common.py:35 | Avg. local train loss : 4.14179173707962, train acc : 0.8889138888888888
INFO flwr 2023-08-15 12:25:33,555 | server.py:116 | fit progress: (23, 1.6300400115966798, {'server_test_acc': 0.7736}, 2348.683052985929)
INFO flwr 2023-08-15 12:25:33,555 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 12:25:38,391 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3024662)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024659)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:26:36,530 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 12:26:36,742 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 12:26:36,871 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3024648)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3024658)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3024659)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3024662)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3024649)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3024656)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3024664)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3024665)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3024664)[0m double free or corruption (fasttop)
E0815 12:26:37.380019907 2950004 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3024665)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024649)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024656)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3024658)[0m double free or corruption (fasttop)
E0815 12:26:39.345469471 3168751 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:27:09,739 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:27:09,740 | fed_df.py:547 | Average fusion training loss : 0.008473100306466221, val accuracy : 0.7623199999999999, best val accuracy : 0.7706
INFO flwr 2023-08-15 12:27:09,742 | common.py:35 | Avg. local train loss : 4.110858086496592, train acc : 0.8917555555555556
INFO flwr 2023-08-15 12:27:12,435 | server.py:116 | fit progress: (24, 1.6539535949707032, {'server_test_acc': 0.7745}, 2447.5628822371364)
INFO flwr 2023-08-15 12:27:12,435 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 12:27:17,081 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:28:15,773 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3245641)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:28:15,986 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 12:28:16,117 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3245637)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3245642)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3245639)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3245641)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3245640)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3245638)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3245635)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3245643)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3245638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3245639)[0m double free or corruption (fasttop)
E0815 12:28:17.319403341 3169365 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 12:28:17.319511324 3169365 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3245643)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3245642)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3245640)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3245635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3245637)[0m double free or corruption (fasttop)
E0815 12:28:26.162238242 3406502 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:28:48,926 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:28:48,926 | fed_df.py:547 | Average fusion training loss : 0.009161000051535665, val accuracy : 0.7608400000000001, best val accuracy : 0.7688
INFO flwr 2023-08-15 12:28:48,928 | common.py:35 | Avg. local train loss : 4.043342725932598, train acc : 0.8975361111111111
INFO flwr 2023-08-15 12:28:51,613 | server.py:116 | fit progress: (25, 1.6555341827392578, {'server_test_acc': 0.7682}, 2546.7410794678144)
INFO flwr 2023-08-15 12:28:51,613 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 12:28:56,303 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:29:53,702 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-15 12:29:53,913 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 12:29:54,045 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3467024)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3467028)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3467029)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3467031)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3467030)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3467027)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3467032)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3467033)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3467024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3467032)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3467028)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3467031)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3467027)[0m malloc_consolidate(): invalid chunk size
E0815 12:29:56.185964274 3407261 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3467030)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3467033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3467029)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:30:26,800 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:30:26,801 | fed_df.py:547 | Average fusion training loss : 0.008236905224621296, val accuracy : 0.7646799999999999, best val accuracy : 0.7722
INFO flwr 2023-08-15 12:30:26,803 | common.py:35 | Avg. local train loss : 4.033454842865467, train acc : 0.8982249999999999
INFO flwr 2023-08-15 12:30:29,482 | server.py:116 | fit progress: (26, 1.6158318389892579, {'server_test_acc': 0.7776}, 2644.6098663327284)
INFO flwr 2023-08-15 12:30:29,482 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 12:30:34,345 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:31:32,609 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 12:31:32,821 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-15 12:31:32,951 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3686628)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3686616)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3686623)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3686614)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3686639)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3686635)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3686634)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3686638)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3686628)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686639)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686614)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3686634)[0m malloc_consolidate(): invalid chunk size
E0815 12:31:35.501073616 3612043 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3686616)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3686623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3686638)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:32:06,037 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:32:06,038 | fed_df.py:547 | Average fusion training loss : 0.008244283179752529, val accuracy : 0.7719199999999999, best val accuracy : 0.7786
INFO flwr 2023-08-15 12:32:06,040 | common.py:35 | Avg. local train loss : 4.039364665001631, train acc : 0.8966666666666667
INFO flwr 2023-08-15 12:32:08,768 | server.py:116 | fit progress: (27, 1.634933966064453, {'server_test_acc': 0.78}, 2743.896063333843)
INFO flwr 2023-08-15 12:32:08,768 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 12:32:13,426 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3907628)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3907621)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3907623)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:33:12,062 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3907631)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:33:12,273 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-15 12:33:12,407 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3907621)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3907623)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3907633)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3907635)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3907628)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3907625)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3907631)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3907632)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3907633)[0m double free or corruption (fasttop)
E0815 12:33:13.507818967 4051966 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3907632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3907635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3907625)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:33:45,185 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:33:45,185 | fed_df.py:547 | Average fusion training loss : 0.008548147456720471, val accuracy : 0.7720800000000001, best val accuracy : 0.7792
INFO flwr 2023-08-15 12:33:45,187 | common.py:35 | Avg. local train loss : 3.9928286623209717, train acc : 0.9024888888888889
INFO flwr 2023-08-15 12:33:47,946 | server.py:116 | fit progress: (28, 1.6358635681152345, {'server_test_acc': 0.7778}, 2843.073814283125)
INFO flwr 2023-08-15 12:33:47,946 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 12:33:52,654 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4129509)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4129510)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:34:50,938 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 12:34:51,150 | fed_df.py:365 | Warm start at round 29
[2m[36m(launch_and_fit pid=4129223)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:34:51,281 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4129149)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4129223)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4129507)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4129508)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4129509)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4129510)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4129229)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4129341)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4129149)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4129508)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4129507)[0m double free or corruption (fasttop)
E0815 12:34:52.242735117 4052369 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4129341)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4129229)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:35:24,007 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:35:24,008 | fed_df.py:547 | Average fusion training loss : 0.00961276214569807, val accuracy : 0.76672, best val accuracy : 0.7804
INFO flwr 2023-08-15 12:35:24,010 | common.py:35 | Avg. local train loss : 3.9636179145425556, train acc : 0.9024694444444445
INFO flwr 2023-08-15 12:35:26,730 | server.py:116 | fit progress: (29, 1.5860893157958984, {'server_test_acc': 0.7847}, 2941.857658268884)
INFO flwr 2023-08-15 12:35:26,730 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 12:35:31,434 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=156462)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:36:27,213 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 12:36:27,430 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 12:36:27,558 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=156460)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=156464)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=156462)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=156469)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=156467)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=156471)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=156472)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=156470)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=156464)[0m malloc_consolidate(): invalid chunk size
E0815 12:36:28.890315734  305399 chttp2_transport.cc:1079]             ipv4:145.136.62.23:54867: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=156471)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=156460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=156472)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=156469)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=156467)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=156470)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:37:00,692 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:37:00,692 | fed_df.py:547 | Average fusion training loss : 0.009009083426557481, val accuracy : 0.7726, best val accuracy : 0.7806
INFO flwr 2023-08-15 12:37:00,694 | common.py:35 | Avg. local train loss : 3.9387423310428855, train acc : 0.9053361111111113
INFO flwr 2023-08-15 12:37:03,442 | server.py:116 | fit progress: (30, 1.6172040832519532, {'server_test_acc': 0.7788}, 3038.56997109903)
INFO flwr 2023-08-15 12:37:03,442 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 12:37:03,442 | server.py:144 | FL finished in 3038.5703593320213
INFO flwr 2023-08-15 12:37:03,443 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 12:37:03,444 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 12:37:03,444 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.5402157348632812), (2, 1.3521826202392577), (3, 1.3406781555175782), (4, 1.3398211120605468), (5, 1.3619908508300782), (6, 1.4363565460205079), (7, 1.5053358581542968), (8, 1.577997592163086), (9, 1.6214528564453126), (10, 1.590169436645508), (11, 1.7101100860595704), (12, 1.7037653350830078), (13, 1.6912146209716796), (14, 1.6873511291503906), (15, 1.7032088500976563), (16, 1.7017422729492186), (17, 1.724058773803711), (18, 1.6903778503417968), (19, 1.7056174285888672), (20, 1.6994690124511718), (21, 1.6690241729736328), (22, 1.7094560394287108), (23, 1.6300400115966798), (24, 1.6539535949707032), (25, 1.6555341827392578), (26, 1.6158318389892579), (27, 1.634933966064453), (28, 1.6358635681152345), (29, 1.5860893157958984), (30, 1.6172040832519532)]
INFO flwr 2023-08-15 12:37:03,444 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4539), (2, 0.5748), (3, 0.6161), (4, 0.6476), (5, 0.6753), (6, 0.6932), (7, 0.7054), (8, 0.7033), (9, 0.7165), (10, 0.7292), (11, 0.7265), (12, 0.7398), (13, 0.7331), (14, 0.7499), (15, 0.7513), (16, 0.7512), (17, 0.7605), (18, 0.7594), (19, 0.7583), (20, 0.7651), (21, 0.7716), (22, 0.7639), (23, 0.7736), (24, 0.7745), (25, 0.7682), (26, 0.7776), (27, 0.78), (28, 0.7778), (29, 0.7847), (30, 0.7788)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn23: task 0: Aborted
srun: Terminating StepId=3339010.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3339010
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:51:35
CPU Efficiency: 11.87% of 15:40:12 core-walltime
Job Wall-clock time: 00:52:14
Memory Utilized: 66.99 GB
Memory Efficiency: 55.82% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
