-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:10000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.001
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:50
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.5
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=10000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3339012/1692092719_016959217', seed=42, img_per_thread=555)
will save 10000 patches in /scratch-local/sunnys.3339012/1692092719_016959217/single_img_crops/crops
10000 took 0.13min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 11:45:44,087 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 11:45:44,087 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3339012/1692092719_016959217/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3339012/1692092719_016959217/cifar-10-python.tar.gz to /scratch-local/sunnys.3339012/1692092719_016959217
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [256 249 217 265 244 275 235 226 275 258]
INFO flwr 2023-08-15 11:46:15,009 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 11:46:17,308	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-15 11:46:18,346 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.25': 1.0, 'CPU': 18.0, 'accelerator_type:A100': 1.0, 'GPU': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0}
INFO flwr 2023-08-15 11:46:18,346 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 11:46:18,346 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 11:46:18,346 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 11:46:26,681 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-15 11:46:26,681 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 11:46:31,421 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 11:47:26,711 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1969919)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:47:26,928 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-15 11:47:27,055 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1969874)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1969921)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1969875)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1969824)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1969918)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1969919)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1969920)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1969836)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1969824)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1969875)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969836)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1969921)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1969920)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1969918)[0m malloc_consolidate(): invalid chunk size
E0815 11:47:30.511557187 1957855 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 11:47:30.511704502 1957855 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 11:47:30.511716900 1957855 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 11:47:30.511725391 1957855 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 11:47:30.511733711 1957855 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-15 11:47:57,472 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:47:57,473 | fed_df.py:547 | Average fusion training loss : 0.025158494986593723, val accuracy : 0.43427999999999994, best val accuracy : 0.4432
INFO flwr 2023-08-15 11:47:57,475 | common.py:35 | Avg. local train loss : 8.682828553020956, train acc : 0.3980944444444445
INFO flwr 2023-08-15 11:48:00,067 | server.py:116 | fit progress: (1, 1.6053772491455078, {'server_test_acc': 0.4494}, 93.38524070614949)
INFO flwr 2023-08-15 11:48:00,067 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 11:48:04,577 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2137467)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:48:59,834 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2137465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137466)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:49:00,052 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-15 11:49:00,184 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2137461)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2137463)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2137460)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2137466)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2137464)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2137467)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2137465)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2137458)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2137460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137458)[0m malloc_consolidate(): invalid chunk size
E0815 11:49:01.015264338 2084499 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2137463)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137464)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2137461)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:49:31,098 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:49:31,098 | fed_df.py:547 | Average fusion training loss : 0.019050379829481243, val accuracy : 0.54572, best val accuracy : 0.5504
INFO flwr 2023-08-15 11:49:31,100 | common.py:35 | Avg. local train loss : 7.348907157778739, train acc : 0.5400027777777777
INFO flwr 2023-08-15 11:49:33,728 | server.py:116 | fit progress: (2, 1.4716548645019532, {'server_test_acc': 0.5454}, 187.0462673222646)
INFO flwr 2023-08-15 11:49:33,728 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 11:49:38,349 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2285453)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:50:34,072 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2285451)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:50:34,290 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 11:50:34,416 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2285454)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2285451)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2285456)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2285449)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2285450)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2285453)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2285452)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2285455)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2285452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2285454)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2285456)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2285455)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2285450)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2285449)[0m malloc_consolidate(): invalid chunk size
E0815 11:50:38.222601579 2384753 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-15 11:51:05,336 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:51:05,337 | fed_df.py:547 | Average fusion training loss : 0.02058384600095451, val accuracy : 0.6148, best val accuracy : 0.619
INFO flwr 2023-08-15 11:51:05,339 | common.py:35 | Avg. local train loss : 6.493038339167834, train acc : 0.6340305555555555
INFO flwr 2023-08-15 11:51:07,923 | server.py:116 | fit progress: (3, 1.4386465942382813, {'server_test_acc': 0.6228}, 281.24138729227707)
INFO flwr 2023-08-15 11:51:07,923 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 11:51:12,498 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2433706)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:52:08,451 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2433709)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2433710)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:52:08,673 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 11:52:08,800 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2433709)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2433708)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2433706)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2433703)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2433705)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2433711)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2433707)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2433710)[0m Fitting Client 6
E0815 11:52:09.183316576 2385558 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=2433711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2433705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2433708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2433703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2433707)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:52:40,621 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:52:40,621 | fed_df.py:547 | Average fusion training loss : 0.026566027122549712, val accuracy : 0.6534000000000001, best val accuracy : 0.6574
INFO flwr 2023-08-15 11:52:40,623 | common.py:35 | Avg. local train loss : 5.823628314584494, train acc : 0.7042944444444447
INFO flwr 2023-08-15 11:52:43,213 | server.py:116 | fit progress: (4, 1.4864940002441407, {'server_test_acc': 0.6517}, 376.53158844215795)
INFO flwr 2023-08-15 11:52:43,213 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 11:52:47,793 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2581570)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581568)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2581569)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 11:53:43,708 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-15 11:53:43,926 | fed_df.py:365 | Warm start at round 5
[2m[36m(launch_and_fit pid=2581566)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:53:44,053 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2581569)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2581570)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2581564)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2581566)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2581561)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2581562)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2581568)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2581565)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2581565)[0m double free or corruption (fasttop)
E0815 11:53:44.716973946 2528040 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2581564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2581561)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2581562)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:54:15,240 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:54:15,240 | fed_df.py:547 | Average fusion training loss : 0.04526684441789985, val accuracy : 0.66372, best val accuracy : 0.6754
INFO flwr 2023-08-15 11:54:15,242 | common.py:35 | Avg. local train loss : 5.412624618411064, train acc : 0.746936111111111
INFO flwr 2023-08-15 11:54:17,868 | server.py:116 | fit progress: (5, 1.5698148742675782, {'server_test_acc': 0.6659}, 471.1863569370471)
INFO flwr 2023-08-15 11:54:17,868 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 11:54:22,432 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2729261)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:55:17,393 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2729272)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 11:55:17,612 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 11:55:17,738 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2729268)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2729265)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2729270)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2729272)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2729271)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2729264)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2729269)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2729261)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2729271)[0m double free or corruption (fasttop)
E0815 11:55:17.996234998 2675968 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=2729268)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2729270)[0m malloc_consolidate(): invalid chunk size
E0815 11:55:19.011942248 2824772 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=2729269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2729264)[0m malloc_consolidate(): invalid chunk size
E0815 11:55:28.891125444 2839891 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-15 11:55:48,884 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:55:48,885 | fed_df.py:547 | Average fusion training loss : 0.046758598317392173, val accuracy : 0.687, best val accuracy : 0.6978
INFO flwr 2023-08-15 11:55:48,887 | common.py:35 | Avg. local train loss : 5.186889164894819, train acc : 0.7761388888888888
INFO flwr 2023-08-15 11:55:51,500 | server.py:116 | fit progress: (6, 1.6588417572021485, {'server_test_acc': 0.6892}, 564.8182294601575)
INFO flwr 2023-08-15 11:55:51,500 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 11:55:56,087 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2877428)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 11:57:04,935 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2877424)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:57:05,156 | fed_df.py:365 | Warm start at round 7
[2m[36m(launch_and_fit pid=2877421)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 11:57:05,283 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2877429)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2877427)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2877430)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2877431)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2877428)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2877424)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2877429)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2877426)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2877421)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2877431)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2877426)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2877430)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2877427)[0m double free or corruption (fasttop)
E0815 11:57:08.854264658 2840736 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-15 11:57:36,322 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:57:36,323 | fed_df.py:547 | Average fusion training loss : 0.06121153683401644, val accuracy : 0.6634800000000001, best val accuracy : 0.6776
INFO flwr 2023-08-15 11:57:36,325 | common.py:35 | Avg. local train loss : 5.061611562594772, train acc : 0.7897666666666666
INFO flwr 2023-08-15 11:57:38,908 | server.py:116 | fit progress: (7, 1.5881097442626952, {'server_test_acc': 0.6628}, 672.2265664744191)
INFO flwr 2023-08-15 11:57:38,908 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 11:57:43,492 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3025822)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3025817)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-15 11:58:39,707 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 11:58:39,926 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 11:58:40,052 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3025821)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3025812)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3025815)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3025819)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3025817)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3025822)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3025816)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3025820)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3025821)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3025815)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3025816)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3025820)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3025819)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3025812)[0m malloc_consolidate(): invalid chunk size
E0815 11:58:42.025542979 2977779 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-15 11:59:11,191 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 11:59:11,191 | fed_df.py:547 | Average fusion training loss : 0.0535650650402531, val accuracy : 0.69532, best val accuracy : 0.7114
INFO flwr 2023-08-15 11:59:11,193 | common.py:35 | Avg. local train loss : 4.8555153667926785, train acc : 0.8142027777777778
INFO flwr 2023-08-15 11:59:13,818 | server.py:116 | fit progress: (8, 1.743330209350586, {'server_test_acc': 0.7024}, 767.1366662881337)
INFO flwr 2023-08-15 11:59:13,818 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 11:59:18,396 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3173566)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:00:14,764 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3173567)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:00:14,984 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-15 12:00:15,111 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3173567)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3173561)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3173565)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3173560)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3173557)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3173563)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3173564)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3173566)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3173557)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3173560)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3173564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3173561)[0m malloc_consolidate(): invalid chunk size
E0815 12:00:17.076466956 3270327 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=3173565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3173563)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:00:46,394 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:00:46,395 | fed_df.py:547 | Average fusion training loss : 0.05392700378783047, val accuracy : 0.6802400000000001, best val accuracy : 0.7042
INFO flwr 2023-08-15 12:00:46,397 | common.py:35 | Avg. local train loss : 4.801759031414986, train acc : 0.8200749999999999
INFO flwr 2023-08-15 12:00:48,986 | server.py:116 | fit progress: (9, 1.726462466430664, {'server_test_acc': 0.6964}, 862.3042497891001)
INFO flwr 2023-08-15 12:00:48,986 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 12:00:53,545 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3321331)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:01:49,837 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3321327)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3321333)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:01:50,058 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 12:01:50,188 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3321329)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3321328)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3321319)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3321331)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3321327)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3321330)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3321332)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3321333)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3321332)[0m malloc_consolidate(): invalid chunk size
E0815 12:01:50.725070370 3271071 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=3321329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3321319)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3321330)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3321328)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:02:26,482 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:02:26,483 | fed_df.py:547 | Average fusion training loss : 0.042970115236938, val accuracy : 0.69732, best val accuracy : 0.7168
INFO flwr 2023-08-15 12:02:26,485 | common.py:35 | Avg. local train loss : 4.651910810172558, train acc : 0.8375527777777777
INFO flwr 2023-08-15 12:02:29,109 | server.py:116 | fit progress: (10, 1.8590485778808594, {'server_test_acc': 0.706}, 962.4276170544326)
INFO flwr 2023-08-15 12:02:29,109 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 12:02:33,828 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3499002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3499003)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-15 12:03:29,033 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3498904)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:03:29,254 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-15 12:03:29,379 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3498927)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3498904)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3498902)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3498955)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3498974)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3498985)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3499003)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3499002)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3498902)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498927)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498955)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498974)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498985)[0m double free or corruption (fasttop)
E0815 12:03:31.466684327 3424758 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-15 12:05:42,321 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:05:42,322 | fed_df.py:547 | Average fusion training loss : 0.03986142568476498, val accuracy : 0.69628, best val accuracy : 0.7232
INFO flwr 2023-08-15 12:05:42,324 | common.py:35 | Avg. local train loss : 4.557703781872988, train acc : 0.8485638888888889
INFO flwr 2023-08-15 12:05:44,969 | server.py:116 | fit progress: (11, 1.9110397583007812, {'server_test_acc': 0.7054}, 1158.287764456123)
INFO flwr 2023-08-15 12:05:44,969 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 12:05:49,539 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3664706)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3664708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3664704)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:06:46,956 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3664709)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:06:47,176 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 12:06:47,302 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3664705)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3664706)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3664700)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3664707)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3664704)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3664708)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3664709)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3664703)[0m Fitting Client 4
E0815 12:06:47.696192093 3758682 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=3664700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3664707)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3664703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3664705)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:07:18,510 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:07:18,511 | fed_df.py:547 | Average fusion training loss : 0.03406652358919382, val accuracy : 0.6942, best val accuracy : 0.7176
INFO flwr 2023-08-15 12:07:18,513 | common.py:35 | Avg. local train loss : 4.513617829605937, train acc : 0.8527722222222223
INFO flwr 2023-08-15 12:07:21,092 | server.py:116 | fit progress: (12, 1.9313154846191407, {'server_test_acc': 0.705}, 1254.4105916763656)
INFO flwr 2023-08-15 12:07:21,092 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 12:07:25,693 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3812610)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:08:20,938 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3812623)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:08:21,158 | fed_df.py:365 | Warm start at round 13
[2m[36m(launch_and_fit pid=3812609)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:08:21,284 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3812621)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3812620)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3812609)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3812610)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3812622)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3812611)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3812623)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3812607)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3812607)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3812622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3812620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3812611)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3812621)[0m malloc_consolidate(): invalid chunk size
E0815 12:08:25.096687427 3759288 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-15 12:08:52,685 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:08:52,686 | fed_df.py:547 | Average fusion training loss : 0.03127425591833889, val accuracy : 0.68684, best val accuracy : 0.7254
INFO flwr 2023-08-15 12:08:52,688 | common.py:35 | Avg. local train loss : 4.3501981042325495, train acc : 0.8687666666666667
INFO flwr 2023-08-15 12:08:55,304 | server.py:116 | fit progress: (13, 1.9512906677246094, {'server_test_acc': 0.713}, 1348.6231589983217)
INFO flwr 2023-08-15 12:08:55,305 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 12:08:59,880 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:09:55,291 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-15 12:09:55,510 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 12:09:55,637 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3960473)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3960470)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3960465)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3960468)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3960467)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3960469)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3960472)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3960471)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3960473)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3960469)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3960467)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3960468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3960471)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3960465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3960472)[0m malloc_consolidate(): invalid chunk size
E0815 12:09:57.600439858 4056661 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=3960470)[0m malloc_consolidate(): invalid chunk size
E0815 12:10:08.302277183 4056965 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:10:26,928 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:10:26,928 | fed_df.py:547 | Average fusion training loss : 0.028067013880237936, val accuracy : 0.7062, best val accuracy : 0.7344
INFO flwr 2023-08-15 12:10:26,930 | common.py:35 | Avg. local train loss : 4.401710450276733, train acc : 0.8631055555555556
INFO flwr 2023-08-15 12:10:29,546 | server.py:116 | fit progress: (14, 1.9604794128417968, {'server_test_acc': 0.7245}, 1442.8642997662537)
INFO flwr 2023-08-15 12:10:29,546 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 12:10:34,251 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4108367)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:11:29,409 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-15 12:11:29,628 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-15 12:11:29,756 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4108357)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4108368)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4108360)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4108373)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4108358)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4108367)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4108374)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4108375)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4108358)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4108374)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4108375)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4108360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4108357)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4108368)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4108373)[0m malloc_consolidate(): invalid chunk size
E0815 12:11:32.118467010   11927 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:12:01,130 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:12:01,131 | fed_df.py:547 | Average fusion training loss : 0.02648197321780026, val accuracy : 0.6976799999999999, best val accuracy : 0.7314
INFO flwr 2023-08-15 12:12:01,133 | common.py:35 | Avg. local train loss : 4.244263299182057, train acc : 0.8814527777777779
INFO flwr 2023-08-15 12:12:03,818 | server.py:116 | fit progress: (15, 1.9732205200195312, {'server_test_acc': 0.7147}, 1537.1364360740408)
INFO flwr 2023-08-15 12:12:03,818 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 12:12:08,387 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=63103)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:13:03,984 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=63100)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63099)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:13:04,204 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-15 12:13:04,332 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=63091)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=63103)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=63102)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=63101)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=63100)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=63092)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=63093)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=63099)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=63091)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=63093)[0m double free or corruption (fasttop)
E0815 12:13:05.158835981   12763 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=63101)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=63102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63092)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:13:35,656 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:13:35,657 | fed_df.py:547 | Average fusion training loss : 0.026428660437464713, val accuracy : 0.69824, best val accuracy : 0.7346
INFO flwr 2023-08-15 12:13:35,659 | common.py:35 | Avg. local train loss : 4.166933592781424, train acc : 0.8885916666666667
INFO flwr 2023-08-15 12:13:38,254 | server.py:116 | fit progress: (16, 1.9752921020507812, {'server_test_acc': 0.7203}, 1631.5727444193326)
INFO flwr 2023-08-15 12:13:38,254 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 12:13:42,826 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=211237)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:14:38,059 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-15 12:14:38,280 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 12:14:38,406 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=211237)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=211228)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=211239)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=211238)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=211236)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=211240)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=211226)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=211224)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=211228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211240)[0m malloc_consolidate(): invalid chunk size
E0815 12:14:39.021755843  305579 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=211236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211239)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211226)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211224)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:15:09,867 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:15:09,868 | fed_df.py:547 | Average fusion training loss : 0.024445367639884353, val accuracy : 0.7059599999999999, best val accuracy : 0.7334
INFO flwr 2023-08-15 12:15:09,870 | common.py:35 | Avg. local train loss : 4.205665715038776, train acc : 0.8879499999999999
INFO flwr 2023-08-15 12:15:12,483 | server.py:116 | fit progress: (17, 1.9780148498535157, {'server_test_acc': 0.7257}, 1725.801358064171)
INFO flwr 2023-08-15 12:15:12,483 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 12:15:17,052 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=358973)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=358978)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:16:12,855 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-15 12:16:13,077 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 12:16:13,204 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=358976)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=358978)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=358973)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=358971)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=358975)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=358977)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=358979)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=358969)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=358979)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=358976)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358975)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358971)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358977)[0m malloc_consolidate(): invalid chunk size
E0815 12:16:15.352767202  453897 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=358969)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:16:44,963 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:16:44,964 | fed_df.py:547 | Average fusion training loss : 0.02592728728055954, val accuracy : 0.7077600000000001, best val accuracy : 0.7318
INFO flwr 2023-08-15 12:16:44,966 | common.py:35 | Avg. local train loss : 4.112588804215193, train acc : 0.8960944444444444
INFO flwr 2023-08-15 12:16:47,592 | server.py:116 | fit progress: (18, 1.957053253173828, {'server_test_acc': 0.7225}, 1820.9104694584385)
INFO flwr 2023-08-15 12:16:47,592 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 12:16:52,196 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=506925)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:17:48,158 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-15 12:17:48,379 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 12:17:48,507 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=506928)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=506925)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=506926)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=506929)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=506917)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=506927)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=506924)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=506923)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=506923)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=506929)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=506927)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=506917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=506926)[0m malloc_consolidate(): invalid chunk size
E0815 12:17:49.892201466  456056 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=506928)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=506924)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:18:25,009 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:18:25,010 | fed_df.py:547 | Average fusion training loss : 0.01968866812251508, val accuracy : 0.70744, best val accuracy : 0.7382
INFO flwr 2023-08-15 12:18:25,012 | common.py:35 | Avg. local train loss : 4.0813561793416735, train acc : 0.8987972222222222
INFO flwr 2023-08-15 12:18:27,629 | server.py:116 | fit progress: (19, 1.9803708435058593, {'server_test_acc': 0.7243}, 1920.947514507454)
INFO flwr 2023-08-15 12:18:27,629 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 12:18:32,204 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=690820)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:19:25,502 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 12:19:25,724 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 12:19:25,852 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=690820)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=690819)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=690824)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=690817)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=690818)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=690822)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=690825)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=690823)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=690824)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=690825)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=690817)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=690823)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=690822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=690818)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=690819)[0m double free or corruption (fasttop)
E0815 12:19:28.055097417  616002 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:19:57,277 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:19:57,278 | fed_df.py:547 | Average fusion training loss : 0.02149345926567912, val accuracy : 0.72828, best val accuracy : 0.7496
INFO flwr 2023-08-15 12:19:57,280 | common.py:35 | Avg. local train loss : 4.1150703426450495, train acc : 0.8954944444444446
INFO flwr 2023-08-15 12:19:59,899 | server.py:116 | fit progress: (20, 1.9503397033691405, {'server_test_acc': 0.7406}, 2013.2178218252957)
INFO flwr 2023-08-15 12:19:59,899 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 12:20:04,492 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=848695)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=848696)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:21:01,131 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=848702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=848697)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:21:01,353 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 12:21:01,480 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=848700)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=848697)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=848695)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=848702)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=848699)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=848696)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=848701)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=848698)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=848699)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=848701)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=848700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=848698)[0m double free or corruption (fasttop)
E0815 12:21:05.260809930  798247 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:21:32,869 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:21:32,869 | fed_df.py:547 | Average fusion training loss : 0.01812477375101298, val accuracy : 0.7259200000000001, best val accuracy : 0.746
INFO flwr 2023-08-15 12:21:32,871 | common.py:35 | Avg. local train loss : 4.002208372205495, train acc : 0.9053277777777777
INFO flwr 2023-08-15 12:21:35,570 | server.py:116 | fit progress: (21, 1.94755283203125, {'server_test_acc': 0.7375}, 2108.8889923281968)
INFO flwr 2023-08-15 12:21:35,571 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 12:21:40,208 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=996983)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=996985)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:22:35,852 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-15 12:22:36,073 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 12:22:36,198 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=996982)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=996981)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=996986)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=996982)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=996984)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=996980)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=996983)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=996979)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=996985)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=996981)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=996980)[0m double free or corruption (fasttop)
E0815 12:22:36.799879203  948443 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=996979)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=996984)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=996986)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:23:07,610 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:23:07,610 | fed_df.py:547 | Average fusion training loss : 0.018843107240274548, val accuracy : 0.723, best val accuracy : 0.7426
INFO flwr 2023-08-15 12:23:07,613 | common.py:35 | Avg. local train loss : 4.012004043161869, train acc : 0.9060222222222223
INFO flwr 2023-08-15 12:23:10,253 | server.py:116 | fit progress: (22, 1.945108038330078, {'server_test_acc': 0.7403}, 2203.5713425274007)
INFO flwr 2023-08-15 12:23:10,253 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 12:23:14,829 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1144413)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:24:09,582 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 12:24:09,804 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 12:24:09,932 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1144410)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1144413)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1144411)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1144414)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1144401)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1144409)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1144407)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1144412)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1144410)[0m malloc_consolidate(): invalid chunk size
E0815 12:24:10.446124124 1238824 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1144414)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=1144407)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1144411)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1144412)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1144401)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:24:41,385 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:24:41,385 | fed_df.py:547 | Average fusion training loss : 0.018778144738636912, val accuracy : 0.73204, best val accuracy : 0.7512
INFO flwr 2023-08-15 12:24:41,388 | common.py:35 | Avg. local train loss : 3.970034642890096, train acc : 0.9101833333333333
INFO flwr 2023-08-15 12:24:44,026 | server.py:116 | fit progress: (23, 1.93192607421875, {'server_test_acc': 0.7434}, 2297.3451199713163)
INFO flwr 2023-08-15 12:24:44,027 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 12:24:48,676 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1290287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290494)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 12:25:42,033 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 12:25:42,254 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 12:25:42,381 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1290426)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1290425)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1290495)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1290389)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1290284)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1290494)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1290287)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1290285)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1290426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290425)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290284)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1290389)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1290495)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:26:13,964 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:26:13,964 | fed_df.py:547 | Average fusion training loss : 0.01741747573018074, val accuracy : 0.7287199999999999, best val accuracy : 0.7508
INFO flwr 2023-08-15 12:26:13,967 | common.py:35 | Avg. local train loss : 3.924573105946183, train acc : 0.911825
INFO flwr 2023-08-15 12:26:16,608 | server.py:116 | fit progress: (24, 1.920475244140625, {'server_test_acc': 0.7403}, 2389.9266716530547)
INFO flwr 2023-08-15 12:26:16,608 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 12:26:21,490 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:27:14,695 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1441067)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:27:14,918 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 12:27:15,069 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1441067)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1441136)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1440955)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1441135)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1441019)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1440999)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1440790)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1440860)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1440955)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1441136)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1440999)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1441135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1440790)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1440860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1441019)[0m double free or corruption (fasttop)
E0815 12:27:22.216946682 1542397 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:27:46,764 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:27:46,764 | fed_df.py:547 | Average fusion training loss : 0.018691228991374372, val accuracy : 0.73576, best val accuracy : 0.7578
INFO flwr 2023-08-15 12:27:46,766 | common.py:35 | Avg. local train loss : 3.8960803512483837, train acc : 0.91565
INFO flwr 2023-08-15 12:27:49,399 | server.py:116 | fit progress: (25, 1.8800430969238282, {'server_test_acc': 0.743}, 2482.7176488321275)
INFO flwr 2023-08-15 12:27:49,399 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 12:27:54,017 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1590341)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:28:47,930 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1590365)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:28:48,150 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 12:28:48,277 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1590341)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1590367)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1590366)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1590365)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1590330)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1590169)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1590238)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1590368)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1590368)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1590330)[0m corrupted size vs. prev_size in fastbins
E0815 12:28:49.063892956 1544932 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1590238)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1590366)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1590367)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1590169)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:29:19,924 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:29:19,925 | fed_df.py:547 | Average fusion training loss : 0.016252611747011543, val accuracy : 0.73368, best val accuracy : 0.7554
INFO flwr 2023-08-15 12:29:19,927 | common.py:35 | Avg. local train loss : 3.8967448521405457, train acc : 0.9145249999999999
INFO flwr 2023-08-15 12:29:22,541 | server.py:116 | fit progress: (26, 1.9082980651855468, {'server_test_acc': 0.742}, 2575.8600232191384)
INFO flwr 2023-08-15 12:29:22,542 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 12:29:27,132 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1739210)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:30:19,212 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 12:30:19,435 | fed_df.py:365 | Warm start at round 27
[2m[36m(launch_and_fit pid=1739202)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1739207)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:30:19,565 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1739208)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1739204)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1739209)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1739207)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1739202)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1739203)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1739208)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1739206)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1739210)[0m Fitting Client 13
E0815 12:30:20.180747988 1686279 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1739203)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1739206)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1739204)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1739209)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:30:51,064 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:30:51,065 | fed_df.py:547 | Average fusion training loss : 0.017206065487116576, val accuracy : 0.7376, best val accuracy : 0.7582
INFO flwr 2023-08-15 12:30:51,067 | common.py:35 | Avg. local train loss : 3.872116129845381, train acc : 0.9186722222222222
INFO flwr 2023-08-15 12:30:53,706 | server.py:116 | fit progress: (27, 1.9057363830566407, {'server_test_acc': 0.7392}, 2667.024797970429)
INFO flwr 2023-08-15 12:30:53,706 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 12:30:58,343 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:31:54,493 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1887121)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:31:54,714 | fed_df.py:365 | Warm start at round 28
[2m[36m(launch_and_fit pid=1887124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1887116)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:31:54,844 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1887123)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1887120)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1887121)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1887122)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1887118)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1887119)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1887124)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1887116)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1887118)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1887120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1887122)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1887119)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1887123)[0m malloc_consolidate(): invalid chunk size
E0815 12:31:58.546037125 1833911 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:32:26,493 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:32:26,494 | fed_df.py:547 | Average fusion training loss : 0.016701273599639535, val accuracy : 0.73552, best val accuracy : 0.7564
INFO flwr 2023-08-15 12:32:26,496 | common.py:35 | Avg. local train loss : 3.835420610755682, train acc : 0.9200666666666666
INFO flwr 2023-08-15 12:32:29,132 | server.py:116 | fit progress: (28, 1.8883442993164063, {'server_test_acc': 0.7405}, 2762.450712273363)
INFO flwr 2023-08-15 12:32:29,132 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 12:32:33,913 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2037132)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2037131)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 12:33:30,469 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2037114)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 12:33:30,693 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-15 12:33:30,823 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2036961)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2037132)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2037131)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2036965)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2037119)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2037114)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2037130)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2036964)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2036961)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2037130)[0m double free or corruption (fasttop)
E0815 12:33:31.860525487 2138653 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2037119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2036965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2036964)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:34:02,738 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:34:02,738 | fed_df.py:547 | Average fusion training loss : 0.015898578353226184, val accuracy : 0.74504, best val accuracy : 0.7606
INFO flwr 2023-08-15 12:34:02,740 | common.py:35 | Avg. local train loss : 3.7984383426606656, train acc : 0.9228000000000001
INFO flwr 2023-08-15 12:34:05,522 | server.py:116 | fit progress: (29, 1.8510935913085937, {'server_test_acc': 0.7475}, 2858.8408896210603)
INFO flwr 2023-08-15 12:34:05,522 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 12:34:10,187 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 12:35:05,797 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2214701)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:35:06,019 | fed_df.py:365 | Warm start at round 30
[2m[36m(launch_and_fit pid=2214509)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2214514)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 12:35:06,146 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2214508)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2214509)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2214693)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2214697)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2214701)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2214696)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2214431)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2214514)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2214697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2214693)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2214431)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2214508)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2214696)[0m double free or corruption (fasttop)
E0815 12:35:09.805893074 2327586 chttp2_transport.cc:1079]             ipv4:145.136.62.25:41663: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 12:35:37,667 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 12:35:37,668 | fed_df.py:547 | Average fusion training loss : 0.015225348052568734, val accuracy : 0.72952, best val accuracy : 0.7466
INFO flwr 2023-08-15 12:35:37,670 | common.py:35 | Avg. local train loss : 3.7700818240642544, train acc : 0.9254749999999998
INFO flwr 2023-08-15 12:35:40,318 | server.py:116 | fit progress: (30, 1.882092303466797, {'server_test_acc': 0.7395}, 2953.6366549120285)
INFO flwr 2023-08-15 12:35:40,318 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 12:35:40,318 | server.py:144 | FL finished in 2953.6370001444593
INFO flwr 2023-08-15 12:35:40,319 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 12:35:40,320 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 12:35:40,320 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.6053772491455078), (2, 1.4716548645019532), (3, 1.4386465942382813), (4, 1.4864940002441407), (5, 1.5698148742675782), (6, 1.6588417572021485), (7, 1.5881097442626952), (8, 1.743330209350586), (9, 1.726462466430664), (10, 1.8590485778808594), (11, 1.9110397583007812), (12, 1.9313154846191407), (13, 1.9512906677246094), (14, 1.9604794128417968), (15, 1.9732205200195312), (16, 1.9752921020507812), (17, 1.9780148498535157), (18, 1.957053253173828), (19, 1.9803708435058593), (20, 1.9503397033691405), (21, 1.94755283203125), (22, 1.945108038330078), (23, 1.93192607421875), (24, 1.920475244140625), (25, 1.8800430969238282), (26, 1.9082980651855468), (27, 1.9057363830566407), (28, 1.8883442993164063), (29, 1.8510935913085937), (30, 1.882092303466797)]
INFO flwr 2023-08-15 12:35:40,320 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4494), (2, 0.5454), (3, 0.6228), (4, 0.6517), (5, 0.6659), (6, 0.6892), (7, 0.6628), (8, 0.7024), (9, 0.6964), (10, 0.706), (11, 0.7054), (12, 0.705), (13, 0.713), (14, 0.7245), (15, 0.7147), (16, 0.7203), (17, 0.7257), (18, 0.7225), (19, 0.7243), (20, 0.7406), (21, 0.7375), (22, 0.7403), (23, 0.7434), (24, 0.7403), (25, 0.743), (26, 0.742), (27, 0.7392), (28, 0.7405), (29, 0.7475), (30, 0.7395)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn25: task 0: Aborted
srun: Terminating StepId=3339012.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3339012
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:49:57
CPU Efficiency: 12.00% of 15:15:54 core-walltime
Job Wall-clock time: 00:50:53
Memory Utilized: 57.20 GB
Memory Efficiency: 47.66% of 120.00 GB
