-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
MODEL_LIST:{'resnet8':6,'wresnet-16-4':7,'resnet20':7}
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
SERVER_STEPS_ADAPTIVE:False
SERVER_STEPS_ADAPTIVE_MIN:250
SERVER_STEPS_ADAPTIVE_INTERVAL:5
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko_small.jpg', targetpath='/scratch-local/sunnys.3936870/1695816043_839257040', seed=84, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3936870/1695816043_839257040/single_img_crops/crops
50000 took 1.12min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-09-27 14:02:08,339 | simulate.py:51 | Python script started : simulate.py
DEBUG simulate 2023-09-27 14:02:08,339 | simulate.py:56 | Reading args from argument parser
INFO flwr 2023-09-27 14:03:57,753 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-27 14:04:00,569	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-27 14:04:01,635 | app.py:179 | Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'node:145.136.62.62': 1.0, 'CPU': 18.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-09-27 14:04:01,636 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-27 14:04:01,636 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-09-27 14:04:01,636 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3936870/1695816043_839257040/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3936870/1695816043_839257040/cifar-10-python.tar.gz to /scratch-local/sunnys.3936870/1695816043_839257040
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
INFO flwr 2023-09-27 14:04:05,303 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-09-27 14:04:05,303 | server.py:101 | FL starting
DEBUG flwr 2023-09-27 14:04:17,749 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2748110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2748113)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2748108)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2748111)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:05:32,969 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2748112)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:05:33,081 | fed_df.py:367 | Warm start at round 1
INFO flwr 2023-09-27 14:05:33,182 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2748107)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2748106)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2748111)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2748108)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2748109)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2748112)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2748113)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2748110)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2748109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2748106)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2748107)[0m malloc_consolidate(): invalid chunk size
E0927 14:05:35.119773316 2745327 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0927 14:05:35.119942320 2745327 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0927 14:05:35.119958772 2745327 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0927 14:05:35.119967506 2745327 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-09-27 14:05:57,655 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:05:57,656 | fed_df.py:552 | Average fusion training loss : 0.023847534210421146, val accuracy : 0.31216363636363637, best val accuracy : 0.366
INFO flwr 2023-09-27 14:05:57,657 | common.py:35 | Avg. local train loss : 6.542234784923494, train acc : 0.6136291666666667
INFO flwr 2023-09-27 14:06:00,629 | server.py:116 | fit progress: (1, 1.7076608612060546, {'server_test_acc': 0.3744}, 115.32580235300702)
INFO flwr 2023-09-27 14:06:00,629 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-09-27 14:06:12,717 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2957898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957899)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957892)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:07:24,811 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2957894)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:07:24,952 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2957890)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2957892)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2957895)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2957894)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2957899)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2957896)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2957898)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2957897)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2957895)[0m malloc_consolidate(): invalid chunk size
E0927 14:07:25.528001528 3140554 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2957896)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957897)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:07:49,434 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:07:49,434 | fed_df.py:552 | Average fusion training loss : 0.010334614882245659, val accuracy : 0.43578181818181816, best val accuracy : 0.4914
INFO flwr 2023-09-27 14:07:49,436 | common.py:35 | Avg. local train loss : 5.721338767185807, train acc : 0.7029013888888889
INFO flwr 2023-09-27 14:07:52,405 | server.py:116 | fit progress: (2, 1.5092163879394531, {'server_test_acc': 0.4805}, 227.10167573901708)
INFO flwr 2023-09-27 14:07:52,405 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-09-27 14:08:04,494 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3187778)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3187674)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3187689)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3187783)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:09:17,229 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-27 14:09:17,388 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3187638)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3187572)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3187674)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3187689)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3187783)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3187779)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3187713)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3187778)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3187638)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3187713)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3187779)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3187572)[0m malloc_consolidate(): invalid chunk size
E0927 14:09:19.150257800 3384456 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-09-27 14:09:41,957 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:09:41,958 | fed_df.py:552 | Average fusion training loss : 0.013760264713317157, val accuracy : 0.3584727272727273, best val accuracy : 0.4574
INFO flwr 2023-09-27 14:09:41,959 | common.py:35 | Avg. local train loss : 5.03528211042285, train acc : 0.7732680555555557
INFO flwr 2023-09-27 14:09:44,928 | server.py:116 | fit progress: (3, 1.6145195739746094, {'server_test_acc': 0.4553}, 339.62463736199425)
INFO flwr 2023-09-27 14:09:44,928 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-09-27 14:09:57,299 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3419786)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3419779)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3419787)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3419784)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3419781)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3419788)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:11:09,282 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-27 14:11:09,430 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3419779)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3419781)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3419784)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3419787)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3419788)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3419786)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3419785)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3419789)[0m Fitting Client 19
E0927 14:11:09.986165285 3595295 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=3419785)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3419789)[0m malloc_consolidate(): invalid chunk size
E0927 14:11:31.977108977 3622647 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-09-27 14:11:34,130 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:11:34,131 | fed_df.py:552 | Average fusion training loss : 0.012080441040918231, val accuracy : 0.36992727272727266, best val accuracy : 0.4658
INFO flwr 2023-09-27 14:11:34,132 | common.py:35 | Avg. local train loss : 4.834746147878469, train acc : 0.7952763888888889
INFO flwr 2023-09-27 14:11:37,126 | server.py:116 | fit progress: (4, 1.6024506866455077, {'server_test_acc': 0.4553}, 451.8228469710157)
INFO flwr 2023-09-27 14:11:37,126 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-09-27 14:11:49,504 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3628515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3628510)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3628514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3628512)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3628513)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:13:01,489 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-09-27 14:13:01,605 | fed_df.py:367 | Warm start at round 5
INFO flwr 2023-09-27 14:13:01,717 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3628510)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3628508)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3628513)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3628515)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3628512)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3628516)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3628514)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3628517)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3628517)[0m malloc_consolidate(): invalid chunk size
E0927 14:13:02.808895827 3623450 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=3628516)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3628508)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:13:26,263 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:13:26,264 | fed_df.py:552 | Average fusion training loss : 0.01727388819400221, val accuracy : 0.5401636363636363, best val accuracy : 0.5778
INFO flwr 2023-09-27 14:13:26,265 | common.py:35 | Avg. local train loss : 4.839404153637588, train acc : 0.7947152777777776
INFO flwr 2023-09-27 14:13:29,241 | server.py:116 | fit progress: (5, 1.600173843383789, {'server_test_acc': 0.5638}, 563.9384395410016)
INFO flwr 2023-09-27 14:13:29,242 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-09-27 14:13:41,455 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3837840)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3837847)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837845)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:14:53,369 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3837843)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:14:53,534 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3837840)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3837843)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3837844)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3837846)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3837848)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3837847)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3837849)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3837845)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3837846)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3837844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837849)[0m malloc_consolidate(): invalid chunk size
E0927 14:14:57.972995794 4022658 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-09-27 14:15:18,113 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:15:18,113 | fed_df.py:552 | Average fusion training loss : 0.011876203374005854, val accuracy : 0.5568181818181819, best val accuracy : 0.5794
INFO flwr 2023-09-27 14:15:18,115 | common.py:35 | Avg. local train loss : 4.262773590907455, train acc : 0.8549277777777777
INFO flwr 2023-09-27 14:15:21,090 | server.py:116 | fit progress: (6, 1.5855935180664062, {'server_test_acc': 0.565}, 675.7874036110006)
INFO flwr 2023-09-27 14:15:21,091 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-09-27 14:15:33,539 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4047149)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4047156)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4047153)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:16:45,760 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-27 14:16:45,912 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4047149)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4047153)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4047151)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4047152)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4047155)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4047157)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4047156)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4047158)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4047151)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4047157)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4047152)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4047158)[0m malloc_consolidate(): invalid chunk size
E0927 14:16:47.728300068   33416 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=4047155)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:17:10,411 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:17:10,412 | fed_df.py:552 | Average fusion training loss : 0.00463670386467129, val accuracy : 0.45649090909090906, best val accuracy : 0.4962
INFO flwr 2023-09-27 14:17:10,413 | common.py:35 | Avg. local train loss : 4.302273763343692, train acc : 0.8538
INFO flwr 2023-09-27 14:17:13,459 | server.py:116 | fit progress: (7, 1.6075587158203124, {'server_test_acc': 0.4872}, 788.1561586080061)
INFO flwr 2023-09-27 14:17:13,459 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-09-27 14:17:25,986 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=63166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63169)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63168)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=63159)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=63161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63167)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:18:39,350 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=63164)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:18:39,502 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=63159)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=63161)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=63168)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=63164)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=63169)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=63167)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=63166)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=63165)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=63165)[0m malloc_consolidate(): invalid chunk size
E0927 14:18:43.564248037  248815 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-09-27 14:19:03,865 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:19:03,865 | fed_df.py:552 | Average fusion training loss : 0.0034027965841814875, val accuracy : 0.48127272727272724, best val accuracy : 0.5498
INFO flwr 2023-09-27 14:19:03,867 | common.py:35 | Avg. local train loss : 4.563880002126098, train acc : 0.8339458333333334
INFO flwr 2023-09-27 14:19:06,883 | server.py:116 | fit progress: (8, 1.506480780029297, {'server_test_acc': 0.5284}, 901.5802894390072)
INFO flwr 2023-09-27 14:19:06,884 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-09-27 14:19:19,248 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=272974)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=272981)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:20:30,590 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=272976)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:20:30,744 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=272974)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=272981)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=272980)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=272979)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=272976)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=272982)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=272983)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=272984)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=272982)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=272980)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=272983)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=272979)[0m malloc_consolidate(): invalid chunk size
E0927 14:20:32.431467952  251009 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0927 14:20:32.431702806  251009 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0927 14:20:32.431719900  251009 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0927 14:20:32.431731365  251009 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=272984)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:20:55,141 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:20:55,142 | fed_df.py:552 | Average fusion training loss : 0.0036102295662276446, val accuracy : 0.508, best val accuracy : 0.5424
INFO flwr 2023-09-27 14:20:55,143 | common.py:35 | Avg. local train loss : 4.66198785379529, train acc : 0.8247888888888888
INFO flwr 2023-09-27 14:20:58,201 | server.py:116 | fit progress: (9, 1.5317037475585937, {'server_test_acc': 0.5269}, 1012.8980858010182)
INFO flwr 2023-09-27 14:20:58,201 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-09-27 14:21:10,579 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=481998)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=481994)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=482003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=482000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=482002)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:22:21,942 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-09-27 14:22:22,054 | fed_df.py:367 | Warm start at round 10
INFO flwr 2023-09-27 14:22:22,152 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=481994)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=481998)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=482000)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=481999)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=482002)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=482001)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=481997)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=482003)[0m Fitting Client 19
E0927 14:22:22.593979639  453440 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=482001)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=481999)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=481997)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:22:46,823 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:22:46,823 | fed_df.py:552 | Average fusion training loss : 0.00967609016597271, val accuracy : 0.5506181818181818, best val accuracy : 0.5688
INFO flwr 2023-09-27 14:22:46,825 | common.py:35 | Avg. local train loss : 4.544402090273798, train acc : 0.8385083333333333
INFO flwr 2023-09-27 14:22:49,877 | server.py:116 | fit progress: (10, 1.5114112823486328, {'server_test_acc': 0.5638}, 1124.5738801260013)
INFO flwr 2023-09-27 14:22:49,877 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-09-27 14:23:02,485 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=697394)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=697399)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:24:14,034 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-09-27 14:24:14,191 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=697394)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=697399)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=697396)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=697393)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=697400)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=697403)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=697401)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=697402)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=697393)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=697396)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=697403)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=697400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=697402)[0m malloc_consolidate(): invalid chunk size
E0927 14:24:16.446315864  659020 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-09-27 14:24:38,859 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:24:38,860 | fed_df.py:552 | Average fusion training loss : 0.0029161651143804193, val accuracy : 0.5620909090909092, best val accuracy : 0.5886
INFO flwr 2023-09-27 14:24:38,861 | common.py:35 | Avg. local train loss : 4.414884557016194, train acc : 0.8488111111111111
INFO flwr 2023-09-27 14:24:41,847 | server.py:116 | fit progress: (11, 1.4615499145507813, {'server_test_acc': 0.5736}, 1236.5438310150057)
INFO flwr 2023-09-27 14:24:41,847 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-09-27 14:24:54,331 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=935068)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=935103)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=935101)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:26:06,270 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=935063)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:26:06,424 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=935063)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=935068)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=935103)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=935067)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=935102)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=935101)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=935066)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=935100)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=935067)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=935066)[0m malloc_consolidate(): invalid chunk size
E0927 14:26:07.504324322  892261 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=935102)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=935100)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:26:31,228 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:26:31,229 | fed_df.py:552 | Average fusion training loss : 0.004039474850520491, val accuracy : 0.6075636363636364, best val accuracy : 0.625
INFO flwr 2023-09-27 14:26:31,230 | common.py:35 | Avg. local train loss : 4.683414602465928, train acc : 0.8274527777777778
INFO flwr 2023-09-27 14:26:34,291 | server.py:116 | fit progress: (12, 1.3861943267822265, {'server_test_acc': 0.6173}, 1348.9884089209954)
INFO flwr 2023-09-27 14:26:34,292 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-09-27 14:26:46,670 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1153104)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1153099)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1153101)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1153105)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1153107)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:27:58,702 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-27 14:27:58,856 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1153099)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1153101)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1153108)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1153104)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1153107)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1153106)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1153105)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1153103)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1153108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1153106)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1153103)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:28:23,174 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:28:23,174 | fed_df.py:552 | Average fusion training loss : 0.0038037738502025606, val accuracy : 0.572509090909091, best val accuracy : 0.6084
INFO flwr 2023-09-27 14:28:23,176 | common.py:35 | Avg. local train loss : 4.410822619311512, train acc : 0.8500638888888888
INFO flwr 2023-09-27 14:28:26,293 | server.py:116 | fit progress: (13, 1.3702126953125, {'server_test_acc': 0.5996}, 1460.9900269370119)
INFO flwr 2023-09-27 14:28:26,293 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-09-27 14:28:38,799 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1362180)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:29:49,578 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-27 14:29:49,729 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1362179)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1362180)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1362178)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1362184)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1362185)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1362188)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1362186)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1362187)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1362178)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1362188)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1362185)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1362187)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1362186)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1362179)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1362184)[0m malloc_consolidate(): invalid chunk size
E0927 14:29:51.862692855 1120511 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0927 14:29:51.862930547 1120511 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0927 14:29:51.862945542 1120511 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-09-27 14:30:14,105 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:30:14,105 | fed_df.py:552 | Average fusion training loss : 0.004767722990829498, val accuracy : 0.4833636363636364, best val accuracy : 0.6054
INFO flwr 2023-09-27 14:30:14,107 | common.py:35 | Avg. local train loss : 4.2731624322012065, train acc : 0.8631291666666667
INFO flwr 2023-09-27 14:30:17,299 | server.py:116 | fit progress: (14, 1.3832258728027345, {'server_test_acc': 0.5965}, 1571.9960600649938)
INFO flwr 2023-09-27 14:30:17,299 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-09-27 14:30:29,833 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1571428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1571429)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1571425)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1571433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1571430)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:31:41,015 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-27 14:31:41,127 | fed_df.py:367 | Warm start at round 15
INFO flwr 2023-09-27 14:31:41,225 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1571425)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1571423)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1571430)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1571428)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1571429)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1571432)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1571433)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1571431)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1571432)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1571423)[0m malloc_consolidate(): invalid chunk size
E0927 14:31:42.637276184 1538921 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1571431)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:32:05,845 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:32:05,846 | fed_df.py:552 | Average fusion training loss : 0.009804016031790526, val accuracy : 0.6216545454545455, best val accuracy : 0.6558
INFO flwr 2023-09-27 14:32:05,847 | common.py:35 | Avg. local train loss : 4.345481412112713, train acc : 0.8588569444444444
INFO flwr 2023-09-27 14:32:09,042 | server.py:116 | fit progress: (15, 1.4599029632568359, {'server_test_acc': 0.6399}, 1683.7390351369977)
INFO flwr 2023-09-27 14:32:09,042 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-09-27 14:32:21,602 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1780270)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1780274)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:33:32,833 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-09-27 14:33:32,988 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1780270)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1780273)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1780276)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1780274)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1780272)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1780277)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1780278)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1780275)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1780272)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1780273)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1780275)[0m malloc_consolidate(): invalid chunk size
E0927 14:33:34.426390304 1738253 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1780277)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1780278)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1780276)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:33:58,082 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:33:58,082 | fed_df.py:552 | Average fusion training loss : 0.0033700890513136982, val accuracy : 0.5923272727272727, best val accuracy : 0.6508
INFO flwr 2023-09-27 14:33:58,084 | common.py:35 | Avg. local train loss : 4.1423215692862865, train acc : 0.8762722222222222
INFO flwr 2023-09-27 14:34:01,305 | server.py:116 | fit progress: (16, 1.4556365753173828, {'server_test_acc': 0.6387}, 1796.0017484959972)
INFO flwr 2023-09-27 14:34:01,305 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-09-27 14:34:13,828 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1989549)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1989554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1989556)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:35:25,614 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-27 14:35:25,766 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1989549)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1989551)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1989556)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1989558)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1989554)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1989557)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1989559)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1989555)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1989557)[0m double free or corruption (fasttop)
E0927 14:35:26.622762817 1946982 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1989555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1989558)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1989551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1989559)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:35:51,152 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:35:51,152 | fed_df.py:552 | Average fusion training loss : 0.003097909515723586, val accuracy : 0.6019454545454545, best val accuracy : 0.6438
INFO flwr 2023-09-27 14:35:51,154 | common.py:35 | Avg. local train loss : 4.172303826920688, train acc : 0.873501388888889
INFO flwr 2023-09-27 14:35:54,200 | server.py:116 | fit progress: (17, 1.4554690795898437, {'server_test_acc': 0.6345}, 1908.8966967640154)
INFO flwr 2023-09-27 14:35:54,200 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-09-27 14:36:06,696 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2198675)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2198683)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:37:17,689 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-27 14:37:17,845 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2198675)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2198683)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2198679)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2198681)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2198685)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2198684)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2198680)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2198682)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2198684)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2198681)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2198679)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2198682)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2198685)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2198680)[0m double free or corruption (fasttop)
E0927 14:37:20.549297005 2368775 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 14:37:42,655 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:37:42,655 | fed_df.py:552 | Average fusion training loss : 0.002545337879098952, val accuracy : 0.633090909090909, best val accuracy : 0.6534
INFO flwr 2023-09-27 14:37:42,657 | common.py:35 | Avg. local train loss : 4.259622804448009, train acc : 0.8659972222222221
INFO flwr 2023-09-27 14:37:45,750 | server.py:116 | fit progress: (18, 1.372311541748047, {'server_test_acc': 0.6333}, 2020.447145779006)
INFO flwr 2023-09-27 14:37:45,750 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-09-27 14:37:58,022 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2408267)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2408268)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2408257)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:39:09,239 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-27 14:39:09,392 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2408257)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2408252)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2408254)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2408251)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2408255)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2408267)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2408268)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2408256)[0m Fitting Client 2
E0927 14:39:10.031828934 2370445 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2408256)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2408252)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2408254)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2408251)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:39:34,514 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:39:34,515 | fed_df.py:552 | Average fusion training loss : 0.0038588933208957314, val accuracy : 0.5775272727272727, best val accuracy : 0.6442
INFO flwr 2023-09-27 14:39:34,516 | common.py:35 | Avg. local train loss : 4.177493173256517, train acc : 0.8765097222222222
INFO flwr 2023-09-27 14:39:37,662 | server.py:116 | fit progress: (19, 1.385700341796875, {'server_test_acc': 0.6398}, 2132.3589375390147)
INFO flwr 2023-09-27 14:39:37,662 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-09-27 14:39:49,926 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2638162)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2638166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2638167)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=2638168)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2638169)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:41:01,733 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2638171)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:41:01,848 | fed_df.py:367 | Warm start at round 20
INFO flwr 2023-09-27 14:41:01,946 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2638166)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2638167)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2638161)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2638162)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2638168)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2638171)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2638169)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2638170)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2638161)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2638170)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:41:26,452 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:41:26,452 | fed_df.py:552 | Average fusion training loss : 0.008749095036182552, val accuracy : 0.6378363636363638, best val accuracy : 0.6806
INFO flwr 2023-09-27 14:41:26,454 | common.py:35 | Avg. local train loss : 4.2458635894581676, train acc : 0.8684222222222222
INFO flwr 2023-09-27 14:41:29,573 | server.py:116 | fit progress: (20, 1.5059283294677734, {'server_test_acc': 0.6773}, 2244.2695591600204)
INFO flwr 2023-09-27 14:41:29,573 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-09-27 14:41:41,842 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2871739)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871731)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:42:52,649 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-27 14:42:52,804 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2871731)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2871734)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2871735)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2871737)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2871741)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2871739)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2871740)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2871738)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2871734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871737)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2871741)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871735)[0m malloc_consolidate(): invalid chunk size
E0927 14:42:55.356666906 3040116 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 14:43:17,810 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:43:17,811 | fed_df.py:552 | Average fusion training loss : 0.0029219707804732024, val accuracy : 0.6333272727272727, best val accuracy : 0.6664
INFO flwr 2023-09-27 14:43:17,812 | common.py:35 | Avg. local train loss : 4.251552709564566, train acc : 0.8707736111111112
INFO flwr 2023-09-27 14:43:20,951 | server.py:116 | fit progress: (21, 1.5211915435791015, {'server_test_acc': 0.6652}, 2355.6477210230078)
INFO flwr 2023-09-27 14:43:20,951 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-09-27 14:43:33,414 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3081002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3081140)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3081135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3081137)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3081139)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3081138)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3081134)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3081001)[0m ERROR: Unexpected segmentation fault encountered in worker.
[2m[36m(launch_and_fit pid=3081001)[0m  
DEBUG flwr 2023-09-27 14:45:39,260 | ray_client_proxy.py:87 | [36mray::launch_and_fit()[39m (pid=3081001, ip=145.136.62.62)
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3082505) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

[36mray::launch_and_fit()[39m (pid=3081001, ip=145.136.62.62)
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/gpfs/home1/sunnys/thesis_23/single_image_fl/client/fed_df.py", line 171, in fit
    new_parameters, distill_preds, train_res = train_model(
  File "/gpfs/home1/sunnys/thesis_23/single_image_fl/client/fed_df.py", line 57, in train_model
    for images, labels in train_loader:
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/sunnys/.conda/envs/single_image_fl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 3082505) exited unexpectedly
DEBUG flwr 2023-09-27 14:45:39,260 | server.py:229 | fit_round 22 received 7 results and 1 failures
INFO flwr 2023-09-27 14:45:39,418 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3081135)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3081001)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3081002)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3081139)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3081138)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3081140)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3081137)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3081134)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3081001)[0m malloc_consolidate(): invalid chunk size
E0927 14:45:44.585645778 3265749 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 14:46:04,618 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:46:04,619 | fed_df.py:552 | Average fusion training loss : 0.0027073387634009125, val accuracy : 0.6646181818181819, best val accuracy : 0.6774
INFO flwr 2023-09-27 14:46:04,620 | common.py:35 | Avg. local train loss : 4.239028188160487, train acc : 0.8731761904761904
INFO flwr 2023-09-27 14:46:07,639 | server.py:116 | fit progress: (22, 1.5578931121826172, {'server_test_acc': 0.6739}, 2522.335542554996)
INFO flwr 2023-09-27 14:46:07,639 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-09-27 14:46:20,085 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3330151)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:47:31,235 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3330326)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:47:31,389 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3330148)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3330151)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3330326)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3330232)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3330293)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3330146)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3330144)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3330314)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3330232)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3330148)[0m malloc_consolidate(): invalid chunk size
E0927 14:47:32.671420933 3476955 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:47:32.671525261 3476955 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:47:32.671537101 3476955 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:47:32.671547452 3476955 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3330293)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3330314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3330146)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:47:56,502 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:47:56,503 | fed_df.py:552 | Average fusion training loss : 0.002845934237819165, val accuracy : 0.6418909090909092, best val accuracy : 0.6832
INFO flwr 2023-09-27 14:47:56,504 | common.py:35 | Avg. local train loss : 4.009695277735591, train acc : 0.8916680555555555
INFO flwr 2023-09-27 14:47:59,529 | server.py:116 | fit progress: (23, 1.510573110961914, {'server_test_acc': 0.6723}, 2634.22612141)
INFO flwr 2023-09-27 14:47:59,529 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-09-27 14:48:11,989 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3539838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3539706)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:49:23,090 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-27 14:49:23,245 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3539838)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3539704)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3539706)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3539705)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3539840)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3539434)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3539839)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3539703)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3539434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3539705)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3539840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3539703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3539839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3539704)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:49:48,629 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:49:48,630 | fed_df.py:552 | Average fusion training loss : 0.0027112473892048003, val accuracy : 0.6417272727272727, best val accuracy : 0.6596
INFO flwr 2023-09-27 14:49:48,631 | common.py:35 | Avg. local train loss : 3.9844482872635125, train acc : 0.8946875000000001
INFO flwr 2023-09-27 14:49:51,634 | server.py:116 | fit progress: (24, 1.357993685913086, {'server_test_acc': 0.6557}, 2746.331148066005)
INFO flwr 2023-09-27 14:49:51,634 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-09-27 14:50:04,405 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3748349)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3748338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3748342)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:51:15,016 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-27 14:51:15,130 | fed_df.py:367 | Warm start at round 25
[2m[36m(launch_and_fit pid=3748353)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:51:15,236 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3748338)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3748349)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3748350)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3748354)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3748353)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3748342)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3748345)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3748355)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3748355)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3748354)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3748350)[0m malloc_consolidate(): invalid chunk size
E0927 14:51:16.977411229 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977543998 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977561356 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977572072 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977582218 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977594463 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977604804 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977613839 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977625054 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:51:16.977635402 3895699 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3748345)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 14:51:41,247 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:51:41,248 | fed_df.py:552 | Average fusion training loss : 0.008370937642175703, val accuracy : 0.6361090909090908, best val accuracy : 0.7052
INFO flwr 2023-09-27 14:51:41,249 | common.py:35 | Avg. local train loss : 4.306679841689766, train acc : 0.8671861111111111
INFO flwr 2023-09-27 14:51:44,234 | server.py:116 | fit progress: (25, 1.5602356353759765, {'server_test_acc': 0.6898}, 2858.9309580520203)
INFO flwr 2023-09-27 14:51:44,234 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-09-27 14:51:56,976 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3955879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3955916)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3955917)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:53:07,095 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3955905)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:53:07,249 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3955879)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3955905)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3955919)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3955916)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3955917)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3955915)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3955920)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3955918)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3955915)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3955919)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3955920)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3955918)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:53:33,065 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:53:33,065 | fed_df.py:552 | Average fusion training loss : 0.0032492778017185627, val accuracy : 0.6293454545454545, best val accuracy : 0.6838
INFO flwr 2023-09-27 14:53:33,067 | common.py:35 | Avg. local train loss : 3.9957448909059163, train acc : 0.8933958333333333
INFO flwr 2023-09-27 14:53:36,042 | server.py:116 | fit progress: (26, 1.5420846282958984, {'server_test_acc': 0.6758}, 2970.738544961001)
INFO flwr 2023-09-27 14:53:36,042 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-09-27 14:53:48,471 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4162552)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4162687)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4162691)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4162822)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:54:59,608 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-27 14:54:59,767 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4162552)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4162687)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4162691)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4162690)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4162823)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4162824)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4162825)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4162822)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4162690)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4162825)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4162824)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4162823)[0m malloc_consolidate(): invalid chunk size
E0927 14:55:01.808603710 3896095 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.808658626 3896095 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.808668827 3896095 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.808677039 3896095 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.808685392 3896095 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.808992870 3485913 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.809022669 3485913 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.809033007 3485913 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:55:01.809042265 3485913 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 14:55:24,566 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:55:24,567 | fed_df.py:552 | Average fusion training loss : 0.002317611481063068, val accuracy : 0.6893454545454545, best val accuracy : 0.7116
INFO flwr 2023-09-27 14:55:24,568 | common.py:35 | Avg. local train loss : 4.126361082307994, train acc : 0.885136111111111
INFO flwr 2023-09-27 14:55:27,614 | server.py:116 | fit progress: (27, 1.2857858276367187, {'server_test_acc': 0.7019}, 3082.3105933000043)
INFO flwr 2023-09-27 14:55:27,614 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-09-27 14:55:40,152 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=211147)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211161)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211162)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211197)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 14:56:51,379 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-27 14:56:51,534 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=211147)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=211159)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=211158)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=211161)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=211162)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=211198)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=211150)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=211197)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=211158)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211198)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211159)[0m malloc_consolidate(): invalid chunk size
E0927 14:56:52.739769198  143089 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:56:52.739889312  143089 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 14:56:52.739919154  143089 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=211150)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 14:57:16,378 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:57:16,378 | fed_df.py:552 | Average fusion training loss : 0.0026514848263468594, val accuracy : 0.6709454545454546, best val accuracy : 0.6966
INFO flwr 2023-09-27 14:57:16,380 | common.py:35 | Avg. local train loss : 4.082406669296324, train acc : 0.8868888888888888
INFO flwr 2023-09-27 14:57:19,442 | server.py:116 | fit progress: (28, 1.3118788177490235, {'server_test_acc': 0.6871}, 3194.1391017230053)
INFO flwr 2023-09-27 14:57:19,443 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-09-27 14:57:32,289 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=429881)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=429855)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 14:58:43,009 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-27 14:58:43,165 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=429855)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=429881)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=429879)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=430126)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=430115)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=430113)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=430114)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=430117)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=430126)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430113)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=430117)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=429879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=430114)[0m double free or corruption (fasttop)
E0927 14:58:45.709850002  584382 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 14:59:07,980 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 14:59:07,981 | fed_df.py:552 | Average fusion training loss : 0.002967508455738425, val accuracy : 0.673309090909091, best val accuracy : 0.6958
INFO flwr 2023-09-27 14:59:07,982 | common.py:35 | Avg. local train loss : 4.1606700861826535, train acc : 0.8801152777777776
INFO flwr 2023-09-27 14:59:11,068 | server.py:116 | fit progress: (29, 1.2300353271484374, {'server_test_acc': 0.6909}, 3305.7653512380202)
INFO flwr 2023-09-27 14:59:11,069 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-09-27 14:59:23,601 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=637935)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=637638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=637925)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=637933)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 15:00:35,535 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-09-27 15:00:35,650 | fed_df.py:367 | Warm start at round 30
[2m[36m(launch_and_fit pid=637946)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 15:00:35,757 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=637935)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=637924)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=637946)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=637947)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=637638)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=637933)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=637925)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=637730)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=637924)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=637947)[0m malloc_consolidate(): invalid chunk size
E0927 15:00:36.694326840  584980 chttp2_transport.cc:1079]             ipv4:145.136.62.62:57844: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=637730)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 15:00:59,762 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 15:00:59,762 | fed_df.py:552 | Average fusion training loss : 0.008615393397398294, val accuracy : 0.6334727272727273, best val accuracy : 0.6632
INFO flwr 2023-09-27 15:00:59,764 | common.py:35 | Avg. local train loss : 4.129506969824433, train acc : 0.8823083333333333
INFO flwr 2023-09-27 15:01:02,928 | server.py:116 | fit progress: (30, 1.489591485595703, {'server_test_acc': 0.6562}, 3417.6248499620124)
INFO flwr 2023-09-27 15:01:02,928 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-27 15:01:02,928 | server.py:144 | FL finished in 3417.6253253550094
INFO flwr 2023-09-27 15:01:02,929 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-27 15:01:02,930 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-27 15:01:02,930 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.7076608612060546), (2, 1.5092163879394531), (3, 1.6145195739746094), (4, 1.6024506866455077), (5, 1.600173843383789), (6, 1.5855935180664062), (7, 1.6075587158203124), (8, 1.506480780029297), (9, 1.5317037475585937), (10, 1.5114112823486328), (11, 1.4615499145507813), (12, 1.3861943267822265), (13, 1.3702126953125), (14, 1.3832258728027345), (15, 1.4599029632568359), (16, 1.4556365753173828), (17, 1.4554690795898437), (18, 1.372311541748047), (19, 1.385700341796875), (20, 1.5059283294677734), (21, 1.5211915435791015), (22, 1.5578931121826172), (23, 1.510573110961914), (24, 1.357993685913086), (25, 1.5602356353759765), (26, 1.5420846282958984), (27, 1.2857858276367187), (28, 1.3118788177490235), (29, 1.2300353271484374), (30, 1.489591485595703)]
INFO flwr 2023-09-27 15:01:02,930 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.3744), (2, 0.4805), (3, 0.4553), (4, 0.4553), (5, 0.5638), (6, 0.565), (7, 0.4872), (8, 0.5284), (9, 0.5269), (10, 0.5638), (11, 0.5736), (12, 0.6173), (13, 0.5996), (14, 0.5965), (15, 0.6399), (16, 0.6387), (17, 0.6345), (18, 0.6333), (19, 0.6398), (20, 0.6773), (21, 0.6652), (22, 0.6739), (23, 0.6723), (24, 0.6557), (25, 0.6898), (26, 0.6758), (27, 0.7019), (28, 0.6871), (29, 0.6909), (30, 0.6562)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn62: task 0: Aborted
srun: Terminating StepId=3936870.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3936870
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:51:15
CPU Efficiency: 9.94% of 18:39:00 core-walltime
Job Wall-clock time: 01:02:10
Memory Utilized: 23.57 GB
Memory Efficiency: 19.64% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
