-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf_hetero
MODEL_NAME:wresnet-16-4
MODEL_LIST:{'resnet8':7,'wresnet-16-4':7,'resnet20':6}
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
SERVER_STEPS_ADAPTIVE:False
SERVER_STEPS_ADAPTIVE_MIN:100
SERVER_STEPS_ADAPTIVE_INTERVAL:3
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:1000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:3
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko_small.jpg', targetpath='/scratch-local/sunnys.3925070/1695660872_139230789', seed=42, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3925070/1695660872_139230789/single_img_crops/crops
50000 took 0.98min with 18 threads
---------
Simulating feddf_hetero training
INFO simulate 2023-09-25 18:55:51,027 | simulate.py:51 | Python script started : simulate.py
DEBUG simulate 2023-09-25 18:55:51,027 | simulate.py:56 | Reading args from argument parser
INFO flwr 2023-09-25 18:57:53,502 | fed_df_hetero.py:193 | Models in the server : ['resnet8', 'wresnet-16-4', 'resnet20']
INFO flwr 2023-09-25 18:57:53,567 | fed_df_hetero.py:198 | Server Models initialised
INFO flwr 2023-09-25 18:57:53,568 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-25 18:57:57,643	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-25 18:57:58,757 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'node:145.136.62.32': 1.0, 'accelerator_type:A100': 1.0, 'GPU': 1.0, 'CPU': 18.0}
INFO flwr 2023-09-25 18:57:58,758 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-25 18:57:58,758 | server.py:270 | Requesting initial parameters from one random client
INFO flwr 2023-09-25 18:58:06,137 | server.py:274 | Received initial parameters from one random client
INFO flwr 2023-09-25 18:58:06,137 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3925070/1695660872_139230789/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3925070/1695660872_139230789/cifar-10-python.tar.gz to /scratch-local/sunnys.3925070/1695660872_139230789
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
[2m[36m(launch_and_get_parameters pid=1654150)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 18:58:13,571 | server.py:91 | initial parameters (loss, other metrics): 3.7793668823242186, {'server_test_acc': 0.1}
INFO flwr 2023-09-25 18:58:13,571 | server.py:101 | FL starting
[2m[36m(launch_and_get_properties pid=1662096)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1664926)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1665096)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1665288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1665462)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1665632)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1665804)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 18:58:56,187 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=1665982)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 18:59:07,544 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1667046)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1667039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1667045)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1667043)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:00:24,911 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-25 19:00:24,935 | fed_df_hetero.py:400 | Warm start at round 1
[2m[36m(launch_and_fit pid=1667048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1667040)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1667044)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1667047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1758203)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1758705)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1758875)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1759047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1759227)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1759401)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1759864)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:01:07,898 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:01:07,979 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:01:08,002 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:01:08,002 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1667039)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1667047)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1667040)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1667045)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1667043)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1667048)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1667046)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1667044)[0m Fitting Client 8
[2m[36m(launch_and_get_properties pid=1760060)[0m malloc_consolidate(): invalid chunk size
E0925 19:01:15.125813539 1654042 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-09-25 19:01:35,827 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2740572620034218, 'fusion_acc': 0.25821818181818185}, {'fusion_loss': 0.27826873311400413, 'fusion_acc': 0.27778181818181813}, {'fusion_loss': 0.2753669647872448, 'fusion_acc': 0.2746363636363636}]
INFO flwr 2023-09-25 19:01:35,827 | common.py:35 | Avg. local train loss : 6.896367576718331, train acc : 0.5851180555555556
INFO flwr 2023-09-25 19:01:42,772 | server.py:116 | fit progress: (1, 3.256066979980469, {'server_test_acc': 0.3326}, 209.20049637600096)
INFO flwr 2023-09-25 19:01:42,772 | server.py:163 | evaluate_round 1: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=1772442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1772619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1772775)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1772945)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1773455)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1773630)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1773808)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:02:24,828 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=1773990)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:02:39,513 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1774502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1774500)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1774494)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1774503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1774506)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1774504)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:03:55,598 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-25 19:03:55,622 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1774502)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1774503)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1774494)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1774504)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1774506)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1774500)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1774501)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1774505)[0m Fitting Client 7
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=1774505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1774501)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:04:23,047 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.279840705409646, 'fusion_acc': 0.2545818181818182}, {'fusion_loss': 0.3231738067269325, 'fusion_acc': 0.25587272727272725}, {'fusion_loss': 0.27029178205132487, 'fusion_acc': 0.2727454545454545}]
INFO flwr 2023-09-25 19:04:23,047 | common.py:35 | Avg. local train loss : 5.297110871970654, train acc : 0.736598611111111
INFO flwr 2023-09-25 19:04:29,904 | server.py:116 | fit progress: (2, 3.563507568359375, {'server_test_acc': 0.3255}, 376.3324219490023)
INFO flwr 2023-09-25 19:04:29,904 | server.py:163 | evaluate_round 2: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=1878272)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1878430)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1878614)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1878807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1878945)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1879412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1879907)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:05:12,531 | fed_df_hetero.py:270 | Best Server Model Name : resnet20
[2m[36m(launch_and_get_properties pid=1880082)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:05:28,883 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1880597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1880601)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1880598)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1880593)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:06:49,483 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-25 19:06:49,508 | fed_df_hetero.py:400 | Warm start at round 3
[2m[36m(launch_and_fit pid=1880595)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1880602)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1880599)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1880600)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1972067)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1972253)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1972747)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1972938)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1973109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1973280)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1973450)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:07:32,152 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:07:32,244 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:07:32,266 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:07:32,266 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1880599)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1880601)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1880598)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1880595)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1880597)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1880600)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1880602)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1880593)[0m Fitting Client 17
[2m[36m(launch_and_get_properties pid=1973621)[0m double free or corruption (fasttop)
E0925 19:07:42.083531860 1976269 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-09-25 19:07:59,955 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.24339005111157894, 'fusion_acc': 0.39681818181818185}, {'fusion_loss': 0.2745778986811638, 'fusion_acc': 0.3976909090909091}, {'fusion_loss': 0.30251002848148345, 'fusion_acc': 0.36701818181818185}]
INFO flwr 2023-09-25 19:07:59,955 | common.py:35 | Avg. local train loss : 5.2717297153547396, train acc : 0.7446138888888889
INFO flwr 2023-09-25 19:08:06,777 | server.py:116 | fit progress: (3, 2.9610592956542967, {'server_test_acc': 0.4201}, 593.205439147001)
INFO flwr 2023-09-25 19:08:06,777 | server.py:163 | evaluate_round 3: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=1986303)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1986471)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1986643)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1986822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1986992)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=1987179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=1987349)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:08:49,184 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=1987519)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:09:00,375 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1988312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1988299)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1988311)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1988310)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1988313)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:10:24,536 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-25 19:10:24,561 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=1988310)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1988299)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1988296)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1988309)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1988314)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1988311)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1988312)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1988313)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1988296)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1988309)[0m malloc_consolidate(): invalid chunk size
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
E0925 19:10:25.839365073 2080386 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=1988314)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:10:52,374 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.21447306901216506, 'fusion_acc': 0.4458727272727273}, {'fusion_loss': 0.22178745818138124, 'fusion_acc': 0.4589272727272727}, {'fusion_loss': 0.2231701208204031, 'fusion_acc': 0.4238909090909091}]
INFO flwr 2023-09-25 19:10:52,374 | common.py:35 | Avg. local train loss : 4.5582708975300195, train acc : 0.8141138888888888
INFO flwr 2023-09-25 19:10:59,278 | server.py:116 | fit progress: (4, 2.194740905761719, {'server_test_acc': 0.4668}, 765.7065192510017)
INFO flwr 2023-09-25 19:10:59,278 | server.py:163 | evaluate_round 4: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2092366)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=2092863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2093033)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2093214)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2093404)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2093589)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2093780)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:11:41,654 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2093968)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:11:56,304 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2094477)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2094472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2094479)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2094476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2094475)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2094480)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:13:13,067 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-09-25 19:13:13,091 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2094475)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2094479)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2094480)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2094478)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2094476)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2094477)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2094472)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2094470)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2094478)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2094470)[0m corrupted size vs. prev_size in fastbins
E0925 19:13:17.508573119 2211292 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-09-25 19:13:40,991 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.23777767764031887, 'fusion_acc': 0.42081818181818176}, {'fusion_loss': 0.2449017389714718, 'fusion_acc': 0.4021272727272727}, {'fusion_loss': 0.22623184110224248, 'fusion_acc': 0.4221090909090908}]
INFO flwr 2023-09-25 19:13:40,992 | common.py:35 | Avg. local train loss : 4.595261313021184, train acc : 0.8141930555555557
INFO flwr 2023-09-25 19:13:47,980 | server.py:116 | fit progress: (5, 2.6596041381835938, {'server_test_acc': 0.4794}, 934.4084628100027)
INFO flwr 2023-09-25 19:13:47,980 | server.py:163 | evaluate_round 5: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2235864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2238106)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2238276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2238775)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2238945)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2239115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2239287)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:14:30,418 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=2239457)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:14:41,792 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2239987)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2239985)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2239980)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2239984)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:16:03,032 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-09-25 19:16:03,056 | fed_df_hetero.py:400 | Warm start at round 6
[2m[36m(launch_and_fit pid=2239982)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2239989)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2239988)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2239986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2331804)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2332010)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2332190)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2332362)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2332547)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2332717)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2332913)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:16:45,687 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:16:45,770 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:16:45,830 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:16:45,830 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2239982)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2239984)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2239980)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2239988)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2239985)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2239989)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2239986)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2239987)[0m Fitting Client 6
[2m[36m(launch_and_get_properties pid=2333092)[0m malloc_consolidate(): invalid chunk size
E0925 19:16:47.613394927 2212312 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-09-25 19:17:13,841 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2932015522569418, 'fusion_acc': 0.46434545454545456}, {'fusion_loss': 0.2904473842084408, 'fusion_acc': 0.5147818181818182}, {'fusion_loss': 0.30257290935516357, 'fusion_acc': 0.4993090909090909}]
INFO flwr 2023-09-25 19:17:13,842 | common.py:35 | Avg. local train loss : 4.195402946881949, train acc : 0.8477194444444446
INFO flwr 2023-09-25 19:17:20,848 | server.py:116 | fit progress: (6, 2.7568498962402344, {'server_test_acc': 0.5149}, 1147.2769076010009)
INFO flwr 2023-09-25 19:17:20,848 | server.py:163 | evaluate_round 6: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2346041)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2346199)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2346384)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2346545)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2346715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2346895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2347081)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:18:03,231 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2347270)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:18:18,068 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2347793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2347799)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2347800)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2347798)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2347797)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2347802)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:19:33,364 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-25 19:19:33,388 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2347793)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2347797)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2347799)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2347800)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2347802)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2347794)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2347798)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2347791)[0m Fitting Client 11
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=2347794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2347791)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:20:01,517 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.14929547423124315, 'fusion_acc': 0.3947636363636363}, {'fusion_loss': 0.16099381241202354, 'fusion_acc': 0.45500000000000007}, {'fusion_loss': 0.13969972079247236, 'fusion_acc': 0.4651636363636364}]
INFO flwr 2023-09-25 19:20:01,517 | common.py:35 | Avg. local train loss : 3.9843778818845745, train acc : 0.8761138888888889
INFO flwr 2023-09-25 19:20:08,487 | server.py:116 | fit progress: (7, 2.6778547424316406, {'server_test_acc': 0.5336}, 1314.9156344790026)
INFO flwr 2023-09-25 19:20:08,487 | server.py:163 | evaluate_round 7: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2451929)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2452110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2452283)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2452453)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2452623)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2452811)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2452990)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:20:51,146 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2453162)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:21:06,011 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2453973)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2453968)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2453975)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2453976)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2453970)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2453977)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:22:18,705 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-09-25 19:22:18,729 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2453973)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2453968)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2453976)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2453977)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2453974)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2453978)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2453975)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2453970)[0m Fitting Client 4
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
E0925 19:22:19.774776575 2334525 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=2453974)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2453978)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:22:48,561 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.13897415896505116, 'fusion_acc': 0.46494545454545455}, {'fusion_loss': 0.14429154799878596, 'fusion_acc': 0.4941818181818183}, {'fusion_loss': 0.1216625524610281, 'fusion_acc': 0.516109090909091}]
INFO flwr 2023-09-25 19:22:48,561 | common.py:35 | Avg. local train loss : 4.2355406526476145, train acc : 0.8636916666666666
INFO flwr 2023-09-25 19:22:55,599 | server.py:116 | fit progress: (8, 2.485696240234375, {'server_test_acc': 0.5489}, 1482.0275041830027)
INFO flwr 2023-09-25 19:22:55,599 | server.py:163 | evaluate_round 8: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2557361)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2558146)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2558320)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2558491)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2558671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2558841)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2559012)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:23:38,078 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2559206)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:23:52,817 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2559724)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2559721)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2559716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2559726)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2559717)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:25:11,355 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-09-25 19:25:11,380 | fed_df_hetero.py:400 | Warm start at round 9
[2m[36m(launch_and_fit pid=2559723)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2559727)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2559725)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2651409)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2651602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2651772)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2651942)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2652127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2652316)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2652485)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:25:54,057 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:25:54,116 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:25:54,176 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:25:54,176 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2559717)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2559716)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2559725)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2559726)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2559723)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2559724)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2559721)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2559727)[0m Fitting Client 12
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=2652665)[0m double free or corruption (fasttop)
E0925 19:26:03.722371680 2655701 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-09-25 19:26:22,344 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.23511883053183555, 'fusion_acc': 0.48729090909090916}, {'fusion_loss': 0.24610582365095615, 'fusion_acc': 0.5350181818181817}, {'fusion_loss': 0.21712204641103744, 'fusion_acc': 0.5389454545454545}]
INFO flwr 2023-09-25 19:26:22,344 | common.py:35 | Avg. local train loss : 3.8782472038641576, train acc : 0.8837833333333335
INFO flwr 2023-09-25 19:26:29,306 | server.py:116 | fit progress: (9, 2.50418017578125, {'server_test_acc': 0.5732}, 1695.7347206880004)
INFO flwr 2023-09-25 19:26:29,306 | server.py:163 | evaluate_round 9: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2665290)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2665474)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2665645)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2665817)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2666012)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2666194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2666683)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:27:11,673 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=2666863)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:27:22,817 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2667319)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2667316)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2667320)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2667318)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:28:41,393 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-09-25 19:28:41,418 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2667312)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2667316)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2667317)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2667320)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2667321)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2667319)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2667318)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2667314)[0m Fitting Client 10
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=2667314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2667312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2667317)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2667321)[0m malloc_consolidate(): invalid chunk size
E0925 19:28:47.339283398 2796233 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-09-25 19:29:10,298 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.1699519561007619, 'fusion_acc': 0.4699454545454546}, {'fusion_loss': 0.15968756173551082, 'fusion_acc': 0.5522909090909092}, {'fusion_loss': 0.1634477911517024, 'fusion_acc': 0.49187272727272724}]
INFO flwr 2023-09-25 19:29:10,298 | common.py:35 | Avg. local train loss : 3.6427712088450788, train acc : 0.9158555555555555
INFO flwr 2023-09-25 19:29:17,266 | server.py:116 | fit progress: (10, 2.5261666076660156, {'server_test_acc': 0.5692}, 1863.694626433)
INFO flwr 2023-09-25 19:29:17,266 | server.py:163 | evaluate_round 10: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2811076)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2811248)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2811430)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2811678)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2811848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2812018)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2812198)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:29:59,561 | fed_df_hetero.py:270 | Best Server Model Name : resnet20
[2m[36m(launch_and_get_properties pid=2812372)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:30:15,965 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2812886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2812887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2812890)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2812884)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2812888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2812892)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:31:33,616 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-09-25 19:31:33,641 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2812884)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2812888)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2812892)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2812887)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2812886)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2812889)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2812890)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2812891)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2812889)[0m malloc_consolidate(): invalid chunk size
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=2812891)[0m malloc_consolidate(): invalid chunk size
E0925 19:31:37.374747598 2797064 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-09-25 19:32:01,825 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.19701112468540669, 'fusion_acc': 0.5451090909090909}, {'fusion_loss': 0.17283562864363194, 'fusion_acc': 0.5542363636363635}, {'fusion_loss': 0.17013937021791936, 'fusion_acc': 0.547309090909091}]
INFO flwr 2023-09-25 19:32:01,825 | common.py:35 | Avg. local train loss : 3.724277110025287, train acc : 0.9058680555555555
INFO flwr 2023-09-25 19:32:08,882 | server.py:116 | fit progress: (11, 2.3012311340332032, {'server_test_acc': 0.5697}, 2035.3103084989998)
INFO flwr 2023-09-25 19:32:08,882 | server.py:163 | evaluate_round 11: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=2917093)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2917266)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2917447)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2917617)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2917787)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=2917974)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=2918155)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:32:51,631 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=2918335)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:33:06,580 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2919123)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2919120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2919126)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2919127)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2919119)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:34:24,035 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-09-25 19:34:24,059 | fed_df_hetero.py:400 | Warm start at round 12
[2m[36m(launch_and_fit pid=2919128)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2919125)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2919129)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3010537)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3010710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3010947)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3011108)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3011287)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3011467)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3011641)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:35:06,493 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:35:06,553 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:35:06,594 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:35:06,594 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=2919126)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2919125)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2919119)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2919123)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2919129)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2919127)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2919120)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2919128)[0m Fitting Client 12
[2m[36m(launch_and_get_properties pid=3012430)[0m malloc_consolidate(): invalid chunk size
E0925 19:35:10.844045531 3013654 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-09-25 19:35:35,109 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.18486844213306905, 'fusion_acc': 0.5281090909090909}, {'fusion_loss': 0.15868595445156097, 'fusion_acc': 0.6192363636363636}, {'fusion_loss': 0.1758285495042801, 'fusion_acc': 0.5987454545454546}]
INFO flwr 2023-09-25 19:35:35,109 | common.py:35 | Avg. local train loss : 3.817285469360649, train acc : 0.8962583333333334
INFO flwr 2023-09-25 19:35:42,271 | server.py:116 | fit progress: (12, 2.7423670532226563, {'server_test_acc': 0.6203}, 2248.700298578002)
INFO flwr 2023-09-25 19:35:42,272 | server.py:163 | evaluate_round 12: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3024759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3024941)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3025121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3025299)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3025526)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3025696)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3025866)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:36:24,399 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3026038)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:36:39,390 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3026862)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3026870)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3026867)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3026865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3026871)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3026869)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3026872)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:37:55,585 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-25 19:37:55,609 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3026865)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3026862)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3026868)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3026867)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3026870)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3026871)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3026872)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3026869)[0m Fitting Client 19
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=3026868)[0m malloc_consolidate(): invalid chunk size
E0925 19:37:57.575332302 3119304 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-09-25 19:38:23,887 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.1733012896925211, 'fusion_acc': 0.5141818181818182}, {'fusion_loss': 0.14718858594447373, 'fusion_acc': 0.5426181818181819}, {'fusion_loss': 0.14647377417981625, 'fusion_acc': 0.5714545454545455}]
INFO flwr 2023-09-25 19:38:23,887 | common.py:35 | Avg. local train loss : 3.5536989685148, train acc : 0.9224027777777779
INFO flwr 2023-09-25 19:38:30,895 | server.py:116 | fit progress: (13, 2.787506457519531, {'server_test_acc': 0.6243}, 2417.3237517760026)
INFO flwr 2023-09-25 19:38:30,895 | server.py:163 | evaluate_round 13: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3130539)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3130714)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3130884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3131058)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3131240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3131703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3131879)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:39:13,211 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3132053)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:39:28,078 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3132538)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3132535)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132543)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132542)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:40:48,025 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-25 19:40:48,050 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3132542)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3132535)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3132539)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3132543)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3132544)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3132538)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3132541)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3132540)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3132544)[0m malloc_consolidate(): invalid chunk size
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=3132539)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132540)[0m malloc_consolidate(): invalid chunk size
E0925 19:40:51.620371720 3119305 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-09-25 19:41:16,213 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.25298893414437773, 'fusion_acc': 0.5110727272727273}, {'fusion_loss': 0.21426950012147428, 'fusion_acc': 0.5416363636363637}, {'fusion_loss': 0.2077931917756796, 'fusion_acc': 0.5397818181818181}]
INFO flwr 2023-09-25 19:41:16,214 | common.py:35 | Avg. local train loss : 3.4815417272970075, train acc : 0.9235875
INFO flwr 2023-09-25 19:41:23,239 | server.py:116 | fit progress: (14, 2.7080956848144533, {'server_test_acc': 0.6266}, 2589.6675522629994)
INFO flwr 2023-09-25 19:41:23,239 | server.py:163 | evaluate_round 14: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3236814)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3236981)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3237166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3237318)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3237499)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3237684)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3237864)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:42:05,392 | fed_df_hetero.py:270 | Best Server Model Name : resnet20
[2m[36m(launch_and_get_properties pid=3238046)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:42:21,952 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3238578)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3238582)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238581)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238589)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238585)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:43:37,330 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-25 19:43:37,354 | fed_df_hetero.py:400 | Warm start at round 15
[2m[36m(launch_and_fit pid=3238587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3339335)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3346349)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3353238)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3354663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3354871)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3356566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3361571)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:44:20,119 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:44:20,150 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:44:20,252 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:44:20,252 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3238581)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3238578)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3238587)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3238582)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3238588)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3238589)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3238586)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3238585)[0m Fitting Client 15
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3363727)[0m malloc_consolidate(): invalid chunk size
E0925 19:44:23.834430858 3225940 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-09-25 19:44:48,631 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2945771708935499, 'fusion_acc': 0.4667636363636364}, {'fusion_loss': 0.3013743666112423, 'fusion_acc': 0.46416363636363633}, {'fusion_loss': 0.23521724689006807, 'fusion_acc': 0.5254909090909091}]
INFO flwr 2023-09-25 19:44:48,632 | common.py:35 | Avg. local train loss : 3.5055493731051683, train acc : 0.9219555555555555
INFO flwr 2023-09-25 19:44:55,682 | server.py:116 | fit progress: (15, 3.4415918090820314, {'server_test_acc': 0.5502}, 2802.110557975)
INFO flwr 2023-09-25 19:44:55,682 | server.py:163 | evaluate_round 15: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3384164)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3384342)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3384537)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3384707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3384879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3385049)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3385219)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:45:38,106 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=3385715)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:45:49,439 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3386160)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3386163)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3386155)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3386164)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3386161)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3386157)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3386165)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:47:08,801 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-09-25 19:47:08,825 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3386155)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3386165)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3386161)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3386164)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3386163)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3386160)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3386162)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3386157)[0m Fitting Client 13
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=3386162)[0m malloc_consolidate(): invalid chunk size
E0925 19:47:12.438229083 3369633 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-09-25 19:47:37,029 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.34720919498801234, 'fusion_acc': 0.4731818181818182}, {'fusion_loss': 0.37277692863345147, 'fusion_acc': 0.486109090909091}, {'fusion_loss': 0.2946340997517109, 'fusion_acc': 0.5569818181818182}]
INFO flwr 2023-09-25 19:47:37,029 | common.py:35 | Avg. local train loss : 3.284017462097108, train acc : 0.9362347222222223
INFO flwr 2023-09-25 19:47:44,086 | server.py:116 | fit progress: (16, 3.491408673095703, {'server_test_acc': 0.5634}, 2970.5151765459996)
INFO flwr 2023-09-25 19:47:44,087 | server.py:163 | evaluate_round 16: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3489933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3490110)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3490289)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3490459)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3490671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3490853)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3491029)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 19:48:26,567 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=3491207)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:48:37,915 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3491986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3491989)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3491988)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3491987)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3491980)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3491985)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3491990)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:49:53,057 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-25 19:49:53,082 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3491989)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3491984)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3491990)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3491988)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3491986)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3491987)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3491980)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3491985)[0m Fitting Client 18
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=3491984)[0m corrupted size vs. prev_size in fastbins
E0925 19:49:55.113494433 3479715 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-09-25 19:50:21,665 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3968613158464432, 'fusion_acc': 0.48176363636363634}, {'fusion_loss': 0.42408292153477667, 'fusion_acc': 0.4879454545454545}, {'fusion_loss': 0.3062184865474701, 'fusion_acc': 0.5920363636363636}]
INFO flwr 2023-09-25 19:50:21,665 | common.py:35 | Avg. local train loss : 3.3980366026982667, train acc : 0.9298041666666667
INFO flwr 2023-09-25 19:50:28,602 | server.py:116 | fit progress: (17, 2.9162861755371092, {'server_test_acc': 0.6079}, 3135.030842817003)
INFO flwr 2023-09-25 19:50:28,602 | server.py:163 | evaluate_round 17: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3595842)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3596018)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3596188)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3596358)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3596539)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3596716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3597179)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:51:11,181 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=3597368)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:51:22,475 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3597843)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3597838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3597842)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3597839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3597841)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3597840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3597835)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:52:40,865 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-25 19:52:40,889 | fed_df_hetero.py:400 | Warm start at round 18
[2m[36m(launch_and_fit pid=3597844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3689276)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=3689445)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3689629)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3690100)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3690412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3690752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3690922)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:53:23,208 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 19:53:23,269 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 19:53:23,332 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 19:53:23,332 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3597842)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3597844)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3597839)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3597843)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3597835)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3597840)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3597841)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3597838)[0m Fitting Client 0
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=3691105)[0m malloc_consolidate(): invalid chunk size
E0925 19:53:27.038016529 3692530 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-09-25 19:53:51,766 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3241138198077679, 'fusion_acc': 0.5011272727272728}, {'fusion_loss': 0.2868722190856934, 'fusion_acc': 0.5888545454545455}, {'fusion_loss': 0.2807630140185356, 'fusion_acc': 0.5650000000000002}]
INFO flwr 2023-09-25 19:53:51,766 | common.py:35 | Avg. local train loss : 3.391738552413881, train acc : 0.9302625
INFO flwr 2023-09-25 19:53:58,728 | server.py:116 | fit progress: (18, 4.359717932128906, {'server_test_acc': 0.5977}, 3345.1569239560013)
INFO flwr 2023-09-25 19:53:58,728 | server.py:163 | evaluate_round 18: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3703458)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3703660)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3703830)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3704000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3704172)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3704342)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3704512)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:54:41,213 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3705068)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:54:55,974 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3705569)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3705566)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3705562)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3705567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3705568)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 19:56:12,328 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3705571)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:56:12,353 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3705564)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3705566)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3705571)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3705562)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3705568)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3705570)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3705569)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3705567)[0m Fitting Client 19
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=3705564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3705570)[0m malloc_consolidate(): invalid chunk size
E0925 19:56:16.159024613 3798523 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 19:56:40,534 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2653464258015156, 'fusion_acc': 0.5040909090909091}, {'fusion_loss': 0.24411137540638447, 'fusion_acc': 0.6026545454545456}, {'fusion_loss': 0.21605192597210407, 'fusion_acc': 0.5972363636363637}]
INFO flwr 2023-09-25 19:56:40,534 | common.py:35 | Avg. local train loss : 3.2992362845689054, train acc : 0.9458319444444445
INFO flwr 2023-09-25 19:56:47,589 | server.py:116 | fit progress: (19, 3.8544109375, {'server_test_acc': 0.6079}, 3514.0182759870004)
INFO flwr 2023-09-25 19:56:47,590 | server.py:163 | evaluate_round 19: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3809457)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3809636)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3810109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3810299)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3810469)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3810640)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3810813)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 19:57:29,905 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3810994)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:57:44,986 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3811813)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3811810)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3811814)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3811806)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3811809)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 19:58:59,276 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-25 19:58:59,302 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3811806)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3811813)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3811814)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3811816)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3811815)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3811805)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3811810)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3811809)[0m Fitting Client 6
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=3811816)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3811815)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3811805)[0m malloc_consolidate(): invalid chunk size
E0925 19:59:02.412574052 3799238 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 19:59:28,103 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.2719259824156761, 'fusion_acc': 0.4986181818181818}, {'fusion_loss': 0.24624755656719208, 'fusion_acc': 0.5747818181818182}, {'fusion_loss': 0.2347593818604946, 'fusion_acc': 0.5310363636363636}]
INFO flwr 2023-09-25 19:59:28,104 | common.py:35 | Avg. local train loss : 3.393099967762828, train acc : 0.9371847222222222
INFO flwr 2023-09-25 19:59:35,234 | server.py:116 | fit progress: (20, 4.044396130371093, {'server_test_acc': 0.6027}, 3681.662567487001)
INFO flwr 2023-09-25 19:59:35,234 | server.py:163 | evaluate_round 20: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=3940465)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3945750)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3947492)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3951495)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3953634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=3956098)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=3956306)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 20:00:17,752 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=3956476)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:00:32,663 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3957281)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3957283)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3957287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3957286)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3957289)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3957285)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3957288)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:01:47,381 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-25 20:01:47,406 | fed_df_hetero.py:400 | Warm start at round 21
[2m[36m(launch_and_fit pid=3957282)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4048533)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4048716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4048886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4049385)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4049555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4049725)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4049897)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:02:29,987 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 20:02:30,009 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 20:02:30,087 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 20:02:30,087 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=3957286)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3957285)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3957282)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3957289)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3957283)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3957288)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3957287)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3957281)[0m Fitting Client 6
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=4050067)[0m malloc_consolidate(): invalid chunk size
E0925 20:02:35.045529394 4052584 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:02:59,368 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.4072621769309044, 'fusion_acc': 0.3938181818181818}, {'fusion_loss': 0.41726393926143646, 'fusion_acc': 0.3712}, {'fusion_loss': 0.3679959079027176, 'fusion_acc': 0.48956363636363637}]
INFO flwr 2023-09-25 20:02:59,369 | common.py:35 | Avg. local train loss : 3.4943332184106106, train acc : 0.9264055555555555
INFO flwr 2023-09-25 20:03:06,369 | server.py:116 | fit progress: (21, 4.550144812011719, {'server_test_acc': 0.5407}, 3892.7975367340005)
INFO flwr 2023-09-25 20:03:06,369 | server.py:163 | evaluate_round 21: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=4062723)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4062893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4063069)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4063241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4063411)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4063765)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4064076)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 20:03:48,746 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=4064246)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:04:00,108 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4064712)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4064717)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4064715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4064718)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4064709)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4064714)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:05:15,440 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-09-25 20:05:15,464 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=4064709)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4064714)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4064712)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4064715)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4064716)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4064717)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4064718)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4064719)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4064716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4064719)[0m double free or corruption (fasttop)
E0925 20:05:21.871564460 4052653 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:05:44,350 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.25844967509806155, 'fusion_acc': 0.6137636363636363}, {'fusion_loss': 0.27234105706214906, 'fusion_acc': 0.5767818181818182}, {'fusion_loss': 0.21952323660254477, 'fusion_acc': 0.626109090909091}]
INFO flwr 2023-09-25 20:05:44,350 | common.py:35 | Avg. local train loss : 3.340416208282113, train acc : 0.9419597222222225
INFO flwr 2023-09-25 20:05:51,373 | server.py:116 | fit progress: (22, 2.380076141357422, {'server_test_acc': 0.6461}, 4057.8020292110014)
INFO flwr 2023-09-25 20:05:51,373 | server.py:163 | evaluate_round 22: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=4168600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4168781)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4168957)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4169150)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=4169333)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4169509)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=4169681)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 20:06:33,499 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=4169851)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:06:44,962 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4170619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4170615)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4170623)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4170626)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4170625)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4170622)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:07:58,611 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-09-25 20:07:58,636 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=4170617)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4170625)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4170622)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4170615)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4170626)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4170619)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4170624)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4170623)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4170624)[0m malloc_consolidate(): invalid chunk size
E0925 20:08:00.164482561   69952 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4170617)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:08:27,454 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3498946453034878, 'fusion_acc': 0.5058545454545453}, {'fusion_loss': 0.353002255320549, 'fusion_acc': 0.5151454545454546}, {'fusion_loss': 0.24017822669446467, 'fusion_acc': 0.602709090909091}]
INFO flwr 2023-09-25 20:08:27,455 | common.py:35 | Avg. local train loss : 3.40290180426091, train acc : 0.9385666666666667
INFO flwr 2023-09-25 20:08:34,505 | server.py:116 | fit progress: (23, 2.792381396484375, {'server_test_acc': 0.6297}, 4220.933949606002)
INFO flwr 2023-09-25 20:08:34,505 | server.py:163 | evaluate_round 23: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=81306)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=81465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=81635)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=81815)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=82282)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=82452)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=82641)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 20:09:17,205 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=82811)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:09:28,650 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=83300)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=83310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=83305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=83307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=83309)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:10:48,678 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-25 20:10:48,702 | fed_df_hetero.py:400 | Warm start at round 24
[2m[36m(launch_and_fit pid=83292)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=83308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=83311)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=175387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=175588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=176051)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=176559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=176729)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=176909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=177081)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 20:11:31,257 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 20:11:31,336 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 20:11:31,395 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 20:11:31,396 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=83307)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=83292)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=83305)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=83300)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=83310)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=83308)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=83309)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=83311)[0m Fitting Client 13
[2m[36m(launch_and_get_properties pid=177251)[0m malloc_consolidate(): invalid chunk size
E0925 20:11:35.657260222  178570 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:12:00,319 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3769115617275238, 'fusion_acc': 0.5296545454545454}, {'fusion_loss': 0.33577528505027293, 'fusion_acc': 0.6345272727272727}, {'fusion_loss': 0.3062305316627026, 'fusion_acc': 0.6061636363636363}]
INFO flwr 2023-09-25 20:12:00,319 | common.py:35 | Avg. local train loss : 3.1149567998945713, train acc : 0.9527083333333335
INFO flwr 2023-09-25 20:12:07,352 | server.py:116 | fit progress: (24, 2.8480462646484375, {'server_test_acc': 0.6252}, 4433.781115954)
INFO flwr 2023-09-25 20:12:07,353 | server.py:163 | evaluate_round 24: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=189682)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=189840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=190010)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=190182)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=190364)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=190866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=191041)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:12:49,544 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=191229)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:13:04,354 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=192059)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=192053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=192055)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=192060)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=192057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=192062)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=192061)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:14:18,896 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-25 20:14:18,920 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=192053)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=192059)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=192055)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=192060)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=192057)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=192063)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=192062)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=192061)[0m Fitting Client 14
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=192063)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:14:48,239 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.28705885604023934, 'fusion_acc': 0.43818181818181823}, {'fusion_loss': 0.3039944448471069, 'fusion_acc': 0.48849090909090903}, {'fusion_loss': 0.2150566894263029, 'fusion_acc': 0.5488727272727274}]
INFO flwr 2023-09-25 20:14:48,239 | common.py:35 | Avg. local train loss : 3.3319707328453667, train acc : 0.9468958333333332
INFO flwr 2023-09-25 20:14:55,397 | server.py:116 | fit progress: (25, 3.056057159423828, {'server_test_acc': 0.6076}, 4601.825770637002)
INFO flwr 2023-09-25 20:14:55,397 | server.py:163 | evaluate_round 25: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=319537)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=322646)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=326214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=327566)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=331915)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=335693)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=336479)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:15:38,321 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=336741)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:15:53,250 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=337503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=337493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=337501)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=337498)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=337502)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=337499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=337504)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:17:07,792 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-09-25 20:17:07,816 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=337499)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=337501)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=337498)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=337503)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=337495)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=337502)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=337504)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=337493)[0m Fitting Client 5
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=337495)[0m double free or corruption (fasttop)
E0925 20:17:09.295426837  430141 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:17:37,034 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3403502299785614, 'fusion_acc': 0.4953454545454546}, {'fusion_loss': 0.3416834853589535, 'fusion_acc': 0.5732363636363637}, {'fusion_loss': 0.2724049260318279, 'fusion_acc': 0.5886181818181818}]
INFO flwr 2023-09-25 20:17:37,034 | common.py:35 | Avg. local train loss : 3.289187225047499, train acc : 0.9435611111111111
INFO flwr 2023-09-25 20:17:44,076 | server.py:116 | fit progress: (26, 2.791203680419922, {'server_test_acc': 0.6237}, 4770.504978771001)
INFO flwr 2023-09-25 20:17:44,076 | server.py:163 | evaluate_round 26: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=441274)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=441443)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=441649)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=441828)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=442034)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=442204)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=442374)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:18:26,502 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=442546)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:18:41,495 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=443352)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=443357)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=443358)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=443359)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=443361)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=443362)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=443356)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:20:02,415 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-25 20:20:02,440 | fed_df_hetero.py:400 | Warm start at round 27
[2m[36m(launch_and_fit pid=443360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=534863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=535381)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=535550)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=535720)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=535892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=536062)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=536249)[0m double free or corruption (fasttop)
INFO flwr 2023-09-25 20:20:44,904 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 20:20:44,963 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 20:20:45,023 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 20:20:45,023 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=443352)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=443357)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=443360)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=443359)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=443358)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=443361)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=443356)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=443362)[0m Fitting Client 13
[2m[36m(launch_and_get_properties pid=536419)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:21:14,018 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3232792751789093, 'fusion_acc': 0.586090909090909}, {'fusion_loss': 0.3022673338055611, 'fusion_acc': 0.6348363636363636}, {'fusion_loss': 0.26846531897783277, 'fusion_acc': 0.6595454545454545}]
INFO flwr 2023-09-25 20:21:14,018 | common.py:35 | Avg. local train loss : 3.084376330673695, train acc : 0.9571805555555556
INFO flwr 2023-09-25 20:21:21,018 | server.py:116 | fit progress: (27, 2.2312374938964843, {'server_test_acc': 0.661}, 4987.446449472001)
INFO flwr 2023-09-25 20:21:21,018 | server.py:163 | evaluate_round 27: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=549066)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=549247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=549417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=549912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=550091)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=550263)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=550447)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:22:03,482 | fed_df_hetero.py:270 | Best Server Model Name : resnet8
[2m[36m(launch_and_get_properties pid=550617)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:22:14,701 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=551090)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551088)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551091)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551092)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551082)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551093)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:23:32,790 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-25 20:23:32,815 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=551091)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=551082)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=551090)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=551089)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=551086)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=551088)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=551092)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=551093)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=551089)[0m malloc_consolidate(): invalid chunk size
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=551086)[0m double free or corruption (fasttop)
E0925 20:23:46.449899596  594142 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:24:02,180 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.3669085783660412, 'fusion_acc': 0.4362181818181819}, {'fusion_loss': 0.3315042265355587, 'fusion_acc': 0.5453272727272728}, {'fusion_loss': 0.24954966029524803, 'fusion_acc': 0.6142545454545454}]
INFO flwr 2023-09-25 20:24:02,180 | common.py:35 | Avg. local train loss : 3.1736036252230404, train acc : 0.9509861111111112
INFO flwr 2023-09-25 20:24:09,262 | server.py:116 | fit progress: (28, 2.2066702209472657, {'server_test_acc': 0.6635}, 5155.690787561001)
INFO flwr 2023-09-25 20:24:09,262 | server.py:163 | evaluate_round 28: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=654960)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=655127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=655299)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=655469)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=655639)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=656195)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=656376)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:24:51,656 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=656552)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:25:06,417 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=657359)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=657367)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=657360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=657366)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=657363)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=657369)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-25 20:26:23,956 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-25 20:26:23,980 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=657360)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=657370)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=657368)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=657359)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=657369)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=657366)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=657367)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=657363)[0m Fitting Client 19
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_fit pid=657370)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=657368)[0m malloc_consolidate(): invalid chunk size
E0925 20:26:27.896446043  648652 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:26:53,081 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.41208625000715254, 'fusion_acc': 0.5284}, {'fusion_loss': 0.41474180367589, 'fusion_acc': 0.5461818181818182}, {'fusion_loss': 0.3163267148137093, 'fusion_acc': 0.6055454545454546}]
INFO flwr 2023-09-25 20:26:53,081 | common.py:35 | Avg. local train loss : 3.088103273697197, train acc : 0.9579472222222223
INFO flwr 2023-09-25 20:27:00,190 | server.py:116 | fit progress: (29, 2.3992557250976563, {'server_test_acc': 0.6552}, 5326.618995702)
INFO flwr 2023-09-25 20:27:00,190 | server.py:163 | evaluate_round 29: no clients selected, cancel
[2m[36m(launch_and_get_properties pid=761221)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=761398)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=761568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=761738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=761910)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=762080)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_get_properties pid=762263)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:27:42,476 | fed_df_hetero.py:270 | Best Server Model Name : wresnet-16-4
[2m[36m(launch_and_get_properties pid=762764)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:27:57,347 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=763296)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=763298)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=763293)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=763287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=763294)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=763295)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-25 20:29:10,663 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-09-25 20:29:10,688 | fed_df_hetero.py:400 | Warm start at round 30
[2m[36m(launch_and_fit pid=763297)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=763300)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=854957)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=857643)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=860669)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=861624)[0m double free or corruption (fasttop)
[2m[36m(launch_and_get_properties pid=864062)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=871367)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_get_properties pid=877865)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-25 20:29:53,255 | fed_df_hetero.py:430 | resnet8 server model initialised for fusion
INFO flwr 2023-09-25 20:29:53,277 | fed_df_hetero.py:430 | wresnet-16-4 server model initialised for fusion
INFO flwr 2023-09-25 20:29:53,355 | fed_df_hetero.py:430 | resnet20 server model initialised for fusion
INFO flwr 2023-09-25 20:29:53,355 | fed_df_hetero.py:434 | Performing server side distillation training in parallel
[2m[36m(launch_and_fit pid=763287)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=763294)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=763296)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=763297)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=763300)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=763293)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=763295)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=763298)[0m Fitting Client 2
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
[2m[36m(launch_and_get_properties pid=880087)[0m double free or corruption (fasttop)
E0925 20:30:00.644448978  750697 chttp2_transport.cc:1079]             ipv4:145.136.62.32:46845: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-25 20:30:22,619 | fed_df_hetero.py:440 | Fusion results for all models : [{'fusion_loss': 0.35473232048749925, 'fusion_acc': 0.5363636363636364}, {'fusion_loss': 0.3430486969649792, 'fusion_acc': 0.5446000000000001}, {'fusion_loss': 0.26667419204115866, 'fusion_acc': 0.6014727272727273}]
INFO flwr 2023-09-25 20:30:22,620 | common.py:35 | Avg. local train loss : 3.139269062690437, train acc : 0.9594972222222222
INFO flwr 2023-09-25 20:30:29,628 | server.py:116 | fit progress: (30, 3.8473096435546874, {'server_test_acc': 0.6182}, 5536.057160864002)
INFO flwr 2023-09-25 20:30:29,629 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-25 20:30:29,629 | server.py:144 | FL finished in 5536.057571338002
INFO flwr 2023-09-25 20:30:29,629 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-25 20:30:29,630 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-25 20:30:29,630 | app.py:204 | app_fit: losses_centralized [(0, 3.7793668823242186), (1, 3.256066979980469), (2, 3.563507568359375), (3, 2.9610592956542967), (4, 2.194740905761719), (5, 2.6596041381835938), (6, 2.7568498962402344), (7, 2.6778547424316406), (8, 2.485696240234375), (9, 2.50418017578125), (10, 2.5261666076660156), (11, 2.3012311340332032), (12, 2.7423670532226563), (13, 2.787506457519531), (14, 2.7080956848144533), (15, 3.4415918090820314), (16, 3.491408673095703), (17, 2.9162861755371092), (18, 4.359717932128906), (19, 3.8544109375), (20, 4.044396130371093), (21, 4.550144812011719), (22, 2.380076141357422), (23, 2.792381396484375), (24, 2.8480462646484375), (25, 3.056057159423828), (26, 2.791203680419922), (27, 2.2312374938964843), (28, 2.2066702209472657), (29, 2.3992557250976563), (30, 3.8473096435546874)]
INFO flwr 2023-09-25 20:30:29,631 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.1), (1, 0.3326), (2, 0.3255), (3, 0.4201), (4, 0.4668), (5, 0.4794), (6, 0.5149), (7, 0.5336), (8, 0.5489), (9, 0.5732), (10, 0.5692), (11, 0.5697), (12, 0.6203), (13, 0.6243), (14, 0.6266), (15, 0.5502), (16, 0.5634), (17, 0.6079), (18, 0.5977), (19, 0.6079), (20, 0.6027), (21, 0.5407), (22, 0.6461), (23, 0.6297), (24, 0.6252), (25, 0.6076), (26, 0.6237), (27, 0.661), (28, 0.6635), (29, 0.6552), (30, 0.6182)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn32: task 0: Aborted
srun: Terminating StepId=3925070.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3925070
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 02:26:36
CPU Efficiency: 8.39% of 1-05:06:36 core-walltime
Job Wall-clock time: 01:37:02
Memory Utilized: 20.06 GB
Memory Efficiency: 16.71% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
