-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3424559/1692481081_091882755', seed=42, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3424559/1692481081_091882755/single_img_crops/crops
50000 took 0.44min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-19 23:38:49,062 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-19 23:38:49,063 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3424559/1692481081_091882755/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3424559/1692481081_091882755/cifar-10-python.tar.gz to /scratch-local/sunnys.3424559/1692481081_091882755
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
INFO flwr 2023-08-19 23:39:13,916 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-19 23:39:16,921	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-19 23:39:18,095 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'CPU': 18.0, 'node:145.136.62.5': 1.0, 'memory': 103079215104.0, 'GPU': 1.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-08-19 23:39:18,095 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-19 23:39:18,095 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-19 23:39:18,095 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-19 23:39:28,987 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-19 23:39:28,987 | server.py:101 | FL starting
DEBUG flwr 2023-08-19 23:39:35,152 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:40:09,926 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-19 23:40:10,035 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-19 23:40:10,124 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4001882)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4001881)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4001879)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4001885)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4001884)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4001880)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4001886)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4001883)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4001883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001885)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4001880)[0m malloc_consolidate(): invalid chunk size
E0819 23:40:12.121832725 3998600 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-19 23:40:52,176 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:40:52,176 | fed_df.py:547 | Average fusion training loss : 0.07646105287969113, val accuracy : 0.2862, best val accuracy : 0.3054
INFO flwr 2023-08-19 23:40:52,177 | common.py:35 | Avg. local train loss : 8.105423599481583, train acc : 0.47100000000000003
INFO flwr 2023-08-19 23:40:54,654 | server.py:116 | fit progress: (1, 1.8326218078613281, {'server_test_acc': 0.309}, 85.66673362487927)
INFO flwr 2023-08-19 23:40:54,654 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-19 23:41:00,518 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4068313)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:41:32,012 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-19 23:41:32,168 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4068313)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4068319)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4068318)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4068317)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4068316)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4068320)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4068322)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4068321)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4068319)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4068320)[0m malloc_consolidate(): invalid chunk size
E0819 23:41:33.000157424 4028547 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=4068316)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4068321)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4068322)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4068318)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4068317)[0m double free or corruption (fasttop)
E0819 23:41:34.375042938 4093952 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-19 23:42:17,193 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:42:17,194 | fed_df.py:547 | Average fusion training loss : 0.07514579290151596, val accuracy : 0.29047999999999996, best val accuracy : 0.302
INFO flwr 2023-08-19 23:42:17,195 | common.py:35 | Avg. local train loss : 7.103906920552254, train acc : 0.5561444444444446
INFO flwr 2023-08-19 23:42:19,798 | server.py:116 | fit progress: (2, 1.94145830078125, {'server_test_acc': 0.3095}, 170.81089369300753)
INFO flwr 2023-08-19 23:42:19,798 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-19 23:42:25,764 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:42:57,168 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-19 23:42:57,314 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4134880)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4134883)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4134885)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4134884)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4134886)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4134887)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4134889)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4134888)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4134880)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4134887)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4134883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4134885)[0m malloc_consolidate(): invalid chunk size
E0819 23:42:58.438471901 4160482 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=4134888)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4134884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4134886)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4134889)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:43:42,287 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:43:42,288 | fed_df.py:547 | Average fusion training loss : 0.13171431946754455, val accuracy : 0.40815999999999997, best val accuracy : 0.4232
INFO flwr 2023-08-19 23:43:42,289 | common.py:35 | Avg. local train loss : 7.1093924909830095, train acc : 0.5586166666666667
INFO flwr 2023-08-19 23:43:44,891 | server.py:116 | fit progress: (3, 1.710496646118164, {'server_test_acc': 0.4196}, 255.90450707171112)
INFO flwr 2023-08-19 23:43:44,892 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-19 23:43:50,806 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=7893)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:44:22,603 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-19 23:44:22,746 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=7893)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=7898)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=7899)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=7894)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=7903)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=7900)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=7901)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=7902)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=7894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7900)[0m malloc_consolidate(): invalid chunk size
E0819 23:44:23.777321639   33959 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=7899)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=7903)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7901)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7902)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:45:08,043 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:45:08,044 | fed_df.py:547 | Average fusion training loss : 0.055391870006918906, val accuracy : 0.41728000000000004, best val accuracy : 0.4382
INFO flwr 2023-08-19 23:45:08,045 | common.py:35 | Avg. local train loss : 6.981571134924889, train acc : 0.5720777777777778
INFO flwr 2023-08-19 23:45:10,682 | server.py:116 | fit progress: (4, 1.580736297607422, {'server_test_acc': 0.4277}, 341.6949147717096)
INFO flwr 2023-08-19 23:45:10,682 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-19 23:45:16,587 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=74782)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:45:48,235 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-19 23:45:48,346 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-19 23:45:48,444 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=74777)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=74778)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=74780)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=74782)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=74779)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=74781)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=74774)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=74783)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=74777)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=74778)[0m malloc_consolidate(): invalid chunk size
E0819 23:45:49.094507421   34028 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=74780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=74779)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=74781)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=74783)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=74774)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:46:33,581 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:46:33,581 | fed_df.py:547 | Average fusion training loss : 0.026291048243641854, val accuracy : 0.47324, best val accuracy : 0.4774
INFO flwr 2023-08-19 23:46:33,582 | common.py:35 | Avg. local train loss : 6.76463020965457, train acc : 0.5896222222222223
INFO flwr 2023-08-19 23:46:36,266 | server.py:116 | fit progress: (5, 1.5011885681152344, {'server_test_acc': 0.4694}, 427.27873880788684)
INFO flwr 2023-08-19 23:46:36,266 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-19 23:46:42,212 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=141566)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=141573)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:47:13,939 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-19 23:47:14,089 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=141566)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=141564)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=141570)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=141573)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=141574)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=141571)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=141569)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=141572)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=141572)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=141564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=141571)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=141569)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=141574)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=141570)[0m malloc_consolidate(): invalid chunk size
E0819 23:47:15.966742757  170870 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-19 23:48:00,347 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:48:00,348 | fed_df.py:547 | Average fusion training loss : 0.03165859706699848, val accuracy : 0.5198400000000001, best val accuracy : 0.539
INFO flwr 2023-08-19 23:48:00,349 | common.py:35 | Avg. local train loss : 6.133108136802912, train acc : 0.6606222222222222
INFO flwr 2023-08-19 23:48:03,028 | server.py:116 | fit progress: (6, 1.4015735626220702, {'server_test_acc': 0.5334}, 514.0413500457071)
INFO flwr 2023-08-19 23:48:03,028 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-19 23:48:09,029 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=227229)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-19 23:48:40,900 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-19 23:48:41,051 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=227229)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=227225)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=227231)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=227232)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=227227)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=227223)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=227228)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=227230)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=227232)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=227227)[0m malloc_consolidate(): invalid chunk size
E0819 23:48:42.173545344  258400 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=227225)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=227231)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=227228)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=227230)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=227223)[0m double free or corruption (fasttop)
E0819 23:48:43.654584523  258737 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-19 23:49:26,685 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:49:26,686 | fed_df.py:547 | Average fusion training loss : 0.030596827648580075, val accuracy : 0.56968, best val accuracy : 0.5776
INFO flwr 2023-08-19 23:49:26,687 | common.py:35 | Avg. local train loss : 6.03553313612938, train acc : 0.6687166666666666
INFO flwr 2023-08-19 23:49:29,332 | server.py:116 | fit progress: (7, 1.332240591430664, {'server_test_acc': 0.5615}, 600.3453671489842)
INFO flwr 2023-08-19 23:49:29,333 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-19 23:49:35,345 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:50:07,104 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-19 23:50:07,245 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=299406)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=299409)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=299410)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=299407)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=299408)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=299413)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=299412)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=299411)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=299413)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=299406)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=299410)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=299408)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=299407)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=299409)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=299411)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=299412)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:50:52,706 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:50:52,707 | fed_df.py:547 | Average fusion training loss : 0.02781490632146597, val accuracy : 0.50644, best val accuracy : 0.5236
INFO flwr 2023-08-19 23:50:52,708 | common.py:35 | Avg. local train loss : 6.246395506709813, train acc : 0.6497000000000002
INFO flwr 2023-08-19 23:50:55,331 | server.py:116 | fit progress: (8, 1.429972671508789, {'server_test_acc': 0.5228}, 686.3441172759049)
INFO flwr 2023-08-19 23:50:55,331 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-19 23:51:01,260 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=366021)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:51:33,016 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-19 23:51:33,160 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=366018)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=366025)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=366021)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=366022)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=366020)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=366023)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=366024)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=366026)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=366018)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=366025)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=366020)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=366023)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=366026)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=366024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=366022)[0m malloc_consolidate(): invalid chunk size
E0819 23:51:35.298935392  259994 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-19 23:52:18,564 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:52:18,565 | fed_df.py:547 | Average fusion training loss : 0.029889229469001292, val accuracy : 0.57236, best val accuracy : 0.5886
INFO flwr 2023-08-19 23:52:18,566 | common.py:35 | Avg. local train loss : 5.895256546139717, train acc : 0.6859888888888889
INFO flwr 2023-08-19 23:52:21,242 | server.py:116 | fit progress: (9, 1.3271201995849609, {'server_test_acc': 0.5769}, 772.2552239908837)
INFO flwr 2023-08-19 23:52:21,242 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-19 23:52:27,225 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=432561)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:52:58,777 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-19 23:52:58,888 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-19 23:52:58,976 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=432561)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=432566)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=432567)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=432564)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=432569)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=432568)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=432562)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=432565)[0m Fitting Client 13
E0819 23:52:59.507158748  457294 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=432566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=432567)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=432568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=432562)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=432565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=432564)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=432569)[0m malloc_consolidate(): invalid chunk size
E0819 23:53:00.853173271  458766 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-19 23:53:44,316 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:53:44,317 | fed_df.py:547 | Average fusion training loss : 0.026293610081076623, val accuracy : 0.60056, best val accuracy : 0.609
INFO flwr 2023-08-19 23:53:44,318 | common.py:35 | Avg. local train loss : 5.7024956539273255, train acc : 0.70505
INFO flwr 2023-08-19 23:53:46,928 | server.py:116 | fit progress: (10, 1.3068063751220702, {'server_test_acc': 0.5909}, 857.9411313077435)
INFO flwr 2023-08-19 23:53:46,928 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-19 23:53:52,908 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:54:24,852 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=499205)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=499206)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:54:25,010 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=499209)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=499206)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=499205)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=499211)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=499202)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=499210)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=499208)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=499207)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=499207)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=499210)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=499202)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=499208)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=499209)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=499211)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:55:15,643 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:55:15,643 | fed_df.py:547 | Average fusion training loss : 0.01895332147926092, val accuracy : 0.60072, best val accuracy : 0.611
INFO flwr 2023-08-19 23:55:15,644 | common.py:35 | Avg. local train loss : 5.572350826114416, train acc : 0.7177222222222223
INFO flwr 2023-08-19 23:55:18,272 | server.py:116 | fit progress: (11, 1.2612880096435546, {'server_test_acc': 0.5964}, 949.2849461799487)
INFO flwr 2023-08-19 23:55:18,272 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-19 23:55:24,208 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=565831)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:55:55,838 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-19 23:55:55,982 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=565831)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=565835)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=565839)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=565838)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=565837)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=565836)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=565840)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=565841)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=565839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=565835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=565837)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=565840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=565841)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=565838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=565836)[0m malloc_consolidate(): invalid chunk size
E0819 23:55:58.098532723  591844 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-19 23:56:41,688 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:56:41,688 | fed_df.py:547 | Average fusion training loss : 0.017858717124909163, val accuracy : 0.6324799999999999, best val accuracy : 0.638
INFO flwr 2023-08-19 23:56:41,690 | common.py:35 | Avg. local train loss : 5.706184819340706, train acc : 0.7037444444444445
INFO flwr 2023-08-19 23:56:44,322 | server.py:116 | fit progress: (12, 1.2327634368896485, {'server_test_acc': 0.6213}, 1035.334869459737)
INFO flwr 2023-08-19 23:56:44,322 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-19 23:56:50,266 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:57:21,643 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-19 23:57:21,788 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=632443)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=632442)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=632440)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=632444)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=632441)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=632437)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=632436)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=632439)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=632441)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=632437)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=632440)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=632436)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=632443)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=632444)[0m double free or corruption (fasttop)
E0819 23:57:23.753403166  592449 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=632439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=632442)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:58:07,490 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:58:07,491 | fed_df.py:547 | Average fusion training loss : 0.016251284055411815, val accuracy : 0.60904, best val accuracy : 0.612
INFO flwr 2023-08-19 23:58:07,492 | common.py:35 | Avg. local train loss : 5.508836679160596, train acc : 0.7205555555555556
INFO flwr 2023-08-19 23:58:10,377 | server.py:116 | fit progress: (13, 1.2923200134277344, {'server_test_acc': 0.592}, 1121.390548354946)
INFO flwr 2023-08-19 23:58:10,378 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-19 23:58:16,320 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:58:48,048 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-19 23:58:48,193 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=698859)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=698863)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=698862)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=698864)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=698865)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=698866)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=698860)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=698867)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=698864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=698865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=698862)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698867)[0m malloc_consolidate(): invalid chunk size
E0819 23:58:51.571634529  725367 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-19 23:59:34,136 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:59:34,137 | fed_df.py:547 | Average fusion training loss : 0.033343284130096434, val accuracy : 0.56992, best val accuracy : 0.5754
INFO flwr 2023-08-19 23:59:34,138 | common.py:35 | Avg. local train loss : 5.468373291939496, train acc : 0.72845
INFO flwr 2023-08-19 23:59:36,787 | server.py:116 | fit progress: (14, 1.3376067626953125, {'server_test_acc': 0.5677}, 1207.799668150954)
INFO flwr 2023-08-19 23:59:36,787 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-19 23:59:42,723 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=765675)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-20 00:00:14,575 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=765680)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:00:14,688 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 00:00:14,784 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=765679)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=765675)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=765680)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=765681)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=765682)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=765683)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=765684)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=765678)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=765682)[0m double free or corruption (fasttop)
E0820 00:00:15.198827098  790613 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=765683)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=765684)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=765678)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=765681)[0m double free or corruption (fasttop)
E0820 00:00:16.124501179  790681 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=765679)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:01:00,206 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:01:00,206 | fed_df.py:547 | Average fusion training loss : 0.018964604917913675, val accuracy : 0.57012, best val accuracy : 0.5826
INFO flwr 2023-08-20 00:01:00,207 | common.py:35 | Avg. local train loss : 5.3103492766618725, train acc : 0.740388888888889
INFO flwr 2023-08-20 00:01:02,858 | server.py:116 | fit progress: (15, 1.3321098602294923, {'server_test_acc': 0.5661}, 1293.87079176493)
INFO flwr 2023-08-20 00:01:02,858 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 00:01:08,863 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=832045)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:01:40,301 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 00:01:40,445 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=832037)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=832041)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=832039)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=832042)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=832044)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=832047)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=832043)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=832045)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=832037)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=832043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=832039)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=832042)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=832044)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=832041)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=832047)[0m malloc_consolidate(): invalid chunk size
E0820 00:01:42.596285885  791565 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:02:26,321 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:02:26,321 | fed_df.py:547 | Average fusion training loss : 0.014972076188772917, val accuracy : 0.6340399999999999, best val accuracy : 0.6406
INFO flwr 2023-08-20 00:02:26,322 | common.py:35 | Avg. local train loss : 5.215686372667552, train acc : 0.7513277777777778
INFO flwr 2023-08-20 00:02:28,968 | server.py:116 | fit progress: (16, 1.2375445129394531, {'server_test_acc': 0.6277}, 1379.980659124907)
INFO flwr 2023-08-20 00:02:28,968 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 00:02:34,922 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=898655)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:03:06,821 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 00:03:06,972 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=898653)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=898655)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=898659)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=898662)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=898661)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=898664)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=898663)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=898660)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=898663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=898662)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=898653)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=898659)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=898661)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=898660)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=898664)[0m double free or corruption (fasttop)
E0820 00:03:09.086568374  858915 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:03:53,598 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:03:53,598 | fed_df.py:547 | Average fusion training loss : 0.02538747625797987, val accuracy : 0.5875600000000001, best val accuracy : 0.589
INFO flwr 2023-08-20 00:03:53,599 | common.py:35 | Avg. local train loss : 5.357809219509363, train acc : 0.7413000000000001
E0820 00:03:55.270051732  981947 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:03:56,266 | server.py:116 | fit progress: (17, 1.338632943725586, {'server_test_acc': 0.5787}, 1467.2790107629262)
INFO flwr 2023-08-20 00:03:56,266 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 00:04:02,303 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:04:33,797 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 00:04:33,942 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=986964)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=986733)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=986812)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=986735)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=986975)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=986976)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=986964)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=986903)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=986805)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=986735)[0m double free or corruption (fasttop)
E0820 00:04:34.630825851  982419 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=986975)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=986812)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=986976)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=986903)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=986805)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=986733)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:05:19,769 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:05:19,769 | fed_df.py:547 | Average fusion training loss : 0.014220613446086645, val accuracy : 0.63228, best val accuracy : 0.639
INFO flwr 2023-08-20 00:05:19,771 | common.py:35 | Avg. local train loss : 5.218076721578837, train acc : 0.7535888888888889
INFO flwr 2023-08-20 00:05:22,419 | server.py:116 | fit progress: (18, 1.2383706909179688, {'server_test_acc': 0.6353}, 1553.4325441420078)
INFO flwr 2023-08-20 00:05:22,420 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 00:05:28,401 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:05:59,844 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 00:05:59,989 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1056551)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1056553)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1056549)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1056555)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1056548)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1056550)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1056554)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1056552)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1056549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1056551)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1056553)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1056554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1056548)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1056550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1056555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1056552)[0m malloc_consolidate(): invalid chunk size
E0820 00:06:21.767331080 1098012 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:06:46,164 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:06:46,165 | fed_df.py:547 | Average fusion training loss : 0.014414722926914692, val accuracy : 0.641, best val accuracy : 0.6476
INFO flwr 2023-08-20 00:06:46,166 | common.py:35 | Avg. local train loss : 5.273115921020508, train acc : 0.7489833333333333
INFO flwr 2023-08-20 00:06:48,809 | server.py:116 | fit progress: (19, 1.2383506103515625, {'server_test_acc': 0.6354}, 1639.8225630740635)
INFO flwr 2023-08-20 00:06:48,810 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 00:06:54,718 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1123249)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 00:07:26,230 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 00:07:26,342 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-20 00:07:26,431 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1123245)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1123247)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1123249)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1123251)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1123253)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1123252)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1123255)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1123254)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1123255)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1123252)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1123251)[0m double free or corruption (fasttop)
E0820 00:07:27.470300876 1099827 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1123245)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1123247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1123253)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1123254)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 00:08:12,433 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:08:12,434 | fed_df.py:547 | Average fusion training loss : 0.020554933305829762, val accuracy : 0.66552, best val accuracy : 0.6726
INFO flwr 2023-08-20 00:08:12,435 | common.py:35 | Avg. local train loss : 5.220613842457533, train acc : 0.7561444444444443
INFO flwr 2023-08-20 00:08:15,096 | server.py:116 | fit progress: (20, 1.1570427734375, {'server_test_acc': 0.657}, 1726.109236762859)
INFO flwr 2023-08-20 00:08:15,096 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 00:08:21,079 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1189672)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 00:08:52,700 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 00:08:52,844 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1189672)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1189673)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1189675)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1189677)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1189674)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1189678)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1189679)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1189676)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1189679)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1189677)[0m malloc_consolidate(): invalid chunk size
E0820 00:08:53.450855604 1214952 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1189673)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1189675)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1189674)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1189676)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1189678)[0m malloc_consolidate(): invalid chunk size
E0820 00:09:15.689352922 1215355 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:09:38,895 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:09:38,895 | fed_df.py:547 | Average fusion training loss : 0.014908358477056027, val accuracy : 0.58152, best val accuracy : 0.5996
INFO flwr 2023-08-20 00:09:38,897 | common.py:35 | Avg. local train loss : 5.071888027340173, train acc : 0.7669500000000001
INFO flwr 2023-08-20 00:09:41,500 | server.py:116 | fit progress: (21, 1.278704669189453, {'server_test_acc': 0.5959}, 1812.5130659998395)
INFO flwr 2023-08-20 00:09:41,500 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 00:09:47,450 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:10:19,021 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-20 00:10:19,166 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1256540)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1256543)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1256541)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1256539)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1256544)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1256545)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1256538)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1256542)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1256540)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1256545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1256544)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1256541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1256539)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1256543)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1256538)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1256542)[0m double free or corruption (fasttop)
E0820 00:10:21.966744265 1234139 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:11:05,056 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:11:05,057 | fed_df.py:547 | Average fusion training loss : 0.022051571905612945, val accuracy : 0.65644, best val accuracy : 0.662
INFO flwr 2023-08-20 00:11:05,058 | common.py:35 | Avg. local train loss : 5.2194369986653335, train acc : 0.7553444444444446
INFO flwr 2023-08-20 00:11:07,701 | server.py:116 | fit progress: (22, 1.1978244995117187, {'server_test_acc': 0.652}, 1898.7140487888828)
INFO flwr 2023-08-20 00:11:07,701 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 00:11:13,686 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1322922)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 00:11:45,212 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-20 00:11:45,356 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1322922)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1322921)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1322917)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1322919)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1322926)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1322924)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1322925)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1322923)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1322926)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1322921)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1322924)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1322917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1322925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1322923)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1322919)[0m malloc_consolidate(): invalid chunk size
E0820 00:11:48.803249239 1283820 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:12:31,240 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:12:31,240 | fed_df.py:547 | Average fusion training loss : 0.02284936935082078, val accuracy : 0.6365999999999999, best val accuracy : 0.6456
INFO flwr 2023-08-20 00:12:31,241 | common.py:35 | Avg. local train loss : 5.372505746781826, train acc : 0.7399333333333333
INFO flwr 2023-08-20 00:12:33,883 | server.py:116 | fit progress: (23, 1.221207354736328, {'server_test_acc': 0.6326}, 1984.8964280369692)
INFO flwr 2023-08-20 00:12:33,884 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 00:12:39,955 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:13:11,813 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-20 00:13:11,964 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1389507)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1389513)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1389514)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1389511)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1389515)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1389516)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1389510)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1389517)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1389513)[0m malloc_consolidate(): invalid chunk size
E0820 00:13:12.362233075 1414503 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1389517)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1389511)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1389514)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1389515)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1389510)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1389507)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1389516)[0m malloc_consolidate(): invalid chunk size
E0820 00:13:13.964999768 1415765 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:13:57,991 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:13:57,992 | fed_df.py:547 | Average fusion training loss : 0.01716091464832425, val accuracy : 0.66056, best val accuracy : 0.668
INFO flwr 2023-08-20 00:13:57,993 | common.py:35 | Avg. local train loss : 5.0913325548172, train acc : 0.7667222222222223
INFO flwr 2023-08-20 00:14:00,654 | server.py:116 | fit progress: (24, 1.1687253295898437, {'server_test_acc': 0.6524}, 2071.6667477646843)
INFO flwr 2023-08-20 00:14:00,654 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 00:14:06,643 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1456175)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 00:14:38,269 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-20 00:14:38,383 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=1456172)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 00:14:38,473 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1456176)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1456167)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1456175)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1456173)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1456177)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1456171)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1456172)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1456174)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1456174)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1456173)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1456167)[0m malloc_consolidate(): invalid chunk size
E0820 00:14:39.795195488 1416101 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1456177)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1456176)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1456171)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:15:24,454 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:15:24,454 | fed_df.py:547 | Average fusion training loss : 0.022932558551430702, val accuracy : 0.65292, best val accuracy : 0.657
INFO flwr 2023-08-20 00:15:24,456 | common.py:35 | Avg. local train loss : 5.1799752309918405, train acc : 0.7585944444444443
INFO flwr 2023-08-20 00:15:27,109 | server.py:116 | fit progress: (25, 1.1946176788330078, {'server_test_acc': 0.6485}, 2158.121706025675)
INFO flwr 2023-08-20 00:15:27,109 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 00:15:33,084 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1522763)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:16:04,634 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-20 00:16:04,779 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1522763)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1522764)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1522771)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1522770)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1522769)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1522767)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1522768)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1522766)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1522764)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1522769)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1522768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1522767)[0m malloc_consolidate(): invalid chunk size
E0820 00:16:05.964500620 1482147 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1522766)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1522770)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:16:55,937 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:16:55,937 | fed_df.py:547 | Average fusion training loss : 0.014099078826606274, val accuracy : 0.60936, best val accuracy : 0.6202
INFO flwr 2023-08-20 00:16:55,938 | common.py:35 | Avg. local train loss : 5.055651515722275, train acc : 0.7691333333333334
INFO flwr 2023-08-20 00:16:58,620 | server.py:116 | fit progress: (26, 1.2713392059326172, {'server_test_acc': 0.6067}, 2249.6327425688505)
INFO flwr 2023-08-20 00:16:58,620 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 00:17:04,633 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1589344)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:17:36,147 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 00:17:36,314 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1589344)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1589345)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1589346)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1589354)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1589351)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1589350)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1589352)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1589353)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1589346)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1589354)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1589352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1589345)[0m malloc_consolidate(): invalid chunk size
E0820 00:17:37.638855699 1548455 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1589350)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1589351)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1589353)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:18:22,903 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:18:22,903 | fed_df.py:547 | Average fusion training loss : 0.01754422814771533, val accuracy : 0.6664800000000001, best val accuracy : 0.6746
INFO flwr 2023-08-20 00:18:22,905 | common.py:35 | Avg. local train loss : 5.062330493330955, train acc : 0.7714277777777777
INFO flwr 2023-08-20 00:18:25,592 | server.py:116 | fit progress: (27, 1.1737151245117188, {'server_test_acc': 0.6613}, 2336.604985842947)
INFO flwr 2023-08-20 00:18:25,592 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 00:18:31,628 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1666966)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-20 00:19:03,304 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1666967)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:19:03,450 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1666966)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1666967)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1666962)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1666963)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1666964)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1666965)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1666969)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1666968)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1666965)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1666962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1666963)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1666968)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1666964)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1666969)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:19:50,458 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:19:50,458 | fed_df.py:547 | Average fusion training loss : 0.024987716659903528, val accuracy : 0.6380399999999999, best val accuracy : 0.6556
INFO flwr 2023-08-20 00:19:50,460 | common.py:35 | Avg. local train loss : 5.095028623193502, train acc : 0.7691444444444444
INFO flwr 2023-08-20 00:19:53,134 | server.py:116 | fit progress: (28, 1.2275975036621094, {'server_test_acc': 0.6476}, 2424.147062249016)
INFO flwr 2023-08-20 00:19:53,134 | server.py:163 | evaluate_round 28: no clients selected, cancel
E0820 00:19:54.052559215 1744747 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
DEBUG flwr 2023-08-20 00:19:59,096 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:20:30,451 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-20 00:20:30,595 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1747270)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1747273)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1747278)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1747276)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1747277)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1747280)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1747275)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1747279)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1747273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1747270)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1747280)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1747279)[0m malloc_consolidate(): invalid chunk size
E0820 00:20:31.970440002 1746934 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1747275)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1747277)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1747278)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1747276)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:21:16,444 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:21:16,444 | fed_df.py:547 | Average fusion training loss : 0.013011822950094938, val accuracy : 0.6673600000000001, best val accuracy : 0.6748
INFO flwr 2023-08-20 00:21:16,445 | common.py:35 | Avg. local train loss : 4.964532614499331, train acc : 0.7805944444444444
INFO flwr 2023-08-20 00:21:19,091 | server.py:116 | fit progress: (29, 1.1596941955566407, {'server_test_acc': 0.661}, 2510.1045283498242)
INFO flwr 2023-08-20 00:21:19,092 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 00:21:25,045 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1813838)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:21:56,715 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 00:21:56,828 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 00:21:56,916 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1813836)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1813838)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1813840)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1813842)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1813844)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1813839)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1813841)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1813843)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1813836)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1813842)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1813841)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1813839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1813844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1813840)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1813843)[0m double free or corruption (fasttop)
E0820 00:22:00.361361958 1773221 chttp2_transport.cc:1079]             ipv4:145.136.62.5:58069: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:22:43,009 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:22:43,009 | fed_df.py:547 | Average fusion training loss : 0.0196974222548306, val accuracy : 0.63944, best val accuracy : 0.6466
INFO flwr 2023-08-20 00:22:43,010 | common.py:35 | Avg. local train loss : 4.981687080860138, train acc : 0.7774055555555555
INFO flwr 2023-08-20 00:22:45,645 | server.py:116 | fit progress: (30, 1.2221794494628906, {'server_test_acc': 0.6309}, 2596.658106710762)
INFO flwr 2023-08-20 00:22:45,645 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 00:22:45,645 | server.py:144 | FL finished in 2596.658533812035
INFO flwr 2023-08-20 00:22:45,646 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 00:22:45,647 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 00:22:45,647 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.8326218078613281), (2, 1.94145830078125), (3, 1.710496646118164), (4, 1.580736297607422), (5, 1.5011885681152344), (6, 1.4015735626220702), (7, 1.332240591430664), (8, 1.429972671508789), (9, 1.3271201995849609), (10, 1.3068063751220702), (11, 1.2612880096435546), (12, 1.2327634368896485), (13, 1.2923200134277344), (14, 1.3376067626953125), (15, 1.3321098602294923), (16, 1.2375445129394531), (17, 1.338632943725586), (18, 1.2383706909179688), (19, 1.2383506103515625), (20, 1.1570427734375), (21, 1.278704669189453), (22, 1.1978244995117187), (23, 1.221207354736328), (24, 1.1687253295898437), (25, 1.1946176788330078), (26, 1.2713392059326172), (27, 1.1737151245117188), (28, 1.2275975036621094), (29, 1.1596941955566407), (30, 1.2221794494628906)]
INFO flwr 2023-08-20 00:22:45,647 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.309), (2, 0.3095), (3, 0.4196), (4, 0.4277), (5, 0.4694), (6, 0.5334), (7, 0.5615), (8, 0.5228), (9, 0.5769), (10, 0.5909), (11, 0.5964), (12, 0.6213), (13, 0.592), (14, 0.5677), (15, 0.5661), (16, 0.6277), (17, 0.5787), (18, 0.6353), (19, 0.6354), (20, 0.657), (21, 0.5959), (22, 0.652), (23, 0.6326), (24, 0.6524), (25, 0.6485), (26, 0.6067), (27, 0.6613), (28, 0.6476), (29, 0.661), (30, 0.6309)]}
corrupted size vs. prev_size in fastbins
srun: error: gcn5: task 0: Aborted
srun: Terminating StepId=3424559.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3424559
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:51:41
CPU Efficiency: 13.30% of 13:59:42 core-walltime
Job Wall-clock time: 00:46:39
Memory Utilized: 48.96 GB
Memory Efficiency: 40.80% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
