-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:bottom
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3424563/1692481089_106072233', seed=84, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3424563/1692481089_106072233/single_img_crops/crops
50000 took 0.44min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-19 23:38:53,574 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-19 23:38:53,574 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3424563/1692481089_106072233/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3424563/1692481089_106072233/cifar-10-python.tar.gz to /scratch-local/sunnys.3424563/1692481089_106072233
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
INFO flwr 2023-08-19 23:39:17,069 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-19 23:39:20,946	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-19 23:39:22,017 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.27': 1.0, 'object_store_memory': 61847529062.0, 'accelerator_type:A100': 1.0, 'GPU': 1.0, 'CPU': 18.0, 'memory': 103079215104.0}
INFO flwr 2023-08-19 23:39:22,017 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-19 23:39:22,017 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-19 23:39:22,017 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-19 23:39:32,415 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-19 23:39:32,415 | server.py:101 | FL starting
DEBUG flwr 2023-08-19 23:39:38,425 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:40:10,705 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=471538)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=471525)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:40:10,814 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-19 23:40:10,903 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=471503)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=471512)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=471538)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=471507)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=471501)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=471502)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=471525)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=471500)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=471502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=471503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=471512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=471500)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=471501)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=471507)[0m malloc_consolidate(): invalid chunk size
E0819 23:40:12.938929417  501459 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0819 23:40:12.939124884  501459 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0819 23:40:12.939146396  501459 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-19 23:40:53,911 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:40:53,911 | fed_df.py:547 | Average fusion training loss : 0.109881113499403, val accuracy : 0.29244, best val accuracy : 0.3102
INFO flwr 2023-08-19 23:40:53,912 | common.py:35 | Avg. local train loss : 8.278302702307702, train acc : 0.4384444444444444
INFO flwr 2023-08-19 23:40:56,464 | server.py:116 | fit progress: (1, 1.8826087615966798, {'server_test_acc': 0.3049}, 84.04813492577523)
INFO flwr 2023-08-19 23:40:56,464 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-19 23:41:02,266 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:41:34,053 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-19 23:41:34,191 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=541480)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=541481)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=541474)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=541477)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=541478)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=541482)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=541479)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=541476)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=541480)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541479)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541481)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541477)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541478)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541482)[0m malloc_consolidate(): invalid chunk size
E0819 23:41:36.211393428  568366 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=541474)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541476)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 23:42:19,771 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:42:19,771 | fed_df.py:547 | Average fusion training loss : 0.14804264497756958, val accuracy : 0.34524, best val accuracy : 0.36
INFO flwr 2023-08-19 23:42:19,772 | common.py:35 | Avg. local train loss : 7.411329700052738, train acc : 0.5215666666666667
INFO flwr 2023-08-19 23:42:22,381 | server.py:116 | fit progress: (2, 1.7989968963623046, {'server_test_acc': 0.3525}, 169.96584427310154)
INFO flwr 2023-08-19 23:42:22,382 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-19 23:42:28,303 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=608735)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 23:42:59,808 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-19 23:42:59,947 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=608735)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=608739)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=608742)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=608740)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=608738)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=608741)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=608732)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=608736)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=608738)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=608741)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=608739)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=608742)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=608732)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=608740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=608736)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 23:43:45,564 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:43:45,564 | fed_df.py:547 | Average fusion training loss : 0.13565424516797064, val accuracy : 0.39475999999999994, best val accuracy : 0.4218
INFO flwr 2023-08-19 23:43:45,565 | common.py:35 | Avg. local train loss : 7.171047092229127, train acc : 0.5468000000000001
INFO flwr 2023-08-19 23:43:48,205 | server.py:116 | fit progress: (3, 1.6587549957275391, {'server_test_acc': 0.4181}, 255.78937830775976)
INFO flwr 2023-08-19 23:43:48,205 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-19 23:43:54,108 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=675964)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:44:26,763 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-19 23:44:26,903 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=675963)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=675969)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=675966)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=675968)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=675972)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=675971)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=675970)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=675964)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=675971)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=675963)[0m double free or corruption (fasttop)
E0819 23:44:28.150633206  707193 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
E0819 23:44:28.150741534  707193 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
E0819 23:44:28.150754968  707193 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
E0819 23:44:28.150765804  707193 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=675968)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=675966)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=675972)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=675970)[0m malloc_consolidate(): invalid chunk size
E0819 23:44:29.424230627  708196 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-19 23:45:15,424 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:45:15,425 | fed_df.py:547 | Average fusion training loss : 0.18672628879547118, val accuracy : 0.441, best val accuracy : 0.4568
INFO flwr 2023-08-19 23:45:15,425 | common.py:35 | Avg. local train loss : 6.7739897496998305, train acc : 0.5912222222222222
INFO flwr 2023-08-19 23:45:18,149 | server.py:116 | fit progress: (4, 1.6388026275634766, {'server_test_acc': 0.4545}, 345.7332582268864)
INFO flwr 2023-08-19 23:45:18,149 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-19 23:45:24,142 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:45:57,173 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-19 23:45:57,282 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-19 23:45:57,373 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=789344)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=789275)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=789347)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=789415)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=789417)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=789418)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=789416)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=789346)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=789275)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=789344)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=789415)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=789416)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=789418)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=789417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=789347)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=789346)[0m malloc_consolidate(): invalid chunk size
E0819 23:45:59.485034030  832868 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-19 23:46:45,970 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:46:45,970 | fed_df.py:547 | Average fusion training loss : 0.17014971381425859, val accuracy : 0.45640000000000003, best val accuracy : 0.4716
INFO flwr 2023-08-19 23:46:45,971 | common.py:35 | Avg. local train loss : 6.519639433175325, train acc : 0.6155999999999999
INFO flwr 2023-08-19 23:46:48,650 | server.py:116 | fit progress: (5, 1.59055185546875, {'server_test_acc': 0.4676}, 436.2348773931153)
INFO flwr 2023-08-19 23:46:48,651 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-19 23:46:54,774 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=903537)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=903548)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:47:28,809 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-19 23:47:28,949 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=903537)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=903539)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=903550)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=903551)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=903543)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=903541)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=903548)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=903549)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=903550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=903541)[0m double free or corruption (fasttop)
E0819 23:47:30.001897224  833124 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=903543)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=903551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=903549)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=903539)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:48:16,953 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:48:16,954 | fed_df.py:547 | Average fusion training loss : 0.14845679366588593, val accuracy : 0.42704000000000003, best val accuracy : 0.4378
INFO flwr 2023-08-19 23:48:16,955 | common.py:35 | Avg. local train loss : 5.848862954974175, train acc : 0.6814222222222222
INFO flwr 2023-08-19 23:48:19,716 | server.py:116 | fit progress: (6, 1.7757435119628906, {'server_test_acc': 0.432}, 527.3007471929304)
INFO flwr 2023-08-19 23:48:19,717 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-19 23:48:26,011 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1033848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1033849)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 23:48:58,305 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-19 23:48:58,463 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1033849)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1033848)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1033847)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1033856)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1033855)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1033850)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1033853)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1033854)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1033850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1033854)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1033853)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1033855)[0m double free or corruption (fasttop)
E0819 23:48:59.869609068 1082364 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=1033856)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1033847)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:49:47,979 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:49:47,980 | fed_df.py:547 | Average fusion training loss : 0.12436809104681015, val accuracy : 0.48236, best val accuracy : 0.5042
INFO flwr 2023-08-19 23:49:47,981 | common.py:35 | Avg. local train loss : 6.250411707162858, train acc : 0.6478888888888888
INFO flwr 2023-08-19 23:49:50,727 | server.py:116 | fit progress: (7, 1.5260533416748048, {'server_test_acc': 0.4941}, 618.3110496187583)
INFO flwr 2023-08-19 23:49:50,727 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-19 23:49:56,810 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:50:28,567 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-19 23:50:28,708 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1158787)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1158785)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1158788)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1158857)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1158858)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1158860)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1158859)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1158856)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1158859)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1158785)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1158787)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1158860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1158788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1158856)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1158857)[0m malloc_consolidate(): invalid chunk size
E0819 23:50:30.640974322 1082501 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1158858)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:51:17,804 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:51:17,805 | fed_df.py:547 | Average fusion training loss : 0.09102779749035836, val accuracy : 0.5358799999999999, best val accuracy : 0.543
INFO flwr 2023-08-19 23:51:17,806 | common.py:35 | Avg. local train loss : 6.096403962373733, train acc : 0.6569500000000001
INFO flwr 2023-08-19 23:51:20,555 | server.py:116 | fit progress: (8, 1.4624138610839843, {'server_test_acc': 0.532}, 708.1397051457316)
INFO flwr 2023-08-19 23:51:20,555 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-19 23:51:26,545 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1279618)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:52:00,534 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-19 23:52:00,675 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1279621)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1279617)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1279622)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1279618)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1279620)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1279624)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1279623)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1279625)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1279617)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1279621)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1279624)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1279622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1279625)[0m malloc_consolidate(): invalid chunk size
E0819 23:52:01.833880044 1325476 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=1279620)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1279623)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 23:52:49,349 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:52:49,349 | fed_df.py:547 | Average fusion training loss : 0.0897113392651081, val accuracy : 0.5352399999999999, best val accuracy : 0.5478
INFO flwr 2023-08-19 23:52:49,350 | common.py:35 | Avg. local train loss : 5.843965902924538, train acc : 0.6864388888888889
INFO flwr 2023-08-19 23:52:52,040 | server.py:116 | fit progress: (9, 1.4774379119873047, {'server_test_acc': 0.5463}, 799.624542389065)
INFO flwr 2023-08-19 23:52:52,040 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-19 23:52:57,997 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1393653)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1393660)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 23:53:30,942 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-19 23:53:31,053 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-19 23:53:31,141 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1393653)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1393660)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1393661)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1393655)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1393795)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1393797)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1393794)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1393796)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1393661)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1393796)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1393795)[0m double free or corruption (fasttop)
E0819 23:53:32.431377770 1325627 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=1393655)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1393794)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1393797)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:54:21,211 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:54:21,212 | fed_df.py:547 | Average fusion training loss : 0.11996538522839546, val accuracy : 0.5346399999999999, best val accuracy : 0.545
INFO flwr 2023-08-19 23:54:21,213 | common.py:35 | Avg. local train loss : 5.941701561212541, train acc : 0.6746222222222222
INFO flwr 2023-08-19 23:54:24,088 | server.py:116 | fit progress: (10, 1.5154408416748046, {'server_test_acc': 0.5374}, 891.6726592839696)
INFO flwr 2023-08-19 23:54:24,088 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-19 23:54:30,466 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1546886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1546814)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 23:55:02,613 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-19 23:55:02,765 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1546814)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1546889)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1546888)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1546886)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1546912)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1546887)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1546890)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1546904)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1546904)[0m double free or corruption (fasttop)
E0819 23:55:03.392533166 1452939 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=1546887)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1546888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1546890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1546889)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1546912)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 23:55:52,916 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:55:52,916 | fed_df.py:547 | Average fusion training loss : 0.08432570603489876, val accuracy : 0.51488, best val accuracy : 0.53
INFO flwr 2023-08-19 23:55:52,917 | common.py:35 | Avg. local train loss : 6.190224057435989, train acc : 0.6514888888888889
INFO flwr 2023-08-19 23:55:55,709 | server.py:116 | fit progress: (11, 1.471199380493164, {'server_test_acc': 0.5196}, 983.2933510420844)
INFO flwr 2023-08-19 23:55:55,709 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-19 23:56:01,747 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:56:33,827 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1679212)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 23:56:33,969 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1679209)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1679212)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1679207)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1679211)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1679210)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1679213)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1679215)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1679214)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1679211)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1679215)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1679207)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1679210)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1679213)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1679209)[0m double free or corruption (fasttop)
E0819 23:56:35.952272470 1716313 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1679214)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 23:57:24,616 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:57:24,616 | fed_df.py:547 | Average fusion training loss : 0.06012741547822952, val accuracy : 0.53664, best val accuracy : 0.5594
INFO flwr 2023-08-19 23:57:24,618 | common.py:35 | Avg. local train loss : 5.6479158133268355, train acc : 0.7034055555555555
INFO flwr 2023-08-19 23:57:27,317 | server.py:116 | fit progress: (12, 1.4153275848388671, {'server_test_acc': 0.5523}, 1074.90196095407)
INFO flwr 2023-08-19 23:57:27,318 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-19 23:57:33,247 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1797215)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1797216)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1797213)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-19 23:58:08,489 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-19 23:58:08,631 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1797213)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1797215)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1797216)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1797219)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1797217)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1797218)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1797214)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1797211)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1797219)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1797218)[0m malloc_consolidate(): invalid chunk size
E0819 23:58:09.921679648 1716567 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1797214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1797217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1797211)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 23:58:57,119 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 23:58:57,119 | fed_df.py:547 | Average fusion training loss : 0.05790467524528503, val accuracy : 0.5638799999999999, best val accuracy : 0.5716
INFO flwr 2023-08-19 23:58:57,121 | common.py:35 | Avg. local train loss : 5.409608642756939, train acc : 0.7265277777777778
INFO flwr 2023-08-19 23:58:59,973 | server.py:116 | fit progress: (13, 1.3920053833007813, {'server_test_acc': 0.5686}, 1167.5578494789079)
INFO flwr 2023-08-19 23:58:59,974 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-19 23:59:06,005 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 23:59:39,411 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-19 23:59:39,557 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1918273)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1918004)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1918272)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1918005)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1918274)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1918138)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1918140)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1918002)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1918273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1918005)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1918272)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1918002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1918274)[0m malloc_consolidate(): invalid chunk size
E0819 23:59:41.627610990 1973259 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1918138)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1918004)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 00:00:28,793 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:00:28,793 | fed_df.py:547 | Average fusion training loss : 0.07946986708045006, val accuracy : 0.56036, best val accuracy : 0.5738
INFO flwr 2023-08-20 00:00:28,794 | common.py:35 | Avg. local train loss : 5.583301234990358, train acc : 0.7134055555555556
INFO flwr 2023-08-20 00:00:31,527 | server.py:116 | fit progress: (14, 1.3978968231201172, {'server_test_acc': 0.5684}, 1259.1111229867674)
INFO flwr 2023-08-20 00:00:31,527 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 00:00:37,591 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2049120)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:01:09,872 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-20 00:01:09,981 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 00:01:10,070 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2049114)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2049115)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2049117)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2049121)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2049116)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2049119)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2049118)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2049120)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2049116)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049119)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2049121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049117)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049118)[0m double free or corruption (fasttop)
E0820 00:01:49.296936457 2145997 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-20 00:01:59,667 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:01:59,667 | fed_df.py:547 | Average fusion training loss : 0.08438806664943695, val accuracy : 0.5953999999999999, best val accuracy : 0.609
INFO flwr 2023-08-20 00:01:59,668 | common.py:35 | Avg. local train loss : 5.513857413083315, train acc : 0.7168666666666668
INFO flwr 2023-08-20 00:02:02,450 | server.py:116 | fit progress: (15, 1.3444649139404297, {'server_test_acc': 0.605}, 1350.0347046628594)
INFO flwr 2023-08-20 00:02:02,450 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 00:02:08,467 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2171397)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 00:02:41,224 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 00:02:41,367 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2171397)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2171400)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2171403)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2171401)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2171399)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2171402)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2171404)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2171405)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2171400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2171403)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2171399)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2171405)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2171402)[0m corrupted size vs. prev_size in fastbins
E0820 00:02:42.728014577 2149168 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=2171404)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2171401)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:03:30,910 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:03:30,910 | fed_df.py:547 | Average fusion training loss : 0.07661391201615333, val accuracy : 0.5828800000000001, best val accuracy : 0.5886
INFO flwr 2023-08-20 00:03:30,911 | common.py:35 | Avg. local train loss : 5.391137962043285, train acc : 0.7290666666666668
INFO flwr 2023-08-20 00:03:33,629 | server.py:116 | fit progress: (16, 1.4458898223876953, {'server_test_acc': 0.5855}, 1441.213063810952)
INFO flwr 2023-08-20 00:03:33,629 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 00:03:39,885 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:04:13,815 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 00:04:13,957 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2286118)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2286117)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2286121)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2286115)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2286114)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2286119)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2286116)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2286120)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2286118)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2286117)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2286121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2286116)[0m malloc_consolidate(): invalid chunk size
E0820 00:04:17.499609409 2211584 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:05:02,372 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:05:02,372 | fed_df.py:547 | Average fusion training loss : 0.06500948223471642, val accuracy : 0.5898, best val accuracy : 0.5952
INFO flwr 2023-08-20 00:05:02,373 | common.py:35 | Avg. local train loss : 5.558347512781621, train acc : 0.7138277777777777
INFO flwr 2023-08-20 00:05:05,301 | server.py:116 | fit progress: (17, 1.3979495025634765, {'server_test_acc': 0.5832}, 1532.8853170117363)
INFO flwr 2023-08-20 00:05:05,301 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 00:05:11,965 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2414383)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2414386)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:05:44,180 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 00:05:44,321 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2414383)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2414386)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2414532)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2414399)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2414533)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2414536)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2414535)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2414534)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2414532)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2414535)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2414399)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2414536)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2414533)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2414534)[0m malloc_consolidate(): invalid chunk size
E0820 00:05:46.765041661 2464214 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:06:33,664 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:06:33,665 | fed_df.py:547 | Average fusion training loss : 0.051909788280725476, val accuracy : 0.5979599999999999, best val accuracy : 0.603
INFO flwr 2023-08-20 00:06:33,666 | common.py:35 | Avg. local train loss : 5.344100314378739, train acc : 0.7352833333333334
INFO flwr 2023-08-20 00:06:36,411 | server.py:116 | fit progress: (18, 1.4010381134033203, {'server_test_acc': 0.5964}, 1623.9951511397958)
INFO flwr 2023-08-20 00:06:36,411 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 00:06:42,514 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2539738)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:07:14,075 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 00:07:14,214 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2539738)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2539742)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2539744)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2539745)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2539815)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2539814)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2539741)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2539743)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2539815)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539741)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539744)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2539814)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539743)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539745)[0m malloc_consolidate(): invalid chunk size
E0820 00:07:17.735702229 2579983 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:08:04,134 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:08:04,134 | fed_df.py:547 | Average fusion training loss : 0.04663710168004036, val accuracy : 0.6244799999999999, best val accuracy : 0.6304
INFO flwr 2023-08-20 00:08:04,135 | common.py:35 | Avg. local train loss : 5.366243531554937, train acc : 0.7348944444444443
INFO flwr 2023-08-20 00:08:06,892 | server.py:116 | fit progress: (19, 1.3606053192138672, {'server_test_acc': 0.6124}, 1714.476389952004)
INFO flwr 2023-08-20 00:08:06,892 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 00:08:12,888 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2661312)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:08:46,858 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 00:08:46,968 | fed_df.py:365 | Warm start at round 20
[2m[36m(launch_and_fit pid=2661314)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:08:47,059 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2661242)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2661312)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2661315)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2661314)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2661383)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2661385)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2661384)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2661313)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2661242)[0m double free or corruption (fasttop)
E0820 00:08:47.821703263 2705120 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2661315)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2661384)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2661383)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2661385)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2661313)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:09:36,436 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:09:36,436 | fed_df.py:547 | Average fusion training loss : 0.09246271347999573, val accuracy : 0.6013999999999999, best val accuracy : 0.6178
INFO flwr 2023-08-20 00:09:36,437 | common.py:35 | Avg. local train loss : 5.610164439678192, train acc : 0.7100444444444445
INFO flwr 2023-08-20 00:09:39,191 | server.py:116 | fit progress: (20, 1.4361190368652343, {'server_test_acc': 0.6112}, 1806.7756993528455)
INFO flwr 2023-08-20 00:09:39,192 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 00:09:45,240 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:10:18,190 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2796535)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:10:18,332 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2796535)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2796605)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2796670)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2796671)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2796560)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2796672)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2796673)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2796669)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2796560)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2796671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2796672)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2796605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2796673)[0m malloc_consolidate(): invalid chunk size
E0820 00:10:19.714547359 2859687 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2796670)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2796669)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:11:07,458 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:11:07,458 | fed_df.py:547 | Average fusion training loss : 0.09104506993293762, val accuracy : 0.63176, best val accuracy : 0.6394
INFO flwr 2023-08-20 00:11:07,459 | common.py:35 | Avg. local train loss : 5.499210579693318, train acc : 0.7232222222222222
INFO flwr 2023-08-20 00:11:10,257 | server.py:116 | fit progress: (21, 1.4388182922363282, {'server_test_acc': 0.6224}, 1897.8419214808382)
INFO flwr 2023-08-20 00:11:10,258 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 00:11:16,463 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:11:49,085 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-20 00:11:49,250 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2933087)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2933042)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2933087)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2933219)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2933220)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2933084)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2933086)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2932949)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2933083)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2933042)[0m double free or corruption (fasttop)
E0820 00:11:49.962012912 2979683 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2933086)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2933084)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2932949)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2933220)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2933219)[0m malloc_consolidate(): invalid chunk size
E0820 00:11:50.568488907 2980107 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2933083)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:12:39,238 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:12:39,239 | fed_df.py:547 | Average fusion training loss : 0.05455237279832363, val accuracy : 0.6012000000000001, best val accuracy : 0.6176
INFO flwr 2023-08-20 00:12:39,240 | common.py:35 | Avg. local train loss : 5.228714888542891, train acc : 0.7473833333333332
INFO flwr 2023-08-20 00:12:42,024 | server.py:116 | fit progress: (22, 1.4322916839599609, {'server_test_acc': 0.5986}, 1989.6086924658157)
INFO flwr 2023-08-20 00:12:42,024 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 00:12:48,200 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3057618)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:13:20,077 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-20 00:13:20,219 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3057618)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3057616)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3057620)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3057625)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3057624)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3057623)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3057626)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3057622)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3057620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3057623)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3057616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3057622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3057624)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3057625)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3057626)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 00:14:15,843 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:14:15,843 | fed_df.py:547 | Average fusion training loss : 0.06312213797867298, val accuracy : 0.60348, best val accuracy : 0.612
INFO flwr 2023-08-20 00:14:15,844 | common.py:35 | Avg. local train loss : 5.180491124838591, train acc : 0.7530333333333333
INFO flwr 2023-08-20 00:14:18,647 | server.py:116 | fit progress: (23, 1.4917506591796874, {'server_test_acc': 0.6049}, 2086.231498667039)
INFO flwr 2023-08-20 00:14:18,647 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 00:14:24,751 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3178851)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3178856)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:14:59,222 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3178854)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:14:59,383 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3178851)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3178854)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3178853)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3178855)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3178857)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3178856)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3178859)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3178858)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3178853)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3178857)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3178859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3178855)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3178858)[0m malloc_consolidate(): invalid chunk size
E0820 00:15:02.220165422 2980790 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:15:48,621 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:15:48,622 | fed_df.py:547 | Average fusion training loss : 0.068280802115798, val accuracy : 0.62396, best val accuracy : 0.6304
INFO flwr 2023-08-20 00:15:48,623 | common.py:35 | Avg. local train loss : 5.532515093684197, train acc : 0.7207222222222224
INFO flwr 2023-08-20 00:15:51,375 | server.py:116 | fit progress: (24, 1.4331749938964844, {'server_test_acc': 0.6206}, 2178.9593738047406)
INFO flwr 2023-08-20 00:15:51,375 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 00:15:57,426 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3296247)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:16:30,476 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-20 00:16:30,587 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-20 00:16:30,677 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3296247)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3296286)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3296288)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3296285)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3296248)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3296283)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3296287)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3296284)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3296283)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3296248)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3296288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3296285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3296286)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3296287)[0m double free or corruption (fasttop)
E0820 00:16:33.054991858 3232293 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3296284)[0m malloc_consolidate(): invalid chunk size
E0820 00:16:43.994767419 3354212 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:17:20,776 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:17:20,776 | fed_df.py:547 | Average fusion training loss : 0.05741814166307449, val accuracy : 0.62056, best val accuracy : 0.6322
INFO flwr 2023-08-20 00:17:20,777 | common.py:35 | Avg. local train loss : 5.283021283149719, train acc : 0.7403833333333333
INFO flwr 2023-08-20 00:17:23,571 | server.py:116 | fit progress: (25, 1.444744662475586, {'server_test_acc': 0.6148}, 2271.1551164127886)
INFO flwr 2023-08-20 00:17:23,571 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 00:17:29,579 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3429456)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:18:01,140 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-20 00:18:01,281 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3429456)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3429532)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3429531)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3429530)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3429529)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3429533)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3429534)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3429535)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3429532)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3429534)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3429530)[0m double free or corruption (fasttop)
E0820 00:18:02.610128907 3471112 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3429529)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429531)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3429533)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:18:51,336 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:18:51,336 | fed_df.py:547 | Average fusion training loss : 0.043561493173241615, val accuracy : 0.64628, best val accuracy : 0.656
INFO flwr 2023-08-20 00:18:51,337 | common.py:35 | Avg. local train loss : 5.424077350646257, train acc : 0.7284833333333333
INFO flwr 2023-08-20 00:18:54,121 | server.py:116 | fit progress: (26, 1.4297118804931641, {'server_test_acc': 0.6433}, 2361.7056257310323)
INFO flwr 2023-08-20 00:18:54,121 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 00:19:00,237 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3552016)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 00:19:32,233 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 00:19:32,401 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3552085)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3552086)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3552016)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3552017)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3552089)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3552088)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3552090)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3552087)[0m Fitting Client 18
E0820 00:19:32.991923180 3471318 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3552085)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3552089)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3552086)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3552088)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3552090)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3552087)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3552017)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 00:20:22,615 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:20:22,616 | fed_df.py:547 | Average fusion training loss : 0.05095134393870831, val accuracy : 0.63756, best val accuracy : 0.6472
INFO flwr 2023-08-20 00:20:22,617 | common.py:35 | Avg. local train loss : 5.177106142789126, train acc : 0.7553388888888889
INFO flwr 2023-08-20 00:20:25,343 | server.py:116 | fit progress: (27, 1.458819970703125, {'server_test_acc': 0.633}, 2452.9273476358503)
INFO flwr 2023-08-20 00:20:25,343 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 00:20:31,407 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:21:03,321 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-20 00:21:03,463 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3665878)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3665882)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3665885)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3665880)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3665879)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3665883)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3665884)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3665881)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3665882)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3665880)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665883)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3665879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665878)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3665885)[0m malloc_consolidate(): invalid chunk size
E0820 00:21:05.836053475 3692732 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:21:52,552 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:21:52,552 | fed_df.py:547 | Average fusion training loss : 0.0672723688185215, val accuracy : 0.64216, best val accuracy : 0.6476
INFO flwr 2023-08-20 00:21:52,553 | common.py:35 | Avg. local train loss : 5.3247099801898, train acc : 0.7403277777777778
INFO flwr 2023-08-20 00:21:55,634 | server.py:116 | fit progress: (28, 1.4705947357177733, {'server_test_acc': 0.6362}, 2543.2189666661434)
INFO flwr 2023-08-20 00:21:55,635 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-20 00:22:02,618 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 00:22:40,660 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-20 00:22:40,803 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3732865)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3732863)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3732860)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3732858)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3732864)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3732861)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3732862)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3732859)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3732865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3732863)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3732858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3732862)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3732861)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3732859)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3732864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3732860)[0m double free or corruption (fasttop)
E0820 00:22:43.189422672 3759612 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:23:29,089 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:23:29,089 | fed_df.py:547 | Average fusion training loss : 0.06799319323897361, val accuracy : 0.6224399999999999, best val accuracy : 0.6354
INFO flwr 2023-08-20 00:23:29,090 | common.py:35 | Avg. local train loss : 5.282080283015967, train acc : 0.7436388888888888
INFO flwr 2023-08-20 00:23:31,826 | server.py:116 | fit progress: (29, 1.4598053436279297, {'server_test_acc': 0.6205}, 2639.4106955779716)
INFO flwr 2023-08-20 00:23:31,826 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 00:23:37,817 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3799699)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 00:24:09,631 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 00:24:09,745 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 00:24:09,852 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3799699)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3799701)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3799707)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3799704)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3799703)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3799706)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3799702)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3799705)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3799701)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3799702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3799706)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3799707)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3799703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3799705)[0m malloc_consolidate(): invalid chunk size
E0820 00:24:11.845144274 3826071 chttp2_transport.cc:1079]             ipv4:145.136.62.27:36872: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 00:24:58,458 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 00:24:58,459 | fed_df.py:547 | Average fusion training loss : 0.07526252716779709, val accuracy : 0.6317999999999999, best val accuracy : 0.6376
INFO flwr 2023-08-20 00:24:58,460 | common.py:35 | Avg. local train loss : 4.850220204144716, train acc : 0.78605
INFO flwr 2023-08-20 00:25:01,230 | server.py:116 | fit progress: (30, 1.5224931762695313, {'server_test_acc': 0.6214}, 2728.814517040737)
INFO flwr 2023-08-20 00:25:01,230 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 00:25:01,230 | server.py:144 | FL finished in 2728.814883395098
INFO flwr 2023-08-20 00:25:01,231 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 00:25:01,232 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 00:25:01,232 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.8826087615966798), (2, 1.7989968963623046), (3, 1.6587549957275391), (4, 1.6388026275634766), (5, 1.59055185546875), (6, 1.7757435119628906), (7, 1.5260533416748048), (8, 1.4624138610839843), (9, 1.4774379119873047), (10, 1.5154408416748046), (11, 1.471199380493164), (12, 1.4153275848388671), (13, 1.3920053833007813), (14, 1.3978968231201172), (15, 1.3444649139404297), (16, 1.4458898223876953), (17, 1.3979495025634765), (18, 1.4010381134033203), (19, 1.3606053192138672), (20, 1.4361190368652343), (21, 1.4388182922363282), (22, 1.4322916839599609), (23, 1.4917506591796874), (24, 1.4331749938964844), (25, 1.444744662475586), (26, 1.4297118804931641), (27, 1.458819970703125), (28, 1.4705947357177733), (29, 1.4598053436279297), (30, 1.5224931762695313)]
INFO flwr 2023-08-20 00:25:01,232 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.3049), (2, 0.3525), (3, 0.4181), (4, 0.4545), (5, 0.4676), (6, 0.432), (7, 0.4941), (8, 0.532), (9, 0.5463), (10, 0.5374), (11, 0.5196), (12, 0.5523), (13, 0.5686), (14, 0.5684), (15, 0.605), (16, 0.5855), (17, 0.5832), (18, 0.5964), (19, 0.6124), (20, 0.6112), (21, 0.6224), (22, 0.5986), (23, 0.6049), (24, 0.6206), (25, 0.6148), (26, 0.6433), (27, 0.633), (28, 0.6362), (29, 0.6205), (30, 0.6214)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn27: task 0: Aborted
srun: Terminating StepId=3424563.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3424563
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:56:52
CPU Efficiency: 13.42% of 14:30:36 core-walltime
Job Wall-clock time: 00:48:22
Memory Utilized: 51.88 GB
Memory Efficiency: 43.23% of 120.00 GB
