-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:20000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:9
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=20000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3358515/1692176705_095469762', seed=84, img_per_thread=1111)
will save 20000 patches in /scratch-local/sunnys.3358515/1692176705_095469762/single_img_crops/crops
20000 took 0.14min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-16 11:05:26,886 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-16 11:05:26,886 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3358515/1692176705_095469762/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3358515/1692176705_095469762/cifar-10-python.tar.gz to /scratch-local/sunnys.3358515/1692176705_095469762
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [225 194 247 272 217 251 256 333 258 247]
INFO flwr 2023-08-16 11:05:45,112 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-16 11:05:47,626	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-16 11:05:48,621 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.38': 1.0, 'accelerator_type:A100': 1.0, 'GPU': 1.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0}
INFO flwr 2023-08-16 11:05:48,621 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-16 11:05:48,621 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-16 11:05:48,621 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-16 11:05:59,572 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-16 11:05:59,572 | server.py:101 | FL starting
DEBUG flwr 2023-08-16 11:06:04,565 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:06:52,363 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-16 11:06:52,577 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-16 11:06:52,701 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=792553)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=792551)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=792547)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=792552)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=792546)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=792549)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=792550)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=792548)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=792553)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=792546)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=792550)[0m double free or corruption (fasttop)
E0816 11:06:53.860343445  789412 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=792548)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=792547)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=792552)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=792551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=792549)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:07:20,789 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:07:20,790 | fed_df.py:547 | Average fusion training loss : 0.018924050617963074, val accuracy : 0.42284, best val accuracy : 0.44
INFO flwr 2023-08-16 11:07:20,791 | common.py:35 | Avg. local train loss : 8.773364333808422, train acc : 0.3847194444444444
INFO flwr 2023-08-16 11:07:23,192 | server.py:116 | fit progress: (1, 1.533942950439453, {'server_test_acc': 0.4544}, 83.61963934701635)
INFO flwr 2023-08-16 11:07:23,192 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-16 11:07:28,174 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:08:15,365 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-16 11:08:15,650 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=866459)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=866458)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=866460)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=866462)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=866461)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=866463)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=866457)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=866464)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=866462)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866461)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=866459)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=866463)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866460)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=866464)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866458)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866457)[0m malloc_consolidate(): invalid chunk size
E0816 11:08:17.683839905  840636 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-16 11:08:43,644 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:08:43,645 | fed_df.py:547 | Average fusion training loss : 0.013108834475278854, val accuracy : 0.51416, best val accuracy : 0.5494
INFO flwr 2023-08-16 11:08:43,647 | common.py:35 | Avg. local train loss : 7.233570565283298, train acc : 0.5546833333333333
INFO flwr 2023-08-16 11:08:46,064 | server.py:116 | fit progress: (2, 1.4111561645507813, {'server_test_acc': 0.554}, 166.49220997400698)
INFO flwr 2023-08-16 11:08:46,065 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-16 11:08:51,017 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=940305)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:09:37,806 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-16 11:09:38,090 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=940305)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=940306)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=940308)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=940307)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=940310)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=940312)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=940311)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=940309)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=940306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=940312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=940307)[0m malloc_consolidate(): invalid chunk size
E0816 11:09:38.961842236  914969 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=940310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=940308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=940309)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=940311)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:10:06,235 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:10:06,235 | fed_df.py:547 | Average fusion training loss : 0.010522040128707886, val accuracy : 0.5666800000000001, best val accuracy : 0.5944
INFO flwr 2023-08-16 11:10:06,237 | common.py:35 | Avg. local train loss : 6.58023468926549, train acc : 0.6275083333333332
INFO flwr 2023-08-16 11:10:08,670 | server.py:116 | fit progress: (3, 1.3397473693847657, {'server_test_acc': 0.5964}, 249.09741261901218)
INFO flwr 2023-08-16 11:10:08,670 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-16 11:10:13,673 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1013997)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1013996)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1013999)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:11:00,876 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-16 11:11:01,160 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1013997)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1013996)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1013999)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1014002)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1014003)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1014004)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1014006)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1014005)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1014004)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1014003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1014002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1014005)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1014006)[0m malloc_consolidate(): invalid chunk size
E0816 11:11:03.358158969 1062313 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-16 11:11:29,395 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:11:29,396 | fed_df.py:547 | Average fusion training loss : 0.0067068618796765804, val accuracy : 0.58972, best val accuracy : 0.6202
INFO flwr 2023-08-16 11:11:29,398 | common.py:35 | Avg. local train loss : 6.246996680647135, train acc : 0.6608694444444444
INFO flwr 2023-08-16 11:11:31,867 | server.py:116 | fit progress: (4, 1.2401222778320313, {'server_test_acc': 0.6177}, 332.29498272400815)
INFO flwr 2023-08-16 11:11:31,867 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-16 11:11:36,846 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1087880)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087888)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:12:24,120 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-16 11:12:24,337 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-16 11:12:24,463 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1087880)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1087886)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1087882)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1087884)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1087885)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1087883)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1087887)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1087888)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1087887)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1087883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1087885)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087882)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1087886)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:12:53,092 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:12:53,093 | fed_df.py:547 | Average fusion training loss : 0.010288022107444703, val accuracy : 0.6461600000000001, best val accuracy : 0.6588
INFO flwr 2023-08-16 11:12:53,095 | common.py:35 | Avg. local train loss : 5.970743527263403, train acc : 0.6936
INFO flwr 2023-08-16 11:12:55,544 | server.py:116 | fit progress: (5, 1.113608056640625, {'server_test_acc': 0.6511}, 415.97217776300386)
INFO flwr 2023-08-16 11:12:55,545 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-16 11:13:00,586 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1183221)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1183248)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1183249)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:13:47,499 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-16 11:13:47,787 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1183221)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1183247)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1183248)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1183249)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1183253)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1183250)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1183252)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1183251)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1183247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1183251)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1183253)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1183250)[0m double free or corruption (fasttop)
E0816 11:13:49.116419758 1062920 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=1183252)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:14:16,099 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:14:16,099 | fed_df.py:547 | Average fusion training loss : 0.004094357894733548, val accuracy : 0.6662399999999999, best val accuracy : 0.6722
INFO flwr 2023-08-16 11:14:16,101 | common.py:35 | Avg. local train loss : 5.608217182382941, train acc : 0.7262361111111112
INFO flwr 2023-08-16 11:14:18,546 | server.py:116 | fit progress: (6, 1.1036437774658203, {'server_test_acc': 0.6676}, 498.9736286450061)
INFO flwr 2023-08-16 11:14:18,546 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-16 11:14:23,575 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1260498)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1260494)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:15:11,110 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-16 11:15:11,395 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1260494)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1260498)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1260496)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1260500)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1260502)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1260499)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1260497)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1260501)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1260496)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1260502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1260497)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1260500)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1260499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1260501)[0m double free or corruption (fasttop)
E0816 11:15:13.247007898 1234885 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-16 11:15:39,841 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:15:39,841 | fed_df.py:547 | Average fusion training loss : 0.004185605340637267, val accuracy : 0.65408, best val accuracy : 0.6656
INFO flwr 2023-08-16 11:15:39,843 | common.py:35 | Avg. local train loss : 5.451265289261937, train acc : 0.7430722222222224
INFO flwr 2023-08-16 11:15:42,296 | server.py:116 | fit progress: (7, 1.1275882415771485, {'server_test_acc': 0.6597}, 582.7239462870057)
INFO flwr 2023-08-16 11:15:42,296 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-16 11:15:47,257 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1334112)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1334118)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:16:34,172 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1334120)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:16:34,458 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1334119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1334112)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1334118)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1334119)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1334117)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1334121)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1334123)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1334122)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1334120)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1334117)[0m malloc_consolidate(): invalid chunk size
E0816 11:16:34.745614670 1308970 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=1334121)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1334123)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1334122)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:17:02,754 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:17:02,754 | fed_df.py:547 | Average fusion training loss : 0.003985009589232504, val accuracy : 0.6726, best val accuracy : 0.6764
INFO flwr 2023-08-16 11:17:02,756 | common.py:35 | Avg. local train loss : 5.361765252426268, train acc : 0.7534666666666666
INFO flwr 2023-08-16 11:17:05,213 | server.py:116 | fit progress: (8, 1.0900843566894531, {'server_test_acc': 0.6762}, 665.64056188002)
INFO flwr 2023-08-16 11:17:05,213 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-16 11:17:10,193 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1408052)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:17:57,549 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1408055)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:17:57,835 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1408050)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1408051)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1408052)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1408053)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1408055)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1408054)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1408057)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1408056)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1408051)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1408057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1408054)[0m malloc_consolidate(): invalid chunk size
E0816 11:17:58.734064418 1381548 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1408053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1408050)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1408056)[0m malloc_consolidate(): invalid chunk size
E0816 11:17:59.910338267 1455928 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-16 11:18:26,171 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:18:26,172 | fed_df.py:547 | Average fusion training loss : 0.003573001562617719, val accuracy : 0.66964, best val accuracy : 0.679
INFO flwr 2023-08-16 11:18:26,174 | common.py:35 | Avg. local train loss : 5.268423953279854, train acc : 0.7649750000000001
INFO flwr 2023-08-16 11:18:28,624 | server.py:116 | fit progress: (9, 1.088238851928711, {'server_test_acc': 0.672}, 749.0514498859993)
INFO flwr 2023-08-16 11:18:28,624 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-16 11:18:33,633 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1481876)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:19:20,418 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-16 11:19:20,636 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-16 11:19:20,763 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1481876)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1481880)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1481875)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1481884)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1481881)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1481882)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1481885)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1481883)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1481875)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1481881)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1481880)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481883)[0m malloc_consolidate(): invalid chunk size
E0816 11:19:22.027124797 1456929 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=1481885)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1481882)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:19:49,319 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:19:49,320 | fed_df.py:547 | Average fusion training loss : 0.010891427459195257, val accuracy : 0.67296, best val accuracy : 0.6798
INFO flwr 2023-08-16 11:19:49,322 | common.py:35 | Avg. local train loss : 5.2269810874015095, train acc : 0.768036111111111
INFO flwr 2023-08-16 11:19:51,796 | server.py:116 | fit progress: (10, 1.087343341064453, {'server_test_acc': 0.6859}, 832.2238518780214)
INFO flwr 2023-08-16 11:19:51,796 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-16 11:19:56,811 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1555663)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:20:44,107 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1555670)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:20:44,395 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1555663)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1555668)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1555669)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1555670)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1555666)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1555667)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1555665)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1555671)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1555671)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1555669)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1555666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1555668)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1555665)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1555667)[0m double free or corruption (fasttop)
E0816 11:20:49.545319062 1606493 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-16 11:21:12,965 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:21:12,965 | fed_df.py:547 | Average fusion training loss : 0.003574206128716469, val accuracy : 0.68712, best val accuracy : 0.689
INFO flwr 2023-08-16 11:21:12,967 | common.py:35 | Avg. local train loss : 5.016924389451742, train acc : 0.7857055555555554
INFO flwr 2023-08-16 11:21:15,444 | server.py:116 | fit progress: (11, 1.0945976745605468, {'server_test_acc': 0.6861}, 915.8721560700214)
INFO flwr 2023-08-16 11:21:15,445 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-16 11:21:20,515 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1629393)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1629400)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:22:07,901 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-16 11:22:08,187 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1629393)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1629397)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1629396)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1629400)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1629401)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1629399)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1629402)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1629403)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1629401)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1629403)[0m double free or corruption (fasttop)
E0816 11:22:08.639173275 1606963 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1629396)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1629397)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1629402)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1629399)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:22:36,736 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:22:36,737 | fed_df.py:547 | Average fusion training loss : 0.0032314781406894326, val accuracy : 0.6802, best val accuracy : 0.697
INFO flwr 2023-08-16 11:22:36,739 | common.py:35 | Avg. local train loss : 5.083303322643041, train acc : 0.7811805555555557
INFO flwr 2023-08-16 11:22:39,199 | server.py:116 | fit progress: (12, 1.0598533477783203, {'server_test_acc': 0.6961}, 999.6263796620187)
INFO flwr 2023-08-16 11:22:39,199 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-16 11:22:44,272 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1703208)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1703210)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:23:31,516 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-16 11:23:31,804 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1703208)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1703212)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1703210)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1703213)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1703211)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1703215)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1703214)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1703216)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1703213)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1703211)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1703212)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1703214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1703216)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1703215)[0m malloc_consolidate(): invalid chunk size
E0816 11:23:35.178700439 1676778 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-16 11:24:00,551 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:24:00,551 | fed_df.py:547 | Average fusion training loss : 0.003020331426989287, val accuracy : 0.6994, best val accuracy : 0.7064
INFO flwr 2023-08-16 11:24:00,553 | common.py:35 | Avg. local train loss : 4.973165791481733, train acc : 0.7922055555555556
INFO flwr 2023-08-16 11:24:03,058 | server.py:116 | fit progress: (13, 1.0433772583007812, {'server_test_acc': 0.7074}, 1083.4860423180216)
INFO flwr 2023-08-16 11:24:03,059 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-16 11:24:08,055 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1777139)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777140)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:24:55,510 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-16 11:24:55,795 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1777140)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1777139)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1777142)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1777144)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1777145)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1777148)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1777146)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1777147)[0m Fitting Client 18
E0816 11:24:56.145686204 1753164 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1777144)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777147)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1777148)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777142)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777145)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777146)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:25:24,492 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:25:24,493 | fed_df.py:547 | Average fusion training loss : 0.0034850921807810663, val accuracy : 0.6912, best val accuracy : 0.7012
INFO flwr 2023-08-16 11:25:24,495 | common.py:35 | Avg. local train loss : 4.990261786803603, train acc : 0.7911611111111111
INFO flwr 2023-08-16 11:25:26,973 | server.py:116 | fit progress: (14, 1.0488144653320313, {'server_test_acc': 0.6949}, 1167.400759058015)
INFO flwr 2023-08-16 11:25:26,973 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-16 11:25:31,945 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1850962)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1850963)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:26:19,855 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-16 11:26:20,075 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-16 11:26:20,200 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1850962)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1850963)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1850966)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1850967)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1850965)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1850964)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1850968)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1850969)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1850969)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1850964)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1850968)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1850965)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1850966)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1850967)[0m malloc_consolidate(): invalid chunk size
E0816 11:26:21.556936727 1898759 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0816 11:26:40.359106720 1914567 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-16 11:26:48,746 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:26:48,746 | fed_df.py:547 | Average fusion training loss : 0.0124024048903957, val accuracy : 0.70324, best val accuracy : 0.7112
INFO flwr 2023-08-16 11:26:48,748 | common.py:35 | Avg. local train loss : 5.005812598019839, train acc : 0.7888111111111111
INFO flwr 2023-08-16 11:26:51,323 | server.py:116 | fit progress: (15, 1.0362488067626954, {'server_test_acc': 0.7072}, 1251.7505284450017)
INFO flwr 2023-08-16 11:26:51,323 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-16 11:26:56,305 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1924854)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1924858)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:27:43,661 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1924852)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:27:43,947 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1924852)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1924854)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1924856)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1924859)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1924858)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1924861)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1924862)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1924860)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1924862)[0m malloc_consolidate(): invalid chunk size
E0816 11:27:44.502032844 1914971 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1924856)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1924861)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1924860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1924859)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:28:12,913 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:28:12,913 | fed_df.py:547 | Average fusion training loss : 0.002914070713799447, val accuracy : 0.71488, best val accuracy : 0.7182
INFO flwr 2023-08-16 11:28:12,915 | common.py:35 | Avg. local train loss : 4.729188074544072, train acc : 0.8131944444444444
INFO flwr 2023-08-16 11:28:15,428 | server.py:116 | fit progress: (16, 1.0337856475830078, {'server_test_acc': 0.713}, 1335.8553889890027)
INFO flwr 2023-08-16 11:28:15,428 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-16 11:28:20,603 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2018678)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:29:07,906 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2018717)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:29:08,196 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2018678)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2018717)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2018718)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2018719)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2018720)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2018722)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2018705)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2018721)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2018721)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2018722)[0m malloc_consolidate(): invalid chunk size
E0816 11:29:09.168676402 1976085 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2018720)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2018718)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2018719)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2018705)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:29:36,874 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:29:36,875 | fed_df.py:547 | Average fusion training loss : 0.0026212475863285362, val accuracy : 0.7191599999999999, best val accuracy : 0.7282
INFO flwr 2023-08-16 11:29:36,877 | common.py:35 | Avg. local train loss : 4.80045675188303, train acc : 0.8092916666666667
INFO flwr 2023-08-16 11:29:39,374 | server.py:116 | fit progress: (17, 0.9944493774414063, {'server_test_acc': 0.7172}, 1419.801583190012)
INFO flwr 2023-08-16 11:29:39,374 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-16 11:29:44,405 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2097105)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:30:31,745 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2097111)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:30:32,033 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2097105)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2097108)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2097109)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2097111)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2097110)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2097113)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2097114)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2097112)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2097112)[0m malloc_consolidate(): invalid chunk size
E0816 11:30:32.460085718 2144207 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2097110)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2097114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2097113)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2097109)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:31:00,729 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:31:00,730 | fed_df.py:547 | Average fusion training loss : 0.0029586883396841585, val accuracy : 0.69672, best val accuracy : 0.7064
INFO flwr 2023-08-16 11:31:00,732 | common.py:35 | Avg. local train loss : 4.767900824919343, train acc : 0.8124444444444445
INFO flwr 2023-08-16 11:31:03,212 | server.py:116 | fit progress: (18, 1.0262483459472656, {'server_test_acc': 0.7073}, 1503.6397781550186)
INFO flwr 2023-08-16 11:31:03,212 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-16 11:31:08,220 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:31:57,158 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-16 11:31:57,446 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2170983)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2170978)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2170980)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2170987)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2170988)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2170984)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2170985)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2170986)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2170987)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2170980)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2170984)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2170988)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2170985)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2170983)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2170978)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2170986)[0m double free or corruption (fasttop)
E0816 11:31:59.396708524 2144343 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:32:26,367 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:32:26,368 | fed_df.py:547 | Average fusion training loss : 0.002611358942463994, val accuracy : 0.71648, best val accuracy : 0.7236
INFO flwr 2023-08-16 11:32:26,370 | common.py:35 | Avg. local train loss : 4.811008162796497, train acc : 0.8087055555555556
INFO flwr 2023-08-16 11:32:28,831 | server.py:116 | fit progress: (19, 0.9960323211669921, {'server_test_acc': 0.7207}, 1589.258724550018)
INFO flwr 2023-08-16 11:32:28,831 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-16 11:32:33,818 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2244903)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:33:21,163 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-16 11:33:21,377 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-16 11:33:21,504 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2244903)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2244904)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2244906)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2244908)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2244907)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2244911)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2244909)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2244910)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2244904)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2244910)[0m malloc_consolidate(): invalid chunk size
E0816 11:33:22.237761164 2291785 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2244906)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2244908)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2244907)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2244909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2244911)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:33:50,434 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:33:50,435 | fed_df.py:547 | Average fusion training loss : 0.01206340395193547, val accuracy : 0.7204400000000001, best val accuracy : 0.73
INFO flwr 2023-08-16 11:33:50,437 | common.py:35 | Avg. local train loss : 4.784514387696982, train acc : 0.8113694444444444
INFO flwr 2023-08-16 11:33:52,920 | server.py:116 | fit progress: (20, 1.063532147216797, {'server_test_acc': 0.7266}, 1673.3477051109949)
INFO flwr 2023-08-16 11:33:52,920 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-16 11:33:57,951 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:34:45,191 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2318754)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:34:45,479 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2318750)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2318753)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2318752)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2318751)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2318757)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2318756)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2318754)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2318755)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2318756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318757)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2318750)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318755)[0m malloc_consolidate(): invalid chunk size
E0816 11:34:49.055367472 2292256 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:35:14,477 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:35:14,477 | fed_df.py:547 | Average fusion training loss : 0.002056475430727005, val accuracy : 0.7212, best val accuracy : 0.7316
INFO flwr 2023-08-16 11:35:14,479 | common.py:35 | Avg. local train loss : 4.560558859258891, train acc : 0.8322472222222221
INFO flwr 2023-08-16 11:35:16,975 | server.py:116 | fit progress: (21, 1.0404713439941407, {'server_test_acc': 0.7303}, 1757.4029942339985)
INFO flwr 2023-08-16 11:35:16,975 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-16 11:35:21,963 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2392331)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2392329)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:36:09,646 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-16 11:36:09,931 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2392331)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2392329)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2392337)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2392340)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2392338)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2392339)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2392336)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2392335)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2392340)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2392338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392337)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392339)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2392335)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392336)[0m malloc_consolidate(): invalid chunk size
E0816 11:36:12.136377014 2440922 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:36:38,808 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:36:38,808 | fed_df.py:547 | Average fusion training loss : 0.0022616222528740763, val accuracy : 0.71788, best val accuracy : 0.7256
INFO flwr 2023-08-16 11:36:38,810 | common.py:35 | Avg. local train loss : 4.690935015305876, train acc : 0.8207138888888889
INFO flwr 2023-08-16 11:36:41,313 | server.py:116 | fit progress: (22, 1.039242330932617, {'server_test_acc': 0.723}, 1841.7406976610073)
INFO flwr 2023-08-16 11:36:41,313 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-16 11:36:46,339 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:37:33,515 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2466255)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2466260)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:37:33,804 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2466255)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2466258)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2466262)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2466265)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2466260)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2466263)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2466264)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2466266)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2466258)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2466265)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2466262)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2466266)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2466264)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2466263)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:38:02,441 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:38:02,441 | fed_df.py:547 | Average fusion training loss : 0.0027617189781740307, val accuracy : 0.70148, best val accuracy : 0.7178
INFO flwr 2023-08-16 11:38:02,443 | common.py:35 | Avg. local train loss : 4.67102452032268, train acc : 0.8238944444444445
INFO flwr 2023-08-16 11:38:04,925 | server.py:116 | fit progress: (23, 1.058371743774414, {'server_test_acc': 0.7143}, 1925.353108220006)
INFO flwr 2023-08-16 11:38:04,926 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-16 11:38:09,922 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2540040)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540043)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:38:57,234 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2540046)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:38:57,523 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2540040)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2540043)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2540046)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2540048)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2540047)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2540051)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2540050)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2540049)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2540050)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540051)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540047)[0m malloc_consolidate(): invalid chunk size
E0816 11:38:58.374257350 2441392 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2540049)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540048)[0m double free or corruption (fasttop)
E0816 11:39:12.259102998 2587865 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:39:26,288 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:39:26,288 | fed_df.py:547 | Average fusion training loss : 0.002878646361641586, val accuracy : 0.7288399999999999, best val accuracy : 0.7346
INFO flwr 2023-08-16 11:39:26,290 | common.py:35 | Avg. local train loss : 4.719146249443292, train acc : 0.8181777777777778
INFO flwr 2023-08-16 11:39:28,793 | server.py:116 | fit progress: (24, 1.0111509582519531, {'server_test_acc': 0.7358}, 2009.2202811550233)
INFO flwr 2023-08-16 11:39:28,793 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-16 11:39:33,814 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2613887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2613886)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:40:21,465 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2613889)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:40:21,683 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=2613894)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:40:21,809 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2613887)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2613886)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2613892)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2613889)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2613894)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2613893)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2613896)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2613895)[0m Fitting Client 0
E0816 11:40:22.188243128 2660791 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2613892)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2613895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2613896)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2613893)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:40:50,426 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:40:50,426 | fed_df.py:547 | Average fusion training loss : 0.012910773186013103, val accuracy : 0.6963999999999999, best val accuracy : 0.7132
INFO flwr 2023-08-16 11:40:50,428 | common.py:35 | Avg. local train loss : 4.714715063944459, train acc : 0.8170638888888889
INFO flwr 2023-08-16 11:40:52,916 | server.py:116 | fit progress: (25, 1.1292988708496094, {'server_test_acc': 0.7112}, 2093.3438147100096)
INFO flwr 2023-08-16 11:40:52,916 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-16 11:40:57,982 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2687888)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2687894)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:41:45,206 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2687892)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:41:45,495 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2687888)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2687892)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2687893)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2687894)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2687895)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2687898)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2687897)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2687896)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2687897)[0m malloc_consolidate(): invalid chunk size
E0816 11:41:46.150726082 2661154 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2687893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2687895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2687896)[0m malloc_consolidate(): invalid chunk size
E0816 11:41:46.703801297 2735318 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2687898)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:42:14,245 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:42:14,246 | fed_df.py:547 | Average fusion training loss : 0.0029793106596916912, val accuracy : 0.7231599999999999, best val accuracy : 0.7314
INFO flwr 2023-08-16 11:42:14,248 | common.py:35 | Avg. local train loss : 4.544108948111535, train acc : 0.8325888888888888
INFO flwr 2023-08-16 11:42:16,712 | server.py:116 | fit progress: (26, 1.1003214324951172, {'server_test_acc': 0.7272}, 2177.1397560580226)
INFO flwr 2023-08-16 11:42:16,712 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-16 11:42:21,763 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2761538)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:43:08,864 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-16 11:43:09,151 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2761538)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2761540)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2761543)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2761545)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2761547)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2761546)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2761548)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2761544)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2761547)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2761545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2761548)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2761540)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2761544)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2761546)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2761543)[0m double free or corruption (fasttop)
E0816 11:43:11.218512361 2816243 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:43:38,470 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:43:38,470 | fed_df.py:547 | Average fusion training loss : 0.0022626348612830045, val accuracy : 0.73512, best val accuracy : 0.7384
INFO flwr 2023-08-16 11:43:38,473 | common.py:35 | Avg. local train loss : 4.575116623938084, train acc : 0.8330361111111111
INFO flwr 2023-08-16 11:43:40,991 | server.py:116 | fit progress: (27, 1.0319334747314453, {'server_test_acc': 0.732}, 2261.418847599998)
INFO flwr 2023-08-16 11:43:40,991 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-16 11:43:46,024 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2854744)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:44:33,372 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-16 11:44:33,662 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2854750)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2854744)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2854745)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2854822)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2854827)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2854749)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2854828)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2854826)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2854750)[0m malloc_consolidate(): invalid chunk size
E0816 11:44:34.115206354 2816603 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2854827)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2854745)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2854828)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2854749)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2854822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2854826)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:45:07,411 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:45:07,412 | fed_df.py:547 | Average fusion training loss : 0.002217278014868498, val accuracy : 0.7250400000000001, best val accuracy : 0.7304
INFO flwr 2023-08-16 11:45:07,414 | common.py:35 | Avg. local train loss : 4.549383467808366, train acc : 0.8349916666666667
INFO flwr 2023-08-16 11:45:09,892 | server.py:116 | fit progress: (28, 1.0196489196777343, {'server_test_acc': 0.7246}, 2350.319963757007)
INFO flwr 2023-08-16 11:45:09,892 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-16 11:45:14,870 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2934090)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2934093)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:46:01,739 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-16 11:46:02,028 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2934090)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2934093)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2934096)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2934097)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2934095)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2934098)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2934094)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2934099)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2934097)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2934098)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2934096)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2934094)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2934099)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2934095)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:46:30,709 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:46:30,709 | fed_df.py:547 | Average fusion training loss : 0.0024143999312072994, val accuracy : 0.7266, best val accuracy : 0.7354
INFO flwr 2023-08-16 11:46:30,711 | common.py:35 | Avg. local train loss : 4.543240824341774, train acc : 0.8346416666666666
INFO flwr 2023-08-16 11:46:33,168 | server.py:116 | fit progress: (29, 0.9656720275878906, {'server_test_acc': 0.7357}, 2433.5961904660217)
INFO flwr 2023-08-16 11:46:33,169 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-16 11:46:38,174 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3007943)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:47:25,393 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3007946)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:47:25,613 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-16 11:47:25,738 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3007943)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3007945)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3007946)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3007950)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3007949)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3007947)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3007951)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3007948)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3007945)[0m malloc_consolidate(): invalid chunk size
E0816 11:47:26.170599607 2984537 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3007949)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3007948)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3007950)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3007947)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3007951)[0m malloc_consolidate(): invalid chunk size
E0816 11:47:27.640947257 3056228 chttp2_transport.cc:1079]             ipv4:145.136.62.38:52918: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:47:54,491 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:47:54,491 | fed_df.py:547 | Average fusion training loss : 0.01150299471616745, val accuracy : 0.73232, best val accuracy : 0.7462
INFO flwr 2023-08-16 11:47:54,493 | common.py:35 | Avg. local train loss : 4.534690834954381, train acc : 0.8352833333333334
INFO flwr 2023-08-16 11:47:56,964 | server.py:116 | fit progress: (30, 1.0696354553222656, {'server_test_acc': 0.7394}, 2517.3920876870106)
INFO flwr 2023-08-16 11:47:56,965 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-16 11:47:56,965 | server.py:144 | FL finished in 2517.3924527670024
INFO flwr 2023-08-16 11:47:56,965 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-16 11:47:56,966 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-16 11:47:56,966 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.533942950439453), (2, 1.4111561645507813), (3, 1.3397473693847657), (4, 1.2401222778320313), (5, 1.113608056640625), (6, 1.1036437774658203), (7, 1.1275882415771485), (8, 1.0900843566894531), (9, 1.088238851928711), (10, 1.087343341064453), (11, 1.0945976745605468), (12, 1.0598533477783203), (13, 1.0433772583007812), (14, 1.0488144653320313), (15, 1.0362488067626954), (16, 1.0337856475830078), (17, 0.9944493774414063), (18, 1.0262483459472656), (19, 0.9960323211669921), (20, 1.063532147216797), (21, 1.0404713439941407), (22, 1.039242330932617), (23, 1.058371743774414), (24, 1.0111509582519531), (25, 1.1292988708496094), (26, 1.1003214324951172), (27, 1.0319334747314453), (28, 1.0196489196777343), (29, 0.9656720275878906), (30, 1.0696354553222656)]
INFO flwr 2023-08-16 11:47:56,966 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4544), (2, 0.554), (3, 0.5964), (4, 0.6177), (5, 0.6511), (6, 0.6676), (7, 0.6597), (8, 0.6762), (9, 0.672), (10, 0.6859), (11, 0.6861), (12, 0.6961), (13, 0.7074), (14, 0.6949), (15, 0.7072), (16, 0.713), (17, 0.7172), (18, 0.7073), (19, 0.7207), (20, 0.7266), (21, 0.7303), (22, 0.723), (23, 0.7143), (24, 0.7358), (25, 0.7112), (26, 0.7272), (27, 0.732), (28, 0.7246), (29, 0.7357), (30, 0.7394)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn38: task 0: Aborted
srun: Terminating StepId=3358515.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3358515
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:44:25
CPU Efficiency: 13.41% of 12:58:48 core-walltime
Job Wall-clock time: 00:43:16
Memory Utilized: 62.85 GB
Memory Efficiency: 52.37% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
