-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar100
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3425362/1692490438_493114528', seed=84, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3425362/1692490438_493114528/single_img_crops/crops
50000 took 0.59min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 02:14:50,828 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 02:14:50,829 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3425362/1692490438_493114528/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3425362/1692490438_493114528/cifar-100-python.tar.gz to /scratch-local/sunnys.3425362/1692490438_493114528
Generating unified cifar100 dataset
Class histogram for 0-th partition (alpha=1.0, 100 classes): [ 29  16  30 102   3  22  45   3   3   8   0  48  24  15   6   3  16  24
   7  31  42  37  15  10  71  21   7  12  12   3  53  26  71  22  34  53
  10  40  24  25  13  56  78   3  23  47  18  99   1  53  40   6  35  30
  43  49   0   7  17  14  26  23   3  21  17  26   2  63  26  11   0  13
   0  31   1  18  34  50  12   8   4   3  10  45  22  11   0  12 105  62
  26  26  24  22  30   1  18  27  12   0]
INFO flwr 2023-08-20 02:15:13,532 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 02:15:16,377	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-20 02:15:17,405 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'node:145.136.62.13': 1.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'memory': 103079215104.0}
INFO flwr 2023-08-20 02:15:17,405 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 02:15:17,405 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 02:15:17,405 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 02:15:27,778 | server.py:91 | initial parameters (loss, other metrics): 4.651723132324219, {'server_test_acc': 0.0095}
INFO flwr 2023-08-20 02:15:27,778 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 02:15:33,941 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:16:09,061 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-20 02:16:09,176 | fed_df.py:365 | Warm start at round 1
[2m[36m(launch_and_fit pid=1583130)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:16:09,267 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1583129)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1583127)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1583124)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1583128)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1583126)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1583131)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1583130)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1583125)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1583131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1583128)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1583126)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1583127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1583125)[0m malloc_consolidate(): invalid chunk size
E0820 02:16:11.175050422 1574917 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=1583124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1583129)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:16:51,927 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:16:51,927 | fed_df.py:547 | Average fusion training loss : 0.373249125123024, val accuracy : 0.06808, best val accuracy : 0.075
INFO flwr 2023-08-20 02:16:51,928 | common.py:35 | Avg. local train loss : 20.94915116429329, train acc : 0.14434444444444444
INFO flwr 2023-08-20 02:16:54,436 | server.py:116 | fit progress: (1, 4.488532287597656, {'server_test_acc': 0.0775}, 86.65741864033043)
INFO flwr 2023-08-20 02:16:54,436 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 02:17:00,532 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1649999)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:17:32,490 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-20 02:17:32,636 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1649997)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1649998)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1650001)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1650003)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1650004)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1650000)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1649999)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1650002)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1650004)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1650001)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1650000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1649997)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1650003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1649998)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1650002)[0m double free or corruption (fasttop)
E0820 02:17:37.399170613 1609962 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-20 02:18:17,709 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:18:17,709 | fed_df.py:547 | Average fusion training loss : 0.3749968914985657, val accuracy : 0.0816, best val accuracy : 0.092
INFO flwr 2023-08-20 02:18:17,711 | common.py:35 | Avg. local train loss : 20.318213170766832, train acc : 0.18675
INFO flwr 2023-08-20 02:18:20,329 | server.py:116 | fit progress: (2, 4.501061499023438, {'server_test_acc': 0.0939}, 172.55100526520982)
INFO flwr 2023-08-20 02:18:20,330 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 02:18:26,594 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1716524)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:18:58,484 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-20 02:18:58,629 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1716528)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1716527)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1716524)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1716523)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1716529)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1716530)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1716531)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1716526)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1716527)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1716530)[0m double free or corruption (fasttop)
E0820 02:18:59.745510624 1742250 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=1716523)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1716531)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1716529)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1716526)[0m malloc_consolidate(): invalid chunk size
E0820 02:19:00.717457519 1742969 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-20 02:19:43,892 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:19:43,892 | fed_df.py:547 | Average fusion training loss : 0.42007192635536195, val accuracy : 0.08424, best val accuracy : 0.0884
INFO flwr 2023-08-20 02:19:43,894 | common.py:35 | Avg. local train loss : 20.247871112823486, train acc : 0.1913888888888889
INFO flwr 2023-08-20 02:19:46,527 | server.py:116 | fit progress: (3, 4.585840405273437, {'server_test_acc': 0.0884}, 258.74850838724524)
INFO flwr 2023-08-20 02:19:46,527 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 02:19:52,786 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:20:24,501 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-20 02:20:24,648 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1783340)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1783339)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1783338)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1783342)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1783344)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1783345)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1783341)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1783343)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1783345)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1783339)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1783343)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1783344)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1783338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1783341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1783340)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1783342)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:21:10,424 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:21:10,425 | fed_df.py:547 | Average fusion training loss : 0.5007285723686218, val accuracy : 0.08216000000000001, best val accuracy : 0.0886
INFO flwr 2023-08-20 02:21:10,426 | common.py:35 | Avg. local train loss : 20.201037880778312, train acc : 0.1947333333333333
INFO flwr 2023-08-20 02:21:13,138 | server.py:116 | fit progress: (4, 4.582349938964843, {'server_test_acc': 0.0827}, 345.36020647594705)
INFO flwr 2023-08-20 02:21:13,139 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 02:21:19,330 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1849772)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:21:50,864 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-20 02:21:50,979 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-20 02:21:51,068 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1849768)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1849766)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1849772)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1849767)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1849769)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1849770)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1849773)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1849771)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1849768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1849766)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1849773)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1849767)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1849771)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1849770)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1849769)[0m malloc_consolidate(): invalid chunk size
E0820 02:21:53.598548023 1743238 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-20 02:22:36,995 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:22:36,995 | fed_df.py:547 | Average fusion training loss : 0.4745649449825287, val accuracy : 0.09260000000000002, best val accuracy : 0.0956
INFO flwr 2023-08-20 02:22:36,996 | common.py:35 | Avg. local train loss : 20.120068460702896, train acc : 0.20552222222222225
INFO flwr 2023-08-20 02:22:39,639 | server.py:116 | fit progress: (5, 4.531572412109375, {'server_test_acc': 0.0962}, 431.8604579651728)
INFO flwr 2023-08-20 02:22:39,639 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 02:22:45,908 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1916359)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-20 02:23:17,864 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1916355)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:23:18,013 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1916355)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1916359)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1916364)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1916357)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1916365)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1916363)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1916362)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1916366)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1916357)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1916365)[0m malloc_consolidate(): invalid chunk size
E0820 02:23:18.754743429 1876900 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=1916364)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1916363)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1916362)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1916366)[0m double free or corruption (fasttop)
E0820 02:23:20.227032544 1941782 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-20 02:24:04,654 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:24:04,655 | fed_df.py:547 | Average fusion training loss : 0.32992215859889984, val accuracy : 0.08619999999999998, best val accuracy : 0.0908
INFO flwr 2023-08-20 02:24:04,656 | common.py:35 | Avg. local train loss : 19.856069073081017, train acc : 0.22701666666666664
INFO flwr 2023-08-20 02:24:07,308 | server.py:116 | fit progress: (6, 4.4576645263671875, {'server_test_acc': 0.0935}, 519.5298977261409)
INFO flwr 2023-08-20 02:24:07,308 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 02:24:13,712 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:24:45,222 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-20 02:24:45,378 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1983036)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1983032)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1983035)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1983038)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1983039)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1983040)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1983037)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1983034)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1983039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1983032)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1983038)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1983040)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1983036)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1983037)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1983035)[0m corrupted size vs. prev_size in fastbins
E0820 02:24:47.473758231 1943041 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1983034)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:25:31,475 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:25:31,475 | fed_df.py:547 | Average fusion training loss : 0.20423125451803206, val accuracy : 0.10507999999999999, best val accuracy : 0.1124
INFO flwr 2023-08-20 02:25:31,477 | common.py:35 | Avg. local train loss : 19.985959321260456, train acc : 0.21857222222222222
INFO flwr 2023-08-20 02:25:34,125 | server.py:116 | fit progress: (7, 4.374697106933594, {'server_test_acc': 0.1066}, 606.347114583943)
INFO flwr 2023-08-20 02:25:34,126 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 02:25:40,487 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:26:12,554 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-20 02:26:12,711 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2049307)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2049315)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2049311)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2049314)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2049310)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2049312)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2049316)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2049313)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2049311)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049310)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2049316)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049313)[0m double free or corruption (fasttop)
E0820 02:26:13.681029000 2009602 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=2049307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2049314)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2049315)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2049312)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:26:58,795 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:26:58,795 | fed_df.py:547 | Average fusion training loss : 0.12603678515553474, val accuracy : 0.10636000000000001, best val accuracy : 0.1098
INFO flwr 2023-08-20 02:26:58,796 | common.py:35 | Avg. local train loss : 19.891961318254474, train acc : 0.23197777777777778
INFO flwr 2023-08-20 02:27:01,474 | server.py:116 | fit progress: (8, 4.403359069824218, {'server_test_acc': 0.1151}, 693.6957539552823)
INFO flwr 2023-08-20 02:27:01,474 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 02:27:07,852 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2116165)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:27:39,441 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-20 02:27:39,597 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2116165)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2116169)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2116170)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2116171)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2116172)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2116173)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2116174)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2116175)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2116172)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116173)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116169)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2116174)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116171)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2116175)[0m malloc_consolidate(): invalid chunk size
E0820 02:27:43.162712263 2075272 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-20 02:28:26,052 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:28:26,053 | fed_df.py:547 | Average fusion training loss : 0.14044070875644685, val accuracy : 0.11708, best val accuracy : 0.119
INFO flwr 2023-08-20 02:28:26,054 | common.py:35 | Avg. local train loss : 19.84454643726349, train acc : 0.2335111111111111
INFO flwr 2023-08-20 02:28:28,722 | server.py:116 | fit progress: (9, 4.389146057128906, {'server_test_acc': 0.1227}, 780.9433608530089)
INFO flwr 2023-08-20 02:28:28,722 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 02:28:35,201 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2182569)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:29:07,250 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-20 02:29:07,367 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-20 02:29:07,465 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2182569)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2182576)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2182575)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2182574)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2182570)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2182573)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2182568)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2182572)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2182568)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2182570)[0m malloc_consolidate(): invalid chunk size
E0820 02:29:08.248735670 2143707 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=2182575)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2182573)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2182576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2182574)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2182572)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:29:53,876 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:29:53,876 | fed_df.py:547 | Average fusion training loss : 0.12409588906168938, val accuracy : 0.12592, best val accuracy : 0.1278
INFO flwr 2023-08-20 02:29:53,878 | common.py:35 | Avg. local train loss : 19.856520321965217, train acc : 0.23725555555555555
INFO flwr 2023-08-20 02:29:56,553 | server.py:116 | fit progress: (10, 4.3288975463867185, {'server_test_acc': 0.1292}, 868.7746792603284)
INFO flwr 2023-08-20 02:29:56,553 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 02:30:02,984 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2249409)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:30:34,957 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-20 02:30:35,114 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2249409)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2249408)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2249413)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2249406)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2249407)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2249410)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2249411)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2249412)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2249411)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2249406)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2249408)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2249413)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2249412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2249410)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2249407)[0m malloc_consolidate(): invalid chunk size
E0820 02:30:38.646749849 2282322 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-20 02:31:22,690 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:31:22,690 | fed_df.py:547 | Average fusion training loss : 0.05763137447834015, val accuracy : 0.11936, best val accuracy : 0.1284
INFO flwr 2023-08-20 02:31:22,692 | common.py:35 | Avg. local train loss : 19.8739875048399, train acc : 0.23332777777777777
INFO flwr 2023-08-20 02:31:25,389 | server.py:116 | fit progress: (11, 4.303953833007813, {'server_test_acc': 0.1319}, 957.6104197981767)
INFO flwr 2023-08-20 02:31:25,389 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 02:31:32,042 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2340429)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:32:03,617 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 02:32:03,772 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2340430)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2340429)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2340393)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2340428)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2340441)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2340440)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2340438)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2340439)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2340430)[0m malloc_consolidate(): invalid chunk size
E0820 02:32:04.168797905 2366058 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=2340393)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2340438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2340439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2340428)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2340441)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2340440)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:32:50,296 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:32:50,297 | fed_df.py:547 | Average fusion training loss : 0.05673767577111721, val accuracy : 0.13504, best val accuracy : 0.1386
INFO flwr 2023-08-20 02:32:50,298 | common.py:35 | Avg. local train loss : 19.751857087016106, train acc : 0.2470166666666667
INFO flwr 2023-08-20 02:32:52,964 | server.py:116 | fit progress: (12, 4.245827648925781, {'server_test_acc': 0.1421}, 1045.1860485160723)
INFO flwr 2023-08-20 02:32:52,965 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 02:32:59,513 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2407516)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:33:30,837 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-20 02:33:30,997 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2407516)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2407518)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2407522)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2407514)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2407517)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2407520)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2407521)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2407519)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2407521)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2407519)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2407520)[0m malloc_consolidate(): invalid chunk size
E0820 02:33:31.977330089 2366159 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=2407514)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2407518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2407517)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2407522)[0m malloc_consolidate(): invalid chunk size
E0820 02:33:33.130663258 2433069 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-20 02:34:17,462 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:34:17,463 | fed_df.py:547 | Average fusion training loss : 0.06030719912052154, val accuracy : 0.1452, best val accuracy : 0.148
INFO flwr 2023-08-20 02:34:17,464 | common.py:35 | Avg. local train loss : 19.549134278297423, train acc : 0.2642055555555555
INFO flwr 2023-08-20 02:34:20,143 | server.py:116 | fit progress: (13, 4.272707666015625, {'server_test_acc': 0.153}, 1132.3650458953343)
INFO flwr 2023-08-20 02:34:20,144 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 02:34:26,645 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:34:58,124 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-20 02:34:58,289 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2473940)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2473943)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2473944)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2473945)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2473946)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2473947)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2473942)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2473948)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2473946)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2473947)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2473942)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2473940)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2473944)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2473945)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2473943)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2473948)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:35:45,008 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:35:45,009 | fed_df.py:547 | Average fusion training loss : 0.05985936076939106, val accuracy : 0.13540000000000002, best val accuracy : 0.142
INFO flwr 2023-08-20 02:35:45,011 | common.py:35 | Avg. local train loss : 19.61794287264347, train acc : 0.26110555555555554
INFO flwr 2023-08-20 02:35:47,705 | server.py:116 | fit progress: (14, 4.2546310791015625, {'server_test_acc': 0.1514}, 1219.9270705631934)
INFO flwr 2023-08-20 02:35:47,706 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 02:35:54,235 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2540728)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:36:25,844 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-20 02:36:25,959 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 02:36:26,057 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2540722)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2540728)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2540727)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2540731)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2540729)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2540730)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2540724)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2540726)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2540722)[0m malloc_consolidate(): invalid chunk size
E0820 02:36:26.461816479 2433993 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=2540729)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540731)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540730)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540727)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540724)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2540726)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:37:12,510 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:37:12,511 | fed_df.py:547 | Average fusion training loss : 0.05483070936799049, val accuracy : 0.13756, best val accuracy : 0.14
INFO flwr 2023-08-20 02:37:12,512 | common.py:35 | Avg. local train loss : 19.679687583446505, train acc : 0.2558888888888889
INFO flwr 2023-08-20 02:37:15,193 | server.py:116 | fit progress: (15, 4.241772778320312, {'server_test_acc': 0.1509}, 1307.4149173130281)
INFO flwr 2023-08-20 02:37:15,194 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 02:37:21,710 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2607119)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:37:53,250 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 02:37:53,412 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2607119)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2607116)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2607118)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2607117)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2607121)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2607120)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2607123)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2607122)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2607117)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2607121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2607118)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2607122)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2607123)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2607120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2607116)[0m malloc_consolidate(): invalid chunk size
E0820 02:37:56.881226454 2633771 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:38:40,102 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:38:40,102 | fed_df.py:547 | Average fusion training loss : 0.029871315505355597, val accuracy : 0.14708000000000002, best val accuracy : 0.1508
INFO flwr 2023-08-20 02:38:40,104 | common.py:35 | Avg. local train loss : 19.417503231763842, train acc : 0.28287222222222225
INFO flwr 2023-08-20 02:38:42,805 | server.py:116 | fit progress: (16, 4.214298181152344, {'server_test_acc': 0.1526}, 1395.0265315640718)
INFO flwr 2023-08-20 02:38:42,805 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 02:38:49,366 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:39:21,055 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2673901)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:39:21,215 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2673893)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2673892)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2673899)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2673897)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2673898)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2673901)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2673902)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2673900)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2673902)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2673893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2673899)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2673897)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2673892)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2673898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2673900)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:40:13,194 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:40:13,195 | fed_df.py:547 | Average fusion training loss : 0.0447366306707263, val accuracy : 0.16144, best val accuracy : 0.1662
INFO flwr 2023-08-20 02:40:13,196 | common.py:35 | Avg. local train loss : 19.52934477925301, train acc : 0.2740166666666667
INFO flwr 2023-08-20 02:40:15,904 | server.py:116 | fit progress: (17, 4.238673132324219, {'server_test_acc': 0.1661}, 1488.1261309422553)
INFO flwr 2023-08-20 02:40:15,905 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 02:40:22,490 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2740388)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:40:54,297 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 02:40:54,457 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2740388)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2740390)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2740394)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2740395)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2740391)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2740393)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2740387)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2740392)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2740395)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2740394)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2740387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2740393)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2740392)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2740390)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2740391)[0m malloc_consolidate(): invalid chunk size
E0820 02:40:57.007630710 2767132 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 02:41:19.499314970 2767670 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:41:41,282 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:41:41,283 | fed_df.py:547 | Average fusion training loss : 0.047245712459087374, val accuracy : 0.16143999999999997, best val accuracy : 0.167
INFO flwr 2023-08-20 02:41:41,285 | common.py:35 | Avg. local train loss : 19.447585821151733, train acc : 0.28007777777777776
INFO flwr 2023-08-20 02:41:43,989 | server.py:116 | fit progress: (18, 4.203653186035156, {'server_test_acc': 0.1671}, 1576.2110110013746)
INFO flwr 2023-08-20 02:41:43,990 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 02:41:50,767 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:42:22,513 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 02:42:22,684 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2807157)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2807162)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2807160)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2807161)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2807164)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2807159)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2807158)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2807163)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2807158)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2807157)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2807163)[0m malloc_consolidate(): invalid chunk size
E0820 02:42:23.786977611 2832456 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2807161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2807159)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2807162)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2807164)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2807160)[0m malloc_consolidate(): invalid chunk size
E0820 02:42:24.992675415 2833645 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:43:09,192 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:43:09,193 | fed_df.py:547 | Average fusion training loss : 0.0104873880520463, val accuracy : 0.17072, best val accuracy : 0.175
INFO flwr 2023-08-20 02:43:09,194 | common.py:35 | Avg. local train loss : 19.532190784811974, train acc : 0.27621666666666667
INFO flwr 2023-08-20 02:43:11,993 | server.py:116 | fit progress: (19, 4.129244836425781, {'server_test_acc': 0.1759}, 1664.214995115064)
INFO flwr 2023-08-20 02:43:11,994 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 02:43:18,657 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:43:50,388 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 02:43:50,507 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-20 02:43:50,605 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2873615)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2873618)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2873620)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2873617)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2873619)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2873621)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2873622)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2873623)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2873620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2873615)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2873618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2873617)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2873622)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2873621)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2873623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2873619)[0m double free or corruption (fasttop)
E0820 02:43:52.730590889 2833847 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:44:37,206 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:44:37,207 | fed_df.py:547 | Average fusion training loss : 0.013039638129994273, val accuracy : 0.17508, best val accuracy : 0.1776
INFO flwr 2023-08-20 02:44:37,208 | common.py:35 | Avg. local train loss : 19.446742218732837, train acc : 0.28852222222222224
INFO flwr 2023-08-20 02:44:39,884 | server.py:116 | fit progress: (20, 4.147450537109375, {'server_test_acc': 0.1873}, 1752.1061264472082)
INFO flwr 2023-08-20 02:44:39,885 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 02:44:46,590 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:45:18,290 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 02:45:18,444 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2940448)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2940446)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2940453)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2940454)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2940455)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2940450)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2940452)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2940451)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2940446)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2940448)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2940452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2940454)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2940455)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2940451)[0m malloc_consolidate(): invalid chunk size
E0820 02:45:20.375860242 2900419 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2940450)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:46:05,305 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:46:05,306 | fed_df.py:547 | Average fusion training loss : 0.006030550580238924, val accuracy : 0.16956000000000002, best val accuracy : 0.171
INFO flwr 2023-08-20 02:46:05,307 | common.py:35 | Avg. local train loss : 19.28739972710609, train acc : 0.3036333333333333
INFO flwr 2023-08-20 02:46:08,013 | server.py:116 | fit progress: (21, 4.14317421875, {'server_test_acc': 0.1819}, 1840.2349573881365)
INFO flwr 2023-08-20 02:46:08,014 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 02:46:14,879 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3011591)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:46:46,990 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-20 02:46:47,152 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3011591)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3011587)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3011582)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3011589)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3011581)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3011590)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3011584)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3011588)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3011590)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3011582)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3011584)[0m malloc_consolidate(): invalid chunk size
E0820 02:46:48.256490557 3048146 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3011589)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3011581)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3011588)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3011587)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:47:34,456 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:47:34,456 | fed_df.py:547 | Average fusion training loss : 0.008572843160480261, val accuracy : 0.1906, best val accuracy : 0.1952
INFO flwr 2023-08-20 02:47:34,458 | common.py:35 | Avg. local train loss : 19.156012377142904, train acc : 0.31759999999999994
INFO flwr 2023-08-20 02:47:37,118 | server.py:116 | fit progress: (22, 4.093550390625, {'server_test_acc': 0.2026}, 1929.3396594133228)
INFO flwr 2023-08-20 02:47:37,118 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 02:47:43,990 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:48:15,213 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-20 02:48:15,378 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3098597)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3098616)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3098602)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3098620)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3098622)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3098621)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3098601)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3098623)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3098597)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3098602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3098601)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3098620)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3098622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3098621)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3098623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3098616)[0m malloc_consolidate(): invalid chunk size
E0820 02:48:19.036042248 3048683 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:49:02,255 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:49:02,255 | fed_df.py:547 | Average fusion training loss : 0.006343724541366101, val accuracy : 0.20099999999999998, best val accuracy : 0.2042
INFO flwr 2023-08-20 02:49:02,257 | common.py:35 | Avg. local train loss : 18.970579659938814, train acc : 0.3357722222222222
INFO flwr 2023-08-20 02:49:04,945 | server.py:116 | fit progress: (23, 4.1067358642578125, {'server_test_acc': 0.2017}, 2017.1670790510252)
INFO flwr 2023-08-20 02:49:04,946 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 02:49:11,589 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3165117)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:49:43,360 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-20 02:49:43,521 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3165121)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3165116)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3165119)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3165117)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3165118)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3165120)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3165113)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3165115)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3165116)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3165118)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3165115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3165121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3165119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3165120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3165113)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:50:30,576 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:50:30,576 | fed_df.py:547 | Average fusion training loss : 0.0061850807629525665, val accuracy : 0.20472, best val accuracy : 0.2062
INFO flwr 2023-08-20 02:50:30,578 | common.py:35 | Avg. local train loss : 19.14405960440636, train acc : 0.32383888888888884
INFO flwr 2023-08-20 02:50:33,262 | server.py:116 | fit progress: (24, 4.064919165039062, {'server_test_acc': 0.212}, 2105.483281529043)
INFO flwr 2023-08-20 02:50:33,262 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 02:50:40,139 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3231760)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:51:11,970 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-20 02:51:12,091 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-20 02:51:12,188 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3231762)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3231753)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3231755)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3231759)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3231757)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3231760)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3231761)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3231758)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3231762)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3231753)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3231757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3231758)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3231755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3231761)[0m malloc_consolidate(): invalid chunk size
E0820 02:51:13.560004085 3126459 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3231759)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:51:59,257 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:51:59,257 | fed_df.py:547 | Average fusion training loss : 0.006839881857391447, val accuracy : 0.20376, best val accuracy : 0.2054
INFO flwr 2023-08-20 02:51:59,259 | common.py:35 | Avg. local train loss : 18.963955274224283, train acc : 0.3344277777777778
INFO flwr 2023-08-20 02:52:01,952 | server.py:116 | fit progress: (25, 4.098169519042969, {'server_test_acc': 0.2119}, 2194.173624102026)
INFO flwr 2023-08-20 02:52:01,952 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 02:52:08,668 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:52:40,220 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-20 02:52:40,380 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3298429)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3298431)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3298428)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3298430)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3298434)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3298433)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3298432)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3298427)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3298430)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298429)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298431)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3298428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298427)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298432)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:53:27,573 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:53:27,573 | fed_df.py:547 | Average fusion training loss : 0.002373310679104179, val accuracy : 0.21015999999999999, best val accuracy : 0.2118
INFO flwr 2023-08-20 02:53:27,574 | common.py:35 | Avg. local train loss : 19.010401964187622, train acc : 0.33414444444444447
INFO flwr 2023-08-20 02:53:30,307 | server.py:116 | fit progress: (26, 4.101973974609375, {'server_test_acc': 0.221}, 2282.5290092541836)
INFO flwr 2023-08-20 02:53:30,308 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 02:53:36,968 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3364831)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:54:09,030 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 02:54:09,192 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3364826)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3364828)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3364831)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3364830)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3364827)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3364829)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3364825)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3364832)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3364825)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3364826)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3364828)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3364832)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3364830)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3364827)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3364829)[0m malloc_consolidate(): invalid chunk size
E0820 02:54:11.854681365 3257786 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:54:56,619 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:54:56,620 | fed_df.py:547 | Average fusion training loss : 0.001745048074168153, val accuracy : 0.21608, best val accuracy : 0.2186
INFO flwr 2023-08-20 02:54:56,621 | common.py:35 | Avg. local train loss : 18.875658336281777, train acc : 0.3435444444444445
INFO flwr 2023-08-20 02:54:59,333 | server.py:116 | fit progress: (27, 4.057919323730469, {'server_test_acc': 0.2254}, 2371.5543201710097)
INFO flwr 2023-08-20 02:54:59,333 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 02:55:05,982 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3431668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3431672)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:55:37,611 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-20 02:55:37,777 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3431668)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3431675)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3431672)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3431674)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3431671)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3431676)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3431677)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3431673)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3431671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3431676)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3431675)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3431677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3431673)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3431674)[0m double free or corruption (fasttop)
E0820 02:55:39.729308867 3457754 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:56:25,041 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:56:25,041 | fed_df.py:547 | Average fusion training loss : 0.0019139791638590395, val accuracy : 0.21256, best val accuracy : 0.216
INFO flwr 2023-08-20 02:56:25,043 | common.py:35 | Avg. local train loss : 18.83749584555626, train acc : 0.3499611111111111
INFO flwr 2023-08-20 02:56:27,735 | server.py:116 | fit progress: (28, 4.059671447753907, {'server_test_acc': 0.2223}, 2459.9567221081816)
INFO flwr 2023-08-20 02:56:27,735 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-20 02:56:34,400 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:57:06,141 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-20 02:57:06,298 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3498112)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3498113)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3498114)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3498115)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3498117)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3498116)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3498111)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3498107)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3498113)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498117)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498116)[0m double free or corruption (fasttop)
E0820 02:57:07.537111964 3458024 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3498112)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3498114)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3498111)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3498107)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:57:58,332 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:57:58,332 | fed_df.py:547 | Average fusion training loss : 0.0017714345729909838, val accuracy : 0.21812, best val accuracy : 0.222
INFO flwr 2023-08-20 02:57:58,334 | common.py:35 | Avg. local train loss : 18.895480224490164, train acc : 0.34273888888888887
INFO flwr 2023-08-20 02:58:01,017 | server.py:116 | fit progress: (29, 4.046378686523438, {'server_test_acc': 0.2286}, 2553.2385086342692)
INFO flwr 2023-08-20 02:58:01,017 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 02:58:07,563 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:58:39,452 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 02:58:39,569 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 02:58:39,667 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3564884)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3564885)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3564883)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3564886)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3564888)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3564887)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3564890)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3564889)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3564885)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3564890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3564884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3564888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3564889)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3564883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3564886)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3564887)[0m malloc_consolidate(): invalid chunk size
E0820 02:58:42.323948260 3524113 chttp2_transport.cc:1079]             ipv4:145.136.62.13:58560: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:59:27,155 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:59:27,156 | fed_df.py:547 | Average fusion training loss : 0.0020165290324948727, val accuracy : 0.23280000000000003, best val accuracy : 0.236
INFO flwr 2023-08-20 02:59:27,158 | common.py:35 | Avg. local train loss : 18.62687894105911, train acc : 0.3724
INFO flwr 2023-08-20 02:59:29,876 | server.py:116 | fit progress: (30, 4.08044541015625, {'server_test_acc': 0.2383}, 2642.097823418211)
INFO flwr 2023-08-20 02:59:29,876 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 02:59:29,876 | server.py:144 | FL finished in 2642.098180727102
INFO flwr 2023-08-20 02:59:29,877 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 02:59:29,878 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 02:59:29,878 | app.py:204 | app_fit: losses_centralized [(0, 4.651723132324219), (1, 4.488532287597656), (2, 4.501061499023438), (3, 4.585840405273437), (4, 4.582349938964843), (5, 4.531572412109375), (6, 4.4576645263671875), (7, 4.374697106933594), (8, 4.403359069824218), (9, 4.389146057128906), (10, 4.3288975463867185), (11, 4.303953833007813), (12, 4.245827648925781), (13, 4.272707666015625), (14, 4.2546310791015625), (15, 4.241772778320312), (16, 4.214298181152344), (17, 4.238673132324219), (18, 4.203653186035156), (19, 4.129244836425781), (20, 4.147450537109375), (21, 4.14317421875), (22, 4.093550390625), (23, 4.1067358642578125), (24, 4.064919165039062), (25, 4.098169519042969), (26, 4.101973974609375), (27, 4.057919323730469), (28, 4.059671447753907), (29, 4.046378686523438), (30, 4.08044541015625)]
INFO flwr 2023-08-20 02:59:29,878 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0095), (1, 0.0775), (2, 0.0939), (3, 0.0884), (4, 0.0827), (5, 0.0962), (6, 0.0935), (7, 0.1066), (8, 0.1151), (9, 0.1227), (10, 0.1292), (11, 0.1319), (12, 0.1421), (13, 0.153), (14, 0.1514), (15, 0.1509), (16, 0.1526), (17, 0.1661), (18, 0.1671), (19, 0.1759), (20, 0.1873), (21, 0.1819), (22, 0.2026), (23, 0.2017), (24, 0.212), (25, 0.2119), (26, 0.221), (27, 0.2254), (28, 0.2223), (29, 0.2286), (30, 0.2383)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn13: task 0: Aborted
srun: Terminating StepId=3425362.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3425362
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:52:25
CPU Efficiency: 13.08% of 14:19:30 core-walltime
Job Wall-clock time: 00:47:45
Memory Utilized: 48.57 GB
Memory Efficiency: 40.48% of 120.00 GB
