-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:5000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:0.1
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=5000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3429375/1692555656_578708201', seed=84, img_per_thread=277)
will save 5000 patches in /scratch-local/sunnys.3429375/1692555656_578708201/single_img_crops/crops
5000 took 0.09min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 20:22:53,079 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 20:22:53,079 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3429375/1692555656_578708201/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3429375/1692555656_578708201/cifar-10-python.tar.gz to /scratch-local/sunnys.3429375/1692555656_578708201
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=0.1, 10 classes): [ 981 1228    0  289    0    0    1    1    0    0]
INFO flwr 2023-08-20 20:23:08,179 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 20:23:10,833	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-20 20:23:11,929 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'GPU': 1.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'CPU': 18.0, 'node:145.136.62.28': 1.0}
INFO flwr 2023-08-20 20:23:11,929 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 20:23:11,929 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 20:23:11,929 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 20:23:19,649 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-20 20:23:19,649 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 20:23:23,088 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 20:24:11,699 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-20 20:24:11,806 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-20 20:24:11,902 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2445516)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2445529)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2445534)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2445530)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2445535)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2445515)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2445532)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2445531)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2445516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2445531)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445515)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2445534)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445529)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2445530)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2445535)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2445532)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2445532)[0m malloc_consolidate(): invalid chunk size
E0820 20:24:13.984926155 2426663 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-20 20:25:42,680 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:25:42,681 | fed_df.py:547 | Average fusion training loss : 0.012672934029251338, val accuracy : 0.29839999999999994, best val accuracy : 0.3324
INFO flwr 2023-08-20 20:25:42,682 | common.py:35 | Avg. local train loss : 4.957688998803497, train acc : 0.7630750000000001
INFO flwr 2023-08-20 20:25:45,438 | server.py:116 | fit progress: (1, 1.891298211669922, {'server_test_acc': 0.3184}, 145.7885366086848)
INFO flwr 2023-08-20 20:25:45,438 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 20:25:49,071 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2697970)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2697977)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:26:36,858 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-20 20:26:36,964 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-20 20:26:37,061 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2697970)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2697977)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2697973)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2697975)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2697972)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2697976)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2697978)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2697974)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2697973)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2697978)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2697972)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2697974)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2697976)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2697975)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:28:16,611 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:28:16,612 | fed_df.py:547 | Average fusion training loss : 0.03432105739042163, val accuracy : 0.28924, best val accuracy : 0.3078
INFO flwr 2023-08-20 20:28:16,613 | common.py:35 | Avg. local train loss : 4.22254268117249, train acc : 0.8367388888888889
INFO flwr 2023-08-20 20:28:19,202 | server.py:116 | fit progress: (2, 2.093659832763672, {'server_test_acc': 0.2971}, 299.5525825936347)
INFO flwr 2023-08-20 20:28:19,202 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 20:28:22,693 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2954600)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:29:10,524 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-20 20:29:10,633 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-20 20:29:10,726 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2954600)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2954529)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2954604)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2954601)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2954565)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2954602)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2954603)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2954599)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2954604)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2954603)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2954529)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2954599)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2954565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2954602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2954601)[0m malloc_consolidate(): invalid chunk size
E0820 20:29:13.073949084 3045288 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-20 20:30:41,115 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:30:41,115 | fed_df.py:547 | Average fusion training loss : 0.019663638565689326, val accuracy : 0.34647999999999995, best val accuracy : 0.36
INFO flwr 2023-08-20 20:30:41,116 | common.py:35 | Avg. local train loss : 4.254878655448556, train acc : 0.8397333333333333
INFO flwr 2023-08-20 20:30:43,699 | server.py:116 | fit progress: (3, 1.9292242126464845, {'server_test_acc': 0.3452}, 444.0497520407662)
INFO flwr 2023-08-20 20:30:43,700 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 20:30:47,158 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3205882)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:31:34,675 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3205887)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:31:34,784 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-20 20:31:34,878 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3205882)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3205884)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3205886)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3205887)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3205956)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3205958)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3205888)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3205957)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3205884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3205958)[0m malloc_consolidate(): invalid chunk size
E0820 20:31:36.024044271 3293611 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=3205888)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3205886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3205957)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:33:05,236 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:33:05,237 | fed_df.py:547 | Average fusion training loss : 0.015816323652863503, val accuracy : 0.34848, best val accuracy : 0.361
INFO flwr 2023-08-20 20:33:05,238 | common.py:35 | Avg. local train loss : 4.447807798162103, train acc : 0.8178111111111112
INFO flwr 2023-08-20 20:33:07,826 | server.py:116 | fit progress: (4, 1.8588919494628906, {'server_test_acc': 0.3588}, 588.1763361790217)
INFO flwr 2023-08-20 20:33:07,826 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 20:33:11,413 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3456766)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3456769)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:33:59,280 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-20 20:33:59,388 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-20 20:33:59,482 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3456766)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3456769)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3456768)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3456698)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3456767)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3456697)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3456770)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3456696)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3456697)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3456698)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3456767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3456770)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3456768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3456696)[0m malloc_consolidate(): invalid chunk size
E0820 20:34:02.161074614 3294083 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-20 20:35:30,592 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:35:30,592 | fed_df.py:547 | Average fusion training loss : 0.016797421341761945, val accuracy : 0.38962, best val accuracy : 0.3948
INFO flwr 2023-08-20 20:35:30,593 | common.py:35 | Avg. local train loss : 4.05697751827538, train acc : 0.8593472222222223
INFO flwr 2023-08-20 20:35:33,232 | server.py:116 | fit progress: (5, 1.8133299438476562, {'server_test_acc': 0.3922}, 733.5827675177716)
INFO flwr 2023-08-20 20:35:33,233 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 20:35:36,703 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3714738)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3714739)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3714852)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:36:25,038 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-20 20:36:25,146 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-20 20:36:25,242 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3714738)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3714739)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3714852)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3714737)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3714850)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3714853)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3714854)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3714851)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3714850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3714851)[0m double free or corruption (fasttop)
E0820 20:36:26.371724773 3816414 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=3714854)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3714737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3714853)[0m double free or corruption (fasttop)
E0820 20:36:57.439185140 3875857 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-20 20:37:55,882 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:37:55,882 | fed_df.py:547 | Average fusion training loss : 0.015504063377156853, val accuracy : 0.39302, best val accuracy : 0.4012
INFO flwr 2023-08-20 20:37:55,883 | common.py:35 | Avg. local train loss : 3.909428399801254, train acc : 0.8733249999999999
INFO flwr 2023-08-20 20:37:58,473 | server.py:116 | fit progress: (6, 1.8918137756347657, {'server_test_acc': 0.4022}, 878.8233928256668)
INFO flwr 2023-08-20 20:37:58,473 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 20:38:01,913 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3986432)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:38:50,091 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-20 20:38:50,200 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-20 20:38:50,296 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3986432)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3986434)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3986503)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3986506)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3986505)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3986574)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3986576)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3986575)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3986574)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3986575)[0m double free or corruption (fasttop)
E0820 20:38:51.226129740 4073719 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=3986506)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3986434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3986505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3986576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3986503)[0m double free or corruption (fasttop)
E0820 20:39:02.631583820 4074288 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-20 20:40:21,089 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:40:21,089 | fed_df.py:547 | Average fusion training loss : 0.018236129725351928, val accuracy : 0.36842, best val accuracy : 0.38
INFO flwr 2023-08-20 20:40:21,091 | common.py:35 | Avg. local train loss : 4.01820119060576, train acc : 0.8646444444444444
INFO flwr 2023-08-20 20:40:23,714 | server.py:116 | fit progress: (7, 1.832922036743164, {'server_test_acc': 0.3834}, 1024.0642844447866)
INFO flwr 2023-08-20 20:40:23,714 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 20:40:27,140 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=45160)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:41:15,024 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-20 20:41:15,133 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-20 20:41:15,228 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=45088)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=45088)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=45160)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=45139)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=45089)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=45162)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=45125)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=45163)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=45161)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=45163)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=45162)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=45139)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=45161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=45089)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=45125)[0m malloc_consolidate(): invalid chunk size
E0820 20:41:17.223247700 4094001 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-20 20:42:46,138 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:42:46,139 | fed_df.py:547 | Average fusion training loss : 0.014608384359627961, val accuracy : 0.35781999999999997, best val accuracy : 0.3744
INFO flwr 2023-08-20 20:42:46,140 | common.py:35 | Avg. local train loss : 3.7026706822216515, train acc : 0.8949027777777778
INFO flwr 2023-08-20 20:42:48,882 | server.py:116 | fit progress: (8, 1.888625469970703, {'server_test_acc': 0.3682}, 1169.232494649943)
INFO flwr 2023-08-20 20:42:48,882 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 20:42:52,327 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=297330)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=297401)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:43:40,391 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-20 20:43:40,500 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-20 20:43:40,594 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=297330)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=297259)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=297329)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=297401)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=297400)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=297328)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=297399)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=297398)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=297329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297328)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297400)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=297259)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297399)[0m double free or corruption (fasttop)
E0820 20:43:42.828477822  135514 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0820 20:43:53.027775388  404810 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-20 20:45:11,226 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:45:11,227 | fed_df.py:547 | Average fusion training loss : 0.008142799709457905, val accuracy : 0.37382, best val accuracy : 0.394
INFO flwr 2023-08-20 20:45:11,228 | common.py:35 | Avg. local train loss : 3.709756574779749, train acc : 0.8976972222222221
INFO flwr 2023-08-20 20:45:13,844 | server.py:116 | fit progress: (9, 1.8933110443115235, {'server_test_acc': 0.3966}, 1314.1948867258616)
INFO flwr 2023-08-20 20:45:13,845 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 20:45:17,293 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=549453)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=549555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=549558)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:46:05,486 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-20 20:46:05,595 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-20 20:46:05,691 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=549453)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=549455)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=549554)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=549555)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=549559)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=549558)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=549556)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=549557)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=549554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=549556)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=549455)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=549557)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=549559)[0m double free or corruption (fasttop)
E0820 20:46:09.583786262  640179 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-20 20:47:38,022 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:47:38,022 | fed_df.py:547 | Average fusion training loss : 0.005955332418670878, val accuracy : 0.42074, best val accuracy : 0.4354
INFO flwr 2023-08-20 20:47:38,023 | common.py:35 | Avg. local train loss : 3.7385656587779525, train acc : 0.8961888888888889
INFO flwr 2023-08-20 20:47:40,681 | server.py:116 | fit progress: (10, 1.797315286254883, {'server_test_acc': 0.4281}, 1461.0313288508914)
INFO flwr 2023-08-20 20:47:40,681 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 20:47:45,588 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=802525)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=802598)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:48:33,751 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-20 20:48:33,860 | fed_df.py:365 | Warm start at round 11
[2m[36m(launch_and_fit pid=802668)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:48:33,958 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=802525)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=802527)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=802667)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=802599)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=802528)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=802669)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=802668)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=802598)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=802527)[0m double free or corruption (fasttop)
E0820 20:48:34.531082040  643037 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=802528)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=802599)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=802667)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=802669)[0m double free or corruption (fasttop)
E0820 20:49:14.239980633  890334 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-20 20:50:05,015 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:50:05,015 | fed_df.py:547 | Average fusion training loss : 0.006983341645216569, val accuracy : 0.41892000000000007, best val accuracy : 0.4298
INFO flwr 2023-08-20 20:50:05,017 | common.py:35 | Avg. local train loss : 3.74505083039403, train acc : 0.8970027777777778
INFO flwr 2023-08-20 20:50:07,617 | server.py:116 | fit progress: (11, 1.7861522369384766, {'server_test_acc': 0.4316}, 1607.9675647029653)
INFO flwr 2023-08-20 20:50:07,617 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 20:50:11,087 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1054742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1054596)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:50:59,229 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 20:50:59,338 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-20 20:50:59,433 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1054596)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1054667)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1054598)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1054668)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1054740)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1054626)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1054741)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1054742)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1054740)[0m double free or corruption (fasttop)
E0820 20:50:59.842177435 1143128 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1054668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1054741)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1054626)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1054667)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1054598)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 20:52:31,215 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:52:31,216 | fed_df.py:547 | Average fusion training loss : 0.004882777906022966, val accuracy : 0.4311999999999999, best val accuracy : 0.4446
INFO flwr 2023-08-20 20:52:31,217 | common.py:35 | Avg. local train loss : 3.789098127931356, train acc : 0.8916333333333333
INFO flwr 2023-08-20 20:52:33,851 | server.py:116 | fit progress: (12, 1.8484950775146485, {'server_test_acc': 0.4493}, 1754.20184975164)
INFO flwr 2023-08-20 20:52:33,852 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 20:52:37,304 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1334926)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:53:25,151 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1334922)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:53:25,261 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-20 20:53:25,356 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1334926)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1334923)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1334922)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1334927)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1334929)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1334928)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1334925)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1334924)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1334925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1334928)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1334923)[0m malloc_consolidate(): invalid chunk size
E0820 20:53:26.415027514 1143295 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1334927)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1334924)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1334929)[0m malloc_consolidate(): invalid chunk size
E0820 20:54:09.880951223 1484932 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 20:54:56,356 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:54:56,357 | fed_df.py:547 | Average fusion training loss : 0.0031444426098605617, val accuracy : 0.37507999999999997, best val accuracy : 0.3812
INFO flwr 2023-08-20 20:54:56,358 | common.py:35 | Avg. local train loss : 3.6468745041638613, train acc : 0.9098333333333334
INFO flwr 2023-08-20 20:54:58,955 | server.py:116 | fit progress: (13, 1.8750997985839843, {'server_test_acc': 0.382}, 1899.305801210925)
INFO flwr 2023-08-20 20:54:58,956 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 20:55:02,451 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1582849)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1582918)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1582848)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 20:55:50,371 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-20 20:55:50,480 | fed_df.py:365 | Warm start at round 14
[2m[36m(launch_and_fit pid=1582850)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:55:50,577 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1582780)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1582848)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1582850)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1582849)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1582920)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1582921)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1582919)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1582918)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1582919)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1582780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1582921)[0m double free or corruption (fasttop)
E0820 20:55:52.360737493 1670185 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1582920)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:57:21,599 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:57:21,599 | fed_df.py:547 | Average fusion training loss : 0.0026706227564718575, val accuracy : 0.44882, best val accuracy : 0.4584
INFO flwr 2023-08-20 20:57:21,601 | common.py:35 | Avg. local train loss : 3.8599242221564056, train acc : 0.896136111111111
INFO flwr 2023-08-20 20:57:24,205 | server.py:116 | fit progress: (14, 1.8909188385009765, {'server_test_acc': 0.4582}, 2044.55564631382)
INFO flwr 2023-08-20 20:57:24,205 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 20:57:27,685 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1833851)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 20:58:14,987 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-20 20:58:15,098 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 20:58:15,205 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1833851)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1833853)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1833925)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1833924)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1833995)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1833923)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1833993)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1833994)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1833995)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1833924)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1833853)[0m malloc_consolidate(): invalid chunk size
E0820 20:58:16.282337929 1671267 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1833993)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1833923)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1833925)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1833994)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 20:59:47,071 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 20:59:47,071 | fed_df.py:547 | Average fusion training loss : 0.0022551854893099518, val accuracy : 0.45, best val accuracy : 0.4656
INFO flwr 2023-08-20 20:59:47,072 | common.py:35 | Avg. local train loss : 3.821878673136234, train acc : 0.9013944444444446
INFO flwr 2023-08-20 20:59:49,688 | server.py:116 | fit progress: (15, 1.8298649932861328, {'server_test_acc': 0.4565}, 2190.038439887576)
INFO flwr 2023-08-20 20:59:49,688 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 20:59:53,150 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2084859)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:00:41,340 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 21:00:41,449 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-20 21:00:41,543 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2084856)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2084855)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2084857)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2084852)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2084859)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2084860)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2084858)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2084854)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2084857)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2084854)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2084855)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2084852)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2084856)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2084858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2084860)[0m double free or corruption (fasttop)
E0820 21:00:44.338822427 1921161 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:00:44.338898619 1921161 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:02:13,326 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:02:13,327 | fed_df.py:547 | Average fusion training loss : 0.002505539181700442, val accuracy : 0.48818, best val accuracy : 0.4994
INFO flwr 2023-08-20 21:02:13,328 | common.py:35 | Avg. local train loss : 3.7949217662215236, train acc : 0.9085944444444444
INFO flwr 2023-08-20 21:02:15,939 | server.py:116 | fit progress: (16, 1.896278564453125, {'server_test_acc': 0.487}, 2336.289850918576)
INFO flwr 2023-08-20 21:02:15,940 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 21:02:19,419 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2337222)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2337220)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:03:06,869 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 21:03:06,978 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-20 21:03:07,073 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2337220)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2337222)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2337293)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2337294)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2337223)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2337292)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2337363)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2337362)[0m Fitting Client 14
E0820 21:03:07.447486616 2422690 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2337293)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2337292)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2337363)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2337294)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2337223)[0m double free or corruption (fasttop)
E0820 21:03:08.908839484 2425097 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:04:38,965 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:04:38,965 | fed_df.py:547 | Average fusion training loss : 0.0015779389580129646, val accuracy : 0.45430000000000004, best val accuracy : 0.4748
INFO flwr 2023-08-20 21:04:38,966 | common.py:35 | Avg. local train loss : 3.8396637562662366, train acc : 0.9089944444444443
INFO flwr 2023-08-20 21:04:41,549 | server.py:116 | fit progress: (17, 1.8766689697265626, {'server_test_acc': 0.4566}, 2481.8992427317426)
INFO flwr 2023-08-20 21:04:41,549 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 21:04:45,035 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2590734)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:05:32,900 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2590736)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:05:33,010 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-20 21:05:33,104 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2590710)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2590736)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2590734)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2590735)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2590739)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2590740)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2590738)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2590737)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2590710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2590737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2590735)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2590738)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2590739)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2590740)[0m corrupted size vs. prev_size in fastbins
E0820 21:05:35.738831947 2428034 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:07:04,574 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:07:04,575 | fed_df.py:547 | Average fusion training loss : 0.0007656856291578151, val accuracy : 0.49820000000000003, best val accuracy : 0.5146
INFO flwr 2023-08-20 21:07:04,576 | common.py:35 | Avg. local train loss : 4.240116385370493, train acc : 0.9010527777777778
INFO flwr 2023-08-20 21:07:07,216 | server.py:116 | fit progress: (18, 1.9622776184082031, {'server_test_acc': 0.5079}, 2627.5661105397157)
INFO flwr 2023-08-20 21:07:07,216 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 21:07:10,690 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2859704)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2859631)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:07:58,954 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 21:07:59,062 | fed_df.py:365 | Warm start at round 19
[2m[36m(launch_and_fit pid=2859557)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:07:59,159 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2859557)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2859629)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2859631)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2859628)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2859667)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2859627)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2859630)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2859704)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2859629)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2859630)[0m malloc_consolidate(): invalid chunk size
E0820 21:08:00.166043274 2680922 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2859627)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2859628)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2859667)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:09:31,256 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:09:31,256 | fed_df.py:547 | Average fusion training loss : 0.001009493399236817, val accuracy : 0.44162, best val accuracy : 0.4518
INFO flwr 2023-08-20 21:09:31,257 | common.py:35 | Avg. local train loss : 4.130841140449047, train acc : 0.8974555555555556
INFO flwr 2023-08-20 21:09:33,882 | server.py:116 | fit progress: (19, 1.9319413513183594, {'server_test_acc': 0.454}, 2774.2320058769546)
INFO flwr 2023-08-20 21:09:33,882 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 21:09:37,362 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3121749)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:10:25,103 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 21:10:25,212 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-20 21:10:25,307 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3121750)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3121749)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3121752)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3121821)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3121822)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3121714)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3121753)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3121751)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3121753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3121822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3121714)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3121821)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3121751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3121752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3121750)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:11:57,751 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:11:57,751 | fed_df.py:547 | Average fusion training loss : 0.0009667918010964058, val accuracy : 0.45232, best val accuracy : 0.4574
INFO flwr 2023-08-20 21:11:57,752 | common.py:35 | Avg. local train loss : 3.9353629842400553, train acc : 0.9111166666666666
INFO flwr 2023-08-20 21:12:00,371 | server.py:116 | fit progress: (20, 1.961614453125, {'server_test_acc': 0.4526}, 2920.7212929907255)
INFO flwr 2023-08-20 21:12:00,371 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 21:12:03,830 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3375191)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375265)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:12:51,947 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 21:12:52,056 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-20 21:12:52,150 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3375191)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3375196)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3375265)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3375194)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3375195)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3375193)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3375264)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3375266)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3375195)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375193)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375196)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3375264)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3375266)[0m double free or corruption (fasttop)
E0820 21:12:54.655276555 3463862 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:14:23,672 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:14:23,673 | fed_df.py:547 | Average fusion training loss : 0.0007293925925623625, val accuracy : 0.47446, best val accuracy : 0.4888
INFO flwr 2023-08-20 21:14:23,674 | common.py:35 | Avg. local train loss : 4.1286765448749065, train acc : 0.9060666666666667
INFO flwr 2023-08-20 21:14:26,260 | server.py:116 | fit progress: (21, 1.9503027709960938, {'server_test_acc': 0.4787}, 3066.6104408646934)
INFO flwr 2023-08-20 21:14:26,260 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 21:14:29,707 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3627570)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3627547)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:15:17,693 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-20 21:15:17,802 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-20 21:15:17,899 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3627571)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3627570)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3627572)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3627498)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3627501)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3627499)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3627547)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3627527)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3627571)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3627527)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3627499)[0m malloc_consolidate(): invalid chunk size
E0820 21:15:18.845163364 3466176 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3627501)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3627572)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3627498)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:16:48,576 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:16:48,577 | fed_df.py:547 | Average fusion training loss : 0.0008727701618918218, val accuracy : 0.40474000000000004, best val accuracy : 0.4118
INFO flwr 2023-08-20 21:16:48,578 | common.py:35 | Avg. local train loss : 4.251545753329992, train acc : 0.8948583333333332
INFO flwr 2023-08-20 21:16:51,169 | server.py:116 | fit progress: (22, 1.9489025390625, {'server_test_acc': 0.4126}, 3211.519804602023)
INFO flwr 2023-08-20 21:16:51,170 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 21:16:54,681 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3879609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3879440)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:17:42,390 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-20 21:17:42,498 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-20 21:17:42,593 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3879440)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3879438)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3879527)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3879528)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3879529)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3879607)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3879608)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3879609)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3879607)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3879608)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3879529)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3879438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3879528)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3879527)[0m double free or corruption (fasttop)
E0820 21:17:47.360281695 3716217 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:19:13,676 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:19:13,676 | fed_df.py:547 | Average fusion training loss : 0.0009732175639946946, val accuracy : 0.4427, best val accuracy : 0.4524
INFO flwr 2023-08-20 21:19:13,677 | common.py:35 | Avg. local train loss : 4.1500201623886825, train acc : 0.9012777777777777
INFO flwr 2023-08-20 21:19:16,272 | server.py:116 | fit progress: (23, 1.9289696228027344, {'server_test_acc': 0.4482}, 3356.6226380397566)
INFO flwr 2023-08-20 21:19:16,272 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 21:19:19,799 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 21:20:07,423 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-20 21:20:07,532 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-20 21:20:07,628 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4130353)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130424)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4130355)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4130425)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4130353)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4130428)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4130427)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4130426)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4130352)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4130427)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130424)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130425)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130355)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4130352)[0m double free or corruption (fasttop)
E0820 21:20:11.352756352 3973313 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:21:38,582 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:21:38,583 | fed_df.py:547 | Average fusion training loss : 0.0008632773635326885, val accuracy : 0.47152000000000005, best val accuracy : 0.4896
INFO flwr 2023-08-20 21:21:38,584 | common.py:35 | Avg. local train loss : 4.126605997979641, train acc : 0.9045888888888887
INFO flwr 2023-08-20 21:21:41,232 | server.py:116 | fit progress: (24, 1.9287776550292968, {'server_test_acc': 0.4778}, 3501.5820928555913)
INFO flwr 2023-08-20 21:21:41,232 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 21:21:44,723 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=188771)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=188776)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:22:33,208 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-20 21:22:33,316 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=188783)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=188773)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=188775)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:22:33,413 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=188771)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=188773)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=188775)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=188776)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=188787)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=188786)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=188774)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=188783)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=188786)[0m malloc_consolidate(): invalid chunk size
E0820 21:22:34.482419393  280858 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=188787)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=188774)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 21:24:07,050 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:24:07,051 | fed_df.py:547 | Average fusion training loss : 0.0012492230472853408, val accuracy : 0.4508, best val accuracy : 0.457
INFO flwr 2023-08-20 21:24:07,052 | common.py:35 | Avg. local train loss : 3.9131994631141422, train acc : 0.9100472222222222
INFO flwr 2023-08-20 21:24:09,670 | server.py:116 | fit progress: (25, 1.8962083129882812, {'server_test_acc': 0.4582}, 3650.0201756525785)
INFO flwr 2023-08-20 21:24:09,670 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 21:24:13,172 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=470639)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:25:00,512 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-20 21:25:00,621 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-20 21:25:00,717 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=470568)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=470640)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=470639)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=470710)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=470641)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=470712)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=470711)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=470642)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=470710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=470642)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=470640)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=470568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=470712)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=470641)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=470711)[0m malloc_consolidate(): invalid chunk size
E0820 21:25:03.007825358  283260 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:26:36,676 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:26:36,677 | fed_df.py:547 | Average fusion training loss : 0.0008321291859028861, val accuracy : 0.39668000000000003, best val accuracy : 0.4102
INFO flwr 2023-08-20 21:26:36,678 | common.py:35 | Avg. local train loss : 4.279517401382327, train acc : 0.8914000000000001
INFO flwr 2023-08-20 21:26:39,322 | server.py:116 | fit progress: (26, 1.95101728515625, {'server_test_acc': 0.4003}, 3799.6723961699754)
INFO flwr 2023-08-20 21:26:39,322 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 21:26:42,766 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=725866)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 21:27:30,691 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 21:27:30,800 | fed_df.py:365 | Warm start at round 27
[2m[36m(launch_and_fit pid=725793)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:27:30,896 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=725865)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=725866)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=725797)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=725793)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=725796)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=725795)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=725794)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=725791)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=725797)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=725796)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=725795)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=725794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=725865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=725791)[0m double free or corruption (fasttop)
E0820 21:27:32.897492397  560264 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:29:02,178 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:29:02,179 | fed_df.py:547 | Average fusion training loss : 0.000833133390173316, val accuracy : 0.39942, best val accuracy : 0.4054
INFO flwr 2023-08-20 21:29:02,180 | common.py:35 | Avg. local train loss : 4.269163141027093, train acc : 0.9020833333333332
INFO flwr 2023-08-20 21:29:04,782 | server.py:116 | fit progress: (27, 1.9032876770019531, {'server_test_acc': 0.4076}, 3945.132515814621)
INFO flwr 2023-08-20 21:29:04,782 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 21:29:08,233 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=977005)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:29:55,954 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-20 21:29:56,063 | fed_df.py:365 | Warm start at round 28
[2m[36m(launch_and_fit pid=977109)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 21:29:56,159 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=977005)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=977108)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=977106)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=977109)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=977112)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=977111)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=977110)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=977006)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=977110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=977112)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=977006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=977106)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=977111)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=977108)[0m malloc_consolidate(): invalid chunk size
E0820 21:29:58.280531137  814678 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:31:28,424 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:31:28,425 | fed_df.py:547 | Average fusion training loss : 0.0006310581868456211, val accuracy : 0.48902, best val accuracy : 0.4986
INFO flwr 2023-08-20 21:31:28,426 | common.py:35 | Avg. local train loss : 4.22572766058147, train acc : 0.9098999999999999
INFO flwr 2023-08-20 21:31:31,055 | server.py:116 | fit progress: (28, 1.9322315002441406, {'server_test_acc': 0.4896}, 4091.4054358056746)
INFO flwr 2023-08-20 21:31:31,055 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-20 21:31:34,601 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1228789)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1228824)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1228788)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:32:22,525 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-20 21:32:22,634 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-20 21:32:22,728 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1228789)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1228824)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1228787)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1228786)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1228858)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1228860)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1228788)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1228859)[0m Fitting Client 10
E0820 21:32:23.435933180 1066771 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1228786)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1228860)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1228858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1228859)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1228787)[0m malloc_consolidate(): invalid chunk size
E0820 21:32:25.192216357 1318377 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:33:55,677 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:33:55,677 | fed_df.py:547 | Average fusion training loss : 0.00047257253710995427, val accuracy : 0.4643, best val accuracy : 0.4692
INFO flwr 2023-08-20 21:33:55,679 | common.py:35 | Avg. local train loss : 3.958393785357475, train acc : 0.9285333333333333
INFO flwr 2023-08-20 21:33:58,321 | server.py:116 | fit progress: (29, 1.9860701904296876, {'server_test_acc': 0.4689}, 4238.671918196604)
INFO flwr 2023-08-20 21:33:58,322 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 21:34:01,833 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1481104)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 21:34:50,185 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 21:34:50,294 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 21:34:50,389 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1481029)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1481100)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1481066)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1481101)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1481102)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1481103)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1481030)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1481104)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1481102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481100)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481066)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481103)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481101)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1481030)[0m malloc_consolidate(): invalid chunk size
E0820 21:34:51.704751275 1319118 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 21:35:14.658331339 1597656 chttp2_transport.cc:1079]             ipv4:145.136.62.28:51938: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 21:36:20,880 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 21:36:20,880 | fed_df.py:547 | Average fusion training loss : 0.0005585914087714627, val accuracy : 0.4041200000000001, best val accuracy : 0.4078
INFO flwr 2023-08-20 21:36:20,881 | common.py:35 | Avg. local train loss : 3.9945161767303947, train acc : 0.9079055555555554
INFO flwr 2023-08-20 21:36:23,451 | server.py:116 | fit progress: (30, 1.9620098083496094, {'server_test_acc': 0.4119}, 4383.801672581583)
INFO flwr 2023-08-20 21:36:23,451 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 21:36:23,451 | server.py:144 | FL finished in 4383.802002009004
INFO flwr 2023-08-20 21:36:23,452 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 21:36:23,453 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 21:36:23,453 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.891298211669922), (2, 2.093659832763672), (3, 1.9292242126464845), (4, 1.8588919494628906), (5, 1.8133299438476562), (6, 1.8918137756347657), (7, 1.832922036743164), (8, 1.888625469970703), (9, 1.8933110443115235), (10, 1.797315286254883), (11, 1.7861522369384766), (12, 1.8484950775146485), (13, 1.8750997985839843), (14, 1.8909188385009765), (15, 1.8298649932861328), (16, 1.896278564453125), (17, 1.8766689697265626), (18, 1.9622776184082031), (19, 1.9319413513183594), (20, 1.961614453125), (21, 1.9503027709960938), (22, 1.9489025390625), (23, 1.9289696228027344), (24, 1.9287776550292968), (25, 1.8962083129882812), (26, 1.95101728515625), (27, 1.9032876770019531), (28, 1.9322315002441406), (29, 1.9860701904296876), (30, 1.9620098083496094)]
INFO flwr 2023-08-20 21:36:23,453 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.3184), (2, 0.2971), (3, 0.3452), (4, 0.3588), (5, 0.3922), (6, 0.4022), (7, 0.3834), (8, 0.3682), (9, 0.3966), (10, 0.4281), (11, 0.4316), (12, 0.4493), (13, 0.382), (14, 0.4582), (15, 0.4565), (16, 0.487), (17, 0.4566), (18, 0.5079), (19, 0.454), (20, 0.4526), (21, 0.4787), (22, 0.4126), (23, 0.4482), (24, 0.4778), (25, 0.4582), (26, 0.4003), (27, 0.4076), (28, 0.4896), (29, 0.4689), (30, 0.4119)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn28: task 0: Aborted
srun: Terminating StepId=3429375.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3429375
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:48:09
CPU Efficiency: 12.34% of 22:42:54 core-walltime
Job Wall-clock time: 01:15:43
Memory Utilized: 50.04 GB
Memory Efficiency: 41.70% of 120.00 GB
