-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:25000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar100
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=25000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3423719/1692469240_063137266', seed=42, img_per_thread=1388)
will save 25000 patches in /scratch-local/sunnys.3423719/1692469240_063137266/single_img_crops/crops
25000 took 0.34min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-19 20:21:15,783 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-19 20:21:15,783 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3423719/1692469240_063137266/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3423719/1692469240_063137266/cifar-100-python.tar.gz to /scratch-local/sunnys.3423719/1692469240_063137266
Generating unified cifar100 dataset
Class histogram for 0-th partition (alpha=1.0, 100 classes): [ 65  77  67   8   1  43  47  96   4  28   0  26  39  10  37   4   0  12
  20  11  38   8  50  35  20  11  16   0   5  16  13  33  16   9  10  17
  11  10  29  11  27  31  29   2  25  41  21   8   4   2   9   1   8  35
 132   9   9   7  15   4  39  45  31 146  69  42  29  20   1  23  23  42
  39  11   2  30  51  23  57  28  36   7   2   6   1   4  62   7  10  33
   6  54  36  11   7  12   7   2  19  55]
INFO flwr 2023-08-19 20:21:35,038 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-19 20:21:38,719	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-19 20:21:40,897 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'CPU': 18.0, 'GPU': 1.0, 'node:145.136.62.58': 1.0}
INFO flwr 2023-08-19 20:21:40,898 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-19 20:21:40,898 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-19 20:21:40,898 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-19 20:21:50,001 | server.py:91 | initial parameters (loss, other metrics): 4.655556018066406, {'server_test_acc': 0.0107}
INFO flwr 2023-08-19 20:21:50,001 | server.py:101 | FL starting
DEBUG flwr 2023-08-19 20:21:54,777 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3927922)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:22:32,900 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-19 20:22:33,016 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-19 20:22:33,115 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3927923)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3927922)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3927919)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3927920)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3927921)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3927925)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3927924)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3927911)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3927921)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927920)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927923)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927919)[0m double free or corruption (fasttop)
E0819 20:22:35.201873129 3981048 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=3927911)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927924)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3927925)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-19 20:23:17,713 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:23:17,713 | fed_df.py:547 | Average fusion training loss : 0.502745804309845, val accuracy : 0.056479999999999995, best val accuracy : 0.0624
INFO flwr 2023-08-19 20:23:17,714 | common.py:35 | Avg. local train loss : 21.038114073872567, train acc : 0.13455
INFO flwr 2023-08-19 20:23:20,286 | server.py:116 | fit progress: (1, 4.579686059570313, {'server_test_acc': 0.0578}, 90.28537522396073)
INFO flwr 2023-08-19 20:23:20,287 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-19 20:23:25,124 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4060623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060618)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:24:00,839 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-19 20:24:00,989 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4060618)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4060616)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4060625)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4060623)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4060622)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4060620)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4060621)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4060624)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4060620)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060625)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4060624)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4060622)[0m malloc_consolidate(): invalid chunk size
E0819 20:24:03.038734801 3981451 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=4060621)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:24:46,913 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:24:46,913 | fed_df.py:547 | Average fusion training loss : 0.5792592262029648, val accuracy : 0.06776, best val accuracy : 0.075
INFO flwr 2023-08-19 20:24:46,914 | common.py:35 | Avg. local train loss : 20.446398565173148, train acc : 0.1741611111111111
INFO flwr 2023-08-19 20:24:49,533 | server.py:116 | fit progress: (2, 4.541773815917969, {'server_test_acc': 0.0726}, 179.53187975287437)
INFO flwr 2023-08-19 20:24:49,533 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-19 20:24:54,443 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:25:29,447 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-19 20:25:29,600 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4193832)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4193836)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4193835)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4193839)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4193837)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4193834)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4193833)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4193838)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4193836)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193833)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4193837)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4193835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193834)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193832)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193838)[0m malloc_consolidate(): invalid chunk size
E0819 20:25:32.993514319   57558 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-19 20:26:15,791 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:26:15,791 | fed_df.py:547 | Average fusion training loss : 0.7143253631591797, val accuracy : 0.06208, best val accuracy : 0.071
INFO flwr 2023-08-19 20:26:15,792 | common.py:35 | Avg. local train loss : 20.528099095821382, train acc : 0.16963888888888892
INFO flwr 2023-08-19 20:26:18,418 | server.py:116 | fit progress: (3, 4.499819311523438, {'server_test_acc': 0.0691}, 268.41727232187986)
INFO flwr 2023-08-19 20:26:18,418 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-19 20:26:23,307 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=133381)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:26:56,683 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-19 20:26:56,834 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=133381)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=133386)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=133388)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=133385)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=133387)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=133389)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=133390)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=133391)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=133390)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=133387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=133391)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=133386)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=133388)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=133385)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=133389)[0m double free or corruption (fasttop)
E0819 20:26:59.044165079   57961 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-19 20:27:43,699 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:27:43,700 | fed_df.py:547 | Average fusion training loss : 0.6167013783454895, val accuracy : 0.07511999999999999, best val accuracy : 0.0798
INFO flwr 2023-08-19 20:27:43,701 | common.py:35 | Avg. local train loss : 20.667553529143333, train acc : 0.15865
INFO flwr 2023-08-19 20:27:46,357 | server.py:116 | fit progress: (4, 4.483887939453125, {'server_test_acc': 0.0704}, 356.3556124116294)
INFO flwr 2023-08-19 20:27:46,357 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-19 20:27:51,304 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:28:24,751 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-19 20:28:24,873 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-19 20:28:24,978 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=266067)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=266070)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=266074)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=266068)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=266071)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=266069)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=266073)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=266072)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=266067)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=266071)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=266074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=266070)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=266069)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=266072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=266073)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=266068)[0m double free or corruption (fasttop)
E0819 20:28:26.954317457  188196 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-19 20:29:11,871 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:29:11,871 | fed_df.py:547 | Average fusion training loss : 0.4615560483932495, val accuracy : 0.0822, best val accuracy : 0.0892
INFO flwr 2023-08-19 20:29:11,873 | common.py:35 | Avg. local train loss : 20.502410915493964, train acc : 0.17397222222222222
INFO flwr 2023-08-19 20:29:14,545 | server.py:116 | fit progress: (5, 4.610132189941406, {'server_test_acc': 0.0869}, 444.5442007826641)
INFO flwr 2023-08-19 20:29:14,545 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-19 20:29:19,794 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:29:53,925 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-19 20:29:54,080 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=398547)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=398546)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=398540)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=398550)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=398551)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=398549)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=398544)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=398543)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=398540)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=398550)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=398547)[0m malloc_consolidate(): invalid chunk size
E0819 20:29:54.765264749  320620 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=398549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398546)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398544)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398543)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:30:41,101 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:30:41,102 | fed_df.py:547 | Average fusion training loss : 0.19811778730154037, val accuracy : 0.07816000000000001, best val accuracy : 0.082
INFO flwr 2023-08-19 20:30:41,103 | common.py:35 | Avg. local train loss : 20.221137258410455, train acc : 0.19585555555555556
INFO flwr 2023-08-19 20:30:43,744 | server.py:116 | fit progress: (6, 4.3778621826171875, {'server_test_acc': 0.0803}, 533.7429146566428)
INFO flwr 2023-08-19 20:30:43,744 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-19 20:30:48,931 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=531459)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:31:22,982 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-19 20:31:23,147 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=531460)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=531459)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=531464)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=531465)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=531468)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=531467)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=531466)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=531469)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=531460)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=531468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=531467)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=531469)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=531465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=531466)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=531464)[0m malloc_consolidate(): invalid chunk size
E0819 20:31:26.646667041  451232 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-19 20:32:10,824 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:32:10,824 | fed_df.py:547 | Average fusion training loss : 0.19810170137882233, val accuracy : 0.08868000000000001, best val accuracy : 0.0936
INFO flwr 2023-08-19 20:32:10,826 | common.py:35 | Avg. local train loss : 20.15942620933056, train acc : 0.20699444444444445
INFO flwr 2023-08-19 20:32:13,475 | server.py:116 | fit progress: (7, 4.399159118652344, {'server_test_acc': 0.096}, 623.4744800087065)
INFO flwr 2023-08-19 20:32:13,476 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-19 20:32:18,711 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=664232)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:32:51,717 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=664241)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:32:51,879 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=664232)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=664240)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=664235)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=664239)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=664237)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=664236)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=664238)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=664241)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=664240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=664239)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=664237)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=664238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=664235)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=664236)[0m malloc_consolidate(): invalid chunk size
E0819 20:33:35.901132273  589486 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-19 20:33:39,563 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:33:39,564 | fed_df.py:547 | Average fusion training loss : 0.2123855088353157, val accuracy : 0.09776000000000001, best val accuracy : 0.1022
INFO flwr 2023-08-19 20:33:39,565 | common.py:35 | Avg. local train loss : 20.228607580065727, train acc : 0.20137777777777777
INFO flwr 2023-08-19 20:33:42,229 | server.py:116 | fit progress: (8, 4.417740148925781, {'server_test_acc': 0.1079}, 712.228263258934)
INFO flwr 2023-08-19 20:33:42,229 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-19 20:33:47,686 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=797141)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=797137)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:34:20,805 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-19 20:34:20,963 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=797137)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=797141)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=797162)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=797163)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=797166)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=797167)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=797165)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=797161)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=797167)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=797161)[0m double free or corruption (fasttop)
E0819 20:34:22.308327330  853807 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=797163)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=797162)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=797166)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:35:08,978 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:35:08,978 | fed_df.py:547 | Average fusion training loss : 0.20947308713197707, val accuracy : 0.11316000000000001, best val accuracy : 0.1184
INFO flwr 2023-08-19 20:35:08,979 | common.py:35 | Avg. local train loss : 20.12573845386505, train acc : 0.2134
INFO flwr 2023-08-19 20:35:11,684 | server.py:116 | fit progress: (9, 4.4438301391601565, {'server_test_acc': 0.1164}, 801.6830657087266)
INFO flwr 2023-08-19 20:35:11,684 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-19 20:35:17,283 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=948203)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:35:51,387 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-19 20:35:51,509 | fed_df.py:365 | Warm start at round 10
[2m[36m(launch_and_fit pid=948196)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:35:51,610 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=948196)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=948197)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=948200)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=948198)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=948201)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=948199)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=948203)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=948202)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=948199)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948202)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948200)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948201)[0m double free or corruption (fasttop)
E0819 20:35:52.549557593  854020 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=948197)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=948198)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-19 20:36:39,628 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:36:39,629 | fed_df.py:547 | Average fusion training loss : 0.08498479700088502, val accuracy : 0.11716, best val accuracy : 0.1228
INFO flwr 2023-08-19 20:36:39,630 | common.py:35 | Avg. local train loss : 20.068036189675333, train acc : 0.2213166666666667
INFO flwr 2023-08-19 20:36:42,323 | server.py:116 | fit progress: (10, 4.3428376831054685, {'server_test_acc': 0.1256}, 892.3221393427812)
INFO flwr 2023-08-19 20:36:42,323 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-19 20:36:47,652 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1091554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1091557)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:37:20,505 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-19 20:37:20,668 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1091557)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1091550)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1091552)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1091551)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1091556)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1091555)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1091554)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1091553)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1091552)[0m double free or corruption (fasttop)
E0819 20:37:21.009937223 1010529 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=1091551)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1091553)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1091555)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1091550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1091556)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:38:08,863 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:38:08,864 | fed_df.py:547 | Average fusion training loss : 0.036480358466506005, val accuracy : 0.13288, best val accuracy : 0.1352
INFO flwr 2023-08-19 20:38:08,865 | common.py:35 | Avg. local train loss : 19.75917464494705, train acc : 0.2474666666666667
INFO flwr 2023-08-19 20:38:11,556 | server.py:116 | fit progress: (11, 4.325327685546875, {'server_test_acc': 0.129}, 981.5547869778238)
INFO flwr 2023-08-19 20:38:11,556 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-19 20:38:17,156 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:38:50,171 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1224618)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:38:50,330 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1224622)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1224618)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1224623)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1224620)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1224619)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1224624)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1224617)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1224621)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1224622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1224623)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1224619)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1224620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1224617)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1224624)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1224621)[0m malloc_consolidate(): invalid chunk size
E0819 20:38:52.594841876 1280501 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-19 20:39:38,872 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:39:38,872 | fed_df.py:547 | Average fusion training loss : 0.040790077835321424, val accuracy : 0.1402, best val accuracy : 0.1424
INFO flwr 2023-08-19 20:39:38,873 | common.py:35 | Avg. local train loss : 19.84921773970127, train acc : 0.24277777777777776
INFO flwr 2023-08-19 20:39:41,587 | server.py:116 | fit progress: (12, 4.282059997558593, {'server_test_acc': 0.148}, 1071.5857309098355)
INFO flwr 2023-08-19 20:39:41,587 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-19 20:39:47,032 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:40:19,922 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-19 20:40:20,077 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1357186)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1357194)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1357187)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1357189)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1357190)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1357192)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1357193)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1357191)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1357186)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1357187)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1357189)[0m malloc_consolidate(): invalid chunk size
E0819 20:40:20.801759329 1283008 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1357194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1357190)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1357193)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1357191)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1357192)[0m double free or corruption (fasttop)
E0819 20:40:22.430217884 1416321 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-19 20:41:08,396 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:41:08,396 | fed_df.py:547 | Average fusion training loss : 0.04171429434046149, val accuracy : 0.1502, best val accuracy : 0.155
INFO flwr 2023-08-19 20:41:08,398 | common.py:35 | Avg. local train loss : 19.72522168159485, train acc : 0.2553722222222222
INFO flwr 2023-08-19 20:41:11,115 | server.py:116 | fit progress: (13, 4.2645745361328125, {'server_test_acc': 0.1553}, 1161.1141922338866)
INFO flwr 2023-08-19 20:41:11,115 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-19 20:41:16,651 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1489913)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:41:49,435 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-19 20:41:49,587 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1489915)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1489912)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1489916)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1489913)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1489919)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1489914)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1489917)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1489918)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1489915)[0m malloc_consolidate(): invalid chunk size
E0819 20:41:50.440619796 1416556 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1489912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1489916)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1489919)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1489917)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1489914)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:42:38,004 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:42:38,005 | fed_df.py:547 | Average fusion training loss : 0.015545628372579813, val accuracy : 0.14992, best val accuracy : 0.1532
INFO flwr 2023-08-19 20:42:38,006 | common.py:35 | Avg. local train loss : 19.649454852938653, train acc : 0.2647277777777778
INFO flwr 2023-08-19 20:42:40,728 | server.py:116 | fit progress: (14, 4.217445812988281, {'server_test_acc': 0.1537}, 1250.7270168038085)
INFO flwr 2023-08-19 20:42:40,728 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-19 20:42:46,198 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1622582)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1622580)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:43:18,795 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-19 20:43:18,915 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-19 20:43:19,005 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1622577)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1622580)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1622582)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1622578)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1622581)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1622583)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1622579)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1622584)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1622577)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1622581)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1622583)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1622578)[0m double free or corruption (fasttop)
E0819 20:43:20.233395724 1547465 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1622579)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1622584)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:44:07,098 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:44:07,098 | fed_df.py:547 | Average fusion training loss : 0.010341387280263006, val accuracy : 0.15908, best val accuracy : 0.16
INFO flwr 2023-08-19 20:44:07,100 | common.py:35 | Avg. local train loss : 19.372914674878118, train acc : 0.28799444444444444
INFO flwr 2023-08-19 20:44:09,789 | server.py:116 | fit progress: (15, 4.20853623046875, {'server_test_acc': 0.1541}, 1339.7876873430796)
INFO flwr 2023-08-19 20:44:09,789 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-19 20:44:15,214 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1757349)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:44:47,508 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-19 20:44:47,662 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1757349)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1757345)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1757350)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1757340)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1757346)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1757344)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1757348)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1757347)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1757346)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757344)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757347)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1757345)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757340)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757350)[0m double free or corruption (fasttop)
E0819 20:44:49.054082649 1816078 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1757348)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:45:36,398 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:45:36,398 | fed_df.py:547 | Average fusion training loss : 0.005623470067977906, val accuracy : 0.1676, best val accuracy : 0.1714
INFO flwr 2023-08-19 20:45:36,400 | common.py:35 | Avg. local train loss : 19.367267328500745, train acc : 0.2869055555555556
INFO flwr 2023-08-19 20:45:39,270 | server.py:116 | fit progress: (16, 4.206353063964844, {'server_test_acc': 0.1602}, 1429.2691295458935)
INFO flwr 2023-08-19 20:45:39,270 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-19 20:45:44,736 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1889986)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:46:16,954 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1889988)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:46:17,110 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1889986)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1889988)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1889983)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1889990)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1889989)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1889991)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1889987)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1889992)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1889983)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1889991)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1889992)[0m double free or corruption (fasttop)
E0819 20:46:18.241588355 1816222 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1889987)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1889989)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1889990)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:47:08,995 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:47:08,996 | fed_df.py:547 | Average fusion training loss : 0.0069816333691123875, val accuracy : 0.17836000000000002, best val accuracy : 0.182
INFO flwr 2023-08-19 20:47:08,997 | common.py:35 | Avg. local train loss : 19.334686663746833, train acc : 0.29563333333333336
INFO flwr 2023-08-19 20:47:12,161 | server.py:116 | fit progress: (17, 4.174718151855469, {'server_test_acc': 0.1764}, 1522.1597370407544)
INFO flwr 2023-08-19 20:47:12,161 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-19 20:47:17,897 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2027868)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2027887)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:47:50,845 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-19 20:47:51,005 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2027868)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2027887)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2027894)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2027893)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2027888)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2027885)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2027889)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2027892)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2027894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2027889)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2027885)[0m malloc_consolidate(): invalid chunk size
E0819 20:47:52.126509289 1949478 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2027892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2027888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2027893)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:48:37,864 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:48:37,864 | fed_df.py:547 | Average fusion training loss : 0.005960807378869504, val accuracy : 0.17776, best val accuracy : 0.1804
INFO flwr 2023-08-19 20:48:37,866 | common.py:35 | Avg. local train loss : 19.30759017467499, train acc : 0.29904444444444445
INFO flwr 2023-08-19 20:48:41,026 | server.py:116 | fit progress: (18, 4.177537353515625, {'server_test_acc': 0.1745}, 1611.024714154657)
INFO flwr 2023-08-19 20:48:41,026 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-19 20:48:46,713 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:49:19,552 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-19 20:49:19,713 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2159671)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2159670)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2159666)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2159695)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2159709)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2159812)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2159811)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2159813)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2159666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2159671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2159709)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2159695)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2159812)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2159670)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2159813)[0m double free or corruption (fasttop)
E0819 20:49:21.667901765 2220515 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2159811)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:50:07,076 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:50:07,077 | fed_df.py:547 | Average fusion training loss : 0.0065372232624795286, val accuracy : 0.18492000000000003, best val accuracy : 0.186
INFO flwr 2023-08-19 20:50:07,078 | common.py:35 | Avg. local train loss : 19.276682800054548, train acc : 0.29895000000000005
INFO flwr 2023-08-19 20:50:09,820 | server.py:116 | fit progress: (19, 4.167488110351562, {'server_test_acc': 0.1763}, 1699.818748560734)
INFO flwr 2023-08-19 20:50:09,820 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-19 20:50:15,619 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2301876)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2301878)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:50:49,324 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-19 20:50:49,446 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-19 20:50:49,545 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2301876)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2301878)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2301875)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2301881)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2301879)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2301883)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2301880)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2301882)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2301875)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2301881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2301880)[0m malloc_consolidate(): invalid chunk size
E0819 20:50:50.461593324 2372806 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2301882)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2301879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2301883)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:51:37,086 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:51:37,087 | fed_df.py:547 | Average fusion training loss : 0.008339359401725232, val accuracy : 0.19608, best val accuracy : 0.1982
INFO flwr 2023-08-19 20:51:37,088 | common.py:35 | Avg. local train loss : 19.328179135918617, train acc : 0.30039444444444446
INFO flwr 2023-08-19 20:51:40,131 | server.py:116 | fit progress: (20, 4.177930285644531, {'server_test_acc': 0.1988}, 1790.1295970180072)
INFO flwr 2023-08-19 20:51:40,131 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-19 20:51:45,658 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2462102)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:52:18,256 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2462086)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:52:18,411 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2462102)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2462086)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2462253)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2462252)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2462254)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2462221)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2462250)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2462255)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2462221)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2462255)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2462253)[0m malloc_consolidate(): invalid chunk size
E0819 20:52:19.525739532 2373422 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2462254)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2462252)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2462250)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:53:05,217 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:53:05,217 | fed_df.py:547 | Average fusion training loss : 0.0031108531517675146, val accuracy : 0.18668, best val accuracy : 0.1902
INFO flwr 2023-08-19 20:53:05,219 | common.py:35 | Avg. local train loss : 19.02167001664639, train acc : 0.3277777777777778
INFO flwr 2023-08-19 20:53:08,150 | server.py:116 | fit progress: (21, 4.20134130859375, {'server_test_acc': 0.1898}, 1878.1495245606638)
INFO flwr 2023-08-19 20:53:08,151 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-19 20:53:13,656 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2593728)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:53:46,390 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-19 20:53:46,553 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2593728)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2593865)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2593866)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2593999)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2593998)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2594000)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2594004)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2594003)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2593865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2593998)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2594004)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2594003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2593999)[0m malloc_consolidate(): invalid chunk size
E0819 20:53:47.914862535 2518125 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2593866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2594000)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:54:33,428 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:54:33,429 | fed_df.py:547 | Average fusion training loss : 0.006560460562352091, val accuracy : 0.19356, best val accuracy : 0.1952
INFO flwr 2023-08-19 20:54:33,430 | common.py:35 | Avg. local train loss : 19.201519510149957, train acc : 0.3155
INFO flwr 2023-08-19 20:54:36,439 | server.py:116 | fit progress: (22, 4.176234338378906, {'server_test_acc': 0.1974}, 1966.4380244957283)
INFO flwr 2023-08-19 20:54:36,439 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-19 20:54:42,114 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2727778)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:55:15,315 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-19 20:55:15,478 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2727626)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2727626)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2727776)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2727848)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2727778)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2727850)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2727779)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2727849)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2727669)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2727848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2727779)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2727850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2727776)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2727669)[0m malloc_consolidate(): invalid chunk size
E0819 20:55:17.398244259 2780605 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:56:02,538 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:56:02,538 | fed_df.py:547 | Average fusion training loss : 0.0037008020649664103, val accuracy : 0.19348, best val accuracy : 0.198
INFO flwr 2023-08-19 20:56:02,539 | common.py:35 | Avg. local train loss : 19.147610127925873, train acc : 0.31949444444444447
INFO flwr 2023-08-19 20:56:05,285 | server.py:116 | fit progress: (23, 4.154790869140625, {'server_test_acc': 0.2069}, 2055.284538117703)
INFO flwr 2023-08-19 20:56:05,286 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-19 20:56:11,071 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2855239)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2855246)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:56:44,306 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-19 20:56:44,471 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2855239)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2855240)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2855246)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2855238)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2855264)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2855282)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2855243)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2855236)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2855238)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2855243)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2855282)[0m double free or corruption (fasttop)
E0819 20:56:45.741454378 2912833 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2855264)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2855240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2855236)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:57:32,340 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:57:32,341 | fed_df.py:547 | Average fusion training loss : 0.008763612187234685, val accuracy : 0.20736, best val accuracy : 0.21
INFO flwr 2023-08-19 20:57:32,343 | common.py:35 | Avg. local train loss : 19.01064519882202, train acc : 0.33055555555555555
INFO flwr 2023-08-19 20:57:35,065 | server.py:116 | fit progress: (24, 4.149083642578125, {'server_test_acc': 0.2031}, 2145.0635985517874)
INFO flwr 2023-08-19 20:57:35,065 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-19 20:57:40,804 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:58:13,849 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-19 20:58:13,971 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=2988289)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:58:14,063 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2988342)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2988289)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2988286)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2988456)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2988457)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2988455)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2988454)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2988458)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2988456)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2988342)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2988455)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2988458)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2988286)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2988454)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2988457)[0m malloc_consolidate(): invalid chunk size
E0819 20:58:15.991310438 2913274 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:59:01,319 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:59:01,319 | fed_df.py:547 | Average fusion training loss : 0.0092065331437625, val accuracy : 0.20296000000000003, best val accuracy : 0.2042
INFO flwr 2023-08-19 20:59:01,321 | common.py:35 | Avg. local train loss : 19.0903603553772, train acc : 0.3246166666666666
INFO flwr 2023-08-19 20:59:04,134 | server.py:116 | fit progress: (25, 4.163485900878906, {'server_test_acc': 0.2059}, 2234.1335473489016)
INFO flwr 2023-08-19 20:59:04,135 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-19 20:59:09,936 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:59:43,254 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-19 20:59:43,416 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3122395)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3122397)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3122399)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3122260)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3122398)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3122259)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3122400)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3122396)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3122399)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3122398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3122400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3122397)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3122395)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3122259)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3122396)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3122260)[0m malloc_consolidate(): invalid chunk size
E0819 20:59:45.444238075 3177449 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 21:00:30,423 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:00:30,423 | fed_df.py:547 | Average fusion training loss : 0.0020936722580809147, val accuracy : 0.20948000000000003, best val accuracy : 0.2116
INFO flwr 2023-08-19 21:00:30,425 | common.py:35 | Avg. local train loss : 18.94906972050667, train acc : 0.33718888888888887
INFO flwr 2023-08-19 21:00:33,178 | server.py:116 | fit progress: (26, 4.169892456054687, {'server_test_acc': 0.2087}, 2323.1775007909164)
INFO flwr 2023-08-19 21:00:33,179 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-19 21:00:38,769 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3250948)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 21:01:12,080 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-19 21:01:12,243 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3250856)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3250948)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3250950)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3250966)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3250947)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3251119)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3251050)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3251118)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3250856)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3250950)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3251119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3251118)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3250966)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3251050)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3250947)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:02:00,879 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:02:00,880 | fed_df.py:547 | Average fusion training loss : 0.008149327626219019, val accuracy : 0.20459999999999998, best val accuracy : 0.208
INFO flwr 2023-08-19 21:02:00,882 | common.py:35 | Avg. local train loss : 18.984410503506663, train acc : 0.3367
INFO flwr 2023-08-19 21:02:03,712 | server.py:116 | fit progress: (27, 4.182829528808594, {'server_test_acc': 0.2065}, 2413.711226685904)
INFO flwr 2023-08-19 21:02:03,712 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-19 21:02:09,318 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3389026)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3389162)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 21:02:42,487 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-19 21:02:42,642 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3389026)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3389162)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3389165)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3389163)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3389029)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3389030)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3389028)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3389164)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3389029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3389030)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3389028)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3389165)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3389164)[0m malloc_consolidate(): invalid chunk size
E0819 21:02:43.997040555 3447080 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3389163)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 21:03:29,536 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:03:29,536 | fed_df.py:547 | Average fusion training loss : 0.0005490709451260045, val accuracy : 0.21064, best val accuracy : 0.2138
INFO flwr 2023-08-19 21:03:29,538 | common.py:35 | Avg. local train loss : 18.967916443943977, train acc : 0.3366
INFO flwr 2023-08-19 21:03:32,407 | server.py:116 | fit progress: (28, 4.134128540039063, {'server_test_acc': 0.2135}, 2502.406068992801)
INFO flwr 2023-08-19 21:03:32,407 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-19 21:03:38,053 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3524815)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 21:04:10,974 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3524816)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:04:11,137 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3524815)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3524837)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3524817)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3524816)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3524838)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3524842)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3524840)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3524841)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3524842)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3524841)[0m double free or corruption (fasttop)
E0819 21:04:12.317260569 3447300 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3524817)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524837)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:04:58,613 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:04:58,613 | fed_df.py:547 | Average fusion training loss : 0.003817781124264002, val accuracy : 0.21915999999999997, best val accuracy : 0.2206
INFO flwr 2023-08-19 21:04:58,614 | common.py:35 | Avg. local train loss : 18.970197463035582, train acc : 0.3427555555555555
INFO flwr 2023-08-19 21:05:01,462 | server.py:116 | fit progress: (29, 4.124432336425781, {'server_test_acc': 0.2211}, 2591.4606880918145)
INFO flwr 2023-08-19 21:05:01,462 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-19 21:05:07,173 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:05:39,580 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3657888)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 21:05:39,702 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-19 21:05:39,802 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3657922)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3657888)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3658130)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3658127)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3658128)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3658132)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3658131)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3658129)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3657922)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3658130)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3658132)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3658127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3658131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3658128)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3658129)[0m malloc_consolidate(): invalid chunk size
E0819 21:05:43.542375126 3580266 chttp2_transport.cc:1079]             ipv4:145.136.62.58:48365: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 21:06:27,096 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:06:27,096 | fed_df.py:547 | Average fusion training loss : 0.0022024564685998484, val accuracy : 0.21508, best val accuracy : 0.2186
INFO flwr 2023-08-19 21:06:27,097 | common.py:35 | Avg. local train loss : 18.77146762907505, train acc : 0.3579444444444444
INFO flwr 2023-08-19 21:06:29,784 | server.py:116 | fit progress: (30, 4.157189038085938, {'server_test_acc': 0.2202}, 2679.7828212687746)
INFO flwr 2023-08-19 21:06:29,784 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-19 21:06:29,784 | server.py:144 | FL finished in 2679.7832086137496
INFO flwr 2023-08-19 21:06:29,784 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-19 21:06:29,786 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-19 21:06:29,786 | app.py:204 | app_fit: losses_centralized [(0, 4.655556018066406), (1, 4.579686059570313), (2, 4.541773815917969), (3, 4.499819311523438), (4, 4.483887939453125), (5, 4.610132189941406), (6, 4.3778621826171875), (7, 4.399159118652344), (8, 4.417740148925781), (9, 4.4438301391601565), (10, 4.3428376831054685), (11, 4.325327685546875), (12, 4.282059997558593), (13, 4.2645745361328125), (14, 4.217445812988281), (15, 4.20853623046875), (16, 4.206353063964844), (17, 4.174718151855469), (18, 4.177537353515625), (19, 4.167488110351562), (20, 4.177930285644531), (21, 4.20134130859375), (22, 4.176234338378906), (23, 4.154790869140625), (24, 4.149083642578125), (25, 4.163485900878906), (26, 4.169892456054687), (27, 4.182829528808594), (28, 4.134128540039063), (29, 4.124432336425781), (30, 4.157189038085938)]
INFO flwr 2023-08-19 21:06:29,786 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0107), (1, 0.0578), (2, 0.0726), (3, 0.0691), (4, 0.0704), (5, 0.0869), (6, 0.0803), (7, 0.096), (8, 0.1079), (9, 0.1164), (10, 0.1256), (11, 0.129), (12, 0.148), (13, 0.1553), (14, 0.1537), (15, 0.1541), (16, 0.1602), (17, 0.1764), (18, 0.1745), (19, 0.1763), (20, 0.1988), (21, 0.1898), (22, 0.1974), (23, 0.2069), (24, 0.2031), (25, 0.2059), (26, 0.2087), (27, 0.2065), (28, 0.2135), (29, 0.2211), (30, 0.2202)]}
double free or corruption (fasttop)
srun: error: gcn58: task 0: Aborted
srun: Terminating StepId=3423719.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3423719
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:56:28
CPU Efficiency: 13.84% of 14:01:48 core-walltime
Job Wall-clock time: 00:46:46
Memory Utilized: 52.97 GB
Memory Efficiency: 44.15% of 120.00 GB
