-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:25000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar100
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=25000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3423720/1692469248_427798891', seed=84, img_per_thread=1388)
will save 25000 patches in /scratch-local/sunnys.3423720/1692469248_427798891/single_img_crops/crops
25000 took 1.32min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-19 20:22:23,227 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-19 20:22:23,227 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3423720/1692469248_427798891/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3423720/1692469248_427798891/cifar-100-python.tar.gz to /scratch-local/sunnys.3423720/1692469248_427798891
Generating unified cifar100 dataset
Class histogram for 0-th partition (alpha=1.0, 100 classes): [ 29  16  30 102   3  22  45   3   3   8   0  48  24  15   6   3  16  24
   7  31  42  37  15  10  71  21   7  12  12   3  53  26  71  22  34  53
  10  40  24  25  13  56  78   3  23  47  18  99   1  53  40   6  35  30
  43  49   0   7  17  14  26  23   3  21  17  26   2  63  26  11   0  13
   0  31   1  18  34  50  12   8   4   3  10  45  22  11   0  12 105  62
  26  26  24  22  30   1  18  27  12   0]
INFO flwr 2023-08-19 20:22:42,696 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-19 20:22:46,038	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-19 20:22:47,461 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'node:145.136.62.59': 1.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-08-19 20:22:47,461 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-19 20:22:47,461 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-19 20:22:47,461 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-19 20:22:56,353 | server.py:91 | initial parameters (loss, other metrics): 4.651723132324219, {'server_test_acc': 0.0095}
INFO flwr 2023-08-19 20:22:56,353 | server.py:101 | FL starting
DEBUG flwr 2023-08-19 20:23:01,081 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:23:39,212 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-19 20:23:39,326 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-19 20:23:39,422 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4123676)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4123674)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4123675)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4123677)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4123668)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4123678)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4123679)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4123680)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4123677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123676)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123674)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4123680)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4123675)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123679)[0m malloc_consolidate(): invalid chunk size
E0819 20:23:41.411192019 4117633 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=4123678)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:24:23,803 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:24:23,803 | fed_df.py:547 | Average fusion training loss : 0.2741783640384674, val accuracy : 0.06444, best val accuracy : 0.0724
INFO flwr 2023-08-19 20:24:23,804 | common.py:35 | Avg. local train loss : 20.948986706137656, train acc : 0.1442166666666667
INFO flwr 2023-08-19 20:24:26,355 | server.py:116 | fit progress: (1, 4.473614892578125, {'server_test_acc': 0.0741}, 90.00201045675203)
INFO flwr 2023-08-19 20:24:26,356 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-19 20:24:31,081 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:25:06,363 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-19 20:25:06,510 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=63114)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=63124)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=63132)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=63130)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=63123)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=63127)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=63125)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=63133)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=63133)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63130)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63127)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=63123)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=63125)[0m double free or corruption (fasttop)
E0819 20:25:08.344632077  114608 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=63114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=63132)[0m malloc_consolidate(): invalid chunk size
E0819 20:25:25.948509033  115933 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-19 20:25:51,883 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:25:51,883 | fed_df.py:547 | Average fusion training loss : 0.27457501220703123, val accuracy : 0.08224000000000001, best val accuracy : 0.0874
INFO flwr 2023-08-19 20:25:51,884 | common.py:35 | Avg. local train loss : 20.278509718179702, train acc : 0.19070555555555554
INFO flwr 2023-08-19 20:25:54,465 | server.py:116 | fit progress: (2, 4.396752697753906, {'server_test_acc': 0.089}, 178.11174629675224)
INFO flwr 2023-08-19 20:25:54,465 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-19 20:25:59,431 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=195946)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:26:34,621 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-19 20:26:34,766 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=195946)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=195941)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=195936)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=195942)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=195944)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=195945)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=195943)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=195938)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=195936)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=195941)[0m malloc_consolidate(): invalid chunk size
E0819 20:26:35.785438967  246488 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=195945)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=195938)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=195943)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=195944)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=195942)[0m double free or corruption (fasttop)
E0819 20:26:37.357433201  249083 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-19 20:27:20,956 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:27:20,957 | fed_df.py:547 | Average fusion training loss : 0.28449077743291856, val accuracy : 0.08548000000000001, best val accuracy : 0.0868
INFO flwr 2023-08-19 20:27:20,958 | common.py:35 | Avg. local train loss : 20.205112576484677, train acc : 0.19622222222222221
INFO flwr 2023-08-19 20:27:23,570 | server.py:116 | fit progress: (3, 4.49777578125, {'server_test_acc': 0.0862}, 267.21673851367086)
INFO flwr 2023-08-19 20:27:23,570 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-19 20:27:28,593 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:28:04,173 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-19 20:28:04,323 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=328574)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=328578)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=328579)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=328590)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=328595)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=328589)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=328594)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=328588)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=328574)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=328579)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=328590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=328594)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=328589)[0m malloc_consolidate(): invalid chunk size
E0819 20:28:06.240841120  381332 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=328588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=328578)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:28:50,920 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:28:50,920 | fed_df.py:547 | Average fusion training loss : 0.2427725617289543, val accuracy : 0.08516000000000001, best val accuracy : 0.0892
INFO flwr 2023-08-19 20:28:50,921 | common.py:35 | Avg. local train loss : 20.157303312420844, train acc : 0.1999611111111111
INFO flwr 2023-08-19 20:28:53,579 | server.py:116 | fit progress: (4, 4.530605737304687, {'server_test_acc': 0.0897}, 357.2258346248418)
INFO flwr 2023-08-19 20:28:53,579 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-19 20:28:58,546 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=461722)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:29:33,219 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-19 20:29:33,334 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-19 20:29:33,423 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=461722)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=461726)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=461801)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=461727)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=461764)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=461725)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=461724)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=461842)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=461801)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=461726)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=461842)[0m double free or corruption (fasttop)
E0819 20:29:34.694976635  513607 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=461725)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=461764)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=461727)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=461724)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:30:21,160 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:30:21,160 | fed_df.py:547 | Average fusion training loss : 0.22423644256591796, val accuracy : 0.10047999999999999, best val accuracy : 0.1072
INFO flwr 2023-08-19 20:30:21,162 | common.py:35 | Avg. local train loss : 20.038737192749977, train acc : 0.21368333333333334
INFO flwr 2023-08-19 20:30:23,792 | server.py:116 | fit progress: (5, 4.397219079589844, {'server_test_acc': 0.1034}, 447.43875100603327)
INFO flwr 2023-08-19 20:30:23,792 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-19 20:30:28,818 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:31:03,363 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-19 20:31:03,519 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=594906)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=594904)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=594907)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=594910)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=594909)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=594908)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=594912)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=594911)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=594907)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=594909)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=594908)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=594912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=594904)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=594911)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=594910)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=594906)[0m malloc_consolidate(): invalid chunk size
E0819 20:31:06.148241607  652207 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
E0819 20:31:47.478186537  736232 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-19 20:31:50,843 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:31:50,844 | fed_df.py:547 | Average fusion training loss : 0.09470786246657371, val accuracy : 0.096, best val accuracy : 0.1002
INFO flwr 2023-08-19 20:31:50,845 | common.py:35 | Avg. local train loss : 19.752379050850866, train acc : 0.2392777777777778
INFO flwr 2023-08-19 20:31:53,447 | server.py:116 | fit progress: (6, 4.324489392089844, {'server_test_acc': 0.1062}, 537.0939447758719)
INFO flwr 2023-08-19 20:31:53,448 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-19 20:31:58,503 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:32:32,783 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-19 20:32:32,949 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=750276)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=750277)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=750280)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=750336)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=750335)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=750357)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=750355)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=750356)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=750355)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750280)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750335)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=750277)[0m double free or corruption (fasttop)
E0819 20:32:34.345359516  737488 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=750356)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750357)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:33:19,959 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:33:19,960 | fed_df.py:547 | Average fusion training loss : 0.0796221473813057, val accuracy : 0.11772, best val accuracy : 0.1236
INFO flwr 2023-08-19 20:33:19,961 | common.py:35 | Avg. local train loss : 19.85216641128063, train acc : 0.23481666666666667
INFO flwr 2023-08-19 20:33:22,595 | server.py:116 | fit progress: (7, 4.25882744140625, {'server_test_acc': 0.1204}, 626.2417238438502)
INFO flwr 2023-08-19 20:33:22,595 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-19 20:33:27,840 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=889539)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:34:02,127 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-19 20:34:02,289 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=889399)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=889539)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=889428)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=889440)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=889540)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=889444)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=889439)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=889538)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=889538)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=889428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=889399)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=889439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=889444)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=889540)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=889440)[0m malloc_consolidate(): invalid chunk size
E0819 20:34:05.804433952  944776 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-19 20:34:47,323 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:34:47,324 | fed_df.py:547 | Average fusion training loss : 0.07639896939694882, val accuracy : 0.1238, best val accuracy : 0.1272
INFO flwr 2023-08-19 20:34:47,325 | common.py:35 | Avg. local train loss : 19.67291210591793, train acc : 0.2550388888888889
INFO flwr 2023-08-19 20:34:49,964 | server.py:116 | fit progress: (8, 4.292693566894531, {'server_test_acc': 0.1302}, 713.6108758361079)
INFO flwr 2023-08-19 20:34:49,964 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-19 20:34:55,114 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:35:30,262 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-19 20:35:30,421 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1021915)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1021909)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1021908)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1021912)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1021913)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1021914)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1021916)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1021917)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1021915)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1021917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021908)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021913)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021916)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021914)[0m malloc_consolidate(): invalid chunk size
E0819 20:35:33.983793054 1076633 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
E0819 20:36:03.298836474 1079194 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-19 20:36:17,613 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:36:17,613 | fed_df.py:547 | Average fusion training loss : 0.04356312721222639, val accuracy : 0.13628, best val accuracy : 0.1382
INFO flwr 2023-08-19 20:36:17,615 | common.py:35 | Avg. local train loss : 19.632836562395095, train acc : 0.25656111111111113
INFO flwr 2023-08-19 20:36:20,257 | server.py:116 | fit progress: (9, 4.211205493164062, {'server_test_acc': 0.1396}, 803.9036957570352)
INFO flwr 2023-08-19 20:36:20,257 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-19 20:36:25,461 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1154866)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:36:58,586 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-19 20:36:58,704 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-19 20:36:58,802 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1154866)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1154870)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1154871)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1154875)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1154876)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1154872)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1154874)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1154877)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1154870)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1154876)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1154872)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1154874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1154871)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1154875)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1154877)[0m double free or corruption (fasttop)
E0819 20:37:01.336193547 1127978 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-19 20:37:46,306 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:37:46,307 | fed_df.py:547 | Average fusion training loss : 0.04947577065229416, val accuracy : 0.15284, best val accuracy : 0.1538
INFO flwr 2023-08-19 20:37:46,308 | common.py:35 | Avg. local train loss : 19.59313750565052, train acc : 0.26998888888888883
INFO flwr 2023-08-19 20:37:48,962 | server.py:116 | fit progress: (10, 4.189240759277344, {'server_test_acc': 0.1544}, 892.6090811928734)
INFO flwr 2023-08-19 20:37:48,963 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-19 20:37:54,142 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1287377)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:38:28,863 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-19 20:38:29,029 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1287377)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1287382)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1287386)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1287380)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1287384)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1287385)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1287387)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1287383)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1287386)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1287387)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1287387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1287385)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1287384)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1287380)[0m double free or corruption (fasttop)
E0819 20:38:29.937631958 1339840 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1287382)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1287383)[0m malloc_consolidate(): invalid chunk size
E0819 20:38:38.878777956 1353675 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0819 20:39:04.012447754 1394979 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:39:16,703 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:39:16,703 | fed_df.py:547 | Average fusion training loss : 0.004729518806561828, val accuracy : 0.149, best val accuracy : 0.1556
INFO flwr 2023-08-19 20:39:16,705 | common.py:35 | Avg. local train loss : 19.57030227482319, train acc : 0.2681722222222222
INFO flwr 2023-08-19 20:39:19,584 | server.py:116 | fit progress: (11, 4.10127373046875, {'server_test_acc': 0.1641}, 983.2308850567788)
INFO flwr 2023-08-19 20:39:19,584 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-19 20:39:25,369 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1420307)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:39:58,900 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-19 20:39:59,060 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1420307)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1420304)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1420435)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1420454)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1420455)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1420305)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1420456)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1420457)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1420304)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1420435)[0m double free or corruption (fasttop)
E0819 20:39:59.737379643 1395960 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1420455)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1420305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1420456)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1420457)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1420454)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-19 20:40:46,313 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:40:46,313 | fed_df.py:547 | Average fusion training loss : 0.006072595494333655, val accuracy : 0.17168, best val accuracy : 0.178
INFO flwr 2023-08-19 20:40:46,315 | common.py:35 | Avg. local train loss : 19.367939713597295, train acc : 0.2908777777777778
INFO flwr 2023-08-19 20:40:48,990 | server.py:116 | fit progress: (12, 4.072927758789063, {'server_test_acc': 0.1867}, 1072.636421035044)
INFO flwr 2023-08-19 20:40:48,990 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-19 20:40:54,315 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:41:28,519 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-19 20:41:28,680 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1552825)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1552820)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1552826)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1552827)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1552824)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1552823)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1552815)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1552822)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1552827)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1552826)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1552820)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1552815)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1552823)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1552822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1552825)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1552824)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:42:20,771 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:42:20,771 | fed_df.py:547 | Average fusion training loss : 0.008996304169297219, val accuracy : 0.17712, best val accuracy : 0.1802
INFO flwr 2023-08-19 20:42:20,773 | common.py:35 | Avg. local train loss : 19.100893890857698, train acc : 0.3163333333333333
INFO flwr 2023-08-19 20:42:23,417 | server.py:116 | fit progress: (13, 4.076659765625, {'server_test_acc': 0.1789}, 1167.0641361949965)
INFO flwr 2023-08-19 20:42:23,418 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-19 20:42:29,087 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:43:03,098 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1686173)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:43:03,265 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1686177)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1686169)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1686174)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1686175)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1686173)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1686178)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1686177)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1686168)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1686176)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1686169)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1686174)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1686168)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1686175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1686176)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1686178)[0m malloc_consolidate(): invalid chunk size
E0819 20:43:06.711259296 1745119 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0819 20:43:19.854852313 1747085 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:43:50,455 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:43:50,456 | fed_df.py:547 | Average fusion training loss : 0.010411160570569336, val accuracy : 0.18768, best val accuracy : 0.1928
INFO flwr 2023-08-19 20:43:50,457 | common.py:35 | Avg. local train loss : 19.157618653774264, train acc : 0.31353333333333333
INFO flwr 2023-08-19 20:43:53,129 | server.py:116 | fit progress: (14, 4.071371435546875, {'server_test_acc': 0.1948}, 1256.7755854637362)
INFO flwr 2023-08-19 20:43:53,129 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-19 20:43:59,004 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1818847)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:44:32,717 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-19 20:44:32,838 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-19 20:44:32,936 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1818833)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1818839)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1818832)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1818841)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1818840)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1818846)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1818847)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1818837)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1818832)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1818839)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1818837)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1818840)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1818846)[0m double free or corruption (fasttop)
E0819 20:44:33.910576013 1874951 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1818833)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1818841)[0m malloc_consolidate(): invalid chunk size
E0819 20:45:00.618867889 1875585 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:45:20,074 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:45:20,075 | fed_df.py:547 | Average fusion training loss : 0.007947598356287926, val accuracy : 0.18939999999999999, best val accuracy : 0.1916
INFO flwr 2023-08-19 20:45:20,076 | common.py:35 | Avg. local train loss : 19.205754008889198, train acc : 0.3102222222222222
INFO flwr 2023-08-19 20:45:22,700 | server.py:116 | fit progress: (15, 4.088613488769531, {'server_test_acc': 0.2031}, 1346.3462744876742)
INFO flwr 2023-08-19 20:45:22,700 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-19 20:45:28,423 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:46:01,997 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-19 20:46:02,159 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1951436)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1951435)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1951437)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1951438)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1951439)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1951433)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1951434)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1951440)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1951435)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951440)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951436)[0m malloc_consolidate(): invalid chunk size
E0819 20:46:03.514170226 1919557 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1951433)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1951439)[0m malloc_consolidate(): invalid chunk size
E0819 20:46:20.706580323 2010074 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:46:50,242 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:46:50,242 | fed_df.py:547 | Average fusion training loss : 0.0041994657907634975, val accuracy : 0.18944, best val accuracy : 0.192
INFO flwr 2023-08-19 20:46:50,243 | common.py:35 | Avg. local train loss : 18.97324647009373, train acc : 0.33569999999999994
INFO flwr 2023-08-19 20:46:52,966 | server.py:116 | fit progress: (16, 4.104623083496094, {'server_test_acc': 0.1967}, 1436.6128732669167)
INFO flwr 2023-08-19 20:46:52,966 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-19 20:46:58,681 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:47:31,584 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-19 20:47:31,739 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2106603)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2106606)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2106610)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2106607)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2106608)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2106605)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2106609)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2106611)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2106606)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106610)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106607)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106603)[0m malloc_consolidate(): invalid chunk size
E0819 20:47:33.977872215 2170688 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2106608)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106609)[0m double free or corruption (fasttop)
E0819 20:47:35.680243220 2173265 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:48:19,366 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:48:19,367 | fed_df.py:547 | Average fusion training loss : 0.010510954069904982, val accuracy : 0.19916, best val accuracy : 0.201
INFO flwr 2023-08-19 20:48:19,368 | common.py:35 | Avg. local train loss : 19.049798581004143, train acc : 0.32813333333333333
INFO flwr 2023-08-19 20:48:22,048 | server.py:116 | fit progress: (17, 4.101542907714844, {'server_test_acc': 0.1995}, 1525.6949087278917)
INFO flwr 2023-08-19 20:48:22,049 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-19 20:48:28,114 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2245729)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245726)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:49:01,953 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-19 20:49:02,112 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2245731)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2245723)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2245727)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2245728)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2245730)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2245729)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2245726)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2245725)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2245731)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245723)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245728)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245727)[0m double free or corruption (fasttop)
E0819 20:49:03.397680271 2173938 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2245725)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:49:49,591 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:49:49,591 | fed_df.py:547 | Average fusion training loss : 0.004564926028018818, val accuracy : 0.2024, best val accuracy : 0.204
INFO flwr 2023-08-19 20:49:49,593 | common.py:35 | Avg. local train loss : 18.970559832453727, train acc : 0.3361111111111111
INFO flwr 2023-08-19 20:49:52,245 | server.py:116 | fit progress: (18, 4.072843713378906, {'server_test_acc': 0.2067}, 1615.8913703588769)
INFO flwr 2023-08-19 20:49:52,245 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-19 20:49:58,077 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2378395)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:50:31,541 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-19 20:50:31,701 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2378395)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2378400)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2378397)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2378401)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2378402)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2378403)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2378404)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2378405)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2378402)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2378405)[0m malloc_consolidate(): invalid chunk size
E0819 20:50:32.626006041 2302798 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2378400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2378401)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2378397)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2378404)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2378403)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:51:19,359 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:51:19,359 | fed_df.py:547 | Average fusion training loss : 0.004480911223217845, val accuracy : 0.20012, best val accuracy : 0.2084
INFO flwr 2023-08-19 20:51:19,360 | common.py:35 | Avg. local train loss : 19.093620944023137, train acc : 0.32558333333333334
INFO flwr 2023-08-19 20:51:22,141 | server.py:116 | fit progress: (19, 4.064038732910157, {'server_test_acc': 0.2035}, 1705.7877164348029)
INFO flwr 2023-08-19 20:51:22,141 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-19 20:51:28,134 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:52:01,247 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2511081)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:52:01,373 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-19 20:52:01,471 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2511076)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2511081)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2511074)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2511079)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2511072)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2511083)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2511080)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2511082)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2511076)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2511074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2511080)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2511079)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2511072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2511083)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2511082)[0m malloc_consolidate(): invalid chunk size
E0819 20:52:04.923207459 2569429 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:52:49,301 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:52:49,302 | fed_df.py:547 | Average fusion training loss : 0.0026376547885593026, val accuracy : 0.21104000000000003, best val accuracy : 0.2146
INFO flwr 2023-08-19 20:52:49,303 | common.py:35 | Avg. local train loss : 19.02502213716507, train acc : 0.33482777777777784
INFO flwr 2023-08-19 20:52:51,975 | server.py:116 | fit progress: (20, 4.097873852539062, {'server_test_acc': 0.2191}, 1795.621228107717)
INFO flwr 2023-08-19 20:52:51,975 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-19 20:52:57,781 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:53:31,857 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-19 20:53:32,017 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2643752)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2643763)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2643765)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2643769)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2643762)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2643753)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2643770)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2643764)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2643765)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2643770)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2643762)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2643763)[0m double free or corruption (fasttop)
E0819 20:53:32.915862293 2700050 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2643769)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2643753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2643752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2643764)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:54:18,004 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:54:18,005 | fed_df.py:547 | Average fusion training loss : 0.0010254941544262691, val accuracy : 0.21200000000000002, best val accuracy : 0.2158
INFO flwr 2023-08-19 20:54:18,006 | common.py:35 | Avg. local train loss : 18.854376399517058, train acc : 0.3511944444444445
INFO flwr 2023-08-19 20:54:20,652 | server.py:116 | fit progress: (21, 4.092846545410156, {'server_test_acc': 0.2272}, 1884.2990090986714)
INFO flwr 2023-08-19 20:54:20,653 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-19 20:54:26,454 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:55:00,071 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-19 20:55:00,231 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2776561)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2776569)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2776562)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2776568)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2776566)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2776567)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2776571)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2776570)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2776562)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2776566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2776561)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2776569)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2776571)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2776567)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2776570)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2776568)[0m double free or corruption (fasttop)
E0819 20:55:02.684619697 2834794 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:55:46,397 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:55:46,397 | fed_df.py:547 | Average fusion training loss : 0.006408331143902614, val accuracy : 0.22684, best val accuracy : 0.23
INFO flwr 2023-08-19 20:55:46,398 | common.py:35 | Avg. local train loss : 18.799817815423012, train acc : 0.3578
INFO flwr 2023-08-19 20:55:49,107 | server.py:116 | fit progress: (22, 4.071796435546875, {'server_test_acc': 0.2252}, 1972.7537894067355)
INFO flwr 2023-08-19 20:55:49,107 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-19 20:55:54,988 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2908938)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2908998)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:56:28,663 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-19 20:56:28,824 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2908938)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2908937)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2908998)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2908934)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2908999)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2909002)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2909001)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2909000)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2908934)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2908999)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2909000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2909001)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2909002)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2908937)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:57:16,730 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:57:16,731 | fed_df.py:547 | Average fusion training loss : 0.0007163659784710035, val accuracy : 0.23444000000000004, best val accuracy : 0.2368
INFO flwr 2023-08-19 20:57:16,732 | common.py:35 | Avg. local train loss : 18.611823400855062, train acc : 0.3751222222222222
INFO flwr 2023-08-19 20:57:19,445 | server.py:116 | fit progress: (23, 4.050772912597656, {'server_test_acc': 0.2254}, 2063.0918368441053)
INFO flwr 2023-08-19 20:57:19,445 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-19 20:57:24,771 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3041430)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:57:59,718 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3041429)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:57:59,878 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3041430)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3041429)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3041432)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3041431)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3041433)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3041427)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3041425)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3041424)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3041432)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3041425)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3041431)[0m malloc_consolidate(): invalid chunk size
E0819 20:58:00.667297018 2835634 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0819 20:58:00.667439814 2835634 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3041433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3041424)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3041427)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:58:48,415 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:58:48,416 | fed_df.py:547 | Average fusion training loss : 0.0024530219037551433, val accuracy : 0.23444000000000004, best val accuracy : 0.2372
INFO flwr 2023-08-19 20:58:48,418 | common.py:35 | Avg. local train loss : 18.81103365421295, train acc : 0.36255
INFO flwr 2023-08-19 20:58:51,077 | server.py:116 | fit progress: (24, 4.002140869140625, {'server_test_acc': 0.2427}, 2154.7236551139504)
INFO flwr 2023-08-19 20:58:51,077 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-19 20:58:56,531 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3174230)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:59:30,202 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-19 20:59:30,320 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-19 20:59:30,416 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3174230)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3174234)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3174235)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3174239)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3174240)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3174237)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3174236)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3174238)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3174235)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3174234)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3174240)[0m double free or corruption (fasttop)
E0819 20:59:31.338444038 3094406 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0819 20:59:31.338571819 3094406 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0819 20:59:31.338592648 3094406 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3174239)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174237)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3174238)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:00:18,293 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:00:18,293 | fed_df.py:547 | Average fusion training loss : 0.0022228591181337833, val accuracy : 0.2412, best val accuracy : 0.2436
INFO flwr 2023-08-19 21:00:18,294 | common.py:35 | Avg. local train loss : 18.625782895088197, train acc : 0.37627777777777777
INFO flwr 2023-08-19 21:00:20,935 | server.py:116 | fit progress: (25, 4.060255590820312, {'server_test_acc': 0.2351}, 2244.58169489773)
INFO flwr 2023-08-19 21:00:20,935 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-19 21:00:26,270 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:01:00,057 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-19 21:01:00,222 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3306807)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3306808)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3306809)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3306802)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3306800)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3306805)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3306804)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3306806)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3306805)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3306804)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3306807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3306800)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3306808)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3306806)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3306809)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3306802)[0m double free or corruption (fasttop)
E0819 21:01:02.784188299 3227039 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 21:01:48,288 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:01:48,289 | fed_df.py:547 | Average fusion training loss : 0.0008067097290768288, val accuracy : 0.23796, best val accuracy : 0.2412
INFO flwr 2023-08-19 21:01:48,290 | common.py:35 | Avg. local train loss : 18.644704180955888, train acc : 0.3732444444444445
INFO flwr 2023-08-19 21:01:50,944 | server.py:116 | fit progress: (26, 4.078501391601563, {'server_test_acc': 0.242}, 2334.590314217843)
INFO flwr 2023-08-19 21:01:50,944 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-19 21:01:56,385 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:02:30,018 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-19 21:02:30,177 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3439673)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3439674)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3439679)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3439676)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3439677)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3439675)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3439503)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3439678)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3439677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3439675)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3439503)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3439678)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3439673)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3439679)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3439674)[0m malloc_consolidate(): invalid chunk size
E0819 21:02:32.244383397 3362592 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3439676)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 21:03:18,898 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:03:18,898 | fed_df.py:547 | Average fusion training loss : 0.0022276779792737215, val accuracy : 0.24276, best val accuracy : 0.2474
INFO flwr 2023-08-19 21:03:18,900 | common.py:35 | Avg. local train loss : 18.55079175829887, train acc : 0.38068888888888885
INFO flwr 2023-08-19 21:03:21,542 | server.py:116 | fit progress: (27, 4.033626342773437, {'server_test_acc': 0.2459}, 2425.188255606685)
INFO flwr 2023-08-19 21:03:21,542 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-19 21:03:26,999 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3601301)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 21:04:00,987 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-19 21:04:01,146 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3601301)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3601304)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3601303)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3601311)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3601297)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3601300)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3601305)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3601307)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3601304)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3601311)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3601305)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3601300)[0m malloc_consolidate(): invalid chunk size
E0819 21:04:02.528037753 3654068 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3601297)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3601307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3601303)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 21:04:49,196 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:04:49,197 | fed_df.py:547 | Average fusion training loss : 0.0023518929103156553, val accuracy : 0.2394, best val accuracy : 0.2428
INFO flwr 2023-08-19 21:04:49,198 | common.py:35 | Avg. local train loss : 18.53384588062763, train acc : 0.3834222222222223
INFO flwr 2023-08-19 21:04:51,866 | server.py:116 | fit progress: (28, 4.032540625, {'server_test_acc': 0.2441}, 2515.5121652819216)
INFO flwr 2023-08-19 21:04:51,866 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-19 21:04:57,261 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3733461)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 21:05:31,497 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-19 21:05:31,656 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3733455)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3733456)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3733460)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3733461)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3733459)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3733462)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3733463)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3733458)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3733463)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3733459)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3733455)[0m malloc_consolidate(): invalid chunk size
E0819 21:05:33.038446327 3654476 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3733458)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3733462)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3733460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3733456)[0m malloc_consolidate(): invalid chunk size
E0819 21:05:54.734164326 3821228 chttp2_transport.cc:1079]             ipv4:145.136.62.59:42046: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 21:06:19,712 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:06:19,713 | fed_df.py:547 | Average fusion training loss : 0.0013008128744550049, val accuracy : 0.25207999999999997, best val accuracy : 0.2554
INFO flwr 2023-08-19 21:06:19,714 | common.py:35 | Avg. local train loss : 18.609173408150674, train acc : 0.3767777777777777
INFO flwr 2023-08-19 21:06:22,382 | server.py:116 | fit progress: (29, 4.0281693359375, {'server_test_acc': 0.2526}, 2606.0287579717115)
INFO flwr 2023-08-19 21:06:22,382 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-19 21:06:27,824 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:07:01,791 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-19 21:07:01,913 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-19 21:07:02,022 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3866551)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3866669)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3866627)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3866668)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3866666)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3866671)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3866670)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3866667)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3866669)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3866670)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3866667)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3866627)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3866671)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3866551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3866668)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3866666)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:07:50,401 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:07:50,401 | fed_df.py:547 | Average fusion training loss : 0.0013307690414367244, val accuracy : 0.25632, best val accuracy : 0.2616
INFO flwr 2023-08-19 21:07:50,403 | common.py:35 | Avg. local train loss : 18.34049706459045, train acc : 0.40430555555555553
INFO flwr 2023-08-19 21:07:53,061 | server.py:116 | fit progress: (30, 4.071918029785156, {'server_test_acc': 0.2558}, 2696.707547579892)
INFO flwr 2023-08-19 21:07:53,061 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-19 21:07:53,061 | server.py:144 | FL finished in 2696.707895118743
INFO flwr 2023-08-19 21:07:53,062 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-19 21:07:53,063 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-19 21:07:53,063 | app.py:204 | app_fit: losses_centralized [(0, 4.651723132324219), (1, 4.473614892578125), (2, 4.396752697753906), (3, 4.49777578125), (4, 4.530605737304687), (5, 4.397219079589844), (6, 4.324489392089844), (7, 4.25882744140625), (8, 4.292693566894531), (9, 4.211205493164062), (10, 4.189240759277344), (11, 4.10127373046875), (12, 4.072927758789063), (13, 4.076659765625), (14, 4.071371435546875), (15, 4.088613488769531), (16, 4.104623083496094), (17, 4.101542907714844), (18, 4.072843713378906), (19, 4.064038732910157), (20, 4.097873852539062), (21, 4.092846545410156), (22, 4.071796435546875), (23, 4.050772912597656), (24, 4.002140869140625), (25, 4.060255590820312), (26, 4.078501391601563), (27, 4.033626342773437), (28, 4.032540625), (29, 4.0281693359375), (30, 4.071918029785156)]
INFO flwr 2023-08-19 21:07:53,063 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0095), (1, 0.0741), (2, 0.089), (3, 0.0862), (4, 0.0897), (5, 0.1034), (6, 0.1062), (7, 0.1204), (8, 0.1302), (9, 0.1396), (10, 0.1544), (11, 0.1641), (12, 0.1867), (13, 0.1789), (14, 0.1948), (15, 0.2031), (16, 0.1967), (17, 0.1995), (18, 0.2067), (19, 0.2035), (20, 0.2191), (21, 0.2272), (22, 0.2252), (23, 0.2254), (24, 0.2427), (25, 0.2351), (26, 0.242), (27, 0.2459), (28, 0.2441), (29, 0.2526), (30, 0.2558)]}
double free or corruption (fasttop)
srun: error: gcn59: task 0: Aborted
srun: Terminating StepId=3423720.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3423720
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:56:14
CPU Efficiency: 13.34% of 14:31:12 core-walltime
Job Wall-clock time: 00:48:24
Memory Utilized: 55.21 GB
Memory Efficiency: 46.01% of 120.00 GB
