-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:25000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar100
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=25000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3423718/1692469239_373396768', seed=84, img_per_thread=1388)
will save 25000 patches in /scratch-local/sunnys.3423718/1692469239_373396768/single_img_crops/crops
25000 took 0.31min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-19 20:21:15,784 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-19 20:21:15,784 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3423718/1692469239_373396768/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3423718/1692469239_373396768/cifar-100-python.tar.gz to /scratch-local/sunnys.3423718/1692469239_373396768
Generating unified cifar100 dataset
Class histogram for 0-th partition (alpha=1.0, 100 classes): [ 29  16  30 102   3  22  45   3   3   8   0  48  24  15   6   3  16  24
   7  31  42  37  15  10  71  21   7  12  12   3  53  26  71  22  34  53
  10  40  24  25  13  56  78   3  23  47  18  99   1  53  40   6  35  30
  43  49   0   7  17  14  26  23   3  21  17  26   2  63  26  11   0  13
   0  31   1  18  34  50  12   8   4   3  10  45  22  11   0  12 105  62
  26  26  24  22  30   1  18  27  12   0]
INFO flwr 2023-08-19 20:21:34,929 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-19 20:21:38,724	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-19 20:21:40,743 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.58': 1.0, 'CPU': 18.0, 'accelerator_type:A100': 1.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'memory': 103079215104.0}
INFO flwr 2023-08-19 20:21:40,743 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-19 20:21:40,743 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-19 20:21:40,743 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-19 20:21:50,004 | server.py:91 | initial parameters (loss, other metrics): 4.651723132324219, {'server_test_acc': 0.0095}
INFO flwr 2023-08-19 20:21:50,004 | server.py:101 | FL starting
DEBUG flwr 2023-08-19 20:21:54,760 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3927914)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:22:32,992 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-19 20:22:33,108 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-19 20:22:33,197 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3927912)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3927915)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3927917)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3927913)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3927918)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3927910)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3927916)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3927914)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3927917)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3927913)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927916)[0m malloc_consolidate(): invalid chunk size
E0819 20:22:33.999277852 3978867 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0819 20:22:33.999486881 3978867 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=3927910)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3927918)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3927915)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:23:17,459 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:23:17,459 | fed_df.py:547 | Average fusion training loss : 0.35947441339492797, val accuracy : 0.05664, best val accuracy : 0.0614
INFO flwr 2023-08-19 20:23:17,460 | common.py:35 | Avg. local train loss : 20.84947004318237, train acc : 0.14462777777777777
INFO flwr 2023-08-19 20:23:20,024 | server.py:116 | fit progress: (1, 4.574655798339844, {'server_test_acc': 0.0589}, 90.01981514226645)
INFO flwr 2023-08-19 20:23:20,025 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-19 20:23:24,784 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4060599)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:23:59,452 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-19 20:23:59,599 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4060599)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4060603)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4060600)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4060602)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4060607)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4060608)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4060604)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4060609)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4060600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060603)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060609)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4060604)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4060608)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4060607)[0m malloc_consolidate(): invalid chunk size
E0819 20:24:02.109683634 4112255 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-19 20:24:44,996 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:24:44,996 | fed_df.py:547 | Average fusion training loss : 0.30322282820940016, val accuracy : 0.06512, best val accuracy : 0.0718
INFO flwr 2023-08-19 20:24:44,997 | common.py:35 | Avg. local train loss : 20.55542378127575, train acc : 0.16814444444444443
INFO flwr 2023-08-19 20:24:47,581 | server.py:116 | fit progress: (2, 4.4662224609375, {'server_test_acc': 0.0742}, 177.5762751949951)
INFO flwr 2023-08-19 20:24:47,581 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-19 20:24:52,577 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4193349)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:25:26,365 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-19 20:25:26,514 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4193349)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4193350)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4193351)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4193355)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4193354)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4193352)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4193353)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4193356)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4193350)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4193351)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4193355)[0m double free or corruption (fasttop)
E0819 20:25:27.951939190 4113468 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=4193352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193354)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193356)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4193353)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:26:12,814 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:26:12,814 | fed_df.py:547 | Average fusion training loss : 0.3704844017028809, val accuracy : 0.08216, best val accuracy : 0.0914
INFO flwr 2023-08-19 20:26:12,815 | common.py:35 | Avg. local train loss : 20.209170743823048, train acc : 0.1949611111111111
INFO flwr 2023-08-19 20:26:15,459 | server.py:116 | fit progress: (3, 4.429264526367188, {'server_test_acc': 0.0882}, 265.4540204340592)
INFO flwr 2023-08-19 20:26:15,459 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-19 20:26:20,487 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=132703)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:26:54,285 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-19 20:26:54,434 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=132704)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=132699)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=132702)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=132706)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=132707)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=132705)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=132701)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=132703)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=132705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=132706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=132701)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=132707)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=132704)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=132699)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=132702)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:27:40,695 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:27:40,695 | fed_df.py:547 | Average fusion training loss : 0.2882786707282066, val accuracy : 0.07836000000000001, best val accuracy : 0.0824
INFO flwr 2023-08-19 20:27:40,696 | common.py:35 | Avg. local train loss : 20.126674002408983, train acc : 0.20095000000000002
INFO flwr 2023-08-19 20:27:43,344 | server.py:116 | fit progress: (4, 4.547315185546875, {'server_test_acc': 0.0776}, 353.33909824024886)
INFO flwr 2023-08-19 20:27:43,344 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-19 20:27:48,315 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:28:21,644 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=265393)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:28:21,764 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-19 20:28:21,853 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=265393)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=265391)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=265394)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=265396)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=265398)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=265397)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=265399)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=265400)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=265398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=265399)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=265394)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=265396)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=265397)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=265391)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=265400)[0m malloc_consolidate(): invalid chunk size
E0819 20:28:24.750687577  315984 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-19 20:29:09,278 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:29:09,278 | fed_df.py:547 | Average fusion training loss : 0.2765411605834961, val accuracy : 0.09315999999999999, best val accuracy : 0.099
INFO flwr 2023-08-19 20:29:09,279 | common.py:35 | Avg. local train loss : 20.031657806038854, train acc : 0.2089833333333333
INFO flwr 2023-08-19 20:29:11,945 | server.py:116 | fit progress: (5, 4.4384865478515625, {'server_test_acc': 0.0971}, 441.94049187237397)
INFO flwr 2023-08-19 20:29:11,945 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-19 20:29:17,023 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=398047)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:29:50,958 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-19 20:29:51,116 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=398045)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=398047)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=398043)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=398049)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=398050)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=398048)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=398042)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=398046)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=398050)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=398048)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=398042)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398049)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=398046)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=398045)[0m double free or corruption (fasttop)
E0819 20:29:53.501091668  449031 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-19 20:30:37,568 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:30:37,568 | fed_df.py:547 | Average fusion training loss : 0.22011614960432052, val accuracy : 0.08108000000000001, best val accuracy : 0.0846
INFO flwr 2023-08-19 20:30:37,569 | common.py:35 | Avg. local train loss : 19.953862315416337, train acc : 0.22483333333333333
E0819 20:30:39.134120768  449377 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-19 20:30:40,260 | server.py:116 | fit progress: (6, 4.378839562988281, {'server_test_acc': 0.084}, 530.2557490142062)
INFO flwr 2023-08-19 20:30:40,261 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-19 20:30:45,379 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=530739)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:31:18,972 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-19 20:31:19,125 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=530744)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=530739)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=530745)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=530742)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=530746)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=530744)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=530743)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=530748)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=530747)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=530745)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=530742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=530746)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=530748)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=530747)[0m malloc_consolidate(): invalid chunk size
E0819 20:31:20.449498076  524414 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=530743)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-19 20:32:06,118 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:32:06,118 | fed_df.py:547 | Average fusion training loss : 0.24496033579111098, val accuracy : 0.09884000000000001, best val accuracy : 0.1036
INFO flwr 2023-08-19 20:32:06,119 | common.py:35 | Avg. local train loss : 19.92325237691402, train acc : 0.22397222222222224
INFO flwr 2023-08-19 20:32:08,787 | server.py:116 | fit progress: (7, 4.380016931152344, {'server_test_acc': 0.0977}, 618.7827248689719)
INFO flwr 2023-08-19 20:32:08,788 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-19 20:32:13,949 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:32:47,676 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=662786)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:32:47,827 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=662784)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=662785)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=662749)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=662783)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=662714)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=662854)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=662786)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=662855)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=662784)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=662785)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662714)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662783)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=662855)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=662749)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662854)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:33:32,602 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:33:32,603 | fed_df.py:547 | Average fusion training loss : 0.23404743403196335, val accuracy : 0.09564, best val accuracy : 0.1024
INFO flwr 2023-08-19 20:33:32,604 | common.py:35 | Avg. local train loss : 19.877344977855685, train acc : 0.23382777777777775
INFO flwr 2023-08-19 20:33:35,244 | server.py:116 | fit progress: (8, 4.416641589355469, {'server_test_acc': 0.103}, 705.239514304325)
INFO flwr 2023-08-19 20:33:35,244 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-19 20:33:40,569 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:34:14,188 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-19 20:34:14,356 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=793709)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=793711)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=793706)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=793707)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=793712)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=793710)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=793708)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=793705)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=793709)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793712)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=793705)[0m malloc_consolidate(): invalid chunk size
E0819 20:34:16.933175242  841592 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-19 20:35:00,345 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:35:00,345 | fed_df.py:547 | Average fusion training loss : 0.2029783124923706, val accuracy : 0.10647999999999999, best val accuracy : 0.1084
INFO flwr 2023-08-19 20:35:00,346 | common.py:35 | Avg. local train loss : 19.831504783034326, train acc : 0.2347333333333333
INFO flwr 2023-08-19 20:35:03,010 | server.py:116 | fit progress: (9, 4.384504431152344, {'server_test_acc': 0.1094}, 793.0054094810039)
INFO flwr 2023-08-19 20:35:03,010 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-19 20:35:08,247 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=941832)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=941833)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:35:41,971 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-19 20:35:42,092 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-19 20:35:42,184 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=941832)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=941833)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=941723)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=941798)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=941771)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=941721)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=941834)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=941734)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=941834)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=941771)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=941721)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=941734)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=941723)[0m malloc_consolidate(): invalid chunk size
E0819 20:35:43.537690238  843389 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=941798)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:36:30,380 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:36:30,380 | fed_df.py:547 | Average fusion training loss : 0.20408866798877717, val accuracy : 0.11159999999999999, best val accuracy : 0.1196
INFO flwr 2023-08-19 20:36:30,382 | common.py:35 | Avg. local train loss : 19.891663211584092, train acc : 0.2339111111111111
INFO flwr 2023-08-19 20:36:33,151 | server.py:116 | fit progress: (10, 4.39159453125, {'server_test_acc': 0.1267}, 883.146321291104)
INFO flwr 2023-08-19 20:36:33,151 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-19 20:36:38,394 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:37:11,675 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-19 20:37:11,828 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1087133)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1087132)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1087203)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1087131)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1087202)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1087204)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1087205)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1087201)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1087132)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1087204)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087203)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087201)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087205)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087202)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=1087133)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087131)[0m corrupted size vs. prev_size in fastbins
E0819 20:37:14.362835163  992351 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-19 20:37:59,716 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:37:59,717 | fed_df.py:547 | Average fusion training loss : 0.05150445230305195, val accuracy : 0.11816, best val accuracy : 0.1232
INFO flwr 2023-08-19 20:37:59,718 | common.py:35 | Avg. local train loss : 19.88377705514431, train acc : 0.23187222222222223
INFO flwr 2023-08-19 20:38:02,392 | server.py:116 | fit progress: (11, 4.323479919433594, {'server_test_acc': 0.1256}, 972.3870300222188)
INFO flwr 2023-08-19 20:38:02,392 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-19 20:38:07,874 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1220533)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:38:41,060 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-19 20:38:41,211 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1220533)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1220532)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1220464)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1220536)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1220534)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1220537)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1220535)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1220555)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1220464)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220536)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220534)[0m double free or corruption (fasttop)
E0819 20:38:42.041073809 1262336 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=1220532)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220555)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1220537)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220535)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:39:30,026 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:39:30,026 | fed_df.py:547 | Average fusion training loss : 0.053550421126186847, val accuracy : 0.13184, best val accuracy : 0.1366
INFO flwr 2023-08-19 20:39:30,027 | common.py:35 | Avg. local train loss : 19.77038893401623, train acc : 0.2447777777777778
INFO flwr 2023-08-19 20:39:32,697 | server.py:116 | fit progress: (12, 4.28899853515625, {'server_test_acc': 0.1351}, 1062.69232870033)
INFO flwr 2023-08-19 20:39:32,697 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-19 20:39:38,063 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1353232)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:40:11,062 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-19 20:40:11,211 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1353232)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1353308)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1353306)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1353307)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1353230)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1353238)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1353237)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1353236)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1353237)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353230)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1353307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353236)[0m malloc_consolidate(): invalid chunk size
E0819 20:40:15.074722242 1401103 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-19 20:40:58,918 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:40:58,918 | fed_df.py:547 | Average fusion training loss : 0.059432377867400646, val accuracy : 0.13748, best val accuracy : 0.1422
INFO flwr 2023-08-19 20:40:58,919 | common.py:35 | Avg. local train loss : 19.539810609817504, train acc : 0.26476666666666665
INFO flwr 2023-08-19 20:41:01,587 | server.py:116 | fit progress: (13, 4.274971801757813, {'server_test_acc': 0.1381}, 1151.5829752362333)
INFO flwr 2023-08-19 20:41:01,588 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-19 20:41:06,890 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:41:39,719 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-19 20:41:39,872 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1485219)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1485289)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1485290)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1485288)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1485360)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1485291)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1485361)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1485359)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1485219)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1485289)[0m double free or corruption (fasttop)
E0819 20:41:41.023516979 1527065 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1485360)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1485359)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1485290)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1485361)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1485291)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:42:27,504 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:42:27,504 | fed_df.py:547 | Average fusion training loss : 0.05986568710952997, val accuracy : 0.14328000000000002, best val accuracy : 0.148
INFO flwr 2023-08-19 20:42:27,505 | common.py:35 | Avg. local train loss : 19.586566364765165, train acc : 0.26570555555555553
INFO flwr 2023-08-19 20:42:30,167 | server.py:116 | fit progress: (14, 4.276031689453125, {'server_test_acc': 0.1523}, 1240.1628864272498)
INFO flwr 2023-08-19 20:42:30,168 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-19 20:42:35,562 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1616980)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:43:08,271 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-19 20:43:08,396 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-19 20:43:08,491 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1616980)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1617119)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1617051)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1617124)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1617120)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1617121)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1617123)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1617122)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1617051)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1617120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1617122)[0m double free or corruption (fasttop)
E0819 20:43:09.770511930 1528503 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1617124)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1617119)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1617123)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1617121)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:43:54,421 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:43:54,421 | fed_df.py:547 | Average fusion training loss : 0.09455455587804318, val accuracy : 0.14596, best val accuracy : 0.1518
INFO flwr 2023-08-19 20:43:54,422 | common.py:35 | Avg. local train loss : 19.63413442373276, train acc : 0.2607777777777778
INFO flwr 2023-08-19 20:43:57,072 | server.py:116 | fit progress: (15, 4.2914868774414066, {'server_test_acc': 0.154}, 1327.0678029181436)
INFO flwr 2023-08-19 20:43:57,073 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-19 20:44:02,481 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:44:34,294 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1747951)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:44:34,454 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1747951)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1747948)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1747950)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1748021)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1748020)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1747947)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1748019)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1747949)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1747948)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1748019)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1747949)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1747950)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1748020)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1748021)[0m double free or corruption (fasttop)
E0819 20:44:35.953008541 1661020 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1747947)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:45:22,512 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:45:22,512 | fed_df.py:547 | Average fusion training loss : 0.050366378419101236, val accuracy : 0.1446, best val accuracy : 0.1468
INFO flwr 2023-08-19 20:45:22,513 | common.py:35 | Avg. local train loss : 19.419897973537445, train acc : 0.2816722222222222
INFO flwr 2023-08-19 20:45:25,187 | server.py:116 | fit progress: (16, 4.271333410644531, {'server_test_acc': 0.1448}, 1415.1826206962578)
INFO flwr 2023-08-19 20:45:25,187 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-19 20:45:30,491 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:46:02,275 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-19 20:46:02,437 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1879624)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1879622)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1879693)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1879625)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1879694)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1879696)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1879695)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1879623)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1879622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1879696)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1879695)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1879693)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1879694)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1879625)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1879623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1879624)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:46:50,560 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:46:50,561 | fed_df.py:547 | Average fusion training loss : 0.0795062640607357, val accuracy : 0.15655999999999998, best val accuracy : 0.1594
INFO flwr 2023-08-19 20:46:50,562 | common.py:35 | Avg. local train loss : 19.495871037244793, train acc : 0.2762055555555555
INFO flwr 2023-08-19 20:46:53,281 | server.py:116 | fit progress: (17, 4.3100962036132815, {'server_test_acc': 0.164}, 1503.2768555921502)
INFO flwr 2023-08-19 20:46:53,282 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-19 20:46:58,634 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2008361)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:47:30,380 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-19 20:47:30,540 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2008361)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2008434)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2008504)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2008503)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2008433)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2008505)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2008435)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2008432)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2008434)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2008435)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008504)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008432)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2008433)[0m double free or corruption (fasttop)
E0819 20:47:38.245504382 1789545 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-19 20:48:19,926 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:48:19,927 | fed_df.py:547 | Average fusion training loss : 0.07504795943200589, val accuracy : 0.16184, best val accuracy : 0.1674
INFO flwr 2023-08-19 20:48:19,928 | common.py:35 | Avg. local train loss : 19.42317381501198, train acc : 0.2815388888888889
INFO flwr 2023-08-19 20:48:22,639 | server.py:116 | fit progress: (18, 4.286568579101562, {'server_test_acc': 0.1631}, 1592.634627492167)
INFO flwr 2023-08-19 20:48:22,639 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-19 20:48:28,069 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:48:59,611 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-19 20:48:59,772 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2141352)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2141425)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2141353)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2141426)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2141356)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2141354)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2141355)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2141424)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2141352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141425)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141355)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141353)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141356)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141424)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141354)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:49:45,995 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:49:45,996 | fed_df.py:547 | Average fusion training loss : 0.06852553859353065, val accuracy : 0.15199999999999997, best val accuracy : 0.1554
INFO flwr 2023-08-19 20:49:45,997 | common.py:35 | Avg. local train loss : 19.54166579246521, train acc : 0.27399444444444443
INFO flwr 2023-08-19 20:49:48,688 | server.py:116 | fit progress: (19, 4.276924597167969, {'server_test_acc': 0.1563}, 1678.6838837130927)
INFO flwr 2023-08-19 20:49:48,689 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-19 20:49:54,011 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 20:50:25,684 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-19 20:50:25,806 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-19 20:50:25,903 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2273324)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2273412)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2273327)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2273421)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2273322)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2273325)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2273427)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2273413)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2273413)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2273322)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2273327)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2273325)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2273324)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2273412)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2273421)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2273427)[0m double free or corruption (fasttop)
E0819 20:50:28.612633879 2058189 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:51:12,568 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:51:12,569 | fed_df.py:547 | Average fusion training loss : 0.0481331085562706, val accuracy : 0.17268, best val accuracy : 0.1762
INFO flwr 2023-08-19 20:51:12,570 | common.py:35 | Avg. local train loss : 19.461699715256692, train acc : 0.2820333333333333
INFO flwr 2023-08-19 20:51:15,250 | server.py:116 | fit progress: (20, 4.258435266113281, {'server_test_acc': 0.1748}, 1765.245662308298)
INFO flwr 2023-08-19 20:51:15,250 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-19 20:51:20,612 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2426790)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:51:52,386 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-19 20:51:52,541 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2426790)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2426903)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2426788)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2426905)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2426791)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2426904)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2426792)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2426906)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2426791)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426792)[0m double free or corruption (fasttop)
E0819 20:51:53.797897756 2325265 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2426903)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2426905)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426904)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426906)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426788)[0m double free or corruption (fasttop)
E0819 20:52:21.685736462 2520126 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:52:41,220 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:52:41,220 | fed_df.py:547 | Average fusion training loss : 0.02205323373526335, val accuracy : 0.16792, best val accuracy : 0.1702
INFO flwr 2023-08-19 20:52:41,221 | common.py:35 | Avg. local train loss : 19.335989382863044, train acc : 0.2951111111111111
INFO flwr 2023-08-19 20:52:43,872 | server.py:116 | fit progress: (21, 4.236511657714844, {'server_test_acc': 0.1712}, 1853.867163658142)
INFO flwr 2023-08-19 20:52:43,872 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-19 20:52:49,450 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2563257)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 20:53:21,449 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2563329)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 20:53:21,612 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2563257)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2563260)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2563331)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2563261)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2563258)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2563259)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2563329)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2563330)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2563330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2563261)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2563258)[0m malloc_consolidate(): invalid chunk size
E0819 20:53:22.741649618 2521481 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2563260)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2563331)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2563259)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:54:08,562 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:54:08,562 | fed_df.py:547 | Average fusion training loss : 0.05582698575407267, val accuracy : 0.17332, best val accuracy : 0.1766
INFO flwr 2023-08-19 20:54:08,563 | common.py:35 | Avg. local train loss : 19.239370995759963, train acc : 0.30474444444444443
INFO flwr 2023-08-19 20:54:11,243 | server.py:116 | fit progress: (22, 4.263219873046875, {'server_test_acc': 0.1762}, 1941.2384717743844)
INFO flwr 2023-08-19 20:54:11,243 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-19 20:54:16,680 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2694927)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:54:48,507 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-19 20:54:48,667 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2694927)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2694929)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2694939)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2694940)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2694941)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2694942)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2694943)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2694930)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2694930)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2694940)[0m double free or corruption (fasttop)
E0819 20:54:49.772722237 2737793 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2694939)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2694942)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2694929)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2694941)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2694943)[0m double free or corruption (fasttop)
E0819 20:54:51.145805564 2738942 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 20:55:41,962 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:55:41,963 | fed_df.py:547 | Average fusion training loss : 0.03361972714960575, val accuracy : 0.18232, best val accuracy : 0.1894
INFO flwr 2023-08-19 20:55:41,964 | common.py:35 | Avg. local train loss : 19.064466497302053, train acc : 0.32234444444444443
INFO flwr 2023-08-19 20:55:44,670 | server.py:116 | fit progress: (23, 4.2369932983398435, {'server_test_acc': 0.1838}, 2034.6656063380651)
INFO flwr 2023-08-19 20:55:44,670 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-19 20:55:49,992 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2831125)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2831197)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:56:21,466 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-19 20:56:21,628 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2831125)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2831198)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2831199)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2831127)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2831197)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2831268)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2831196)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2831267)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2831267)[0m malloc_consolidate(): invalid chunk size
E0819 20:56:22.083074211 2870084 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2831198)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2831196)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2831199)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2831127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2831268)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:57:11,029 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:57:11,029 | fed_df.py:547 | Average fusion training loss : 0.04990586011856794, val accuracy : 0.19327999999999998, best val accuracy : 0.1972
INFO flwr 2023-08-19 20:57:11,031 | common.py:35 | Avg. local train loss : 19.26738801300526, train acc : 0.30748333333333333
INFO flwr 2023-08-19 20:57:13,720 | server.py:116 | fit progress: (24, 4.208879162597656, {'server_test_acc': 0.1948}, 2123.715767205227)
INFO flwr 2023-08-19 20:57:13,721 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-19 20:57:19,302 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2964159)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:57:50,873 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2964158)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:57:50,995 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-19 20:57:51,089 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2964156)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2964159)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2964161)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2964158)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2964160)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2964153)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2964157)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2964155)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2964156)[0m malloc_consolidate(): invalid chunk size
E0819 20:57:51.910940421 2870152 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2964161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2964155)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2964153)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2964160)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 20:58:39,246 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 20:58:39,247 | fed_df.py:547 | Average fusion training loss : 0.03523954950179905, val accuracy : 0.19424000000000002, best val accuracy : 0.197
INFO flwr 2023-08-19 20:58:39,248 | common.py:35 | Avg. local train loss : 19.06718552708626, train acc : 0.3232222222222223
INFO flwr 2023-08-19 20:58:41,938 | server.py:116 | fit progress: (25, 4.213754309082031, {'server_test_acc': 0.1998}, 2211.933041033335)
INFO flwr 2023-08-19 20:58:41,938 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-19 20:58:47,406 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3095521)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 20:59:18,947 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-19 20:59:19,107 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3095516)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3095521)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3095522)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3095527)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3095525)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3095520)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3095528)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3095526)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3095528)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3095520)[0m double free or corruption (fasttop)
E0819 20:59:20.241487442 3135917 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3095525)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3095522)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3095516)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3095527)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3095526)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 21:00:11,027 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:00:11,028 | fed_df.py:547 | Average fusion training loss : 0.02930040533281863, val accuracy : 0.19336, best val accuracy : 0.1956
INFO flwr 2023-08-19 21:00:11,029 | common.py:35 | Avg. local train loss : 19.131049996614454, train acc : 0.3188388888888889
INFO flwr 2023-08-19 21:00:13,716 | server.py:116 | fit progress: (26, 4.238377734375, {'server_test_acc': 0.1951}, 2303.7112831510603)
INFO flwr 2023-08-19 21:00:13,716 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-19 21:00:19,144 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:00:50,567 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3230235)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:00:50,733 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3230235)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3230232)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3230233)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3230305)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3230230)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3230306)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3230304)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3230234)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3230232)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3230306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3230304)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3230230)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3230233)[0m malloc_consolidate(): invalid chunk size
E0819 21:00:52.825619864 3271949 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3230305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3230234)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:01:37,769 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:01:37,769 | fed_df.py:547 | Average fusion training loss : 0.026153718881309032, val accuracy : 0.1996, best val accuracy : 0.202
INFO flwr 2023-08-19 21:01:37,771 | common.py:35 | Avg. local train loss : 19.0109549164772, train acc : 0.32645
INFO flwr 2023-08-19 21:01:40,544 | server.py:116 | fit progress: (27, 4.208655126953125, {'server_test_acc': 0.2009}, 2390.539945814293)
INFO flwr 2023-08-19 21:01:40,545 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-19 21:01:46,071 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:02:17,490 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-19 21:02:17,649 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3360253)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3360254)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3360255)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3360324)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3360256)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3360326)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3360325)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3360252)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3360254)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3360253)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3360255)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3360256)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3360326)[0m malloc_consolidate(): invalid chunk size
E0819 21:02:18.950417861 3272085 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3360252)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3360324)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3360325)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:03:04,209 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:03:04,210 | fed_df.py:547 | Average fusion training loss : 0.025609027924016117, val accuracy : 0.20163999999999999, best val accuracy : 0.2036
INFO flwr 2023-08-19 21:03:04,211 | common.py:35 | Avg. local train loss : 18.99144152402878, train acc : 0.33169444444444446
INFO flwr 2023-08-19 21:03:06,908 | server.py:116 | fit progress: (28, 4.2020466430664065, {'server_test_acc': 0.2017}, 2476.9030341571197)
INFO flwr 2023-08-19 21:03:06,908 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-19 21:03:12,237 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:03:44,159 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-19 21:03:44,320 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3490840)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3490837)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3490842)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3490844)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3490839)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3490841)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3490843)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3490838)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3490837)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3490844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3490840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3490841)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3490839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3490838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3490842)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3490843)[0m corrupted size vs. prev_size in fastbins
E0819 21:03:47.924156736 3401849 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 21:04:33,119 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:04:33,119 | fed_df.py:547 | Average fusion training loss : 0.02885146114975214, val accuracy : 0.19663999999999998, best val accuracy : 0.1998
INFO flwr 2023-08-19 21:04:33,120 | common.py:35 | Avg. local train loss : 19.068802231550215, train acc : 0.3188888888888889
INFO flwr 2023-08-19 21:04:35,952 | server.py:116 | fit progress: (29, 4.177611474609375, {'server_test_acc': 0.1971}, 2565.947540627327)
INFO flwr 2023-08-19 21:04:35,952 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-19 21:04:41,260 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 21:05:13,110 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3623532)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 21:05:13,232 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-19 21:05:13,329 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3623454)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3623454)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3623532)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3623556)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3623567)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3623557)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3623568)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3623566)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3623569)[0m Fitting Client 9
E0819 21:05:14.028829723 3665877 chttp2_transport.cc:1079]             ipv4:145.136.62.58:63972: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3623566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3623557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3623569)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3623567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3623568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3623556)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 21:06:02,495 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 21:06:02,496 | fed_df.py:547 | Average fusion training loss : 0.03640079066902399, val accuracy : 0.21755999999999998, best val accuracy : 0.2214
INFO flwr 2023-08-19 21:06:02,497 | common.py:35 | Avg. local train loss : 18.79176556766033, train acc : 0.3500777777777778
INFO flwr 2023-08-19 21:06:05,363 | server.py:116 | fit progress: (30, 4.191727783203125, {'server_test_acc': 0.217}, 2655.3583298581652)
INFO flwr 2023-08-19 21:06:05,363 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-19 21:06:05,363 | server.py:144 | FL finished in 2655.3586868392304
INFO flwr 2023-08-19 21:06:05,363 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-19 21:06:05,365 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-19 21:06:05,365 | app.py:204 | app_fit: losses_centralized [(0, 4.651723132324219), (1, 4.574655798339844), (2, 4.4662224609375), (3, 4.429264526367188), (4, 4.547315185546875), (5, 4.4384865478515625), (6, 4.378839562988281), (7, 4.380016931152344), (8, 4.416641589355469), (9, 4.384504431152344), (10, 4.39159453125), (11, 4.323479919433594), (12, 4.28899853515625), (13, 4.274971801757813), (14, 4.276031689453125), (15, 4.2914868774414066), (16, 4.271333410644531), (17, 4.3100962036132815), (18, 4.286568579101562), (19, 4.276924597167969), (20, 4.258435266113281), (21, 4.236511657714844), (22, 4.263219873046875), (23, 4.2369932983398435), (24, 4.208879162597656), (25, 4.213754309082031), (26, 4.238377734375), (27, 4.208655126953125), (28, 4.2020466430664065), (29, 4.177611474609375), (30, 4.191727783203125)]
INFO flwr 2023-08-19 21:06:05,365 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0095), (1, 0.0589), (2, 0.0742), (3, 0.0882), (4, 0.0776), (5, 0.0971), (6, 0.084), (7, 0.0977), (8, 0.103), (9, 0.1094), (10, 0.1267), (11, 0.1256), (12, 0.1351), (13, 0.1381), (14, 0.1523), (15, 0.154), (16, 0.1448), (17, 0.164), (18, 0.1631), (19, 0.1563), (20, 0.1748), (21, 0.1712), (22, 0.1762), (23, 0.1838), (24, 0.1948), (25, 0.1998), (26, 0.1951), (27, 0.2009), (28, 0.2017), (29, 0.1971), (30, 0.217)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn58: task 0: Aborted
srun: Terminating StepId=3423718.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3423718
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:52:23
CPU Efficiency: 13.38% of 13:59:42 core-walltime
Job Wall-clock time: 00:46:39
Memory Utilized: 52.96 GB
Memory Efficiency: 44.14% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
