-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:100000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar100
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:100
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3347612/1692127631_843672156', seed=84, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3347612/1692127631_843672156/single_img_crops/crops
100000 took 0.85min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 21:28:17,662 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 21:28:17,662 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3347612/1692127631_843672156/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3347612/1692127631_843672156/cifar-100-python.tar.gz to /scratch-local/sunnys.3347612/1692127631_843672156
Generating unified cifar100 dataset
Class histogram for 0-th partition (alpha=100.0, 100 classes): [28 19 16 18 15 17 18 32 19 33 23 30 27 11 21 30 31 34 26 21 24 19 23 27
 31 25 32 16 31 24 24 22 19 25 18 21 37 27 29 22 22 23 28 21 24 21 18 32
 17 25 23 30 28 29 24 19 16 14 30 26 20 26 24 31 26 26 27 27 29 29 23 23
 23 34 29 27 31 25 22 30 16 18 24 28 32 32 20 26 23 23 25 27 30 33 33 25
 31 38 27 22]
INFO flwr 2023-08-15 21:31:22,559 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 21:31:25,182	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-15 21:31:26,316 | app.py:179 | Flower VCE: Ray initialized with resources: {'object_store_memory': 61847529062.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0, 'CPU': 18.0, 'node:145.136.62.65': 1.0, 'memory': 103079215104.0}
INFO flwr 2023-08-15 21:31:26,316 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 21:31:26,316 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 21:31:26,316 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 21:31:36,654 | server.py:91 | initial parameters (loss, other metrics): 4.651723132324219, {'server_test_acc': 0.0095}
INFO flwr 2023-08-15 21:31:36,654 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 21:31:45,633 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 21:32:35,877 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3426814)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:32:36,101 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-15 21:32:36,214 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3426813)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3426814)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3426812)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3426816)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3426815)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3426817)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3426818)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3426819)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3426812)[0m corrupted size vs. prev_size in fastbins
E0815 21:32:36.839044502 3423741 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=3426815)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3426813)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3426816)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3426819)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3426818)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3426817)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:33:07,258 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:33:07,258 | fed_df.py:547 | Average fusion training loss : 0.36376139771938326, val accuracy : 0.07408, best val accuracy : 0.0838
INFO flwr 2023-08-15 21:33:07,260 | common.py:35 | Avg. local train loss : 21.371575412154197, train acc : 0.11414722222222222
INFO flwr 2023-08-15 21:33:09,924 | server.py:116 | fit progress: (1, 4.356128051757812, {'server_test_acc': 0.088}, 93.26995274284855)
INFO flwr 2023-08-15 21:33:09,924 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 21:33:19,587 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3500241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3500240)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:34:06,995 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3500246)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 21:34:07,222 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-15 21:34:07,333 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3500241)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3500240)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3500246)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3500247)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3500244)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3500249)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3500250)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3500245)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3500245)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3500244)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3500247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3500249)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3500250)[0m double free or corruption (fasttop)
E0815 21:34:08.923535189 3474009 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0815 21:34:15.520045302 3552551 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-15 21:34:41,349 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:34:41,349 | fed_df.py:547 | Average fusion training loss : 0.24736749243736267, val accuracy : 0.12904, best val accuracy : 0.136
INFO flwr 2023-08-15 21:34:41,351 | common.py:35 | Avg. local train loss : 20.57968340963125, train acc : 0.1840361111111111
INFO flwr 2023-08-15 21:34:44,153 | server.py:116 | fit progress: (2, 4.267468872070313, {'server_test_acc': 0.1391}, 187.49919707188383)
INFO flwr 2023-08-15 21:34:44,153 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 21:34:54,370 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3573754)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:35:41,875 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-15 21:35:42,111 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 21:35:42,223 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3573754)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3573757)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3573760)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3573756)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3573758)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3573761)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3573759)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3573762)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3573760)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3573762)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3573758)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3573761)[0m corrupted size vs. prev_size in fastbins
E0815 21:35:43.263723351 3552888 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=3573756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3573757)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3573759)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:36:17,466 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:36:17,466 | fed_df.py:547 | Average fusion training loss : 0.11674744242429733, val accuracy : 0.15956, best val accuracy : 0.1694
INFO flwr 2023-08-15 21:36:17,469 | common.py:35 | Avg. local train loss : 20.03924821317196, train acc : 0.24826111111111107
INFO flwr 2023-08-15 21:36:20,292 | server.py:116 | fit progress: (3, 4.258265759277344, {'server_test_acc': 0.1709}, 283.6380992811173)
INFO flwr 2023-08-15 21:36:20,292 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 21:36:30,648 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3646972)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:37:18,007 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-15 21:37:18,234 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 21:37:18,399 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3646972)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3646976)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3646977)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3646979)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3646978)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3646981)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3646973)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3646980)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3646973)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3646977)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3646976)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3646979)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3646980)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3646978)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3646981)[0m malloc_consolidate(): invalid chunk size
E0815 21:37:20.717823791 3620999 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-15 21:37:53,344 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:37:53,344 | fed_df.py:547 | Average fusion training loss : 0.022439218267798423, val accuracy : 0.19756, best val accuracy : 0.2034
INFO flwr 2023-08-15 21:37:53,346 | common.py:35 | Avg. local train loss : 19.590369904041292, train acc : 0.30013611111111116
INFO flwr 2023-08-15 21:37:56,245 | server.py:116 | fit progress: (4, 4.222847546386719, {'server_test_acc': 0.2046}, 379.59119079681113)
INFO flwr 2023-08-15 21:37:56,245 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 21:38:06,599 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 21:38:53,907 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3720594)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:38:54,134 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 21:38:54,244 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3720595)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3720594)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3720598)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3720599)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3720597)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3720601)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3720600)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3720602)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3720599)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3720602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3720595)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3720597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3720600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3720598)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3720601)[0m double free or corruption (fasttop)
E0815 21:39:13.321409390 3778511 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-15 21:39:29,423 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:39:29,424 | fed_df.py:547 | Average fusion training loss : 0.00399839565390721, val accuracy : 0.22296, best val accuracy : 0.2316
INFO flwr 2023-08-15 21:39:29,426 | common.py:35 | Avg. local train loss : 19.325565038621423, train acc : 0.3299916666666667
INFO flwr 2023-08-15 21:39:32,319 | server.py:116 | fit progress: (5, 4.259666455078125, {'server_test_acc': 0.2337}, 475.66479335492477)
INFO flwr 2023-08-15 21:39:32,319 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 21:39:42,586 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 21:40:29,850 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-15 21:40:30,078 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 21:40:30,191 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3794000)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3794002)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3794003)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3794004)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3794001)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3794005)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3794007)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3794006)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3794002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794001)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794005)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794004)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3794006)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3794007)[0m malloc_consolidate(): invalid chunk size
E0815 21:40:33.550122580 3841898 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-15 21:41:05,605 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:41:05,606 | fed_df.py:547 | Average fusion training loss : 0.0014258964929613285, val accuracy : 0.23904, best val accuracy : 0.2422
INFO flwr 2023-08-15 21:41:05,608 | common.py:35 | Avg. local train loss : 19.024164886772635, train acc : 0.3634416666666667
INFO flwr 2023-08-15 21:41:08,499 | server.py:116 | fit progress: (6, 4.292753820800781, {'server_test_acc': 0.2436}, 571.8446676349267)
INFO flwr 2023-08-15 21:41:08,499 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 21:41:18,808 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3867286)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:42:06,279 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-15 21:42:06,519 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 21:42:06,630 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3867286)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3867284)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3867287)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3867289)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3867288)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3867290)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3867292)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3867291)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3867290)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3867288)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3867289)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3867287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3867292)[0m malloc_consolidate(): invalid chunk size
E0815 21:42:08.249945605 3914660 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=3867284)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3867291)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:42:41,913 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:42:41,914 | fed_df.py:547 | Average fusion training loss : 0.0013271119228447789, val accuracy : 0.25288, best val accuracy : 0.2598
INFO flwr 2023-08-15 21:42:41,916 | common.py:35 | Avg. local train loss : 18.949874420464038, train acc : 0.37478055555555556
INFO flwr 2023-08-15 21:42:44,795 | server.py:116 | fit progress: (7, 4.334494287109375, {'server_test_acc': 0.2652}, 668.1413794769906)
INFO flwr 2023-08-15 21:42:44,796 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 21:42:55,170 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3940754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3940760)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:43:42,462 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3940758)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 21:43:42,690 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 21:43:42,800 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3940757)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3940754)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3940760)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3940759)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3940758)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3940761)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3940762)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3940763)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3940757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3940761)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3940763)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3940762)[0m malloc_consolidate(): invalid chunk size
E0815 21:43:44.203168124 3915048 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3940759)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:44:18,245 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:44:18,246 | fed_df.py:547 | Average fusion training loss : 0.001106456497858744, val accuracy : 0.2546, best val accuracy : 0.2604
INFO flwr 2023-08-15 21:44:18,248 | common.py:35 | Avg. local train loss : 18.929397685825823, train acc : 0.3809416666666666
INFO flwr 2023-08-15 21:44:21,230 | server.py:116 | fit progress: (8, 4.376752563476563, {'server_test_acc': 0.2722}, 764.5764906508848)
INFO flwr 2023-08-15 21:44:21,231 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 21:44:31,590 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4019234)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:45:19,063 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-15 21:45:19,292 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-15 21:45:19,404 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4019234)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4019233)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4019237)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4019238)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4019239)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4019236)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4019240)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4019235)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4019237)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4019240)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4019233)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4019239)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4019238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4019235)[0m double free or corruption (fasttop)
E0815 21:45:20.892736309 3988268 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=4019236)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:45:54,945 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:45:54,945 | fed_df.py:547 | Average fusion training loss : 0.0012625000554835424, val accuracy : 0.26027999999999996, best val accuracy : 0.2728
INFO flwr 2023-08-15 21:45:54,947 | common.py:35 | Avg. local train loss : 18.860565412044526, train acc : 0.3919166666666667
INFO flwr 2023-08-15 21:45:57,869 | server.py:116 | fit progress: (9, 4.400242309570313, {'server_test_acc': 0.2671}, 861.2150892717764)
INFO flwr 2023-08-15 21:45:57,869 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 21:46:08,118 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4104126)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4104124)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4104132)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:46:56,062 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-15 21:46:56,292 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 21:46:56,402 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4104124)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4104127)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4104131)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4104128)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4104129)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4104126)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4104130)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4104132)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4104128)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4104127)[0m malloc_consolidate(): invalid chunk size
E0815 21:46:57.112197221 4077508 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=4104129)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4104130)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4104131)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:47:31,757 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:47:31,757 | fed_df.py:547 | Average fusion training loss : 0.0009404579907422886, val accuracy : 0.25952000000000003, best val accuracy : 0.2716
INFO flwr 2023-08-15 21:47:31,759 | common.py:35 | Avg. local train loss : 18.763150170445442, train acc : 0.4049333333333333
INFO flwr 2023-08-15 21:47:34,675 | server.py:116 | fit progress: (10, 4.464045629882812, {'server_test_acc': 0.2771}, 958.0210964838043)
INFO flwr 2023-08-15 21:47:34,675 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 21:47:44,921 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4177453)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:48:32,487 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4177456)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:48:32,720 | fed_df.py:365 | Warm start at round 11
[2m[36m(launch_and_fit pid=4177458)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:48:32,831 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4177453)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4177456)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4177458)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4177459)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4177454)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4177457)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4177460)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4177455)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4177459)[0m malloc_consolidate(): invalid chunk size
E0815 21:48:33.383280304   31015 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=4177454)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4177457)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4177460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4177455)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:49:08,299 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:49:08,299 | fed_df.py:547 | Average fusion training loss : 0.0015466835151892156, val accuracy : 0.27752000000000004, best val accuracy : 0.289
INFO flwr 2023-08-15 21:49:08,301 | common.py:35 | Avg. local train loss : 18.77122383415699, train acc : 0.4082055555555556
INFO flwr 2023-08-15 21:49:11,242 | server.py:116 | fit progress: (11, 4.4512253051757815, {'server_test_acc': 0.29}, 1054.5881366617978)
INFO flwr 2023-08-15 21:49:11,242 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 21:49:21,723 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=57700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=57704)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=57703)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:50:09,858 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=57706)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:50:10,099 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 21:50:10,241 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=57700)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=57703)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=57702)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=57701)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=57704)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=57706)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=57705)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=57707)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=57702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=57707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=57705)[0m malloc_consolidate(): invalid chunk size
E0815 21:50:11.689043082  105086 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=57701)[0m malloc_consolidate(): invalid chunk size
E0815 21:50:43.167023232  126503 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-15 21:50:45,640 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:50:45,640 | fed_df.py:547 | Average fusion training loss : 0.001327012843627017, val accuracy : 0.27359999999999995, best val accuracy : 0.294
INFO flwr 2023-08-15 21:50:45,642 | common.py:35 | Avg. local train loss : 18.61553316563368, train acc : 0.423613888888889
INFO flwr 2023-08-15 21:50:48,553 | server.py:116 | fit progress: (12, 4.459036877441406, {'server_test_acc': 0.2906}, 1151.8995808959007)
INFO flwr 2023-08-15 21:50:48,554 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 21:50:58,814 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=131216)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=131217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131223)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:51:46,799 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 21:51:47,027 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 21:51:47,137 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=131217)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=131216)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=131221)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=131222)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=131224)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=131223)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=131219)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=131220)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=131219)[0m malloc_consolidate(): invalid chunk size
E0815 21:51:47.594802574  178419 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=131220)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131221)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131222)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131224)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:52:22,522 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:52:22,522 | fed_df.py:547 | Average fusion training loss : 0.0011533584328717553, val accuracy : 0.27464, best val accuracy : 0.2902
INFO flwr 2023-08-15 21:52:22,524 | common.py:35 | Avg. local train loss : 18.498980474472045, train acc : 0.4339944444444444
INFO flwr 2023-08-15 21:52:25,435 | server.py:116 | fit progress: (13, 4.467033154296875, {'server_test_acc': 0.2986}, 1248.781183497049)
INFO flwr 2023-08-15 21:52:25,435 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 21:52:35,545 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=205173)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:53:23,222 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-15 21:53:23,453 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 21:53:23,565 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=205173)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=205175)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=205174)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=205176)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=205178)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=205177)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=205180)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=205179)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=205179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=205178)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=205175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=205176)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=205180)[0m malloc_consolidate(): invalid chunk size
E0815 21:53:24.988834055  178587 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=205174)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=205177)[0m malloc_consolidate(): invalid chunk size
E0815 21:53:48.693129853  252678 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 21:53:59,225 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:53:59,226 | fed_df.py:547 | Average fusion training loss : 0.0014841676507494413, val accuracy : 0.28764, best val accuracy : 0.3012
INFO flwr 2023-08-15 21:53:59,228 | common.py:35 | Avg. local train loss : 18.476853066682818, train acc : 0.4343888888888889
INFO flwr 2023-08-15 21:54:02,151 | server.py:116 | fit progress: (14, 4.445701440429687, {'server_test_acc': 0.3028}, 1345.4975460288115)
INFO flwr 2023-08-15 21:54:02,152 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 21:54:12,423 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=278549)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:54:59,943 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-15 21:55:00,173 | fed_df.py:365 | Warm start at round 15
[2m[36m(launch_and_fit pid=278552)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:55:00,290 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=278549)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=278550)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=278552)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=278553)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=278551)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=278556)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=278555)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=278554)[0m Fitting Client 18
E0815 21:55:00.746868747  268642 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=278553)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=278555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=278554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=278550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=278556)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=278551)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:55:36,056 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:55:36,056 | fed_df.py:547 | Average fusion training loss : 0.0016771676770295017, val accuracy : 0.2944, best val accuracy : 0.3088
INFO flwr 2023-08-15 21:55:36,058 | common.py:35 | Avg. local train loss : 18.36956181526184, train acc : 0.4441722222222222
INFO flwr 2023-08-15 21:55:39,043 | server.py:116 | fit progress: (15, 4.428327551269531, {'server_test_acc': 0.3123}, 1442.389473610092)
INFO flwr 2023-08-15 21:55:39,044 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 21:55:49,266 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 21:56:36,868 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=352033)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 21:56:37,104 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-15 21:56:37,270 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=352033)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=352034)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=352032)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=352036)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=352035)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=352037)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=352039)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=352038)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=352034)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=352038)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=352032)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=352037)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=352035)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=352039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=352036)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:57:18,284 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:57:18,285 | fed_df.py:547 | Average fusion training loss : 0.0016241790683707222, val accuracy : 0.3012, best val accuracy : 0.3138
INFO flwr 2023-08-15 21:57:18,287 | common.py:35 | Avg. local train loss : 18.29119907617569, train acc : 0.44830555555555557
INFO flwr 2023-08-15 21:57:21,272 | server.py:116 | fit progress: (16, 4.428994140625, {'server_test_acc': 0.3151}, 1544.6179520119913)
INFO flwr 2023-08-15 21:57:21,272 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 21:57:31,676 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=425527)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 21:58:19,233 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=425531)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 21:58:19,465 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 21:58:19,576 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=425527)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=425531)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=425532)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=425533)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=425534)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=425537)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=425535)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=425536)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=425534)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=425532)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=425535)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=425533)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=425537)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=425536)[0m malloc_consolidate(): invalid chunk size
E0815 21:58:22.536118825  325483 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 21:58:22.536240915  325483 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 21:58:55,464 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 21:58:55,464 | fed_df.py:547 | Average fusion training loss : 0.0016554915794986301, val accuracy : 0.30664, best val accuracy : 0.3186
INFO flwr 2023-08-15 21:58:55,467 | common.py:35 | Avg. local train loss : 18.19486544430256, train acc : 0.4564805555555555
INFO flwr 2023-08-15 21:58:58,421 | server.py:116 | fit progress: (17, 4.423118896484375, {'server_test_acc': 0.3207}, 1641.7674406501465)
INFO flwr 2023-08-15 21:58:58,422 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 21:59:08,592 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=499021)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 21:59:56,387 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-15 21:59:56,619 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 21:59:56,734 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=499021)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=499018)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=499023)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=499025)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=499026)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=499027)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=499029)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=499028)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=499018)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=499028)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=499029)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=499023)[0m corrupted size vs. prev_size in fastbins
E0815 21:59:57.900177691  474135 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=499027)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=499025)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=499026)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 22:00:33,026 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:00:33,027 | fed_df.py:547 | Average fusion training loss : 0.0016705851046135648, val accuracy : 0.30060000000000003, best val accuracy : 0.314
INFO flwr 2023-08-15 22:00:33,029 | common.py:35 | Avg. local train loss : 18.152841544151308, train acc : 0.45923055555555553
INFO flwr 2023-08-15 22:00:36,357 | server.py:116 | fit progress: (18, 4.427500939941406, {'server_test_acc': 0.319}, 1739.7033358281478)
INFO flwr 2023-08-15 22:00:36,357 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 22:00:47,373 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=589019)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=589012)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 22:01:34,883 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-15 22:01:35,111 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 22:01:35,220 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=589012)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=589014)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=589017)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=589018)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=589019)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=589016)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=589021)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=589020)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=589018)[0m malloc_consolidate(): invalid chunk size
E0815 22:01:36.186291029  554660 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=589014)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=589016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=589017)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=589021)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=589020)[0m malloc_consolidate(): invalid chunk size
E0815 22:01:37.517102619  636301 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 22:02:10,753 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:02:10,754 | fed_df.py:547 | Average fusion training loss : 0.0017283746815519407, val accuracy : 0.31588, best val accuracy : 0.328
INFO flwr 2023-08-15 22:02:10,756 | common.py:35 | Avg. local train loss : 18.029873362183572, train acc : 0.4706361111111112
INFO flwr 2023-08-15 22:02:13,656 | server.py:116 | fit progress: (19, 4.403445971679687, {'server_test_acc': 0.329}, 1837.0024811141193)
INFO flwr 2023-08-15 22:02:13,657 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 22:02:23,929 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=662458)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 22:03:11,288 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 22:03:11,524 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 22:03:11,689 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=662458)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=662463)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=662462)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=662469)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=662466)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=662464)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=662467)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=662468)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=662468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662464)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662467)[0m malloc_consolidate(): invalid chunk size
E0815 22:03:12.776227422  709638 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=662463)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662466)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=662469)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=662462)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:03:47,633 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:03:47,633 | fed_df.py:547 | Average fusion training loss : 0.0017273585652001202, val accuracy : 0.31252, best val accuracy : 0.324
INFO flwr 2023-08-15 22:03:47,635 | common.py:35 | Avg. local train loss : 18.022745671868325, train acc : 0.4700666666666667
INFO flwr 2023-08-15 22:03:50,597 | server.py:116 | fit progress: (20, 4.428892797851563, {'server_test_acc': 0.3346}, 1933.9434012267739)
INFO flwr 2023-08-15 22:03:50,598 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 22:04:01,001 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=736017)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=736020)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 22:04:48,622 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-15 22:04:48,851 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 22:04:48,964 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=736017)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=736020)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=736022)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=736023)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=736026)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=736024)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=736027)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=736025)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=736022)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=736023)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=736025)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=736026)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=736024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=736027)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 22:05:24,760 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:05:24,760 | fed_df.py:547 | Average fusion training loss : 0.0020003302823752163, val accuracy : 0.31351999999999997, best val accuracy : 0.3266
INFO flwr 2023-08-15 22:05:24,762 | common.py:35 | Avg. local train loss : 17.930400754511357, train acc : 0.4810027777777777
INFO flwr 2023-08-15 22:05:27,705 | server.py:116 | fit progress: (21, 4.417842358398437, {'server_test_acc': 0.333}, 2031.0507678710856)
INFO flwr 2023-08-15 22:05:27,705 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 22:05:37,928 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=809361)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=809370)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:06:25,575 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=809369)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:06:25,822 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 22:06:25,934 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=809361)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=809367)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=809370)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=809371)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=809369)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=809368)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=809364)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=809372)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=809371)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=809364)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=809372)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=809368)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=809367)[0m malloc_consolidate(): invalid chunk size
E0815 22:06:36.132797902  858634 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 22:07:07,087 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:07:07,087 | fed_df.py:547 | Average fusion training loss : 0.0018417838217574172, val accuracy : 0.31764000000000003, best val accuracy : 0.3324
INFO flwr 2023-08-15 22:07:07,089 | common.py:35 | Avg. local train loss : 17.85068534016609, train acc : 0.48185833333333333
INFO flwr 2023-08-15 22:07:10,234 | server.py:116 | fit progress: (22, 4.40798388671875, {'server_test_acc': 0.3396}, 2133.580277725123)
INFO flwr 2023-08-15 22:07:10,234 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 22:07:20,541 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=882755)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:08:07,929 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 22:08:08,163 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 22:08:08,277 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=882758)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=882755)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=882762)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=882756)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=882761)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=882760)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=882763)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=882764)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=882762)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=882761)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=882764)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=882758)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=882760)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=882756)[0m malloc_consolidate(): invalid chunk size
E0815 22:08:09.770607372  930237 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=882763)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:08:44,507 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:08:44,507 | fed_df.py:547 | Average fusion training loss : 0.0021053387075662612, val accuracy : 0.32171999999999995, best val accuracy : 0.3336
INFO flwr 2023-08-15 22:08:44,510 | common.py:35 | Avg. local train loss : 17.85384003072977, train acc : 0.4808111111111112
INFO flwr 2023-08-15 22:08:47,475 | server.py:116 | fit progress: (23, 4.407154248046875, {'server_test_acc': 0.3416}, 2230.8209435227327)
INFO flwr 2023-08-15 22:08:47,475 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 22:08:57,679 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=956456)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956461)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:09:45,080 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 22:09:45,314 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 22:09:45,426 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=956456)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=956461)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=956463)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=956462)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=956466)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=956467)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=956464)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=956465)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=956463)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956462)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=956464)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956467)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956465)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=956466)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:10:27,309 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:10:27,310 | fed_df.py:547 | Average fusion training loss : 0.001985090330941603, val accuracy : 0.3278, best val accuracy : 0.3382
INFO flwr 2023-08-15 22:10:27,312 | common.py:35 | Avg. local train loss : 17.792375399172304, train acc : 0.487475
INFO flwr 2023-08-15 22:10:30,266 | server.py:116 | fit progress: (24, 4.401090808105469, {'server_test_acc': 0.3502}, 2333.6123022041284)
INFO flwr 2023-08-15 22:10:30,267 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 22:10:40,613 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1029829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1029837)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:11:28,002 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-15 22:11:28,235 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 22:11:28,401 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1029829)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1029833)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1029834)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1029839)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1029838)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1029837)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1029836)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1029835)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1029839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1029834)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1029835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1029836)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1029833)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1029838)[0m malloc_consolidate(): invalid chunk size
E0815 22:11:31.531151423 1077862 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 22:12:04,703 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:12:04,704 | fed_df.py:547 | Average fusion training loss : 0.0024299334816168996, val accuracy : 0.32492, best val accuracy : 0.3404
INFO flwr 2023-08-15 22:12:04,706 | common.py:35 | Avg. local train loss : 17.74899204671383, train acc : 0.4893055555555556
INFO flwr 2023-08-15 22:12:07,663 | server.py:116 | fit progress: (25, 4.380748010253906, {'server_test_acc': 0.351}, 2431.0096210408956)
INFO flwr 2023-08-15 22:12:07,664 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 22:12:18,292 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1103233)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:13:05,951 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1103231)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 22:13:06,182 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 22:13:06,293 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1103233)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1103232)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1103231)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1103234)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1103235)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1103236)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1103227)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1103230)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1103232)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1103230)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1103236)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1103227)[0m malloc_consolidate(): invalid chunk size
E0815 22:13:07.810189044 1078721 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1103235)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1103234)[0m malloc_consolidate(): invalid chunk size
E0815 22:13:11.209473451 1150969 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 22:13:42,511 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:13:42,512 | fed_df.py:547 | Average fusion training loss : 0.0028833948681131006, val accuracy : 0.33432000000000006, best val accuracy : 0.3436
INFO flwr 2023-08-15 22:13:42,514 | common.py:35 | Avg. local train loss : 17.69747969508171, train acc : 0.4951972222222222
INFO flwr 2023-08-15 22:13:45,473 | server.py:116 | fit progress: (26, 4.386542248535156, {'server_test_acc': 0.3508}, 2528.819111475721)
INFO flwr 2023-08-15 22:13:45,473 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 22:13:55,733 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1176756)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 22:14:43,457 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 22:14:43,701 | fed_df.py:365 | Warm start at round 27
[2m[36m(launch_and_fit pid=1176758)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:14:43,817 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1176756)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1176753)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1176752)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1176759)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1176754)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1176757)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1176755)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1176758)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1176759)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1176752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1176755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1176753)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1176754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1176757)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:15:20,007 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:15:20,008 | fed_df.py:547 | Average fusion training loss : 0.0031142490601632745, val accuracy : 0.33212, best val accuracy : 0.3388
INFO flwr 2023-08-15 22:15:20,010 | common.py:35 | Avg. local train loss : 17.64351452291012, train acc : 0.5013805555555556
INFO flwr 2023-08-15 22:15:22,963 | server.py:116 | fit progress: (27, 4.3869638671875, {'server_test_acc': 0.3486}, 2626.3087829858996)
INFO flwr 2023-08-15 22:15:22,963 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 22:15:33,322 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1253560)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:16:21,064 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1253564)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:16:21,295 | fed_df.py:365 | Warm start at round 28
[2m[36m(launch_and_fit pid=1253558)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 22:16:21,408 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1253558)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1253560)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1253559)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1253562)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1253561)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1253564)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1253565)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1253563)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1253565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1253562)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1253563)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1253559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1253561)[0m double free or corruption (fasttop)
E0815 22:16:26.918302920 1153098 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 22:16:57,902 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:16:57,902 | fed_df.py:547 | Average fusion training loss : 0.0034825652758590877, val accuracy : 0.32988, best val accuracy : 0.3396
INFO flwr 2023-08-15 22:16:57,904 | common.py:35 | Avg. local train loss : 17.59284505993128, train acc : 0.5038416666666667
INFO flwr 2023-08-15 22:17:00,903 | server.py:116 | fit progress: (28, 4.392502587890625, {'server_test_acc': 0.3457}, 2724.2486943490803)
INFO flwr 2023-08-15 22:17:00,903 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 22:17:11,275 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1340155)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 22:17:59,003 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1340147)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 22:17:59,234 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-15 22:17:59,348 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1340147)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1340149)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1340150)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1340151)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1340152)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1340153)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1340155)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1340154)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1340153)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1340152)[0m double free or corruption (fasttop)
E0815 22:18:00.009202456 1316968 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1340151)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1340154)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1340149)[0m malloc_consolidate(): invalid chunk size
E0815 22:18:17.078029722 1398057 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 22:18:35,583 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:18:35,584 | fed_df.py:547 | Average fusion training loss : 0.0034798726123408414, val accuracy : 0.33292, best val accuracy : 0.3438
INFO flwr 2023-08-15 22:18:35,586 | common.py:35 | Avg. local train loss : 17.602208779752253, train acc : 0.5012777777777777
INFO flwr 2023-08-15 22:18:38,540 | server.py:116 | fit progress: (29, 4.376628991699219, {'server_test_acc': 0.352}, 2821.8861902127974)
INFO flwr 2023-08-15 22:18:38,540 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 22:18:49,192 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1413598)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 22:19:36,412 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 22:19:36,642 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 22:19:36,754 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1413598)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1413601)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1413602)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1413600)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1413603)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1413604)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1413605)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1413606)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1413605)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1413603)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1413601)[0m malloc_consolidate(): invalid chunk size
E0815 22:19:37.938740997 1398396 chttp2_transport.cc:1079]             ipv4:145.136.62.65:55736: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1413600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1413606)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1413604)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1413602)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 22:20:13,638 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 22:20:13,639 | fed_df.py:547 | Average fusion training loss : 0.0020338539091753773, val accuracy : 0.33287999999999995, best val accuracy : 0.3454
INFO flwr 2023-08-15 22:20:13,641 | common.py:35 | Avg. local train loss : 17.577354173362256, train acc : 0.5014333333333333
INFO flwr 2023-08-15 22:20:16,639 | server.py:116 | fit progress: (30, 4.400369482421875, {'server_test_acc': 0.3469}, 2919.985450841021)
INFO flwr 2023-08-15 22:20:16,640 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 22:20:16,640 | server.py:144 | FL finished in 2919.985862564761
INFO flwr 2023-08-15 22:20:16,640 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 22:20:16,641 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 22:20:16,641 | app.py:204 | app_fit: losses_centralized [(0, 4.651723132324219), (1, 4.356128051757812), (2, 4.267468872070313), (3, 4.258265759277344), (4, 4.222847546386719), (5, 4.259666455078125), (6, 4.292753820800781), (7, 4.334494287109375), (8, 4.376752563476563), (9, 4.400242309570313), (10, 4.464045629882812), (11, 4.4512253051757815), (12, 4.459036877441406), (13, 4.467033154296875), (14, 4.445701440429687), (15, 4.428327551269531), (16, 4.428994140625), (17, 4.423118896484375), (18, 4.427500939941406), (19, 4.403445971679687), (20, 4.428892797851563), (21, 4.417842358398437), (22, 4.40798388671875), (23, 4.407154248046875), (24, 4.401090808105469), (25, 4.380748010253906), (26, 4.386542248535156), (27, 4.3869638671875), (28, 4.392502587890625), (29, 4.376628991699219), (30, 4.400369482421875)]
INFO flwr 2023-08-15 22:20:16,641 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0095), (1, 0.088), (2, 0.1391), (3, 0.1709), (4, 0.2046), (5, 0.2337), (6, 0.2436), (7, 0.2652), (8, 0.2722), (9, 0.2671), (10, 0.2771), (11, 0.29), (12, 0.2906), (13, 0.2986), (14, 0.3028), (15, 0.3123), (16, 0.3151), (17, 0.3207), (18, 0.319), (19, 0.329), (20, 0.3346), (21, 0.333), (22, 0.3396), (23, 0.3416), (24, 0.3502), (25, 0.351), (26, 0.3508), (27, 0.3486), (28, 0.3457), (29, 0.352), (30, 0.3469)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn65: task 0: Aborted
srun: Terminating StepId=3347612.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3347612
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:05:01
CPU Efficiency: 12.76% of 16:19:30 core-walltime
Job Wall-clock time: 00:54:25
Memory Utilized: 65.75 GB
Memory Efficiency: 54.79% of 120.00 GB
