-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:500
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:False
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:500
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
Simulating feddf training
INFO simulate 2023-09-19 11:56:01,677 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-09-19 11:56:01,677 | simulate.py:55 | Reading args from argument parser
INFO flwr 2023-09-19 11:56:22,949 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-19 11:56:26,160	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-09-19 11:56:28,457 | app.py:179 | Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'node:145.136.62.26': 1.0, 'memory': 103079215104.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-09-19 11:56:28,458 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-19 11:56:28,458 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-09-19 11:56:28,458 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3894397/1695117341_216617882/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3894397/1695117341_216617882/cifar-10-python.tar.gz to /scratch-local/sunnys.3894397/1695117341_216617882
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3894397/1695117341_216617882/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3894397/1695117341_216617882/cifar-100-python.tar.gz to /scratch-local/sunnys.3894397/1695117341_216617882
INFO flwr 2023-09-19 11:56:37,992 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-09-19 11:56:37,992 | server.py:101 | FL starting
DEBUG flwr 2023-09-19 11:56:40,433 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1335562)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1335566)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1335567)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 11:58:05,858 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-19 11:58:05,871 | fed_df.py:366 | Warm start at round 1
[2m[36m(launch_and_fit pid=1335570)[0m double free or corruption (fasttop)
INFO flwr 2023-09-19 11:58:05,942 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1335567)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1335568)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1335562)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1335569)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1335566)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1335570)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1335563)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1335564)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1335563)[0m malloc_consolidate(): invalid chunk size
E0919 11:58:06.983082954 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038080704 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038152722 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038168794 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038181900 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038190660 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038201046 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038213345 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038225692 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038237200 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038247306 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0919 11:58:07.038256255 1329305 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=1335569)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1335568)[0m malloc_consolidate(): invalid chunk size
E0919 11:58:07.730698894 1524323 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=1335564)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 11:59:04,678 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 11:59:04,678 | fed_df.py:551 | Average fusion training loss : 0.030958304434083404, val accuracy : 0.40725999999999996, best val accuracy : 0.4532
INFO flwr 2023-09-19 11:59:04,679 | common.py:35 | Avg. local train loss : 6.904190584644676, train acc : 0.5799055555555555
INFO flwr 2023-09-19 11:59:07,162 | server.py:116 | fit progress: (1, 1.6259392181396484, {'server_test_acc': 0.4374}, 149.1692631021142)
INFO flwr 2023-09-19 11:59:07,162 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-09-19 11:59:09,342 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1636818)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1636827)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:00:33,751 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-19 12:00:33,764 | fed_df.py:366 | Warm start at round 2
INFO flwr 2023-09-19 12:00:33,833 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1636822)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1636823)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1636821)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1636824)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1636826)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1636827)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1636825)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1636818)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1636821)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1636825)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1636826)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1636822)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1636824)[0m malloc_consolidate(): invalid chunk size
E0919 12:00:36.157721068 1524795 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=1636823)[0m double free or corruption (fasttop)
INFO flwr 2023-09-19 12:01:34,109 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:01:34,110 | fed_df.py:551 | Average fusion training loss : 0.017134713999927043, val accuracy : 0.48108000000000006, best val accuracy : 0.5284
INFO flwr 2023-09-19 12:01:34,111 | common.py:35 | Avg. local train loss : 5.278122551366686, train acc : 0.7469722222222221
INFO flwr 2023-09-19 12:01:36,902 | server.py:116 | fit progress: (2, 1.648829901123047, {'server_test_acc': 0.5233}, 298.90930656623095)
INFO flwr 2023-09-19 12:01:36,902 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-09-19 12:01:40,452 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1939062)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1939060)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1939063)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1939064)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1939061)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1939059)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 12:03:06,994 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-19 12:03:07,007 | fed_df.py:366 | Warm start at round 3
INFO flwr 2023-09-19 12:03:07,075 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1939063)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1939059)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1939057)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1939060)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1939061)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1939064)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1939062)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1939054)[0m Fitting Client 4
E0919 12:03:07.306113927 1823821 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=1939057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1939054)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:04:11,845 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:04:11,846 | fed_df.py:551 | Average fusion training loss : 0.01755043150950223, val accuracy : 0.5388200000000001, best val accuracy : 0.5598
INFO flwr 2023-09-19 12:04:11,846 | common.py:35 | Avg. local train loss : 4.608881855010987, train acc : 0.8200736111111112
INFO flwr 2023-09-19 12:04:14,530 | server.py:116 | fit progress: (3, 1.6981983612060547, {'server_test_acc': 0.5468}, 456.53791972529143)
INFO flwr 2023-09-19 12:04:14,530 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-09-19 12:04:16,996 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2431375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2431338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2431377)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2431368)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:05:43,554 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-19 12:05:43,567 | fed_df.py:366 | Warm start at round 4
INFO flwr 2023-09-19 12:05:43,637 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2431377)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2431357)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2431166)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2431375)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2431368)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2431348)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2431330)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2431338)[0m Fitting Client 0
E0919 12:05:44.231591209 2227890 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2431357)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2431330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2431166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2431348)[0m double free or corruption (fasttop)
INFO flwr 2023-09-19 12:06:47,924 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:06:47,924 | fed_df.py:551 | Average fusion training loss : 0.02059319036733359, val accuracy : 0.5605600000000001, best val accuracy : 0.5878
INFO flwr 2023-09-19 12:06:47,925 | common.py:35 | Avg. local train loss : 4.310610949806869, train acc : 0.8568083333333334
INFO flwr 2023-09-19 12:06:50,768 | server.py:116 | fit progress: (4, 1.6708453094482423, {'server_test_acc': 0.5792}, 612.775930098258)
INFO flwr 2023-09-19 12:06:50,768 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-09-19 12:06:53,278 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2890681)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:08:20,325 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-09-19 12:08:20,338 | fed_df.py:366 | Warm start at round 5
INFO flwr 2023-09-19 12:08:20,408 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2890679)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2890686)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2890682)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2890678)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2890683)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2890681)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2890685)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2890684)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2890684)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2890686)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2890686)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2890683)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2890679)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2890682)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2890685)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2890678)[0m malloc_consolidate(): invalid chunk size
E0919 12:08:24.890457490 2716559 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-09-19 12:09:26,979 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:09:26,980 | fed_df.py:551 | Average fusion training loss : 0.012875338028650731, val accuracy : 0.5715, best val accuracy : 0.597
INFO flwr 2023-09-19 12:09:26,981 | common.py:35 | Avg. local train loss : 4.1495219392701985, train acc : 0.8756499999999999
INFO flwr 2023-09-19 12:09:29,800 | server.py:116 | fit progress: (5, 1.8290144165039062, {'server_test_acc': 0.5826}, 771.8072800980881)
INFO flwr 2023-09-19 12:09:29,800 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-09-19 12:09:32,167 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3337102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3337098)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 12:10:56,816 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-09-19 12:10:56,829 | fed_df.py:366 | Warm start at round 6
INFO flwr 2023-09-19 12:10:56,899 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3337099)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3337098)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3337100)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3337104)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3337103)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3337097)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3337101)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3337102)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3337104)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3337099)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3337101)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3337103)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3337097)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3337100)[0m malloc_consolidate(): invalid chunk size
E0919 12:10:59.092966901 3166775 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-09-19 12:12:01,536 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:12:01,537 | fed_df.py:551 | Average fusion training loss : 0.012873442385345697, val accuracy : 0.5758000000000001, best val accuracy : 0.6064
INFO flwr 2023-09-19 12:12:01,537 | common.py:35 | Avg. local train loss : 3.941673697158694, train acc : 0.8970027777777778
INFO flwr 2023-09-19 12:12:04,255 | server.py:116 | fit progress: (6, 1.8149196228027344, {'server_test_acc': 0.592}, 926.2631752332672)
INFO flwr 2023-09-19 12:12:04,256 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-09-19 12:12:06,820 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3765007)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3765347)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3765360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3765236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3765226)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3765009)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 12:13:29,527 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-19 12:13:29,540 | fed_df.py:366 | Warm start at round 7
INFO flwr 2023-09-19 12:13:29,609 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3765226)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3765007)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3765347)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3765236)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3765360)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3765084)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3765227)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3765009)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3765084)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3765227)[0m malloc_consolidate(): invalid chunk size
E0919 12:13:45.749267826 3595268 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-09-19 12:14:34,771 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:14:34,771 | fed_df.py:551 | Average fusion training loss : 0.012728038789937272, val accuracy : 0.62814, best val accuracy : 0.6584
INFO flwr 2023-09-19 12:14:34,772 | common.py:35 | Avg. local train loss : 4.090291392244398, train acc : 0.8903736111111111
INFO flwr 2023-09-19 12:14:37,437 | server.py:116 | fit progress: (7, 1.7789145874023438, {'server_test_acc': 0.6475}, 1079.4452247153968)
INFO flwr 2023-09-19 12:14:37,438 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-09-19 12:14:39,915 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4188659)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4188655)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4188660)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 12:16:03,305 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-09-19 12:16:03,318 | fed_df.py:366 | Warm start at round 8
INFO flwr 2023-09-19 12:16:03,390 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4188655)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4188660)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4188659)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4188653)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4188658)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4188663)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4188662)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4188661)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4188658)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4188662)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4188661)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4188653)[0m malloc_consolidate(): invalid chunk size
E0919 12:16:05.234567153 4051754 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-09-19 12:17:09,633 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:17:09,634 | fed_df.py:551 | Average fusion training loss : 0.01370828220178373, val accuracy : 0.6668, best val accuracy : 0.6962
INFO flwr 2023-09-19 12:17:09,635 | common.py:35 | Avg. local train loss : 4.018215130083263, train acc : 0.8965541666666667
INFO flwr 2023-09-19 12:17:12,561 | server.py:116 | fit progress: (8, 1.7650592224121093, {'server_test_acc': 0.6888}, 1234.5686228256673)
INFO flwr 2023-09-19 12:17:12,561 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-09-19 12:17:15,069 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=416388)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=416360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=416398)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=416408)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:18:36,896 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-09-19 12:18:36,909 | fed_df.py:366 | Warm start at round 9
INFO flwr 2023-09-19 12:18:36,977 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=416388)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=416382)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=416373)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=416360)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=416367)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=416398)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=416408)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=416404)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=416367)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=416382)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=416404)[0m malloc_consolidate(): invalid chunk size
E0919 12:18:38.835551658  235390 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0919 12:18:48.943582867  650625 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-09-19 12:19:44,567 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:19:44,567 | fed_df.py:551 | Average fusion training loss : 0.01435008753463626, val accuracy : 0.6469199999999999, best val accuracy : 0.6748
INFO flwr 2023-09-19 12:19:44,568 | common.py:35 | Avg. local train loss : 3.839131277985871, train acc : 0.9125791666666666
INFO flwr 2023-09-19 12:19:47,439 | server.py:116 | fit progress: (9, 1.773674008178711, {'server_test_acc': 0.6605}, 1389.446756833233)
INFO flwr 2023-09-19 12:19:47,439 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-09-19 12:19:50,028 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=859667)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=859654)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:21:12,013 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-09-19 12:21:12,026 | fed_df.py:366 | Warm start at round 10
INFO flwr 2023-09-19 12:21:12,093 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=859652)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=859666)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=859667)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=859651)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=859668)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=859669)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=859654)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=859657)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=859651)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=859657)[0m corrupted size vs. prev_size in fastbins
E0919 12:21:13.485309187  680399 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=859652)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=859666)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=859668)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=859669)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-09-19 12:22:22,859 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:22:22,860 | fed_df.py:551 | Average fusion training loss : 0.015043770483229309, val accuracy : 0.65776, best val accuracy : 0.6882
INFO flwr 2023-09-19 12:22:22,861 | common.py:35 | Avg. local train loss : 3.9090652031823994, train acc : 0.9077180555555555
INFO flwr 2023-09-19 12:22:25,615 | server.py:116 | fit progress: (10, 1.6478188201904296, {'server_test_acc': 0.6867}, 1547.6226335233077)
INFO flwr 2023-09-19 12:22:25,615 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-09-19 12:22:28,070 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1310174)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1310260)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1310244)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 12:23:49,115 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-09-19 12:23:49,128 | fed_df.py:366 | Warm start at round 11
INFO flwr 2023-09-19 12:23:49,197 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1310174)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1310244)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1310243)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1310260)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1310240)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1310242)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1310245)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1310261)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1310242)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1310240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1310243)[0m double free or corruption (fasttop)
E0919 12:23:50.318552483 1105808 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1310245)[0m malloc_consolidate(): invalid chunk size
E0919 12:23:54.811997059 1543874 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-09-19 12:25:04,001 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:25:04,001 | fed_df.py:551 | Average fusion training loss : 0.014477328130044043, val accuracy : 0.72208, best val accuracy : 0.7324
INFO flwr 2023-09-19 12:25:04,002 | common.py:35 | Avg. local train loss : 3.983291894942522, train acc : 0.9044694444444443
INFO flwr 2023-09-19 12:25:06,742 | server.py:116 | fit progress: (11, 1.659006478881836, {'server_test_acc': 0.7238}, 1708.7492530895397)
INFO flwr 2023-09-19 12:25:06,742 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-09-19 12:25:09,194 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-19 12:26:31,369 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-09-19 12:26:31,382 | fed_df.py:366 | Warm start at round 12
INFO flwr 2023-09-19 12:26:31,449 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1753311)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1753351)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1753368)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1753313)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1753415)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1753308)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1753433)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1753434)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1753351)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1753415)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1753368)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1753308)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1753313)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1753433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1753434)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1753434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1753311)[0m double free or corruption (fasttop)
INFO flwr 2023-09-19 12:27:47,442 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:27:47,442 | fed_df.py:551 | Average fusion training loss : 0.015524448506534099, val accuracy : 0.68042, best val accuracy : 0.698
INFO flwr 2023-09-19 12:27:47,443 | common.py:35 | Avg. local train loss : 3.716667747870088, train acc : 0.9241458333333332
E0919 12:27:49.100451212 2185067 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-09-19 12:27:50,193 | server.py:116 | fit progress: (12, 1.7199748077392578, {'server_test_acc': 0.6892}, 1872.2005095845088)
INFO flwr 2023-09-19 12:27:50,193 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-09-19 12:27:52,575 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2202248)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2202245)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2202249)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:29:13,013 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-19 12:29:13,026 | fed_df.py:366 | Warm start at round 13
INFO flwr 2023-09-19 12:29:13,095 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2202248)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2202250)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2202249)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2202239)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2202245)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2202246)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2202241)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2202247)[0m Fitting Client 0
E0919 12:29:13.786943174 2406562 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=2202250)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2202241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2202247)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2202239)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2202246)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:30:25,902 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:30:25,903 | fed_df.py:551 | Average fusion training loss : 0.017150656080339104, val accuracy : 0.6524400000000001, best val accuracy : 0.6654
INFO flwr 2023-09-19 12:30:25,903 | common.py:35 | Avg. local train loss : 3.5670466987416147, train acc : 0.9358083333333332
INFO flwr 2023-09-19 12:30:28,631 | server.py:116 | fit progress: (13, 1.7182119873046875, {'server_test_acc': 0.6555}, 2030.6382955843583)
INFO flwr 2023-09-19 12:30:28,631 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-09-19 12:30:30,986 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2639033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2638953)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=2639037)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2638956)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639040)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:31:55,476 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-19 12:31:55,489 | fed_df.py:366 | Warm start at round 14
INFO flwr 2023-09-19 12:31:55,557 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2639038)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2639039)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2639037)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2639036)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2639033)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2638956)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2639040)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2638953)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2639038)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2639036)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2639039)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:33:07,245 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:33:07,246 | fed_df.py:551 | Average fusion training loss : 0.016195167035795748, val accuracy : 0.71898, best val accuracy : 0.737
INFO flwr 2023-09-19 12:33:07,247 | common.py:35 | Avg. local train loss : 3.628861218877137, train acc : 0.9315569444444445
INFO flwr 2023-09-19 12:33:09,930 | server.py:116 | fit progress: (14, 1.7079544311523438, {'server_test_acc': 0.7205}, 2191.9382405299693)
INFO flwr 2023-09-19 12:33:09,931 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-09-19 12:33:12,308 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3074583)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3074584)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3074585)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3074580)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:34:35,428 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-19 12:34:35,441 | fed_df.py:366 | Warm start at round 15
INFO flwr 2023-09-19 12:34:35,509 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3074584)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3074583)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3074585)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3074588)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3074587)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3074589)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3074580)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3074586)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3074588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3074586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3074587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3074589)[0m malloc_consolidate(): invalid chunk size
E0919 12:34:38.136435342 2409550 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 12:35:46,872 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:35:46,873 | fed_df.py:551 | Average fusion training loss : 0.018905794801190496, val accuracy : 0.70904, best val accuracy : 0.7194
INFO flwr 2023-09-19 12:35:46,874 | common.py:35 | Avg. local train loss : 3.585045934282243, train acc : 0.934625
INFO flwr 2023-09-19 12:35:49,596 | server.py:116 | fit progress: (15, 1.6867846130371094, {'server_test_acc': 0.7056}, 2351.603732544929)
INFO flwr 2023-09-19 12:35:49,596 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-09-19 12:35:52,022 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3540759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3540769)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3540767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3540773)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3540768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3540770)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 12:37:18,686 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-09-19 12:37:18,699 | fed_df.py:366 | Warm start at round 16
INFO flwr 2023-09-19 12:37:18,765 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3540770)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3540767)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3540759)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3540768)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3540769)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3540773)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3540764)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3540766)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3540764)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3540764)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3540766)[0m malloc_consolidate(): invalid chunk size
E0919 12:37:37.699326994 3850073 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0919 12:37:57.753767294 3899818 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 12:38:25,271 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:38:25,271 | fed_df.py:551 | Average fusion training loss : 0.018366739636287092, val accuracy : 0.70022, best val accuracy : 0.7104
INFO flwr 2023-09-19 12:38:25,272 | common.py:35 | Avg. local train loss : 3.5608127931132914, train acc : 0.9376152777777778
INFO flwr 2023-09-19 12:38:27,938 | server.py:116 | fit progress: (16, 1.662995022583008, {'server_test_acc': 0.7004}, 2509.945958177559)
INFO flwr 2023-09-19 12:38:27,938 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-09-19 12:38:30,249 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-19 12:39:54,090 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-19 12:39:54,103 | fed_df.py:366 | Warm start at round 17
INFO flwr 2023-09-19 12:39:54,171 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3971177)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3971185)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3971176)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3971186)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3971182)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3971184)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3971183)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3971180)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3971186)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3971183)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3971182)[0m double free or corruption (fasttop)
E0919 12:39:54.815189910   24161 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3971176)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3971177)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3971184)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3971185)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3971180)[0m double free or corruption (fasttop)
INFO flwr 2023-09-19 12:41:01,342 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:41:01,343 | fed_df.py:551 | Average fusion training loss : 0.018922318914439528, val accuracy : 0.7362599999999999, best val accuracy : 0.7466
INFO flwr 2023-09-19 12:41:01,344 | common.py:35 | Avg. local train loss : 3.5827541103586555, train acc : 0.9373513888888889
INFO flwr 2023-09-19 12:41:04,034 | server.py:116 | fit progress: (17, 1.6834350219726562, {'server_test_acc': 0.7254}, 2666.041363920085)
INFO flwr 2023-09-19 12:41:04,034 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-09-19 12:41:06,447 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=196383)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=196399)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:42:29,738 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-19 12:42:29,751 | fed_df.py:366 | Warm start at round 18
INFO flwr 2023-09-19 12:42:29,820 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=196386)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=196383)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=196399)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=196381)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=196387)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=196388)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=196380)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=196385)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=196386)[0m malloc_consolidate(): invalid chunk size
E0919 12:42:30.356728591  440899 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=196387)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=196385)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=196380)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=196388)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=196381)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:43:37,502 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:43:37,502 | fed_df.py:551 | Average fusion training loss : 0.018385167017579078, val accuracy : 0.7188799999999999, best val accuracy : 0.737
INFO flwr 2023-09-19 12:43:37,503 | common.py:35 | Avg. local train loss : 3.4830862298607825, train acc : 0.9435944444444444
INFO flwr 2023-09-19 12:43:40,161 | server.py:116 | fit progress: (18, 1.7014061737060546, {'server_test_acc': 0.7234}, 2822.1682913359255)
INFO flwr 2023-09-19 12:43:40,161 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-09-19 12:43:42,645 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=618940)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=618942)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:45:05,128 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-19 12:45:05,141 | fed_df.py:366 | Warm start at round 19
INFO flwr 2023-09-19 12:45:05,209 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=618937)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=618940)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=618939)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=618938)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=618936)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=618941)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=618934)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=618942)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=618936)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=618941)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=618934)[0m malloc_consolidate(): invalid chunk size
E0919 12:45:06.571708858  442023 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=618937)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=618938)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:46:15,579 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:46:15,579 | fed_df.py:551 | Average fusion training loss : 0.020631067103240638, val accuracy : 0.73166, best val accuracy : 0.7428
INFO flwr 2023-09-19 12:46:15,580 | common.py:35 | Avg. local train loss : 3.4893949350342153, train acc : 0.9443333333333332
INFO flwr 2023-09-19 12:46:18,506 | server.py:116 | fit progress: (19, 1.7021571716308594, {'server_test_acc': 0.7303}, 2980.513818296604)
INFO flwr 2023-09-19 12:46:18,506 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-09-19 12:46:21,067 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-19 12:47:41,292 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-19 12:47:41,305 | fed_df.py:366 | Warm start at round 20
INFO flwr 2023-09-19 12:47:41,373 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1045329)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1045326)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1045333)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1045324)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1045331)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1045334)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1045332)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1045330)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1045324)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1045333)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1045332)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1045334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1045326)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1045329)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1045331)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1045330)[0m malloc_consolidate(): invalid chunk size
E0919 12:48:42.975983286 1417387 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 12:48:57,090 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:48:57,091 | fed_df.py:551 | Average fusion training loss : 0.01864773987652734, val accuracy : 0.73722, best val accuracy : 0.7456
INFO flwr 2023-09-19 12:48:57,091 | common.py:35 | Avg. local train loss : 3.5612190021201973, train acc : 0.9398875000000001
INFO flwr 2023-09-19 12:48:59,778 | server.py:116 | fit progress: (20, 1.6597309020996094, {'server_test_acc': 0.7235}, 3141.7854576380923)
INFO flwr 2023-09-19 12:48:59,778 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-09-19 12:49:02,369 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1487137)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1487107)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1487136)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:50:23,597 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-19 12:50:23,611 | fed_df.py:366 | Warm start at round 21
[2m[36m(launch_and_fit pid=1487109)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:50:23,679 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1487137)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1487135)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1487113)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1487115)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1487109)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1487136)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1487138)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1487107)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1487115)[0m malloc_consolidate(): invalid chunk size
E0919 12:50:24.276240558 1429486 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1487135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1487113)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1487138)[0m malloc_consolidate(): invalid chunk size
E0919 12:50:25.796330215 1730464 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 12:51:39,303 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:51:39,304 | fed_df.py:551 | Average fusion training loss : 0.019804012363776564, val accuracy : 0.7470799999999999, best val accuracy : 0.7592
INFO flwr 2023-09-19 12:51:39,305 | common.py:35 | Avg. local train loss : 3.520564667880535, train acc : 0.9436583333333333
INFO flwr 2023-09-19 12:51:42,232 | server.py:116 | fit progress: (21, 1.5979369323730468, {'server_test_acc': 0.7495}, 3304.239991201088)
INFO flwr 2023-09-19 12:51:42,232 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-09-19 12:51:44,702 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-19 12:53:04,732 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-09-19 12:53:04,746 | fed_df.py:366 | Warm start at round 22
[2m[36m(launch_and_fit pid=1973687)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:53:04,815 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1973687)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1973683)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1973686)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1973691)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1973690)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1973689)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1973688)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1973685)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1973690)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1973686)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1973688)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1973689)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1973683)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1973691)[0m malloc_consolidate(): invalid chunk size
E0919 12:53:07.338239591 1731143 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1973685)[0m double free or corruption (fasttop)
INFO flwr 2023-09-19 12:54:25,881 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:54:25,881 | fed_df.py:551 | Average fusion training loss : 0.021525369070470333, val accuracy : 0.6766, best val accuracy : 0.6878
INFO flwr 2023-09-19 12:54:25,882 | common.py:35 | Avg. local train loss : 3.397000520955771, train acc : 0.9505374999999999
INFO flwr 2023-09-19 12:54:28,682 | server.py:116 | fit progress: (22, 1.7061190185546875, {'server_test_acc': 0.6806}, 3470.6896299701184)
INFO flwr 2023-09-19 12:54:28,682 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-09-19 12:54:31,063 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2425876)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:55:50,709 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-09-19 12:55:50,722 | fed_df.py:366 | Warm start at round 23
INFO flwr 2023-09-19 12:55:50,791 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2425886)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2425896)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2425715)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2425720)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2425718)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2425876)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2425716)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2425735)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2425716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2425886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2425735)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2425720)[0m malloc_consolidate(): invalid chunk size
E0919 12:55:52.981189885 2606312 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2425715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2425896)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2425718)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 12:57:08,793 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:57:08,794 | fed_df.py:551 | Average fusion training loss : 0.021437784616835414, val accuracy : 0.70012, best val accuracy : 0.715
INFO flwr 2023-09-19 12:57:08,794 | common.py:35 | Avg. local train loss : 3.3654481763951476, train acc : 0.9526152777777778
INFO flwr 2023-09-19 12:57:11,538 | server.py:116 | fit progress: (23, 1.715637677001953, {'server_test_acc': 0.6981}, 3633.5455745812505)
INFO flwr 2023-09-19 12:57:11,538 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-09-19 12:57:13,861 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2856736)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 12:58:34,040 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-19 12:58:34,053 | fed_df.py:366 | Warm start at round 24
INFO flwr 2023-09-19 12:58:34,121 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2856736)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2856758)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2856806)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2856807)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2856732)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2856738)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2856730)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2856734)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2856732)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2856738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856758)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2856807)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2856806)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856734)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2856730)[0m double free or corruption (fasttop)
E0919 12:58:36.914781707 2608630 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0919 12:58:51.600306634 3055278 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 12:59:56,200 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 12:59:56,200 | fed_df.py:551 | Average fusion training loss : 0.020512843345757575, val accuracy : 0.7535400000000001, best val accuracy : 0.7608
INFO flwr 2023-09-19 12:59:56,201 | common.py:35 | Avg. local train loss : 3.5369314145296813, train acc : 0.9404166666666666
INFO flwr 2023-09-19 12:59:58,931 | server.py:116 | fit progress: (24, 1.6322333312988282, {'server_test_acc': 0.7458}, 3800.9384029759094)
INFO flwr 2023-09-19 12:59:58,931 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-09-19 13:00:01,343 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3297420)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3297417)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 13:01:21,749 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-19 13:01:21,763 | fed_df.py:366 | Warm start at round 25
INFO flwr 2023-09-19 13:01:21,833 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3297420)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3297419)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3297422)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3297414)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3297423)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3297417)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3297421)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3297424)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3297414)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3297422)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3297421)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3297419)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3297423)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3297424)[0m double free or corruption (fasttop)
E0919 13:02:20.360186563 3101258 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 13:02:34,259 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 13:02:34,259 | fed_df.py:551 | Average fusion training loss : 0.021543444727314637, val accuracy : 0.72752, best val accuracy : 0.7358
INFO flwr 2023-09-19 13:02:34,260 | common.py:35 | Avg. local train loss : 3.383406152762473, train acc : 0.9520583333333335
INFO flwr 2023-09-19 13:02:36,971 | server.py:116 | fit progress: (25, 1.6746769195556641, {'server_test_acc': 0.7271}, 3958.978915475309)
INFO flwr 2023-09-19 13:02:36,971 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-09-19 13:02:39,409 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3721893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3721904)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 13:03:59,978 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-09-19 13:03:59,991 | fed_df.py:366 | Warm start at round 26
INFO flwr 2023-09-19 13:04:00,060 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3721893)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3721904)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3721892)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3721925)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3721891)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3721890)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3721947)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3721894)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3721894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3721892)[0m double free or corruption (fasttop)
E0919 13:04:01.058439526 3934436 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3721891)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3721890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3721925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3721947)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 13:05:11,410 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 13:05:11,410 | fed_df.py:551 | Average fusion training loss : 0.020311089107533917, val accuracy : 0.73612, best val accuracy : 0.7446
INFO flwr 2023-09-19 13:05:11,411 | common.py:35 | Avg. local train loss : 3.4989263804629447, train acc : 0.9445013888888889
INFO flwr 2023-09-19 13:05:14,155 | server.py:116 | fit progress: (26, 1.6555327331542968, {'server_test_acc': 0.7313}, 4116.163008326665)
INFO flwr 2023-09-19 13:05:14,155 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-09-19 13:05:16,633 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-19 13:06:41,646 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-19 13:06:41,659 | fed_df.py:366 | Warm start at round 27
INFO flwr 2023-09-19 13:06:41,728 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4148605)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4148578)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4148711)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4148495)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4148661)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4148710)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4148567)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4148509)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4148495)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4148711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4148509)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4148661)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4148605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4148567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4148578)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4148710)[0m malloc_consolidate(): invalid chunk size
E0919 13:06:44.706101441  219957 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 13:07:49,857 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 13:07:49,857 | fed_df.py:551 | Average fusion training loss : 0.022019565826281905, val accuracy : 0.7383, best val accuracy : 0.745
INFO flwr 2023-09-19 13:07:49,858 | common.py:35 | Avg. local train loss : 3.3641105163842444, train acc : 0.9542597222222222
INFO flwr 2023-09-19 13:07:52,659 | server.py:116 | fit progress: (27, 1.662827264404297, {'server_test_acc': 0.7391}, 4274.666345024481)
INFO flwr 2023-09-19 13:07:52,659 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-09-19 13:07:55,146 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=418697)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-19 13:09:18,982 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-19 13:09:18,995 | fed_df.py:366 | Warm start at round 28
INFO flwr 2023-09-19 13:09:19,063 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=418697)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=418691)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=418695)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=418700)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=418699)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=418696)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=418702)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=418698)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=418698)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=418691)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=418696)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=418695)[0m double free or corruption (fasttop)
E0919 13:09:20.323019088  407807 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=418700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=418699)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=418702)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 13:10:28,198 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 13:10:28,198 | fed_df.py:551 | Average fusion training loss : 0.023040426281513645, val accuracy : 0.74504, best val accuracy : 0.7506
INFO flwr 2023-09-19 13:10:28,199 | common.py:35 | Avg. local train loss : 3.3873937759548425, train acc : 0.9531541666666665
INFO flwr 2023-09-19 13:10:31,121 | server.py:116 | fit progress: (28, 1.6662496673583984, {'server_test_acc': 0.7438}, 4433.128843445331)
INFO flwr 2023-09-19 13:10:31,121 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-09-19 13:10:34,198 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=833987)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=833981)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=833985)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=833982)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 13:11:58,683 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-19 13:11:58,696 | fed_df.py:366 | Warm start at round 29
INFO flwr 2023-09-19 13:11:58,763 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=833987)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=833981)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=833983)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=833984)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=833985)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=833986)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=833982)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=833980)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=833980)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=833983)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=833986)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=833984)[0m malloc_consolidate(): invalid chunk size
E0919 13:12:06.420533258 1097191 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0919 13:12:06.420635508 1097191 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0919 13:12:06.420652433 1097191 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0919 13:12:06.420663519 1097191 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-19 13:13:07,400 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 13:13:07,401 | fed_df.py:551 | Average fusion training loss : 0.02344584810780361, val accuracy : 0.7337199999999999, best val accuracy : 0.7396
INFO flwr 2023-09-19 13:13:07,401 | common.py:35 | Avg. local train loss : 3.368896789290011, train acc : 0.9541055555555555
INFO flwr 2023-09-19 13:13:10,240 | server.py:116 | fit progress: (29, 1.6685989593505859, {'server_test_acc': 0.7325}, 4592.247711607255)
INFO flwr 2023-09-19 13:13:10,240 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-09-19 13:13:12,973 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1264039)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1264042)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1264032)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-19 13:14:34,902 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-09-19 13:14:34,915 | fed_df.py:366 | Warm start at round 30
INFO flwr 2023-09-19 13:14:34,982 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1264032)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1264042)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1264034)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1264039)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1264036)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1264038)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1264037)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1264041)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1264036)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1264038)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1264041)[0m corrupted size vs. prev_size in fastbins
E0919 13:14:36.853427600 1102800 chttp2_transport.cc:1079]             ipv4:145.136.62.26:50934: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1264037)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-19 13:15:40,760 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-19 13:15:40,760 | fed_df.py:551 | Average fusion training loss : 0.022674635623348878, val accuracy : 0.7034400000000001, best val accuracy : 0.7162
INFO flwr 2023-09-19 13:15:40,761 | common.py:35 | Avg. local train loss : 3.1922706927172837, train acc : 0.9641930555555556
INFO flwr 2023-09-19 13:15:43,637 | server.py:116 | fit progress: (30, 1.7245112854003906, {'server_test_acc': 0.7077}, 4745.645221057348)
INFO flwr 2023-09-19 13:15:43,638 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-19 13:15:43,638 | server.py:144 | FL finished in 4745.645555888303
INFO flwr 2023-09-19 13:15:43,638 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-19 13:15:43,639 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-19 13:15:43,639 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.6259392181396484), (2, 1.648829901123047), (3, 1.6981983612060547), (4, 1.6708453094482423), (5, 1.8290144165039062), (6, 1.8149196228027344), (7, 1.7789145874023438), (8, 1.7650592224121093), (9, 1.773674008178711), (10, 1.6478188201904296), (11, 1.659006478881836), (12, 1.7199748077392578), (13, 1.7182119873046875), (14, 1.7079544311523438), (15, 1.6867846130371094), (16, 1.662995022583008), (17, 1.6834350219726562), (18, 1.7014061737060546), (19, 1.7021571716308594), (20, 1.6597309020996094), (21, 1.5979369323730468), (22, 1.7061190185546875), (23, 1.715637677001953), (24, 1.6322333312988282), (25, 1.6746769195556641), (26, 1.6555327331542968), (27, 1.662827264404297), (28, 1.6662496673583984), (29, 1.6685989593505859), (30, 1.7245112854003906)]
INFO flwr 2023-09-19 13:15:43,639 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4374), (2, 0.5233), (3, 0.5468), (4, 0.5792), (5, 0.5826), (6, 0.592), (7, 0.6475), (8, 0.6888), (9, 0.6605), (10, 0.6867), (11, 0.7238), (12, 0.6892), (13, 0.6555), (14, 0.7205), (15, 0.7056), (16, 0.7004), (17, 0.7254), (18, 0.7234), (19, 0.7303), (20, 0.7235), (21, 0.7495), (22, 0.6806), (23, 0.6981), (24, 0.7458), (25, 0.7271), (26, 0.7313), (27, 0.7391), (28, 0.7438), (29, 0.7325), (30, 0.7077)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn26: task 0: Aborted
srun: Terminating StepId=3894397.0
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3894397
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 02:29:56
CPU Efficiency: 10.37% of 1-00:06:18 core-walltime
Job Wall-clock time: 01:20:21
Memory Utilized: 45.43 GB
Memory Efficiency: 37.85% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
