-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:20000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:pathmnist
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:colonpath_sample.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:9
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=20000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/colonpath_sample.jpg', targetpath='/scratch-local/sunnys.3358499/1692176627_583928592', seed=84, img_per_thread=1111)
will save 20000 patches in /scratch-local/sunnys.3358499/1692176627_583928592/single_img_crops/crops
20000 took 0.08min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-16 11:04:06,112 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-16 11:04:06,112 | simulate.py:55 | Reading args from argument parser
Downloading https://zenodo.org/record/6496656/files/pathmnist.npz?download=1 to /scratch-local/sunnys.3358499/1692176627_583928592/pathmnist.npz
Generating unified pathmnist dataset
Class histogram for 0-th partition (alpha=100.0, 9 classes): [442 400 475 553 489 529 484 583 545]
INFO flwr 2023-08-16 11:05:12,948 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-16 11:05:15,443	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-16 11:05:16,457 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 103079215104.0, 'CPU': 18.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0, 'node:145.136.62.48': 1.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-08-16 11:05:16,457 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-16 11:05:16,457 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-16 11:05:16,457 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-16 11:05:27,547 | server.py:91 | initial parameters (loss, other metrics): 2.192614644616427, {'server_test_acc': 0.18704735376044568}
INFO flwr 2023-08-16 11:05:27,547 | server.py:101 | FL starting
DEBUG flwr 2023-08-16 11:05:32,580 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1878001)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1878006)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:06:25,536 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1878007)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1878000)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:06:25,744 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-16 11:06:25,871 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1878005)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1878000)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1878007)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1878001)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1878003)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1878004)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1878002)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1878006)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1878002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1878005)[0m malloc_consolidate(): invalid chunk size
E0816 11:06:26.470301344 1924902 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0816 11:06:26.470498066 1924902 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=1878003)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1878004)[0m double free or corruption (fasttop)
E0816 11:06:27.031248776 1925105 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-16 11:06:54,524 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:06:54,524 | fed_df.py:547 | Average fusion training loss : 0.12441498911380768, val accuracy : 0.49919964428634955, best val accuracy : 0.548910626945309
INFO flwr 2023-08-16 11:06:54,526 | common.py:35 | Avg. local train loss : 8.377494710311293, train acc : 0.7123194444444445
INFO flwr 2023-08-16 11:06:56,616 | server.py:116 | fit progress: (1, 1.8604065847264026, {'server_test_acc': 0.4967966573816156}, 89.06910525890999)
INFO flwr 2023-08-16 11:06:56,616 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-16 11:07:01,549 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1951536)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:07:52,803 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-16 11:07:53,101 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1951546)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1951536)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1951540)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1951543)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1951541)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1951542)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1951545)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1951546)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1951547)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1951543)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951540)[0m double free or corruption (fasttop)
E0816 11:07:53.789952071 1925717 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=1951541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951547)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1951542)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:08:21,507 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:08:21,508 | fed_df.py:547 | Average fusion training loss : 0.06177261859178543, val accuracy : 0.43390395731436193, best val accuracy : 0.4722098710538017
INFO flwr 2023-08-16 11:08:21,510 | common.py:35 | Avg. local train loss : 7.067162404581903, train acc : 0.79220987654321
INFO flwr 2023-08-16 11:08:23,634 | server.py:116 | fit progress: (2, 2.1096618227307844, {'server_test_acc': 0.3761838440111421}, 176.0868254781235)
INFO flwr 2023-08-16 11:08:23,634 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-16 11:08:28,525 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:09:20,635 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2024770)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2024764)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:09:20,915 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2024767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2024764)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2024766)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2024768)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2024771)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2024769)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2024772)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2024770)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2024767)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2024766)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2024768)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2024772)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2024771)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2024769)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:09:54,272 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:09:54,272 | fed_df.py:547 | Average fusion training loss : 0.10155164840817452, val accuracy : 0.5099377501111606, best val accuracy : 0.5808136949755447
INFO flwr 2023-08-16 11:09:54,274 | common.py:35 | Avg. local train loss : 7.266256651282311, train acc : 0.7805077160493826
INFO flwr 2023-08-16 11:09:56,420 | server.py:116 | fit progress: (3, 2.170837488944816, {'server_test_acc': 0.5566852367688022}, 268.8727299529128)
INFO flwr 2023-08-16 11:09:56,420 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-16 11:10:01,410 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2098445)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2098447)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:10:53,526 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2098441)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:10:53,805 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2098441)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2098443)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2098442)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2098444)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2098445)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2098447)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2098439)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2098446)[0m Fitting Client 9
E0816 11:10:54.176764660 2144943 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=2098446)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2098439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2098442)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2098444)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2098443)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:11:22,283 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:11:22,284 | fed_df.py:547 | Average fusion training loss : 0.07928943192958832, val accuracy : 0.5246998666073811, best val accuracy : 0.5820364606491775
INFO flwr 2023-08-16 11:11:22,286 | common.py:35 | Avg. local train loss : 7.296646350994706, train acc : 0.7811141975308642
INFO flwr 2023-08-16 11:11:24,432 | server.py:116 | fit progress: (4, 1.6612039454468113, {'server_test_acc': 0.625766016713092}, 356.8851412530057)
INFO flwr 2023-08-16 11:11:24,432 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-16 11:11:29,405 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2171630)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:12:20,800 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2171634)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:12:21,010 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-16 11:12:21,136 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2171630)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2171632)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2171634)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2171635)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2171633)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2171638)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2171637)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2171636)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2171633)[0m malloc_consolidate(): invalid chunk size
E0816 11:12:21.573778190 2145286 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2171632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2171637)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2171638)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2171635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2171636)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:12:49,917 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:12:49,917 | fed_df.py:547 | Average fusion training loss : 0.1400285784304142, val accuracy : 0.47714539795464656, best val accuracy : 0.5534682080924855
INFO flwr 2023-08-16 11:12:49,919 | common.py:35 | Avg. local train loss : 7.192703422904015, train acc : 0.7873996913580247
INFO flwr 2023-08-16 11:12:52,051 | server.py:116 | fit progress: (5, 2.443435620597478, {'server_test_acc': 0.4384401114206128}, 444.50394463096745)
INFO flwr 2023-08-16 11:12:52,051 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-16 11:12:56,957 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2245250)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245249)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:13:48,720 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-16 11:13:49,004 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2245252)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2245250)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2245249)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2245253)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2245257)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2245256)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2245254)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2245255)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2245256)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245257)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245255)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2245252)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245253)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245254)[0m malloc_consolidate(): invalid chunk size
E0816 11:13:50.087768677 2292398 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-16 11:14:17,851 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:14:17,852 | fed_df.py:547 | Average fusion training loss : 0.09728524056077004, val accuracy : 0.5506224988883949, best val accuracy : 0.5852601156069365
INFO flwr 2023-08-16 11:14:17,854 | common.py:35 | Avg. local train loss : 6.074528923816979, train acc : 0.8550216049382716
INFO flwr 2023-08-16 11:14:20,024 | server.py:116 | fit progress: (6, 2.047211986531122, {'server_test_acc': 0.4805013927576602}, 532.4772191660013)
INFO flwr 2023-08-16 11:14:20,024 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-16 11:14:24,979 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2318437)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2318433)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:15:16,568 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2318431)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:15:16,846 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2318433)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2318431)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2318437)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2318436)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2318438)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2318440)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2318435)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2318439)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2318439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2318440)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2318436)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2318435)[0m malloc_consolidate(): invalid chunk size
E0816 11:15:20.239564152 2366384 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-16 11:15:45,598 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:15:45,598 | fed_df.py:547 | Average fusion training loss : 0.10926116198301315, val accuracy : 0.5389506447309915, best val accuracy : 0.6089373054690974
INFO flwr 2023-08-16 11:15:45,600 | common.py:35 | Avg. local train loss : 6.399573687650264, train acc : 0.8377824074074075
INFO flwr 2023-08-16 11:15:47,800 | server.py:116 | fit progress: (7, 1.853629314667003, {'server_test_acc': 0.5084958217270195}, 620.2529112640768)
INFO flwr 2023-08-16 11:15:47,800 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-16 11:15:52,746 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2392057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392062)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:16:44,004 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-16 11:16:44,283 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2392057)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2392056)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2392062)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2392063)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2392064)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2392066)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2392059)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2392065)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2392056)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392065)[0m malloc_consolidate(): invalid chunk size
E0816 11:16:45.042113391 2438829 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=2392064)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392066)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2392063)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2392059)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:17:13,136 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:17:13,137 | fed_df.py:547 | Average fusion training loss : 0.10714244005084038, val accuracy : 0.6315695864828813, best val accuracy : 0.6597376611827479
INFO flwr 2023-08-16 11:17:13,139 | common.py:35 | Avg. local train loss : 6.392615976557136, train acc : 0.8372824074074074
INFO flwr 2023-08-16 11:17:15,314 | server.py:116 | fit progress: (8, 1.657655411244767, {'server_test_acc': 0.5449860724233984}, 707.7668655540328)
INFO flwr 2023-08-16 11:17:15,314 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-16 11:17:20,264 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:18:11,663 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-16 11:18:11,942 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2465242)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2465243)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2465241)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2465240)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2465244)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2465246)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2465236)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2465245)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2465240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465242)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2465243)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465246)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2465244)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465245)[0m malloc_consolidate(): invalid chunk size
E0816 11:18:13.834914108 2513403 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-16 11:18:40,924 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:18:40,924 | fed_df.py:547 | Average fusion training loss : 0.08311899058520794, val accuracy : 0.5841929746554024, best val accuracy : 0.6211649622054246
INFO flwr 2023-08-16 11:18:40,926 | common.py:35 | Avg. local train loss : 6.130012046173215, train acc : 0.8522006172839507
INFO flwr 2023-08-16 11:18:43,118 | server.py:116 | fit progress: (9, 2.083323677403017, {'server_test_acc': 0.481058495821727}, 795.5714064999484)
INFO flwr 2023-08-16 11:18:43,118 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-16 11:18:48,054 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2539773)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:19:40,209 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2539775)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539779)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:19:40,421 | fed_df.py:365 | Warm start at round 10
[2m[36m(launch_and_fit pid=2539776)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:19:40,550 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2539773)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2539775)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2539777)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2539779)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2539776)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2539778)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2539780)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2539781)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2539777)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539778)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2539780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539781)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:20:09,906 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:20:09,907 | fed_df.py:547 | Average fusion training loss : 0.08584768643975257, val accuracy : 0.6758337038683859, best val accuracy : 0.7493330369052913
INFO flwr 2023-08-16 11:20:09,909 | common.py:35 | Avg. local train loss : 6.401002042554319, train acc : 0.8381342592592591
INFO flwr 2023-08-16 11:20:12,094 | server.py:116 | fit progress: (10, 2.446035850546154, {'server_test_acc': 0.6059888579387187}, 884.5476435991004)
INFO flwr 2023-08-16 11:20:12,095 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-16 11:20:17,145 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2632493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2632496)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:21:08,746 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2632515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2632520)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:21:09,027 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2632493)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2632496)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2632500)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2632515)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2632520)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2632554)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2632555)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2632501)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2632554)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2632555)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2632500)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2632501)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:21:37,967 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:21:37,967 | fed_df.py:547 | Average fusion training loss : 0.10851288583874702, val accuracy : 0.6322810137839039, best val accuracy : 0.6707425522454424
INFO flwr 2023-08-16 11:21:37,969 | common.py:35 | Avg. local train loss : 5.83969035409391, train acc : 0.8690154320987654
INFO flwr 2023-08-16 11:21:40,166 | server.py:116 | fit progress: (11, 1.7677078986898438, {'server_test_acc': 0.5635097493036212}, 972.619463392999)
INFO flwr 2023-08-16 11:21:40,167 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-16 11:21:45,124 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2711373)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2711379)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:22:36,751 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-16 11:22:37,031 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2711373)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2711378)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2711376)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2711375)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2711377)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2711380)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2711381)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2711379)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2711375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2711381)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2711376)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2711377)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2711378)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2711380)[0m malloc_consolidate(): invalid chunk size
E0816 11:22:46.713406453 2513741 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-16 11:23:06,043 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:23:06,043 | fed_df.py:547 | Average fusion training loss : 0.061908965110778806, val accuracy : 0.7170964873277011, best val accuracy : 0.7765673632725656
INFO flwr 2023-08-16 11:23:06,045 | common.py:35 | Avg. local train loss : 5.874876166135073, train acc : 0.8675555555555555
INFO flwr 2023-08-16 11:23:08,217 | server.py:116 | fit progress: (12, 1.4939562579715484, {'server_test_acc': 0.7005571030640668}, 1060.669777666917)
INFO flwr 2023-08-16 11:23:08,217 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-16 11:23:13,193 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2784759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2784763)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:24:04,612 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2784762)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:24:04,892 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2784759)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2784761)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2784763)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2784765)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2784767)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2784766)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2784764)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2784762)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2784767)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2784766)[0m malloc_consolidate(): invalid chunk size
E0816 11:24:05.463868488 2765793 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=2784761)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2784765)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2784764)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:24:34,190 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:24:34,191 | fed_df.py:547 | Average fusion training loss : 0.03761838455498218, val accuracy : 0.7518452645620275, best val accuracy : 0.7877945753668297
INFO flwr 2023-08-16 11:24:34,193 | common.py:35 | Avg. local train loss : 5.552407553792, train acc : 0.888628086419753
INFO flwr 2023-08-16 11:24:36,380 | server.py:116 | fit progress: (13, 0.8965960037741488, {'server_test_acc': 0.7653203342618384}, 1148.8330995419528)
INFO flwr 2023-08-16 11:24:36,380 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-16 11:24:41,313 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2858170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2858171)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2858172)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:25:33,457 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-16 11:25:33,738 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2858171)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2858172)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2858170)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2858174)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2858173)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2858175)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2858177)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2858176)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2858177)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2858174)[0m malloc_consolidate(): invalid chunk size
E0816 11:25:34.520827052 2831795 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=2858173)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2858175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2858176)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:26:02,625 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:26:02,626 | fed_df.py:547 | Average fusion training loss : 0.030098780773580074, val accuracy : 0.7024010671409515, best val accuracy : 0.7259893285904847
INFO flwr 2023-08-16 11:26:02,628 | common.py:35 | Avg. local train loss : 5.7806769769638775, train acc : 0.8746404320987654
INFO flwr 2023-08-16 11:26:04,828 | server.py:116 | fit progress: (14, 1.5107595629678796, {'server_test_acc': 0.682033426183844}, 1237.280961478129)
INFO flwr 2023-08-16 11:26:04,828 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-16 11:26:09,751 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2931789)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:27:01,151 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2931797)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:27:01,362 | fed_df.py:365 | Warm start at round 15
[2m[36m(launch_and_fit pid=2931792)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:27:01,490 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2931789)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2931792)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2931794)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2931795)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2931793)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2931797)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2931796)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2931798)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2931795)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2931798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2931794)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2931796)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2931793)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:27:30,490 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:27:30,490 | fed_df.py:547 | Average fusion training loss : 0.09083113220334053, val accuracy : 0.6604490884837706, best val accuracy : 0.7835704757670076
INFO flwr 2023-08-16 11:27:30,492 | common.py:35 | Avg. local train loss : 5.670425130054355, train acc : 0.88175
INFO flwr 2023-08-16 11:27:32,668 | server.py:116 | fit progress: (15, 2.316953443484718, {'server_test_acc': 0.6625348189415042}, 1325.1206799149513)
INFO flwr 2023-08-16 11:27:32,668 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-16 11:27:37,661 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:28:29,315 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-16 11:28:29,597 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3004991)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3004992)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3004989)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3004994)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3004995)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3004993)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3004990)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3004996)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3004993)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3004991)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3004992)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3004995)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3004996)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3004994)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3004990)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3004989)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:29:03,692 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:29:03,692 | fed_df.py:547 | Average fusion training loss : 0.05414899979531765, val accuracy : 0.7744330813694975, best val accuracy : 0.8065807025344598
INFO flwr 2023-08-16 11:29:03,694 | common.py:35 | Avg. local train loss : 5.237744900211692, train acc : 0.9053348765432099
INFO flwr 2023-08-16 11:29:05,889 | server.py:116 | fit progress: (16, 2.1533271659383533, {'server_test_acc': 0.6511142061281338}, 1418.3418614729308)
INFO flwr 2023-08-16 11:29:05,889 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-16 11:29:10,904 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3078541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3078543)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:30:03,439 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3078538)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3078544)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:30:03,725 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3078538)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3078541)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3078540)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3078539)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3078542)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3078544)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3078545)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3078543)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3078542)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3078545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3078539)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3078540)[0m malloc_consolidate(): invalid chunk size
E0816 11:30:07.946530219 2905336 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
E0816 11:30:07.946608492 2905336 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-16 11:30:32,784 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:30:32,784 | fed_df.py:547 | Average fusion training loss : 0.04090467692166567, val accuracy : 0.8058692752334371, best val accuracy : 0.8277012005335704
INFO flwr 2023-08-16 11:30:32,786 | common.py:35 | Avg. local train loss : 5.328107979893684, train acc : 0.9005462962962961
INFO flwr 2023-08-16 11:30:34,950 | server.py:116 | fit progress: (17, 2.2637984182841264, {'server_test_acc': 0.7125348189415042}, 1507.40294523607)
INFO flwr 2023-08-16 11:30:34,950 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-16 11:30:39,945 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3151838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3151841)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:31:33,260 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3151843)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:31:33,541 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3151841)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3151843)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3151839)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3151838)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3151842)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3151837)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3151840)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3151836)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3151839)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3151836)[0m double free or corruption (fasttop)
E0816 11:31:34.458871146 3128750 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=3151840)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3151842)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3151837)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:32:02,626 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:32:02,627 | fed_df.py:547 | Average fusion training loss : 0.02616679947078228, val accuracy : 0.7821698532681192, best val accuracy : 0.8082481102712317
INFO flwr 2023-08-16 11:32:02,629 | common.py:35 | Avg. local train loss : 5.246676366589963, train acc : 0.9072638888888889
INFO flwr 2023-08-16 11:32:04,786 | server.py:116 | fit progress: (18, 2.0148611059427926, {'server_test_acc': 0.6345403899721448}, 1597.2390812730882)
INFO flwr 2023-08-16 11:32:04,786 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-16 11:32:09,737 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3225381)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3225377)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:33:01,556 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-16 11:33:01,836 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3225377)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3225381)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3225379)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3225383)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3225385)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3225384)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3225387)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3225386)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3225379)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3225387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3225384)[0m malloc_consolidate(): invalid chunk size
E0816 11:33:02.636456084 3272405 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=3225385)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3225383)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3225386)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:33:31,119 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:33:31,119 | fed_df.py:547 | Average fusion training loss : 0.03970448834449053, val accuracy : 0.8054913294797688, best val accuracy : 0.8231436193863939
INFO flwr 2023-08-16 11:33:31,121 | common.py:35 | Avg. local train loss : 5.334570176154375, train acc : 0.9014305555555555
INFO flwr 2023-08-16 11:33:33,309 | server.py:116 | fit progress: (19, 2.398664494809334, {'server_test_acc': 0.6753481894150418}, 1685.762095146114)
INFO flwr 2023-08-16 11:33:33,309 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-16 11:33:38,345 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3298569)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:34:29,974 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3298571)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:34:30,186 | fed_df.py:365 | Warm start at round 20
[2m[36m(launch_and_fit pid=3298574)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298577)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:34:30,315 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3298569)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3298571)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3298574)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3298575)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3298577)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3298576)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3298578)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3298579)[0m Fitting Client 0
E0816 11:34:30.902325640 3272473 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=3298579)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298575)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3298578)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298576)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:34:59,637 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:34:59,638 | fed_df.py:547 | Average fusion training loss : 0.06014061018824577, val accuracy : 0.7234548688305914, best val accuracy : 0.8233659404179635
INFO flwr 2023-08-16 11:34:59,640 | common.py:35 | Avg. local train loss : 5.390684295073152, train acc : 0.8987067901234569
INFO flwr 2023-08-16 11:35:01,875 | server.py:116 | fit progress: (20, 2.4286900516339998, {'server_test_acc': 0.7655988857938719}, 1774.3277629730292)
INFO flwr 2023-08-16 11:35:01,875 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-16 11:35:06,895 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3376247)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:35:59,274 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-16 11:35:59,556 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3376241)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3376244)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3376246)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3376240)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3376247)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3376245)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3376243)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3376242)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3376240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3376242)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3376244)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3376246)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3376245)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3376241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3376243)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:36:28,927 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:36:28,927 | fed_df.py:547 | Average fusion training loss : 0.0291629034653306, val accuracy : 0.8365718096931969, best val accuracy : 0.8424855491329479
INFO flwr 2023-08-16 11:36:28,929 | common.py:35 | Avg. local train loss : 4.963934683054685, train acc : 0.9223904320987653
INFO flwr 2023-08-16 11:36:31,126 | server.py:116 | fit progress: (21, 2.0955404522027146, {'server_test_acc': 0.6958217270194986}, 1863.5787221039645)
INFO flwr 2023-08-16 11:36:31,126 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-16 11:36:36,173 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3470273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3470277)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:37:28,495 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-16 11:37:28,776 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3470273)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3470275)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3470277)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3470276)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3470274)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3470280)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3470278)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3470279)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3470280)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3470278)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3470279)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3470276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3470274)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3470275)[0m double free or corruption (fasttop)
E0816 11:37:52.222826492 3534490 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:37:57,916 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:37:57,916 | fed_df.py:547 | Average fusion training loss : 0.021380749613046646, val accuracy : 0.8216318363717207, best val accuracy : 0.8619386393952868
INFO flwr 2023-08-16 11:37:57,918 | common.py:35 | Avg. local train loss : 4.997351830080152, train acc : 0.9219320987654321
INFO flwr 2023-08-16 11:38:00,126 | server.py:116 | fit progress: (22, 1.3413913045420953, {'server_test_acc': 0.7805013927576602}, 1952.578698772937)
INFO flwr 2023-08-16 11:38:00,126 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-16 11:38:05,096 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3543839)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:38:56,435 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-16 11:38:56,714 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3543839)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3543842)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3543843)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3543845)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3543846)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3543844)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3543848)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3543847)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3543842)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3543846)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3543845)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3543844)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3543848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3543847)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3543843)[0m malloc_consolidate(): invalid chunk size
E0816 11:38:58.792987872 3591484 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 11:39:20.337658381 3591754 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:39:26,000 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:39:26,000 | fed_df.py:547 | Average fusion training loss : 0.03303005044162274, val accuracy : 0.8405291240551357, best val accuracy : 0.8652734548688306
INFO flwr 2023-08-16 11:39:26,002 | common.py:35 | Avg. local train loss : 4.9754523174837235, train acc : 0.9236327160493828
INFO flwr 2023-08-16 11:39:28,340 | server.py:116 | fit progress: (23, 0.9321270329042397, {'server_test_acc': 0.7622562674094707}, 2040.7930012401193)
INFO flwr 2023-08-16 11:39:28,340 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-16 11:39:33,330 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3616986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3616987)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3616991)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:40:24,714 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-16 11:40:24,998 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3616987)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3616989)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3616991)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3616986)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3616995)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3616994)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3616992)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3616993)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3616989)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3616992)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3616995)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3616994)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3616993)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:40:54,230 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:40:54,231 | fed_df.py:547 | Average fusion training loss : 0.033459610901772976, val accuracy : 0.7620497999110716, best val accuracy : 0.801578479324144
INFO flwr 2023-08-16 11:40:54,233 | common.py:35 | Avg. local train loss : 5.121361623331905, train acc : 0.9147037037037038
INFO flwr 2023-08-16 11:40:56,413 | server.py:116 | fit progress: (24, 1.4958657339090757, {'server_test_acc': 0.6642061281337047}, 2128.866220935015)
INFO flwr 2023-08-16 11:40:56,413 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-16 11:41:01,577 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3690568)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 11:41:53,929 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-16 11:41:54,141 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-16 11:41:54,271 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3690570)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3690568)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3690566)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3690573)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3690572)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3690569)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3690567)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3690571)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3690573)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3690571)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3690567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3690566)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3690569)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3690572)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3690570)[0m malloc_consolidate(): invalid chunk size
E0816 11:41:56.265123185 3738539 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:42:23,462 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:42:23,463 | fed_df.py:547 | Average fusion training loss : 0.07950051319599151, val accuracy : 0.7500666963094709, best val accuracy : 0.8443752779012894
INFO flwr 2023-08-16 11:42:23,464 | common.py:35 | Avg. local train loss : 5.078808991238476, train acc : 0.9174783950617285
INFO flwr 2023-08-16 11:42:25,666 | server.py:116 | fit progress: (25, 1.513375410595312, {'server_test_acc': 0.7541782729805014}, 2218.119089364074)
INFO flwr 2023-08-16 11:42:25,666 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-16 11:42:30,758 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3763809)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:43:22,888 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3763814)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:43:23,170 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3763809)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3763810)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3763813)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3763814)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3763815)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3763817)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3763816)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3763818)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3763813)[0m malloc_consolidate(): invalid chunk size
E0816 11:43:23.811259956 3810513 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3763810)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3763815)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3763818)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3763816)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3763817)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:43:52,373 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:43:52,374 | fed_df.py:547 | Average fusion training loss : 0.04321336244791746, val accuracy : 0.8256336149399732, best val accuracy : 0.869386393952868
INFO flwr 2023-08-16 11:43:52,376 | common.py:35 | Avg. local train loss : 4.794389763474465, train acc : 0.9320956790123457
INFO flwr 2023-08-16 11:43:54,618 | server.py:116 | fit progress: (26, 0.9502193421706516, {'server_test_acc': 0.7972144846796657}, 2307.0708650220186)
INFO flwr 2023-08-16 11:43:54,618 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-16 11:43:59,571 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:44:51,002 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-16 11:44:51,282 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3837410)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3837413)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3837416)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3837419)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3837420)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3837417)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3837412)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3837418)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3837413)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837419)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837412)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3837420)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837416)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3837417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3837410)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3837418)[0m double free or corruption (fasttop)
E0816 11:44:54.827731118 3810815 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:45:20,830 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:45:20,831 | fed_df.py:547 | Average fusion training loss : 0.047999187380075456, val accuracy : 0.835460204535349, best val accuracy : 0.8772787905735883
INFO flwr 2023-08-16 11:45:20,833 | common.py:35 | Avg. local train loss : 4.855152616091073, train acc : 0.9301913580246913
INFO flwr 2023-08-16 11:45:23,007 | server.py:116 | fit progress: (27, 1.0194654885772876, {'server_test_acc': 0.8256267409470752}, 2395.4601946829353)
INFO flwr 2023-08-16 11:45:23,007 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-16 11:45:28,096 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3910695)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3910694)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:46:19,465 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3910698)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:46:19,747 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3910694)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3910695)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3910697)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3910696)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3910698)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3910699)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3910692)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3910700)[0m Fitting Client 8
E0816 11:46:20.108134584 3957036 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3910697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3910696)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3910699)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3910692)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3910700)[0m malloc_consolidate(): invalid chunk size
E0816 11:46:26.621372232 3957372 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 11:46:49,026 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:46:49,027 | fed_df.py:547 | Average fusion training loss : 0.03412935154885054, val accuracy : 0.8200088928412628, best val accuracy : 0.8365940417963539
INFO flwr 2023-08-16 11:46:49,029 | common.py:35 | Avg. local train loss : 4.873531232029199, train acc : 0.9290756172839506
INFO flwr 2023-08-16 11:46:51,216 | server.py:116 | fit progress: (28, 1.1893787632413562, {'server_test_acc': 0.778133704735376}, 2483.6688921221066)
INFO flwr 2023-08-16 11:46:51,216 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-16 11:46:56,170 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 11:47:46,978 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-16 11:47:47,256 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3984256)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3984255)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3984262)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3984263)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3984264)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3984265)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3984266)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3984260)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3984255)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3984256)[0m malloc_consolidate(): invalid chunk size
E0816 11:47:47.689262117 3962982 chttp2_transport.cc:1079]             ipv4:145.136.62.48:48536: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3984263)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3984264)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3984266)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3984262)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3984265)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3984260)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 11:48:16,682 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:48:16,683 | fed_df.py:547 | Average fusion training loss : 0.05584111730754376, val accuracy : 0.8426856380613605, best val accuracy : 0.8507114273010227
INFO flwr 2023-08-16 11:48:16,685 | common.py:35 | Avg. local train loss : 4.875516108982264, train acc : 0.9290740740740739
INFO flwr 2023-08-16 11:48:18,884 | server.py:116 | fit progress: (29, 1.1149826189269594, {'server_test_acc': 0.7610027855153203}, 2571.336675231112)
INFO flwr 2023-08-16 11:48:18,884 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-16 11:48:23,849 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4057505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4057544)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4057558)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 11:49:15,723 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-16 11:49:15,934 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-16 11:49:16,061 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4057505)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4057544)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4057546)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4057547)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4057551)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4057549)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4057557)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4057558)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4057551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4057549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4057557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4057547)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4057546)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 11:49:45,479 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 11:49:45,479 | fed_df.py:547 | Average fusion training loss : 0.034061316031962635, val accuracy : 0.8305469097376612, best val accuracy : 0.8837261004891063
INFO flwr 2023-08-16 11:49:45,481 | common.py:35 | Avg. local train loss : 4.801811739616096, train acc : 0.9334197530864198
INFO flwr 2023-08-16 11:49:47,698 | server.py:116 | fit progress: (30, 0.9620711131348252, {'server_test_acc': 0.7986072423398328}, 2660.151369320927)
INFO flwr 2023-08-16 11:49:47,698 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-16 11:49:47,699 | server.py:144 | FL finished in 2660.15172983706
INFO flwr 2023-08-16 11:49:47,699 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-16 11:49:47,700 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-16 11:49:47,700 | app.py:204 | app_fit: losses_centralized [(0, 2.192614644616427), (1, 1.8604065847264026), (2, 2.1096618227307844), (3, 2.170837488944816), (4, 1.6612039454468113), (5, 2.443435620597478), (6, 2.047211986531122), (7, 1.853629314667003), (8, 1.657655411244767), (9, 2.083323677403017), (10, 2.446035850546154), (11, 1.7677078986898438), (12, 1.4939562579715484), (13, 0.8965960037741488), (14, 1.5107595629678796), (15, 2.316953443484718), (16, 2.1533271659383533), (17, 2.2637984182841264), (18, 2.0148611059427926), (19, 2.398664494809334), (20, 2.4286900516339998), (21, 2.0955404522027146), (22, 1.3413913045420953), (23, 0.9321270329042397), (24, 1.4958657339090757), (25, 1.513375410595312), (26, 0.9502193421706516), (27, 1.0194654885772876), (28, 1.1893787632413562), (29, 1.1149826189269594), (30, 0.9620711131348252)]
INFO flwr 2023-08-16 11:49:47,700 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.18704735376044568), (1, 0.4967966573816156), (2, 0.3761838440111421), (3, 0.5566852367688022), (4, 0.625766016713092), (5, 0.4384401114206128), (6, 0.4805013927576602), (7, 0.5084958217270195), (8, 0.5449860724233984), (9, 0.481058495821727), (10, 0.6059888579387187), (11, 0.5635097493036212), (12, 0.7005571030640668), (13, 0.7653203342618384), (14, 0.682033426183844), (15, 0.6625348189415042), (16, 0.6511142061281338), (17, 0.7125348189415042), (18, 0.6345403899721448), (19, 0.6753481894150418), (20, 0.7655988857938719), (21, 0.6958217270194986), (22, 0.7805013927576602), (23, 0.7622562674094707), (24, 0.6642061281337047), (25, 0.7541782729805014), (26, 0.7972144846796657), (27, 0.8256267409470752), (28, 0.778133704735376), (29, 0.7610027855153203), (30, 0.7986072423398328)]}
double free or corruption (fasttop)
srun: error: gcn48: task 0: Aborted
srun: Terminating StepId=3358499.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3358499
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:52:27
CPU Efficiency: 13.48% of 13:54:00 core-walltime
Job Wall-clock time: 00:46:20
Memory Utilized: 57.33 GB
Memory Efficiency: 47.77% of 120.00 GB
