-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3430911/1692575016_488188068', seed=84, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3430911/1692575016_488188068/single_img_crops/crops
50000 took 0.51min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-21 01:44:26,403 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-21 01:44:26,403 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3430911/1692575016_488188068/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3430911/1692575016_488188068/cifar-10-python.tar.gz to /scratch-local/sunnys.3430911/1692575016_488188068
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
INFO flwr 2023-08-21 01:45:57,747 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-21 01:46:00,579	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-21 01:46:01,582 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.26': 1.0, 'GPU': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'accelerator_type:A100': 1.0, 'CPU': 18.0}
INFO flwr 2023-08-21 01:46:01,583 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-21 01:46:01,583 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-21 01:46:01,583 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-21 01:46:12,269 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-21 01:46:12,269 | server.py:101 | FL starting
DEBUG flwr 2023-08-21 01:46:18,398 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1295545)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:47:09,289 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-21 01:47:09,396 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-21 01:47:09,486 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1295549)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1295547)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1295543)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1295542)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1295548)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1295545)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1295544)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1295546)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1295546)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1295549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1295547)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1295542)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1295543)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1295548)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1295544)[0m malloc_consolidate(): invalid chunk size
E0821 01:47:11.115229329 1292396 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-21 01:48:30,592 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:48:30,592 | fed_df.py:547 | Average fusion training loss : 0.01191171345859766, val accuracy : 0.36401999999999995, best val accuracy : 0.3966
INFO flwr 2023-08-21 01:48:30,593 | common.py:35 | Avg. local train loss : 7.015585138648748, train acc : 0.5684083333333333
INFO flwr 2023-08-21 01:48:33,029 | server.py:116 | fit progress: (1, 1.7254804138183595, {'server_test_acc': 0.396}, 140.7601418858394)
INFO flwr 2023-08-21 01:48:33,030 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-21 01:48:38,808 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1421788)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:49:26,538 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1421791)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 01:49:26,645 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-21 01:49:26,734 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1421792)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1421787)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1421788)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1421794)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1421793)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1421790)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1421791)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1421789)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1421789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1421794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1421792)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1421793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1421790)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1421787)[0m malloc_consolidate(): invalid chunk size
E0821 01:49:28.996866489 1343946 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-21 01:50:52,972 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:50:52,972 | fed_df.py:547 | Average fusion training loss : 0.007321658032014966, val accuracy : 0.46574, best val accuracy : 0.4908
INFO flwr 2023-08-21 01:50:52,973 | common.py:35 | Avg. local train loss : 6.965854830294847, train acc : 0.5728555555555555
INFO flwr 2023-08-21 01:50:55,527 | server.py:116 | fit progress: (2, 1.4514095825195312, {'server_test_acc': 0.4823}, 283.2574227331206)
INFO flwr 2023-08-21 01:50:55,527 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-21 01:51:01,457 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 01:51:48,110 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-21 01:51:48,218 | fed_df.py:365 | Warm start at round 3
[2m[36m(launch_and_fit pid=1548262)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 01:51:48,307 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1548262)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1548265)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1548267)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1548264)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1548268)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1548269)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1548270)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1548266)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1548267)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1548265)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1548264)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1548266)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1548269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1548268)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1548270)[0m malloc_consolidate(): invalid chunk size
E0821 01:51:50.655769007 1470923 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-21 01:53:13,934 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:53:13,935 | fed_df.py:547 | Average fusion training loss : 0.008207490313798188, val accuracy : 0.54254, best val accuracy : 0.5586
INFO flwr 2023-08-21 01:53:13,936 | common.py:35 | Avg. local train loss : 5.457778091728688, train acc : 0.7293444444444445
INFO flwr 2023-08-21 01:53:16,535 | server.py:116 | fit progress: (3, 1.2924409271240234, {'server_test_acc': 0.5581}, 424.26552513986826)
INFO flwr 2023-08-21 01:53:16,535 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-21 01:53:22,425 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1681477)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:54:09,711 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-21 01:54:09,819 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-21 01:54:09,908 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1681483)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1681482)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1681443)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1681477)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1681439)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1681481)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1681454)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1681444)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1681482)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1681483)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1681443)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1681439)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1681481)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1681444)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1681454)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 01:55:36,349 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:55:36,349 | fed_df.py:547 | Average fusion training loss : 0.010206130835460498, val accuracy : 0.5483399999999999, best val accuracy : 0.563
INFO flwr 2023-08-21 01:55:36,350 | common.py:35 | Avg. local train loss : 4.829035207256675, train acc : 0.79025
INFO flwr 2023-08-21 01:55:38,904 | server.py:116 | fit progress: (4, 1.3069245727539063, {'server_test_acc': 0.5509}, 566.6347398809157)
INFO flwr 2023-08-21 01:55:38,904 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-21 01:55:44,784 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1825942)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:56:32,097 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-21 01:56:32,205 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-21 01:56:32,293 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1825946)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1825942)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1825945)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1825950)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1825948)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1825947)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1825943)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1825946)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1825949)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1825947)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1825943)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1825950)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1825948)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1825945)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1825949)[0m malloc_consolidate(): invalid chunk size
E0821 01:56:35.999020124 1874476 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-21 01:57:58,580 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:57:58,581 | fed_df.py:547 | Average fusion training loss : 0.008404838318238034, val accuracy : 0.5226599999999999, best val accuracy : 0.5392
INFO flwr 2023-08-21 01:57:58,582 | common.py:35 | Avg. local train loss : 4.75945058055222, train acc : 0.8003055555555555
INFO flwr 2023-08-21 01:58:01,110 | server.py:116 | fit progress: (5, 1.377033251953125, {'server_test_acc': 0.5354}, 708.8405930921435)
INFO flwr 2023-08-21 01:58:01,110 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-21 01:58:07,051 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1952241)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:58:53,762 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-21 01:58:53,870 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-21 01:58:53,959 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1952241)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1952242)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1952240)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1952238)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1952239)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1952243)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1952237)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1952244)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1952244)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1952242)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1952239)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1952237)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1952240)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1952238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1952243)[0m malloc_consolidate(): invalid chunk size
E0821 01:58:56.326761326 2000983 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-21 02:00:19,725 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:00:19,725 | fed_df.py:547 | Average fusion training loss : 0.0069498510013800115, val accuracy : 0.6348199999999998, best val accuracy : 0.652
INFO flwr 2023-08-21 02:00:19,726 | common.py:35 | Avg. local train loss : 4.782777654379606, train acc : 0.7986833333333334
INFO flwr 2023-08-21 02:00:22,284 | server.py:116 | fit progress: (6, 1.1799580780029297, {'server_test_acc': 0.6419}, 850.0145645947196)
INFO flwr 2023-08-21 02:00:22,284 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-21 02:00:28,193 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2078854)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:01:15,081 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2078857)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:01:15,189 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-21 02:01:15,277 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2078858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2078859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078854)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2078855)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2078857)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2078858)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2078856)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2078861)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2078860)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2078859)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2078856)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2078855)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2078861)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:02:46,115 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:02:46,116 | fed_df.py:547 | Average fusion training loss : 0.005947261015884578, val accuracy : 0.57088, best val accuracy : 0.584
INFO flwr 2023-08-21 02:02:46,117 | common.py:35 | Avg. local train loss : 4.68888774625957, train acc : 0.8129166666666667
INFO flwr 2023-08-21 02:02:48,679 | server.py:116 | fit progress: (7, 1.3834883178710937, {'server_test_acc': 0.572}, 996.4097125227563)
INFO flwr 2023-08-21 02:02:48,679 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-21 02:02:54,602 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2205109)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:03:41,966 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-21 02:03:42,075 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-21 02:03:42,165 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2205109)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2205111)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2205113)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2205114)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2205112)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2205116)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2205117)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2205115)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2205111)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2205116)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2205113)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2205114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2205115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2205112)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2205117)[0m malloc_consolidate(): invalid chunk size
E0821 02:03:46.855157237 2253292 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
E0821 02:03:52.519105894 2260588 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
E0821 02:04:12.785358502 2278959 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
E0821 02:05:03.229586753 2279430 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-21 02:05:08,307 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:05:08,307 | fed_df.py:547 | Average fusion training loss : 0.005837120383395814, val accuracy : 0.6419599999999999, best val accuracy : 0.6496
INFO flwr 2023-08-21 02:05:08,308 | common.py:35 | Avg. local train loss : 4.651702754199505, train acc : 0.8166527777777778
INFO flwr 2023-08-21 02:05:10,876 | server.py:116 | fit progress: (8, 1.3186351837158203, {'server_test_acc': 0.6422}, 1138.6069356747903)
INFO flwr 2023-08-21 02:05:10,876 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-21 02:05:16,720 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2331439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2331436)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:06:04,126 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-21 02:06:04,234 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-21 02:06:04,322 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2331439)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2331436)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2331440)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2331437)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2331434)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2331441)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2331442)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2331438)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2331441)[0m malloc_consolidate(): invalid chunk size
E0821 02:06:04.921913443 2378257 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=2331437)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2331440)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2331442)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2331438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2331434)[0m double free or corruption (fasttop)
E0821 02:06:06.352294077 2379671 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-21 02:07:30,742 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:07:30,742 | fed_df.py:547 | Average fusion training loss : 0.00474427019234281, val accuracy : 0.5934200000000001, best val accuracy : 0.6214
INFO flwr 2023-08-21 02:07:30,744 | common.py:35 | Avg. local train loss : 4.440156627073884, train acc : 0.8428361111111111
INFO flwr 2023-08-21 02:07:33,305 | server.py:116 | fit progress: (9, 1.4483761779785156, {'server_test_acc': 0.6106}, 1281.0355058247223)
INFO flwr 2023-08-21 02:07:33,305 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-21 02:07:39,200 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2457901)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:08:26,224 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-21 02:08:26,333 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-21 02:08:26,423 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2457901)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2457902)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2457903)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2457905)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2457907)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2457909)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2457908)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2457906)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2457902)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2457907)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2457908)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2457903)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2457909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2457905)[0m double free or corruption (fasttop)
E0821 02:08:28.444793917 2380008 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=2457906)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:09:53,292 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:09:53,293 | fed_df.py:547 | Average fusion training loss : 0.0045748997166519985, val accuracy : 0.62984, best val accuracy : 0.6624
INFO flwr 2023-08-21 02:09:53,294 | common.py:35 | Avg. local train loss : 4.605951349064707, train acc : 0.8258972222222222
INFO flwr 2023-08-21 02:09:55,870 | server.py:116 | fit progress: (10, 1.509673126220703, {'server_test_acc': 0.6584}, 1423.6003707731143)
INFO flwr 2023-08-21 02:09:55,870 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-21 02:10:01,812 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:10:48,773 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-21 02:10:48,883 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-21 02:10:48,971 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2603203)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2603202)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2603200)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2603201)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2603206)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2603205)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2603204)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2603207)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2603201)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2603202)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2603205)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2603200)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2603204)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2603203)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2603207)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2603206)[0m malloc_consolidate(): invalid chunk size
E0821 02:10:52.956488412 2506321 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-21 02:12:15,535 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:12:15,535 | fed_df.py:547 | Average fusion training loss : 0.0047137107476592065, val accuracy : 0.6468, best val accuracy : 0.688
INFO flwr 2023-08-21 02:12:15,536 | common.py:35 | Avg. local train loss : 4.716375298798084, train acc : 0.8207111111111111
INFO flwr 2023-08-21 02:12:18,096 | server.py:116 | fit progress: (11, 1.5768891296386718, {'server_test_acc': 0.6909}, 1565.8265930661)
INFO flwr 2023-08-21 02:12:18,096 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-21 02:12:24,067 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:13:11,029 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2735365)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:13:11,138 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-21 02:13:11,229 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2735362)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2735365)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2735364)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2735374)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2735373)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2735370)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2735372)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2735371)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2735362)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2735372)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2735364)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2735374)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2735373)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2735371)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2735370)[0m malloc_consolidate(): invalid chunk size
E0821 02:13:13.390249123 2659225 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-21 02:14:37,864 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:14:37,865 | fed_df.py:547 | Average fusion training loss : 0.0038583892628084866, val accuracy : 0.65962, best val accuracy : 0.6848
INFO flwr 2023-08-21 02:14:37,866 | common.py:35 | Avg. local train loss : 4.381165956705809, train acc : 0.8520472222222222
INFO flwr 2023-08-21 02:14:40,421 | server.py:116 | fit progress: (12, 1.5772842193603516, {'server_test_acc': 0.6783}, 1708.1515005240217)
INFO flwr 2023-08-21 02:14:40,421 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-21 02:14:46,310 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2861568)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:15:34,004 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-21 02:15:34,114 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-21 02:15:34,202 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2861567)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2861568)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2861564)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2861565)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2861563)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2861569)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2861566)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2861562)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2861564)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861566)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2861563)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861569)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2861562)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2861565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2861567)[0m double free or corruption (fasttop)
E0821 02:15:36.624247091 2909889 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-21 02:17:01,135 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:17:01,135 | fed_df.py:547 | Average fusion training loss : 0.0030918970935745163, val accuracy : 0.6422399999999999, best val accuracy : 0.6948
INFO flwr 2023-08-21 02:17:01,136 | common.py:35 | Avg. local train loss : 4.200674769282341, train acc : 0.8707388888888888
INFO flwr 2023-08-21 02:17:03,705 | server.py:116 | fit progress: (13, 1.654343246459961, {'server_test_acc': 0.6921}, 1851.4353750990704)
INFO flwr 2023-08-21 02:17:03,705 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-21 02:17:09,663 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2987906)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2987910)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:17:56,844 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-21 02:17:56,953 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-21 02:17:57,058 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2987906)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2987914)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2987912)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2987911)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2987908)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2987910)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2987913)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2987909)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2987908)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2987909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2987914)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2987912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2987911)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2987913)[0m malloc_consolidate(): invalid chunk size
E0821 02:17:58.869584289 3035856 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-21 02:19:23,529 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:19:23,530 | fed_df.py:547 | Average fusion training loss : 0.0026765042040497065, val accuracy : 0.6447400000000001, best val accuracy : 0.7038
INFO flwr 2023-08-21 02:19:23,531 | common.py:35 | Avg. local train loss : 4.300425741448998, train acc : 0.8651638888888888
INFO flwr 2023-08-21 02:19:26,083 | server.py:116 | fit progress: (14, 1.635238165283203, {'server_test_acc': 0.7034}, 1993.813342280686)
INFO flwr 2023-08-21 02:19:26,083 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-21 02:19:32,038 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3114304)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3114302)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:20:19,356 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3114303)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:20:19,466 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-21 02:20:19,556 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3114304)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3114302)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3114300)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3114303)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3114301)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3114305)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3114306)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3114307)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3114300)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3114307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3114301)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3114306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3114305)[0m malloc_consolidate(): invalid chunk size
E0821 02:20:23.166110825 3162588 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:21:46,184 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:21:46,185 | fed_df.py:547 | Average fusion training loss : 0.0025200983609538524, val accuracy : 0.6563599999999999, best val accuracy : 0.7124
INFO flwr 2023-08-21 02:21:46,186 | common.py:35 | Avg. local train loss : 4.244096375256777, train acc : 0.8701472222222224
INFO flwr 2023-08-21 02:21:48,761 | server.py:116 | fit progress: (15, 1.7183223724365235, {'server_test_acc': 0.7048}, 2136.49147678772)
INFO flwr 2023-08-21 02:21:48,761 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-21 02:21:54,656 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3240546)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3240548)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:22:41,609 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-21 02:22:41,719 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-21 02:22:41,807 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3240546)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3240548)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3240549)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3240550)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3240552)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3240554)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3240551)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3240553)[0m Fitting Client 7
E0821 02:22:42.173700112 3164416 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3240550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3240549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3240551)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3240553)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3240552)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:24:08,649 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:24:08,649 | fed_df.py:547 | Average fusion training loss : 0.0023596205804497002, val accuracy : 0.64192, best val accuracy : 0.7016
INFO flwr 2023-08-21 02:24:08,650 | common.py:35 | Avg. local train loss : 4.227765457704663, train acc : 0.8725749999999999
INFO flwr 2023-08-21 02:24:11,215 | server.py:116 | fit progress: (16, 1.707230645751953, {'server_test_acc': 0.6965}, 2278.9452739167027)
INFO flwr 2023-08-21 02:24:11,215 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-21 02:24:17,177 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3367125)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:25:04,687 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-21 02:25:04,798 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-21 02:25:04,888 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3367125)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3367126)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3367132)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3367130)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3367129)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3367128)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3367127)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3367131)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3367128)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3367130)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3367129)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3367127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3367131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3367132)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3367126)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:26:37,075 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:26:37,075 | fed_df.py:547 | Average fusion training loss : 0.0021243694184231573, val accuracy : 0.65894, best val accuracy : 0.7246
INFO flwr 2023-08-21 02:26:37,076 | common.py:35 | Avg. local train loss : 4.276765884459018, train acc : 0.872375
INFO flwr 2023-08-21 02:26:39,643 | server.py:116 | fit progress: (17, 1.6986098693847655, {'server_test_acc': 0.7188}, 2427.3737612110563)
INFO flwr 2023-08-21 02:26:39,643 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-21 02:26:45,555 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:27:32,878 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-21 02:27:32,987 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-21 02:27:33,076 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3518378)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3518377)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3518376)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3518375)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3518381)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3518380)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3518374)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3518379)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3518378)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3518380)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3518381)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3518375)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3518379)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3518377)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3518376)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3518374)[0m malloc_consolidate(): invalid chunk size
E0821 02:27:45.609532935 3287894 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 02:28:16.168246678 3602886 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:28:59,792 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:28:59,793 | fed_df.py:547 | Average fusion training loss : 0.0014228562838979996, val accuracy : 0.67418, best val accuracy : 0.728
INFO flwr 2023-08-21 02:28:59,794 | common.py:35 | Avg. local train loss : 4.153490522131324, train acc : 0.8829777777777778
INFO flwr 2023-08-21 02:29:02,387 | server.py:116 | fit progress: (18, 1.7030062316894532, {'server_test_acc': 0.7248}, 2570.11794489203)
INFO flwr 2023-08-21 02:29:02,387 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-21 02:29:08,325 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3644675)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:29:55,490 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-21 02:29:55,600 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-21 02:29:55,704 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3644675)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3644676)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3644677)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3644674)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3644678)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3644681)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3644680)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3644679)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3644680)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3644676)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3644678)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3644677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3644674)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3644679)[0m double free or corruption (fasttop)
E0821 02:29:57.612257369 3603384 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3644681)[0m double free or corruption (fasttop)
E0821 02:30:01.104005205 3693004 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:31:22,754 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:31:22,754 | fed_df.py:547 | Average fusion training loss : 0.001663930891198106, val accuracy : 0.6840800000000001, best val accuracy : 0.7334
INFO flwr 2023-08-21 02:31:22,755 | common.py:35 | Avg. local train loss : 4.153614727780224, train acc : 0.8841527777777779
INFO flwr 2023-08-21 02:31:25,335 | server.py:116 | fit progress: (19, 1.7194141326904298, {'server_test_acc': 0.7314}, 2713.0655763461255)
INFO flwr 2023-08-21 02:31:25,335 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-21 02:31:31,319 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:32:18,139 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-21 02:32:18,249 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-21 02:32:18,338 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3771102)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3771103)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3771104)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3771105)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3771108)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3771109)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3771107)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3771106)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3771104)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3771103)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3771109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3771108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3771105)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3771106)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3771102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3771107)[0m malloc_consolidate(): invalid chunk size
E0821 02:32:20.982990776 3696172 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:33:45,452 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:33:45,452 | fed_df.py:547 | Average fusion training loss : 0.001359649481426459, val accuracy : 0.71436, best val accuracy : 0.7558
INFO flwr 2023-08-21 02:33:45,453 | common.py:35 | Avg. local train loss : 4.307539226487278, train acc : 0.8727972222222222
INFO flwr 2023-08-21 02:33:48,023 | server.py:116 | fit progress: (20, 1.7212160583496094, {'server_test_acc': 0.7446}, 2855.7539839558303)
INFO flwr 2023-08-21 02:33:48,024 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-21 02:33:53,970 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3897249)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3897247)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:34:40,683 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-21 02:34:40,790 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-21 02:34:40,892 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3897251)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3897249)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3897248)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3897250)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3897247)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3897254)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3897253)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3897252)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3897251)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3897252)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3897248)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3897253)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3897250)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3897254)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:36:13,242 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:36:13,242 | fed_df.py:547 | Average fusion training loss : 0.0012377126952633263, val accuracy : 0.73762, best val accuracy : 0.767
INFO flwr 2023-08-21 02:36:13,244 | common.py:35 | Avg. local train loss : 4.254726721346379, train acc : 0.8798055555555556
E0821 02:36:15.670859358 4019851 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:36:15,814 | server.py:116 | fit progress: (21, 1.6538311096191407, {'server_test_acc': 0.758}, 3003.544779686723)
INFO flwr 2023-08-21 02:36:15,814 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-21 02:36:21,791 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4023954)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:37:08,965 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4023956)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:37:09,074 | fed_df.py:365 | Warm start at round 22
[2m[36m(launch_and_fit pid=4023962)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:37:09,164 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4023954)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4023958)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4023956)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4023961)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4023960)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4023957)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4023959)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4023962)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4023960)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4023961)[0m malloc_consolidate(): invalid chunk size
E0821 02:37:10.295947759 4022490 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4023959)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4023957)[0m double free or corruption (fasttop)
E0821 02:38:02.693579744 4071747 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:38:35,939 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:38:35,939 | fed_df.py:547 | Average fusion training loss : 0.0013117411835119129, val accuracy : 0.68594, best val accuracy : 0.7426
INFO flwr 2023-08-21 02:38:35,940 | common.py:35 | Avg. local train loss : 4.072992124408484, train acc : 0.8931944444444444
INFO flwr 2023-08-21 02:38:38,494 | server.py:116 | fit progress: (22, 1.754510888671875, {'server_test_acc': 0.7346}, 3146.2245453568175)
INFO flwr 2023-08-21 02:38:38,494 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-21 02:38:44,528 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4150170)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4150166)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:39:31,499 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-21 02:39:31,608 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-21 02:39:31,713 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4150167)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4150166)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4150169)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4150170)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4150171)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4150172)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4150174)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4150173)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4150167)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4150171)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4150172)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4150169)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4150173)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4150174)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:40:59,137 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:40:59,138 | fed_df.py:547 | Average fusion training loss : 0.0009188932945544366, val accuracy : 0.7243999999999999, best val accuracy : 0.7558
INFO flwr 2023-08-21 02:40:59,139 | common.py:35 | Avg. local train loss : 4.017661476135253, train acc : 0.8996694444444444
INFO flwr 2023-08-21 02:41:01,714 | server.py:116 | fit progress: (23, 1.674042318725586, {'server_test_acc': 0.7449}, 3289.444272483699)
INFO flwr 2023-08-21 02:41:01,714 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-21 02:41:07,692 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=99032)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:41:54,895 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-21 02:41:55,005 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-21 02:41:55,095 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=99032)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=99041)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=99042)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=99043)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=99045)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=99044)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=99046)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=99048)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=99046)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=99041)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=99044)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=99048)[0m malloc_consolidate(): invalid chunk size
E0821 02:41:56.325243184 4117900 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=99045)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=99042)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=99043)[0m double free or corruption (fasttop)
E0821 02:42:02.648301977  161392 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:43:22,399 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:43:22,399 | fed_df.py:547 | Average fusion training loss : 0.0010303213451988995, val accuracy : 0.73284, best val accuracy : 0.7718
INFO flwr 2023-08-21 02:43:22,401 | common.py:35 | Avg. local train loss : 4.254183687269688, train acc : 0.8793388888888889
INFO flwr 2023-08-21 02:43:24,980 | server.py:116 | fit progress: (24, 1.711112631225586, {'server_test_acc': 0.7607}, 3432.7107838229276)
INFO flwr 2023-08-21 02:43:24,980 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-21 02:43:30,914 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=234934)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:44:17,760 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-21 02:44:17,869 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-21 02:44:17,959 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=234932)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=234934)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=234936)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=234939)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=234938)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=234937)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=234929)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=234935)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=234932)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=234938)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=234929)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234939)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234935)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234937)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=234936)[0m malloc_consolidate(): invalid chunk size
E0821 02:44:21.777681687  161813 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:45:45,186 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:45:45,187 | fed_df.py:547 | Average fusion training loss : 0.0008766228108434006, val accuracy : 0.72304, best val accuracy : 0.7526
INFO flwr 2023-08-21 02:45:45,188 | common.py:35 | Avg. local train loss : 4.08437765724957, train acc : 0.8938916666666666
INFO flwr 2023-08-21 02:45:47,758 | server.py:116 | fit progress: (25, 1.7379169311523437, {'server_test_acc': 0.7447}, 3575.48919723602)
INFO flwr 2023-08-21 02:45:47,759 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-21 02:45:53,659 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:46:40,465 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-21 02:46:40,574 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-21 02:46:40,662 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=361033)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=361035)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=361038)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=361036)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=361042)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=361039)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=361040)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=361041)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=361036)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=361033)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=361038)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=361041)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=361039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=361040)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=361042)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=361035)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:48:07,877 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:48:07,877 | fed_df.py:547 | Average fusion training loss : 0.0010242740149842575, val accuracy : 0.74798, best val accuracy : 0.7776
INFO flwr 2023-08-21 02:48:07,878 | common.py:35 | Avg. local train loss : 4.231357470154762, train acc : 0.8829833333333332
INFO flwr 2023-08-21 02:48:10,450 | server.py:116 | fit progress: (26, 1.7309293701171875, {'server_test_acc': 0.769}, 3718.180703117978)
INFO flwr 2023-08-21 02:48:10,450 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-21 02:48:16,410 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=487484)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:49:03,470 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-21 02:49:03,579 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-21 02:49:03,669 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=487483)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=487484)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=487482)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=487489)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=487488)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=487485)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=487486)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=487487)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=487483)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=487487)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=487485)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=487488)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=487482)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=487486)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=487489)[0m malloc_consolidate(): invalid chunk size
E0821 02:49:07.519705712  535726 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:50:30,756 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:50:30,756 | fed_df.py:547 | Average fusion training loss : 0.0008331798495491967, val accuracy : 0.74322, best val accuracy : 0.7686
INFO flwr 2023-08-21 02:50:30,757 | common.py:35 | Avg. local train loss : 4.067156274244189, train acc : 0.8970916666666666
INFO flwr 2023-08-21 02:50:33,336 | server.py:116 | fit progress: (27, 1.7283454132080078, {'server_test_acc': 0.7625}, 3861.067033007741)
INFO flwr 2023-08-21 02:50:33,337 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-21 02:50:39,282 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:51:26,216 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=614009)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:51:26,327 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-21 02:51:26,415 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=614009)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=614010)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=614008)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=614012)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=614011)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=614014)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=614013)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=614015)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=614014)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=614010)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=614008)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=614011)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=614013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=614015)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=614012)[0m malloc_consolidate(): invalid chunk size
E0821 02:51:28.509006370  537676 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 02:51:38.863837795  662604 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:52:54,118 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:52:54,119 | fed_df.py:547 | Average fusion training loss : 0.0006981332013965585, val accuracy : 0.7590600000000001, best val accuracy : 0.7766
INFO flwr 2023-08-21 02:52:54,120 | common.py:35 | Avg. local train loss : 4.131209024786949, train acc : 0.8937722222222223
INFO flwr 2023-08-21 02:52:56,724 | server.py:116 | fit progress: (28, 1.7126121490478516, {'server_test_acc': 0.7751}, 4004.4542950959876)
INFO flwr 2023-08-21 02:52:56,724 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-21 02:53:02,701 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:53:49,530 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-21 02:53:49,639 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-21 02:53:49,728 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=740172)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=740177)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=740178)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=740179)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=740174)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=740173)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=740175)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=740176)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=740177)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=740172)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=740174)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=740175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=740179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=740178)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=740173)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=740176)[0m malloc_consolidate(): invalid chunk size
E0821 02:54:44.890017812  834890 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:55:17,090 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:55:17,091 | fed_df.py:547 | Average fusion training loss : 0.000683306973631261, val accuracy : 0.7354, best val accuracy : 0.7634
INFO flwr 2023-08-21 02:55:17,092 | common.py:35 | Avg. local train loss : 4.0696868937462565, train acc : 0.8986916666666666
INFO flwr 2023-08-21 02:55:19,700 | server.py:116 | fit progress: (29, 1.7532943908691405, {'server_test_acc': 0.7522}, 4147.431046125945)
INFO flwr 2023-08-21 02:55:19,701 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-21 02:55:25,946 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=866886)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:56:12,961 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=866887)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:56:13,070 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-21 02:56:13,157 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=866887)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=866889)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=866886)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=866884)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=866883)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=866885)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=866888)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=866882)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=866884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=866889)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866883)[0m double free or corruption (fasttop)
E0821 02:56:13.730084583  915599 chttp2_transport.cc:1079]             ipv4:145.136.62.26:62500: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=866882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=866885)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:57:40,594 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:57:40,594 | fed_df.py:547 | Average fusion training loss : 0.0006387872646155302, val accuracy : 0.7495999999999999, best val accuracy : 0.7696
INFO flwr 2023-08-21 02:57:40,595 | common.py:35 | Avg. local train loss : 3.81556259803474, train acc : 0.9163222222222223
INFO flwr 2023-08-21 02:57:43,181 | server.py:116 | fit progress: (30, 1.7719634765625, {'server_test_acc': 0.7595}, 4290.911954890005)
INFO flwr 2023-08-21 02:57:43,181 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-21 02:57:43,182 | server.py:144 | FL finished in 4290.912321320735
INFO flwr 2023-08-21 02:57:43,182 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-21 02:57:43,183 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-21 02:57:43,183 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.7254804138183595), (2, 1.4514095825195312), (3, 1.2924409271240234), (4, 1.3069245727539063), (5, 1.377033251953125), (6, 1.1799580780029297), (7, 1.3834883178710937), (8, 1.3186351837158203), (9, 1.4483761779785156), (10, 1.509673126220703), (11, 1.5768891296386718), (12, 1.5772842193603516), (13, 1.654343246459961), (14, 1.635238165283203), (15, 1.7183223724365235), (16, 1.707230645751953), (17, 1.6986098693847655), (18, 1.7030062316894532), (19, 1.7194141326904298), (20, 1.7212160583496094), (21, 1.6538311096191407), (22, 1.754510888671875), (23, 1.674042318725586), (24, 1.711112631225586), (25, 1.7379169311523437), (26, 1.7309293701171875), (27, 1.7283454132080078), (28, 1.7126121490478516), (29, 1.7532943908691405), (30, 1.7719634765625)]
INFO flwr 2023-08-21 02:57:43,183 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.396), (2, 0.4823), (3, 0.5581), (4, 0.5509), (5, 0.5354), (6, 0.6419), (7, 0.572), (8, 0.6422), (9, 0.6106), (10, 0.6584), (11, 0.6909), (12, 0.6783), (13, 0.6921), (14, 0.7034), (15, 0.7048), (16, 0.6965), (17, 0.7188), (18, 0.7248), (19, 0.7314), (20, 0.7446), (21, 0.758), (22, 0.7346), (23, 0.7449), (24, 0.7607), (25, 0.7447), (26, 0.769), (27, 0.7625), (28, 0.7751), (29, 0.7522), (30, 0.7595)]}
corrupted size vs. prev_size in fastbins
srun: error: gcn26: task 0: Aborted
srun: Terminating StepId=3430911.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3430911
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:51:10
CPU Efficiency: 12.43% of 22:57:00 core-walltime
Job Wall-clock time: 01:16:30
Memory Utilized: 51.90 GB
Memory Efficiency: 43.25% of 120.00 GB
