-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:2
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3430914/1692575052_106256072', seed=42, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3430914/1692575052_106256072/single_img_crops/crops
50000 took 0.73min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-21 01:45:12,769 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-21 01:45:12,769 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3430914/1692575052_106256072/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3430914/1692575052_106256072/cifar-10-python.tar.gz to /scratch-local/sunnys.3430914/1692575052_106256072
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
INFO flwr 2023-08-21 01:52:19,659 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-21 01:52:22,864	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-21 01:52:23,980 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'GPU': 1.0, 'node:145.136.62.34': 1.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-21 01:52:23,980 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-21 01:52:23,980 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-21 01:52:23,980 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-21 01:52:34,101 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-21 01:52:34,101 | server.py:101 | FL starting
DEBUG flwr 2023-08-21 01:52:40,256 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 01:53:34,700 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-21 01:53:34,808 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-21 01:53:34,900 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2363619)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2363620)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2363623)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2363616)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2363622)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2363621)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2363618)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2363617)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2363616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2363623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2363621)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2363619)[0m double free or corruption (fasttop)
E0821 01:53:36.726601039 2459222 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=2363620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2363617)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2363622)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 01:55:06,888 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:55:06,888 | fed_df.py:547 | Average fusion training loss : 0.014386994479224086, val accuracy : 0.39537999999999995, best val accuracy : 0.4246
INFO flwr 2023-08-21 01:55:06,889 | common.py:35 | Avg. local train loss : 7.529612254351378, train acc : 0.5214444444444444
INFO flwr 2023-08-21 01:55:09,470 | server.py:116 | fit progress: (1, 1.6290419555664062, {'server_test_acc': 0.4266}, 155.3685092399828)
INFO flwr 2023-08-21 01:55:09,470 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-21 01:55:15,451 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2615741)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 01:56:05,775 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-21 01:56:05,883 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-21 01:56:05,972 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2615742)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2615741)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2615747)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2615743)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2615748)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2615745)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2615746)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2615744)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2615745)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2615742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2615746)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2615748)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2615744)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2615747)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2615743)[0m double free or corruption (fasttop)
E0821 01:56:08.310073980 2460155 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-21 01:57:43,571 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 01:57:43,572 | fed_df.py:547 | Average fusion training loss : 0.009592748169787228, val accuracy : 0.42225999999999997, best val accuracy : 0.4384
INFO flwr 2023-08-21 01:57:43,573 | common.py:35 | Avg. local train loss : 6.237378590553999, train acc : 0.6474833333333333
INFO flwr 2023-08-21 01:57:46,297 | server.py:116 | fit progress: (2, 1.6871790435791016, {'server_test_acc': 0.4377}, 312.1953866109252)
INFO flwr 2023-08-21 01:57:46,297 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-21 01:57:52,691 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2895587)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 01:58:41,612 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-21 01:58:41,753 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2895587)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2895555)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2895557)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2895627)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2895591)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2895628)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2895638)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2895635)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2895591)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2895557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2895635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2895555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2895638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2895627)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2895628)[0m double free or corruption (fasttop)
E0821 01:58:45.982233958 2995609 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-21 02:00:18,238 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:00:18,239 | fed_df.py:547 | Average fusion training loss : 0.006436820020433515, val accuracy : 0.49291999999999997, best val accuracy : 0.5212
INFO flwr 2023-08-21 02:00:18,240 | common.py:35 | Avg. local train loss : 5.898888340592384, train acc : 0.6826833333333333
INFO flwr 2023-08-21 02:00:20,965 | server.py:116 | fit progress: (3, 1.361027508544922, {'server_test_acc': 0.5236}, 466.8634051447734)
INFO flwr 2023-08-21 02:00:20,965 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-21 02:00:27,204 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:01:16,553 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3146843)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:01:16,664 | fed_df.py:365 | Warm start at round 4
[2m[36m(launch_and_fit pid=3146850)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:01:16,754 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3146843)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3146850)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3146847)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3146846)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3146848)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3146849)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3146851)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3146852)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3146848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3146851)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3146847)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3146852)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3146846)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3146849)[0m malloc_consolidate(): invalid chunk size
E0821 02:01:19.027536499 3248291 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-21 02:02:54,025 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:02:54,026 | fed_df.py:547 | Average fusion training loss : 0.008312763197347521, val accuracy : 0.58324, best val accuracy : 0.5976
INFO flwr 2023-08-21 02:02:54,027 | common.py:35 | Avg. local train loss : 5.313101337477565, train acc : 0.7455916666666665
INFO flwr 2023-08-21 02:02:56,769 | server.py:116 | fit progress: (4, 1.206486441040039, {'server_test_acc': 0.593}, 622.667186117731)
INFO flwr 2023-08-21 02:02:56,769 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-21 02:03:02,988 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3397410)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:03:52,291 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-21 02:03:52,434 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3397410)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3397465)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3397458)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3397452)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3397457)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3397549)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3397548)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3397547)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3397549)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=3397547)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3397465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3397457)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3397452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3397458)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3397548)[0m malloc_consolidate(): invalid chunk size
E0821 02:03:55.442133127 3501056 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-21 02:05:28,965 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:05:28,965 | fed_df.py:547 | Average fusion training loss : 0.0033645020970143377, val accuracy : 0.61358, best val accuracy : 0.6258
INFO flwr 2023-08-21 02:05:28,966 | common.py:35 | Avg. local train loss : 5.297122674435378, train acc : 0.7457916666666667
INFO flwr 2023-08-21 02:05:31,656 | server.py:116 | fit progress: (5, 1.1974858215332032, {'server_test_acc': 0.6145}, 777.5547385746613)
INFO flwr 2023-08-21 02:05:31,656 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-21 02:05:37,903 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3650640)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:06:26,473 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-21 02:06:26,584 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-21 02:06:26,673 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3650637)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3650631)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3650636)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3650635)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3650640)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3650639)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3650638)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3650634)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3650635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650639)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650637)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650631)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3650634)[0m malloc_consolidate(): invalid chunk size
E0821 02:06:29.174832447 3502804 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
E0821 02:07:20.055002509 3755318 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
E0821 02:07:44.662777119 3875162 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-21 02:08:02,755 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:08:02,755 | fed_df.py:547 | Average fusion training loss : 0.007500644823070616, val accuracy : 0.6206799999999999, best val accuracy : 0.6426
INFO flwr 2023-08-21 02:08:02,756 | common.py:35 | Avg. local train loss : 5.21619522124529, train acc : 0.7559250000000001
INFO flwr 2023-08-21 02:08:05,539 | server.py:116 | fit progress: (6, 1.120199313354492, {'server_test_acc': 0.6347}, 931.4377473308705)
INFO flwr 2023-08-21 02:08:05,539 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-21 02:08:12,085 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3901663)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3901667)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:09:00,618 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-21 02:09:00,760 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3901667)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3901663)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3901669)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3901802)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3901804)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3901801)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3901670)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3901803)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3901803)[0m double free or corruption (fasttop)
E0821 02:09:01.334047651 4003196 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3901802)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3901804)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3901669)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3901670)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3901801)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:10:37,196 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:10:37,196 | fed_df.py:547 | Average fusion training loss : 0.002106232356163673, val accuracy : 0.63112, best val accuracy : 0.6424
INFO flwr 2023-08-21 02:10:37,198 | common.py:35 | Avg. local train loss : 4.758134146779775, train acc : 0.8035972222222222
INFO flwr 2023-08-21 02:10:39,961 | server.py:116 | fit progress: (7, 1.1136160552978516, {'server_test_acc': 0.629}, 1085.8600078839809)
INFO flwr 2023-08-21 02:10:39,962 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-21 02:10:46,105 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4154470)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:11:34,374 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4154311)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:11:34,486 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-21 02:11:34,584 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4154470)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4154311)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4154493)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4154622)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4154623)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4154618)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4154472)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4154624)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4154472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4154493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4154623)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4154618)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4154622)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4154624)[0m malloc_consolidate(): invalid chunk size
E0821 02:11:37.239561339   65144 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-21 02:13:11,977 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:13:11,977 | fed_df.py:547 | Average fusion training loss : 0.006284586847759783, val accuracy : 0.6586000000000001, best val accuracy : 0.6684
INFO flwr 2023-08-21 02:13:11,979 | common.py:35 | Avg. local train loss : 4.809332134947181, train acc : 0.8006527777777779
INFO flwr 2023-08-21 02:13:14,780 | server.py:116 | fit progress: (8, 1.1226107330322266, {'server_test_acc': 0.6494}, 1240.6788460537791)
INFO flwr 2023-08-21 02:13:14,781 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-21 02:13:20,971 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:14:09,553 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-21 02:14:09,697 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=234921)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=234958)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=234919)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=234820)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=234960)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=234920)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=234957)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=234959)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=234960)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234957)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234920)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234820)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=234958)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234959)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234919)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=234921)[0m malloc_consolidate(): invalid chunk size
E0821 02:14:12.562130887   67105 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-21 02:15:46,616 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:15:46,616 | fed_df.py:547 | Average fusion training loss : 0.001621568138594739, val accuracy : 0.67864, best val accuracy : 0.6882
INFO flwr 2023-08-21 02:15:46,617 | common.py:35 | Avg. local train loss : 4.892160936817527, train acc : 0.7924777777777778
INFO flwr 2023-08-21 02:15:49,521 | server.py:116 | fit progress: (9, 1.1233374450683593, {'server_test_acc': 0.673}, 1395.419114985969)
INFO flwr 2023-08-21 02:15:49,521 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-21 02:15:55,662 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=497691)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:16:44,246 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-21 02:16:44,357 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-21 02:16:44,445 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=497691)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=497695)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=497700)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=497697)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=497715)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=497718)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=497716)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=497698)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=497697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=497695)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=497698)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=497718)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=497715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=497700)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=497716)[0m malloc_consolidate(): invalid chunk size
E0821 02:16:48.792864819  348124 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-21 02:18:21,074 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:18:21,074 | fed_df.py:547 | Average fusion training loss : 0.006134326367406175, val accuracy : 0.64806, best val accuracy : 0.6726
INFO flwr 2023-08-21 02:18:21,075 | common.py:35 | Avg. local train loss : 4.705106782913208, train acc : 0.8157027777777777
INFO flwr 2023-08-21 02:18:23,812 | server.py:116 | fit progress: (10, 1.1922422119140625, {'server_test_acc': 0.6654}, 1549.710433386732)
INFO flwr 2023-08-21 02:18:23,812 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-21 02:18:29,988 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:19:18,097 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=750170)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:19:18,240 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=750170)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=750172)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=750179)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=750181)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=750167)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=750175)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=750173)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=750180)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=750179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=750173)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750180)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750181)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750167)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=750172)[0m double free or corruption (fasttop)
E0821 02:19:20.878014544  602863 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
E0821 02:19:20.878515112  602863 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
E0821 02:19:20.878534783  602863 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-21 02:20:55,276 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:20:55,277 | fed_df.py:547 | Average fusion training loss : 0.0010174763922696003, val accuracy : 0.68674, best val accuracy : 0.6964
INFO flwr 2023-08-21 02:20:55,278 | common.py:35 | Avg. local train loss : 4.544866025447845, train acc : 0.8306861111111111
INFO flwr 2023-08-21 02:20:58,295 | server.py:116 | fit progress: (11, 1.1849612213134766, {'server_test_acc': 0.6838}, 1704.193579575047)
INFO flwr 2023-08-21 02:20:58,295 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-21 02:21:04,581 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=997369)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:21:52,634 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-21 02:21:52,745 | fed_df.py:365 | Warm start at round 12
[2m[36m(launch_and_fit pid=997374)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:21:52,835 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=997369)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=997374)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=997375)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=997378)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=997379)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=997377)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=997380)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=997364)[0m Fitting Client 8
E0821 02:21:53.475314718 1092435 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=997364)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997378)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997380)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997377)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=997379)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:23:29,627 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:23:29,627 | fed_df.py:547 | Average fusion training loss : 0.004829559814883396, val accuracy : 0.699, best val accuracy : 0.718
INFO flwr 2023-08-21 02:23:29,629 | common.py:35 | Avg. local train loss : 4.6349042825400835, train acc : 0.8265583333333333
INFO flwr 2023-08-21 02:23:32,368 | server.py:116 | fit progress: (12, 1.2522410217285156, {'server_test_acc': 0.6997}, 1858.2664578640833)
INFO flwr 2023-08-21 02:23:32,368 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-21 02:23:38,660 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1243594)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:24:26,805 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-21 02:24:26,946 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1243594)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1243733)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1243732)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1243726)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1243730)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1243728)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1243727)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1243725)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1243726)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1243732)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1243728)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1243727)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1243725)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1243730)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1243733)[0m double free or corruption (fasttop)
E0821 02:24:29.946164662 1348786 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-21 02:26:02,826 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:26:02,827 | fed_df.py:547 | Average fusion training loss : 0.0004901837297657039, val accuracy : 0.72154, best val accuracy : 0.7278
INFO flwr 2023-08-21 02:26:02,828 | common.py:35 | Avg. local train loss : 4.585618827491999, train acc : 0.8286666666666667
INFO flwr 2023-08-21 02:26:05,655 | server.py:116 | fit progress: (13, 1.213230340576172, {'server_test_acc': 0.712}, 2011.5538331340067)
INFO flwr 2023-08-21 02:26:05,656 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-21 02:26:12,297 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1497426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1497354)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:27:00,663 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-21 02:27:00,774 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-21 02:27:00,862 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1497354)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1497426)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1497356)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1497492)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1497490)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1497493)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1497491)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1497290)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1497356)[0m malloc_consolidate(): invalid chunk size
E0821 02:27:01.580217363 1350321 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1497491)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1497493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1497490)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1497492)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1497290)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:28:37,536 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:28:37,536 | fed_df.py:547 | Average fusion training loss : 0.00415492975176312, val accuracy : 0.66046, best val accuracy : 0.6908
INFO flwr 2023-08-21 02:28:37,537 | common.py:35 | Avg. local train loss : 4.600526914745569, train acc : 0.8301999999999999
INFO flwr 2023-08-21 02:28:40,293 | server.py:116 | fit progress: (14, 1.4192644775390626, {'server_test_acc': 0.6863}, 2166.1918663089164)
INFO flwr 2023-08-21 02:28:40,294 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-21 02:28:46,650 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1756938)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:29:34,818 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-21 02:29:34,961 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1756938)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1757068)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1756968)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1757129)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1757069)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1757067)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1757194)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1757191)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1756968)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757067)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757191)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757068)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757069)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1757129)[0m double free or corruption (fasttop)
E0821 02:29:37.893577808 1871967 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:31:12,323 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:31:12,323 | fed_df.py:547 | Average fusion training loss : 0.0005824447984923609, val accuracy : 0.688, best val accuracy : 0.7012
INFO flwr 2023-08-21 02:31:12,324 | common.py:35 | Avg. local train loss : 4.4374895516783, train acc : 0.8435638888888888
INFO flwr 2023-08-21 02:31:15,087 | server.py:116 | fit progress: (15, 1.2837624328613282, {'server_test_acc': 0.6908}, 2320.985680004116)
INFO flwr 2023-08-21 02:31:15,087 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-21 02:31:21,200 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2033597)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2033595)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:32:10,171 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-21 02:32:10,282 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-21 02:32:10,373 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2033576)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2033596)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2033579)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2033599)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2033598)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2033597)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2033595)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2033600)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2033599)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2033600)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2033579)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2033576)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2033598)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2033596)[0m malloc_consolidate(): invalid chunk size
E0821 02:32:14.390180745 1873184 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:33:47,573 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:33:47,574 | fed_df.py:547 | Average fusion training loss : 0.003745532946428284, val accuracy : 0.65138, best val accuracy : 0.6736
INFO flwr 2023-08-21 02:33:47,575 | common.py:35 | Avg. local train loss : 4.35921700000763, train acc : 0.8517944444444445
INFO flwr 2023-08-21 02:33:50,546 | server.py:116 | fit progress: (16, 1.501740072631836, {'server_test_acc': 0.6717}, 2476.4442272437736)
INFO flwr 2023-08-21 02:33:50,546 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-21 02:33:56,725 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2286897)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2287042)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2287127)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:34:44,358 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-21 02:34:44,501 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2286897)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2287127)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2287042)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2287180)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2287043)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2287044)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2287182)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2287181)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2287180)[0m malloc_consolidate(): invalid chunk size
E0821 02:34:45.510421616 2384766 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2287043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2287182)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2287044)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2287181)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-21 02:36:21,342 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:36:21,343 | fed_df.py:547 | Average fusion training loss : 0.000358734210516559, val accuracy : 0.7058199999999999, best val accuracy : 0.716
INFO flwr 2023-08-21 02:36:21,344 | common.py:35 | Avg. local train loss : 4.305066129565239, train acc : 0.8586583333333332
INFO flwr 2023-08-21 02:36:24,223 | server.py:116 | fit progress: (17, 1.3849537902832032, {'server_test_acc': 0.7086}, 2630.1216801730916)
INFO flwr 2023-08-21 02:36:24,223 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-21 02:36:30,370 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2539594)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2539983)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:37:18,288 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-21 02:37:18,400 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-21 02:37:18,488 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2539594)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2539836)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2539983)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2539984)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2539982)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2539971)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2539780)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2539834)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2539971)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539836)[0m malloc_consolidate(): invalid chunk size
E0821 02:37:19.270098150 2385477 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2539982)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539984)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2539834)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2539780)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:38:55,108 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:38:55,108 | fed_df.py:547 | Average fusion training loss : 0.0032413193236570806, val accuracy : 0.64936, best val accuracy : 0.6868
INFO flwr 2023-08-21 02:38:55,109 | common.py:35 | Avg. local train loss : 4.462238350510597, train acc : 0.8459277777777777
INFO flwr 2023-08-21 02:38:57,932 | server.py:116 | fit progress: (18, 1.588652554321289, {'server_test_acc': 0.6773}, 2783.830328454729)
INFO flwr 2023-08-21 02:38:57,932 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-21 02:39:04,122 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2791732)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2791881)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2791879)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:39:52,806 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-21 02:39:52,949 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2791882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2791732)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2791879)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2791877)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2791741)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2791878)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2791882)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2791876)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2791881)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2791741)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2791878)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2791876)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2791877)[0m malloc_consolidate(): invalid chunk size
E0821 02:39:55.056959731 2891212 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:41:29,979 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:41:29,979 | fed_df.py:547 | Average fusion training loss : 0.00032875477857305667, val accuracy : 0.7086000000000001, best val accuracy : 0.721
INFO flwr 2023-08-21 02:41:29,980 | common.py:35 | Avg. local train loss : 4.276134140789509, train acc : 0.8652222222222222
INFO flwr 2023-08-21 02:41:33,000 | server.py:116 | fit progress: (19, 1.3984819427490234, {'server_test_acc': 0.7097}, 2938.8986446759664)
INFO flwr 2023-08-21 02:41:33,000 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-21 02:41:39,256 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3046051)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3046126)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3046131)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:42:27,689 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3046067)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:42:27,801 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-21 02:42:27,890 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3046051)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3046126)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3046192)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3046131)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3046194)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3046067)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3046092)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3046193)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3046092)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3046194)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3046193)[0m malloc_consolidate(): invalid chunk size
E0821 02:42:28.987303011 3142091 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3046192)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:44:05,479 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:44:05,479 | fed_df.py:547 | Average fusion training loss : 0.002572234130639117, val accuracy : 0.69578, best val accuracy : 0.7378
INFO flwr 2023-08-21 02:44:05,480 | common.py:35 | Avg. local train loss : 4.377461234107614, train acc : 0.8567611111111112
INFO flwr 2023-08-21 02:44:08,757 | server.py:116 | fit progress: (20, 1.650650045776367, {'server_test_acc': 0.7292}, 3094.655202930793)
INFO flwr 2023-08-21 02:44:08,757 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-21 02:44:14,896 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3307512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3307522)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3307520)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:45:03,840 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-21 02:45:03,983 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3307512)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3307514)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3307560)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3307532)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3307520)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3307522)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3307521)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3307579)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3307521)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3307514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3307560)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3307532)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3307579)[0m double free or corruption (fasttop)
E0821 02:45:06.619451783 3142463 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:46:41,916 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:46:41,917 | fed_df.py:547 | Average fusion training loss : 0.00033001148130279033, val accuracy : 0.7431, best val accuracy : 0.7518
INFO flwr 2023-08-21 02:46:41,918 | common.py:35 | Avg. local train loss : 4.282116837054492, train acc : 0.8667361111111113
INFO flwr 2023-08-21 02:46:44,738 | server.py:116 | fit progress: (21, 1.4533444213867188, {'server_test_acc': 0.7392}, 3250.6368932719342)
INFO flwr 2023-08-21 02:46:44,739 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-21 02:46:50,958 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3587396)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3587247)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:47:40,285 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-21 02:47:40,396 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-21 02:47:40,485 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3587247)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3587302)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3587396)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3587303)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3587518)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3587517)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3587516)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3587515)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3587302)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3587303)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3587516)[0m malloc_consolidate(): invalid chunk size
E0821 02:47:41.581365541 3679626 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3587518)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3587517)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3587515)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 02:49:18,953 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:49:18,953 | fed_df.py:547 | Average fusion training loss : 0.0023875391834881155, val accuracy : 0.63796, best val accuracy : 0.6914
INFO flwr 2023-08-21 02:49:18,955 | common.py:35 | Avg. local train loss : 4.28349234238267, train acc : 0.8635583333333332
INFO flwr 2023-08-21 02:49:22,104 | server.py:116 | fit progress: (22, 1.7273913604736328, {'server_test_acc': 0.6839}, 3408.0029900898226)
INFO flwr 2023-08-21 02:49:22,105 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-21 02:49:28,670 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3844312)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3844317)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:50:18,783 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-21 02:50:18,926 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3844312)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3844317)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3844309)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3844318)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3844451)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3844319)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3844452)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3844321)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3844451)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3844452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3844309)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3844318)[0m malloc_consolidate(): invalid chunk size
E0821 02:50:20.362120557 3680030 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3844319)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3844321)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:51:57,939 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:51:57,940 | fed_df.py:547 | Average fusion training loss : 0.00034089980681892485, val accuracy : 0.73066, best val accuracy : 0.7356
INFO flwr 2023-08-21 02:51:57,941 | common.py:35 | Avg. local train loss : 4.348156653717161, train acc : 0.8657444444444444
INFO flwr 2023-08-21 02:52:00,813 | server.py:116 | fit progress: (23, 1.4957280731201172, {'server_test_acc': 0.7244}, 3566.711085239891)
INFO flwr 2023-08-21 02:52:00,813 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-21 02:52:07,087 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4102353)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4102623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4102624)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 02:52:55,539 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-21 02:52:55,650 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-21 02:52:55,737 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4102353)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4102491)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4102581)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4102490)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4102623)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4102402)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4102625)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4102624)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4102490)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4102581)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4102625)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4102402)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4102491)[0m malloc_consolidate(): invalid chunk size
E0821 02:53:00.087155468 3936124 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:54:34,725 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:54:34,725 | fed_df.py:547 | Average fusion training loss : 0.0018958225668175145, val accuracy : 0.7000200000000001, best val accuracy : 0.7338
INFO flwr 2023-08-21 02:54:34,726 | common.py:35 | Avg. local train loss : 4.486422745138407, train acc : 0.8506277777777779
INFO flwr 2023-08-21 02:54:37,587 | server.py:116 | fit progress: (24, 1.757539013671875, {'server_test_acc': 0.7237}, 3723.485167190898)
INFO flwr 2023-08-21 02:54:37,587 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-21 02:54:43,835 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 02:55:31,431 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-21 02:55:31,575 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=164112)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=164106)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=164108)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=164113)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=164116)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=164115)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=164110)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=164114)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=164108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=164113)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=164110)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=164112)[0m malloc_consolidate(): invalid chunk size
E0821 02:55:32.798618823 4194090 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=164115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=164114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=164116)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=164106)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:57:10,126 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:57:10,127 | fed_df.py:547 | Average fusion training loss : 0.00027809766825521363, val accuracy : 0.7437, best val accuracy : 0.7484
INFO flwr 2023-08-21 02:57:10,128 | common.py:35 | Avg. local train loss : 4.251860513538122, train acc : 0.8739999999999999
INFO flwr 2023-08-21 02:57:12,936 | server.py:116 | fit progress: (25, 1.5174655639648438, {'server_test_acc': 0.7393}, 3878.8346599279903)
INFO flwr 2023-08-21 02:57:12,936 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-21 02:57:19,318 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=412947)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 02:58:07,679 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-21 02:58:07,791 | fed_df.py:365 | Warm start at round 26
[2m[36m(launch_and_fit pid=413031)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 02:58:07,904 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=413011)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=412947)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=413013)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=413033)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=413025)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=413031)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=413012)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=413032)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=413025)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=413012)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=413013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=413011)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=413033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=413032)[0m malloc_consolidate(): invalid chunk size
E0821 02:58:10.867486662  501519 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 02:59:47,408 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 02:59:47,408 | fed_df.py:547 | Average fusion training loss : 0.0018606286113499663, val accuracy : 0.6853, best val accuracy : 0.7368
INFO flwr 2023-08-21 02:59:47,409 | common.py:35 | Avg. local train loss : 4.300394541025161, train acc : 0.8682583333333335
INFO flwr 2023-08-21 02:59:50,332 | server.py:116 | fit progress: (26, 1.7593667114257812, {'server_test_acc': 0.735}, 4036.230924725067)
INFO flwr 2023-08-21 02:59:50,333 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-21 02:59:56,618 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=685103)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 03:00:44,288 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-21 03:00:44,431 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=685032)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=685102)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=685045)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=685103)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=684963)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=684966)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=685082)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=684961)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=685082)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=685032)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=685102)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=684961)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=684966)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=685045)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=684963)[0m malloc_consolidate(): invalid chunk size
E0821 03:00:46.739447818  781987 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 03:02:23,747 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:02:23,748 | fed_df.py:547 | Average fusion training loss : 0.00029091040269122457, val accuracy : 0.72394, best val accuracy : 0.7328
INFO flwr 2023-08-21 03:02:23,749 | common.py:35 | Avg. local train loss : 4.2597486693412066, train acc : 0.8721999999999999
INFO flwr 2023-08-21 03:02:26,536 | server.py:116 | fit progress: (27, 1.5364720001220704, {'server_test_acc': 0.7254}, 4192.434423082974)
INFO flwr 2023-08-21 03:02:26,536 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-21 03:02:32,869 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 03:03:20,634 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=948267)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948338)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 03:03:20,748 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-21 03:03:20,838 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=948267)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=948337)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=948268)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=948269)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=948341)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=948338)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=948340)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=948339)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=948339)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948337)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948268)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=948340)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=948269)[0m double free or corruption (fasttop)
E0821 03:03:23.154105969 1034477 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 03:04:56,058 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:04:56,058 | fed_df.py:547 | Average fusion training loss : 0.0018758096656529234, val accuracy : 0.72592, best val accuracy : 0.7564
INFO flwr 2023-08-21 03:04:56,059 | common.py:35 | Avg. local train loss : 4.284603983163834, train acc : 0.8709166666666668
INFO flwr 2023-08-21 03:04:59,219 | server.py:116 | fit progress: (28, 1.6661353179931642, {'server_test_acc': 0.746}, 4345.117147704121)
INFO flwr 2023-08-21 03:04:59,219 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-21 03:05:05,567 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1199208)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1199211)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 03:05:53,313 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-21 03:05:53,457 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1199208)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1199211)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1199207)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1199209)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1199210)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1199212)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1199281)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1199280)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1199207)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1199210)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1199280)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1199281)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1199209)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1199212)[0m malloc_consolidate(): invalid chunk size
E0821 03:05:56.052198355 1285510 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 03:07:32,469 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:07:32,469 | fed_df.py:547 | Average fusion training loss : 0.00024114193764398806, val accuracy : 0.75196, best val accuracy : 0.7606
INFO flwr 2023-08-21 03:07:32,470 | common.py:35 | Avg. local train loss : 4.263901955261827, train acc : 0.8760555555555555
INFO flwr 2023-08-21 03:07:35,437 | server.py:116 | fit progress: (29, 1.5261849884033203, {'server_test_acc': 0.7549}, 4501.33544480009)
INFO flwr 2023-08-21 03:07:35,437 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-21 03:07:41,606 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1449357)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 03:08:29,308 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-21 03:08:29,420 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-21 03:08:29,510 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1449352)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1449351)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1449353)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1449356)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1449355)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1449358)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1449354)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1449357)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1449352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1449356)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1449353)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1449354)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1449358)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1449351)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1449355)[0m corrupted size vs. prev_size in fastbins
E0821 03:08:31.997577083 1535194 chttp2_transport.cc:1079]             ipv4:145.136.62.34:54713: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 03:10:05,931 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:10:05,932 | fed_df.py:547 | Average fusion training loss : 0.0015989343032124452, val accuracy : 0.71524, best val accuracy : 0.7398
INFO flwr 2023-08-21 03:10:05,933 | common.py:35 | Avg. local train loss : 4.173003762960434, train acc : 0.8804916666666667
INFO flwr 2023-08-21 03:10:08,695 | server.py:116 | fit progress: (30, 1.7868651794433594, {'server_test_acc': 0.7365}, 4654.593544826843)
INFO flwr 2023-08-21 03:10:08,695 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-21 03:10:08,695 | server.py:144 | FL finished in 4654.593934583943
INFO flwr 2023-08-21 03:10:08,696 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-21 03:10:08,696 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-21 03:10:08,697 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.6290419555664062), (2, 1.6871790435791016), (3, 1.361027508544922), (4, 1.206486441040039), (5, 1.1974858215332032), (6, 1.120199313354492), (7, 1.1136160552978516), (8, 1.1226107330322266), (9, 1.1233374450683593), (10, 1.1922422119140625), (11, 1.1849612213134766), (12, 1.2522410217285156), (13, 1.213230340576172), (14, 1.4192644775390626), (15, 1.2837624328613282), (16, 1.501740072631836), (17, 1.3849537902832032), (18, 1.588652554321289), (19, 1.3984819427490234), (20, 1.650650045776367), (21, 1.4533444213867188), (22, 1.7273913604736328), (23, 1.4957280731201172), (24, 1.757539013671875), (25, 1.5174655639648438), (26, 1.7593667114257812), (27, 1.5364720001220704), (28, 1.6661353179931642), (29, 1.5261849884033203), (30, 1.7868651794433594)]
INFO flwr 2023-08-21 03:10:08,697 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4266), (2, 0.4377), (3, 0.5236), (4, 0.593), (5, 0.6145), (6, 0.6347), (7, 0.629), (8, 0.6494), (9, 0.673), (10, 0.6654), (11, 0.6838), (12, 0.6997), (13, 0.712), (14, 0.6863), (15, 0.6908), (16, 0.6717), (17, 0.7086), (18, 0.6773), (19, 0.7097), (20, 0.7292), (21, 0.7392), (22, 0.6839), (23, 0.7244), (24, 0.7237), (25, 0.7393), (26, 0.735), (27, 0.7254), (28, 0.746), (29, 0.7549), (30, 0.7365)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn34: task 0: Aborted
srun: Terminating StepId=3430914.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3430914
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 03:04:33
CPU Efficiency: 11.63% of 1-02:27:00 core-walltime
Job Wall-clock time: 01:28:10
Memory Utilized: 53.54 GB
Memory Efficiency: 44.62% of 120.00 GB
