-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:1000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:False
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:1000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:2
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
Simulating feddf training
INFO simulate 2023-09-20 11:26:15,266 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-09-20 11:26:15,266 | simulate.py:55 | Reading args from argument parser
INFO flwr 2023-09-20 11:26:37,017 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-20 11:26:39,513	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-20 11:26:40,521 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.66': 1.0, 'object_store_memory': 61847529062.0, 'accelerator_type:A100': 1.0, 'CPU': 18.0, 'memory': 103079215104.0, 'GPU': 1.0}
INFO flwr 2023-09-20 11:26:40,522 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-20 11:26:40,522 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-09-20 11:26:40,522 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3902873/1695201965_242538405/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3902873/1695201965_242538405/cifar-10-python.tar.gz to /scratch-local/sunnys.3902873/1695201965_242538405
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3902873/1695201965_242538405/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3902873/1695201965_242538405/cifar-100-python.tar.gz to /scratch-local/sunnys.3902873/1695201965_242538405
INFO flwr 2023-09-20 11:26:50,895 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-09-20 11:26:50,896 | server.py:101 | FL starting
DEBUG flwr 2023-09-20 11:26:53,383 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2241123)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2241118)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2241117)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2241121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2241124)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:28:13,037 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-20 11:28:13,060 | fed_df.py:366 | Warm start at round 1
INFO flwr 2023-09-20 11:28:13,131 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2241119)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2241118)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2241120)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2241117)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2241123)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2241121)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2241124)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2241122)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2241122)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2241119)[0m double free or corruption (fasttop)
E0920 11:28:15.137496944 2237927 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=2241120)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:28:47,250 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:28:47,251 | fed_df.py:551 | Average fusion training loss : 0.05206243683770299, val accuracy : 0.35902, best val accuracy : 0.4022
INFO flwr 2023-09-20 11:28:47,251 | common.py:35 | Avg. local train loss : 6.30339332409203, train acc : 0.6398819444444444
INFO flwr 2023-09-20 11:28:49,982 | server.py:116 | fit progress: (1, 1.6482290313720702, {'server_test_acc': 0.405}, 119.08641529921442)
INFO flwr 2023-09-20 11:28:49,982 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-09-20 11:28:52,372 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2367992)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367986)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:30:10,790 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-20 11:30:10,814 | fed_df.py:366 | Warm start at round 2
INFO flwr 2023-09-20 11:30:10,884 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2367991)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2367992)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2367985)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2367989)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2367993)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2367986)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2367988)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2367990)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2367988)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367993)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367989)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367991)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2367985)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2367990)[0m double free or corruption (fasttop)
E0920 11:30:13.089514033 2460438 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0920 11:30:13.089605505 2460438 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0920 11:30:13.089624599 2460438 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0920 11:30:13.089639346 2460438 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-09-20 11:30:45,076 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:30:45,077 | fed_df.py:551 | Average fusion training loss : 0.023051293220371007, val accuracy : 0.52188, best val accuracy : 0.5504
INFO flwr 2023-09-20 11:30:45,078 | common.py:35 | Avg. local train loss : 5.870474242791533, train acc : 0.6893472222222222
INFO flwr 2023-09-20 11:30:47,460 | server.py:116 | fit progress: (2, 1.5153007934570313, {'server_test_acc': 0.5466}, 236.5641659423709)
INFO flwr 2023-09-20 11:30:47,460 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-09-20 11:30:49,705 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2495031)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2495032)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2495027)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:32:08,762 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-20 11:32:08,798 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2495031)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2495032)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2495027)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2495030)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2495033)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2495035)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2495034)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2495028)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2495035)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2495033)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2495034)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2495030)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2495028)[0m malloc_consolidate(): invalid chunk size
E0920 11:32:11.182857684 2460574 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-09-20 11:32:43,452 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:32:43,452 | fed_df.py:551 | Average fusion training loss : 0.012766559736803174, val accuracy : 0.45276000000000005, best val accuracy : 0.49
INFO flwr 2023-09-20 11:32:43,453 | common.py:35 | Avg. local train loss : 4.464736913517116, train acc : 0.8338972222222222
INFO flwr 2023-09-20 11:32:45,803 | server.py:116 | fit progress: (3, 1.6576401702880859, {'server_test_acc': 0.4862}, 354.9071299182251)
INFO flwr 2023-09-20 11:32:45,803 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-09-20 11:32:48,070 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2628121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2628128)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2628131)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:34:06,631 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-20 11:34:06,654 | fed_df.py:366 | Warm start at round 4
INFO flwr 2023-09-20 11:34:06,726 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2628121)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2628129)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2628127)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2628130)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2628128)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2628124)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2628136)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2628131)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2628130)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2628124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2628129)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2628127)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2628136)[0m double free or corruption (fasttop)
E0920 11:34:08.744410181 2591248 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-09-20 11:34:41,418 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:34:41,418 | fed_df.py:551 | Average fusion training loss : 0.021722920909523963, val accuracy : 0.49972000000000005, best val accuracy : 0.5458
INFO flwr 2023-09-20 11:34:41,419 | common.py:35 | Avg. local train loss : 4.354633989557624, train acc : 0.8421611111111111
INFO flwr 2023-09-20 11:34:43,816 | server.py:116 | fit progress: (4, 1.5928300964355468, {'server_test_acc': 0.5371}, 472.92034440487623)
INFO flwr 2023-09-20 11:34:43,816 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-09-20 11:34:46,093 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2762132)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2762131)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:36:04,930 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-09-20 11:36:04,967 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2762129)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2762124)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2762132)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2762128)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2762126)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2762133)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2762131)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2762130)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2762130)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2762129)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2762133)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2762124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2762128)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2762126)[0m malloc_consolidate(): invalid chunk size
E0920 11:36:08.761000059 2724318 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-09-20 11:36:40,009 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:36:40,009 | fed_df.py:551 | Average fusion training loss : 0.010365607317071408, val accuracy : 0.53772, best val accuracy : 0.5788
INFO flwr 2023-09-20 11:36:40,010 | common.py:35 | Avg. local train loss : 4.16305884886533, train acc : 0.8650152777777778
INFO flwr 2023-09-20 11:36:42,386 | server.py:116 | fit progress: (5, 1.629374789428711, {'server_test_acc': 0.5679}, 591.4904958475381)
INFO flwr 2023-09-20 11:36:42,386 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-09-20 11:36:44,649 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2896656)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2896661)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:38:03,277 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-09-20 11:38:03,300 | fed_df.py:366 | Warm start at round 6
INFO flwr 2023-09-20 11:38:03,370 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2896656)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2896666)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2896653)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2896661)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2896659)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2896665)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2896668)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2896667)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2896666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2896659)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2896667)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2896665)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2896668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2896653)[0m double free or corruption (fasttop)
E0920 11:38:06.721443768 2860995 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-09-20 11:38:38,459 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:38:38,459 | fed_df.py:551 | Average fusion training loss : 0.019833300482947378, val accuracy : 0.59548, best val accuracy : 0.6282
INFO flwr 2023-09-20 11:38:38,460 | common.py:35 | Avg. local train loss : 4.328492369875312, train acc : 0.8503916666666667
INFO flwr 2023-09-20 11:38:40,846 | server.py:116 | fit progress: (6, 1.5782202117919921, {'server_test_acc': 0.6198}, 709.9507216345519)
INFO flwr 2023-09-20 11:38:40,847 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-09-20 11:38:43,113 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3030004)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3029998)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:40:02,197 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-20 11:40:02,235 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3029998)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3030008)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3030004)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3030007)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3030000)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3029999)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3030006)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3030003)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3029999)[0m malloc_consolidate(): invalid chunk size
E0920 11:40:02.656408306 2994114 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=3030003)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3030008)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3030000)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3030007)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3030006)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:40:37,349 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:40:37,350 | fed_df.py:551 | Average fusion training loss : 0.009886298443190753, val accuracy : 0.53444, best val accuracy : 0.5604
INFO flwr 2023-09-20 11:40:37,350 | common.py:35 | Avg. local train loss : 4.197840915247798, train acc : 0.8712444444444445
INFO flwr 2023-09-20 11:40:39,752 | server.py:116 | fit progress: (7, 1.6531849243164063, {'server_test_acc': 0.5571}, 828.8560520717874)
INFO flwr 2023-09-20 11:40:39,752 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-09-20 11:40:42,032 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3163749)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3163757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3163752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3163750)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3163755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3163756)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3163753)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:42:02,934 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-09-20 11:42:02,957 | fed_df.py:366 | Warm start at round 8
INFO flwr 2023-09-20 11:42:03,026 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3163756)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3163749)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3163750)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3163752)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3163757)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3163753)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3163755)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3163754)[0m Fitting Client 15
E0920 11:42:03.642118114 3125287 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=3163754)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:42:37,967 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:42:37,968 | fed_df.py:551 | Average fusion training loss : 0.02434284823620692, val accuracy : 0.5663199999999999, best val accuracy : 0.5988
INFO flwr 2023-09-20 11:42:37,968 | common.py:35 | Avg. local train loss : 4.278892620280385, train acc : 0.8598513888888887
INFO flwr 2023-09-20 11:42:40,366 | server.py:116 | fit progress: (8, 1.6711793212890624, {'server_test_acc': 0.5852}, 949.4706079149619)
INFO flwr 2023-09-20 11:42:40,367 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-09-20 11:42:42,637 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3290632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3290638)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3290634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3290637)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:44:01,270 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-09-20 11:44:01,306 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3290634)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3290637)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3290636)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3290635)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3290638)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3290633)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3290632)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3290631)[0m Fitting Client 18
E0920 11:44:01.943118306 3381211 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3290636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3290635)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3290631)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3290633)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:44:36,834 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:44:36,835 | fed_df.py:551 | Average fusion training loss : 0.010149626428261399, val accuracy : 0.61296, best val accuracy : 0.652
INFO flwr 2023-09-20 11:44:36,835 | common.py:35 | Avg. local train loss : 4.057543903775513, train acc : 0.8872430555555555
INFO flwr 2023-09-20 11:44:39,225 | server.py:116 | fit progress: (9, 1.7293688110351562, {'server_test_acc': 0.6321}, 1068.3294478859752)
INFO flwr 2023-09-20 11:44:39,225 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-09-20 11:44:41,483 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3417790)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:45:59,844 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-09-20 11:45:59,868 | fed_df.py:366 | Warm start at round 10
INFO flwr 2023-09-20 11:45:59,939 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3417789)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3417790)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3417788)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3417791)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3417787)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3417794)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3417793)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3417792)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3417788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3417787)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3417793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3417791)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3417794)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3417789)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3417792)[0m malloc_consolidate(): invalid chunk size
E0920 11:46:03.364484090 3381686 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-09-20 11:46:35,382 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:46:35,382 | fed_df.py:551 | Average fusion training loss : 0.016844265275169162, val accuracy : 0.6314200000000001, best val accuracy : 0.656
INFO flwr 2023-09-20 11:46:35,383 | common.py:35 | Avg. local train loss : 4.228044232726097, train acc : 0.8702777777777777
INFO flwr 2023-09-20 11:46:37,822 | server.py:116 | fit progress: (10, 1.6675810913085938, {'server_test_acc': 0.6441}, 1186.9260168075562)
INFO flwr 2023-09-20 11:46:37,822 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-09-20 11:46:40,246 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3545335)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:47:58,966 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-09-20 11:47:59,003 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3545337)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3545341)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3545339)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3545335)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3545338)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3545336)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3545342)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3545340)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3545339)[0m corrupted size vs. prev_size in fastbins
E0920 11:47:59.236998061 3511667 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=3545340)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3545337)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3545336)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3545338)[0m malloc_consolidate(): invalid chunk size
E0920 11:48:00.143226577 3641124 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=3545341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3545342)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:48:34,595 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:48:34,596 | fed_df.py:551 | Average fusion training loss : 0.00914081694977358, val accuracy : 0.6530800000000001, best val accuracy : 0.6756
INFO flwr 2023-09-20 11:48:34,597 | common.py:35 | Avg. local train loss : 4.264162345603108, train acc : 0.8729430555555556
INFO flwr 2023-09-20 11:48:36,995 | server.py:116 | fit progress: (11, 1.6697467956542968, {'server_test_acc': 0.6676}, 1306.099752499722)
INFO flwr 2023-09-20 11:48:36,996 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-09-20 11:48:39,273 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3679248)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3679259)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3679260)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:49:58,707 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-09-20 11:49:58,730 | fed_df.py:366 | Warm start at round 12
[2m[36m(launch_and_fit pid=3679261)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3679262)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:49:58,802 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3679248)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3679252)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3679254)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3679262)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3679260)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3679259)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3679261)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3679253)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3679254)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3679252)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3679253)[0m double free or corruption (fasttop)
E0920 11:50:00.329752317 3641344 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-09-20 11:50:34,316 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:50:34,316 | fed_df.py:551 | Average fusion training loss : 0.015363254809752107, val accuracy : 0.66374, best val accuracy : 0.6884
INFO flwr 2023-09-20 11:50:34,317 | common.py:35 | Avg. local train loss : 4.052524906955659, train acc : 0.8884402777777777
INFO flwr 2023-09-20 11:50:36,759 | server.py:116 | fit progress: (12, 1.6644481323242188, {'server_test_acc': 0.6734}, 1425.8633603397757)
INFO flwr 2023-09-20 11:50:36,759 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-09-20 11:50:39,029 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3813267)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3813274)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3813270)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:51:58,386 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-20 11:51:58,423 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3813274)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3813273)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3813267)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3813263)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3813266)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3813270)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3813269)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3813272)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3813272)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3813263)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3813266)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3813273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3813269)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:52:39,434 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:52:39,434 | fed_df.py:551 | Average fusion training loss : 0.01058401708304882, val accuracy : 0.59962, best val accuracy : 0.6146
INFO flwr 2023-09-20 11:52:39,435 | common.py:35 | Avg. local train loss : 3.83855413980782, train acc : 0.9083
INFO flwr 2023-09-20 11:52:41,830 | server.py:116 | fit progress: (13, 1.7517620483398437, {'server_test_acc': 0.6074}, 1550.934705699794)
INFO flwr 2023-09-20 11:52:41,831 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-09-20 11:52:44,130 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3947536)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3947537)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:54:02,788 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-20 11:54:02,812 | fed_df.py:366 | Warm start at round 14
INFO flwr 2023-09-20 11:54:02,883 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3947531)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3947536)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3947539)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3947538)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3947534)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3947537)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3947540)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3947535)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3947531)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3947535)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3947534)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3947540)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3947538)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3947539)[0m double free or corruption (fasttop)
E0920 11:54:06.424988283 3775328 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-09-20 11:54:38,780 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:54:38,780 | fed_df.py:551 | Average fusion training loss : 0.013621142804156989, val accuracy : 0.69286, best val accuracy : 0.7064
INFO flwr 2023-09-20 11:54:38,781 | common.py:35 | Avg. local train loss : 3.996114502474666, train acc : 0.8945777777777777
INFO flwr 2023-09-20 11:54:41,191 | server.py:116 | fit progress: (14, 1.6797783782958984, {'server_test_acc': 0.6891}, 1670.29551438801)
INFO flwr 2023-09-20 11:54:41,191 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-09-20 11:54:43,467 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4080802)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4080801)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:56:02,303 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-20 11:56:02,342 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4080804)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4080803)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4080805)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4080798)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4080800)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4080793)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4080801)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4080802)[0m Fitting Client 12
E0920 11:56:02.664298635 4045532 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=4080803)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4080798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4080800)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4080804)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4080793)[0m malloc_consolidate(): invalid chunk size
E0920 11:56:04.417396980 4177206 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-09-20 11:56:38,202 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:56:38,202 | fed_df.py:551 | Average fusion training loss : 0.01256383497035131, val accuracy : 0.64686, best val accuracy : 0.6942
INFO flwr 2023-09-20 11:56:38,203 | common.py:35 | Avg. local train loss : 3.8656213130801915, train acc : 0.9082111111111111
INFO flwr 2023-09-20 11:56:40,781 | server.py:116 | fit progress: (15, 1.734477471923828, {'server_test_acc': 0.6731}, 1789.8852787120268)
INFO flwr 2023-09-20 11:56:40,781 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-09-20 11:56:43,072 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=20344)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=20351)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=20349)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:58:01,491 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-09-20 11:58:01,515 | fed_df.py:366 | Warm start at round 16
INFO flwr 2023-09-20 11:58:01,585 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=20344)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=20343)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=20346)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=20348)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=20350)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=20349)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=20347)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=20351)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=20348)[0m double free or corruption (fasttop)
E0920 11:58:01.934812058 4177722 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=20343)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=20347)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=20346)[0m malloc_consolidate(): invalid chunk size
E0920 11:58:03.208979667  111921 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=20350)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:58:37,363 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:58:37,363 | fed_df.py:551 | Average fusion training loss : 0.02108919553598389, val accuracy : 0.6612600000000001, best val accuracy : 0.6938
INFO flwr 2023-09-20 11:58:37,364 | common.py:35 | Avg. local train loss : 3.9363271458074456, train acc : 0.9014708333333332
INFO flwr 2023-09-20 11:58:39,773 | server.py:116 | fit progress: (16, 1.658443701171875, {'server_test_acc': 0.6754}, 1908.8768741665408)
INFO flwr 2023-09-20 11:58:39,773 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-09-20 11:58:42,073 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=147790)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=147789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=147788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=147791)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:00:00,966 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-20 12:00:01,005 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=147790)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=147792)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=147793)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=147789)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=147784)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=147788)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=147791)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=147787)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=147793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=147792)[0m corrupted size vs. prev_size in fastbins
E0920 12:00:01.719318421  238565 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=147784)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=147787)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 12:00:37,040 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:00:37,040 | fed_df.py:551 | Average fusion training loss : 0.012444243468809874, val accuracy : 0.6877, best val accuracy : 0.7124
INFO flwr 2023-09-20 12:00:37,041 | common.py:35 | Avg. local train loss : 3.8794833598658442, train acc : 0.9100916666666666
INFO flwr 2023-09-20 12:00:39,466 | server.py:116 | fit progress: (17, 1.6898462768554687, {'server_test_acc': 0.6958}, 2028.5705495364964)
INFO flwr 2023-09-20 12:00:39,466 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-09-20 12:00:41,768 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=274781)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=274778)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=274783)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:02:00,808 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=274777)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:02:00,832 | fed_df.py:366 | Warm start at round 18
INFO flwr 2023-09-20 12:02:00,902 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=274777)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=274783)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=274781)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=274775)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=274779)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=274778)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=274782)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=274780)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=274780)[0m malloc_consolidate(): invalid chunk size
E0920 12:02:01.526266702  238835 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=274779)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=274775)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=274782)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:02:36,842 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:02:36,842 | fed_df.py:551 | Average fusion training loss : 0.01623391347331926, val accuracy : 0.68432, best val accuracy : 0.7
INFO flwr 2023-09-20 12:02:36,843 | common.py:35 | Avg. local train loss : 3.857903650775552, train acc : 0.9100472222222222
INFO flwr 2023-09-20 12:02:39,267 | server.py:116 | fit progress: (18, 1.6370129516601561, {'server_test_acc': 0.6891}, 2148.3709331387654)
INFO flwr 2023-09-20 12:02:39,267 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-09-20 12:02:41,566 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=403346)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:04:00,160 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-20 12:04:00,197 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=403346)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=403351)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=403354)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=403344)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=403349)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=403352)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=403350)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=403353)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=403344)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=403350)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=403351)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=403354)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=403353)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=403352)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=403349)[0m malloc_consolidate(): invalid chunk size
E0920 12:04:01.836646611  365540 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:04:36,463 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:04:36,464 | fed_df.py:551 | Average fusion training loss : 0.011959163379855454, val accuracy : 0.70866, best val accuracy : 0.7254
INFO flwr 2023-09-20 12:04:36,465 | common.py:35 | Avg. local train loss : 3.7941156500950455, train acc : 0.9164208333333332
INFO flwr 2023-09-20 12:04:38,881 | server.py:116 | fit progress: (19, 1.6476713775634766, {'server_test_acc': 0.7114}, 2267.985421584919)
INFO flwr 2023-09-20 12:04:38,881 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-09-20 12:04:41,186 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-20 12:05:59,672 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-20 12:05:59,696 | fed_df.py:366 | Warm start at round 20
INFO flwr 2023-09-20 12:05:59,766 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=537831)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=537833)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=537829)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=537824)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=537817)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=537819)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=537825)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=537832)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=537833)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=537819)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=537817)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=537829)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=537824)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=537825)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=537832)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=537831)[0m malloc_consolidate(): invalid chunk size
E0920 12:06:01.782009078  634272 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:06:36,137 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:06:36,138 | fed_df.py:551 | Average fusion training loss : 0.018654874758794904, val accuracy : 0.7116200000000001, best val accuracy : 0.7258
INFO flwr 2023-09-20 12:06:36,139 | common.py:35 | Avg. local train loss : 3.9454166492447253, train acc : 0.9053347222222221
INFO flwr 2023-09-20 12:06:38,559 | server.py:116 | fit progress: (20, 1.606076904296875, {'server_test_acc': 0.7128}, 2387.6631481945515)
INFO flwr 2023-09-20 12:06:38,559 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-09-20 12:06:41,020 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=671899)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-09-20 12:07:59,614 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-20 12:07:59,651 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=671899)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=671886)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=671895)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=671894)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=671893)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=671898)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=671896)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=671897)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=671895)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=671894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=671898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=671893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=671897)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=671896)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=671886)[0m malloc_consolidate(): invalid chunk size
E0920 12:08:01.969338240  634500 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:08:36,128 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:08:36,128 | fed_df.py:551 | Average fusion training loss : 0.013189490584190935, val accuracy : 0.7016399999999999, best val accuracy : 0.721
INFO flwr 2023-09-20 12:08:36,129 | common.py:35 | Avg. local train loss : 3.8609833193942906, train acc : 0.9146250000000001
INFO flwr 2023-09-20 12:08:38,608 | server.py:116 | fit progress: (21, 1.6059803894042968, {'server_test_acc': 0.7062}, 2507.712080045603)
INFO flwr 2023-09-20 12:08:38,608 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-09-20 12:08:40,934 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=804941)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=804940)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:10:00,050 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-09-20 12:10:00,074 | fed_df.py:366 | Warm start at round 22
INFO flwr 2023-09-20 12:10:00,143 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=804939)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=804934)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=804941)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=804938)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=804933)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=804940)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=804936)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=804935)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=804939)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=804933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=804936)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=804938)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=804934)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=804935)[0m malloc_consolidate(): invalid chunk size
E0920 12:10:03.686253254  901926 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:10:36,481 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:10:36,482 | fed_df.py:551 | Average fusion training loss : 0.0179896846213378, val accuracy : 0.6954199999999999, best val accuracy : 0.7114
INFO flwr 2023-09-20 12:10:36,483 | common.py:35 | Avg. local train loss : 3.735390178859234, train acc : 0.9209749999999999
INFO flwr 2023-09-20 12:10:38,906 | server.py:116 | fit progress: (22, 1.5809900512695312, {'server_test_acc': 0.6958}, 2628.009935989976)
INFO flwr 2023-09-20 12:10:38,906 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-09-20 12:10:41,209 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=939794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=939803)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:12:00,392 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-09-20 12:12:00,429 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=939803)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=939794)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=939799)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=939805)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=939796)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=939798)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=939806)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=939807)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=939805)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=939799)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=939806)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=939798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=939807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=939796)[0m malloc_consolidate(): invalid chunk size
E0920 12:12:02.546027880 1035192 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0920 12:12:02.546117475 1035192 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:12:36,676 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:12:36,677 | fed_df.py:551 | Average fusion training loss : 0.01288647288037464, val accuracy : 0.6812199999999999, best val accuracy : 0.6928
INFO flwr 2023-09-20 12:12:36,678 | common.py:35 | Avg. local train loss : 3.6630441132932905, train acc : 0.9279875
INFO flwr 2023-09-20 12:12:39,092 | server.py:116 | fit progress: (23, 1.651446157836914, {'server_test_acc': 0.6767}, 2748.1965867783874)
INFO flwr 2023-09-20 12:12:39,092 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-09-20 12:12:41,377 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1070659)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:13:59,881 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-20 12:13:59,905 | fed_df.py:366 | Warm start at round 24
INFO flwr 2023-09-20 12:13:59,976 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1070658)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1070659)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1070660)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1070662)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1070661)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1070655)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1070654)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1070652)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1070652)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1070658)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1070660)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1070661)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1070654)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1070655)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1070662)[0m double free or corruption (fasttop)
E0920 12:14:03.533595230 1162473 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:14:36,176 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:14:36,176 | fed_df.py:551 | Average fusion training loss : 0.018368067597970366, val accuracy : 0.72764, best val accuracy : 0.7398
INFO flwr 2023-09-20 12:14:36,177 | common.py:35 | Avg. local train loss : 3.889039110764861, train acc : 0.9099263888888887
INFO flwr 2023-09-20 12:14:38,609 | server.py:116 | fit progress: (24, 1.5951645690917968, {'server_test_acc': 0.7239}, 2867.7128866137937)
INFO flwr 2023-09-20 12:14:38,609 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-09-20 12:14:40,925 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1197646)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1197645)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:15:59,986 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-20 12:16:00,023 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1197646)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1197643)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1197642)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1197644)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1197640)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1197637)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1197645)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1197641)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1197642)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1197637)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1197643)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1197640)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1197644)[0m malloc_consolidate(): invalid chunk size
E0920 12:16:01.681093167 1289078 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1197641)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:16:36,459 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:16:36,460 | fed_df.py:551 | Average fusion training loss : 0.01527059238916263, val accuracy : 0.70642, best val accuracy : 0.7222
INFO flwr 2023-09-20 12:16:36,461 | common.py:35 | Avg. local train loss : 3.6812496798112986, train acc : 0.9273277777777778
INFO flwr 2023-09-20 12:16:38,893 | server.py:116 | fit progress: (25, 1.6766705627441407, {'server_test_acc': 0.7075}, 2987.9969112630934)
INFO flwr 2023-09-20 12:16:38,893 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-09-20 12:16:41,381 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1324809)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1324805)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1324808)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:17:59,749 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-09-20 12:17:59,773 | fed_df.py:366 | Warm start at round 26
INFO flwr 2023-09-20 12:17:59,842 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1324809)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1324805)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1324810)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1324813)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1324812)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1324808)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1324811)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1324814)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1324814)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1324813)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1324810)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1324812)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1324811)[0m double free or corruption (fasttop)
E0920 12:18:01.634413717 1289325 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:18:36,288 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:18:36,288 | fed_df.py:551 | Average fusion training loss : 0.018294695894699543, val accuracy : 0.74052, best val accuracy : 0.7514
INFO flwr 2023-09-20 12:18:36,289 | common.py:35 | Avg. local train loss : 3.8872985295951366, train acc : 0.9120666666666667
INFO flwr 2023-09-20 12:18:38,719 | server.py:116 | fit progress: (26, 1.5813793548583985, {'server_test_acc': 0.7325}, 3107.8235377101228)
INFO flwr 2023-09-20 12:18:38,719 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-09-20 12:18:41,038 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1454307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1454314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1454312)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:20:00,232 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1454304)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:20:00,270 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1454314)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1454312)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1454304)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1454306)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1454311)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1454307)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1454315)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1454313)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1454315)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1454313)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1454311)[0m malloc_consolidate(): invalid chunk size
E0920 12:20:01.369438829 1416647 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1454306)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:20:36,664 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:20:36,665 | fed_df.py:551 | Average fusion training loss : 0.016025489264633506, val accuracy : 0.72102, best val accuracy : 0.7376
INFO flwr 2023-09-20 12:20:36,666 | common.py:35 | Avg. local train loss : 3.6936072174459698, train acc : 0.9274666666666667
INFO flwr 2023-09-20 12:20:39,116 | server.py:116 | fit progress: (27, 1.6236662628173828, {'server_test_acc': 0.7255}, 3228.220279746689)
INFO flwr 2023-09-20 12:20:39,116 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-09-20 12:20:41,445 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1588580)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1588586)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:22:00,156 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-20 12:22:00,180 | fed_df.py:366 | Warm start at round 28
INFO flwr 2023-09-20 12:22:00,251 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1588580)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1588581)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1588587)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1588583)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1588586)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1588585)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1588582)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1588584)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1588584)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1588583)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1588587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1588585)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1588581)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1588582)[0m double free or corruption (fasttop)
E0920 12:22:03.711196721 1685646 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:22:36,714 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:22:36,714 | fed_df.py:551 | Average fusion training loss : 0.021502635768149047, val accuracy : 0.74238, best val accuracy : 0.75
INFO flwr 2023-09-20 12:22:36,715 | common.py:35 | Avg. local train loss : 3.8013917997479436, train acc : 0.9193930555555555
INFO flwr 2023-09-20 12:22:39,134 | server.py:116 | fit progress: (28, 1.5225814392089845, {'server_test_acc': 0.7411}, 3348.2384187513962)
INFO flwr 2023-09-20 12:22:39,134 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-09-20 12:22:41,472 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1723232)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:24:00,624 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-20 12:24:00,662 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1723233)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1723230)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1723229)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1723235)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1723234)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1723238)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1723237)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1723232)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1723230)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1723238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1723233)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1723229)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1723235)[0m malloc_consolidate(): invalid chunk size
E0920 12:24:02.276758034 1818727 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1723234)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1723237)[0m malloc_consolidate(): invalid chunk size
E0920 12:24:18.240121183 1834217 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:24:37,153 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:24:37,154 | fed_df.py:551 | Average fusion training loss : 0.016306403432041407, val accuracy : 0.7135800000000001, best val accuracy : 0.7314
INFO flwr 2023-09-20 12:24:37,155 | common.py:35 | Avg. local train loss : 3.6809644855558874, train acc : 0.9292999999999999
INFO flwr 2023-09-20 12:24:39,582 | server.py:116 | fit progress: (29, 1.6536943298339843, {'server_test_acc': 0.7212}, 3468.686754496768)
INFO flwr 2023-09-20 12:24:39,583 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-09-20 12:24:41,894 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1856467)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1856473)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:26:00,640 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-09-20 12:26:00,663 | fed_df.py:366 | Warm start at round 30
INFO flwr 2023-09-20 12:26:00,733 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1856473)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1856467)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1856477)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1856476)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1856466)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1856474)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1856475)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1856472)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1856466)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1856476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1856475)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1856474)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1856477)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1856472)[0m malloc_consolidate(): invalid chunk size
E0920 12:26:03.979998222 1834718 chttp2_transport.cc:1079]             ipv4:145.136.62.66:64128: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:26:37,317 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:26:37,317 | fed_df.py:551 | Average fusion training loss : 0.01637600141065195, val accuracy : 0.70636, best val accuracy : 0.717
INFO flwr 2023-09-20 12:26:37,318 | common.py:35 | Avg. local train loss : 3.502267198078335, train acc : 0.940025
INFO flwr 2023-09-20 12:26:39,900 | server.py:116 | fit progress: (30, 1.5806761260986328, {'server_test_acc': 0.7035}, 3589.0045393547043)
INFO flwr 2023-09-20 12:26:39,900 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-20 12:26:39,900 | server.py:144 | FL finished in 3589.0048420820385
INFO flwr 2023-09-20 12:26:39,901 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-20 12:26:39,901 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-20 12:26:39,901 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.6482290313720702), (2, 1.5153007934570313), (3, 1.6576401702880859), (4, 1.5928300964355468), (5, 1.629374789428711), (6, 1.5782202117919921), (7, 1.6531849243164063), (8, 1.6711793212890624), (9, 1.7293688110351562), (10, 1.6675810913085938), (11, 1.6697467956542968), (12, 1.6644481323242188), (13, 1.7517620483398437), (14, 1.6797783782958984), (15, 1.734477471923828), (16, 1.658443701171875), (17, 1.6898462768554687), (18, 1.6370129516601561), (19, 1.6476713775634766), (20, 1.606076904296875), (21, 1.6059803894042968), (22, 1.5809900512695312), (23, 1.651446157836914), (24, 1.5951645690917968), (25, 1.6766705627441407), (26, 1.5813793548583985), (27, 1.6236662628173828), (28, 1.5225814392089845), (29, 1.6536943298339843), (30, 1.5806761260986328)]
INFO flwr 2023-09-20 12:26:39,901 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.405), (2, 0.5466), (3, 0.4862), (4, 0.5371), (5, 0.5679), (6, 0.6198), (7, 0.5571), (8, 0.5852), (9, 0.6321), (10, 0.6441), (11, 0.6676), (12, 0.6734), (13, 0.6074), (14, 0.6891), (15, 0.6731), (16, 0.6754), (17, 0.6958), (18, 0.6891), (19, 0.7114), (20, 0.7128), (21, 0.7062), (22, 0.6958), (23, 0.6767), (24, 0.7239), (25, 0.7075), (26, 0.7325), (27, 0.7255), (28, 0.7411), (29, 0.7212), (30, 0.7035)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn66: task 0: Aborted
srun: Terminating StepId=3902873.0
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3902873
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:00:58
CPU Efficiency: 11.03% of 18:16:48 core-walltime
Job Wall-clock time: 01:00:56
Memory Utilized: 43.40 GB
Memory Efficiency: 36.17% of 120.00 GB
