-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:1000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:False
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:1000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
Simulating feddf training
INFO simulate 2023-09-20 11:27:47,625 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-09-20 11:27:47,636 | simulate.py:55 | Reading args from argument parser
INFO flwr 2023-09-20 11:28:09,076 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-20 11:28:16,444	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-20 11:28:17,444 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'CPU': 18.0, 'accelerator_type:A100': 1.0, 'GPU': 1.0, 'node:145.136.62.62': 1.0}
INFO flwr 2023-09-20 11:28:17,444 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-20 11:28:17,444 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-09-20 11:28:17,444 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3902869/1695201977_652728631/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3902869/1695201977_652728631/cifar-10-python.tar.gz to /scratch-local/sunnys.3902869/1695201977_652728631
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3902869/1695201977_652728631/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3902869/1695201977_652728631/cifar-100-python.tar.gz to /scratch-local/sunnys.3902869/1695201977_652728631
INFO flwr 2023-09-20 11:28:33,670 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-09-20 11:28:33,670 | server.py:101 | FL starting
DEBUG flwr 2023-09-20 11:28:37,551 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=297798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297800)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297797)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=297793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297795)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=297799)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:30:14,811 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-20 11:30:14,834 | fed_df.py:366 | Warm start at round 1
INFO flwr 2023-09-20 11:30:14,904 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=297794)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=297800)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=297795)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=297798)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=297799)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=297793)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=297797)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=297796)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=297796)[0m double free or corruption (fasttop)
E0920 11:30:19.742709723  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742828657  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742841061  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742849815  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742857794  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742865560  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742873408  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742881203  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742889158  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742896989  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742904786  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742912413  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742920273  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742930537  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742938641  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742946548  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742954310  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742961960  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742969632  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742977255  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742984996  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.742992728  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743000277  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743008104  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743015753  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743023455  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743032147  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743040057  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743047849  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743055507  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0920 11:30:19.743063439  390237 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-09-20 11:30:49,337 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:30:49,337 | fed_df.py:551 | Average fusion training loss : 0.04972048640996218, val accuracy : 0.37196, best val accuracy : 0.4242
INFO flwr 2023-09-20 11:30:49,338 | common.py:35 | Avg. local train loss : 6.755638895742595, train acc : 0.6001569444444443
INFO flwr 2023-09-20 11:30:52,087 | server.py:116 | fit progress: (1, 1.603173309326172, {'server_test_acc': 0.4279}, 138.41691811569035)
INFO flwr 2023-09-20 11:30:52,087 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-09-20 11:30:54,489 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=424736)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:32:15,984 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-20 11:32:16,007 | fed_df.py:366 | Warm start at round 2
INFO flwr 2023-09-20 11:32:16,078 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=424729)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=424731)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=424732)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=424728)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=424734)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=424736)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=424733)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=424735)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=424729)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=424733)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=424732)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=424735)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=424734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=424728)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=424731)[0m malloc_consolidate(): invalid chunk size
E0920 11:32:18.009823972  519479 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-09-20 11:32:51,138 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:32:51,138 | fed_df.py:551 | Average fusion training loss : 0.0346015360262245, val accuracy : 0.46530000000000005, best val accuracy : 0.501
INFO flwr 2023-09-20 11:32:51,139 | common.py:35 | Avg. local train loss : 5.229729020036757, train acc : 0.7518430555555556
INFO flwr 2023-09-20 11:32:53,558 | server.py:116 | fit progress: (2, 1.5722584503173829, {'server_test_acc': 0.5059}, 259.88720961101353)
INFO flwr 2023-09-20 11:32:53,558 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-09-20 11:32:55,829 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=556787)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=556780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=556788)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:34:15,210 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-20 11:34:15,233 | fed_df.py:366 | Warm start at round 3
INFO flwr 2023-09-20 11:34:15,304 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=556780)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=556789)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=556782)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=556787)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=556784)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=556786)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=556788)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=556790)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=556782)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=556784)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=556786)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=556790)[0m double free or corruption (fasttop)
E0920 11:34:16.878876782  519696 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=556789)[0m malloc_consolidate(): invalid chunk size
E0920 11:34:48.583893893  685555 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-09-20 11:34:50,379 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:34:50,380 | fed_df.py:551 | Average fusion training loss : 0.01709079864388332, val accuracy : 0.5739799999999999, best val accuracy : 0.6024
INFO flwr 2023-09-20 11:34:50,381 | common.py:35 | Avg. local train loss : 4.809876706637443, train acc : 0.8009319444444444
INFO flwr 2023-09-20 11:34:52,776 | server.py:116 | fit progress: (3, 1.6508866088867187, {'server_test_acc': 0.6012}, 379.10578001476824)
INFO flwr 2023-09-20 11:34:52,776 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-09-20 11:34:55,042 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=691403)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=691413)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:36:13,795 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-20 11:36:13,819 | fed_df.py:366 | Warm start at round 4
INFO flwr 2023-09-20 11:36:13,889 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=691410)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=691413)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=691404)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=691403)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=691409)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=691408)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=691406)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=691407)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=691407)[0m malloc_consolidate(): invalid chunk size
E0920 11:36:14.250043998  686570 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=691404)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=691406)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=691409)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=691408)[0m malloc_consolidate(): invalid chunk size
E0920 11:36:15.833510511  786145 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=691410)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:36:49,101 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:36:49,102 | fed_df.py:551 | Average fusion training loss : 0.023105065427254885, val accuracy : 0.6053000000000001, best val accuracy : 0.6318
INFO flwr 2023-09-20 11:36:49,102 | common.py:35 | Avg. local train loss : 4.315534200705589, train acc : 0.8555152777777777
INFO flwr 2023-09-20 11:36:51,502 | server.py:116 | fit progress: (4, 1.5203734680175782, {'server_test_acc': 0.6307}, 497.83162796031684)
INFO flwr 2023-09-20 11:36:51,502 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-09-20 11:36:53,774 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=825065)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:38:12,788 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-09-20 11:38:12,811 | fed_df.py:366 | Warm start at round 5
INFO flwr 2023-09-20 11:38:12,883 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=825069)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=825065)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=825071)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=825073)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=825072)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=825074)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=825077)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=825075)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=825071)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=825075)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=825069)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=825077)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=825073)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=825072)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=825074)[0m malloc_consolidate(): invalid chunk size
E0920 11:38:14.948911160  788016 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-09-20 11:38:48,953 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:38:48,954 | fed_df.py:551 | Average fusion training loss : 0.018137158297467978, val accuracy : 0.6347000000000002, best val accuracy : 0.6724
INFO flwr 2023-09-20 11:38:48,955 | common.py:35 | Avg. local train loss : 4.381388204917312, train acc : 0.8541930555555554
INFO flwr 2023-09-20 11:38:51,384 | server.py:116 | fit progress: (5, 1.5809531555175782, {'server_test_acc': 0.6693}, 617.7136682895944)
INFO flwr 2023-09-20 11:38:51,384 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-09-20 11:38:53,666 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=958867)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=958862)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=958865)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:40:13,408 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-09-20 11:40:13,432 | fed_df.py:366 | Warm start at round 6
INFO flwr 2023-09-20 11:40:13,503 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=958857)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=958866)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=958863)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=958867)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=958862)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=958861)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=958864)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=958865)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=958866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=958863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=958864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=958857)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=958861)[0m double free or corruption (fasttop)
E0920 11:40:15.221581553 1054777 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-09-20 11:40:49,409 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:40:49,410 | fed_df.py:551 | Average fusion training loss : 0.01673693010862917, val accuracy : 0.6614399999999999, best val accuracy : 0.6902
INFO flwr 2023-09-20 11:40:49,410 | common.py:35 | Avg. local train loss : 4.214713995344937, train acc : 0.8734055555555555
INFO flwr 2023-09-20 11:40:51,804 | server.py:116 | fit progress: (6, 1.5812418701171875, {'server_test_acc': 0.6865}, 738.1340545108542)
INFO flwr 2023-09-20 11:40:51,805 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-09-20 11:40:54,086 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1092437)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1092440)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1092439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1092432)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:42:13,931 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-20 11:42:13,954 | fed_df.py:366 | Warm start at round 7
INFO flwr 2023-09-20 11:42:14,025 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1092437)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1092438)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1092431)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1092436)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1092440)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1092432)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1092439)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1092435)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1092438)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1092431)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1092435)[0m double free or corruption (fasttop)
E0920 11:42:14.918225528 1184737 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=1092436)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:42:49,567 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:42:49,568 | fed_df.py:551 | Average fusion training loss : 0.01622238475875929, val accuracy : 0.6603600000000001, best val accuracy : 0.686
INFO flwr 2023-09-20 11:42:49,568 | common.py:35 | Avg. local train loss : 3.9696659311652187, train acc : 0.8963166666666667
INFO flwr 2023-09-20 11:42:52,000 | server.py:116 | fit progress: (7, 1.5929445556640625, {'server_test_acc': 0.6759}, 858.3296771580353)
INFO flwr 2023-09-20 11:42:52,000 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-09-20 11:42:54,287 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1220967)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:44:12,915 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-09-20 11:44:12,939 | fed_df.py:366 | Warm start at round 8
INFO flwr 2023-09-20 11:44:13,010 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1220974)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1220968)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1220975)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1220971)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1220969)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1220967)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1220973)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1220972)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1220972)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220973)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220969)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1220975)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220971)[0m double free or corruption (fasttop)
E0920 11:44:14.519543464 1185082 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=1220968)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1220974)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:44:49,070 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:44:49,071 | fed_df.py:551 | Average fusion training loss : 0.024787158239632845, val accuracy : 0.68486, best val accuracy : 0.7138
INFO flwr 2023-09-20 11:44:49,072 | common.py:35 | Avg. local train loss : 3.9468044418841597, train acc : 0.8991388888888889
INFO flwr 2023-09-20 11:44:51,488 | server.py:116 | fit progress: (8, 1.5147960968017578, {'server_test_acc': 0.7032}, 977.8179958313704)
INFO flwr 2023-09-20 11:44:51,489 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-09-20 11:44:53,788 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1347788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1347780)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:46:12,682 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1347786)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:46:12,706 | fed_df.py:366 | Warm start at round 9
INFO flwr 2023-09-20 11:46:12,776 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1347783)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1347780)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1347789)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1347786)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1347788)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1347787)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1347785)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1347790)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1347789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1347783)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1347790)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1347785)[0m malloc_consolidate(): invalid chunk size
E0920 11:46:14.819813332 1312548 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=1347787)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:46:53,573 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:46:53,573 | fed_df.py:551 | Average fusion training loss : 0.019903427545912563, val accuracy : 0.7072800000000001, best val accuracy : 0.7248
INFO flwr 2023-09-20 11:46:53,574 | common.py:35 | Avg. local train loss : 4.012127194367349, train acc : 0.8963541666666667
INFO flwr 2023-09-20 11:46:56,026 | server.py:116 | fit progress: (9, 1.510197817993164, {'server_test_acc': 0.7143}, 1102.3557333024219)
INFO flwr 2023-09-20 11:46:56,026 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-09-20 11:46:58,326 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1475948)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1475944)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:48:17,569 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-09-20 11:48:17,593 | fed_df.py:366 | Warm start at round 10
INFO flwr 2023-09-20 11:48:17,662 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1475948)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1475941)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1475946)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1475940)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1475937)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1475944)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1475938)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1475947)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1475946)[0m malloc_consolidate(): invalid chunk size
E0920 11:48:18.087605219 1571059 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1475941)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1475938)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1475940)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1475947)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1475937)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:48:53,521 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:48:53,521 | fed_df.py:551 | Average fusion training loss : 0.020273939279373734, val accuracy : 0.7144, best val accuracy : 0.7258
INFO flwr 2023-09-20 11:48:53,522 | common.py:35 | Avg. local train loss : 3.76715289875865, train acc : 0.9169222222222222
INFO flwr 2023-09-20 11:48:55,935 | server.py:116 | fit progress: (10, 1.4749478942871095, {'server_test_acc': 0.7159}, 1222.2645368874073)
INFO flwr 2023-09-20 11:48:55,935 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-09-20 11:48:58,236 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1610216)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1610211)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1610210)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:50:17,674 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-09-20 11:50:17,698 | fed_df.py:366 | Warm start at round 11
INFO flwr 2023-09-20 11:50:17,769 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1610213)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1610210)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1610211)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1610212)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1610215)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1610206)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1610216)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1610214)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1610206)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1610212)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1610214)[0m double free or corruption (fasttop)
E0920 11:50:18.839290040 1705868 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1610215)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1610213)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:50:53,685 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:50:53,685 | fed_df.py:551 | Average fusion training loss : 0.022881903568748384, val accuracy : 0.70984, best val accuracy : 0.729
INFO flwr 2023-09-20 11:50:53,686 | common.py:35 | Avg. local train loss : 3.7031625639647245, train acc : 0.9244875
INFO flwr 2023-09-20 11:50:56,122 | server.py:116 | fit progress: (11, 1.499104412841797, {'server_test_acc': 0.7223}, 1342.45157342311)
INFO flwr 2023-09-20 11:50:56,122 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-09-20 11:50:58,423 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-20 11:52:17,974 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-09-20 11:52:17,998 | fed_df.py:366 | Warm start at round 12
INFO flwr 2023-09-20 11:52:18,070 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1744122)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1744127)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1744126)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1744131)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1744129)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1744133)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1744130)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1744135)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1744130)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1744133)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1744131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1744122)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1744127)[0m double free or corruption (fasttop)
E0920 11:52:19.124983818 1706165 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1744135)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1744126)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1744129)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:52:54,238 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:52:54,239 | fed_df.py:551 | Average fusion training loss : 0.022468814136460423, val accuracy : 0.7213200000000001, best val accuracy : 0.7366
INFO flwr 2023-09-20 11:52:54,239 | common.py:35 | Avg. local train loss : 3.6417708884924656, train acc : 0.9290583333333333
INFO flwr 2023-09-20 11:52:56,684 | server.py:116 | fit progress: (12, 1.4120682312011719, {'server_test_acc': 0.7327}, 1463.0133160343394)
INFO flwr 2023-09-20 11:52:56,684 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-09-20 11:52:59,014 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1877157)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1877160)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1877168)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 11:54:18,726 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-20 11:54:18,750 | fed_df.py:366 | Warm start at round 13
INFO flwr 2023-09-20 11:54:18,820 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1877157)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1877164)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1877165)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1877166)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1877158)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1877168)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1877160)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1877167)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1877166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1877165)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1877167)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1877164)[0m malloc_consolidate(): invalid chunk size
E0920 11:54:20.467098470 1839617 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0920 11:54:53.087717005 2005588 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-09-20 11:54:55,103 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:54:55,104 | fed_df.py:551 | Average fusion training loss : 0.026859261324629187, val accuracy : 0.71724, best val accuracy : 0.7304
INFO flwr 2023-09-20 11:54:55,105 | common.py:35 | Avg. local train loss : 3.681495442427695, train acc : 0.9252444444444444
INFO flwr 2023-09-20 11:54:57,522 | server.py:116 | fit progress: (13, 1.4947557006835936, {'server_test_acc': 0.7237}, 1583.8517068671063)
INFO flwr 2023-09-20 11:54:57,522 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-09-20 11:54:59,841 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-20 11:56:18,955 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-20 11:56:18,978 | fed_df.py:366 | Warm start at round 14
INFO flwr 2023-09-20 11:56:19,051 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2011334)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2011330)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2011333)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2011323)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2011331)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2011332)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2011335)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2011326)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2011331)[0m malloc_consolidate(): invalid chunk size
E0920 11:56:19.621216105 2105811 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2011323)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2011326)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2011330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2011333)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2011334)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2011332)[0m malloc_consolidate(): invalid chunk size
E0920 11:56:21.004795965 2106168 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2011335)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 11:57:00,096 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:57:00,096 | fed_df.py:551 | Average fusion training loss : 0.02121977992868051, val accuracy : 0.7060600000000001, best val accuracy : 0.7198
INFO flwr 2023-09-20 11:57:00,097 | common.py:35 | Avg. local train loss : 3.598277189768851, train acc : 0.9314819444444445
INFO flwr 2023-09-20 11:57:02,542 | server.py:116 | fit progress: (14, 1.518309603881836, {'server_test_acc': 0.7233}, 1708.8714421931654)
INFO flwr 2023-09-20 11:57:02,542 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-09-20 11:57:04,844 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2143634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2143630)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 11:58:25,363 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-20 11:58:25,387 | fed_df.py:366 | Warm start at round 15
[2m[36m(launch_and_fit pid=2143633)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:58:25,458 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2143630)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2143632)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2143637)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2143633)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2143636)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2143635)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2143629)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2143634)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2143636)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2143637)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2143632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2143629)[0m double free or corruption (fasttop)
E0920 11:58:27.458515949 2107644 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2143635)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 11:59:01,398 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 11:59:01,399 | fed_df.py:551 | Average fusion training loss : 0.02358252458181232, val accuracy : 0.7207600000000001, best val accuracy : 0.7366
INFO flwr 2023-09-20 11:59:01,400 | common.py:35 | Avg. local train loss : 3.5797239009290935, train acc : 0.9316166666666668
INFO flwr 2023-09-20 11:59:03,814 | server.py:116 | fit progress: (15, 1.4880407684326171, {'server_test_acc': 0.7295}, 1830.1438456391916)
INFO flwr 2023-09-20 11:59:03,814 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-09-20 11:59:06,128 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2270955)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2270946)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2270954)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2270947)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:00:25,487 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-09-20 12:00:25,510 | fed_df.py:366 | Warm start at round 16
INFO flwr 2023-09-20 12:00:25,582 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2270939)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2270953)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2270947)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2270946)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2270955)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2270944)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2270954)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2270945)[0m Fitting Client 4
E0920 12:00:25.901488162 2236250 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2270939)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2270953)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2270944)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2270945)[0m malloc_consolidate(): invalid chunk size
E0920 12:00:49.762318329 2383642 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:01:01,451 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:01:01,451 | fed_df.py:551 | Average fusion training loss : 0.02096947998087853, val accuracy : 0.69756, best val accuracy : 0.7214
INFO flwr 2023-09-20 12:01:01,452 | common.py:35 | Avg. local train loss : 3.4377033332362767, train acc : 0.9426694444444443
INFO flwr 2023-09-20 12:01:03,880 | server.py:116 | fit progress: (16, 1.5092686492919922, {'server_test_acc': 0.7189}, 1950.2091889539734)
INFO flwr 2023-09-20 12:01:03,880 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-09-20 12:01:06,200 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2397860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2397853)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:02:25,074 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-20 12:02:25,098 | fed_df.py:366 | Warm start at round 17
INFO flwr 2023-09-20 12:02:25,168 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2397860)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2397853)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2397859)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2397858)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2397855)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2397856)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2397850)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2397857)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2397850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2397858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2397855)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2397856)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2397859)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2397857)[0m double free or corruption (fasttop)
E0920 12:02:27.306316413 2384099 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:03:01,234 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:03:01,234 | fed_df.py:551 | Average fusion training loss : 0.023288424530997873, val accuracy : 0.7075400000000001, best val accuracy : 0.7312
INFO flwr 2023-09-20 12:03:01,235 | common.py:35 | Avg. local train loss : 3.4544353628531095, train acc : 0.942238888888889
INFO flwr 2023-09-20 12:03:03,677 | server.py:116 | fit progress: (17, 1.4854941528320313, {'server_test_acc': 0.7314}, 2070.0067398743704)
INFO flwr 2023-09-20 12:03:03,677 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-09-20 12:03:05,989 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-20 12:04:25,126 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-20 12:04:25,150 | fed_df.py:366 | Warm start at round 18
[2m[36m(launch_and_fit pid=2529329)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 12:04:25,222 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2529340)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2529339)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2529336)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2529329)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2529337)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2529334)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2529338)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2529335)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2529339)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2529340)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2529336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2529338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2529337)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2529335)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2529334)[0m malloc_consolidate(): invalid chunk size
E0920 12:04:27.550388473 2491944 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0920 12:04:40.495140337 2625917 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:05:01,449 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:05:01,450 | fed_df.py:551 | Average fusion training loss : 0.023900141043588518, val accuracy : 0.7126999999999999, best val accuracy : 0.7254
INFO flwr 2023-09-20 12:05:01,450 | common.py:35 | Avg. local train loss : 3.4955048276111484, train acc : 0.9404499999999999
INFO flwr 2023-09-20 12:05:03,896 | server.py:116 | fit progress: (18, 1.5442583282470703, {'server_test_acc': 0.7099}, 2190.226162539795)
INFO flwr 2023-09-20 12:05:03,897 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-09-20 12:05:06,227 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2662588)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:06:25,068 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-20 12:06:25,091 | fed_df.py:366 | Warm start at round 19
INFO flwr 2023-09-20 12:06:25,164 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2662582)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2662580)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2662591)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2662581)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2662588)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2662584)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2662578)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2662590)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2662580)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2662582)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2662584)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2662581)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2662591)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2662578)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2662590)[0m malloc_consolidate(): invalid chunk size
E0920 12:06:28.354421542 2759729 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:07:03,401 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:07:03,402 | fed_df.py:551 | Average fusion training loss : 0.02720367528684437, val accuracy : 0.7231, best val accuracy : 0.7396
INFO flwr 2023-09-20 12:07:03,402 | common.py:35 | Avg. local train loss : 3.3858099887147546, train acc : 0.9490638888888888
INFO flwr 2023-09-20 12:07:05,845 | server.py:116 | fit progress: (19, 1.5216160827636718, {'server_test_acc': 0.7327}, 2312.174254416488)
INFO flwr 2023-09-20 12:07:05,845 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-09-20 12:07:08,155 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2796867)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2796855)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-20 12:08:27,639 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-20 12:08:27,663 | fed_df.py:366 | Warm start at round 20
INFO flwr 2023-09-20 12:08:27,734 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2796860)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2796858)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2796855)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2796863)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2796867)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2796861)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2796864)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2796862)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2796860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2796858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2796863)[0m corrupted size vs. prev_size in fastbins
E0920 12:08:28.416952617 2891560 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2796864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2796861)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2796862)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 12:09:03,993 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:09:03,993 | fed_df.py:551 | Average fusion training loss : 0.028008160346187652, val accuracy : 0.73164, best val accuracy : 0.743
INFO flwr 2023-09-20 12:09:03,994 | common.py:35 | Avg. local train loss : 3.40702350102365, train acc : 0.9479694444444444
INFO flwr 2023-09-20 12:09:06,429 | server.py:116 | fit progress: (20, 1.4807340728759766, {'server_test_acc': 0.7372}, 2432.7586839664727)
INFO flwr 2023-09-20 12:09:06,429 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-09-20 12:09:08,726 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-20 12:10:28,072 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-20 12:10:28,096 | fed_df.py:366 | Warm start at round 21
INFO flwr 2023-09-20 12:10:28,167 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2930386)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2930397)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2930394)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2930396)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2930393)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2930395)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2930387)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2930392)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2930397)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2930393)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2930396)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2930387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2930394)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2930386)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2930392)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2930395)[0m double free or corruption (fasttop)
E0920 12:10:32.423630987 3029072 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:11:04,591 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:11:04,592 | fed_df.py:551 | Average fusion training loss : 0.03223372319666669, val accuracy : 0.72644, best val accuracy : 0.739
INFO flwr 2023-09-20 12:11:04,593 | common.py:35 | Avg. local train loss : 3.4094533607363697, train acc : 0.9461916666666667
INFO flwr 2023-09-20 12:11:07,039 | server.py:116 | fit progress: (21, 1.5087847930908203, {'server_test_acc': 0.7398}, 2553.368493039161)
INFO flwr 2023-09-20 12:11:07,039 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-09-20 12:11:09,364 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3064881)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:12:28,302 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-09-20 12:12:28,326 | fed_df.py:366 | Warm start at round 22
INFO flwr 2023-09-20 12:12:28,398 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3064878)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3064881)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3064876)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3064879)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3064875)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3064880)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3064874)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3064877)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3064876)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3064874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3064878)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3064877)[0m malloc_consolidate(): invalid chunk size
E0920 12:12:29.465749462 3029663 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3064879)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3064880)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3064875)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 12:13:04,787 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:13:04,787 | fed_df.py:551 | Average fusion training loss : 0.02523551692860201, val accuracy : 0.69644, best val accuracy : 0.7028
INFO flwr 2023-09-20 12:13:04,788 | common.py:35 | Avg. local train loss : 3.4032913269475102, train acc : 0.9464041666666667
INFO flwr 2023-09-20 12:13:07,246 | server.py:116 | fit progress: (22, 1.520107470703125, {'server_test_acc': 0.7058}, 2673.5760317137465)
INFO flwr 2023-09-20 12:13:07,247 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-09-20 12:13:09,579 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-20 12:14:29,620 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-09-20 12:14:29,644 | fed_df.py:366 | Warm start at round 23
INFO flwr 2023-09-20 12:14:29,716 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3193626)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3193622)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3193624)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3193621)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3193623)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3193625)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3193627)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3193628)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3193622)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3193625)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3193627)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3193621)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3193626)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3193624)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3193623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3193628)[0m malloc_consolidate(): invalid chunk size
E0920 12:14:34.879749438 3157848 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:15:06,302 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:15:06,302 | fed_df.py:551 | Average fusion training loss : 0.029515588477253912, val accuracy : 0.73662, best val accuracy : 0.7432
INFO flwr 2023-09-20 12:15:06,303 | common.py:35 | Avg. local train loss : 3.410070256516337, train acc : 0.9471541666666666
INFO flwr 2023-09-20 12:15:08,756 | server.py:116 | fit progress: (23, 1.5079069366455078, {'server_test_acc': 0.739}, 2795.085670577362)
INFO flwr 2023-09-20 12:15:08,756 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-09-20 12:15:11,058 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3320943)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:16:30,875 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-20 12:16:30,899 | fed_df.py:366 | Warm start at round 24
INFO flwr 2023-09-20 12:16:30,971 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3320941)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3320940)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3320935)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3320939)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3320942)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3320943)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3320933)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3320937)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3320942)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3320935)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3320933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3320941)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3320937)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3320940)[0m malloc_consolidate(): invalid chunk size
E0920 12:16:32.503914987 3289232 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3320939)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:17:07,608 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:17:07,608 | fed_df.py:551 | Average fusion training loss : 0.030308169045485556, val accuracy : 0.7117199999999999, best val accuracy : 0.7224
INFO flwr 2023-09-20 12:17:07,609 | common.py:35 | Avg. local train loss : 3.470925139449537, train acc : 0.9445680555555555
INFO flwr 2023-09-20 12:17:10,092 | server.py:116 | fit progress: (24, 1.4769681213378907, {'server_test_acc': 0.7143}, 2916.4218762032688)
INFO flwr 2023-09-20 12:17:10,092 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-09-20 12:17:12,434 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3448411)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:18:31,240 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-20 12:18:31,264 | fed_df.py:366 | Warm start at round 25
INFO flwr 2023-09-20 12:18:31,334 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3448412)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3448410)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3448414)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3448408)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3448411)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3448409)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3448413)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3448407)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3448412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3448413)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3448410)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3448409)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3448408)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3448407)[0m malloc_consolidate(): invalid chunk size
E0920 12:18:33.285986703 3412925 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:19:09,640 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:19:09,641 | fed_df.py:551 | Average fusion training loss : 0.034998709619045255, val accuracy : 0.71668, best val accuracy : 0.7312
INFO flwr 2023-09-20 12:19:09,641 | common.py:35 | Avg. local train loss : 3.3133885053917767, train acc : 0.9532402777777779
INFO flwr 2023-09-20 12:19:12,098 | server.py:116 | fit progress: (25, 1.4989963897705079, {'server_test_acc': 0.7217}, 3038.4279891038314)
INFO flwr 2023-09-20 12:19:12,099 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-09-20 12:19:14,511 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3580449)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3580445)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3580442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3580441)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3580450)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3580446)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3580447)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:20:39,797 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-09-20 12:20:39,821 | fed_df.py:366 | Warm start at round 26
INFO flwr 2023-09-20 12:20:39,891 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3580449)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3580445)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3580442)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3580446)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3580441)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3580450)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3580447)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3580448)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3580448)[0m double free or corruption (fasttop)
E0920 12:20:41.924352950 3542522 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:21:17,838 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:21:17,838 | fed_df.py:551 | Average fusion training loss : 0.02797247911989689, val accuracy : 0.7256600000000001, best val accuracy : 0.7406
INFO flwr 2023-09-20 12:21:17,839 | common.py:35 | Avg. local train loss : 3.3309459274634716, train acc : 0.9539597222222221
INFO flwr 2023-09-20 12:21:20,354 | server.py:116 | fit progress: (26, 1.4925187377929687, {'server_test_acc': 0.7415}, 3166.6838477952406)
INFO flwr 2023-09-20 12:21:20,354 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-09-20 12:21:22,680 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3714834)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3714826)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3714816)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3714825)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:22:42,101 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-20 12:22:42,125 | fed_df.py:366 | Warm start at round 27
INFO flwr 2023-09-20 12:22:42,196 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3714833)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3714834)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3714829)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3714816)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3714831)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3714826)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3714830)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3714825)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3714829)[0m malloc_consolidate(): invalid chunk size
E0920 12:22:42.755726595 3677196 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3714831)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3714833)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3714830)[0m malloc_consolidate(): invalid chunk size
E0920 12:23:00.396486105 3809916 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:23:18,939 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:23:18,940 | fed_df.py:551 | Average fusion training loss : 0.030280813643708826, val accuracy : 0.71168, best val accuracy : 0.7244
INFO flwr 2023-09-20 12:23:18,941 | common.py:35 | Avg. local train loss : 3.360369535163045, train acc : 0.9498486111111112
INFO flwr 2023-09-20 12:23:21,414 | server.py:116 | fit progress: (27, 1.5310676330566406, {'server_test_acc': 0.715}, 3287.743197157979)
INFO flwr 2023-09-20 12:23:21,414 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-09-20 12:23:23,740 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3848665)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:24:42,868 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-20 12:24:42,893 | fed_df.py:366 | Warm start at round 28
INFO flwr 2023-09-20 12:24:42,964 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3848669)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3848666)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3848656)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3848662)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3848663)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3848665)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3848668)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3848664)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3848664)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3848662)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3848669)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3848656)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3848668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3848663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3848666)[0m malloc_consolidate(): invalid chunk size
E0920 12:24:45.986141052 3827423 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-20 12:25:20,065 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:25:20,066 | fed_df.py:551 | Average fusion training loss : 0.03104356404254213, val accuracy : 0.74048, best val accuracy : 0.7518
INFO flwr 2023-09-20 12:25:20,066 | common.py:35 | Avg. local train loss : 3.2820660330355165, train acc : 0.9567694444444443
INFO flwr 2023-09-20 12:25:22,523 | server.py:116 | fit progress: (28, 1.4828410308837892, {'server_test_acc': 0.7447}, 3408.8531610602513)
INFO flwr 2023-09-20 12:25:22,524 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-09-20 12:25:24,872 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3982936)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3982935)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3982934)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3982938)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3982937)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:26:44,935 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-20 12:26:44,958 | fed_df.py:366 | Warm start at round 29
INFO flwr 2023-09-20 12:26:45,030 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3982940)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3982936)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3982935)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3982934)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3982939)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3982937)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3982938)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3982933)[0m Fitting Client 14
E0920 12:26:45.523651283 3945363 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3982933)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3982939)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3982940)[0m double free or corruption (fasttop)
INFO flwr 2023-09-20 12:27:21,917 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:27:21,917 | fed_df.py:551 | Average fusion training loss : 0.032306269926950335, val accuracy : 0.7364599999999999, best val accuracy : 0.7504
INFO flwr 2023-09-20 12:27:21,918 | common.py:35 | Avg. local train loss : 3.321637052297592, train acc : 0.9533430555555557
INFO flwr 2023-09-20 12:27:24,378 | server.py:116 | fit progress: (29, 1.479255682373047, {'server_test_acc': 0.7478}, 3530.7077804394066)
INFO flwr 2023-09-20 12:27:24,378 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-09-20 12:27:26,710 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4116769)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4116773)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-20 12:28:45,723 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-09-20 12:28:45,747 | fed_df.py:366 | Warm start at round 30
INFO flwr 2023-09-20 12:28:45,817 | fed_df.py:464 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4116769)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4116772)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4116774)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4116773)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4116766)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4116771)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4116776)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4116775)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4116771)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4116766)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4116775)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4116774)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4116776)[0m malloc_consolidate(): invalid chunk size
E0920 12:28:47.879224180   15239 chttp2_transport.cc:1079]             ipv4:145.136.62.62:62782: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4116772)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-20 12:29:22,735 | fed_df.py:544 | Distillation training stopped at step number : 500
INFO flwr 2023-09-20 12:29:22,736 | fed_df.py:551 | Average fusion training loss : 0.031205835478380323, val accuracy : 0.73404, best val accuracy : 0.7428
INFO flwr 2023-09-20 12:29:22,737 | common.py:35 | Avg. local train loss : 3.2505151674151422, train acc : 0.9578888888888889
INFO flwr 2023-09-20 12:29:25,194 | server.py:116 | fit progress: (30, 1.4683595428466796, {'server_test_acc': 0.7418}, 3651.52358847484)
INFO flwr 2023-09-20 12:29:25,194 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-20 12:29:25,194 | server.py:144 | FL finished in 3651.5239243013784
INFO flwr 2023-09-20 12:29:25,194 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-20 12:29:25,195 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-20 12:29:25,195 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.603173309326172), (2, 1.5722584503173829), (3, 1.6508866088867187), (4, 1.5203734680175782), (5, 1.5809531555175782), (6, 1.5812418701171875), (7, 1.5929445556640625), (8, 1.5147960968017578), (9, 1.510197817993164), (10, 1.4749478942871095), (11, 1.499104412841797), (12, 1.4120682312011719), (13, 1.4947557006835936), (14, 1.518309603881836), (15, 1.4880407684326171), (16, 1.5092686492919922), (17, 1.4854941528320313), (18, 1.5442583282470703), (19, 1.5216160827636718), (20, 1.4807340728759766), (21, 1.5087847930908203), (22, 1.520107470703125), (23, 1.5079069366455078), (24, 1.4769681213378907), (25, 1.4989963897705079), (26, 1.4925187377929687), (27, 1.5310676330566406), (28, 1.4828410308837892), (29, 1.479255682373047), (30, 1.4683595428466796)]
INFO flwr 2023-09-20 12:29:25,196 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4279), (2, 0.5059), (3, 0.6012), (4, 0.6307), (5, 0.6693), (6, 0.6865), (7, 0.6759), (8, 0.7032), (9, 0.7143), (10, 0.7159), (11, 0.7223), (12, 0.7327), (13, 0.7237), (14, 0.7233), (15, 0.7295), (16, 0.7189), (17, 0.7314), (18, 0.7099), (19, 0.7327), (20, 0.7372), (21, 0.7398), (22, 0.7058), (23, 0.739), (24, 0.7143), (25, 0.7217), (26, 0.7415), (27, 0.715), (28, 0.7447), (29, 0.7478), (30, 0.7418)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn62: task 0: Aborted
srun: Terminating StepId=3902869.0
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3902869
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:05:02
CPU Efficiency: 10.90% of 19:06:54 core-walltime
Job Wall-clock time: 01:03:43
Memory Utilized: 42.75 GB
Memory Efficiency: 35.63% of 120.00 GB
