-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:True
USE_FEDPROX:True
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3431066/1692581994_967012180', seed=42, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3431066/1692581994_967012180/single_img_crops/crops
50000 took 0.36min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-21 03:40:33,290 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-21 03:40:33,290 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3431066/1692581994_967012180/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3431066/1692581994_967012180/cifar-10-python.tar.gz to /scratch-local/sunnys.3431066/1692581994_967012180
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
INFO flwr 2023-08-21 03:41:06,121 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-21 03:41:08,638	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-21 03:41:09,672 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0, 'node:145.136.62.46': 1.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-21 03:41:09,672 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-21 03:41:09,672 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-21 03:41:09,672 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-21 03:41:21,488 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-21 03:41:21,488 | server.py:101 | FL starting
DEBUG flwr 2023-08-21 03:41:27,955 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3067308)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 03:42:50,743 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-21 03:42:50,851 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-21 03:42:50,940 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3067312)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3067315)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3067313)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3067314)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3067310)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3067308)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3067311)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3067316)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3067312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3067311)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3067314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3067315)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3067310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3067316)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3067313)[0m double free or corruption (fasttop)
E0821 03:42:53.188259101 3061572 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0821 03:42:53.188656748 3061572 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0821 03:42:53.188672597 3061572 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0821 03:42:53.188689413 3061572 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0821 03:42:53.188701706 3061572 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-21 03:44:17,970 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:44:17,970 | fed_df.py:547 | Average fusion training loss : 0.01133467759937048, val accuracy : 0.40713999999999995, best val accuracy : 0.449
INFO flwr 2023-08-21 03:44:17,971 | common.py:35 | Avg. local train loss : 6.757860815338791, train acc : 0.6000958333333334
INFO flwr 2023-08-21 03:44:20,526 | server.py:116 | fit progress: (1, 1.5781340393066405, {'server_test_acc': 0.4459}, 179.0378895730246)
INFO flwr 2023-08-21 03:44:20,527 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-21 03:44:26,462 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3399327)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3399172)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 03:45:46,388 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-21 03:45:46,497 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-21 03:45:46,586 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3399327)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3399172)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3399241)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3399312)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3399242)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3399310)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3399348)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3399311)[0m Fitting Client 8
E0821 03:45:47.029318771 3555824 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=3399242)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3399241)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3399311)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3399348)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3399310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3399312)[0m double free or corruption (fasttop)
E0821 03:46:45.602867317 3667357 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-21 03:47:18,956 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:47:18,956 | fed_df.py:547 | Average fusion training loss : 0.007120633291546255, val accuracy : 0.50926, best val accuracy : 0.5294
INFO flwr 2023-08-21 03:47:18,957 | common.py:35 | Avg. local train loss : 5.3347053732723, train acc : 0.7409583333333333
INFO flwr 2023-08-21 03:47:21,606 | server.py:116 | fit progress: (2, 1.4870212677001953, {'server_test_acc': 0.5253}, 360.117253059987)
INFO flwr 2023-08-21 03:47:21,606 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-21 03:47:27,647 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 03:48:46,789 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-21 03:48:46,899 | fed_df.py:365 | Warm start at round 3
[2m[36m(launch_and_fit pid=3735539)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 03:48:46,989 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3735540)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3735541)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3735542)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3735544)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3735539)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3735545)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3735470)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3735538)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3735541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3735470)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3735542)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3735540)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3735538)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3735545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3735544)[0m malloc_consolidate(): invalid chunk size
E0821 03:48:48.871029841 3669955 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-21 03:50:21,064 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:50:21,064 | fed_df.py:547 | Average fusion training loss : 0.009433379175607114, val accuracy : 0.57764, best val accuracy : 0.6196
INFO flwr 2023-08-21 03:50:21,066 | common.py:35 | Avg. local train loss : 4.805454382859171, train acc : 0.7982333333333334
INFO flwr 2023-08-21 03:50:23,763 | server.py:116 | fit progress: (3, 1.5198754180908203, {'server_test_acc': 0.6101}, 542.2749336779816)
INFO flwr 2023-08-21 03:50:23,764 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-21 03:50:29,691 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4072288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072356)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072357)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 03:51:50,071 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-21 03:51:50,179 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-21 03:51:50,265 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4072231)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4072357)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4072356)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4072287)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4072359)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4072360)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4072288)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4072358)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4072287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072358)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072360)[0m malloc_consolidate(): invalid chunk size
E0821 03:51:51.513498621 3895354 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=4072359)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072231)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 03:53:22,627 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:53:22,628 | fed_df.py:547 | Average fusion training loss : 0.010061830576509237, val accuracy : 0.5295599999999999, best val accuracy : 0.5922
INFO flwr 2023-08-21 03:53:22,628 | common.py:35 | Avg. local train loss : 4.320509464479983, train acc : 0.8540916666666667
INFO flwr 2023-08-21 03:53:25,310 | server.py:116 | fit progress: (4, 1.7195905242919922, {'server_test_acc': 0.5869}, 723.8217984230723)
INFO flwr 2023-08-21 03:53:25,311 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-21 03:53:31,314 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=215835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=215836)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 03:54:51,499 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-21 03:54:51,608 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-21 03:54:51,695 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=215835)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=215836)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=215951)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=215950)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=215952)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=215954)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=215949)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=215953)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=215950)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=215949)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=215951)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=215952)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=215954)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=215953)[0m double free or corruption (fasttop)
E0821 03:54:54.310269902   39821 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
E0821 03:55:00.916644179  377187 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
E0821 03:55:46.331958760  391604 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-21 03:56:25,031 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:56:25,031 | fed_df.py:547 | Average fusion training loss : 0.007964610643917694, val accuracy : 0.52292, best val accuracy : 0.6424
INFO flwr 2023-08-21 03:56:25,032 | common.py:35 | Avg. local train loss : 4.471870137378573, train acc : 0.8452472222222223
INFO flwr 2023-08-21 03:56:27,695 | server.py:116 | fit progress: (5, 1.8885771423339843, {'server_test_acc': 0.6377}, 906.206400915049)
INFO flwr 2023-08-21 03:56:27,695 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-21 03:56:33,662 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=560273)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=560281)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=560282)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 03:57:53,411 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-21 03:57:53,521 | fed_df.py:365 | Warm start at round 6
[2m[36m(launch_and_fit pid=560312)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 03:57:53,653 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=560269)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=560326)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=560281)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=560273)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=560312)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=560352)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=560282)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=560353)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=560269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=560352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=560326)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=560353)[0m malloc_consolidate(): invalid chunk size
E0821 03:57:57.706337845  741390 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-21 03:59:26,756 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 03:59:26,757 | fed_df.py:547 | Average fusion training loss : 0.005025400727288797, val accuracy : 0.55146, best val accuracy : 0.6526
INFO flwr 2023-08-21 03:59:26,758 | common.py:35 | Avg. local train loss : 4.255734011530876, train acc : 0.8689694444444443
INFO flwr 2023-08-21 03:59:29,419 | server.py:116 | fit progress: (6, 1.914615936279297, {'server_test_acc': 0.6437}, 1087.9301556210266)
INFO flwr 2023-08-21 03:59:29,419 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-21 03:59:35,379 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=916914)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:00:54,838 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-21 04:00:54,948 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-21 04:00:55,036 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=916775)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=916776)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=916846)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=916916)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=916917)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=916914)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=916918)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=916915)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=916916)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=916915)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=916846)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=916917)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=916776)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=916918)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=916775)[0m malloc_consolidate(): invalid chunk size
E0821 04:00:57.738850536 1075751 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
E0821 04:02:18.128509775 1223664 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-21 04:02:28,302 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:02:28,303 | fed_df.py:547 | Average fusion training loss : 0.0048691172386752446, val accuracy : 0.58726, best val accuracy : 0.6696
INFO flwr 2023-08-21 04:02:28,304 | common.py:35 | Avg. local train loss : 3.991898827254772, train acc : 0.8947055555555555
INFO flwr 2023-08-21 04:02:30,940 | server.py:116 | fit progress: (7, 1.9392906311035156, {'server_test_acc': 0.6526}, 1269.4515191540122)
INFO flwr 2023-08-21 04:02:30,940 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-21 04:02:36,928 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1252062)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1252057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1252060)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1252063)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-21 04:03:56,434 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-21 04:03:56,545 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-21 04:03:56,633 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1252060)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1252057)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1252064)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1252063)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1252062)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1252074)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1252073)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1252142)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1252073)[0m malloc_consolidate(): invalid chunk size
E0821 04:03:57.223030330 1225674 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1252142)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1252074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1252064)[0m malloc_consolidate(): invalid chunk size
E0821 04:05:29.353555709 1406546 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-21 04:05:30,199 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:05:30,200 | fed_df.py:547 | Average fusion training loss : 0.005166851432761178, val accuracy : 0.62234, best val accuracy : 0.6906
INFO flwr 2023-08-21 04:05:30,201 | common.py:35 | Avg. local train loss : 3.93850990254432, train acc : 0.9009333333333335
INFO flwr 2023-08-21 04:05:32,870 | server.py:116 | fit progress: (8, 1.9035989807128906, {'server_test_acc': 0.6824}, 1451.3811271779705)
INFO flwr 2023-08-21 04:05:32,870 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-21 04:05:38,824 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1587964)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 04:06:58,426 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-21 04:06:58,537 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-21 04:06:58,624 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1587893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1587891)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1587894)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1587890)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1587893)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1587930)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1587895)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1587964)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1587892)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1587891)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1587895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1587930)[0m malloc_consolidate(): invalid chunk size
E0821 04:06:59.750871846 1741215 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0821 04:06:59.751175792 1741215 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1587890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1587892)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1587894)[0m malloc_consolidate(): invalid chunk size
E0821 04:07:49.203172257 1741389 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-21 04:08:32,340 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:08:32,341 | fed_df.py:547 | Average fusion training loss : 0.0027691491456935183, val accuracy : 0.66474, best val accuracy : 0.7202
INFO flwr 2023-08-21 04:08:32,342 | common.py:35 | Avg. local train loss : 4.056350007839501, train acc : 0.8944652777777778
INFO flwr 2023-08-21 04:08:35,031 | server.py:116 | fit progress: (9, 1.845620526123047, {'server_test_acc': 0.7113}, 1633.5424557880033)
INFO flwr 2023-08-21 04:08:35,031 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-21 04:08:41,055 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1923080)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1923010)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1923081)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1923006)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:10:01,363 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1923013)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:10:01,475 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-21 04:10:01,564 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1923006)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1923008)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1923013)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1923011)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1923081)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1923082)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1923010)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1923080)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1923011)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1923082)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1923008)[0m malloc_consolidate(): invalid chunk size
E0821 04:10:02.838867893 1842056 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0821 04:10:24.276954532 2076458 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:11:36,151 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:11:36,151 | fed_df.py:547 | Average fusion training loss : 0.0021230263338657095, val accuracy : 0.6711800000000001, best val accuracy : 0.7046
INFO flwr 2023-08-21 04:11:36,152 | common.py:35 | Avg. local train loss : 3.7975364772602913, train acc : 0.9163486111111112
INFO flwr 2023-08-21 04:11:38,781 | server.py:116 | fit progress: (10, 1.8567190734863281, {'server_test_acc': 0.6975}, 1817.2920392970555)
INFO flwr 2023-08-21 04:11:38,781 | server.py:163 | evaluate_round 10: no clients selected, cancel
E0821 04:11:40.155401759 2259829 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
DEBUG flwr 2023-08-21 04:11:44,804 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 04:13:03,997 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2266637)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:13:04,109 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-21 04:13:04,197 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2266638)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2266571)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2266635)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2266637)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2266636)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2266564)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2266565)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2266634)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2266564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2266634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2266565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2266638)[0m double free or corruption (fasttop)
E0821 04:13:05.689688389 2261677 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2266571)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2266636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2266635)[0m double free or corruption (fasttop)
E0821 04:13:20.072986342 2469144 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:14:39,197 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:14:39,198 | fed_df.py:547 | Average fusion training loss : 0.0021245942179812117, val accuracy : 0.6563599999999999, best val accuracy : 0.7036
INFO flwr 2023-08-21 04:14:39,199 | common.py:35 | Avg. local train loss : 3.7340252013877033, train acc : 0.9241527777777777
INFO flwr 2023-08-21 04:14:41,842 | server.py:116 | fit progress: (11, 1.8430271606445312, {'server_test_acc': 0.7012}, 2000.3540309469681)
INFO flwr 2023-08-21 04:14:41,843 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-21 04:14:47,808 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2623330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2623326)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:16:07,422 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-21 04:16:07,533 | fed_df.py:365 | Warm start at round 12
[2m[36m(launch_and_fit pid=2623331)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 04:16:07,620 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2623326)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2623330)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2623328)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2623324)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2623327)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2623329)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2623331)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2623332)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2623329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2623324)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2623327)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2623328)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2623332)[0m malloc_consolidate(): invalid chunk size
E0821 04:16:09.952613859 2470267 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:16:30.475803739 2821054 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:17:10.877618988 2897204 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:17:41,548 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:17:41,549 | fed_df.py:547 | Average fusion training loss : 0.0012685649839113467, val accuracy : 0.7132, best val accuracy : 0.7372
INFO flwr 2023-08-21 04:17:41,550 | common.py:35 | Avg. local train loss : 3.6620750155299904, train acc : 0.9290763888888889
INFO flwr 2023-08-21 04:17:44,218 | server.py:116 | fit progress: (12, 1.8311696258544923, {'server_test_acc': 0.7325}, 2182.7292355040554)
INFO flwr 2023-08-21 04:17:44,218 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-21 04:17:50,202 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2959614)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2959641)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:19:09,491 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2959640)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:19:09,604 | fed_df.py:365 | Warm start at round 13
[2m[36m(launch_and_fit pid=2959644)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:19:09,693 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2959643)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2959644)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2959641)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2959614)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2959639)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2959640)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2959638)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2959642)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2959638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2959639)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2959643)[0m malloc_consolidate(): invalid chunk size
E0821 04:19:10.701108778 2898518 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2959642)[0m double free or corruption (fasttop)
E0821 04:19:46.504224887 3108946 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:20:11.358130622 3231648 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:20:43,891 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:20:43,892 | fed_df.py:547 | Average fusion training loss : 0.001394316831312608, val accuracy : 0.72028, best val accuracy : 0.742
INFO flwr 2023-08-21 04:20:43,893 | common.py:35 | Avg. local train loss : 3.7311334270983934, train acc : 0.9236194444444444
INFO flwr 2023-08-21 04:20:46,536 | server.py:116 | fit progress: (13, 1.8449261474609375, {'server_test_acc': 0.7306}, 2365.0478403940797)
INFO flwr 2023-08-21 04:20:46,537 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-21 04:20:52,540 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3295813)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:22:11,645 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-21 04:22:11,756 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-21 04:22:11,844 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3295708)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3295710)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3295789)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3295811)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3295812)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3295808)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3295813)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3295788)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3295811)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3295812)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3295710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3295788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3295808)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3295789)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3295708)[0m double free or corruption (fasttop)
E0821 04:22:16.000375635 3232401 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:23:45,878 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:23:45,879 | fed_df.py:547 | Average fusion training loss : 0.0013809561927919276, val accuracy : 0.69166, best val accuracy : 0.7234
INFO flwr 2023-08-21 04:23:45,880 | common.py:35 | Avg. local train loss : 3.631468018703163, train acc : 0.930376388888889
INFO flwr 2023-08-21 04:23:48,549 | server.py:116 | fit progress: (14, 1.903128497314453, {'server_test_acc': 0.724}, 2547.0606205000076)
INFO flwr 2023-08-21 04:23:48,549 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-21 04:23:54,527 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3630789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3630787)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:25:13,429 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-21 04:25:13,540 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-21 04:25:13,629 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3630789)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3630791)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3630787)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3630794)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3630788)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3630790)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3630792)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3630793)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3630791)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3630788)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3630793)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3630792)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3630794)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3630790)[0m malloc_consolidate(): invalid chunk size
E0821 04:25:18.296893232 3781817 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:26:08.012132647 3784464 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:26:47,508 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:26:47,509 | fed_df.py:547 | Average fusion training loss : 0.0011750547356205062, val accuracy : 0.7349199999999999, best val accuracy : 0.7554
INFO flwr 2023-08-21 04:26:47,510 | common.py:35 | Avg. local train loss : 3.631839022040367, train acc : 0.9297916666666667
INFO flwr 2023-08-21 04:26:50,195 | server.py:116 | fit progress: (15, 1.8107337219238282, {'server_test_acc': 0.7474}, 2728.706383730052)
INFO flwr 2023-08-21 04:26:50,195 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-21 04:26:56,221 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3967337)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 04:28:15,942 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3967326)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 04:28:16,054 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-21 04:28:16,141 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3967337)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3967329)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3967327)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3967338)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3967339)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3967326)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3967352)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3967328)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3967339)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3967328)[0m malloc_consolidate(): invalid chunk size
E0821 04:28:16.923598837 3890014 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3967352)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3967338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3967327)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3967329)[0m double free or corruption (fasttop)
E0821 04:28:18.349537370 4138327 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:29:08.921562735 4139119 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:29:51,218 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:29:51,218 | fed_df.py:547 | Average fusion training loss : 0.0012772754801553673, val accuracy : 0.68766, best val accuracy : 0.7122
INFO flwr 2023-08-21 04:29:51,219 | common.py:35 | Avg. local train loss : 3.485579582117498, train acc : 0.9414152777777778
INFO flwr 2023-08-21 04:29:53,933 | server.py:116 | fit progress: (16, 1.8418948852539063, {'server_test_acc': 0.7119}, 2912.444246876985)
INFO flwr 2023-08-21 04:29:53,933 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-21 04:29:59,890 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=131010)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=130967)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:31:19,311 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-21 04:31:19,422 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-21 04:31:19,509 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=130966)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=130965)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=131037)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=130967)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=131010)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=131039)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=131038)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=130968)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=130965)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=130966)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=131037)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131038)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=131039)[0m malloc_consolidate(): invalid chunk size
E0821 04:31:20.555995879   55623 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=130968)[0m malloc_consolidate(): invalid chunk size
E0821 04:32:09.870140365  272530 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:32:52,547 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:32:52,548 | fed_df.py:547 | Average fusion training loss : 0.0009667829788522795, val accuracy : 0.7032800000000001, best val accuracy : 0.7228
INFO flwr 2023-08-21 04:32:52,549 | common.py:35 | Avg. local train loss : 3.527916949801147, train acc : 0.9383986111111111
INFO flwr 2023-08-21 04:32:55,198 | server.py:116 | fit progress: (17, 1.901251171875, {'server_test_acc': 0.7223}, 3093.709321414004)
INFO flwr 2023-08-21 04:32:55,198 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-21 04:33:01,155 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=429467)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=429461)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=429462)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 04:34:20,442 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-21 04:34:20,553 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-21 04:34:20,641 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=429461)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=429462)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=429468)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=429467)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=429465)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=429463)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=429466)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=429464)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=429468)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=429465)[0m double free or corruption (fasttop)
E0821 04:34:21.509923647  377661 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=429466)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=429464)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=429463)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 04:35:55,378 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:35:55,379 | fed_df.py:547 | Average fusion training loss : 0.0009471111574093811, val accuracy : 0.73448, best val accuracy : 0.7532
INFO flwr 2023-08-21 04:35:55,380 | common.py:35 | Avg. local train loss : 3.5801675559952852, train acc : 0.9368458333333333
INFO flwr 2023-08-21 04:35:58,102 | server.py:116 | fit progress: (18, 1.8836172119140624, {'server_test_acc': 0.7389}, 3276.61334710801)
INFO flwr 2023-08-21 04:35:58,102 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-21 04:36:04,297 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=752424)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 04:37:25,734 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=752422)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=752425)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:37:25,846 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-21 04:37:25,961 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=752421)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=752427)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=752287)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=752422)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=752424)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=752426)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=752425)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=752423)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=752426)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=752421)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=752287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=752427)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=752423)[0m malloc_consolidate(): invalid chunk size
E0821 04:37:31.345918327  577900 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:37:40.458230528  920841 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:38:59,651 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:38:59,651 | fed_df.py:547 | Average fusion training loss : 0.000873258582665585, val accuracy : 0.7373999999999999, best val accuracy : 0.7532
INFO flwr 2023-08-21 04:38:59,653 | common.py:35 | Avg. local train loss : 3.4646267373114825, train acc : 0.9456166666666667
INFO flwr 2023-08-21 04:39:02,421 | server.py:116 | fit progress: (19, 1.8631715026855469, {'server_test_acc': 0.7448}, 3460.9328824330587)
INFO flwr 2023-08-21 04:39:02,422 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-21 04:39:08,541 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1085882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1085885)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 04:40:28,180 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-21 04:40:28,292 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-21 04:40:28,381 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1085882)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1085883)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1085733)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1085881)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1085888)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1085884)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1085885)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1085887)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1085883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1085884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1085881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1085733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1085888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1085887)[0m malloc_consolidate(): invalid chunk size
E0821 04:40:30.933183755 1249847 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:42:02,203 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:42:02,203 | fed_df.py:547 | Average fusion training loss : 0.0008949993964051828, val accuracy : 0.7375200000000001, best val accuracy : 0.7562
INFO flwr 2023-08-21 04:42:02,205 | common.py:35 | Avg. local train loss : 3.4888528143987054, train acc : 0.943626388888889
INFO flwr 2023-08-21 04:42:04,908 | server.py:116 | fit progress: (20, 1.9172225830078125, {'server_test_acc': 0.7556}, 3643.4199437299976)
INFO flwr 2023-08-21 04:42:04,909 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-21 04:42:10,951 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1417940)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:43:31,121 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1417977)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 04:43:31,234 | fed_df.py:365 | Warm start at round 21
[2m[36m(launch_and_fit pid=1417939)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1417976)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:43:31,323 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1417940)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1417939)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1417941)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1417938)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1417977)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1418259)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1417976)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1418265)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1417941)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1418259)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1417938)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1418265)[0m double free or corruption (fasttop)
E0821 04:43:33.615520836 1250250 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:45:04,797 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:45:04,797 | fed_df.py:547 | Average fusion training loss : 0.0008079656376503408, val accuracy : 0.74506, best val accuracy : 0.7598
INFO flwr 2023-08-21 04:45:04,798 | common.py:35 | Avg. local train loss : 3.5125483240932223, train acc : 0.9410624999999999
INFO flwr 2023-08-21 04:45:07,542 | server.py:116 | fit progress: (21, 1.8928547668457032, {'server_test_acc': 0.7584}, 3826.0534703190206)
INFO flwr 2023-08-21 04:45:07,542 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-21 04:45:13,841 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1780386)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1780121)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 04:46:34,122 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-21 04:46:34,234 | fed_df.py:365 | Warm start at round 22
[2m[36m(launch_and_fit pid=1780389)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:46:34,324 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1780386)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1780389)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1780388)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1780136)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1780143)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1780120)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1780121)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1780387)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1780387)[0m malloc_consolidate(): invalid chunk size
E0821 04:46:34.933755320 1944563 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1780120)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1780136)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1780388)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1780143)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:48:08,435 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:48:08,435 | fed_df.py:547 | Average fusion training loss : 0.001199433374335058, val accuracy : 0.6987399999999999, best val accuracy : 0.729
INFO flwr 2023-08-21 04:48:08,436 | common.py:35 | Avg. local train loss : 3.4671599607914687, train acc : 0.9432055555555556
INFO flwr 2023-08-21 04:48:11,171 | server.py:116 | fit progress: (22, 1.954885400390625, {'server_test_acc': 0.7195}, 4009.6827303890605)
INFO flwr 2023-08-21 04:48:11,171 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-21 04:48:17,230 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2114376)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:49:36,929 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-21 04:49:37,039 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-21 04:49:37,126 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2114144)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2114122)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2114145)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2114139)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2114285)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2114374)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2114376)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2114391)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2114145)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2114122)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2114139)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2114285)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2114391)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2114374)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2114144)[0m double free or corruption (fasttop)
E0821 04:49:43.687129862 1945175 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 04:50:28.453255767 2289785 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:51:10,863 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:51:10,864 | fed_df.py:547 | Average fusion training loss : 0.0009236059148679487, val accuracy : 0.7498400000000001, best val accuracy : 0.767
INFO flwr 2023-08-21 04:51:10,865 | common.py:35 | Avg. local train loss : 3.487170957401395, train acc : 0.943951388888889
INFO flwr 2023-08-21 04:51:13,588 | server.py:116 | fit progress: (23, 1.9214659240722656, {'server_test_acc': 0.7595}, 4192.099077720079)
INFO flwr 2023-08-21 04:51:13,588 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-21 04:51:19,613 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2447011)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:52:39,217 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2447017)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:52:39,329 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-21 04:52:39,417 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2447006)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2447018)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2447009)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2447011)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2447016)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2447007)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2447019)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2447017)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2447016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2447006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2447018)[0m malloc_consolidate(): invalid chunk size
E0821 04:52:40.462370078 2614543 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2447009)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2447019)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2447007)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 04:54:12,961 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:54:12,961 | fed_df.py:547 | Average fusion training loss : 0.0009762873115250841, val accuracy : 0.73706, best val accuracy : 0.7628
INFO flwr 2023-08-21 04:54:12,963 | common.py:35 | Avg. local train loss : 3.5437597902491698, train acc : 0.9409333333333333
INFO flwr 2023-08-21 04:54:15,748 | server.py:116 | fit progress: (24, 1.901662432861328, {'server_test_acc': 0.761}, 4374.259158213041)
INFO flwr 2023-08-21 04:54:15,748 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-21 04:54:21,916 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2779883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2779874)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2779881)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:55:41,607 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-21 04:55:41,719 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-21 04:55:41,806 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2779656)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2779881)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2779658)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2779882)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2779874)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2779877)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2779883)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2779880)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2779656)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2779658)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2779877)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2779882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2779880)[0m malloc_consolidate(): invalid chunk size
E0821 04:55:59.440875521 2952104 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 04:57:14,327 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 04:57:14,328 | fed_df.py:547 | Average fusion training loss : 0.0012039214514079505, val accuracy : 0.73288, best val accuracy : 0.7542
INFO flwr 2023-08-21 04:57:14,329 | common.py:35 | Avg. local train loss : 3.391398120857775, train acc : 0.948911111111111
INFO flwr 2023-08-21 04:57:17,161 | server.py:116 | fit progress: (25, 1.9333661193847655, {'server_test_acc': 0.7511}, 4555.672038582037)
INFO flwr 2023-08-21 04:57:17,161 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-21 04:57:23,203 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3113943)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 04:58:43,584 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3114086)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 04:58:43,697 | fed_df.py:365 | Warm start at round 26
[2m[36m(launch_and_fit pid=3114087)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 04:58:43,786 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3113926)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3114087)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3113928)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3113943)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3113925)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3114086)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3113919)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3113923)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3113928)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3113925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3113919)[0m malloc_consolidate(): invalid chunk size
E0821 04:58:44.623917763 2977621 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3113923)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3113926)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 05:00:16,982 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 05:00:16,983 | fed_df.py:547 | Average fusion training loss : 0.0011260119685903192, val accuracy : 0.7218399999999999, best val accuracy : 0.7428
INFO flwr 2023-08-21 05:00:16,984 | common.py:35 | Avg. local train loss : 3.396981955878436, train acc : 0.9499430555555555
INFO flwr 2023-08-21 05:00:19,909 | server.py:116 | fit progress: (26, 1.9700453369140625, {'server_test_acc': 0.7439}, 4738.420120539027)
INFO flwr 2023-08-21 05:00:19,909 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-21 05:00:25,970 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3474662)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 05:01:46,976 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3474654)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 05:01:47,089 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-21 05:01:47,175 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3474656)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3474664)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3474657)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3474654)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3474660)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3474663)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3474666)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3474662)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3474663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3474666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3474660)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3474657)[0m malloc_consolidate(): invalid chunk size
E0821 05:01:48.367717072 3290327 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3474656)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3474664)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 05:03:19,547 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 05:03:19,548 | fed_df.py:547 | Average fusion training loss : 0.0028522235192358493, val accuracy : 0.61322, best val accuracy : 0.7118
INFO flwr 2023-08-21 05:03:19,549 | common.py:35 | Avg. local train loss : 3.433436868153512, train acc : 0.9467347222222222
INFO flwr 2023-08-21 05:03:22,309 | server.py:116 | fit progress: (27, 1.9793924255371094, {'server_test_acc': 0.7059}, 4920.820271383971)
INFO flwr 2023-08-21 05:03:22,309 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-21 05:03:28,455 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3800564)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 05:04:48,009 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-21 05:04:48,121 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-21 05:04:48,209 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3800558)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3800426)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3800559)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3800590)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3800565)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3800569)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3800564)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3800568)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3800565)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3800559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3800568)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3800569)[0m malloc_consolidate(): invalid chunk size
E0821 05:04:49.377627454 3646545 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3800426)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3800590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3800558)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 05:06:21,137 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 05:06:21,138 | fed_df.py:547 | Average fusion training loss : 0.0018303141798824071, val accuracy : 0.7458400000000001, best val accuracy : 0.7626
INFO flwr 2023-08-21 05:06:21,139 | common.py:35 | Avg. local train loss : 3.31784076038748, train acc : 0.9557694444444446
INFO flwr 2023-08-21 05:06:23,977 | server.py:116 | fit progress: (28, 1.9654696960449218, {'server_test_acc': 0.7593}, 5102.488560825004)
INFO flwr 2023-08-21 05:06:23,977 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-21 05:06:29,974 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4131744)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4131745)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4131737)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 05:07:50,667 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4131742)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 05:07:50,785 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-21 05:07:50,872 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4131737)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4131745)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4131742)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4131744)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4132010)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4131741)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4132009)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4131971)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4132010)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4131741)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4132009)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4131971)[0m malloc_consolidate(): invalid chunk size
E0821 05:07:53.342880909  121574 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 05:08:22.550077513  170214 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 05:09:23,059 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 05:09:23,060 | fed_df.py:547 | Average fusion training loss : 0.0015961270591942594, val accuracy : 0.75034, best val accuracy : 0.7784
INFO flwr 2023-08-21 05:09:23,061 | common.py:35 | Avg. local train loss : 3.364308640919626, train acc : 0.9522666666666667
INFO flwr 2023-08-21 05:09:25,843 | server.py:116 | fit progress: (29, 1.9063223510742187, {'server_test_acc': 0.7718}, 5284.354295916972)
INFO flwr 2023-08-21 05:09:25,843 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-21 05:09:31,927 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=270889)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=270894)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 05:10:52,573 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-21 05:10:52,687 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-21 05:10:52,792 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=270889)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=270893)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=270894)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=270752)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=270891)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=270751)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=270890)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=270892)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=270752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=270893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=270890)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=270891)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=270892)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=270751)[0m malloc_consolidate(): invalid chunk size
E0821 05:10:55.003867413  171421 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 05:11:23.200768648  457668 chttp2_transport.cc:1079]             ipv4:145.136.62.46:59369: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 05:12:25,545 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 05:12:25,546 | fed_df.py:547 | Average fusion training loss : 0.0012499329899437726, val accuracy : 0.7331, best val accuracy : 0.751
INFO flwr 2023-08-21 05:12:25,547 | common.py:35 | Avg. local train loss : 3.2552700974047184, train acc : 0.9587263888888888
INFO flwr 2023-08-21 05:12:28,242 | server.py:116 | fit progress: (30, 2.007501385498047, {'server_test_acc': 0.7526}, 5466.753687607008)
INFO flwr 2023-08-21 05:12:28,242 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-21 05:12:28,242 | server.py:144 | FL finished in 5466.754092682037
INFO flwr 2023-08-21 05:12:28,243 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-21 05:12:28,244 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-21 05:12:28,244 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.5781340393066405), (2, 1.4870212677001953), (3, 1.5198754180908203), (4, 1.7195905242919922), (5, 1.8885771423339843), (6, 1.914615936279297), (7, 1.9392906311035156), (8, 1.9035989807128906), (9, 1.845620526123047), (10, 1.8567190734863281), (11, 1.8430271606445312), (12, 1.8311696258544923), (13, 1.8449261474609375), (14, 1.903128497314453), (15, 1.8107337219238282), (16, 1.8418948852539063), (17, 1.901251171875), (18, 1.8836172119140624), (19, 1.8631715026855469), (20, 1.9172225830078125), (21, 1.8928547668457032), (22, 1.954885400390625), (23, 1.9214659240722656), (24, 1.901662432861328), (25, 1.9333661193847655), (26, 1.9700453369140625), (27, 1.9793924255371094), (28, 1.9654696960449218), (29, 1.9063223510742187), (30, 2.007501385498047)]
INFO flwr 2023-08-21 05:12:28,244 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4459), (2, 0.5253), (3, 0.6101), (4, 0.5869), (5, 0.6377), (6, 0.6437), (7, 0.6526), (8, 0.6824), (9, 0.7113), (10, 0.6975), (11, 0.7012), (12, 0.7325), (13, 0.7306), (14, 0.724), (15, 0.7474), (16, 0.7119), (17, 0.7223), (18, 0.7389), (19, 0.7448), (20, 0.7556), (21, 0.7584), (22, 0.7195), (23, 0.7595), (24, 0.761), (25, 0.7511), (26, 0.7439), (27, 0.7059), (28, 0.7593), (29, 0.7718), (30, 0.7526)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn46: task 0: Aborted
srun: Terminating StepId=3431066.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3431066
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 03:12:17
CPU Efficiency: 11.30% of 1-04:22:12 core-walltime
Job Wall-clock time: 01:34:34
Memory Utilized: 54.50 GB
Memory Efficiency: 45.42% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
