-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:5000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:True
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=5000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3430373/1692565080_496727256', seed=42, img_per_thread=277)
will save 5000 patches in /scratch-local/sunnys.3430373/1692565080_496727256/single_img_crops/crops
5000 took 0.07min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 22:58:20,330 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 22:58:20,330 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3430373/1692565080_496727256/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3430373/1692565080_496727256/cifar-10-python.tar.gz to /scratch-local/sunnys.3430373/1692565080_496727256
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
INFO flwr 2023-08-20 22:58:34,474 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 22:58:37,127	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-20 22:58:38,154 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.28': 1.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0, 'object_store_memory': 61847529062.0, 'CPU': 18.0, 'memory': 103079215104.0}
INFO flwr 2023-08-20 22:58:38,155 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 22:58:38,155 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 22:58:38,155 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 22:58:49,247 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-20 22:58:49,247 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 22:58:52,775 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1710588)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:00:12,356 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1710590)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:00:12,459 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-20 23:00:12,553 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1710591)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1710587)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1710589)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1710590)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1710593)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1710592)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1710594)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1710588)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1710591)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1710589)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1710592)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1710593)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1710587)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1710594)[0m malloc_consolidate(): invalid chunk size
E0820 23:00:14.207888373 1801828 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-20 23:01:36,181 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:01:36,182 | fed_df.py:547 | Average fusion training loss : 0.013760943928267808, val accuracy : 0.38496, best val accuracy : 0.4384
INFO flwr 2023-08-20 23:01:36,183 | common.py:35 | Avg. local train loss : 6.758596674539149, train acc : 0.6000430555555556
INFO flwr 2023-08-20 23:01:38,851 | server.py:116 | fit progress: (1, 1.6077239166259765, {'server_test_acc': 0.4386}, 169.60413871938363)
INFO flwr 2023-08-20 23:01:38,852 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 23:01:42,386 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1908675)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1908690)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1908661)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:03:03,339 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1908687)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1908691)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 23:03:03,443 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-20 23:03:03,539 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1908657)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1908675)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1908661)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1908687)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1908690)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1908691)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1908689)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1908688)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1908657)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1908689)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1908688)[0m double free or corruption (fasttop)
E0820 23:03:05.362192677 2092575 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-20 23:04:31,491 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:04:31,491 | fed_df.py:547 | Average fusion training loss : 0.008628121156943962, val accuracy : 0.52136, best val accuracy : 0.5456
INFO flwr 2023-08-20 23:04:31,492 | common.py:35 | Avg. local train loss : 5.240142437070608, train acc : 0.7507833333333334
INFO flwr 2023-08-20 23:04:34,112 | server.py:116 | fit progress: (2, 1.4840391204833985, {'server_test_acc': 0.547}, 344.8647240321152)
INFO flwr 2023-08-20 23:04:34,112 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 23:04:37,663 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2245257)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2245258)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245413)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2245413)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245415)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2245411)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2245414)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:05:59,103 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-20 23:05:59,205 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-20 23:05:59,299 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2245257)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2245258)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2245412)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2245415)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2245413)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2245411)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2245414)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2245416)[0m Fitting Client 4
E0820 23:06:00.315654397 2093753 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=2245416)[0m malloc_consolidate(): invalid chunk size
E0820 23:06:12.924915084 2451010 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-20 23:07:27,806 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:07:27,806 | fed_df.py:547 | Average fusion training loss : 0.011623187799705193, val accuracy : 0.5862200000000001, best val accuracy : 0.6216
INFO flwr 2023-08-20 23:07:27,807 | common.py:35 | Avg. local train loss : 4.754221896454692, train acc : 0.8043736111111113
INFO flwr 2023-08-20 23:07:30,412 | server.py:116 | fit progress: (3, 1.5501010009765626, {'server_test_acc': 0.614}, 521.1644786279649)
INFO flwr 2023-08-20 23:07:30,412 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 23:07:33,942 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2582556)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:08:53,602 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-20 23:08:53,706 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-20 23:08:53,801 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2582556)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2582593)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2582911)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2582813)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2582912)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2582642)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2582913)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2582910)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2582911)[0m double free or corruption (fasttop)
E0820 23:08:54.156929005 2451614 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2582910)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2582593)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2582913)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2582642)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2582813)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2582912)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:10:21,373 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:10:21,373 | fed_df.py:547 | Average fusion training loss : 0.008097796668065711, val accuracy : 0.6227199999999999, best val accuracy : 0.646
INFO flwr 2023-08-20 23:10:21,374 | common.py:35 | Avg. local train loss : 4.288576191104949, train acc : 0.856901388888889
INFO flwr 2023-08-20 23:10:23,948 | server.py:116 | fit progress: (4, 1.6526113983154296, {'server_test_acc': 0.6359}, 694.7009847853333)
INFO flwr 2023-08-20 23:10:23,949 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 23:10:27,504 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2916008)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2916007)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2915738)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:11:48,770 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2915739)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 23:11:48,874 | fed_df.py:365 | Warm start at round 5
[2m[36m(launch_and_fit pid=2916009)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:11:48,969 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2916007)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2915944)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2915739)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2916008)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2915738)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2916005)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2916009)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2916006)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2916005)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2915944)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2916006)[0m malloc_consolidate(): invalid chunk size
E0820 23:11:53.761949593 2765276 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-20 23:13:17,301 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:13:17,302 | fed_df.py:547 | Average fusion training loss : 0.0069321389810647815, val accuracy : 0.65488, best val accuracy : 0.6828
INFO flwr 2023-08-20 23:13:17,303 | common.py:35 | Avg. local train loss : 4.397696705907583, train acc : 0.856525
INFO flwr 2023-08-20 23:13:20,219 | server.py:116 | fit progress: (5, 1.7149032409667968, {'server_test_acc': 0.6748}, 870.9716290310025)
INFO flwr 2023-08-20 23:13:20,219 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 23:13:23,663 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3282239)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3282241)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3282248)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3282238)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:14:44,044 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-20 23:14:44,147 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-20 23:14:44,242 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3282239)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3282238)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3282241)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3282247)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3282248)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3282246)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3282249)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3282245)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3282245)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3282246)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3282249)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3282247)[0m double free or corruption (fasttop)
E0820 23:14:46.058174475 3120548 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-20 23:16:12,001 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:16:12,001 | fed_df.py:547 | Average fusion training loss : 0.005844995070248842, val accuracy : 0.66644, best val accuracy : 0.6994
INFO flwr 2023-08-20 23:16:12,002 | common.py:35 | Avg. local train loss : 4.214029383473098, train acc : 0.8777138888888889
INFO flwr 2023-08-20 23:16:14,621 | server.py:116 | fit progress: (6, 1.8125321746826173, {'server_test_acc': 0.6909}, 1045.3739952300675)
INFO flwr 2023-08-20 23:16:14,622 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 23:16:18,095 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3617965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3617963)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:17:38,350 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-20 23:17:38,454 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-20 23:17:38,548 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3617962)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3617960)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3617961)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3617963)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3617967)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3617966)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3617965)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3617959)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3617966)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3617962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3617959)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3617967)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3617960)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3617961)[0m malloc_consolidate(): invalid chunk size
E0820 23:17:46.225167685 3813168 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-20 23:19:06,469 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:19:06,470 | fed_df.py:547 | Average fusion training loss : 0.005983948215376586, val accuracy : 0.68408, best val accuracy : 0.704
INFO flwr 2023-08-20 23:19:06,471 | common.py:35 | Avg. local train loss : 3.932283169962466, train acc : 0.903911111111111
INFO flwr 2023-08-20 23:19:09,110 | server.py:116 | fit progress: (7, 1.8069347534179687, {'server_test_acc': 0.6936}, 1219.862801096402)
INFO flwr 2023-08-20 23:19:09,110 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 23:19:12,660 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3951896)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:20:32,428 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-20 23:20:32,531 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-20 23:20:32,628 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3951896)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3952023)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3951885)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3952162)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3952164)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3952022)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3952143)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3952165)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3952022)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3952164)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3951885)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3952165)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3952162)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3952023)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3952143)[0m malloc_consolidate(): invalid chunk size
E0820 23:20:35.050673368 3816489 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-20 23:22:00,466 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:22:00,466 | fed_df.py:547 | Average fusion training loss : 0.005294734176946804, val accuracy : 0.692, best val accuracy : 0.7214
INFO flwr 2023-08-20 23:22:00,467 | common.py:35 | Avg. local train loss : 3.8960891092196106, train acc : 0.90805
INFO flwr 2023-08-20 23:22:03,156 | server.py:116 | fit progress: (8, 1.8190706115722657, {'server_test_acc': 0.7047}, 1393.908475138247)
INFO flwr 2023-08-20 23:22:03,156 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 23:22:06,615 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=93131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=93170)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:23:27,119 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-20 23:23:27,223 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-20 23:23:27,318 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=93131)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=93172)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=93174)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=93169)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=93173)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=93167)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=93170)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=93168)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=93168)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=93169)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=93173)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=93174)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=93172)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=93167)[0m malloc_consolidate(): invalid chunk size
E0820 23:23:29.126678484 4142876 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-20 23:24:55,619 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:24:55,619 | fed_df.py:547 | Average fusion training loss : 0.005443811282981187, val accuracy : 0.6892999999999999, best val accuracy : 0.7182
INFO flwr 2023-08-20 23:24:55,620 | common.py:35 | Avg. local train loss : 3.991318304650486, train acc : 0.9044986111111112
INFO flwr 2023-08-20 23:24:58,136 | server.py:116 | fit progress: (9, 1.8803034484863281, {'server_test_acc': 0.7044}, 1568.8890728000551)
INFO flwr 2023-08-20 23:24:58,137 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 23:25:01,652 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=428435)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:26:22,181 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-20 23:26:22,284 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-20 23:26:22,380 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=428430)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=428433)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=428429)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=428434)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=428435)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=428428)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=428432)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=428431)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=428433)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=428431)[0m double free or corruption (fasttop)
E0820 23:26:23.009477793  616893 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=428432)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=428429)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=428430)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=428428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=428434)[0m malloc_consolidate(): invalid chunk size
E0820 23:26:24.771183245  619933 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-20 23:27:51,223 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:27:51,224 | fed_df.py:547 | Average fusion training loss : 0.005517705367528833, val accuracy : 0.713, best val accuracy : 0.7308
INFO flwr 2023-08-20 23:27:51,225 | common.py:35 | Avg. local train loss : 3.806268205866218, train acc : 0.9184361111111111
INFO flwr 2023-08-20 23:27:53,749 | server.py:116 | fit progress: (10, 1.8253358520507812, {'server_test_acc': 0.718}, 1744.5019263392314)
INFO flwr 2023-08-20 23:27:53,749 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 23:27:57,145 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=795873)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=795870)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:29:19,415 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-20 23:29:19,519 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-20 23:29:19,615 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=795872)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=795870)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=795871)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=795869)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=795868)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=795875)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=795873)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=795874)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=795871)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=795874)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=795872)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=795875)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=795869)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=795868)[0m double free or corruption (fasttop)
E0820 23:29:21.560361156  620799 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-20 23:30:48,124 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:30:48,124 | fed_df.py:547 | Average fusion training loss : 0.005587149088387378, val accuracy : 0.70388, best val accuracy : 0.7286
INFO flwr 2023-08-20 23:30:48,125 | common.py:35 | Avg. local train loss : 3.684948389232159, train acc : 0.9307972222222223
INFO flwr 2023-08-20 23:30:50,654 | server.py:116 | fit progress: (11, 1.7947281433105469, {'server_test_acc': 0.7183}, 1921.4066514912993)
INFO flwr 2023-08-20 23:30:50,654 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 23:30:54,237 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1134465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1134484)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:32:15,395 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 23:32:15,499 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-20 23:32:15,595 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1134433)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1134446)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1134443)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1134445)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1134447)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1134468)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1134465)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1134484)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1134433)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1134468)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1134445)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1134447)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1134443)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1134446)[0m malloc_consolidate(): invalid chunk size
E0820 23:32:18.014824592  985470 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
E0820 23:33:22.585387741 1431979 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-20 23:33:43,857 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:33:43,858 | fed_df.py:547 | Average fusion training loss : 0.0038684025492984804, val accuracy : 0.7268600000000001, best val accuracy : 0.7416
INFO flwr 2023-08-20 23:33:43,859 | common.py:35 | Avg. local train loss : 3.6504154631868, train acc : 0.9323402777777777
INFO flwr 2023-08-20 23:33:46,373 | server.py:116 | fit progress: (12, 1.7757756713867188, {'server_test_acc': 0.7321}, 2097.126118613407)
INFO flwr 2023-08-20 23:33:46,374 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 23:33:49,795 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1472405)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1472400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1472403)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1472407)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:35:11,805 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-20 23:35:11,909 | fed_df.py:365 | Warm start at round 13
[2m[36m(launch_and_fit pid=1472401)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:35:12,005 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1472400)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1472405)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1472401)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1472407)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1472404)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1472403)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1472406)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1472402)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1472402)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1472404)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1472406)[0m malloc_consolidate(): invalid chunk size
E0820 23:35:13.849362399 1656778 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-20 23:36:40,313 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:36:40,313 | fed_df.py:547 | Average fusion training loss : 0.0036659468075959014, val accuracy : 0.7378399999999999, best val accuracy : 0.7502
INFO flwr 2023-08-20 23:36:40,314 | common.py:35 | Avg. local train loss : 3.7027524568140513, train acc : 0.9290791666666667
INFO flwr 2023-08-20 23:36:42,897 | server.py:116 | fit progress: (13, 1.7794672607421875, {'server_test_acc': 0.7384}, 2273.64974090131)
INFO flwr 2023-08-20 23:36:42,897 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 23:36:46,306 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1811460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1811455)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:38:07,199 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-20 23:38:07,304 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-20 23:38:07,398 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1811455)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1811460)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1811462)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1811463)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1811465)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1811458)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1811461)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1811464)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1811465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1811463)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1811464)[0m double free or corruption (fasttop)
E0820 23:38:08.196481568 1657665 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1811458)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1811462)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1811461)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:39:36,306 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:39:36,306 | fed_df.py:547 | Average fusion training loss : 0.0037961378921754657, val accuracy : 0.736, best val accuracy : 0.7566
INFO flwr 2023-08-20 23:39:36,308 | common.py:35 | Avg. local train loss : 3.625757747888565, train acc : 0.9341611111111111
INFO flwr 2023-08-20 23:39:38,906 | server.py:116 | fit progress: (14, 1.8138043273925781, {'server_test_acc': 0.7364}, 2449.6583927613683)
INFO flwr 2023-08-20 23:39:38,906 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 23:39:42,351 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2150611)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2150607)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2150614)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:41:04,938 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-20 23:41:05,042 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 23:41:05,139 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2150611)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2150607)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2150609)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2150613)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2150619)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2150615)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2150618)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2150614)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2150619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2150615)[0m malloc_consolidate(): invalid chunk size
E0820 23:41:05.994122501 1994565 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2150618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2150609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2150613)[0m malloc_consolidate(): invalid chunk size
E0820 23:41:06.973593556 2333874 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:42:34,495 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:42:34,496 | fed_df.py:547 | Average fusion training loss : 0.0034071258675539865, val accuracy : 0.73136, best val accuracy : 0.7472
INFO flwr 2023-08-20 23:42:34,497 | common.py:35 | Avg. local train loss : 3.604039845243096, train acc : 0.9349263888888889
INFO flwr 2023-08-20 23:42:37,105 | server.py:116 | fit progress: (15, 1.7946380798339843, {'server_test_acc': 0.736}, 2627.857516795397)
INFO flwr 2023-08-20 23:42:37,105 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 23:42:40,564 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2507402)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2507404)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:44:02,222 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 23:44:02,326 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-20 23:44:02,422 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2507400)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2507398)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2507402)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2507405)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2507406)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2507407)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2507404)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2507403)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2507398)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507403)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2507405)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2507400)[0m malloc_consolidate(): invalid chunk size
E0820 23:44:04.237762755 2701172 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2507406)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2507407)[0m double free or corruption (fasttop)
E0820 23:44:13.556612135 2717601 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:45:30,903 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:45:30,904 | fed_df.py:547 | Average fusion training loss : 0.0037031359140528367, val accuracy : 0.71928, best val accuracy : 0.737
INFO flwr 2023-08-20 23:45:30,905 | common.py:35 | Avg. local train loss : 3.478705790452659, train acc : 0.9444555555555556
INFO flwr 2023-08-20 23:45:33,539 | server.py:116 | fit progress: (16, 1.7841842956542968, {'server_test_acc': 0.7285}, 2804.2920462819748)
INFO flwr 2023-08-20 23:45:33,540 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 23:45:36,981 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2856447)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:46:59,474 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 23:46:59,578 | fed_df.py:365 | Warm start at round 17
[2m[36m(launch_and_fit pid=2856442)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:46:59,674 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2856442)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2856444)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2856443)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2856445)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2856447)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2856446)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2856448)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2856440)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2856443)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856445)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856440)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856448)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856444)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2856446)[0m double free or corruption (fasttop)
E0820 23:47:01.697181994 3040520 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:48:28,489 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:48:28,489 | fed_df.py:547 | Average fusion training loss : 0.0028614621361484753, val accuracy : 0.7341599999999999, best val accuracy : 0.7462
INFO flwr 2023-08-20 23:48:28,491 | common.py:35 | Avg. local train loss : 3.4826839594170456, train acc : 0.9444097222222223
INFO flwr 2023-08-20 23:48:31,079 | server.py:116 | fit progress: (17, 1.8054840118408204, {'server_test_acc': 0.7453}, 2981.8313252399676)
INFO flwr 2023-08-20 23:48:31,079 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 23:48:34,485 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3194731)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3194730)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3194728)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3194724)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3194729)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-20 23:49:57,760 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 23:49:57,864 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-20 23:49:57,959 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3194724)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3194729)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3194730)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3194731)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3194727)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3194728)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3194726)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3194732)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3194727)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3194726)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3194732)[0m malloc_consolidate(): invalid chunk size
E0820 23:50:00.217968389 3379444 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:50:50.466178589 3465344 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:51:26,401 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:51:26,401 | fed_df.py:547 | Average fusion training loss : 0.003584372717188671, val accuracy : 0.7283000000000001, best val accuracy : 0.748
INFO flwr 2023-08-20 23:51:26,403 | common.py:35 | Avg. local train loss : 3.5156812546774745, train acc : 0.9440625
INFO flwr 2023-08-20 23:51:29,019 | server.py:116 | fit progress: (18, 1.775398388671875, {'server_test_acc': 0.7337}, 3159.7717544049956)
INFO flwr 2023-08-20 23:51:29,019 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 23:51:32,442 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3533143)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:52:54,935 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 23:52:55,040 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-20 23:52:55,136 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3533144)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3533143)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3533147)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3533150)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3533149)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3533145)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3533148)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3533146)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3533148)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3533149)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533150)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3533147)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533145)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533144)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3533146)[0m malloc_consolidate(): invalid chunk size
E0820 23:52:59.064389246 3716971 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:54:24,384 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:54:24,385 | fed_df.py:547 | Average fusion training loss : 0.004019040856161155, val accuracy : 0.74596, best val accuracy : 0.756
INFO flwr 2023-08-20 23:54:24,386 | common.py:35 | Avg. local train loss : 3.439681748487055, train acc : 0.950025
INFO flwr 2023-08-20 23:54:26,942 | server.py:116 | fit progress: (19, 1.7614172790527345, {'server_test_acc': 0.745}, 3337.6946186833084)
INFO flwr 2023-08-20 23:54:26,942 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 23:54:30,454 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3871177)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:55:54,161 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 23:55:54,266 | fed_df.py:365 | Warm start at round 20
[2m[36m(launch_and_fit pid=3871174)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:55:54,365 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3871177)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3871175)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3871181)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3871176)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3871178)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3871180)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3871174)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3871179)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3871181)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3871176)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3871175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3871178)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3871180)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3871179)[0m malloc_consolidate(): invalid chunk size
E0820 23:55:58.579732215 3720045 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:57:23,237 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:57:23,237 | fed_df.py:547 | Average fusion training loss : 0.0033243669477524235, val accuracy : 0.7434200000000001, best val accuracy : 0.7548
INFO flwr 2023-08-20 23:57:23,238 | common.py:35 | Avg. local train loss : 3.4592944756150246, train acc : 0.9480138888888889
INFO flwr 2023-08-20 23:57:25,818 | server.py:116 | fit progress: (20, 1.7464318603515625, {'server_test_acc': 0.7396}, 3516.5712004150264)
INFO flwr 2023-08-20 23:57:25,819 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 23:57:29,326 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=15937)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=15945)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=15939)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:58:52,350 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 23:58:52,454 | fed_df.py:365 | Warm start at round 21
[2m[36m(launch_and_fit pid=15948)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:58:52,549 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=15937)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=15945)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=15939)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=15940)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=15941)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=15946)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=15948)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=15944)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=15946)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=15944)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=15940)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=15941)[0m double free or corruption (fasttop)
E0820 23:58:55.081121137  211988 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:59:47.263156992  213756 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:00:22,096 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:00:22,097 | fed_df.py:547 | Average fusion training loss : 0.004742413502419367, val accuracy : 0.75276, best val accuracy : 0.7628
INFO flwr 2023-08-21 00:00:22,098 | common.py:35 | Avg. local train loss : 3.4412820979952814, train acc : 0.9477708333333333
INFO flwr 2023-08-21 00:00:24,654 | server.py:116 | fit progress: (21, 1.6966073455810546, {'server_test_acc': 0.7422}, 3695.406742951367)
INFO flwr 2023-08-21 00:00:24,654 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-21 00:00:28,128 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=384079)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=384074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384077)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 00:01:51,210 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-21 00:01:51,316 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-21 00:01:51,412 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=384075)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=384073)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=384077)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=384074)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=384076)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=384079)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=384072)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=384078)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=384072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384076)[0m malloc_consolidate(): invalid chunk size
E0821 00:01:52.471214706  565208 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=384073)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384075)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=384078)[0m malloc_consolidate(): invalid chunk size
E0821 00:03:13.563225150  565479 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:03:20,521 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:03:20,521 | fed_df.py:547 | Average fusion training loss : 0.003244435815373436, val accuracy : 0.7413799999999999, best val accuracy : 0.7536
INFO flwr 2023-08-21 00:03:20,523 | common.py:35 | Avg. local train loss : 3.420599831826985, train acc : 0.9481402777777778
INFO flwr 2023-08-21 00:03:23,116 | server.py:116 | fit progress: (22, 1.7627359558105469, {'server_test_acc': 0.7416}, 3873.869122029282)
INFO flwr 2023-08-21 00:03:23,117 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-21 00:03:26,619 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=722859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=722863)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 00:04:49,417 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-21 00:04:49,521 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-21 00:04:49,617 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=722860)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=722863)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=722859)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=722862)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=722865)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=722866)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=722861)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=722864)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=722865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722862)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722861)[0m double free or corruption (fasttop)
E0821 00:04:53.027440104  703986 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:05:33.361282681  907864 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:05:42.875748759  992742 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:06:08.104714238  993413 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:06:19,111 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:06:19,111 | fed_df.py:547 | Average fusion training loss : 0.0032916639145696537, val accuracy : 0.75808, best val accuracy : 0.7664
INFO flwr 2023-08-21 00:06:19,113 | common.py:35 | Avg. local train loss : 3.43875370323658, train acc : 0.9484027777777777
INFO flwr 2023-08-21 00:06:21,672 | server.py:116 | fit progress: (23, 1.7646574432373048, {'server_test_acc': 0.747}, 4052.424840155989)
INFO flwr 2023-08-21 00:06:21,672 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-21 00:06:25,161 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1061705)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:07:47,190 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-21 00:07:47,294 | fed_df.py:365 | Warm start at round 24
[2m[36m(launch_and_fit pid=1061707)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:07:47,391 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1061705)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1061710)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1061708)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1061709)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1061712)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1061713)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1061707)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1061711)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1061708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1061713)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1061711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1061712)[0m malloc_consolidate(): invalid chunk size
E0821 00:07:48.711967226 1242599 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1061710)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1061709)[0m malloc_consolidate(): invalid chunk size
E0821 00:09:10.026286475 1379085 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:09:16,830 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:09:16,830 | fed_df.py:547 | Average fusion training loss : 0.003906471114023588, val accuracy : 0.74756, best val accuracy : 0.7572
INFO flwr 2023-08-21 00:09:16,832 | common.py:35 | Avg. local train loss : 3.487978244014084, train acc : 0.9463277777777778
INFO flwr 2023-08-21 00:09:19,432 | server.py:116 | fit progress: (24, 1.7405374816894532, {'server_test_acc': 0.7444}, 4230.185203083325)
INFO flwr 2023-08-21 00:09:19,433 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-21 00:09:22,910 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1399964)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-21 00:10:44,695 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-21 00:10:44,799 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-21 00:10:44,897 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1399968)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1399961)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1399962)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1399965)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1399967)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1399966)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1399964)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1399963)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1399967)[0m malloc_consolidate(): invalid chunk size
E0821 00:10:45.518223617 1381661 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1399966)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1399963)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1399965)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1399962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1399968)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1399961)[0m malloc_consolidate(): invalid chunk size
E0821 00:11:45.326145398 1679108 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:12:13,898 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:12:13,898 | fed_df.py:547 | Average fusion training loss : 0.0035127733264816927, val accuracy : 0.75442, best val accuracy : 0.765
INFO flwr 2023-08-21 00:12:13,899 | common.py:35 | Avg. local train loss : 3.358123183995485, train acc : 0.9525777777777777
INFO flwr 2023-08-21 00:12:16,493 | server.py:116 | fit progress: (25, 1.7293958160400391, {'server_test_acc': 0.7519}, 4407.24545950396)
INFO flwr 2023-08-21 00:12:16,493 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-21 00:12:19,982 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1738533)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1738587)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:13:41,867 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-21 00:13:41,971 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-21 00:13:42,066 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1738535)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1738533)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1738548)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1738536)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1738534)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1738587)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1738606)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1738532)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1738548)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1738536)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1738532)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1738534)[0m double free or corruption (fasttop)
E0821 00:13:43.375564504 1681368 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1738535)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1738606)[0m double free or corruption (fasttop)
E0821 00:14:15.247367981 1919633 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:15:12,171 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:15:12,172 | fed_df.py:547 | Average fusion training loss : 0.0028433925776043907, val accuracy : 0.75422, best val accuracy : 0.761
INFO flwr 2023-08-21 00:15:12,173 | common.py:35 | Avg. local train loss : 3.3686147406697273, train acc : 0.9533069444444444
INFO flwr 2023-08-21 00:15:14,823 | server.py:116 | fit progress: (26, 1.71765458984375, {'server_test_acc': 0.7528}, 4585.576102821156)
INFO flwr 2023-08-21 00:15:14,824 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-21 00:15:18,291 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2106078)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2106086)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:16:41,602 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2106084)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106082)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:16:41,709 | fed_df.py:365 | Warm start at round 27
[2m[36m(launch_and_fit pid=2106083)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:16:41,806 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2106072)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2106078)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2106084)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2106082)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2106083)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2106085)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2106221)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2106086)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2106072)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2106221)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2106085)[0m malloc_consolidate(): invalid chunk size
E0821 00:16:44.133251307 2288582 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:17:16.111393494 2288992 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:17:45.975766797 2343337 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:18:10,804 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:18:10,804 | fed_df.py:547 | Average fusion training loss : 0.0033188731219852344, val accuracy : 0.7499399999999999, best val accuracy : 0.7568
INFO flwr 2023-08-21 00:18:10,806 | common.py:35 | Avg. local train loss : 3.390664418786764, train acc : 0.9503763888888889
INFO flwr 2023-08-21 00:18:13,542 | server.py:116 | fit progress: (27, 1.71128447265625, {'server_test_acc': 0.75}, 4764.295044259168)
INFO flwr 2023-08-21 00:18:13,543 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-21 00:18:17,005 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2444486)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:19:39,023 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-21 00:19:39,127 | fed_df.py:365 | Warm start at round 28
[2m[36m(launch_and_fit pid=2444555)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:19:39,223 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2444486)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2444558)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2444557)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2444560)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2444559)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2444485)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2444556)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2444555)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2444557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2444485)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2444559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2444558)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2444556)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2444560)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:21:08,650 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:21:08,650 | fed_df.py:547 | Average fusion training loss : 0.003990946163074114, val accuracy : 0.7649, best val accuracy : 0.7716
INFO flwr 2023-08-21 00:21:08,652 | common.py:35 | Avg. local train loss : 3.3360198078677055, train acc : 0.9552597222222222
INFO flwr 2023-08-21 00:21:11,386 | server.py:116 | fit progress: (28, 1.6774017730712891, {'server_test_acc': 0.7607}, 4942.138521031011)
INFO flwr 2023-08-21 00:21:11,386 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-21 00:21:14,866 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2781533)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2781609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2781605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2781610)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 00:22:37,066 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-21 00:22:37,171 | fed_df.py:365 | Warm start at round 29
[2m[36m(launch_and_fit pid=2781606)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:22:37,268 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2781533)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2781534)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2781605)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2781606)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2781609)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2781610)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2781607)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2781608)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2781608)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2781534)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2781607)[0m double free or corruption (fasttop)
E0821 00:22:40.786657170 2394684 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:23:37.851763171 3061329 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:24:06,737 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:24:06,737 | fed_df.py:547 | Average fusion training loss : 0.00364037172368262, val accuracy : 0.76344, best val accuracy : 0.7718
INFO flwr 2023-08-21 00:24:06,738 | common.py:35 | Avg. local train loss : 3.3767313150689007, train acc : 0.9526583333333333
INFO flwr 2023-08-21 00:24:09,348 | server.py:116 | fit progress: (29, 1.664128076171875, {'server_test_acc': 0.754}, 5120.100815063342)
INFO flwr 2023-08-21 00:24:09,348 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-21 00:24:12,922 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3119965)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-21 00:25:35,543 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3119968)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:25:35,648 | fed_df.py:365 | Warm start at round 30
[2m[36m(launch_and_fit pid=3119969)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:25:35,745 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3119965)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3119967)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3119963)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3119966)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3119968)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3119969)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3119971)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3119970)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3119970)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=3119963)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3119967)[0m malloc_consolidate(): invalid chunk size
E0821 00:25:36.821628267 3062908 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3119971)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3119966)[0m double free or corruption (fasttop)
E0821 00:26:13.200479190 3298346 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:26:37.901578422 3398947 chttp2_transport.cc:1079]             ipv4:145.136.62.28:62904: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:27:04,936 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:27:04,937 | fed_df.py:547 | Average fusion training loss : 0.0036319703862536697, val accuracy : 0.7568400000000001, best val accuracy : 0.7636
INFO flwr 2023-08-21 00:27:04,938 | common.py:35 | Avg. local train loss : 3.2947742365300656, train acc : 0.9573444444444446
INFO flwr 2023-08-21 00:27:07,550 | server.py:116 | fit progress: (30, 1.6622934814453125, {'server_test_acc': 0.7564}, 5298.302835305221)
INFO flwr 2023-08-21 00:27:07,550 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-21 00:27:07,550 | server.py:144 | FL finished in 5298.303161655087
INFO flwr 2023-08-21 00:27:07,551 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-21 00:27:07,551 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-21 00:27:07,552 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.6077239166259765), (2, 1.4840391204833985), (3, 1.5501010009765626), (4, 1.6526113983154296), (5, 1.7149032409667968), (6, 1.8125321746826173), (7, 1.8069347534179687), (8, 1.8190706115722657), (9, 1.8803034484863281), (10, 1.8253358520507812), (11, 1.7947281433105469), (12, 1.7757756713867188), (13, 1.7794672607421875), (14, 1.8138043273925781), (15, 1.7946380798339843), (16, 1.7841842956542968), (17, 1.8054840118408204), (18, 1.775398388671875), (19, 1.7614172790527345), (20, 1.7464318603515625), (21, 1.6966073455810546), (22, 1.7627359558105469), (23, 1.7646574432373048), (24, 1.7405374816894532), (25, 1.7293958160400391), (26, 1.71765458984375), (27, 1.71128447265625), (28, 1.6774017730712891), (29, 1.664128076171875), (30, 1.6622934814453125)]
INFO flwr 2023-08-21 00:27:07,552 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4386), (2, 0.547), (3, 0.614), (4, 0.6359), (5, 0.6748), (6, 0.6909), (7, 0.6936), (8, 0.7047), (9, 0.7044), (10, 0.718), (11, 0.7183), (12, 0.7321), (13, 0.7384), (14, 0.7364), (15, 0.736), (16, 0.7285), (17, 0.7453), (18, 0.7337), (19, 0.745), (20, 0.7396), (21, 0.7422), (22, 0.7416), (23, 0.747), (24, 0.7444), (25, 0.7519), (26, 0.7528), (27, 0.75), (28, 0.7607), (29, 0.754), (30, 0.7564)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn28: task 0: Aborted
srun: Terminating StepId=3430373.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3430373
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:59:59
CPU Efficiency: 11.18% of 1-02:49:12 core-walltime
Job Wall-clock time: 01:29:24
Memory Utilized: 49.09 GB
Memory Efficiency: 40.91% of 120.00 GB
