-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:5000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:pathmnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:2
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:True
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=5000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3430447/1692565235_404559538', seed=42, img_per_thread=277)
will save 5000 patches in /scratch-local/sunnys.3430447/1692565235_404559538/single_img_crops/crops
5000 took 0.09min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 23:00:56,569 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 23:00:56,569 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3430447/1692565235_404559538/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3430447/1692565235_404559538/cifar-10-python.tar.gz to /scratch-local/sunnys.3430447/1692565235_404559538
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
INFO flwr 2023-08-20 23:01:16,438 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 23:01:18,975	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-20 23:01:19,994 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'accelerator_type:A100': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'GPU': 1.0, 'node:145.136.62.20': 1.0}
INFO flwr 2023-08-20 23:01:19,995 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 23:01:19,995 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 23:01:19,995 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 23:01:30,378 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-20 23:01:30,378 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 23:01:34,068 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1075891)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:02:54,393 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-20 23:02:54,502 | fed_df.py:365 | Warm start at round 1
[2m[36m(launch_and_fit pid=1075886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1075888)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:02:54,591 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1075885)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1075884)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1075890)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1075887)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1075886)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1075891)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1075889)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1075888)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1075885)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075887)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075889)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075890)[0m malloc_consolidate(): invalid chunk size
E0820 23:02:57.096539847 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102117787 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102130153 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102139150 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102146998 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102155049 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102164054 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102172065 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102180001 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102187811 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102195507 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102203234 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:02:57.102213500 1069818 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0820 23:03:14.213450482 1201896 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
E0820 23:04:04.764171744 1254121 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-20 23:04:14,529 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:04:14,532 | fed_df.py:547 | Average fusion training loss : 0.011466934080701322, val accuracy : 0.39394, best val accuracy : 0.4362
INFO flwr 2023-08-20 23:04:14,533 | common.py:35 | Avg. local train loss : 6.7993005275726315, train acc : 0.5957749999999999
INFO flwr 2023-08-20 23:04:16,954 | server.py:116 | fit progress: (1, 1.634512271118164, {'server_test_acc': 0.4348}, 166.57538089575246)
INFO flwr 2023-08-20 23:04:16,954 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 23:04:20,367 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1267247)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:05:40,222 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-20 23:05:40,329 | fed_df.py:365 | Warm start at round 2
[2m[36m(launch_and_fit pid=1267243)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:05:40,425 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1267239)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1267244)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1267246)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1267238)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1267248)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1267247)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1267245)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1267243)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1267248)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1267246)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1267245)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1267244)[0m malloc_consolidate(): invalid chunk size
E0820 23:05:41.545626857 1254900 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=1267239)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1267238)[0m double free or corruption (fasttop)
E0820 23:06:15.305632493 1358268 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
E0820 23:06:40.234699593 1409059 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
E0820 23:07:05.194382627 1432957 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-20 23:07:06,152 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:07:06,153 | fed_df.py:547 | Average fusion training loss : 0.007900099636986851, val accuracy : 0.5256199999999999, best val accuracy : 0.5506
INFO flwr 2023-08-20 23:07:06,154 | common.py:35 | Avg. local train loss : 5.304451769031584, train acc : 0.7417027777777778
INFO flwr 2023-08-20 23:07:08,611 | server.py:116 | fit progress: (2, 1.5693269744873046, {'server_test_acc': 0.5307}, 338.23225096194074)
INFO flwr 2023-08-20 23:07:08,611 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 23:07:11,974 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1437023)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:08:31,468 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-20 23:08:31,606 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1437028)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1437026)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1437022)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1437023)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1437027)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1437029)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1437021)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1437028)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1437016)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1437029)[0m double free or corruption (fasttop)
E0820 23:08:31.847114472 1433429 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1437022)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1437021)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1437026)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1437016)[0m double free or corruption (fasttop)
E0820 23:08:33.479633374 1527270 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=1437027)[0m double free or corruption (fasttop)
E0820 23:08:50.805076887 1528875 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-20 23:09:53,368 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:09:53,369 | fed_df.py:547 | Average fusion training loss : 0.002577080577844754, val accuracy : 0.59662, best val accuracy : 0.6138
INFO flwr 2023-08-20 23:09:53,370 | common.py:35 | Avg. local train loss : 4.65477279536426, train acc : 0.8169083333333333
INFO flwr 2023-08-20 23:09:55,875 | server.py:116 | fit progress: (3, 1.568582733154297, {'server_test_acc': 0.5981}, 505.4969032756053)
INFO flwr 2023-08-20 23:09:55,876 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 23:09:59,272 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1606883)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:11:19,304 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-20 23:11:19,410 | fed_df.py:365 | Warm start at round 4
[2m[36m(launch_and_fit pid=1606884)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:11:19,498 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1606884)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1606883)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1606880)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1606879)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1606882)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1606881)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1606878)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1606885)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1606880)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1606878)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1606881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1606882)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1606879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1606885)[0m malloc_consolidate(): invalid chunk size
E0820 23:11:21.663670865 1545252 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-20 23:12:40,693 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:12:40,693 | fed_df.py:547 | Average fusion training loss : 0.014061001670779661, val accuracy : 0.5726, best val accuracy : 0.6078
INFO flwr 2023-08-20 23:12:40,694 | common.py:35 | Avg. local train loss : 4.785681022703647, train acc : 0.8041652777777778
INFO flwr 2023-08-20 23:12:43,162 | server.py:116 | fit progress: (4, 1.5834111419677734, {'server_test_acc': 0.5886}, 672.7834763349965)
INFO flwr 2023-08-20 23:12:43,162 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 23:12:46,568 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 23:14:05,996 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1776856)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 23:14:06,133 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1776851)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1776852)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1776854)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1776853)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1776849)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1776855)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1776856)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1776850)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1776849)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1776855)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1776851)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1776854)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1776850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1776852)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1776853)[0m malloc_consolidate(): invalid chunk size
E0820 23:14:47.389852637 1887953 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
E0820 23:15:12.497126296 1929226 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-20 23:15:27,687 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:15:27,687 | fed_df.py:547 | Average fusion training loss : 0.002111297243507579, val accuracy : 0.6361600000000001, best val accuracy : 0.6502
INFO flwr 2023-08-20 23:15:27,688 | common.py:35 | Avg. local train loss : 4.519434040412307, train acc : 0.8338916666666667
INFO flwr 2023-08-20 23:15:30,160 | server.py:116 | fit progress: (5, 1.5184144592285156, {'server_test_acc': 0.6375}, 839.78163322201)
INFO flwr 2023-08-20 23:15:30,160 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 23:15:33,575 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1946603)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1946601)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1946605)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:16:53,661 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1946606)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:16:53,767 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-20 23:16:53,862 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1946601)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1946602)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1946598)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1946606)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1946603)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1946605)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1946604)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1946600)[0m Fitting Client 17
E0820 23:16:54.253195927 2037199 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1946600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1946598)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1946602)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1946604)[0m malloc_consolidate(): invalid chunk size
E0820 23:16:55.772151794 2039070 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0820 23:17:23.092910112 2039468 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0820 23:17:48.108808623 2102447 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:18:16,766 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:18:16,767 | fed_df.py:547 | Average fusion training loss : 0.006835958319948986, val accuracy : 0.62536, best val accuracy : 0.6454
INFO flwr 2023-08-20 23:18:16,767 | common.py:35 | Avg. local train loss : 4.292897857911885, train acc : 0.8555305555555556
INFO flwr 2023-08-20 23:18:19,253 | server.py:116 | fit progress: (6, 1.6268824951171874, {'server_test_acc': 0.6337}, 1008.8741997038014)
INFO flwr 2023-08-20 23:18:19,253 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 23:18:22,643 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2141227)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141220)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:19:42,846 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-20 23:19:42,991 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2141229)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2141221)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2141227)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2141228)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2141226)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2141223)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2141222)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2141220)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2141223)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141221)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141229)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141226)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141222)[0m malloc_consolidate(): invalid chunk size
E0820 23:19:45.322880944 2102886 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:20:18.740660253 2233421 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:21:04,804 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:21:04,804 | fed_df.py:547 | Average fusion training loss : 0.0017892435203539208, val accuracy : 0.66616, best val accuracy : 0.679
INFO flwr 2023-08-20 23:21:04,805 | common.py:35 | Avg. local train loss : 4.225621919706464, train acc : 0.8695097222222223
INFO flwr 2023-08-20 23:21:07,308 | server.py:116 | fit progress: (7, 1.5643567016601563, {'server_test_acc': 0.6674}, 1176.929763843771)
INFO flwr 2023-08-20 23:21:07,308 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 23:21:10,715 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2310960)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:22:30,285 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-20 23:22:30,392 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-20 23:22:30,487 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2310958)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2310962)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2310964)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2310958)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2310955)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2310961)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2310960)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2310963)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2310959)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2310961)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2310963)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2310964)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2310962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2310959)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2310955)[0m malloc_consolidate(): invalid chunk size
E0820 23:22:32.674497814 2265093 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:23:51,755 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:23:51,755 | fed_df.py:547 | Average fusion training loss : 0.006052431999472902, val accuracy : 0.6749599999999999, best val accuracy : 0.6912
INFO flwr 2023-08-20 23:23:51,756 | common.py:35 | Avg. local train loss : 4.418889865651727, train acc : 0.8543208333333334
INFO flwr 2023-08-20 23:23:54,263 | server.py:116 | fit progress: (8, 1.7308848388671876, {'server_test_acc': 0.6805}, 1343.8845551968552)
INFO flwr 2023-08-20 23:23:54,263 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 23:23:57,650 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2480758)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:25:17,279 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-20 23:25:17,424 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2480755)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2480758)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2480756)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2480754)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2480751)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2480757)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2480752)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2480753)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2480757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2480755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2480756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2480752)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2480754)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2480751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2480753)[0m malloc_consolidate(): invalid chunk size
E0820 23:25:58.195607092 2403188 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:26:39,044 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:26:39,045 | fed_df.py:547 | Average fusion training loss : 0.00245165641407948, val accuracy : 0.6843600000000001, best val accuracy : 0.6932
INFO flwr 2023-08-20 23:26:39,046 | common.py:35 | Avg. local train loss : 4.117075667716564, train acc : 0.8858736111111111
INFO flwr 2023-08-20 23:26:41,527 | server.py:116 | fit progress: (9, 1.6146913146972657, {'server_test_acc': 0.6842}, 1511.1481605949812)
INFO flwr 2023-08-20 23:26:41,527 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 23:26:44,964 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2650754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2650756)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:28:05,172 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2650751)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2650755)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:28:05,280 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-20 23:28:05,376 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2650756)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2650751)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2650754)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2650753)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2650755)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2650748)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2650744)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2650746)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2650753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2650746)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2650744)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2650748)[0m malloc_consolidate(): invalid chunk size
E0820 23:28:09.199541778 2609462 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:28:40.978670507 2744435 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:29:27,000 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:29:27,000 | fed_df.py:547 | Average fusion training loss : 0.006154223937075585, val accuracy : 0.6700999999999999, best val accuracy : 0.6876
INFO flwr 2023-08-20 23:29:27,001 | common.py:35 | Avg. local train loss : 4.091724197007716, train acc : 0.8890083333333333
INFO flwr 2023-08-20 23:29:29,514 | server.py:116 | fit progress: (10, 1.6905153686523438, {'server_test_acc': 0.6803}, 1679.135628205724)
INFO flwr 2023-08-20 23:29:29,514 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 23:29:32,917 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2820640)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2820642)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:30:52,083 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-20 23:30:52,228 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2820640)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2820633)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2820642)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2820639)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2820637)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2820643)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2820638)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2820641)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2820638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2820639)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2820637)[0m malloc_consolidate(): invalid chunk size
E0820 23:30:53.200817049 2911357 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2820643)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2820641)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2820633)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 23:32:13,734 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:32:13,735 | fed_df.py:547 | Average fusion training loss : 0.0019065739610232412, val accuracy : 0.70038, best val accuracy : 0.708
INFO flwr 2023-08-20 23:32:13,736 | common.py:35 | Avg. local train loss : 4.026137975417078, train acc : 0.8964083333333334
INFO flwr 2023-08-20 23:32:16,174 | server.py:116 | fit progress: (11, 1.659815460205078, {'server_test_acc': 0.6922}, 1845.795953918714)
INFO flwr 2023-08-20 23:32:16,175 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 23:32:19,642 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2990956)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2990934)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:33:39,542 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 23:33:39,649 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-20 23:33:39,748 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2990956)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2990934)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2990935)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2990949)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2990928)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2990943)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2990958)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2990909)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2990958)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2990949)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2990909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2990928)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2990943)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2990935)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:35:02,369 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:35:02,369 | fed_df.py:547 | Average fusion training loss : 0.005543340034084395, val accuracy : 0.68848, best val accuracy : 0.7146
INFO flwr 2023-08-20 23:35:02,370 | common.py:35 | Avg. local train loss : 4.142590208165348, train acc : 0.8851541666666667
INFO flwr 2023-08-20 23:35:04,846 | server.py:116 | fit progress: (12, 1.7049868774414063, {'server_test_acc': 0.6978}, 2014.4673887258396)
INFO flwr 2023-08-20 23:35:04,846 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 23:35:08,274 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 23:36:27,851 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3184842)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3184840)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 23:36:27,999 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3184839)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3184838)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3184824)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3184840)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3184841)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3184842)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3184837)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3184834)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3184838)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3184839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3184834)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3184824)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3184841)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3184837)[0m malloc_consolidate(): invalid chunk size
E0820 23:36:36.537020493 3278991 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:37:49,702 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:37:49,702 | fed_df.py:547 | Average fusion training loss : 0.0017963673864724115, val accuracy : 0.70214, best val accuracy : 0.7138
INFO flwr 2023-08-20 23:37:49,703 | common.py:35 | Avg. local train loss : 3.9677521025761964, train acc : 0.9011847222222222
INFO flwr 2023-08-20 23:37:52,166 | server.py:116 | fit progress: (13, 1.6507399383544923, {'server_test_acc': 0.7002}, 2181.7877221410163)
INFO flwr 2023-08-20 23:37:52,166 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 23:37:55,588 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3354586)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:39:15,613 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3354583)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 23:39:15,720 | fed_df.py:365 | Warm start at round 14
[2m[36m(launch_and_fit pid=3354584)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:39:15,815 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3354580)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3354585)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3354586)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3354582)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3354587)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3354583)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3354584)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3354588)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3354588)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354585)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354580)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3354587)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3354582)[0m malloc_consolidate(): invalid chunk size
E0820 23:39:17.905153602 3282944 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:40:37,772 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:40:37,773 | fed_df.py:547 | Average fusion training loss : 0.005398945899331011, val accuracy : 0.67328, best val accuracy : 0.6966
INFO flwr 2023-08-20 23:40:37,774 | common.py:35 | Avg. local train loss : 3.968382510915399, train acc : 0.899775
INFO flwr 2023-08-20 23:40:40,280 | server.py:116 | fit progress: (14, 1.7519315338134767, {'server_test_acc': 0.6922}, 2349.9020434687845)
INFO flwr 2023-08-20 23:40:40,281 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 23:40:43,695 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 23:42:03,138 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-20 23:42:03,284 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3524580)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3524586)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3524587)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3524590)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3524588)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3524589)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3524591)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3524592)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3524589)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524580)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524588)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3524586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524591)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3524592)[0m malloc_consolidate(): invalid chunk size
E0820 23:42:07.067045082 3446764 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:43:25,075 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:43:25,075 | fed_df.py:547 | Average fusion training loss : 0.0017861919833812862, val accuracy : 0.70684, best val accuracy : 0.7154
INFO flwr 2023-08-20 23:43:25,076 | common.py:35 | Avg. local train loss : 3.8046328973025076, train acc : 0.9140583333333333
INFO flwr 2023-08-20 23:43:27,546 | server.py:116 | fit progress: (15, 1.6425013671875, {'server_test_acc': 0.7039}, 2517.167747030966)
INFO flwr 2023-08-20 23:43:27,546 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 23:43:30,963 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3694605)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3694604)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:44:50,830 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-20 23:44:50,937 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-20 23:44:51,032 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3694605)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3694603)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3694604)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3694601)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3694607)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3694606)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3694602)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3694599)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3694601)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3694607)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3694606)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3694599)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3694603)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3694602)[0m malloc_consolidate(): invalid chunk size
E0820 23:45:58.336385147 3844549 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:45:58.336458689 3844549 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:46:13,319 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:46:13,319 | fed_df.py:547 | Average fusion training loss : 0.004311662486637943, val accuracy : 0.69338, best val accuracy : 0.7138
INFO flwr 2023-08-20 23:46:13,320 | common.py:35 | Avg. local train loss : 3.8639027232304217, train acc : 0.9090805555555556
INFO flwr 2023-08-20 23:46:15,851 | server.py:116 | fit progress: (16, 1.7803576568603516, {'server_test_acc': 0.7022}, 2685.472580409609)
INFO flwr 2023-08-20 23:46:15,851 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 23:46:19,371 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3865139)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3865138)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:47:39,213 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3865137)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:47:39,359 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3865138)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3865134)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3865131)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3865137)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3865136)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3865139)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3865133)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3865135)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3865131)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3865133)[0m double free or corruption (fasttop)
E0820 23:47:40.037649471 3955992 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3865135)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3865134)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3865136)[0m double free or corruption (fasttop)
E0820 23:48:06.164510741 3956402 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:48:30.912165709 4013568 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:48:55.768859113 4042615 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:49:02,748 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:49:02,749 | fed_df.py:547 | Average fusion training loss : 0.0020617747690994293, val accuracy : 0.7009799999999999, best val accuracy : 0.709
INFO flwr 2023-08-20 23:49:02,750 | common.py:35 | Avg. local train loss : 3.8918103946372873, train acc : 0.9104472222222223
INFO flwr 2023-08-20 23:49:05,289 | server.py:116 | fit progress: (17, 1.6926986755371094, {'server_test_acc': 0.7005}, 2854.9103932660073)
INFO flwr 2023-08-20 23:49:05,289 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 23:49:08,764 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4055707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4055703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4055716)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4055715)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:50:29,565 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4055702)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:50:29,673 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-20 23:50:29,768 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4055714)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4055701)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4055707)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4055703)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4055702)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4055715)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4055716)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4055706)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4055701)[0m double free or corruption (fasttop)
E0820 23:50:30.549587770 4152743 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4055706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4055714)[0m double free or corruption (fasttop)
E0820 23:50:36.235582970 4157882 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:51:01.397729704 4158359 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:51:52,238 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:51:52,238 | fed_df.py:547 | Average fusion training loss : 0.004476990040508099, val accuracy : 0.7106, best val accuracy : 0.7252
INFO flwr 2023-08-20 23:51:52,239 | common.py:35 | Avg. local train loss : 3.830427646636963, train acc : 0.9152902777777778
INFO flwr 2023-08-20 23:51:54,731 | server.py:116 | fit progress: (18, 1.683527264404297, {'server_test_acc': 0.7223}, 3024.352360748686)
INFO flwr 2023-08-20 23:51:54,731 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 23:51:58,146 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=39460)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=39456)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:53:18,032 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 23:53:18,178 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=39455)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=39457)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=39460)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=39458)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=39459)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=39452)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=39461)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=39456)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=39452)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=39457)[0m malloc_consolidate(): invalid chunk size
E0820 23:53:18.739582804 4181893 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=39459)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=39461)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=39455)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=39458)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 23:54:40,508 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:54:40,508 | fed_df.py:547 | Average fusion training loss : 0.0017762391524156556, val accuracy : 0.7357199999999999, best val accuracy : 0.739
INFO flwr 2023-08-20 23:54:40,509 | common.py:35 | Avg. local train loss : 3.821879711188376, train acc : 0.9178569444444444
INFO flwr 2023-08-20 23:54:43,007 | server.py:116 | fit progress: (19, 1.608461489868164, {'server_test_acc': 0.727}, 3192.62849496305)
INFO flwr 2023-08-20 23:54:43,007 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 23:54:46,440 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=211115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211122)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211120)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 23:56:06,975 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 23:56:07,081 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-20 23:56:07,176 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=211121)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=211119)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=211111)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=211122)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=211120)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=211118)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=211115)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=211073)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=211111)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=211119)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211121)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211073)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=211118)[0m malloc_consolidate(): invalid chunk size
E0820 23:57:14.676816905  131029 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 23:57:29,241 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-20 23:57:29,242 | fed_df.py:547 | Average fusion training loss : 0.0038419338145758955, val accuracy : 0.7298599999999998, best val accuracy : 0.7394
INFO flwr 2023-08-20 23:57:29,243 | common.py:35 | Avg. local train loss : 3.8356198662891985, train acc : 0.9138222222222223
INFO flwr 2023-08-20 23:57:31,725 | server.py:116 | fit progress: (20, 1.6952832916259766, {'server_test_acc': 0.7287}, 3361.3468298986554)
INFO flwr 2023-08-20 23:57:31,725 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 23:57:35,127 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=381760)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=381761)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=381765)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=381762)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 23:58:55,474 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 23:58:55,620 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=381766)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=381765)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=381757)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=381764)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=381761)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=381762)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=381760)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=381763)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=381764)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=381763)[0m double free or corruption (fasttop)
E0820 23:58:56.396601763  365443 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=381757)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=381766)[0m double free or corruption (fasttop)
E0820 23:59:08.379113772  483373 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 23:59:33.569899673  483913 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:00:17,612 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:00:17,612 | fed_df.py:547 | Average fusion training loss : 0.001544039913569577, val accuracy : 0.70724, best val accuracy : 0.7156
INFO flwr 2023-08-21 00:00:17,613 | common.py:35 | Avg. local train loss : 3.773824325203896, train acc : 0.9185208333333332
INFO flwr 2023-08-21 00:00:20,097 | server.py:116 | fit progress: (21, 1.6544996948242188, {'server_test_acc': 0.6997}, 3529.7187837618403)
INFO flwr 2023-08-21 00:00:20,097 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-21 00:00:23,497 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=551948)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:01:44,376 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=551949)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:01:44,483 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-21 00:01:44,578 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=551952)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=551947)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=551951)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=551949)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=551953)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=551948)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=551945)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=551950)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=551947)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=551953)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551952)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=551951)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=551945)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=551950)[0m malloc_consolidate(): invalid chunk size
E0821 00:01:48.414414627  507721 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:02:09.145085294  645539 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:02:59.705538397  665160 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:03:06,527 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:03:06,528 | fed_df.py:547 | Average fusion training loss : 0.0035826721675693987, val accuracy : 0.74322, best val accuracy : 0.753
INFO flwr 2023-08-21 00:03:06,529 | common.py:35 | Avg. local train loss : 3.8362930415198204, train acc : 0.9142388888888889
INFO flwr 2023-08-21 00:03:09,052 | server.py:116 | fit progress: (22, 1.686807794189453, {'server_test_acc': 0.7428}, 3698.6733136349358)
INFO flwr 2023-08-21 00:03:09,052 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-21 00:03:12,511 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 00:04:32,395 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=722135)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:04:32,545 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=722150)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=722134)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=722135)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=722151)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=722149)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=722108)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=722127)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=722133)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=722149)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=722151)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722134)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=722108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722127)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=722150)[0m malloc_consolidate(): invalid chunk size
E0821 00:04:34.330186860  829581 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=722133)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:05:55,946 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:05:55,947 | fed_df.py:547 | Average fusion training loss : 0.0014427006099140272, val accuracy : 0.74196, best val accuracy : 0.7494
INFO flwr 2023-08-21 00:05:55,948 | common.py:35 | Avg. local train loss : 3.9033358307555317, train acc : 0.9118486111111112
INFO flwr 2023-08-21 00:05:58,455 | server.py:116 | fit progress: (23, 1.6063131134033204, {'server_test_acc': 0.7423}, 3868.0762165179476)
INFO flwr 2023-08-21 00:05:58,455 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-21 00:06:01,861 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=917055)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=917052)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:07:22,354 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=917053)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:07:22,461 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-21 00:07:22,550 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=917050)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=917053)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=917055)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=917054)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=917052)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=917047)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=917051)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=917056)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=917047)[0m double free or corruption (fasttop)
E0821 00:07:22.905000775 1007469 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=917054)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=917051)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=917050)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=917056)[0m double free or corruption (fasttop)
E0821 00:07:40.643367855 1007708 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:08:05.517024415 1024355 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:08:44,670 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:08:44,670 | fed_df.py:547 | Average fusion training loss : 0.003885581074282527, val accuracy : 0.73286, best val accuracy : 0.7426
INFO flwr 2023-08-21 00:08:44,671 | common.py:35 | Avg. local train loss : 3.7135089427232737, train acc : 0.9240152777777778
INFO flwr 2023-08-21 00:08:47,165 | server.py:116 | fit progress: (24, 1.6829655059814452, {'server_test_acc': 0.7279}, 4036.7863634107634)
INFO flwr 2023-08-21 00:08:47,165 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-21 00:08:50,678 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1087972)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1087978)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087976)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:10:11,125 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-21 00:10:11,264 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1087972)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1087974)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1087978)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1087973)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1087976)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1087975)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1087977)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1087979)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1087979)[0m malloc_consolidate(): invalid chunk size
E0821 00:10:11.586302725 1047513 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1087977)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087974)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087973)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1087975)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:11:33,812 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:11:33,812 | fed_df.py:547 | Average fusion training loss : 0.001272801162151154, val accuracy : 0.72752, best val accuracy : 0.7328
INFO flwr 2023-08-21 00:11:33,813 | common.py:35 | Avg. local train loss : 3.753118091449142, train acc : 0.9233208333333334
INFO flwr 2023-08-21 00:11:36,311 | server.py:116 | fit progress: (25, 1.6448604431152343, {'server_test_acc': 0.727}, 4205.932187375613)
INFO flwr 2023-08-21 00:11:36,311 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-21 00:11:39,750 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1258166)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1258161)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1258165)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:12:59,523 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-21 00:12:59,630 | fed_df.py:365 | Warm start at round 26
[2m[36m(launch_and_fit pid=1258159)[0m double free or corruption (fasttop)
INFO flwr 2023-08-21 00:12:59,720 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1258167)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1258164)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1258163)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1258159)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1258165)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1258161)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1258168)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1258166)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1258163)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1258164)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1258167)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1258168)[0m double free or corruption (fasttop)
E0821 00:13:02.747546250 1349523 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:14:22,764 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:14:22,764 | fed_df.py:547 | Average fusion training loss : 0.0033756598780164495, val accuracy : 0.71812, best val accuracy : 0.7308
INFO flwr 2023-08-21 00:14:22,765 | common.py:35 | Avg. local train loss : 3.7563791774213313, train acc : 0.9208027777777777
INFO flwr 2023-08-21 00:14:25,280 | server.py:116 | fit progress: (26, 1.7721381256103517, {'server_test_acc': 0.7218}, 4374.901153666899)
INFO flwr 2023-08-21 00:14:25,280 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-21 00:14:28,708 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 00:15:48,555 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1428056)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-21 00:15:48,696 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1428057)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1428054)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1428051)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1428053)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1428056)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1428059)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1428049)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1428058)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1428049)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1428057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1428059)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1428058)[0m malloc_consolidate(): invalid chunk size
E0821 00:15:49.586074549 1350844 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1428054)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1428053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1428051)[0m malloc_consolidate(): invalid chunk size
E0821 00:16:12.796738549 1539679 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:17:11,804 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:17:11,805 | fed_df.py:547 | Average fusion training loss : 0.0017645010036649183, val accuracy : 0.7484, best val accuracy : 0.7516
INFO flwr 2023-08-21 00:17:11,806 | common.py:35 | Avg. local train loss : 3.68109602611512, train acc : 0.9302944444444444
INFO flwr 2023-08-21 00:17:14,319 | server.py:116 | fit progress: (27, 1.7018956298828125, {'server_test_acc': 0.7432}, 4543.940258761868)
INFO flwr 2023-08-21 00:17:14,319 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-21 00:17:17,846 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1598051)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:18:37,680 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-21 00:18:37,788 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-21 00:18:37,878 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1598056)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1598058)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1598057)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1598052)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1598055)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1598051)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1598053)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1598054)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1598056)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1598052)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1598057)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1598058)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1598053)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1598054)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1598055)[0m double free or corruption (fasttop)
E0821 00:18:39.788508027 1540425 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:19:13.343758512 1689534 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:20:01,820 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:20:01,821 | fed_df.py:547 | Average fusion training loss : 0.0034430183187359946, val accuracy : 0.73694, best val accuracy : 0.7462
INFO flwr 2023-08-21 00:20:01,822 | common.py:35 | Avg. local train loss : 3.7531160132959487, train acc : 0.9237958333333333
E0821 00:20:03.790569102 1787241 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:20:04,362 | server.py:116 | fit progress: (28, 1.699318032836914, {'server_test_acc': 0.7332}, 4713.983935717028)
INFO flwr 2023-08-21 00:20:04,363 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-21 00:20:08,014 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-21 00:21:28,032 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-21 00:21:28,173 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1791071)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1791078)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1791072)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1791057)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1791073)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1791068)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1791077)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1791048)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1791078)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1791057)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1791073)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1791071)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1791077)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1791048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1791072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1791068)[0m malloc_consolidate(): invalid chunk size
E0821 00:21:30.137659485 1788121 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:21:43.886168668 1884255 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:22:50,707 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:22:50,708 | fed_df.py:547 | Average fusion training loss : 0.0015450445630121976, val accuracy : 0.7421800000000001, best val accuracy : 0.7492
INFO flwr 2023-08-21 00:22:50,709 | common.py:35 | Avg. local train loss : 3.6151413964107637, train acc : 0.9332999999999999
INFO flwr 2023-08-21 00:22:53,201 | server.py:116 | fit progress: (29, 1.647018359375, {'server_test_acc': 0.744}, 4882.8225370738655)
INFO flwr 2023-08-21 00:22:53,201 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-21 00:22:56,642 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1962159)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-21 00:24:16,310 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-21 00:24:16,418 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-21 00:24:16,508 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1962158)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1962161)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1962164)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1962162)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1962160)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1962159)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1962163)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1962157)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1962160)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1962164)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1962157)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1962162)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1962163)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1962161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1962158)[0m malloc_consolidate(): invalid chunk size
E0821 00:24:18.984662449 1897126 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:24:44.706194122 2077841 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0821 00:25:34.971539833 2078517 chttp2_transport.cc:1079]             ipv4:145.136.62.20:58737: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-21 00:25:39,878 | fed_df.py:540 | Distillation training stopped at step number : 500
INFO flwr 2023-08-21 00:25:39,879 | fed_df.py:547 | Average fusion training loss : 0.0031835266961716116, val accuracy : 0.73902, best val accuracy : 0.7514
INFO flwr 2023-08-21 00:25:39,880 | common.py:35 | Avg. local train loss : 3.618032327666879, train acc : 0.9316
INFO flwr 2023-08-21 00:25:42,365 | server.py:116 | fit progress: (30, 1.725153155517578, {'server_test_acc': 0.7347}, 5051.986943816766)
INFO flwr 2023-08-21 00:25:42,366 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-21 00:25:42,366 | server.py:144 | FL finished in 5051.987372224685
INFO flwr 2023-08-21 00:25:42,366 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-21 00:25:42,367 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-21 00:25:42,367 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.634512271118164), (2, 1.5693269744873046), (3, 1.568582733154297), (4, 1.5834111419677734), (5, 1.5184144592285156), (6, 1.6268824951171874), (7, 1.5643567016601563), (8, 1.7308848388671876), (9, 1.6146913146972657), (10, 1.6905153686523438), (11, 1.659815460205078), (12, 1.7049868774414063), (13, 1.6507399383544923), (14, 1.7519315338134767), (15, 1.6425013671875), (16, 1.7803576568603516), (17, 1.6926986755371094), (18, 1.683527264404297), (19, 1.608461489868164), (20, 1.6952832916259766), (21, 1.6544996948242188), (22, 1.686807794189453), (23, 1.6063131134033204), (24, 1.6829655059814452), (25, 1.6448604431152343), (26, 1.7721381256103517), (27, 1.7018956298828125), (28, 1.699318032836914), (29, 1.647018359375), (30, 1.725153155517578)]
INFO flwr 2023-08-21 00:25:42,367 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4348), (2, 0.5307), (3, 0.5981), (4, 0.5886), (5, 0.6375), (6, 0.6337), (7, 0.6674), (8, 0.6805), (9, 0.6842), (10, 0.6803), (11, 0.6922), (12, 0.6978), (13, 0.7002), (14, 0.6922), (15, 0.7039), (16, 0.7022), (17, 0.7005), (18, 0.7223), (19, 0.727), (20, 0.7287), (21, 0.6997), (22, 0.7428), (23, 0.7423), (24, 0.7279), (25, 0.727), (26, 0.7218), (27, 0.7432), (28, 0.7332), (29, 0.744), (30, 0.7347)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn20: task 0: Aborted
srun: Terminating StepId=3430447.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3430447
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:56:34
CPU Efficiency: 11.45% of 1-01:42:18 core-walltime
Job Wall-clock time: 01:25:41
Memory Utilized: 50.13 GB
Memory Efficiency: 41.78% of 120.00 GB
