-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:100000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar100
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar10
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3342168/1692105549_888658591', seed=42, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3342168/1692105549_888658591/single_img_crops/crops
100000 took 0.77min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 15:20:08,847 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 15:20:08,847 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3342168/1692105549_888658591/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3342168/1692105549_888658591/cifar-100-python.tar.gz to /scratch-local/sunnys.3342168/1692105549_888658591
Generating unified cifar100 dataset
Class histogram for 0-th partition (alpha=100.0, 100 classes): [26 20 14 17 24 36 32 25 40 29 23 24 20 26 28 32 35 28 17 22 19 19 30 26
 29 24 26 17 36 24 29 19 22 28 29 27 27 21 19 23 23 24 13 16 21 32 29 28
 26 27 27 33 26 17 22 25 24 27 28 28 32 16 27 31 30 27 29 20 21 26 34 28
 16 22 23 31 16 18 22 25 24 19 32 18 28 25 22 21 26 18 29 38 22 27 18 22
 29 23 27 30]
INFO flwr 2023-08-15 15:20:49,009 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 15:20:51,844	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-15 15:20:52,935 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'CPU': 18.0, 'memory': 103079215104.0, 'GPU': 1.0, 'object_store_memory': 61847529062.0, 'node:145.136.62.31': 1.0}
INFO flwr 2023-08-15 15:20:52,935 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 15:20:52,935 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 15:20:52,935 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 15:21:00,589 | server.py:91 | initial parameters (loss, other metrics): 4.655556018066406, {'server_test_acc': 0.0107}
INFO flwr 2023-08-15 15:21:00,589 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 15:21:09,980 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:22:00,648 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4115284)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:22:00,870 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-15 15:22:00,982 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4115283)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4115284)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4115287)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4115286)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4115285)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4115289)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4115288)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4115290)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4115283)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4115285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4115287)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4115288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4115286)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4115290)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4115289)[0m double free or corruption (fasttop)
E0815 15:22:04.854385672 4109158 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-15 15:22:38,818 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:22:38,818 | fed_df.py:547 | Average fusion training loss : 0.30398416316509247, val accuracy : 0.088, best val accuracy : 0.0988
INFO flwr 2023-08-15 15:22:38,820 | common.py:35 | Avg. local train loss : 21.385666680336, train acc : 0.11317222222222222
INFO flwr 2023-08-15 15:22:41,838 | server.py:116 | fit progress: (1, 4.375170275878906, {'server_test_acc': 0.0907}, 101.24903366481885)
INFO flwr 2023-08-15 15:22:41,838 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 15:22:52,224 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=71326)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:23:43,909 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-15 15:23:44,138 | fed_df.py:365 | Warm start at round 2
[2m[36m(launch_and_fit pid=71330)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:23:44,253 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=71326)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=71327)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=71331)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=71330)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=71329)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=71332)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=71334)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=71333)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=71334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=71332)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=71331)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=71329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=71327)[0m double free or corruption (fasttop)
E0815 15:23:45.586294311  168539 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=71333)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:24:25,865 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:24:25,865 | fed_df.py:547 | Average fusion training loss : 0.29593518435955046, val accuracy : 0.11747999999999999, best val accuracy : 0.1304
INFO flwr 2023-08-15 15:24:25,867 | common.py:35 | Avg. local train loss : 20.55399637818336, train acc : 0.18487777777777778
INFO flwr 2023-08-15 15:24:29,196 | server.py:116 | fit progress: (2, 4.378863000488281, {'server_test_acc': 0.1242}, 208.60716774361208)
INFO flwr 2023-08-15 15:24:29,196 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 15:24:40,497 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:25:31,303 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=221777)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:25:31,534 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 15:25:31,647 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=221778)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=221773)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=221776)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=221782)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=221779)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=221780)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=221781)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=221777)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=221780)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221778)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221776)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221781)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221782)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221773)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=221779)[0m malloc_consolidate(): invalid chunk size
E0815 15:25:33.514853454  319736 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
E0815 15:25:33.515474399  319736 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
E0815 15:25:33.515491983  319736 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-15 15:26:13,863 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:26:13,864 | fed_df.py:547 | Average fusion training loss : 0.1597321122288704, val accuracy : 0.14679999999999999, best val accuracy : 0.1548
INFO flwr 2023-08-15 15:26:13,865 | common.py:35 | Avg. local train loss : 20.225128585100176, train acc : 0.22771111111111111
INFO flwr 2023-08-15 15:26:17,198 | server.py:116 | fit progress: (3, 4.347889074707031, {'server_test_acc': 0.1549}, 316.6089484617114)
INFO flwr 2023-08-15 15:26:17,198 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 15:26:28,334 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:27:20,018 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-15 15:27:20,248 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 15:27:20,361 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=371641)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=371755)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=371754)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=371757)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=371759)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=371758)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=371753)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=371756)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=371759)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=371758)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=371754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=371756)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=371753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=371755)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=371757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=371641)[0m malloc_consolidate(): invalid chunk size
E0815 15:27:22.291395695  469459 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
E0815 15:27:22.291465120  469459 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-15 15:28:02,223 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:28:02,223 | fed_df.py:547 | Average fusion training loss : 0.03838563472777605, val accuracy : 0.18172, best val accuracy : 0.1872
INFO flwr 2023-08-15 15:28:02,225 | common.py:35 | Avg. local train loss : 19.854580643773076, train acc : 0.27195
INFO flwr 2023-08-15 15:28:05,626 | server.py:116 | fit progress: (4, 4.2631642578125, {'server_test_acc': 0.1855}, 425.0367947318591)
INFO flwr 2023-08-15 15:28:05,626 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 15:28:16,738 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:29:07,223 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-15 15:29:07,453 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 15:29:07,567 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=520409)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=520407)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=520413)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=520414)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=520411)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=520412)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=520415)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=520416)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=520413)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=520412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520414)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520411)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520416)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520409)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=520407)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520415)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:29:50,662 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:29:50,662 | fed_df.py:547 | Average fusion training loss : 0.0061970638753846286, val accuracy : 0.22183999999999998, best val accuracy : 0.228
INFO flwr 2023-08-15 15:29:50,664 | common.py:35 | Avg. local train loss : 19.498082369565964, train acc : 0.3153222222222222
INFO flwr 2023-08-15 15:29:54,045 | server.py:116 | fit progress: (5, 4.240584741210937, {'server_test_acc': 0.2272}, 533.4555976218544)
INFO flwr 2023-08-15 15:29:54,045 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 15:30:05,252 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=670162)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=670165)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=670153)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=670159)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:30:55,682 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-15 15:30:55,910 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 15:30:56,029 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=670153)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=670162)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=670159)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=670164)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=670165)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=670163)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=670160)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=670166)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=670163)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=670164)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=670166)[0m double free or corruption (fasttop)
E0815 15:30:56.880606310  469714 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=670160)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:31:39,442 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:31:39,443 | fed_df.py:547 | Average fusion training loss : 0.0025823113803053275, val accuracy : 0.24632, best val accuracy : 0.2516
INFO flwr 2023-08-15 15:31:39,445 | common.py:35 | Avg. local train loss : 19.220962615311148, train acc : 0.3464416666666667
INFO flwr 2023-08-15 15:31:42,823 | server.py:116 | fit progress: (6, 4.299122900390625, {'server_test_acc': 0.2455}, 642.2339902017266)
INFO flwr 2023-08-15 15:31:42,823 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 15:31:53,901 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=819479)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:32:44,628 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-15 15:32:44,859 | fed_df.py:365 | Warm start at round 7
[2m[36m(launch_and_fit pid=819481)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=819485)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:32:44,973 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=819479)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=819481)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=819482)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=819482)[0m 
[2m[36m(launch_and_fit pid=819485)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=819488)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=819487)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=819484)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=819483)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=819488)[0m malloc_consolidate(): invalid chunk size
E0815 15:32:45.559924170  767635 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=819482)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=819484)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=819487)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=819483)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:33:32,824 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:33:32,824 | fed_df.py:547 | Average fusion training loss : 0.0012303562693996356, val accuracy : 0.26172, best val accuracy : 0.27
INFO flwr 2023-08-15 15:33:32,826 | common.py:35 | Avg. local train loss : 19.11400227546692, train acc : 0.3621083333333333
INFO flwr 2023-08-15 15:33:36,322 | server.py:116 | fit progress: (7, 4.331119873046875, {'server_test_acc': 0.2676}, 755.733395577874)
INFO flwr 2023-08-15 15:33:36,323 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 15:33:47,691 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1020867)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1020980)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:34:38,422 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 15:34:38,652 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 15:34:38,763 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1020867)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1020866)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1020865)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1020864)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1020980)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1021011)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1021009)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1021010)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1020866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021009)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1020864)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1020865)[0m malloc_consolidate(): invalid chunk size
E0815 15:34:40.432483856 1121949 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=1021011)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1021010)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:35:21,647 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:35:21,647 | fed_df.py:547 | Average fusion training loss : 0.0014673782783211208, val accuracy : 0.27224000000000004, best val accuracy : 0.2834
INFO flwr 2023-08-15 15:35:21,649 | common.py:35 | Avg. local train loss : 19.041977453231816, train acc : 0.37097777777777774
INFO flwr 2023-08-15 15:35:25,043 | server.py:116 | fit progress: (8, 4.332090905761719, {'server_test_acc': 0.2723}, 864.4536154810339)
INFO flwr 2023-08-15 15:35:25,043 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 15:35:36,358 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1170747)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1170735)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:36:27,189 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-15 15:36:27,420 | fed_df.py:365 | Warm start at round 9
[2m[36m(launch_and_fit pid=1170746)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:36:27,533 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1170747)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1170737)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1170748)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1170739)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1170738)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1170749)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1170746)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1170735)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1170739)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1170737)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1170749)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1170748)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1170738)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:37:11,502 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:37:11,503 | fed_df.py:547 | Average fusion training loss : 0.001196991246426478, val accuracy : 0.27076, best val accuracy : 0.281
INFO flwr 2023-08-15 15:37:11,504 | common.py:35 | Avg. local train loss : 18.948172551393508, train acc : 0.38355833333333333
INFO flwr 2023-08-15 15:37:14,949 | server.py:116 | fit progress: (9, 4.362375219726562, {'server_test_acc': 0.2691}, 974.3603954608552)
INFO flwr 2023-08-15 15:37:14,950 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 15:37:26,215 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:38:16,259 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-15 15:38:16,507 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 15:38:16,621 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1319700)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1319697)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1319706)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1319703)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1319699)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1319701)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1319705)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1319704)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1319699)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1319703)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1319697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1319704)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1319705)[0m malloc_consolidate(): invalid chunk size
E0815 15:38:18.167690633 1122475 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
E0815 15:38:18.167784853 1122475 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
E0815 15:38:18.167806370 1122475 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1319701)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1319700)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1319706)[0m malloc_consolidate(): invalid chunk size
E0815 15:38:50.103872105 1454942 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-15 15:39:01,019 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:39:01,019 | fed_df.py:547 | Average fusion training loss : 0.0012441732391016557, val accuracy : 0.27328, best val accuracy : 0.2856
INFO flwr 2023-08-15 15:39:01,021 | common.py:35 | Avg. local train loss : 18.85443461537361, train acc : 0.3970694444444444
INFO flwr 2023-08-15 15:39:04,630 | server.py:116 | fit progress: (10, 4.368644580078125, {'server_test_acc': 0.2773}, 1084.0406272346154)
INFO flwr 2023-08-15 15:39:04,630 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 15:39:16,381 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1468606)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1468604)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1468598)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:40:06,434 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-15 15:40:06,664 | fed_df.py:365 | Warm start at round 11
[2m[36m(launch_and_fit pid=1468605)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:40:06,779 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1468601)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1468598)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1468604)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1468605)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1468597)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1468606)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1468603)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1468602)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1468597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1468601)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1468603)[0m malloc_consolidate(): invalid chunk size
E0815 15:40:08.396034852 1569584 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=1468602)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:40:50,768 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:40:50,769 | fed_df.py:547 | Average fusion training loss : 0.0013316695718094706, val accuracy : 0.27928, best val accuracy : 0.2926
INFO flwr 2023-08-15 15:40:50,770 | common.py:35 | Avg. local train loss : 18.739279539883135, train acc : 0.4105944444444444
INFO flwr 2023-08-15 15:40:54,449 | server.py:116 | fit progress: (11, 4.371797277832031, {'server_test_acc': 0.2867}, 1193.859940782655)
INFO flwr 2023-08-15 15:40:54,449 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 15:41:05,666 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1618248)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:41:56,144 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-15 15:41:56,377 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 15:41:56,491 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1618246)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1618250)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1618247)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1618242)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1618249)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1618256)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1618255)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1618248)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1618242)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1618255)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1618256)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1618250)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1618246)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1618247)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1618249)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:42:45,360 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:42:45,360 | fed_df.py:547 | Average fusion training loss : 0.001335575696080923, val accuracy : 0.29124, best val accuracy : 0.3056
INFO flwr 2023-08-15 15:42:45,362 | common.py:35 | Avg. local train loss : 18.67483023405075, train acc : 0.4165555555555556
INFO flwr 2023-08-15 15:42:48,818 | server.py:116 | fit progress: (12, 4.3865015502929685, {'server_test_acc': 0.2943}, 1308.2288826699369)
INFO flwr 2023-08-15 15:42:48,818 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 15:43:00,580 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1777640)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:43:50,184 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 15:43:50,416 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 15:43:50,531 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1777642)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1777712)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1777777)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1777641)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1777778)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1777643)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1777640)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1777780)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1777778)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1777642)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777780)[0m double free or corruption (fasttop)
E0815 15:43:51.508474529 1872431 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=1777777)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1777712)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777643)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1777641)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:44:34,069 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:44:34,069 | fed_df.py:547 | Average fusion training loss : 0.0013740765964030289, val accuracy : 0.29668, best val accuracy : 0.3088
INFO flwr 2023-08-15 15:44:34,072 | common.py:35 | Avg. local train loss : 18.495452570915223, train acc : 0.4337888888888889
INFO flwr 2023-08-15 15:44:37,494 | server.py:116 | fit progress: (13, 4.419468310546875, {'server_test_acc': 0.2937}, 1416.9046919126995)
INFO flwr 2023-08-15 15:44:37,494 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 15:44:48,643 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1927058)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:45:39,074 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1926912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1926923)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1927057)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:45:39,307 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 15:45:39,422 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1927058)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1926918)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1926923)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1926912)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1927057)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1926916)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1926914)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1926924)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1926916)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1926924)[0m double free or corruption (fasttop)
E0815 15:45:40.405800365 2022220 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1926918)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1926914)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:46:23,615 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:46:23,616 | fed_df.py:547 | Average fusion training loss : 0.0013737699184566737, val accuracy : 0.30332, best val accuracy : 0.3186
INFO flwr 2023-08-15 15:46:23,618 | common.py:35 | Avg. local train loss : 18.6223646402359, train acc : 0.419325
INFO flwr 2023-08-15 15:46:27,237 | server.py:116 | fit progress: (14, 4.4066722900390625, {'server_test_acc': 0.3059}, 1526.6484505678527)
INFO flwr 2023-08-15 15:46:27,238 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 15:46:38,302 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:47:28,491 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-15 15:47:28,723 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-15 15:47:28,853 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2078325)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2078531)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2078506)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2078471)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2078735)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2078734)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2078737)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2078736)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2078735)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078734)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078471)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2078531)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078736)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078325)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2078506)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:48:13,438 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:48:13,438 | fed_df.py:547 | Average fusion training loss : 0.00175408022312331, val accuracy : 0.30267999999999995, best val accuracy : 0.3172
INFO flwr 2023-08-15 15:48:13,441 | common.py:35 | Avg. local train loss : 18.32586307674646, train acc : 0.45139166666666664
INFO flwr 2023-08-15 15:48:16,961 | server.py:116 | fit progress: (15, 4.418552282714844, {'server_test_acc': 0.307}, 1636.3719493118115)
INFO flwr 2023-08-15 15:48:16,961 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 15:48:28,460 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2269975)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2269705)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:49:19,166 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2269701)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:49:19,400 | fed_df.py:365 | Warm start at round 16
[2m[36m(launch_and_fit pid=2269976)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:49:19,534 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2269957)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2269697)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2269701)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2269705)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2269838)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2269956)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2269957)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2269975)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2269976)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2269956)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2269697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2269838)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:50:05,929 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:50:05,930 | fed_df.py:547 | Average fusion training loss : 0.002036282118933741, val accuracy : 0.30652, best val accuracy : 0.3194
INFO flwr 2023-08-15 15:50:05,933 | common.py:35 | Avg. local train loss : 18.246430300176144, train acc : 0.4562333333333333
INFO flwr 2023-08-15 15:50:09,406 | server.py:116 | fit progress: (16, 4.3925099975585935, {'server_test_acc': 0.3135}, 1748.8173624919727)
INFO flwr 2023-08-15 15:50:09,407 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 15:50:20,761 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:51:10,920 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2436004)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:51:11,156 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 15:51:11,269 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2436000)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2436007)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2436005)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2436006)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2436002)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2436003)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2436004)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2436001)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2436006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2436007)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2436003)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2436001)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2436000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2436002)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2436005)[0m malloc_consolidate(): invalid chunk size
E0815 15:51:21.956105372 2535277 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-15 15:51:55,604 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:51:55,604 | fed_df.py:547 | Average fusion training loss : 0.004012066918774508, val accuracy : 0.30111999999999994, best val accuracy : 0.3268
INFO flwr 2023-08-15 15:51:55,606 | common.py:35 | Avg. local train loss : 18.354426577687263, train acc : 0.4456472222222222
INFO flwr 2023-08-15 15:51:59,384 | server.py:116 | fit progress: (17, 4.2959953125, {'server_test_acc': 0.3177}, 1858.7949827159755)
INFO flwr 2023-08-15 15:51:59,384 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 15:52:10,699 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:53:01,286 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-15 15:53:01,515 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 15:53:01,630 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2587132)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2587399)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2587396)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2587013)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2587015)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2587183)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2587397)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2587398)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2587132)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2587396)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2587013)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2587397)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2587399)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2587183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2587015)[0m double free or corruption (fasttop)
E0815 15:53:03.378940609 2535982 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=2587398)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:53:46,440 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:53:46,440 | fed_df.py:547 | Average fusion training loss : 0.0028621973783301657, val accuracy : 0.31716000000000005, best val accuracy : 0.3264
INFO flwr 2023-08-15 15:53:46,442 | common.py:35 | Avg. local train loss : 18.165737935900687, train acc : 0.4542138888888889
INFO flwr 2023-08-15 15:53:50,061 | server.py:116 | fit progress: (18, 4.345653601074218, {'server_test_acc': 0.3236}, 1969.4725262490101)
INFO flwr 2023-08-15 15:53:50,062 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 15:54:01,279 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2738930)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2738810)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:54:52,643 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-15 15:54:52,873 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 15:54:52,988 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2738947)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2738812)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2738811)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2738810)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2738930)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2738929)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2738946)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2738932)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2738946)[0m malloc_consolidate(): invalid chunk size
E0815 15:54:53.866285969 2675592 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=2738932)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2738812)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2738929)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2738811)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:55:37,409 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:55:37,409 | fed_df.py:547 | Average fusion training loss : 0.0033665100630605595, val accuracy : 0.30952, best val accuracy : 0.3262
INFO flwr 2023-08-15 15:55:37,411 | common.py:35 | Avg. local train loss : 17.978436049818992, train acc : 0.4710555555555555
INFO flwr 2023-08-15 15:55:41,080 | server.py:116 | fit progress: (19, 4.307349841308594, {'server_test_acc': 0.3259}, 2080.4906948697753)
INFO flwr 2023-08-15 15:55:41,080 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 15:55:52,348 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2892318)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2892448)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2892464)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:56:43,349 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 15:56:43,595 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 15:56:43,745 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2892318)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2892448)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2892464)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2892316)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2892317)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2892319)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2892446)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2892467)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2892446)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2892467)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2892316)[0m double free or corruption (fasttop)
E0815 15:56:44.730385578 2973509 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=2892319)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:57:27,601 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:57:27,601 | fed_df.py:547 | Average fusion training loss : 0.0028564069679705424, val accuracy : 0.32639999999999997, best val accuracy : 0.3366
INFO flwr 2023-08-15 15:57:27,604 | common.py:35 | Avg. local train loss : 18.038505551218986, train acc : 0.4564694444444444
INFO flwr 2023-08-15 15:57:31,086 | server.py:116 | fit progress: (20, 4.355318139648437, {'server_test_acc': 0.3342}, 2190.496895447839)
INFO flwr 2023-08-15 15:57:31,086 | server.py:163 | evaluate_round 20: no clients selected, cancel
E0815 15:57:33.169852940 2973913 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:57:33.170321599 2973913 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
DEBUG flwr 2023-08-15 15:57:42,808 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3036542)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3036682)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:58:34,000 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-15 15:58:34,246 | fed_df.py:365 | Warm start at round 21
[2m[36m(launch_and_fit pid=3036545)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:58:34,380 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3036542)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3036681)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3036683)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3036400)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3036545)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3036543)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3036682)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3036544)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3036683)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3036544)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3036681)[0m malloc_consolidate(): invalid chunk size
E0815 15:58:35.058225013 3022868 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3036543)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:59:19,527 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:59:19,527 | fed_df.py:547 | Average fusion training loss : 0.002417395824508276, val accuracy : 0.3146, best val accuracy : 0.3274
INFO flwr 2023-08-15 15:59:19,530 | common.py:35 | Avg. local train loss : 17.84841139763594, train acc : 0.4752527777777778
INFO flwr 2023-08-15 15:59:23,234 | server.py:116 | fit progress: (21, 4.409758312988282, {'server_test_acc': 0.3267}, 2302.644989769906)
INFO flwr 2023-08-15 15:59:23,234 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 15:59:34,586 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:00:25,302 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3183764)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:00:25,536 | fed_df.py:365 | Warm start at round 22
[2m[36m(launch_and_fit pid=3183588)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:00:25,652 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3183589)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3183628)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3183627)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3183622)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3183764)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3183588)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3183762)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3183763)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3183762)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3183628)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3183622)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3183589)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3183627)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3183763)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:01:11,656 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:01:11,657 | fed_df.py:547 | Average fusion training loss : 0.002241919297433924, val accuracy : 0.31816000000000005, best val accuracy : 0.3296
INFO flwr 2023-08-15 16:01:11,659 | common.py:35 | Avg. local train loss : 17.96178155094385, train acc : 0.46543333333333337
INFO flwr 2023-08-15 16:01:15,104 | server.py:116 | fit progress: (22, 4.41506279296875, {'server_test_acc': 0.3252}, 2414.5146283167414)
INFO flwr 2023-08-15 16:01:15,104 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 16:01:26,185 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3334007)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3334146)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3334009)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3334145)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 16:02:17,584 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 16:02:17,813 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 16:02:17,925 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3334143)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3334007)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3334012)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3334146)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3334145)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3334009)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3333989)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3334013)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3334012)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3334143)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3334013)[0m double free or corruption (fasttop)
E0815 16:02:18.696870253 3272631 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3333989)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:03:03,851 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:03:03,852 | fed_df.py:547 | Average fusion training loss : 0.002067846931691747, val accuracy : 0.3224, best val accuracy : 0.331
INFO flwr 2023-08-15 16:03:03,854 | common.py:35 | Avg. local train loss : 17.874525183439257, train acc : 0.4769416666666667
INFO flwr 2023-08-15 16:03:07,577 | server.py:116 | fit progress: (23, 4.4129189697265625, {'server_test_acc': 0.3255}, 2526.9878800958395)
INFO flwr 2023-08-15 16:03:07,577 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 16:03:19,236 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3495190)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3495496)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3494991)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 16:04:11,602 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 16:04:11,839 | fed_df.py:365 | Warm start at round 24
[2m[36m(launch_and_fit pid=3495315)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:04:11,989 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3495152)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3495190)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3495502)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3495496)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3495239)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3495473)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3494991)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3495315)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3495502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3495473)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3495239)[0m malloc_consolidate(): invalid chunk size
E0815 16:04:12.664994941 3421444 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3495152)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:04:56,656 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:04:56,656 | fed_df.py:547 | Average fusion training loss : 0.002166442004730925, val accuracy : 0.31772, best val accuracy : 0.3342
INFO flwr 2023-08-15 16:04:56,658 | common.py:35 | Avg. local train loss : 17.754904040694235, train acc : 0.48640277777777774
INFO flwr 2023-08-15 16:05:00,263 | server.py:116 | fit progress: (24, 4.423724523925781, {'server_test_acc': 0.3313}, 2639.673617350869)
INFO flwr 2023-08-15 16:05:00,263 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 16:05:12,085 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3692568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3692248)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:06:02,872 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-15 16:06:03,107 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=3692693)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3692566)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:06:03,305 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3692693)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3692568)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3692695)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3692391)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3692248)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3692562)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3692563)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3692566)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3692695)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3692391)[0m malloc_consolidate(): invalid chunk size
E0815 16:06:04.202693004 3774523 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3692563)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:06:48,140 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:06:48,141 | fed_df.py:547 | Average fusion training loss : 0.0022827934125671163, val accuracy : 0.31828, best val accuracy : 0.332
INFO flwr 2023-08-15 16:06:48,143 | common.py:35 | Avg. local train loss : 17.735038447380063, train acc : 0.48888611111111113
INFO flwr 2023-08-15 16:06:51,765 | server.py:116 | fit progress: (25, 4.420536279296875, {'server_test_acc': 0.3271}, 2751.1760939667)
INFO flwr 2023-08-15 16:06:51,765 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 16:07:03,206 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:07:52,915 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3845483)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3845520)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:07:53,148 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 16:07:53,279 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3845384)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3845519)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3845520)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3845483)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3845518)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3845651)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3845652)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3845653)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3845651)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3845518)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3845652)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3845384)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3845519)[0m malloc_consolidate(): invalid chunk size
E0815 16:07:55.053783622 3925095 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3845653)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:08:38,394 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:08:38,395 | fed_df.py:547 | Average fusion training loss : 0.0028066366544808262, val accuracy : 0.31643999999999994, best val accuracy : 0.3274
INFO flwr 2023-08-15 16:08:38,397 | common.py:35 | Avg. local train loss : 17.794554619491098, train acc : 0.48191666666666666
INFO flwr 2023-08-15 16:08:42,164 | server.py:116 | fit progress: (26, 4.399959057617187, {'server_test_acc': 0.3324}, 2861.575122629758)
INFO flwr 2023-08-15 16:08:42,164 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 16:08:53,409 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:09:43,526 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 16:09:43,772 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-15 16:09:43,932 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3995966)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3995831)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3995989)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3995985)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3995987)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3995866)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3995839)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3995843)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3995843)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3995966)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3995985)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3995831)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3995866)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3995839)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3995987)[0m malloc_consolidate(): invalid chunk size
E0815 16:09:45.993198318 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:09:45.993275665 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:09:45.993285845 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:09:45.993293843 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:09:45.993301609 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:09:45.993309432 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:09:45.993317142 4074328 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3995989)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:10:29,938 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:10:29,939 | fed_df.py:547 | Average fusion training loss : 0.003859185368695762, val accuracy : 0.31808000000000003, best val accuracy : 0.3302
INFO flwr 2023-08-15 16:10:29,941 | common.py:35 | Avg. local train loss : 17.73225322961807, train acc : 0.4896527777777777
INFO flwr 2023-08-15 16:10:33,880 | server.py:116 | fit progress: (27, 4.407773254394531, {'server_test_acc': 0.33}, 2973.291388859041)
INFO flwr 2023-08-15 16:10:33,881 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 16:10:45,686 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4148666)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4148955)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:11:36,880 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4148954)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4148813)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:11:37,116 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-15 16:11:37,286 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4148661)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4148666)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4148813)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4148954)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4148955)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4148815)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4148816)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4148668)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4148668)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4148815)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4148661)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4148816)[0m double free or corruption (fasttop)
E0815 16:12:01.437189347 4075142 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 16:12:22,919 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:12:22,920 | fed_df.py:547 | Average fusion training loss : 0.00235749831359135, val accuracy : 0.32619999999999993, best val accuracy : 0.3356
INFO flwr 2023-08-15 16:12:22,922 | common.py:35 | Avg. local train loss : 17.597058565914633, train acc : 0.49605
INFO flwr 2023-08-15 16:12:26,440 | server.py:116 | fit progress: (28, 4.400229602050781, {'server_test_acc': 0.3344}, 3085.850850895047)
INFO flwr 2023-08-15 16:12:26,440 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 16:12:37,761 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:13:27,451 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 16:13:27,679 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-15 16:13:27,795 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=107428)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=107568)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=107572)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=107575)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=107567)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=107576)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=107430)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=107574)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=107568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=107567)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=107428)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=107574)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=107572)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=107575)[0m malloc_consolidate(): invalid chunk size
E0815 16:13:29.470401003   49163 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=107576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=107430)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:14:13,229 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:14:13,229 | fed_df.py:547 | Average fusion training loss : 0.002463122817338444, val accuracy : 0.32104, best val accuracy : 0.3348
INFO flwr 2023-08-15 16:14:13,231 | common.py:35 | Avg. local train loss : 17.646988336741924, train acc : 0.4911222222222222
INFO flwr 2023-08-15 16:14:16,767 | server.py:116 | fit progress: (29, 4.395197265625, {'server_test_acc': 0.3306}, 3196.1777995848097)
INFO flwr 2023-08-15 16:14:16,767 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 16:14:27,815 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=259115)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:15:17,523 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=258972)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:15:17,761 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 16:15:17,888 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=259091)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=259042)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=258972)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=259115)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=259114)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=259043)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=259044)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=258974)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=259114)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=259042)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=259091)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=258974)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=259043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=259044)[0m double free or corruption (fasttop)
E0815 16:15:19.635073398  185121 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:15:19.635649684  185121 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 16:15:19.635673393  185121 chttp2_transport.cc:1079]             ipv4:145.136.62.31:47091: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 16:16:03,088 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:16:03,089 | fed_df.py:547 | Average fusion training loss : 0.003247008000151254, val accuracy : 0.3278, best val accuracy : 0.338
INFO flwr 2023-08-15 16:16:03,091 | common.py:35 | Avg. local train loss : 17.546828646957874, train acc : 0.49921666666666664
INFO flwr 2023-08-15 16:16:06,617 | server.py:116 | fit progress: (30, 4.412168212890625, {'server_test_acc': 0.3273}, 3306.0284764417447)
INFO flwr 2023-08-15 16:16:06,618 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 16:16:06,618 | server.py:144 | FL finished in 3306.028867188841
INFO flwr 2023-08-15 16:16:06,618 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 16:16:06,619 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 16:16:06,619 | app.py:204 | app_fit: losses_centralized [(0, 4.655556018066406), (1, 4.375170275878906), (2, 4.378863000488281), (3, 4.347889074707031), (4, 4.2631642578125), (5, 4.240584741210937), (6, 4.299122900390625), (7, 4.331119873046875), (8, 4.332090905761719), (9, 4.362375219726562), (10, 4.368644580078125), (11, 4.371797277832031), (12, 4.3865015502929685), (13, 4.419468310546875), (14, 4.4066722900390625), (15, 4.418552282714844), (16, 4.3925099975585935), (17, 4.2959953125), (18, 4.345653601074218), (19, 4.307349841308594), (20, 4.355318139648437), (21, 4.409758312988282), (22, 4.41506279296875), (23, 4.4129189697265625), (24, 4.423724523925781), (25, 4.420536279296875), (26, 4.399959057617187), (27, 4.407773254394531), (28, 4.400229602050781), (29, 4.395197265625), (30, 4.412168212890625)]
INFO flwr 2023-08-15 16:16:06,619 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0107), (1, 0.0907), (2, 0.1242), (3, 0.1549), (4, 0.1855), (5, 0.2272), (6, 0.2455), (7, 0.2676), (8, 0.2723), (9, 0.2691), (10, 0.2773), (11, 0.2867), (12, 0.2943), (13, 0.2937), (14, 0.3059), (15, 0.307), (16, 0.3135), (17, 0.3177), (18, 0.3236), (19, 0.3259), (20, 0.3342), (21, 0.3267), (22, 0.3252), (23, 0.3255), (24, 0.3313), (25, 0.3271), (26, 0.3324), (27, 0.33), (28, 0.3344), (29, 0.3306), (30, 0.3273)]}
double free or corruption (fasttop)
srun: error: gcn31: task 0: Aborted
srun: Terminating StepId=3342168.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3342168
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:16:37
CPU Efficiency: 12.78% of 17:48:36 core-walltime
Job Wall-clock time: 00:59:22
Memory Utilized: 70.42 GB
Memory Efficiency: 58.68% of 120.00 GB
