-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:50000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:pathmnist
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:colonpath_sample.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=50000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/colonpath_sample.jpg', targetpath='/scratch-local/sunnys.3425372/1692490643_212476247', seed=42, img_per_thread=2777)
will save 50000 patches in /scratch-local/sunnys.3425372/1692490643_212476247/single_img_crops/crops
50000 took 0.93min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-20 02:18:37,221 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-20 02:18:37,221 | simulate.py:55 | Reading args from argument parser
Downloading https://zenodo.org/record/6496656/files/pathmnist.npz?download=1 to /scratch-local/sunnys.3425372/1692490643_212476247/pathmnist.npz
Generating unified pathmnist dataset
Class histogram for 0-th partition (alpha=1.0, 9 classes): [ 797  772  834   92   22  456  457 1046   24]
INFO flwr 2023-08-20 02:19:19,721 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-20 02:19:22,059	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-20 02:19:23,216 | app.py:179 | Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0, 'accelerator_type:A100': 1.0, 'memory': 103079215104.0, 'node:145.136.62.58': 1.0}
INFO flwr 2023-08-20 02:19:23,216 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-20 02:19:23,216 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-20 02:19:23,216 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-20 02:19:30,222 | server.py:91 | initial parameters (loss, other metrics): 2.1845225108367154, {'server_test_acc': 0.11030640668523677}
INFO flwr 2023-08-20 02:19:30,222 | server.py:101 | FL starting
DEBUG flwr 2023-08-20 02:19:36,074 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3934443)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:20:11,680 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-20 02:20:11,788 | fed_df.py:365 | Warm start at round 1
[2m[36m(launch_and_fit pid=3934445)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:20:11,877 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3934443)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3934442)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3934441)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3934446)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3934448)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3934447)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3934444)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3934445)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3934444)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3934447)[0m malloc_consolidate(): invalid chunk size
E0820 02:20:12.283930740 3985474 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=3934441)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3934446)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3934442)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3934448)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:20:57,084 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:20:57,084 | fed_df.py:547 | Average fusion training loss : 0.13281997162103654, val accuracy : 0.47698977323254776, best val accuracy : 0.5433526011560693
INFO flwr 2023-08-20 02:20:57,085 | common.py:35 | Avg. local train loss : 8.536411003768444, train acc : 0.7042469135802468
INFO flwr 2023-08-20 02:20:59,376 | server.py:116 | fit progress: (1, 2.3740727889504605, {'server_test_acc': 0.44749303621169917}, 89.15355434594676)
INFO flwr 2023-08-20 02:20:59,376 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-20 02:21:05,184 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:21:42,043 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4067818)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:21:42,184 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4067682)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4067587)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4067854)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4067682)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4067685)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4067643)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4067847)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4067818)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4067858)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4067587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4067858)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4067685)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4067643)[0m malloc_consolidate(): invalid chunk size
E0820 02:21:44.085989890 3985677 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=4067854)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=4067847)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:22:29,478 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:22:29,478 | fed_df.py:547 | Average fusion training loss : 0.04014521518349647, val accuracy : 0.4973988439306359, best val accuracy : 0.5773677189862161
INFO flwr 2023-08-20 02:22:29,479 | common.py:35 | Avg. local train loss : 7.5118507400155075, train acc : 0.7649907407407407
INFO flwr 2023-08-20 02:22:31,848 | server.py:116 | fit progress: (2, 2.021589658784999, {'server_test_acc': 0.6110027855153203}, 181.6256826929748)
INFO flwr 2023-08-20 02:22:31,848 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-20 02:22:37,801 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=7568)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7570)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:23:14,194 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=7574)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:23:14,336 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=7573)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7568)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=7570)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=7571)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=7572)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=7573)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=7574)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=7576)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=7575)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=7571)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7572)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=7575)[0m double free or corruption (fasttop)
E0820 02:23:17.984463217 4120829 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-20 02:24:01,752 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:24:01,752 | fed_df.py:547 | Average fusion training loss : 0.046015655755996705, val accuracy : 0.5067585593597155, best val accuracy : 0.5337927967985772
INFO flwr 2023-08-20 02:24:01,753 | common.py:35 | Avg. local train loss : 8.096571493893862, train acc : 0.7248179012345679
INFO flwr 2023-08-20 02:24:04,178 | server.py:116 | fit progress: (3, 2.433336158582427, {'server_test_acc': 0.6153203342618384}, 273.9562740577385)
INFO flwr 2023-08-20 02:24:04,179 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-20 02:24:10,069 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=141621)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=141624)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:24:46,057 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=141616)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:24:46,197 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=141617)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=141621)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=141622)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=141616)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=141623)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=141624)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=141625)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=141620)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=141622)[0m malloc_consolidate(): invalid chunk size
E0820 02:24:46.719248475   62480 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=141617)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=141623)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=141625)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=141620)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:25:33,746 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:25:33,747 | fed_df.py:547 | Average fusion training loss : 0.04037598494440317, val accuracy : 0.5409293019119609, best val accuracy : 0.5803690529124055
INFO flwr 2023-08-20 02:25:33,748 | common.py:35 | Avg. local train loss : 8.080304945260286, train acc : 0.7286265432098765
INFO flwr 2023-08-20 02:25:36,123 | server.py:116 | fit progress: (4, 3.117450382450497, {'server_test_acc': 0.5061281337047354}, 365.90143699292094)
INFO flwr 2023-08-20 02:25:36,124 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-20 02:25:42,058 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=275308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=275327)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:26:18,265 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=275328)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:26:18,376 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-20 02:26:18,463 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=275308)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=275350)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=275306)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=275330)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=275327)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=275328)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=275349)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=275329)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=275306)[0m double free or corruption (fasttop)
E0820 02:26:19.004040049  189088 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=275330)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=275349)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=275350)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=275329)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:27:06,320 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:27:06,320 | fed_df.py:547 | Average fusion training loss : 0.04205261899530888, val accuracy : 0.49946642952423304, best val accuracy : 0.5320142285460204
INFO flwr 2023-08-20 02:27:06,321 | common.py:35 | Avg. local train loss : 7.8327989526093, train acc : 0.7437438271604938
INFO flwr 2023-08-20 02:27:08,700 | server.py:116 | fit progress: (5, 3.736276050131965, {'server_test_acc': 0.4785515320334262}, 458.4775253450498)
INFO flwr 2023-08-20 02:27:08,700 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-20 02:27:14,622 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=408709)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=408707)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:27:50,707 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=408710)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:27:50,849 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=408707)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=408705)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=408712)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=408709)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=408708)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=408706)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=408710)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=408711)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=408706)[0m double free or corruption (fasttop)
E0820 02:27:51.540785639  454194 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=408711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=408708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=408705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=408712)[0m malloc_consolidate(): invalid chunk size
E0820 02:27:52.917196029  454465 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-20 02:28:38,851 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:28:38,852 | fed_df.py:547 | Average fusion training loss : 0.09850747409462929, val accuracy : 0.5281680746998666, best val accuracy : 0.6033792796798577
INFO flwr 2023-08-20 02:28:38,853 | common.py:35 | Avg. local train loss : 7.265342126786709, train acc : 0.7844722222222222
INFO flwr 2023-08-20 02:28:41,278 | server.py:116 | fit progress: (6, 1.5396811195734816, {'server_test_acc': 0.598050139275766}, 551.0558046200313)
INFO flwr 2023-08-20 02:28:41,278 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-20 02:28:47,211 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=541210)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=541212)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:29:23,196 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-20 02:29:23,338 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=541210)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=541211)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=541212)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=541213)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=541207)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=541214)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=541215)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=541216)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=541207)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541215)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=541216)[0m malloc_consolidate(): invalid chunk size
E0820 02:29:24.543016949  587064 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=541213)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=541211)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:30:11,226 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:30:11,226 | fed_df.py:547 | Average fusion training loss : 0.04578222242742777, val accuracy : 0.634481991996443, best val accuracy : 0.6558470431302801
INFO flwr 2023-08-20 02:30:11,227 | common.py:35 | Avg. local train loss : 7.456010641902686, train acc : 0.7675
INFO flwr 2023-08-20 02:30:13,625 | server.py:116 | fit progress: (7, 2.243804474727025, {'server_test_acc': 0.5910863509749303}, 643.402565647848)
INFO flwr 2023-08-20 02:30:13,625 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-20 02:30:19,630 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=678941)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:30:55,948 | server.py:229 | fit_round 8 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=678917)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:30:56,092 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=678944)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=678940)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=678941)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=678917)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=678918)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=678943)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=678919)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=678942)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=678943)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=678940)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=678918)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=678919)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=678944)[0m double free or corruption (fasttop)
E0820 02:30:57.564005796  588539 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=678942)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:31:44,540 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:31:44,540 | fed_df.py:547 | Average fusion training loss : 0.04921427777409554, val accuracy : 0.6681858603823921, best val accuracy : 0.694086260560249
INFO flwr 2023-08-20 02:31:44,541 | common.py:35 | Avg. local train loss : 7.276872970163821, train acc : 0.783429012345679
INFO flwr 2023-08-20 02:31:46,939 | server.py:116 | fit progress: (8, 1.344462575753087, {'server_test_acc': 0.7104456824512535}, 736.7170373867266)
INFO flwr 2023-08-20 02:31:46,939 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-20 02:31:52,926 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:32:29,283 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=838760)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:32:29,426 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=838764)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=838761)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=838760)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=838787)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=838784)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=838806)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=838805)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=838785)[0m Fitting Client 3
E0820 02:32:29.881113403  739850 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=838787)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=838764)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=838761)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=838784)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=838805)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=838785)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=838806)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:33:17,623 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:33:17,624 | fed_df.py:547 | Average fusion training loss : 0.06307047513127327, val accuracy : 0.6620720320142286, best val accuracy : 0.6728546020453535
INFO flwr 2023-08-20 02:33:17,625 | common.py:35 | Avg. local train loss : 7.470890612900258, train acc : 0.7712993827160494
INFO flwr 2023-08-20 02:33:20,034 | server.py:116 | fit progress: (9, 3.0804467513368654, {'server_test_acc': 0.7513927576601671}, 829.8115221709013)
INFO flwr 2023-08-20 02:33:20,034 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-20 02:33:26,168 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=972410)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:34:02,747 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=972414)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:34:02,859 | fed_df.py:365 | Warm start at round 10
[2m[36m(launch_and_fit pid=972408)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:34:02,951 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=972414)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=972407)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=972411)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=972406)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=972410)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=972412)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=972415)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=972408)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=972406)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=972407)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=972412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=972411)[0m malloc_consolidate(): invalid chunk size
E0820 02:34:05.046908211 1021375 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=972415)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-20 02:34:51,107 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:34:51,108 | fed_df.py:547 | Average fusion training loss : 0.05100489097088575, val accuracy : 0.6407959092930191, best val accuracy : 0.6920853712761227
INFO flwr 2023-08-20 02:34:51,109 | common.py:35 | Avg. local train loss : 7.403814516961574, train acc : 0.774827160493827
INFO flwr 2023-08-20 02:34:53,495 | server.py:116 | fit progress: (10, 2.416905572620275, {'server_test_acc': 0.6151810584958217}, 923.272964138072)
INFO flwr 2023-08-20 02:34:53,495 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-20 02:34:59,478 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1106205)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1106207)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:35:36,469 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-20 02:35:36,612 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1106209)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1106205)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1106228)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1106227)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1106207)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1106210)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1106226)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1106208)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1106227)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1106210)[0m double free or corruption (fasttop)
E0820 02:35:37.181428887 1022513 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1106209)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1106228)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1106226)[0m malloc_consolidate(): invalid chunk size
E0820 02:35:37.920784002 1154626 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=1106208)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:36:24,906 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:36:24,907 | fed_df.py:547 | Average fusion training loss : 0.03921206944435835, val accuracy : 0.6664072921298354, best val accuracy : 0.7079813250333482
INFO flwr 2023-08-20 02:36:24,908 | common.py:35 | Avg. local train loss : 6.985585626214743, train acc : 0.8020987654320988
INFO flwr 2023-08-20 02:36:27,371 | server.py:116 | fit progress: (11, 3.2156628879664004, {'server_test_acc': 0.7637883008356546}, 1017.1494284700602)
INFO flwr 2023-08-20 02:36:27,372 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-20 02:36:33,327 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1240305)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:37:09,356 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-20 02:37:09,499 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1240308)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1240305)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1240307)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1240304)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1240309)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1240311)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1240308)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1240306)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1240310)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1240309)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1240310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1240304)[0m double free or corruption (fasttop)
E0820 02:37:10.664203283 1155193 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=1240306)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1240307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1240311)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:37:57,909 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:37:57,909 | fed_df.py:547 | Average fusion training loss : 0.0616156422495842, val accuracy : 0.6081369497554469, best val accuracy : 0.6462872387727879
INFO flwr 2023-08-20 02:37:57,910 | common.py:35 | Avg. local train loss : 6.744134635478258, train acc : 0.8189475308641976
INFO flwr 2023-08-20 02:38:00,327 | server.py:116 | fit progress: (12, 3.8538061380386353, {'server_test_acc': 0.5671309192200558}, 1110.1053651347756)
INFO flwr 2023-08-20 02:38:00,328 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-20 02:38:06,286 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1373510)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:38:42,356 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-20 02:38:42,499 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1373510)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1373596)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1373665)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1373491)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1373666)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1373667)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1373457)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1373597)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1373491)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1373666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1373597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1373596)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1373665)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1373457)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1373667)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:39:36,172 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:39:36,172 | fed_df.py:547 | Average fusion training loss : 0.12261049151420593, val accuracy : 0.6394619831036017, best val accuracy : 0.6903068030235661
INFO flwr 2023-08-20 02:39:36,174 | common.py:35 | Avg. local train loss : 6.967864506691694, train acc : 0.8029444444444445
INFO flwr 2023-08-20 02:39:38,600 | server.py:116 | fit progress: (13, 5.045491772840282, {'server_test_acc': 0.6842618384401115}, 1208.3783591059037)
INFO flwr 2023-08-20 02:39:38,601 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-20 02:39:44,577 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1507416)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:40:22,151 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-20 02:40:22,295 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1507418)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1507416)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1507415)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1507417)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1507419)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1507421)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1507420)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1507423)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1507417)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1507419)[0m double free or corruption (fasttop)
E0820 02:40:22.928919371 1558253 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1507415)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1507421)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1507418)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1507420)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:41:10,162 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:41:10,163 | fed_df.py:547 | Average fusion training loss : 0.09308734373748302, val accuracy : 0.45929301911960874, best val accuracy : 0.5347932414406403
INFO flwr 2023-08-20 02:41:10,164 | common.py:35 | Avg. local train loss : 7.150745162367819, train acc : 0.790179012345679
INFO flwr 2023-08-20 02:41:12,569 | server.py:116 | fit progress: (14, 3.8089061104819635, {'server_test_acc': 0.5327298050139275}, 1302.347429629881)
INFO flwr 2023-08-20 02:41:12,570 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-20 02:41:18,515 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:41:54,270 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1639918)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:41:54,382 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-20 02:41:54,471 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1639849)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1639919)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1639848)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1639920)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1639918)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1639922)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1639846)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1639921)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1639849)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1639922)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1639920)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1639848)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1639921)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1639846)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1639919)[0m double free or corruption (fasttop)
E0820 02:42:26.856919271 1734803 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-20 02:42:42,570 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:42:42,571 | fed_df.py:547 | Average fusion training loss : 0.2234653912782669, val accuracy : 0.47799021787461093, best val accuracy : 0.5977100933748333
INFO flwr 2023-08-20 02:42:42,572 | common.py:35 | Avg. local train loss : 7.164014152437447, train acc : 0.7904074074074074
INFO flwr 2023-08-20 02:42:44,966 | server.py:116 | fit progress: (15, 2.930731683454806, {'server_test_acc': 0.6190807799442897}, 1394.7441788697615)
INFO flwr 2023-08-20 02:42:44,966 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-20 02:42:51,014 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1772975)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:43:26,695 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1772977)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:43:26,838 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1772975)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1772976)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1772977)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1773046)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1773049)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1773047)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1772978)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1773048)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1773047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1772978)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=1773046)[0m malloc_consolidate(): invalid chunk size
E0820 02:43:28.263204050 1819634 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1773049)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1773048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1772976)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:44:15,740 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:44:15,740 | fed_df.py:547 | Average fusion training loss : 0.05537476865947247, val accuracy : 0.5945531347265451, best val accuracy : 0.628501556247221
INFO flwr 2023-08-20 02:44:15,741 | common.py:35 | Avg. local train loss : 7.032396197319031, train acc : 0.7989444444444445
INFO flwr 2023-08-20 02:44:18,136 | server.py:116 | fit progress: (16, 3.0750140450459003, {'server_test_acc': 0.5986072423398329}, 1487.9142852770165)
INFO flwr 2023-08-20 02:44:18,137 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-20 02:44:24,127 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1906230)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:45:00,079 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-20 02:45:00,224 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1906157)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1906229)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1906221)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1906227)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1906155)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1906230)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1906192)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1906228)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1906221)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1906155)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1906228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1906227)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1906229)[0m malloc_consolidate(): invalid chunk size
E0820 02:45:01.377687692 1820461 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1906192)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1906157)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:45:49,016 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:45:49,016 | fed_df.py:547 | Average fusion training loss : 0.07966171926259995, val accuracy : 0.7104046242774567, best val accuracy : 0.7321031569586482
INFO flwr 2023-08-20 02:45:49,017 | common.py:35 | Avg. local train loss : 6.858886841684579, train acc : 0.8085895061728396
INFO flwr 2023-08-20 02:45:51,485 | server.py:116 | fit progress: (17, 2.7165322258611906, {'server_test_acc': 0.6427576601671309}, 1581.2628634069115)
INFO flwr 2023-08-20 02:45:51,485 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-20 02:45:57,567 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:46:32,907 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-20 02:46:33,049 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2044190)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2044258)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2044259)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2044260)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2044189)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2044183)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2044261)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2044262)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2044190)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2044259)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2044262)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2044262)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2044183)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2044189)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2044260)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2044258)[0m malloc_consolidate(): invalid chunk size
E0820 02:46:35.062807403 1953034 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2044261)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2044261)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:47:22,429 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:47:22,429 | fed_df.py:547 | Average fusion training loss : 0.07358398312330246, val accuracy : 0.7083592707870164, best val accuracy : 0.7556691863050244
INFO flwr 2023-08-20 02:47:22,430 | common.py:35 | Avg. local train loss : 6.712014140933752, train acc : 0.8162654320987655
INFO flwr 2023-08-20 02:47:24,808 | server.py:116 | fit progress: (18, 1.5915093726102356, {'server_test_acc': 0.7824512534818941}, 1674.5864627300762)
INFO flwr 2023-08-20 02:47:24,809 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-20 02:47:30,931 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2201606)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:48:06,299 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-20 02:48:06,440 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2201606)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2201608)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2201611)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2201610)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2201613)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2201612)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2201609)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2201614)[0m Fitting Client 3
E0820 02:48:06.881303819 2244552 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2201608)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2201614)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2201611)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2201609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2201610)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2201613)[0m malloc_consolidate(): invalid chunk size
E0820 02:48:07.877538891 2245897 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2201612)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:48:55,626 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:48:55,626 | fed_df.py:547 | Average fusion training loss : 0.03635867840796709, val accuracy : 0.7546909737661183, best val accuracy : 0.7814584259670965
INFO flwr 2023-08-20 02:48:55,627 | common.py:35 | Avg. local train loss : 6.673838278651237, train acc : 0.8207654320987655
INFO flwr 2023-08-20 02:48:58,128 | server.py:116 | fit progress: (19, 4.065003432271208, {'server_test_acc': 0.7732590529247911}, 1767.9061648729257)
INFO flwr 2023-08-20 02:48:58,128 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-20 02:49:04,166 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2335235)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2335315)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:49:39,797 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-20 02:49:39,907 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-20 02:49:39,995 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2335235)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2335309)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2335313)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2335310)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2335311)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2335312)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2335315)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2335314)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2335309)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2335310)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2335311)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2335314)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2335313)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2335312)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:50:28,951 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:50:28,951 | fed_df.py:547 | Average fusion training loss : 0.11059251528978348, val accuracy : 0.6907514450867052, best val accuracy : 0.7869052912405513
INFO flwr 2023-08-20 02:50:28,952 | common.py:35 | Avg. local train loss : 6.866392918676137, train acc : 0.8126141975308643
INFO flwr 2023-08-20 02:50:31,372 | server.py:116 | fit progress: (20, 1.6372234926914437, {'server_test_acc': 0.7579387186629526}, 1861.1500843428075)
INFO flwr 2023-08-20 02:50:31,372 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-20 02:50:37,420 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2468830)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2468833)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:51:13,211 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-20 02:51:13,354 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2468830)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2468829)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2468832)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2468833)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2468820)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2468835)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2468834)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2468836)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2468836)[0m double free or corruption (fasttop)
E0820 02:51:13.729832950 2247989 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2468829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2468834)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2468835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2468820)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2468832)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:52:02,755 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:52:02,755 | fed_df.py:547 | Average fusion training loss : 0.029809918209910392, val accuracy : 0.7345486883059137, best val accuracy : 0.7528901734104047
INFO flwr 2023-08-20 02:52:02,756 | common.py:35 | Avg. local train loss : 6.329222217947245, train acc : 0.8411358024691357
INFO flwr 2023-08-20 02:52:05,199 | server.py:116 | fit progress: (21, 3.479670715066384, {'server_test_acc': 0.7080779944289693}, 1954.9766599610448)
INFO flwr 2023-08-20 02:52:05,199 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-20 02:52:11,319 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:52:46,502 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2602669)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:52:46,663 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2602666)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2602669)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2602668)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2602673)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2602667)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2602675)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2602665)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2602674)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2602666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2602668)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2602673)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2602665)[0m malloc_consolidate(): invalid chunk size
E0820 02:52:47.985698506 2647808 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 02:52:47.985849589 2647808 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0820 02:52:47.985867684 2647808 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2602675)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2602667)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2602674)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:53:36,331 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:53:36,331 | fed_df.py:547 | Average fusion training loss : 0.06282521279156209, val accuracy : 0.748421520675856, best val accuracy : 0.796242774566474
INFO flwr 2023-08-20 02:53:36,332 | common.py:35 | Avg. local train loss : 6.495231945067643, train acc : 0.8359104938271604
INFO flwr 2023-08-20 02:53:38,779 | server.py:116 | fit progress: (22, 2.414591474851858, {'server_test_acc': 0.7371866295264624}, 2048.5572012956254)
INFO flwr 2023-08-20 02:53:38,779 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-20 02:53:44,898 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:54:20,221 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2736217)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:54:20,365 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2736219)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2736217)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2736218)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2736222)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2736224)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2736223)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2736220)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2736221)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2736221)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2736218)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2736219)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2736223)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2736220)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2736224)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2736222)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:55:09,491 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:55:09,492 | fed_df.py:547 | Average fusion training loss : 0.046746498219668864, val accuracy : 0.6857936860827034, best val accuracy : 0.713983992885727
INFO flwr 2023-08-20 02:55:09,493 | common.py:35 | Avg. local train loss : 6.468371549248696, train acc : 0.834179012345679
INFO flwr 2023-08-20 02:55:11,939 | server.py:116 | fit progress: (23, 2.316682402868457, {'server_test_acc': 0.6873259052924791}, 2141.7174930479378)
INFO flwr 2023-08-20 02:55:11,940 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-20 02:55:18,042 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2866566)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 02:55:52,508 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2866639)[0m double free or corruption (fasttop)
INFO flwr 2023-08-20 02:55:52,653 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2866566)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2866638)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2866636)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2866635)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2866695)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2866637)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2866639)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2866708)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2866638)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2866708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2866695)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2866635)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2866637)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2866636)[0m malloc_consolidate(): invalid chunk size
E0820 02:56:09.625244393 2648288 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:56:42,040 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:56:42,041 | fed_df.py:547 | Average fusion training loss : 0.09412543493509293, val accuracy : 0.720386838594931, best val accuracy : 0.7984659848821698
INFO flwr 2023-08-20 02:56:42,042 | common.py:35 | Avg. local train loss : 6.591736942529678, train acc : 0.8283487654320987
INFO flwr 2023-08-20 02:56:44,497 | server.py:116 | fit progress: (24, 3.0475118792156657, {'server_test_acc': 0.7632311977715878}, 2234.275039295666)
INFO flwr 2023-08-20 02:56:44,497 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-20 02:56:50,582 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2999597)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 02:57:24,758 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-20 02:57:24,870 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-20 02:57:24,960 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2999599)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999597)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2999599)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2999600)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2999602)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2999601)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2999603)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2999586)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2999598)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2999601)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2999586)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999603)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999602)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999598)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 02:58:14,407 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:58:14,407 | fed_df.py:547 | Average fusion training loss : 0.0482314076051116, val accuracy : 0.7892174299688751, best val accuracy : 0.8134726545131169
INFO flwr 2023-08-20 02:58:14,408 | common.py:35 | Avg. local train loss : 6.448774948716164, train acc : 0.8350524691358024
INFO flwr 2023-08-20 02:58:16,851 | server.py:116 | fit progress: (25, 4.828483564209473, {'server_test_acc': 0.756824512534819}, 2326.6289386078715)
INFO flwr 2023-08-20 02:58:16,851 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-20 02:58:22,900 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 02:58:56,949 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-20 02:58:57,107 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3132813)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3132817)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3132818)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3132814)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3132815)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3132816)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3132779)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3132812)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3132812)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132779)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132816)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132813)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132818)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132814)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3132817)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3132815)[0m malloc_consolidate(): invalid chunk size
E0820 02:58:59.816820690 2938723 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 02:59:46,266 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 02:59:46,266 | fed_df.py:547 | Average fusion training loss : 0.03875088642537594, val accuracy : 0.7922632281013785, best val accuracy : 0.8083592707870164
INFO flwr 2023-08-20 02:59:46,268 | common.py:35 | Avg. local train loss : 6.102792363613844, train acc : 0.8550555555555556
INFO flwr 2023-08-20 02:59:48,714 | server.py:116 | fit progress: (26, 3.3883738514440638, {'server_test_acc': 0.7332869080779945}, 2418.4916421198286)
INFO flwr 2023-08-20 02:59:48,714 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-20 02:59:54,805 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3265433)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-20 03:00:28,973 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-20 03:00:29,115 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3265435)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3265432)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3265433)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3265434)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3265439)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3265437)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3265438)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3265436)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3265435)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3265432)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3265436)[0m malloc_consolidate(): invalid chunk size
E0820 03:00:29.823676909 3306094 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3265438)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3265439)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3265437)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3265434)[0m malloc_consolidate(): invalid chunk size
E0820 03:01:07.833016839 3375159 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 03:01:19,377 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 03:01:19,377 | fed_df.py:547 | Average fusion training loss : 0.05031763306260109, val accuracy : 0.7454201867496666, best val accuracy : 0.7887950200088928
INFO flwr 2023-08-20 03:01:19,378 | common.py:35 | Avg. local train loss : 6.376029759645462, train acc : 0.8414938271604938
INFO flwr 2023-08-20 03:01:21,854 | server.py:116 | fit progress: (27, 4.621286620668714, {'server_test_acc': 0.7341225626740947}, 2511.6323304129764)
INFO flwr 2023-08-20 03:01:21,855 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-20 03:01:28,004 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3416593)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 03:02:01,918 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-20 03:02:02,060 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3416592)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3416522)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3416594)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3416591)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3416523)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3416596)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3416595)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3416593)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3416592)[0m double free or corruption (fasttop)
E0820 03:02:02.677907700 3376893 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3416596)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3416522)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3416591)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3416523)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3416594)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3416595)[0m malloc_consolidate(): invalid chunk size
E0820 03:02:04.603171245 3466918 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 03:02:51,876 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 03:02:51,877 | fed_df.py:547 | Average fusion training loss : 0.029261277057230473, val accuracy : 0.7388394842152067, best val accuracy : 0.7626722987994664
INFO flwr 2023-08-20 03:02:51,878 | common.py:35 | Avg. local train loss : 6.4013056345283985, train acc : 0.8400123456790124
INFO flwr 2023-08-20 03:02:54,340 | server.py:116 | fit progress: (28, 4.0902282883529875, {'server_test_acc': 0.6735376044568245}, 2604.1177669088356)
INFO flwr 2023-08-20 03:02:54,340 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-20 03:03:00,448 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-20 03:03:34,231 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-20 03:03:34,389 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3560478)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3560476)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3560480)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3560549)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3560550)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3560548)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3560479)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3560551)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3560476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3560478)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3560549)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3560548)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3560551)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3560480)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3560550)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=3560479)[0m double free or corruption (fasttop)
E0820 03:03:38.065008597 3467489 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-20 03:04:24,177 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 03:04:24,177 | fed_df.py:547 | Average fusion training loss : 0.0460709265768528, val accuracy : 0.7586705202312138, best val accuracy : 0.7812361049355269
INFO flwr 2023-08-20 03:04:24,178 | common.py:35 | Avg. local train loss : 6.411001510173081, train acc : 0.8381203703703703
INFO flwr 2023-08-20 03:04:26,763 | server.py:116 | fit progress: (29, 4.093898244953421, {'server_test_acc': 0.6481894150417827}, 2696.540932924021)
INFO flwr 2023-08-20 03:04:26,763 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-20 03:04:32,916 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3689157)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-20 03:05:07,353 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-20 03:05:07,465 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-20 03:05:07,555 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3689157)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3689159)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3689230)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3689228)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3689227)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3689231)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3689229)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3689232)[0m Fitting Client 2
E0820 03:05:07.945796744 3606057 chttp2_transport.cc:1079]             ipv4:145.136.62.58:56031: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3689231)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3689232)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3689227)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3689230)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3689228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3689159)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3689229)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-20 03:06:02,470 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-20 03:06:02,470 | fed_df.py:547 | Average fusion training loss : 0.04629360488802194, val accuracy : 0.7805469097376612, best val accuracy : 0.8032458870609159
INFO flwr 2023-08-20 03:06:02,471 | common.py:35 | Avg. local train loss : 6.427711077779532, train acc : 0.8395462962962962
INFO flwr 2023-08-20 03:06:04,926 | server.py:116 | fit progress: (30, 4.277764358892414, {'server_test_acc': 0.791782729805014}, 2794.7042742460035)
INFO flwr 2023-08-20 03:06:04,927 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-20 03:06:04,927 | server.py:144 | FL finished in 2794.704658593051
INFO flwr 2023-08-20 03:06:04,927 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-20 03:06:04,928 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-20 03:06:04,928 | app.py:204 | app_fit: losses_centralized [(0, 2.1845225108367154), (1, 2.3740727889504605), (2, 2.021589658784999), (3, 2.433336158582427), (4, 3.117450382450497), (5, 3.736276050131965), (6, 1.5396811195734816), (7, 2.243804474727025), (8, 1.344462575753087), (9, 3.0804467513368654), (10, 2.416905572620275), (11, 3.2156628879664004), (12, 3.8538061380386353), (13, 5.045491772840282), (14, 3.8089061104819635), (15, 2.930731683454806), (16, 3.0750140450459003), (17, 2.7165322258611906), (18, 1.5915093726102356), (19, 4.065003432271208), (20, 1.6372234926914437), (21, 3.479670715066384), (22, 2.414591474851858), (23, 2.316682402868457), (24, 3.0475118792156657), (25, 4.828483564209473), (26, 3.3883738514440638), (27, 4.621286620668714), (28, 4.0902282883529875), (29, 4.093898244953421), (30, 4.277764358892414)]
INFO flwr 2023-08-20 03:06:04,928 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.11030640668523677), (1, 0.44749303621169917), (2, 0.6110027855153203), (3, 0.6153203342618384), (4, 0.5061281337047354), (5, 0.4785515320334262), (6, 0.598050139275766), (7, 0.5910863509749303), (8, 0.7104456824512535), (9, 0.7513927576601671), (10, 0.6151810584958217), (11, 0.7637883008356546), (12, 0.5671309192200558), (13, 0.6842618384401115), (14, 0.5327298050139275), (15, 0.6190807799442897), (16, 0.5986072423398329), (17, 0.6427576601671309), (18, 0.7824512534818941), (19, 0.7732590529247911), (20, 0.7579387186629526), (21, 0.7080779944289693), (22, 0.7371866295264624), (23, 0.6873259052924791), (24, 0.7632311977715878), (25, 0.756824512534819), (26, 0.7332869080779945), (27, 0.7341225626740947), (28, 0.6735376044568245), (29, 0.6481894150417827), (30, 0.791782729805014)]}
double free or corruption (fasttop)
srun: error: gcn58: task 0: Aborted
srun: Terminating StepId=3425372.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3425372
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:59:07
CPU Efficiency: 12.68% of 15:39:36 core-walltime
Job Wall-clock time: 00:52:12
Memory Utilized: 50.84 GB
Memory Efficiency: 42.37% of 120.00 GB
