-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:5000
STRATEGY:feddf
MODEL_NAME:resnet8
MODEL_LIST:{'resnet8':7,'wresnet-16-4':7,'resnet20':6}
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
SERVER_STEPS_ADAPTIVE:False
SERVER_STEPS_ADAPTIVE_MIN:100
SERVER_STEPS_ADAPTIVE_INTERVAL:5
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:False
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
Simulating feddf training
INFO simulate 2023-09-27 01:40:04,466 | simulate.py:51 | Python script started : simulate.py
DEBUG simulate 2023-09-27 01:40:04,466 | simulate.py:56 | Reading args from argument parser
INFO flwr 2023-09-27 01:40:25,853 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-27 01:40:29,556	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-27 01:40:30,653 | app.py:179 | Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'accelerator_type:A100': 1.0, 'CPU': 18.0, 'node:145.136.62.8': 1.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-09-27 01:40:30,654 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-27 01:40:30,654 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-09-27 01:40:30,654 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3935200/1695771593_648564146/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3935200/1695771593_648564146/cifar-10-python.tar.gz to /scratch-local/sunnys.3935200/1695771593_648564146
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [342 114 363 765  49 204 467  25  55 116]
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3935200/1695771593_648564146/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3935200/1695771593_648564146/cifar-100-python.tar.gz to /scratch-local/sunnys.3935200/1695771593_648564146
INFO flwr 2023-09-27 01:40:34,317 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-09-27 01:40:34,317 | server.py:101 | FL starting
DEBUG flwr 2023-09-27 01:40:37,798 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1972715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1972710)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:41:48,314 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-27 01:41:48,420 | fed_df.py:367 | Warm start at round 1
INFO flwr 2023-09-27 01:41:48,672 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1972709)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1972715)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1972714)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1972716)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1972710)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1972712)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1972713)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1972711)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1972711)[0m double free or corruption (fasttop)
E0927 01:41:49.075196079 2069553 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=1972712)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1972714)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1972716)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1972713)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1972709)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 01:42:11,155 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:42:11,155 | fed_df.py:552 | Average fusion training loss : 0.046702791711315514, val accuracy : 0.37852727272727266, best val accuracy : 0.4792
INFO flwr 2023-09-27 01:42:11,156 | common.py:35 | Avg. local train loss : 6.90192433707416, train acc : 0.5805
INFO flwr 2023-09-27 01:42:14,107 | server.py:116 | fit progress: (1, 1.5174114990234375, {'server_test_acc': 0.4763}, 99.79010311100865)
INFO flwr 2023-09-27 01:42:14,108 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-09-27 01:42:17,159 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2085859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2085858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2085863)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:43:27,309 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-27 01:43:27,416 | fed_df.py:367 | Warm start at round 2
INFO flwr 2023-09-27 01:43:27,512 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2085862)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2085858)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2085859)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2085863)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2085861)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2085865)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2085864)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2085860)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2085864)[0m malloc_consolidate(): invalid chunk size
E0927 01:43:27.933935511 2070075 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2085861)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2085860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2085865)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2085862)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:43:50,118 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:43:50,119 | fed_df.py:552 | Average fusion training loss : 0.025148431431502104, val accuracy : 0.5103272727272726, best val accuracy : 0.5492
INFO flwr 2023-09-27 01:43:50,120 | common.py:35 | Avg. local train loss : 5.220829845964909, train acc : 0.753426388888889
INFO flwr 2023-09-27 01:43:53,035 | server.py:116 | fit progress: (2, 1.4816364349365234, {'server_test_acc': 0.5397}, 198.71759028898668)
INFO flwr 2023-09-27 01:43:53,035 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-09-27 01:43:56,133 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2199268)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2199267)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2199217)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 01:45:06,017 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-27 01:45:06,124 | fed_df.py:367 | Warm start at round 3
INFO flwr 2023-09-27 01:45:06,220 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2199217)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2199264)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2199262)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2199268)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2199263)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2199266)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2199265)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2199267)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2199265)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2199264)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2199266)[0m malloc_consolidate(): invalid chunk size
E0927 01:45:07.385461590 2183640 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=2199262)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2199263)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:45:28,654 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:45:28,655 | fed_df.py:552 | Average fusion training loss : 0.03384086255822331, val accuracy : 0.5122545454545454, best val accuracy : 0.5646
INFO flwr 2023-09-27 01:45:28,656 | common.py:35 | Avg. local train loss : 4.589665439911187, train acc : 0.8216249999999998
INFO flwr 2023-09-27 01:45:31,670 | server.py:116 | fit progress: (3, 1.5176260192871094, {'server_test_acc': 0.5596}, 297.3524720160058)
INFO flwr 2023-09-27 01:45:31,670 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-09-27 01:45:34,704 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2313318)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2313314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2313320)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:46:44,528 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-27 01:46:44,635 | fed_df.py:367 | Warm start at round 4
INFO flwr 2023-09-27 01:46:44,731 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2313314)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2313312)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2313310)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2313317)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2313319)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2313318)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2313321)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2313320)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2313319)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2313321)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2313310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2313312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2313317)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:47:07,038 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:47:07,039 | fed_df.py:552 | Average fusion training loss : 0.023425886386074127, val accuracy : 0.5910000000000001, best val accuracy : 0.6224
INFO flwr 2023-09-27 01:47:07,040 | common.py:35 | Avg. local train loss : 4.313188540749252, train acc : 0.8540638888888888
INFO flwr 2023-09-27 01:47:10,068 | server.py:116 | fit progress: (4, 1.5573885955810547, {'server_test_acc': 0.6131}, 395.7511127500038)
INFO flwr 2023-09-27 01:47:10,069 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-09-27 01:47:13,262 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2426686)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426885)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426887)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:48:23,028 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2426685)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2426753)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:48:23,137 | fed_df.py:367 | Warm start at round 5
INFO flwr 2023-09-27 01:48:23,235 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2426685)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2426753)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2426686)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2426819)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2426820)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2426885)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2426887)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2426886)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2426820)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2426886)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2426819)[0m malloc_consolidate(): invalid chunk size
E0927 01:48:25.979309522 2527228 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
E0927 01:48:25.979406296 2527228 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-09-27 01:48:45,400 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:48:45,400 | fed_df.py:552 | Average fusion training loss : 0.026892543783411382, val accuracy : 0.6149272727272727, best val accuracy : 0.6628
INFO flwr 2023-09-27 01:48:45,402 | common.py:35 | Avg. local train loss : 4.040253358334303, train acc : 0.8825236111111112
INFO flwr 2023-09-27 01:48:48,276 | server.py:116 | fit progress: (5, 1.534094140625, {'server_test_acc': 0.6472}, 493.9589912589872)
INFO flwr 2023-09-27 01:48:48,277 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-09-27 01:48:51,309 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2540833)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:50:01,245 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-09-27 01:50:01,358 | fed_df.py:367 | Warm start at round 6
INFO flwr 2023-09-27 01:50:01,466 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2540806)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2540803)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2540809)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2540810)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2540829)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2540831)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2540833)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2540832)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2540803)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540831)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540810)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540829)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2540806)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2540809)[0m double free or corruption (fasttop)
E0927 01:50:03.141115603 2638992 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2540832)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:50:24,148 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:50:24,149 | fed_df.py:552 | Average fusion training loss : 0.02634319225139916, val accuracy : 0.5503090909090909, best val accuracy : 0.5958
INFO flwr 2023-09-27 01:50:24,150 | common.py:35 | Avg. local train loss : 3.788259746693075, train acc : 0.9068916666666667
INFO flwr 2023-09-27 01:50:27,034 | server.py:116 | fit progress: (6, 1.512862173461914, {'server_test_acc': 0.58}, 592.7171035619976)
INFO flwr 2023-09-27 01:50:27,035 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-09-27 01:50:30,253 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2653658)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2653666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2653665)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2653664)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 01:51:40,257 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2653667)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 01:51:40,365 | fed_df.py:367 | Warm start at round 7
INFO flwr 2023-09-27 01:51:40,464 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2653658)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2653666)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2653664)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2653665)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2653667)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2653663)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2653662)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2653668)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2653662)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2653663)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2653668)[0m double free or corruption (fasttop)
E0927 01:51:42.171518076 2639643 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-09-27 01:52:02,862 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:52:02,863 | fed_df.py:552 | Average fusion training loss : 0.022213198109529913, val accuracy : 0.6502545454545454, best val accuracy : 0.6836
INFO flwr 2023-09-27 01:52:02,864 | common.py:35 | Avg. local train loss : 3.958965566754341, train acc : 0.8966402777777778
INFO flwr 2023-09-27 01:52:05,760 | server.py:116 | fit progress: (7, 1.492459323120117, {'server_test_acc': 0.6752}, 691.4431577289943)
INFO flwr 2023-09-27 01:52:05,761 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-09-27 01:52:08,816 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2767948)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 01:53:18,263 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-09-27 01:53:18,370 | fed_df.py:367 | Warm start at round 8
INFO flwr 2023-09-27 01:53:18,467 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2767941)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2767944)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2767942)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2767947)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2767949)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2767945)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2767946)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2767948)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2767942)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2767941)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2767944)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2767949)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2767946)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2767945)[0m malloc_consolidate(): invalid chunk size
E0927 01:53:19.863905301 2866488 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
E0927 01:53:19.864002081 2866488 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
E0927 01:53:19.864017895 2866488 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=2767947)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:53:41,219 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:53:41,219 | fed_df.py:552 | Average fusion training loss : 0.021912168879061937, val accuracy : 0.6552727272727273, best val accuracy : 0.6964
INFO flwr 2023-09-27 01:53:41,220 | common.py:35 | Avg. local train loss : 3.881457337923348, train acc : 0.904488888888889
INFO flwr 2023-09-27 01:53:44,123 | server.py:116 | fit progress: (8, 1.5114525939941406, {'server_test_acc': 0.683}, 789.8052715999947)
INFO flwr 2023-09-27 01:53:44,123 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-09-27 01:53:47,198 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2891703)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 01:54:56,966 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2891570)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2891638)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:54:57,075 | fed_df.py:367 | Warm start at round 9
INFO flwr 2023-09-27 01:54:57,173 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2891570)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2891621)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2891698)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2891697)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2891702)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2891704)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2891638)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2891703)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2891698)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2891697)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2891702)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2891704)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2891621)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:55:19,839 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:55:19,840 | fed_df.py:552 | Average fusion training loss : 0.023307037897408008, val accuracy : 0.6483636363636364, best val accuracy : 0.683
INFO flwr 2023-09-27 01:55:19,841 | common.py:35 | Avg. local train loss : 3.7372336520813407, train acc : 0.9189208333333333
INFO flwr 2023-09-27 01:55:22,742 | server.py:116 | fit progress: (9, 1.457381378173828, {'server_test_acc': 0.6759}, 888.4243745139975)
INFO flwr 2023-09-27 01:55:22,742 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-09-27 01:55:25,829 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3034059)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3034057)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3034052)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 01:56:35,976 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3034058)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 01:56:36,085 | fed_df.py:367 | Warm start at round 10
INFO flwr 2023-09-27 01:56:36,182 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3034052)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3034054)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3034060)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3034059)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3034058)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3034057)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3034061)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3034062)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3034061)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3034062)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3034060)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3034054)[0m malloc_consolidate(): invalid chunk size
E0927 01:56:38.729567625 2866619 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-09-27 01:56:58,626 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:56:58,627 | fed_df.py:552 | Average fusion training loss : 0.023922897341661156, val accuracy : 0.6507818181818181, best val accuracy : 0.6898
INFO flwr 2023-09-27 01:56:58,628 | common.py:35 | Avg. local train loss : 3.804123723693192, train acc : 0.9119638888888888
INFO flwr 2023-09-27 01:57:01,607 | server.py:116 | fit progress: (10, 1.4857353271484375, {'server_test_acc': 0.6839}, 987.2898611889977)
INFO flwr 2023-09-27 01:57:01,607 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-09-27 01:57:04,666 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3148354)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3148351)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:58:14,370 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3148350)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 01:58:14,479 | fed_df.py:367 | Warm start at round 11
INFO flwr 2023-09-27 01:58:14,575 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3148346)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3148351)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3148350)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3148352)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3148353)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3148354)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3148356)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3148355)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3148355)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3148352)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3148356)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3148346)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3148353)[0m malloc_consolidate(): invalid chunk size
E0927 01:58:18.433613396 3247338 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-09-27 01:58:37,071 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 01:58:37,071 | fed_df.py:552 | Average fusion training loss : 0.022742466104216874, val accuracy : 0.7242727272727273, best val accuracy : 0.7516
INFO flwr 2023-09-27 01:58:37,073 | common.py:35 | Avg. local train loss : 3.8533360997214916, train acc : 0.9131555555555556
INFO flwr 2023-09-27 01:58:40,067 | server.py:116 | fit progress: (11, 1.4375980194091798, {'server_test_acc': 0.7412}, 1085.7500735080102)
INFO flwr 2023-09-27 01:58:40,068 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-09-27 01:58:43,207 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3261797)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3261800)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 01:59:53,297 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3261792)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3261796)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3261798)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 01:59:53,406 | fed_df.py:367 | Warm start at round 12
INFO flwr 2023-09-27 01:59:53,505 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3261789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3261789)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3261792)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3261793)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3261797)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3261800)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3261796)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3261798)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3261799)[0m Fitting Client 18
E0927 01:59:54.709331452 3249978 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3261793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3261799)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:00:15,856 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:00:15,857 | fed_df.py:552 | Average fusion training loss : 0.02470509156771004, val accuracy : 0.6984545454545454, best val accuracy : 0.7292
INFO flwr 2023-09-27 02:00:15,858 | common.py:35 | Avg. local train loss : 3.6087616683915256, train acc : 0.9319944444444443
INFO flwr 2023-09-27 02:00:18,734 | server.py:116 | fit progress: (12, 1.434514044189453, {'server_test_acc': 0.7262}, 1184.416503866989)
INFO flwr 2023-09-27 02:00:18,734 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-09-27 02:00:21,778 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-27 02:01:31,262 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-27 02:01:31,369 | fed_df.py:367 | Warm start at round 13
[2m[36m(launch_and_fit pid=3375186)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:01:31,467 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3375179)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3375184)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3375186)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3375187)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3375188)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3375189)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3375182)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3375185)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3375189)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3375188)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3375185)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375182)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375187)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3375179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3375184)[0m malloc_consolidate(): invalid chunk size
E0927 02:01:33.322162474 3475129 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-09-27 02:01:54,220 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:01:54,221 | fed_df.py:552 | Average fusion training loss : 0.026754102047532795, val accuracy : 0.6535272727272727, best val accuracy : 0.6908
INFO flwr 2023-09-27 02:01:54,222 | common.py:35 | Avg. local train loss : 3.4702430829405784, train acc : 0.941675
INFO flwr 2023-09-27 02:01:57,131 | server.py:116 | fit progress: (13, 1.4420121795654297, {'server_test_acc': 0.6801}, 1282.8137123970082)
INFO flwr 2023-09-27 02:01:57,131 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-09-27 02:02:00,245 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3488991)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3488983)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3488986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3488989)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:03:09,671 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-27 02:03:09,778 | fed_df.py:367 | Warm start at round 14
INFO flwr 2023-09-27 02:03:09,873 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3488983)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3488987)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3488986)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3488992)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3488990)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3488991)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3488988)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3488989)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3488988)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3488990)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3488992)[0m malloc_consolidate(): invalid chunk size
E0927 02:03:11.392802585 3475242 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=3488987)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:03:32,563 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:03:32,563 | fed_df.py:552 | Average fusion training loss : 0.02111173843499273, val accuracy : 0.734290909090909, best val accuracy : 0.7554
INFO flwr 2023-09-27 02:03:32,564 | common.py:35 | Avg. local train loss : 3.559236070513726, train acc : 0.9349152777777778
INFO flwr 2023-09-27 02:03:35,457 | server.py:116 | fit progress: (14, 1.4707182250976563, {'server_test_acc': 0.7411}, 1381.1400491259992)
INFO flwr 2023-09-27 02:03:35,458 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-09-27 02:03:38,508 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3602471)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3602466)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3602476)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3602473)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:04:47,860 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-27 02:04:47,967 | fed_df.py:367 | Warm start at round 15
INFO flwr 2023-09-27 02:04:48,067 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3602466)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3602468)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3602471)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3602474)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3602472)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3602473)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3602476)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3602475)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3602468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3602474)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3602475)[0m double free or corruption (fasttop)
E0927 02:04:49.750535415 3701286 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=3602472)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:05:10,809 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:05:10,810 | fed_df.py:552 | Average fusion training loss : 0.02980283006094396, val accuracy : 0.713690909090909, best val accuracy : 0.7348
INFO flwr 2023-09-27 02:05:10,811 | common.py:35 | Avg. local train loss : 3.51101156771183, train acc : 0.939375
INFO flwr 2023-09-27 02:05:13,759 | server.py:116 | fit progress: (15, 1.3892226623535155, {'server_test_acc': 0.7289}, 1479.4418896079878)
INFO flwr 2023-09-27 02:05:13,759 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-09-27 02:05:16,799 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3715847)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3715845)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:06:26,816 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3715848)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-09-27 02:06:26,925 | fed_df.py:367 | Warm start at round 16
INFO flwr 2023-09-27 02:06:27,022 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3715845)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3715847)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3715850)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3715852)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3715848)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3715855)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3715856)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3715853)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3715853)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3715852)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3715856)[0m malloc_consolidate(): invalid chunk size
E0927 02:06:28.181522342 3702055 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=3715850)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3715855)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:06:49,652 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:06:49,652 | fed_df.py:552 | Average fusion training loss : 0.029603043905459345, val accuracy : 0.7252545454545454, best val accuracy : 0.7484
INFO flwr 2023-09-27 02:06:49,653 | common.py:35 | Avg. local train loss : 3.4949464188888673, train acc : 0.9408791666666668
INFO flwr 2023-09-27 02:06:52,593 | server.py:116 | fit progress: (16, 1.384845556640625, {'server_test_acc': 0.7336}, 1578.2760112049873)
INFO flwr 2023-09-27 02:06:52,594 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-09-27 02:06:55,705 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3829778)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:08:04,798 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-27 02:08:04,905 | fed_df.py:367 | Warm start at round 17
[2m[36m(launch_and_fit pid=3829779)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:08:05,009 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3829766)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3829779)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3829780)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3829778)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3829777)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3829783)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3829782)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3829781)[0m Fitting Client 0
E0927 02:08:06.196193422 3814628 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0927 02:08:06.196295848 3814628 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0927 02:08:06.196333118 3814628 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0927 02:08:06.196344261 3814628 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
E0927 02:08:06.196353176 3814628 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=3829777)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3829780)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3829782)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3829781)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3829783)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:08:27,594 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:08:27,594 | fed_df.py:552 | Average fusion training loss : 0.025584356393665075, val accuracy : 0.7288545454545455, best val accuracy : 0.7484
INFO flwr 2023-09-27 02:08:27,595 | common.py:35 | Avg. local train loss : 3.532107447087765, train acc : 0.9404638888888889
INFO flwr 2023-09-27 02:08:30,642 | server.py:116 | fit progress: (17, 1.4113177642822266, {'server_test_acc': 0.7394}, 1676.3247979730077)
INFO flwr 2023-09-27 02:08:30,642 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-09-27 02:08:33,793 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3942907)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3942933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3942910)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3942934)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:09:43,841 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-27 02:09:43,949 | fed_df.py:367 | Warm start at round 18
INFO flwr 2023-09-27 02:09:44,048 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3942907)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3942932)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3942924)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3942933)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3942923)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3942910)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3942934)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3942925)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3942923)[0m malloc_consolidate(): invalid chunk size
E0927 02:09:44.631466481 3928223 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=3942924)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3942932)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3942925)[0m malloc_consolidate(): invalid chunk size
E0927 02:09:53.334145640 4070848 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 02:10:06,746 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:10:06,747 | fed_df.py:552 | Average fusion training loss : 0.025561005890369415, val accuracy : 0.7238363636363635, best val accuracy : 0.7532
INFO flwr 2023-09-27 02:10:06,748 | common.py:35 | Avg. local train loss : 3.4596028772182765, train acc : 0.9442847222222222
INFO flwr 2023-09-27 02:10:09,675 | server.py:116 | fit progress: (18, 1.4258578125, {'server_test_acc': 0.7415}, 1775.3577481709945)
INFO flwr 2023-09-27 02:10:09,675 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-09-27 02:10:12,966 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-27 02:11:23,900 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-27 02:11:24,011 | fed_df.py:367 | Warm start at round 19
[2m[36m(launch_and_fit pid=4093416)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:11:24,111 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4093347)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4093414)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4093416)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4093256)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4093264)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4093255)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4093348)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4093415)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4093414)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093255)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093264)[0m malloc_consolidate(): invalid chunk size
E0927 02:11:24.977676060 4071500 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4093348)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4093415)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093256)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093347)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:11:46,821 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:11:46,821 | fed_df.py:552 | Average fusion training loss : 0.027323643838986753, val accuracy : 0.7478181818181819, best val accuracy : 0.7658
INFO flwr 2023-09-27 02:11:46,822 | common.py:35 | Avg. local train loss : 3.4479817474260925, train acc : 0.9463486111111111
INFO flwr 2023-09-27 02:11:49,769 | server.py:116 | fit progress: (19, 1.3514666717529298, {'server_test_acc': 0.7616}, 1875.4518681619957)
INFO flwr 2023-09-27 02:11:49,769 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-09-27 02:11:52,854 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=15938)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=15936)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=15928)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:13:03,016 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-27 02:13:03,124 | fed_df.py:367 | Warm start at round 20
INFO flwr 2023-09-27 02:13:03,222 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=15931)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=15931)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=15928)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=15933)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=15934)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=15936)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=15938)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=15937)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=15935)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=15933)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=15937)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=15934)[0m malloc_consolidate(): invalid chunk size
E0927 02:13:04.271103868     567 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=15935)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:13:25,930 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:13:25,930 | fed_df.py:552 | Average fusion training loss : 0.026632704697549345, val accuracy : 0.7453090909090908, best val accuracy : 0.7716
INFO flwr 2023-09-27 02:13:25,931 | common.py:35 | Avg. local train loss : 3.52170021366328, train acc : 0.9414597222222223
INFO flwr 2023-09-27 02:13:28,840 | server.py:116 | fit progress: (20, 1.3559291442871093, {'server_test_acc': 0.7585}, 1974.5229308099952)
INFO flwr 2023-09-27 02:13:28,840 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-09-27 02:13:31,926 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=131090)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=131103)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:14:41,592 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-27 02:14:41,700 | fed_df.py:367 | Warm start at round 21
INFO flwr 2023-09-27 02:14:41,797 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=131090)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=131089)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=131102)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=131103)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=131105)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=131104)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=131091)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=131106)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=131105)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131106)[0m malloc_consolidate(): invalid chunk size
E0927 02:14:42.564324426  115111 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=131104)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=131091)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=131102)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=131089)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:15:04,738 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:15:04,739 | fed_df.py:552 | Average fusion training loss : 0.028631044497713448, val accuracy : 0.7556545454545454, best val accuracy : 0.782
INFO flwr 2023-09-27 02:15:04,740 | common.py:35 | Avg. local train loss : 3.4461369182914496, train acc : 0.9495958333333334
INFO flwr 2023-09-27 02:15:07,670 | server.py:116 | fit progress: (21, 1.2825825164794922, {'server_test_acc': 0.7654}, 2073.3528116900125)
INFO flwr 2023-09-27 02:15:07,670 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-09-27 02:15:10,751 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=244634)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:16:20,831 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=244637)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:16:20,940 | fed_df.py:367 | Warm start at round 22
INFO flwr 2023-09-27 02:16:21,035 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=244633)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=244634)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=244638)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=244632)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=244636)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=244637)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=244628)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=244635)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=244633)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=244628)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=244632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=244638)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=244635)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=244636)[0m malloc_consolidate(): invalid chunk size
E0927 02:16:23.346077216  228864 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 02:16:44,095 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:16:44,096 | fed_df.py:552 | Average fusion training loss : 0.03084812444075942, val accuracy : 0.7299454545454545, best val accuracy : 0.7502
INFO flwr 2023-09-27 02:16:44,097 | common.py:35 | Avg. local train loss : 3.3329052968882023, train acc : 0.9551708333333333
INFO flwr 2023-09-27 02:16:47,028 | server.py:116 | fit progress: (22, 1.3517293518066407, {'server_test_acc': 0.7359}, 2172.7111620059877)
INFO flwr 2023-09-27 02:16:47,029 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-09-27 02:16:50,099 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=358784)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:17:59,570 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-09-27 02:17:59,678 | fed_df.py:367 | Warm start at round 23
INFO flwr 2023-09-27 02:17:59,776 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=358786)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=358784)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=358788)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=358787)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=358789)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=358792)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=358790)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=358791)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=358789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358787)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358788)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358790)[0m malloc_consolidate(): invalid chunk size
E0927 02:18:01.043474070  457077 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=358791)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358786)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=358792)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:18:22,673 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:18:22,673 | fed_df.py:552 | Average fusion training loss : 0.029261430902406575, val accuracy : 0.7303454545454545, best val accuracy : 0.7504
INFO flwr 2023-09-27 02:18:22,675 | common.py:35 | Avg. local train loss : 3.2733962515369055, train acc : 0.9571263888888888
INFO flwr 2023-09-27 02:18:25,595 | server.py:116 | fit progress: (23, 1.4043652709960937, {'server_test_acc': 0.7387}, 2271.2781694039877)
INFO flwr 2023-09-27 02:18:25,596 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-09-27 02:18:28,687 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=472208)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=472217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=472213)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=472210)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:19:38,276 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-27 02:19:38,384 | fed_df.py:367 | Warm start at round 24
INFO flwr 2023-09-27 02:19:38,480 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=472208)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=472210)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=472213)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=472215)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=472218)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=472217)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=472216)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=472214)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=472216)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=472215)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=472218)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=472214)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:20:01,328 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:20:01,329 | fed_df.py:552 | Average fusion training loss : 0.028343162258155644, val accuracy : 0.7666909090909091, best val accuracy : 0.7874
INFO flwr 2023-09-27 02:20:01,330 | common.py:35 | Avg. local train loss : 3.456926845386625, train acc : 0.9452430555555554
INFO flwr 2023-09-27 02:20:04,397 | server.py:116 | fit progress: (24, 1.307930029296875, {'server_test_acc': 0.7788}, 2370.07978113601)
INFO flwr 2023-09-27 02:20:04,397 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-09-27 02:20:07,509 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=585274)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:21:16,932 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-27 02:21:17,040 | fed_df.py:367 | Warm start at round 25
INFO flwr 2023-09-27 02:21:17,136 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=585278)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=585268)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=585278)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=585274)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=585277)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=585279)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=585276)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=585270)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=585275)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=585276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=585268)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=585279)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=585270)[0m double free or corruption (fasttop)
E0927 02:21:18.686403445  684422 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=585277)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=585275)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:21:39,817 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:21:39,818 | fed_df.py:552 | Average fusion training loss : 0.03201996554620564, val accuracy : 0.7469636363636364, best val accuracy : 0.7698
INFO flwr 2023-09-27 02:21:39,819 | common.py:35 | Avg. local train loss : 3.306709398329258, train acc : 0.9578527777777778
INFO flwr 2023-09-27 02:21:42,694 | server.py:116 | fit progress: (25, 1.2832289001464843, {'server_test_acc': 0.7552}, 2468.3762864900054)
INFO flwr 2023-09-27 02:21:42,694 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-09-27 02:21:45,919 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=698992)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698997)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698999)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=699001)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=698994)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:22:55,922 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-09-27 02:22:56,031 | fed_df.py:367 | Warm start at round 26
INFO flwr 2023-09-27 02:22:56,135 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=698992)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=698997)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=698999)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=699001)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=698994)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=699002)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=699000)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=698998)[0m Fitting Client 8
E0927 02:22:56.834484659  684423 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=699000)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=698998)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=699002)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:23:18,681 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:23:18,681 | fed_df.py:552 | Average fusion training loss : 0.03381709118001163, val accuracy : 0.7671454545454547, best val accuracy : 0.7796
INFO flwr 2023-09-27 02:23:18,682 | common.py:35 | Avg. local train loss : 3.3877206014469268, train acc : 0.9498277777777777
INFO flwr 2023-09-27 02:23:21,547 | server.py:116 | fit progress: (26, 1.2263822692871094, {'server_test_acc': 0.7651}, 2567.2299101900135)
INFO flwr 2023-09-27 02:23:21,548 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-09-27 02:23:24,705 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-27 02:24:34,693 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-27 02:24:34,802 | fed_df.py:367 | Warm start at round 27
INFO flwr 2023-09-27 02:24:34,901 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=812271)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=812270)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=812275)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=812277)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=812285)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=812284)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=812278)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=812276)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=812271)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=812277)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=812270)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=812285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=812276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=812275)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=812278)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=812284)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:24:57,973 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:24:57,973 | fed_df.py:552 | Average fusion training loss : 0.03450868298858404, val accuracy : 0.7606909090909091, best val accuracy : 0.7776
INFO flwr 2023-09-27 02:24:57,975 | common.py:35 | Avg. local train loss : 3.3181130440905693, train acc : 0.9546708333333334
INFO flwr 2023-09-27 02:25:00,881 | server.py:116 | fit progress: (27, 1.325431298828125, {'server_test_acc': 0.7659}, 2666.563996418001)
INFO flwr 2023-09-27 02:25:00,882 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-09-27 02:25:03,992 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=956363)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:26:13,977 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-09-27 02:26:14,085 | fed_df.py:367 | Warm start at round 28
[2m[36m(launch_and_fit pid=956368)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:26:14,186 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=956363)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=956361)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=956360)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=956365)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=956366)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=956369)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=956367)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=956368)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=956361)[0m double free or corruption (fasttop)
E0927 02:26:14.643775954  797100 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=956360)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956365)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=956366)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956369)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=956367)[0m double free or corruption (fasttop)
E0927 02:26:16.417708617 1063276 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 02:26:37,200 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:26:37,200 | fed_df.py:552 | Average fusion training loss : 0.033698825476691126, val accuracy : 0.7724727272727272, best val accuracy : 0.784
INFO flwr 2023-09-27 02:26:37,202 | common.py:35 | Avg. local train loss : 3.3463391570374377, train acc : 0.9543875
INFO flwr 2023-09-27 02:26:40,110 | server.py:116 | fit progress: (28, 1.2925843811035156, {'server_test_acc': 0.7756}, 2765.7927364390052)
INFO flwr 2023-09-27 02:26:40,110 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-09-27 02:26:43,196 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1079349)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1079346)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1079351)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1079353)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1079354)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-09-27 02:27:54,127 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1079352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1079356)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:27:54,237 | fed_df.py:367 | Warm start at round 29
INFO flwr 2023-09-27 02:27:54,334 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1079349)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1079351)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1079352)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1079354)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1079353)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1079355)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1079356)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1079346)[0m Fitting Client 2
E0927 02:27:54.908741407 1065904 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1079355)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:28:17,025 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:28:17,026 | fed_df.py:552 | Average fusion training loss : 0.034075565985403955, val accuracy : 0.754509090909091, best val accuracy : 0.7702
INFO flwr 2023-09-27 02:28:17,027 | common.py:35 | Avg. local train loss : 3.3321700949221853, train acc : 0.9550569444444446
INFO flwr 2023-09-27 02:28:19,940 | server.py:116 | fit progress: (29, 1.3463908142089844, {'server_test_acc': 0.7607}, 2865.623066174012)
INFO flwr 2023-09-27 02:28:19,941 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-09-27 02:28:22,988 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1192984)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:29:33,064 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1192989)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:29:33,174 | fed_df.py:367 | Warm start at round 30
INFO flwr 2023-09-27 02:29:33,273 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1192984)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1192989)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1192982)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1192988)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1192986)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1192990)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1192987)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1192985)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1192987)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1192982)[0m malloc_consolidate(): invalid chunk size
E0927 02:29:33.772199285 1290282 chttp2_transport.cc:1079]             ipv4:145.136.62.8:37340: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1192986)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1192990)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1192988)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:29:56,175 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:29:56,176 | fed_df.py:552 | Average fusion training loss : 0.030100340242497622, val accuracy : 0.7385818181818181, best val accuracy : 0.7546
INFO flwr 2023-09-27 02:29:56,177 | common.py:35 | Avg. local train loss : 3.191444579325616, train acc : 0.9631263888888889
INFO flwr 2023-09-27 02:29:59,152 | server.py:116 | fit progress: (30, 1.320593310546875, {'server_test_acc': 0.7492}, 2964.8349953959987)
INFO flwr 2023-09-27 02:29:59,153 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-27 02:29:59,153 | server.py:144 | FL finished in 2964.8353461750085
INFO flwr 2023-09-27 02:29:59,153 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-27 02:29:59,154 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-27 02:29:59,154 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.5174114990234375), (2, 1.4816364349365234), (3, 1.5176260192871094), (4, 1.5573885955810547), (5, 1.534094140625), (6, 1.512862173461914), (7, 1.492459323120117), (8, 1.5114525939941406), (9, 1.457381378173828), (10, 1.4857353271484375), (11, 1.4375980194091798), (12, 1.434514044189453), (13, 1.4420121795654297), (14, 1.4707182250976563), (15, 1.3892226623535155), (16, 1.384845556640625), (17, 1.4113177642822266), (18, 1.4258578125), (19, 1.3514666717529298), (20, 1.3559291442871093), (21, 1.2825825164794922), (22, 1.3517293518066407), (23, 1.4043652709960937), (24, 1.307930029296875), (25, 1.2832289001464843), (26, 1.2263822692871094), (27, 1.325431298828125), (28, 1.2925843811035156), (29, 1.3463908142089844), (30, 1.320593310546875)]
INFO flwr 2023-09-27 02:29:59,154 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4763), (2, 0.5397), (3, 0.5596), (4, 0.6131), (5, 0.6472), (6, 0.58), (7, 0.6752), (8, 0.683), (9, 0.6759), (10, 0.6839), (11, 0.7412), (12, 0.7262), (13, 0.6801), (14, 0.7411), (15, 0.7289), (16, 0.7336), (17, 0.7394), (18, 0.7415), (19, 0.7616), (20, 0.7585), (21, 0.7654), (22, 0.7359), (23, 0.7387), (24, 0.7788), (25, 0.7552), (26, 0.7651), (27, 0.7659), (28, 0.7756), (29, 0.7607), (30, 0.7492)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn8: task 0: Aborted
srun: Terminating StepId=3935200.0
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3935200
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 15:06:00 core-walltime
Job Wall-clock time: 00:50:20
Memory Utilized: 0.00 MB (estimated maximum)
Memory Efficiency: 0.00% of 120.00 GB (120.00 GB/node)
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
