-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:5000
STRATEGY:feddf
MODEL_NAME:resnet8
MODEL_LIST:{'resnet8':7,'wresnet-16-4':7,'resnet20':6}
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:32
SERVER_LR:0.005
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
SERVER_STEPS_ADAPTIVE:False
SERVER_STEPS_ADAPTIVE_MIN:100
SERVER_STEPS_ADAPTIVE_INTERVAL:5
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:False
IMG_NAME:ameyoko_small.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:1000
KMEANS_HEURISTICS:hard
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:1.0
CONFIDENCE_THRESHOLD:0.9
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:2.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
Simulating feddf training
INFO simulate 2023-09-27 02:35:03,394 | simulate.py:51 | Python script started : simulate.py
DEBUG simulate 2023-09-27 02:35:03,394 | simulate.py:56 | Reading args from argument parser
INFO flwr 2023-09-27 02:35:24,732 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-09-27 02:35:26,946	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-09-27 02:35:28,001 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'GPU': 1.0, 'node:145.136.62.8': 1.0, 'accelerator_type:A100': 1.0, 'memory': 103079215104.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-09-27 02:35:28,001 | server.py:86 | Initializing global parameters
INFO flwr 2023-09-27 02:35:28,001 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-09-27 02:35:28,001 | server.py:88 | Evaluating initial parameters
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3935203/1695774897_544228290/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3935203/1695774897_544228290/cifar-10-python.tar.gz to /scratch-local/sunnys.3935203/1695774897_544228290
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
Downloading https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz to /scratch-local/sunnys.3935203/1695774897_544228290/cifar-100-python.tar.gz
Extracting /scratch-local/sunnys.3935203/1695774897_544228290/cifar-100-python.tar.gz to /scratch-local/sunnys.3935203/1695774897_544228290
INFO flwr 2023-09-27 02:35:31,171 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-09-27 02:35:31,171 | server.py:101 | FL starting
DEBUG flwr 2023-09-27 02:35:34,539 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1341212)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:36:45,044 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-09-27 02:36:45,155 | fed_df.py:367 | Warm start at round 1
INFO flwr 2023-09-27 02:36:45,480 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1341215)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1341219)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1341217)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1341216)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1341212)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1341214)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1341213)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1341218)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1341219)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1341214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1341213)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1341218)[0m malloc_consolidate(): invalid chunk size
E0927 02:36:46.382667341 1340114 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=1341217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1341215)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1341216)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:37:08,070 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:37:08,070 | fed_df.py:552 | Average fusion training loss : 0.05366159390285611, val accuracy : 0.3434, best val accuracy : 0.4322
INFO flwr 2023-09-27 02:37:08,071 | common.py:35 | Avg. local train loss : 6.754606726020574, train acc : 0.599963888888889
INFO flwr 2023-09-27 02:37:10,936 | server.py:116 | fit progress: (1, 1.5827911315917969, {'server_test_acc': 0.4425}, 99.7653602429782)
INFO flwr 2023-09-27 02:37:10,936 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-09-27 02:37:14,015 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1455149)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:38:23,328 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-09-27 02:38:23,466 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1455149)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1455157)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1455151)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1455153)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1455155)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1455159)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1455158)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1455160)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1455159)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1455160)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1455153)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1455151)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1455155)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1455157)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1455158)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:38:46,213 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:38:46,213 | fed_df.py:552 | Average fusion training loss : 0.03827935114502907, val accuracy : 0.4257454545454546, best val accuracy : 0.4828
INFO flwr 2023-09-27 02:38:46,214 | common.py:35 | Avg. local train loss : 5.210355506651104, train acc : 0.7549027777777779
INFO flwr 2023-09-27 02:38:49,162 | server.py:116 | fit progress: (2, 1.6301771881103515, {'server_test_acc': 0.4826}, 197.99136884798645)
INFO flwr 2023-09-27 02:38:49,162 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-09-27 02:38:52,212 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1568566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1568561)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1568563)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:40:01,964 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-09-27 02:40:02,112 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1568561)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1568563)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1568566)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1568568)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1568570)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1568571)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1568567)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1568569)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1568569)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1568570)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1568571)[0m double free or corruption (fasttop)
E0927 02:40:03.313878962 1440145 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=1568567)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:40:24,887 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:40:24,887 | fed_df.py:552 | Average fusion training loss : 0.02997125619649887, val accuracy : 0.4872363636363637, best val accuracy : 0.535
INFO flwr 2023-09-27 02:40:24,889 | common.py:35 | Avg. local train loss : 5.146288999542594, train acc : 0.7636388888888888
INFO flwr 2023-09-27 02:40:27,787 | server.py:116 | fit progress: (3, 1.4078662811279297, {'server_test_acc': 0.5345}, 296.6159065089887)
INFO flwr 2023-09-27 02:40:27,787 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-09-27 02:40:30,912 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1705995)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:41:40,430 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-09-27 02:41:40,577 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1705995)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1706000)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1705982)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1705994)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1705996)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1705998)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1705997)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1705999)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1706000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1705997)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1705998)[0m malloc_consolidate(): invalid chunk size
E0927 02:41:41.204435472 1675929 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=1705996)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1705999)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1705994)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1705982)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:42:03,534 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:42:03,534 | fed_df.py:552 | Average fusion training loss : 0.026908435551449658, val accuracy : 0.5220181818181818, best val accuracy : 0.5864
INFO flwr 2023-09-27 02:42:03,535 | common.py:35 | Avg. local train loss : 4.677268642000854, train acc : 0.8128722222222223
INFO flwr 2023-09-27 02:42:06,447 | server.py:116 | fit progress: (4, 1.3474323760986329, {'server_test_acc': 0.5769}, 395.2762631229998)
INFO flwr 2023-09-27 02:42:06,447 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-09-27 02:42:09,533 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1835722)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:43:19,142 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1835728)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:43:19,250 | fed_df.py:367 | Warm start at round 5
[2m[36m(launch_and_fit pid=1835723)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:43:19,345 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1835723)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1835725)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1835722)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1835727)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1835729)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1835728)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1835730)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1835731)[0m Fitting Client 9
E0927 02:43:19.727254644 1931975 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=1835729)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1835730)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1835731)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1835727)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1835725)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:43:42,100 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:43:42,100 | fed_df.py:552 | Average fusion training loss : 0.027293433405458926, val accuracy : 0.6069636363636364, best val accuracy : 0.635
INFO flwr 2023-09-27 02:43:42,102 | common.py:35 | Avg. local train loss : 4.81519867554307, train acc : 0.8006611111111113
INFO flwr 2023-09-27 02:43:45,091 | server.py:116 | fit progress: (5, 1.36052470703125, {'server_test_acc': 0.6281}, 493.92042333399877)
INFO flwr 2023-09-27 02:43:45,092 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-09-27 02:43:48,223 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-09-27 02:44:58,021 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1948514)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:44:58,170 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1948512)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1948508)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1948506)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1948514)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1948516)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1948513)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1948515)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1948517)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1948508)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948515)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948513)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1948506)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1948517)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1948512)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:45:20,796 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:45:20,796 | fed_df.py:552 | Average fusion training loss : 0.012540735592134297, val accuracy : 0.5932181818181819, best val accuracy : 0.6262
INFO flwr 2023-09-27 02:45:20,797 | common.py:35 | Avg. local train loss : 4.4764676850289105, train acc : 0.8407111111111112
INFO flwr 2023-09-27 02:45:23,685 | server.py:116 | fit progress: (6, 1.3488162872314453, {'server_test_acc': 0.62}, 592.5140575580008)
INFO flwr 2023-09-27 02:45:23,685 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-09-27 02:45:26,895 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2062509)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2062515)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:46:36,727 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-09-27 02:46:36,875 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2062509)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2062511)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2062515)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2062516)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2062513)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2062514)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2062518)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2062517)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2062514)[0m malloc_consolidate(): invalid chunk size
E0927 02:46:37.579169687 1932694 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2062511)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2062518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2062513)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2062516)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2062517)[0m malloc_consolidate(): invalid chunk size
E0927 02:46:39.386446275 2162557 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-09-27 02:46:59,531 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:46:59,532 | fed_df.py:552 | Average fusion training loss : 0.014409179186448455, val accuracy : 0.6153272727272727, best val accuracy : 0.6372
INFO flwr 2023-09-27 02:46:59,533 | common.py:35 | Avg. local train loss : 4.347452853992581, train acc : 0.852675
INFO flwr 2023-09-27 02:47:02,395 | server.py:116 | fit progress: (7, 1.4338085845947266, {'server_test_acc': 0.628}, 691.2239088529896)
INFO flwr 2023-09-27 02:47:02,395 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-09-27 02:47:05,528 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2175888)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2175889)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2175894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2175893)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2175891)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:48:15,909 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-09-27 02:48:16,054 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2175892)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2175889)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2175891)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2175888)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2175895)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2175894)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2175893)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2175890)[0m Fitting Client 4
E0927 02:48:17.151423329 2162982 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=2175890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2175895)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2175892)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:48:39,063 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:48:39,063 | fed_df.py:552 | Average fusion training loss : 0.014958396453410388, val accuracy : 0.6103818181818181, best val accuracy : 0.645
INFO flwr 2023-09-27 02:48:39,065 | common.py:35 | Avg. local train loss : 4.388029043003917, train acc : 0.8471944444444445
INFO flwr 2023-09-27 02:48:41,949 | server.py:116 | fit progress: (8, 1.4470153045654297, {'server_test_acc': 0.6267}, 790.7782857779821)
INFO flwr 2023-09-27 02:48:41,949 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-09-27 02:48:45,032 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2289889)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:49:55,310 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2289821)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2289962)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:49:55,461 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2289961)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2289888)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2289962)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2289821)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2289887)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2289820)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2289890)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2289889)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2289887)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2289820)[0m malloc_consolidate(): invalid chunk size
E0927 02:49:56.341389407 2274562 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=2289961)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2289890)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2289888)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:50:18,276 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:50:18,276 | fed_df.py:552 | Average fusion training loss : 0.01145048869214952, val accuracy : 0.6137454545454546, best val accuracy : 0.6452
INFO flwr 2023-09-27 02:50:18,277 | common.py:35 | Avg. local train loss : 4.591665019653737, train acc : 0.8297361111111112
INFO flwr 2023-09-27 02:50:21,175 | server.py:116 | fit progress: (9, 1.4919020874023436, {'server_test_acc': 0.6237}, 890.0042707549874)
INFO flwr 2023-09-27 02:50:21,175 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-09-27 02:50:24,232 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2403186)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2403188)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2403189)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:51:33,669 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-09-27 02:51:33,777 | fed_df.py:367 | Warm start at round 10
INFO flwr 2023-09-27 02:51:33,873 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2403186)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2403190)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2403189)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2403193)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2403188)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2403191)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2403192)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2403184)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2403184)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2403192)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2403193)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2403191)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2403190)[0m malloc_consolidate(): invalid chunk size
E0927 02:51:36.202798298 2388202 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-09-27 02:51:56,715 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:51:56,715 | fed_df.py:552 | Average fusion training loss : 0.021430651251226663, val accuracy : 0.6498727272727272, best val accuracy : 0.6712
INFO flwr 2023-09-27 02:51:56,716 | common.py:35 | Avg. local train loss : 4.383703667484223, train acc : 0.8487194444444445
INFO flwr 2023-09-27 02:51:59,659 | server.py:116 | fit progress: (10, 1.533593569946289, {'server_test_acc': 0.6617}, 988.4882078169903)
INFO flwr 2023-09-27 02:51:59,659 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-09-27 02:52:02,759 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2517249)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:53:12,317 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2517385)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:53:12,465 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2517249)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2517318)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2517247)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2517384)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2517386)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2517317)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2517383)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2517385)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2517383)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2517247)[0m malloc_consolidate(): invalid chunk size
E0927 02:53:13.068651077 2503451 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=2517318)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2517317)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2517386)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2517384)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 02:53:35,341 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:53:35,342 | fed_df.py:552 | Average fusion training loss : 0.012453316350467503, val accuracy : 0.6400727272727273, best val accuracy : 0.6592
INFO flwr 2023-09-27 02:53:35,343 | common.py:35 | Avg. local train loss : 4.197311297431588, train acc : 0.8754069444444444
INFO flwr 2023-09-27 02:53:38,285 | server.py:116 | fit progress: (11, 1.4826609252929688, {'server_test_acc': 0.6461}, 1087.1139196709846)
INFO flwr 2023-09-27 02:53:38,285 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-09-27 02:53:41,318 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2630624)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:54:50,811 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-09-27 02:54:50,962 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2630623)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2630624)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2630619)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2630618)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2630622)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2630621)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2630620)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2630625)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2630622)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2630618)[0m malloc_consolidate(): invalid chunk size
E0927 02:54:51.985599631 2615008 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=2630621)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2630625)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2630620)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2630623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2630619)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:55:13,901 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:55:13,902 | fed_df.py:552 | Average fusion training loss : 0.010660536307841539, val accuracy : 0.6396909090909091, best val accuracy : 0.6616
INFO flwr 2023-09-27 02:55:13,903 | common.py:35 | Avg. local train loss : 4.230139306001366, train acc : 0.8691152777777778
INFO flwr 2023-09-27 02:55:16,969 | server.py:116 | fit progress: (12, 1.5231982543945313, {'server_test_acc': 0.6483}, 1185.798343670991)
INFO flwr 2023-09-27 02:55:16,970 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-09-27 02:55:20,116 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2754574)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 02:56:29,668 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-09-27 02:56:29,819 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2754702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2754574)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2754762)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2754701)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2754761)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2754769)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2754639)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2754641)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2754702)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2754639)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2754769)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2754762)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2754761)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2754701)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2754641)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:56:52,422 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:56:52,422 | fed_df.py:552 | Average fusion training loss : 0.010851449099369347, val accuracy : 0.6585090909090909, best val accuracy : 0.6812
INFO flwr 2023-09-27 02:56:52,423 | common.py:35 | Avg. local train loss : 4.317744118720293, train acc : 0.8594055555555555
INFO flwr 2023-09-27 02:56:55,309 | server.py:116 | fit progress: (13, 1.5344457153320312, {'server_test_acc': 0.657}, 1284.1381220399926)
INFO flwr 2023-09-27 02:56:55,309 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-09-27 02:56:58,534 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2897649)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2897646)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2897644)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2897652)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2897653)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2897654)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:58:08,596 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-09-27 02:58:08,747 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2897646)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2897644)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2897649)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2897650)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2897651)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2897654)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2897653)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2897652)[0m Fitting Client 14
E0927 02:58:09.335401527 2728817 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=2897651)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2897650)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 02:58:31,282 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 02:58:31,282 | fed_df.py:552 | Average fusion training loss : 0.009752839837223292, val accuracy : 0.6491454545454545, best val accuracy : 0.671
INFO flwr 2023-09-27 02:58:31,283 | common.py:35 | Avg. local train loss : 4.22993940319866, train acc : 0.8663208333333334
INFO flwr 2023-09-27 02:58:34,219 | server.py:116 | fit progress: (14, 1.5230900268554688, {'server_test_acc': 0.6572}, 1383.048577034002)
INFO flwr 2023-09-27 02:58:34,220 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-09-27 02:58:37,283 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3010732)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3010730)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3010737)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 02:59:46,410 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-09-27 02:59:46,517 | fed_df.py:367 | Warm start at round 15
INFO flwr 2023-09-27 02:59:46,614 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3010732)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3010730)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3010735)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3010740)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3010739)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3010737)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3010736)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3010738)[0m Fitting Client 11
E0927 02:59:47.231317808 2995126 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=3010738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3010736)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3010735)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3010740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3010739)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:00:09,650 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:00:09,650 | fed_df.py:552 | Average fusion training loss : 0.01807818033453077, val accuracy : 0.644090909090909, best val accuracy : 0.6692
INFO flwr 2023-09-27 03:00:09,651 | common.py:35 | Avg. local train loss : 4.2295001216232775, train acc : 0.8659694444444443
INFO flwr 2023-09-27 03:00:12,534 | server.py:116 | fit progress: (15, 1.5418117218017577, {'server_test_acc': 0.6561}, 1481.3629731319961)
INFO flwr 2023-09-27 03:00:12,534 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-09-27 03:00:15,643 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3124463)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3124459)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:01:25,826 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3124465)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:01:25,976 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3124456)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3124459)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3124463)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3124465)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3124467)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3124466)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3124464)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3124462)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3124467)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3124466)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3124456)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3124464)[0m malloc_consolidate(): invalid chunk size
E0927 03:01:27.811676235 3117869 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=3124462)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:01:48,931 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:01:48,931 | fed_df.py:552 | Average fusion training loss : 0.011558679992333055, val accuracy : 0.6330363636363636, best val accuracy : 0.6616
INFO flwr 2023-09-27 03:01:48,932 | common.py:35 | Avg. local train loss : 3.961510893888772, train acc : 0.8935597222222221
INFO flwr 2023-09-27 03:01:51,853 | server.py:116 | fit progress: (16, 1.5769474884033203, {'server_test_acc': 0.6579}, 1580.6822502329887)
INFO flwr 2023-09-27 03:01:51,853 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-09-27 03:01:54,978 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3238092)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238100)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:03:04,505 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-09-27 03:03:04,653 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3238092)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3238097)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3238103)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3238102)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3238100)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3238095)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3238101)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3238096)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3238095)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238103)[0m malloc_consolidate(): invalid chunk size
E0927 03:03:05.280171778 3224056 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=3238097)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3238096)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3238101)[0m double free or corruption (fasttop)
E0927 03:03:07.008693936 3337674 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-09-27 03:03:27,711 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:03:27,711 | fed_df.py:552 | Average fusion training loss : 0.010336566804442554, val accuracy : 0.6466727272727272, best val accuracy : 0.6764
INFO flwr 2023-09-27 03:03:27,712 | common.py:35 | Avg. local train loss : 4.008429782278835, train acc : 0.8909930555555556
INFO flwr 2023-09-27 03:03:30,650 | server.py:116 | fit progress: (17, 1.6054922821044921, {'server_test_acc': 0.6613}, 1679.4787612869986)
INFO flwr 2023-09-27 03:03:30,650 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-09-27 03:03:33,754 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3351716)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3351721)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3351715)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3351722)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:04:43,241 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-09-27 03:04:43,390 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3351716)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3351715)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3351720)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3351722)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3351721)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3351723)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3351719)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3351724)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3351719)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3351724)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3351723)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3351720)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:05:06,306 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:05:06,307 | fed_df.py:552 | Average fusion training loss : 0.010929155507124961, val accuracy : 0.6341454545454546, best val accuracy : 0.6688
INFO flwr 2023-09-27 03:05:06,308 | common.py:35 | Avg. local train loss : 4.122909458912909, train acc : 0.8807138888888889
INFO flwr 2023-09-27 03:05:09,312 | server.py:116 | fit progress: (18, 1.6107198944091796, {'server_test_acc': 0.6637}, 1778.1414984509756)
INFO flwr 2023-09-27 03:05:09,313 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-09-27 03:05:12,445 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3465452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3465449)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:06:22,450 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-09-27 03:06:22,598 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3465449)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3465448)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3465452)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3465521)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3465475)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3465520)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3465453)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3465519)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3465519)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3465521)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3465520)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3465475)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3465448)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3465453)[0m malloc_consolidate(): invalid chunk size
E0927 03:06:25.486284399 3564585 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 03:06:45,300 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:06:45,301 | fed_df.py:552 | Average fusion training loss : 0.010757929612882435, val accuracy : 0.6477636363636363, best val accuracy : 0.6804
INFO flwr 2023-09-27 03:06:45,302 | common.py:35 | Avg. local train loss : 4.042570824734867, train acc : 0.8889277777777778
INFO flwr 2023-09-27 03:06:48,366 | server.py:116 | fit progress: (19, 1.5632309539794922, {'server_test_acc': 0.665}, 1877.1954455129744)
INFO flwr 2023-09-27 03:06:48,367 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-09-27 03:06:51,496 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3579166)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:08:00,628 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-09-27 03:08:00,739 | fed_df.py:367 | Warm start at round 20
INFO flwr 2023-09-27 03:08:00,845 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3579166)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3579170)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3579171)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3579174)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3579173)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3579176)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3579175)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3579172)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3579172)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3579171)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3579170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3579175)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3579176)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3579173)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3579174)[0m malloc_consolidate(): invalid chunk size
E0927 03:08:03.482254507 3566608 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 03:08:23,359 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:08:23,359 | fed_df.py:552 | Average fusion training loss : 0.01558106979727745, val accuracy : 0.6907818181818182, best val accuracy : 0.706
INFO flwr 2023-09-27 03:08:23,360 | common.py:35 | Avg. local train loss : 4.1154302569106225, train acc : 0.8821222222222223
INFO flwr 2023-09-27 03:08:26,281 | server.py:116 | fit progress: (20, 1.5802892028808593, {'server_test_acc': 0.6979}, 1975.109960581991)
INFO flwr 2023-09-27 03:08:26,281 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-09-27 03:08:29,562 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3692301)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3692308)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3692305)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:09:39,488 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-09-27 03:09:39,645 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3692301)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3692303)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3692305)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3692307)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3692308)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3692311)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3692309)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3692310)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3692307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3692310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3692309)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3692311)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3692303)[0m malloc_consolidate(): invalid chunk size
E0927 03:09:43.664942982 3793995 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 03:10:02,593 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:10:02,593 | fed_df.py:552 | Average fusion training loss : 0.01317590335290879, val accuracy : 0.6732, best val accuracy : 0.7034
INFO flwr 2023-09-27 03:10:02,594 | common.py:35 | Avg. local train loss : 4.010462183132768, train acc : 0.8927972222222222
INFO flwr 2023-09-27 03:10:05,540 | server.py:116 | fit progress: (21, 1.584729263305664, {'server_test_acc': 0.6956}, 2074.369229467993)
INFO flwr 2023-09-27 03:10:05,540 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-09-27 03:10:08,651 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3806489)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3806494)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:11:18,470 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3806493)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:11:18,619 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3806489)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3806497)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3806493)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3806498)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3806494)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3806499)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3806495)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3806496)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3806498)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3806496)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3806497)[0m malloc_consolidate(): invalid chunk size
E0927 03:11:19.650646045 3913403 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 03:11:19.650755805 3913403 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 03:11:19.650773231 3913403 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3806499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3806495)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:11:41,874 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:11:41,875 | fed_df.py:552 | Average fusion training loss : 0.010870769164524972, val accuracy : 0.6397090909090909, best val accuracy : 0.6928
INFO flwr 2023-09-27 03:11:41,876 | common.py:35 | Avg. local train loss : 4.002731465175748, train acc : 0.8906236111111111
INFO flwr 2023-09-27 03:11:44,818 | server.py:116 | fit progress: (22, 1.6500486907958984, {'server_test_acc': 0.6827}, 2173.6472173959773)
INFO flwr 2023-09-27 03:11:44,818 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-09-27 03:11:47,926 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3943249)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3943259)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3943251)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3943255)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:12:57,743 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3943261)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:12:57,894 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3943249)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3943251)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3943257)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3943255)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3943258)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3943260)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3943259)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3943261)[0m Fitting Client 15
E0927 03:12:58.830620357 4056966 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3943257)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3943258)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3943260)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:13:20,983 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:13:20,984 | fed_df.py:552 | Average fusion training loss : 0.011468390907160939, val accuracy : 0.6655636363636362, best val accuracy : 0.6946
INFO flwr 2023-09-27 03:13:20,985 | common.py:35 | Avg. local train loss : 4.076294051297008, train acc : 0.886625
INFO flwr 2023-09-27 03:13:23,895 | server.py:116 | fit progress: (23, 1.5488348114013673, {'server_test_acc': 0.6862}, 2272.7238376390014)
INFO flwr 2023-09-27 03:13:23,895 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-09-27 03:13:26,986 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4072871)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072880)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:14:36,896 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-09-27 03:14:37,046 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4072873)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4072871)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4072876)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4072877)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4072878)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4072881)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4072879)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4072880)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4072878)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4072879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072881)[0m malloc_consolidate(): invalid chunk size
E0927 03:14:37.729562693 4057521 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4072877)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072873)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4072876)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:14:59,995 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:14:59,996 | fed_df.py:552 | Average fusion training loss : 0.011640171023551374, val accuracy : 0.6662, best val accuracy : 0.686
INFO flwr 2023-09-27 03:14:59,997 | common.py:35 | Avg. local train loss : 4.201921435631812, train acc : 0.8765722222222222
INFO flwr 2023-09-27 03:15:02,889 | server.py:116 | fit progress: (24, 1.6116050994873048, {'server_test_acc': 0.6782}, 2371.718285023002)
INFO flwr 2023-09-27 03:15:02,889 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-09-27 03:15:05,959 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4186609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186614)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:16:15,426 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-09-27 03:16:15,534 | fed_df.py:367 | Warm start at round 25
INFO flwr 2023-09-27 03:16:15,628 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4186609)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4186613)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4186614)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4186616)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4186618)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4186619)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4186617)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4186615)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4186615)[0m malloc_consolidate(): invalid chunk size
E0927 03:16:16.690707035 4171087 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4186613)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186617)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4186619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4186616)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:16:38,518 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:16:38,518 | fed_df.py:552 | Average fusion training loss : 0.01795633744308725, val accuracy : 0.6789818181818181, best val accuracy : 0.7004
INFO flwr 2023-09-27 03:16:38,520 | common.py:35 | Avg. local train loss : 3.9858513617888094, train acc : 0.8923916666666666
INFO flwr 2023-09-27 03:16:41,456 | server.py:116 | fit progress: (25, 1.590085723876953, {'server_test_acc': 0.6935}, 2470.2848954649817)
INFO flwr 2023-09-27 03:16:41,456 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-09-27 03:16:44,554 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=107467)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=107470)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:17:54,264 | server.py:229 | fit_round 26 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=107471)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=107475)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:17:54,415 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=107467)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=107470)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=107475)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=107473)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=107472)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=107471)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=107476)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=107474)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=107472)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=107473)[0m malloc_consolidate(): invalid chunk size
E0927 03:17:55.101394979  205009 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=107474)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=107476)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:18:16,999 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:18:16,999 | fed_df.py:552 | Average fusion training loss : 0.012556791531853378, val accuracy : 0.6673818181818182, best val accuracy : 0.698
INFO flwr 2023-09-27 03:18:17,001 | common.py:35 | Avg. local train loss : 3.9603029049932954, train acc : 0.899626388888889
INFO flwr 2023-09-27 03:18:19,963 | server.py:116 | fit progress: (26, 1.5851235229492187, {'server_test_acc': 0.688}, 2568.7917959819897)
INFO flwr 2023-09-27 03:18:19,963 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-09-27 03:18:23,133 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=221081)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=221105)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221037)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-09-27 03:19:32,331 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-09-27 03:19:32,482 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=221037)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=221081)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=221179)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=221181)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=221106)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=221105)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=221177)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=221180)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=221179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=221106)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=221177)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221181)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=221180)[0m malloc_consolidate(): invalid chunk size
E0927 03:19:35.409043514  205401 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-09-27 03:19:55,250 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:19:55,250 | fed_df.py:552 | Average fusion training loss : 0.011751892942003905, val accuracy : 0.6569454545454545, best val accuracy : 0.6854
INFO flwr 2023-09-27 03:19:55,252 | common.py:35 | Avg. local train loss : 4.000994684174657, train acc : 0.892151388888889
INFO flwr 2023-09-27 03:19:58,116 | server.py:116 | fit progress: (27, 1.6100691009521484, {'server_test_acc': 0.6747}, 2666.9446200629754)
INFO flwr 2023-09-27 03:19:58,116 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-09-27 03:20:01,237 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=334714)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=334724)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:21:10,585 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=334716)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:21:10,736 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=334714)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=334716)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=334720)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=334721)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=334718)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=334724)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=334722)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=334723)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=334723)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=334718)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=334720)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=334721)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=334722)[0m double free or corruption (fasttop)
INFO flwr 2023-09-27 03:21:34,045 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:21:34,046 | fed_df.py:552 | Average fusion training loss : 0.011998103741090744, val accuracy : 0.6843636363636363, best val accuracy : 0.7054
INFO flwr 2023-09-27 03:21:34,047 | common.py:35 | Avg. local train loss : 3.9494651606306435, train acc : 0.8990972222222223
INFO flwr 2023-09-27 03:21:36,944 | server.py:116 | fit progress: (28, 1.5654434539794921, {'server_test_acc': 0.6884}, 2765.7727438719885)
INFO flwr 2023-09-27 03:21:36,944 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-09-27 03:21:40,057 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=448523)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=448527)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=448517)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:22:49,687 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-09-27 03:22:49,835 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=448523)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=448525)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=448521)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=448522)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=448517)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=448524)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=448526)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=448527)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=448526)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=448522)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=448521)[0m malloc_consolidate(): invalid chunk size
E0927 03:22:51.265524644  433118 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 03:22:51.265626557  433118 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0927 03:22:51.265642745  433118 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=448524)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=448525)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:23:12,717 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:23:12,718 | fed_df.py:552 | Average fusion training loss : 0.011401141020469368, val accuracy : 0.6845272727272728, best val accuracy : 0.707
INFO flwr 2023-09-27 03:23:12,719 | common.py:35 | Avg. local train loss : 4.030841413140297, train acc : 0.8912208333333335
INFO flwr 2023-09-27 03:23:15,657 | server.py:116 | fit progress: (29, 1.571433364868164, {'server_test_acc': 0.6839}, 2864.486347717)
INFO flwr 2023-09-27 03:23:15,657 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-09-27 03:23:18,765 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=561872)[0m double free or corruption (fasttop)
DEBUG flwr 2023-09-27 03:24:28,400 | server.py:229 | fit_round 30 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=561871)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:24:28,510 | fed_df.py:367 | Warm start at round 30
INFO flwr 2023-09-27 03:24:28,607 | fed_df.py:465 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=561867)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=561868)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=561865)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=561871)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=561872)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=561874)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=561873)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=561875)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=561873)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=561865)[0m corrupted size vs. prev_size in fastbins
E0927 03:24:29.600396577  558780 chttp2_transport.cc:1079]             ipv4:145.136.62.8:49461: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=561875)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=561874)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=561867)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=561868)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-09-27 03:24:51,586 | fed_df.py:545 | Distillation training stopped at step number : 500
INFO flwr 2023-09-27 03:24:51,586 | fed_df.py:552 | Average fusion training loss : 0.016737261176109314, val accuracy : 0.6829636363636363, best val accuracy : 0.7098
INFO flwr 2023-09-27 03:24:51,588 | common.py:35 | Avg. local train loss : 3.919982402212918, train acc : 0.8994944444444445
INFO flwr 2023-09-27 03:24:54,527 | server.py:116 | fit progress: (30, 1.614755142211914, {'server_test_acc': 0.701}, 2963.356397961994)
INFO flwr 2023-09-27 03:24:54,528 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-09-27 03:24:54,528 | server.py:144 | FL finished in 2963.356766296987
INFO flwr 2023-09-27 03:24:54,528 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-09-27 03:24:54,529 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-09-27 03:24:54,529 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.5827911315917969), (2, 1.6301771881103515), (3, 1.4078662811279297), (4, 1.3474323760986329), (5, 1.36052470703125), (6, 1.3488162872314453), (7, 1.4338085845947266), (8, 1.4470153045654297), (9, 1.4919020874023436), (10, 1.533593569946289), (11, 1.4826609252929688), (12, 1.5231982543945313), (13, 1.5344457153320312), (14, 1.5230900268554688), (15, 1.5418117218017577), (16, 1.5769474884033203), (17, 1.6054922821044921), (18, 1.6107198944091796), (19, 1.5632309539794922), (20, 1.5802892028808593), (21, 1.584729263305664), (22, 1.6500486907958984), (23, 1.5488348114013673), (24, 1.6116050994873048), (25, 1.590085723876953), (26, 1.5851235229492187), (27, 1.6100691009521484), (28, 1.5654434539794921), (29, 1.571433364868164), (30, 1.614755142211914)]
INFO flwr 2023-09-27 03:24:54,529 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4425), (2, 0.4826), (3, 0.5345), (4, 0.5769), (5, 0.6281), (6, 0.62), (7, 0.628), (8, 0.6267), (9, 0.6237), (10, 0.6617), (11, 0.6461), (12, 0.6483), (13, 0.657), (14, 0.6572), (15, 0.6561), (16, 0.6579), (17, 0.6613), (18, 0.6637), (19, 0.665), (20, 0.6979), (21, 0.6956), (22, 0.6827), (23, 0.6862), (24, 0.6782), (25, 0.6935), (26, 0.688), (27, 0.6747), (28, 0.6884), (29, 0.6839), (30, 0.701)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn8: task 0: Aborted
srun: Terminating StepId=3935203.0
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3935203
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:37:38
CPU Efficiency: 10.81% of 15:03:18 core-walltime
Job Wall-clock time: 00:50:11
Memory Utilized: 24.23 GB
Memory Efficiency: 20.19% of 120.00 GB
