-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:20000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:9
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:random
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:True
USE_KMEANS:False
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=20000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3357208/1692172432_093569663', seed=84, img_per_thread=1111)
will save 20000 patches in /scratch-local/sunnys.3357208/1692172432_093569663/single_img_crops/crops
20000 took 0.17min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-16 09:54:17,700 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-16 09:54:17,701 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3357208/1692172432_093569663/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3357208/1692172432_093569663/cifar-10-python.tar.gz to /scratch-local/sunnys.3357208/1692172432_093569663
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [225 194 247 272 217 251 256 333 258 247]
INFO flwr 2023-08-16 09:54:45,143 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-16 09:54:47,755	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-16 09:54:48,804 | app.py:179 | Flower VCE: Ray initialized with resources: {'object_store_memory': 61847529062.0, 'CPU': 18.0, 'accelerator_type:A100': 1.0, 'memory': 103079215104.0, 'node:145.136.62.42': 1.0, 'GPU': 1.0}
INFO flwr 2023-08-16 09:54:48,805 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-16 09:54:48,805 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-16 09:54:48,805 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-16 09:54:59,324 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-16 09:54:59,325 | server.py:101 | FL starting
DEBUG flwr 2023-08-16 09:55:04,870 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 09:55:55,211 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2346328)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 09:55:55,471 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-16 09:55:55,610 | fed_df.py:463 | Performing server side distillation training...
[W] [09:55:01.815113] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2346329)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2346327)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2346332)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2346331)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2346330)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2346325)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2346326)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2346328)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2346325)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2346327)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2346329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2346332)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2346331)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2346326)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2346330)[0m malloc_consolidate(): invalid chunk size
E0816 09:55:59.209596567 2342992 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-16 09:56:21,876 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 09:56:21,876 | fed_df.py:547 | Average fusion training loss : 0.0209921610429883, val accuracy : 0.4162, best val accuracy : 0.4428
INFO flwr 2023-08-16 09:56:21,878 | common.py:35 | Avg. local train loss : 8.77410546541214, train acc : 0.3843083333333334
INFO flwr 2023-08-16 09:56:24,324 | server.py:116 | fit progress: (1, 1.522981967163086, {'server_test_acc': 0.4619}, 84.99927741102874)
INFO flwr 2023-08-16 09:56:24,324 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-16 09:56:29,628 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2417554)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 09:57:18,045 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2417547)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2417550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417555)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 09:57:18,389 | fed_df.py:463 | Performing server side distillation training...
[W] [09:56:26.733084] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2417545)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2417547)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2417551)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2417552)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2417550)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2417554)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2417553)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2417555)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2417551)[0m malloc_consolidate(): invalid chunk size
E0816 09:57:19.192642450 2396358 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2417553)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2417545)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2417552)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 09:57:44,844 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 09:57:44,845 | fed_df.py:547 | Average fusion training loss : 0.016891458973288535, val accuracy : 0.51772, best val accuracy : 0.5494
INFO flwr 2023-08-16 09:57:44,847 | common.py:35 | Avg. local train loss : 7.218909724801779, train acc : 0.5555305555555555
INFO flwr 2023-08-16 09:57:47,334 | server.py:116 | fit progress: (2, 1.4625373321533204, {'server_test_acc': 0.5566}, 168.0092644530814)
INFO flwr 2023-08-16 09:57:47,334 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-16 09:57:52,629 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 09:58:40,449 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2488744)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2488749)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 09:58:40,791 | fed_df.py:463 | Performing server side distillation training...
[W] [09:57:49.755499] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2488744)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2488749)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2488745)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2488748)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2488747)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2488752)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2488751)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2488750)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2488750)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2488747)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2488748)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2488751)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2488745)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2488752)[0m malloc(): unsorted double linked list corrupted
E0816 09:58:44.502754777 2537941 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
INFO flwr 2023-08-16 09:59:07,792 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 09:59:07,792 | fed_df.py:547 | Average fusion training loss : 0.011618898693472147, val accuracy : 0.57148, best val accuracy : 0.5908
INFO flwr 2023-08-16 09:59:07,794 | common.py:35 | Avg. local train loss : 6.524503976851702, train acc : 0.6343805555555555
INFO flwr 2023-08-16 09:59:10,330 | server.py:116 | fit progress: (3, 1.4004414123535156, {'server_test_acc': 0.5826}, 251.00484716100618)
INFO flwr 2023-08-16 09:59:10,330 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-16 09:59:15,722 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2560402)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:00:06,998 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-16 10:00:07,340 | fed_df.py:463 | Performing server side distillation training...
[W] [09:59:12.778954] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2560396)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2560402)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2560401)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2560400)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2560399)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2560397)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2560403)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2560398)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2560396)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2560403)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2560400)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2560401)[0m double free or corruption (fasttop)
E0816 10:00:08.656847713 2539068 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=2560399)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2560397)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2560398)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:00:34,497 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:00:34,497 | fed_df.py:547 | Average fusion training loss : 0.009061798447743059, val accuracy : 0.61108, best val accuracy : 0.6184
INFO flwr 2023-08-16 10:00:34,499 | common.py:35 | Avg. local train loss : 6.203174797818065, train acc : 0.6667916666666667
INFO flwr 2023-08-16 10:00:37,033 | server.py:116 | fit progress: (4, 1.3352357421875, {'server_test_acc': 0.6152}, 337.7082735639997)
INFO flwr 2023-08-16 10:00:37,033 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-16 10:00:42,476 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2631136)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:01:30,357 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2631141)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:01:30,620 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-16 10:01:30,759 | fed_df.py:463 | Performing server side distillation training...
[W] [10:00:39.559456] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2631134)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2631136)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2631135)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2631137)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2631140)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2631141)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2631138)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2631139)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2631134)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2631138)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2631140)[0m malloc_consolidate(): invalid chunk size
E0816 10:01:31.777079311 2678480 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=2631139)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2631137)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2631135)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:01:57,774 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:01:57,774 | fed_df.py:547 | Average fusion training loss : 0.011698960155248642, val accuracy : 0.63728, best val accuracy : 0.65
INFO flwr 2023-08-16 10:01:57,776 | common.py:35 | Avg. local train loss : 5.975333197042347, train acc : 0.6917777777777778
INFO flwr 2023-08-16 10:02:00,333 | server.py:116 | fit progress: (5, 1.2110019348144532, {'server_test_acc': 0.6468}, 421.00790935591795)
INFO flwr 2023-08-16 10:02:00,333 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-16 10:02:06,389 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2702553)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:02:55,260 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2702549)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:02:55,606 | fed_df.py:463 | Performing server side distillation training...
[W] [10:02:02.808817] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2702547)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2702551)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2702550)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2702548)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2702549)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2702552)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2702553)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2702554)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2702550)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2702554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2702551)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2702547)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2702552)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2702548)[0m malloc_consolidate(): invalid chunk size
E0816 10:02:59.330688904 2752361 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
INFO flwr 2023-08-16 10:03:22,966 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:03:22,966 | fed_df.py:547 | Average fusion training loss : 0.007155967060476541, val accuracy : 0.65036, best val accuracy : 0.654
INFO flwr 2023-08-16 10:03:22,968 | common.py:35 | Avg. local train loss : 5.588664374500513, train acc : 0.7289722222222222
INFO flwr 2023-08-16 10:03:25,505 | server.py:116 | fit progress: (6, 1.2412045043945312, {'server_test_acc': 0.6552}, 506.1800681350287)
INFO flwr 2023-08-16 10:03:25,505 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-16 10:03:30,919 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2773805)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:04:21,556 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2773808)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:04:21,904 | fed_df.py:463 | Performing server side distillation training...
[W] [10:03:27.966260] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2773811)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2773807)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2773812)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2773806)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2773810)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2773805)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2773808)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2773809)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2773807)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2773806)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2773809)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2773812)[0m corrupted size vs. prev_size in fastbins
E0816 10:04:23.031381514 2752698 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=2773811)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2773810)[0m double free or corruption (fasttop)
E0816 10:04:24.716583870 2822182 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-16 10:04:49,666 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:04:49,666 | fed_df.py:547 | Average fusion training loss : 0.010014899954199791, val accuracy : 0.66152, best val accuracy : 0.6732
INFO flwr 2023-08-16 10:04:49,668 | common.py:35 | Avg. local train loss : 5.456782606616616, train acc : 0.7437527777777778
INFO flwr 2023-08-16 10:04:52,219 | server.py:116 | fit progress: (7, 1.236696258544922, {'server_test_acc': 0.6614}, 592.8945891740732)
INFO flwr 2023-08-16 10:04:52,220 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-16 10:04:57,656 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2845846)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2845845)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:05:46,207 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-16 10:05:46,549 | fed_df.py:463 | Performing server side distillation training...
[W] [10:04:54.695257] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2845845)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2845839)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2845846)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2845844)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2845838)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2845841)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2845843)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2845842)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2845844)[0m malloc_consolidate(): invalid chunk size
E0816 10:05:47.105932433 2823651 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=2845842)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2845839)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2845841)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2845838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2845843)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:06:14,080 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:06:14,080 | fed_df.py:547 | Average fusion training loss : 0.00732716554030776, val accuracy : 0.66716, best val accuracy : 0.6768
INFO flwr 2023-08-16 10:06:14,082 | common.py:35 | Avg. local train loss : 5.4118195608258235, train acc : 0.7479611111111111
INFO flwr 2023-08-16 10:06:16,648 | server.py:116 | fit progress: (8, 1.2034395751953124, {'server_test_acc': 0.6701}, 677.3235654500313)
INFO flwr 2023-08-16 10:06:16,649 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-16 10:06:22,073 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:07:09,491 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2917027)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:07:09,834 | fed_df.py:463 | Performing server side distillation training...
[W] [10:06:19.130939] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2917027)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2917024)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2917031)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2917028)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2917030)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2917032)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2917034)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2917033)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2917024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2917030)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2917028)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2917033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2917032)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2917031)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2917034)[0m malloc_consolidate(): invalid chunk size
E0816 10:07:13.490112998 2965675 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-16 10:07:37,041 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:07:37,042 | fed_df.py:547 | Average fusion training loss : 0.006687622472643852, val accuracy : 0.67596, best val accuracy : 0.6826
INFO flwr 2023-08-16 10:07:37,044 | common.py:35 | Avg. local train loss : 5.330900426954031, train acc : 0.7576666666666667
INFO flwr 2023-08-16 10:07:39,658 | server.py:116 | fit progress: (9, 1.255141354370117, {'server_test_acc': 0.6745}, 760.3335475130007)
INFO flwr 2023-08-16 10:07:39,659 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-16 10:07:45,097 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2988216)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:08:32,450 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-16 10:08:32,713 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-16 10:08:32,854 | fed_df.py:463 | Performing server side distillation training...
[W] [10:07:42.144406] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=2988216)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2988219)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2988221)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2988224)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2988217)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2988218)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2988223)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2988222)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2988223)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2988221)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2988217)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2988222)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2988219)[0m malloc_consolidate(): invalid chunk size
E0816 10:08:34.775103184 2966812 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=2988218)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2988224)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:09:00,574 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:09:00,574 | fed_df.py:547 | Average fusion training loss : 0.01191944662388414, val accuracy : 0.6805999999999999, best val accuracy : 0.6948
INFO flwr 2023-08-16 10:09:00,576 | common.py:35 | Avg. local train loss : 5.3085246831178665, train acc : 0.7590027777777779
INFO flwr 2023-08-16 10:09:03,139 | server.py:116 | fit progress: (10, 1.1502689727783204, {'server_test_acc': 0.6932}, 843.814217774896)
INFO flwr 2023-08-16 10:09:03,139 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-16 10:09:08,694 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3073591)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:09:56,672 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-16 10:09:57,019 | fed_df.py:463 | Performing server side distillation training...
[W] [10:09:05.639297] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3073591)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3073476)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3073543)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3073518)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3073514)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3073633)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3073634)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3073630)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3073633)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3073514)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3073476)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3073634)[0m malloc_consolidate(): invalid chunk size
E0816 10:09:58.071372390 3130595 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=3073518)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3073543)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3073630)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:10:24,535 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:10:24,535 | fed_df.py:547 | Average fusion training loss : 0.008159906385466457, val accuracy : 0.6818000000000001, best val accuracy : 0.6882
INFO flwr 2023-08-16 10:10:24,537 | common.py:35 | Avg. local train loss : 5.070783159881831, train acc : 0.7800250000000001
INFO flwr 2023-08-16 10:10:27,093 | server.py:116 | fit progress: (11, 1.2301727752685547, {'server_test_acc': 0.6845}, 927.7683469729964)
INFO flwr 2023-08-16 10:10:27,093 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-16 10:10:32,444 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3155852)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3155860)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:11:20,048 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-16 10:11:20,390 | fed_df.py:463 | Performing server side distillation training...
[W] [10:10:29.526334] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3155850)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3155852)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3155854)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3155857)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3155858)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3155856)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3155860)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3155859)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3155854)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3155850)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3155858)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3155859)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3155856)[0m malloc_consolidate(): invalid chunk size
E0816 10:11:21.751834453 3130831 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
[2m[36m(launch_and_fit pid=3155857)[0m malloc_consolidate(): invalid chunk size
E0816 10:11:42.227108869 3219469 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-16 10:11:47,981 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:11:47,982 | fed_df.py:547 | Average fusion training loss : 0.0059727781368419525, val accuracy : 0.6947599999999999, best val accuracy : 0.7056
INFO flwr 2023-08-16 10:11:47,984 | common.py:35 | Avg. local train loss : 5.082552424818277, train acc : 0.7787666666666666
INFO flwr 2023-08-16 10:11:50,537 | server.py:116 | fit progress: (12, 1.183122299194336, {'server_test_acc': 0.6984}, 1011.2121569619048)
INFO flwr 2023-08-16 10:11:50,537 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-16 10:11:55,934 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:12:43,456 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3227024)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3227023)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:12:43,809 | fed_df.py:463 | Performing server side distillation training...
[W] [10:11:52.992775] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3227015)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3227023)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3227021)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3227022)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3227030)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3227031)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3227032)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3227024)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3227022)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3227031)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3227015)[0m malloc_consolidate(): invalid chunk size
E0816 10:12:44.792277678 3219873 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=3227032)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3227030)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3227021)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:13:11,377 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:13:11,378 | fed_df.py:547 | Average fusion training loss : 0.005873721939511597, val accuracy : 0.68876, best val accuracy : 0.6936
INFO flwr 2023-08-16 10:13:11,380 | common.py:35 | Avg. local train loss : 5.021424947306514, train acc : 0.7859861111111112
INFO flwr 2023-08-16 10:13:13,937 | server.py:116 | fit progress: (13, 1.194285284423828, {'server_test_acc': 0.6957}, 1094.6125155410264)
INFO flwr 2023-08-16 10:13:13,938 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-16 10:13:19,336 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3298397)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:14:06,674 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3298395)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:14:07,018 | fed_df.py:463 | Performing server side distillation training...
[W] [10:13:16.400307] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3298395)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3298397)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3298399)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3298400)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3298404)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3298402)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3298401)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3298403)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3298402)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298401)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3298403)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3298399)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3298404)[0m malloc_consolidate(): invalid chunk size
E0816 10:14:09.235459709 3274729 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
INFO flwr 2023-08-16 10:14:34,426 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:14:34,426 | fed_df.py:547 | Average fusion training loss : 0.005130537325516343, val accuracy : 0.69804, best val accuracy : 0.7076
INFO flwr 2023-08-16 10:14:34,428 | common.py:35 | Avg. local train loss : 5.05304496511817, train acc : 0.7843777777777777
INFO flwr 2023-08-16 10:14:36,983 | server.py:116 | fit progress: (14, 1.2005777221679688, {'server_test_acc': 0.6999}, 1177.6582519209478)
INFO flwr 2023-08-16 10:14:36,983 | server.py:163 | evaluate_round 14: no clients selected, cancel
E0816 10:14:38.014506284 3347151 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
DEBUG flwr 2023-08-16 10:14:42,553 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3369533)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:15:29,897 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-16 10:15:30,159 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-16 10:15:30,299 | fed_df.py:463 | Performing server side distillation training...
[W] [10:14:39.572654] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3369533)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3369538)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3369539)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3369540)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3369544)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3369543)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3369542)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3369541)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3369544)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3369540)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3369542)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3369538)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3369539)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3369541)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3369543)[0m malloc_consolidate(): invalid chunk size
E0816 10:15:33.365413163 3369380 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:15:57,561 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:15:57,562 | fed_df.py:547 | Average fusion training loss : 0.011067274182103574, val accuracy : 0.7081999999999999, best val accuracy : 0.717
INFO flwr 2023-08-16 10:15:57,563 | common.py:35 | Avg. local train loss : 5.062969618663192, train acc : 0.7828916666666669
INFO flwr 2023-08-16 10:16:00,123 | server.py:116 | fit progress: (15, 1.1783128448486329, {'server_test_acc': 0.7129}, 1260.798197515076)
INFO flwr 2023-08-16 10:16:00,123 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-16 10:16:05,577 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3441072)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3441071)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:16:53,245 | server.py:229 | fit_round 16 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3441075)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:16:53,589 | fed_df.py:463 | Performing server side distillation training...
[W] [10:16:02.619716] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3441072)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3441071)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3441074)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3441075)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3441079)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3441077)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3441076)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3441078)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3441078)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3441074)[0m malloc_consolidate(): invalid chunk size
E0816 10:16:54.708746446 3488523 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 10:16:54.708845086 3488523 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 10:16:54.708864390 3488523 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3441077)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3441076)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3441079)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:17:20,896 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:17:20,897 | fed_df.py:547 | Average fusion training loss : 0.0037759230667725207, val accuracy : 0.704, best val accuracy : 0.711
INFO flwr 2023-08-16 10:17:20,898 | common.py:35 | Avg. local train loss : 4.7956281114369625, train acc : 0.8073194444444445
INFO flwr 2023-08-16 10:17:23,464 | server.py:116 | fit progress: (16, 1.2369459259033204, {'server_test_acc': 0.7091}, 1344.1391457018908)
INFO flwr 2023-08-16 10:17:23,464 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-16 10:17:28,852 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:18:16,616 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3512370)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:18:16,961 | fed_df.py:463 | Performing server side distillation training...
[W] [10:17:25.926045] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3512367)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3512372)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3512369)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3512371)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3512373)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3512370)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3512374)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3512375)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3512371)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3512367)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512374)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3512375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512369)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512373)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512372)[0m malloc_consolidate(): invalid chunk size
E0816 10:18:40.859513950 3576504 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:18:44,530 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:18:44,530 | fed_df.py:547 | Average fusion training loss : 0.005194793474860489, val accuracy : 0.7063999999999999, best val accuracy : 0.7114
INFO flwr 2023-08-16 10:18:44,532 | common.py:35 | Avg. local train loss : 4.861810603365302, train acc : 0.8030694444444445
INFO flwr 2023-08-16 10:18:47,081 | server.py:116 | fit progress: (17, 1.221429998779297, {'server_test_acc': 0.7116}, 1427.7561725850683)
INFO flwr 2023-08-16 10:18:47,081 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-16 10:18:52,512 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:19:39,938 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3583556)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:19:40,281 | fed_df.py:463 | Performing server side distillation training...
[W] [10:18:49.564900] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3583555)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3583556)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3583557)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3583558)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3583561)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3583560)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3583554)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3583559)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3583558)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3583555)[0m malloc_consolidate(): invalid chunk size
E0816 10:19:41.161978707 3631264 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3583561)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3583557)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3583554)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3583559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3583560)[0m malloc_consolidate(): invalid chunk size
E0816 10:19:42.673386362 3631399 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:20:07,728 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:20:07,729 | fed_df.py:547 | Average fusion training loss : 0.0043384259548038245, val accuracy : 0.71276, best val accuracy : 0.718
INFO flwr 2023-08-16 10:20:07,731 | common.py:35 | Avg. local train loss : 4.82800668105483, train acc : 0.8061138888888889
INFO flwr 2023-08-16 10:20:10,326 | server.py:116 | fit progress: (18, 1.2263246398925782, {'server_test_acc': 0.7126}, 1511.001305369893)
INFO flwr 2023-08-16 10:20:10,326 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-16 10:20:15,723 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3655102)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:21:03,473 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-16 10:21:03,816 | fed_df.py:463 | Performing server side distillation training...
[W] [10:20:12.801402] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3655102)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3655108)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3655109)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3655105)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3655110)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3655104)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3655107)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3655106)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3655109)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3655108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3655110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3655105)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3655104)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3655106)[0m malloc_consolidate(): invalid chunk size
E0816 10:21:05.781828322 3703302 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3655107)[0m double free or corruption (fasttop)
E0816 10:21:29.657752139 3721633 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:21:31,462 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:21:31,463 | fed_df.py:547 | Average fusion training loss : 0.004477151836268603, val accuracy : 0.71488, best val accuracy : 0.721
INFO flwr 2023-08-16 10:21:31,465 | common.py:35 | Avg. local train loss : 4.850662361085415, train acc : 0.8050666666666667
INFO flwr 2023-08-16 10:21:34,019 | server.py:116 | fit progress: (19, 1.2104552642822266, {'server_test_acc': 0.7154}, 1594.6944413760211)
INFO flwr 2023-08-16 10:21:34,019 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-16 10:21:39,424 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:22:27,211 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-16 10:22:27,473 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-16 10:22:27,616 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3726164)[0m malloc_consolidate(): invalid chunk size
[W] [10:21:36.478675] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3726164)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3726168)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3726167)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3726166)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3726170)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3726169)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3726172)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3726171)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3726167)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3726171)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3726166)[0m malloc_consolidate(): invalid chunk size
E0816 10:22:28.736819446 3722171 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3726168)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3726170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3726172)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3726169)[0m malloc_consolidate(): invalid chunk size
E0816 10:22:44.940636876 3774192 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:22:55,124 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:22:55,125 | fed_df.py:547 | Average fusion training loss : 0.011470452130772173, val accuracy : 0.7050799999999999, best val accuracy : 0.722
INFO flwr 2023-08-16 10:22:55,127 | common.py:35 | Avg. local train loss : 4.850790672004223, train acc : 0.8050111111111111
INFO flwr 2023-08-16 10:22:57,672 | server.py:116 | fit progress: (20, 1.2479518157958984, {'server_test_acc': 0.7236}, 1678.3471097080037)
INFO flwr 2023-08-16 10:22:57,672 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-16 10:23:03,065 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3797822)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:23:50,479 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-16 10:23:50,824 | fed_df.py:463 | Performing server side distillation training...
[W] [10:23:00.149658] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3797822)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3797824)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3797829)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3797828)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3797831)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3797830)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3797832)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3797827)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3797824)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3797829)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3797830)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3797832)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3797827)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3797831)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3797828)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:24:19,024 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:24:19,024 | fed_df.py:547 | Average fusion training loss : 0.003771132992580533, val accuracy : 0.7198, best val accuracy : 0.727
INFO flwr 2023-08-16 10:24:19,026 | common.py:35 | Avg. local train loss : 4.636095163971185, train acc : 0.8255694444444444
INFO flwr 2023-08-16 10:24:21,610 | server.py:116 | fit progress: (21, 1.2882780364990234, {'server_test_acc': 0.7224}, 1762.2850493830629)
INFO flwr 2023-08-16 10:24:21,610 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-16 10:24:27,093 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3883201)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3883205)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:25:15,149 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3883203)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:25:15,495 | fed_df.py:463 | Performing server side distillation training...
[W] [10:24:24.131717] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3883201)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3883203)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3883205)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3883206)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3883210)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3883208)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3883207)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3883209)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3883207)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3883210)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3883208)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3883206)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3883209)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:25:43,056 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:25:43,057 | fed_df.py:547 | Average fusion training loss : 0.0036119935060851278, val accuracy : 0.7206, best val accuracy : 0.728
INFO flwr 2023-08-16 10:25:43,059 | common.py:35 | Avg. local train loss : 4.716307662427425, train acc : 0.8170916666666667
INFO flwr 2023-08-16 10:25:45,601 | server.py:116 | fit progress: (22, 1.2605098724365233, {'server_test_acc': 0.724}, 1846.2757785359863)
INFO flwr 2023-08-16 10:25:45,601 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-16 10:25:51,006 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3965036)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3965042)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:26:38,425 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-16 10:26:38,771 | fed_df.py:463 | Performing server side distillation training...
[W] [10:25:48.057703] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=3965036)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3965042)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3965044)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3965043)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3965041)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3965046)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3965040)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3965045)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3965044)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3965043)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3965046)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3965041)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3965040)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3965045)[0m malloc_consolidate(): invalid chunk size
E0816 10:26:47.852534021 3787063 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 10:27:00.822855861 4025697 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:27:11,281 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:27:11,281 | fed_df.py:547 | Average fusion training loss : 0.0042547828396782275, val accuracy : 0.71828, best val accuracy : 0.723
INFO flwr 2023-08-16 10:27:11,283 | common.py:35 | Avg. local train loss : 4.7168822910636665, train acc : 0.8192333333333334
INFO flwr 2023-08-16 10:27:13,881 | server.py:116 | fit progress: (23, 1.233670199584961, {'server_test_acc': 0.7183}, 1934.5564370590728)
INFO flwr 2023-08-16 10:27:13,881 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-16 10:27:19,341 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4036514)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:28:06,988 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-16 10:28:07,342 | fed_df.py:463 | Performing server side distillation training...
[W] [10:27:16.329290] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=4036514)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4036513)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4036512)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4036511)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4036518)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4036516)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4036515)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4036517)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4036516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4036513)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4036518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4036511)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4036515)[0m malloc_consolidate(): invalid chunk size
E0816 10:28:08.591533716 3417845 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4036512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4036517)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:28:34,914 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:28:34,914 | fed_df.py:547 | Average fusion training loss : 0.004471724905073643, val accuracy : 0.72636, best val accuracy : 0.7366
INFO flwr 2023-08-16 10:28:34,916 | common.py:35 | Avg. local train loss : 4.745986101403833, train acc : 0.8165527777777778
INFO flwr 2023-08-16 10:28:37,478 | server.py:116 | fit progress: (24, 1.2305608245849609, {'server_test_acc': 0.7257}, 2018.1533352930564)
INFO flwr 2023-08-16 10:28:37,478 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-16 10:28:43,235 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4107721)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:29:31,095 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4107723)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4107722)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:29:31,359 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-16 10:29:31,500 | fed_df.py:463 | Performing server side distillation training...
[W] [10:28:40.237231] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=4107721)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4107724)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4107723)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4107728)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4107725)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4107727)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4107726)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4107722)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4107728)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4107725)[0m malloc_consolidate(): invalid chunk size
E0816 10:29:32.409135515 4084377 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4107727)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4107724)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4107726)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:29:59,148 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:29:59,149 | fed_df.py:547 | Average fusion training loss : 0.009735990898683667, val accuracy : 0.7232000000000001, best val accuracy : 0.7314
INFO flwr 2023-08-16 10:29:59,151 | common.py:35 | Avg. local train loss : 4.751514757052064, train acc : 0.8141555555555555
INFO flwr 2023-08-16 10:30:01,758 | server.py:116 | fit progress: (25, 1.258408920288086, {'server_test_acc': 0.7222}, 2102.432897939114)
INFO flwr 2023-08-16 10:30:01,758 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-16 10:30:07,215 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4179291)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4179296)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4179287)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:30:55,275 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-16 10:30:55,620 | fed_df.py:463 | Performing server side distillation training...
[W] [10:30:04.248690] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=4179287)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4179291)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4179289)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4179292)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4179296)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4179294)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4179295)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4179293)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4179295)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4179294)[0m malloc_consolidate(): invalid chunk size
E0816 10:30:56.218781627 4155458 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4179293)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4179292)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4179289)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:31:23,279 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:31:23,279 | fed_df.py:547 | Average fusion training loss : 0.0036073214458301663, val accuracy : 0.73008, best val accuracy : 0.7418
INFO flwr 2023-08-16 10:31:23,281 | common.py:35 | Avg. local train loss : 4.583557886630296, train acc : 0.8313638888888889
INFO flwr 2023-08-16 10:31:25,836 | server.py:116 | fit progress: (26, 1.2609164123535157, {'server_test_acc': 0.7359}, 2186.5116635879967)
INFO flwr 2023-08-16 10:31:25,837 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-16 10:31:31,226 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=57228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=57232)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=57230)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:32:19,149 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=57226)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-16 10:32:19,494 | fed_df.py:463 | Performing server side distillation training...
[W] [10:31:28.303962] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=57226)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=57228)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=57232)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=57230)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=57233)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=57234)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=57235)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=57231)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=57234)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=57233)[0m malloc_consolidate(): invalid chunk size
E0816 10:32:20.514223403  104648 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=57235)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=57231)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:32:52,158 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:32:52,159 | fed_df.py:547 | Average fusion training loss : 0.0037808368345722556, val accuracy : 0.7316800000000001, best val accuracy : 0.74
INFO flwr 2023-08-16 10:32:52,161 | common.py:35 | Avg. local train loss : 4.602489741146565, train acc : 0.83075
INFO flwr 2023-08-16 10:32:54,738 | server.py:116 | fit progress: (27, 1.2543225067138672, {'server_test_acc': 0.7283}, 2275.4137291319203)
INFO flwr 2023-08-16 10:32:54,739 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-16 10:33:00,177 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=128835)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=128839)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-16 10:33:48,168 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=128842)[0m double free or corruption (fasttop)
INFO flwr 2023-08-16 10:33:48,515 | fed_df.py:463 | Performing server side distillation training...
[W] [10:32:57.232093] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=128835)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=128839)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=128841)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=128843)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=128842)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=128840)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=128838)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=128844)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=128838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=128843)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=128844)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=128841)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=128840)[0m double free or corruption (fasttop)
E0816 10:33:52.126692070  105053 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0816 10:34:12.360505269  178334 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:34:16,356 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:34:16,356 | fed_df.py:547 | Average fusion training loss : 0.004159910634625703, val accuracy : 0.72512, best val accuracy : 0.7328
INFO flwr 2023-08-16 10:34:16,358 | common.py:35 | Avg. local train loss : 4.578625252470374, train acc : 0.8337805555555555
INFO flwr 2023-08-16 10:34:18,930 | server.py:116 | fit progress: (28, 1.2672309967041016, {'server_test_acc': 0.7296}, 2359.6055442520883)
INFO flwr 2023-08-16 10:34:18,931 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-16 10:34:24,410 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=200079)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-16 10:35:11,928 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-16 10:35:12,306 | fed_df.py:463 | Performing server side distillation training...
[W] [10:34:21.398104] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=200079)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=200082)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=200083)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=200084)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=200085)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=200080)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=200086)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=200087)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=200083)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=200087)[0m double free or corruption (fasttop)
E0816 10:35:13.161745060  247777 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=200080)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=200082)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=200085)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=200084)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=200086)[0m malloc_consolidate(): invalid chunk size
E0816 10:35:14.504465876  247917 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:35:40,038 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:35:40,038 | fed_df.py:547 | Average fusion training loss : 0.004061997695825994, val accuracy : 0.7306, best val accuracy : 0.7392
INFO flwr 2023-08-16 10:35:40,040 | common.py:35 | Avg. local train loss : 4.582602288201452, train acc : 0.8326666666666668
INFO flwr 2023-08-16 10:35:42,585 | server.py:116 | fit progress: (29, 1.2453050689697265, {'server_test_acc': 0.7341}, 2443.2603133351076)
INFO flwr 2023-08-16 10:35:42,585 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-16 10:35:48,062 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-16 10:36:35,617 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-16 10:36:35,877 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-16 10:36:36,014 | fed_df.py:463 | Performing server side distillation training...
[W] [10:35:45.128033] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...
[2m[36m(launch_and_fit pid=271316)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=271322)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=271319)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=271320)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=271317)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=271321)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=271318)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=271323)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=271319)[0m malloc(): unsorted double linked list corrupted
[2m[36m(launch_and_fit pid=271317)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=271322)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=271320)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=271318)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=271323)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=271316)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=271321)[0m malloc_consolidate(): invalid chunk size
E0816 10:36:39.123353168  320225 chttp2_transport.cc:1079]             ipv4:145.136.62.42:62828: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-16 10:37:03,818 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-16 10:37:03,818 | fed_df.py:547 | Average fusion training loss : 0.00917823910806328, val accuracy : 0.73792, best val accuracy : 0.7446
INFO flwr 2023-08-16 10:37:03,820 | common.py:35 | Avg. local train loss : 4.590881277993321, train acc : 0.8314444444444445
INFO flwr 2023-08-16 10:37:06,378 | server.py:116 | fit progress: (30, 1.3412343719482422, {'server_test_acc': 0.7353}, 2527.0529375420883)
INFO flwr 2023-08-16 10:37:06,378 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-16 10:37:06,378 | server.py:144 | FL finished in 2527.053313309094
INFO flwr 2023-08-16 10:37:06,378 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-16 10:37:06,379 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-16 10:37:06,379 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.522981967163086), (2, 1.4625373321533204), (3, 1.4004414123535156), (4, 1.3352357421875), (5, 1.2110019348144532), (6, 1.2412045043945312), (7, 1.236696258544922), (8, 1.2034395751953124), (9, 1.255141354370117), (10, 1.1502689727783204), (11, 1.2301727752685547), (12, 1.183122299194336), (13, 1.194285284423828), (14, 1.2005777221679688), (15, 1.1783128448486329), (16, 1.2369459259033204), (17, 1.221429998779297), (18, 1.2263246398925782), (19, 1.2104552642822266), (20, 1.2479518157958984), (21, 1.2882780364990234), (22, 1.2605098724365233), (23, 1.233670199584961), (24, 1.2305608245849609), (25, 1.258408920288086), (26, 1.2609164123535157), (27, 1.2543225067138672), (28, 1.2672309967041016), (29, 1.2453050689697265), (30, 1.3412343719482422)]
INFO flwr 2023-08-16 10:37:06,380 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4619), (2, 0.5566), (3, 0.5826), (4, 0.6152), (5, 0.6468), (6, 0.6552), (7, 0.6614), (8, 0.6701), (9, 0.6745), (10, 0.6932), (11, 0.6845), (12, 0.6984), (13, 0.6957), (14, 0.6999), (15, 0.7129), (16, 0.7091), (17, 0.7116), (18, 0.7126), (19, 0.7154), (20, 0.7236), (21, 0.7224), (22, 0.724), (23, 0.7183), (24, 0.7257), (25, 0.7222), (26, 0.7359), (27, 0.7283), (28, 0.7296), (29, 0.7341), (30, 0.7353)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn42: task 0: Aborted
srun: Terminating StepId=3357208.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3357208
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:44:32
CPU Efficiency: 13.31% of 13:05:06 core-walltime
Job Wall-clock time: 00:43:37
Memory Utilized: 63.70 GB
Memory Efficiency: 53.08% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
