-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:25000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:10
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:organamnist
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:5000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:100
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.1
CONFIDENCE_THRESHOLD:0.5
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:False
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=25000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3422098/1692449378_599665762', seed=42, img_per_thread=1388)
will save 25000 patches in /scratch-local/sunnys.3422098/1692449378_599665762/single_img_crops/crops
25000 took 0.41min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-19 14:50:19,684 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-19 14:50:19,684 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3422098/1692449378_599665762/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3422098/1692449378_599665762/cifar-10-python.tar.gz to /scratch-local/sunnys.3422098/1692449378_599665762
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=1.0, 10 classes): [440 381 415  39  10 257 227 532  17 182]
INFO flwr 2023-08-19 14:50:45,097 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-19 14:50:48,122	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-19 14:50:49,158 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'object_store_memory': 61847529062.0, 'node:145.136.62.13': 1.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0, 'memory': 103079215104.0}
INFO flwr 2023-08-19 14:50:49,159 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-19 14:50:49,159 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-19 14:50:49,159 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-19 14:50:59,229 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-19 14:50:59,229 | server.py:101 | FL starting
DEBUG flwr 2023-08-19 14:51:03,737 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 14:51:42,598 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-19 14:51:42,709 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-19 14:51:42,808 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3365524)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3365523)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3365526)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3365525)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3365530)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3365527)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3365529)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3365528)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3365530)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3365527)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3365525)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3365526)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3365523)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3365528)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3365529)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3365524)[0m malloc_consolidate(): invalid chunk size
E0819 14:51:46.268572884 3420100 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-19 14:52:28,027 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 14:52:28,028 | fed_df.py:547 | Average fusion training loss : 0.062193376332521436, val accuracy : 0.29092, best val accuracy : 0.3038
INFO flwr 2023-08-19 14:52:28,029 | common.py:35 | Avg. local train loss : 8.103726448118687, train acc : 0.47101666666666664
INFO flwr 2023-08-19 14:52:30,671 | server.py:116 | fit progress: (1, 1.817745880126953, {'server_test_acc': 0.3088}, 91.44173872796819)
INFO flwr 2023-08-19 14:52:30,671 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-19 14:52:35,250 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 14:53:09,462 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-19 14:53:09,613 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3512592)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3512595)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3512708)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3512793)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3512792)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3512745)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3512748)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3512750)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3512592)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512708)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3512792)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512595)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512750)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512748)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3512745)[0m malloc_consolidate(): invalid chunk size
E0819 14:53:13.146534442 3575330 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-19 14:53:55,806 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 14:53:55,806 | fed_df.py:547 | Average fusion training loss : 0.05171851995587349, val accuracy : 0.31924, best val accuracy : 0.3366
INFO flwr 2023-08-19 14:53:55,807 | common.py:35 | Avg. local train loss : 7.0200838699936865, train acc : 0.5640777777777777
INFO flwr 2023-08-19 14:53:58,478 | server.py:116 | fit progress: (2, 1.848102978515625, {'server_test_acc': 0.3435}, 179.24877088796347)
INFO flwr 2023-08-19 14:53:58,478 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-19 14:54:03,072 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3659489)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3659493)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3659567)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 14:54:36,776 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-19 14:54:36,927 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3659489)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3659493)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3659567)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3659490)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3659637)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3659638)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3659494)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3659491)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3659490)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3659637)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3659638)[0m malloc_consolidate(): invalid chunk size
E0819 14:54:38.249539255 3707125 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=3659491)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3659494)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 14:55:23,551 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 14:55:23,551 | fed_df.py:547 | Average fusion training loss : 0.0813152725249529, val accuracy : 0.38544000000000006, best val accuracy : 0.4144
INFO flwr 2023-08-19 14:55:23,552 | common.py:35 | Avg. local train loss : 7.00079711228609, train acc : 0.56945
INFO flwr 2023-08-19 14:55:26,228 | server.py:116 | fit progress: (3, 1.7487741577148437, {'server_test_acc': 0.4078}, 266.9994931151159)
INFO flwr 2023-08-19 14:55:26,229 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-19 14:55:30,769 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 14:56:04,497 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3789897)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 14:56:04,651 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3789893)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3789897)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3789890)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3789899)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3789896)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3789895)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3789891)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3789898)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3789896)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3789890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3789899)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3789898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3789893)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3789895)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3789891)[0m malloc_consolidate(): invalid chunk size
E0819 14:56:40.562124833 3707523 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-19 14:56:51,447 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 14:56:51,447 | fed_df.py:547 | Average fusion training loss : 0.07350777463614941, val accuracy : 0.41328, best val accuracy : 0.4174
INFO flwr 2023-08-19 14:56:51,448 | common.py:35 | Avg. local train loss : 6.9039590254426, train acc : 0.5796277777777777
INFO flwr 2023-08-19 14:56:54,120 | server.py:116 | fit progress: (4, 1.6199519104003905, {'server_test_acc': 0.4161}, 354.89082077983767)
INFO flwr 2023-08-19 14:56:54,120 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-19 14:56:58,688 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3922541)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3922543)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 14:57:32,858 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-19 14:57:32,970 | fed_df.py:365 | Warm start at round 5
[2m[36m(launch_and_fit pid=3922646)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 14:57:33,070 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3922543)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3922541)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3922614)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3922613)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3922646)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3922674)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3922615)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3922539)[0m Fitting Client 6
E0819 14:57:33.471990504 3896016 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=3922613)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3922614)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3922674)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3922615)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3922539)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 14:58:20,183 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 14:58:20,183 | fed_df.py:547 | Average fusion training loss : 0.04767406561970711, val accuracy : 0.44548, best val accuracy : 0.4564
INFO flwr 2023-08-19 14:58:20,184 | common.py:35 | Avg. local train loss : 6.787648025155068, train acc : 0.5877277777777777
INFO flwr 2023-08-19 14:58:22,882 | server.py:116 | fit progress: (5, 1.5195803314208984, {'server_test_acc': 0.4621}, 443.65349015407264)
INFO flwr 2023-08-19 14:58:22,883 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-19 14:58:27,483 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4056740)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4056669)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 14:59:02,057 | server.py:229 | fit_round 6 received 8 results and 0 failures
INFO flwr 2023-08-19 14:59:02,211 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4056669)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4056670)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4056671)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4056601)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4056672)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4056741)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4056742)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4056740)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4056742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4056741)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4056601)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4056671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4056670)[0m double free or corruption (fasttop)
E0819 14:59:03.304851424 3967783 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=4056672)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 14:59:49,600 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 14:59:49,600 | fed_df.py:547 | Average fusion training loss : 0.04055224893242121, val accuracy : 0.50428, best val accuracy : 0.529
INFO flwr 2023-08-19 14:59:49,601 | common.py:35 | Avg. local train loss : 6.140367180854081, train acc : 0.6593833333333333
INFO flwr 2023-08-19 14:59:52,296 | server.py:116 | fit progress: (6, 1.4482728424072266, {'server_test_acc': 0.5183}, 533.0667129568756)
INFO flwr 2023-08-19 14:59:52,296 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-19 14:59:56,957 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4190285)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:00:31,157 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-19 15:00:31,310 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4190288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4190285)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4190284)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=4190287)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4190286)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=4190288)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4190283)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4190290)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4190289)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4190284)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4190287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4190283)[0m malloc_consolidate(): invalid chunk size
E0819 15:00:32.665815440 4104640 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=4190286)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4190289)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4190290)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:01:19,056 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:01:19,057 | fed_df.py:547 | Average fusion training loss : 0.04460789713263512, val accuracy : 0.5621600000000001, best val accuracy : 0.5702
INFO flwr 2023-08-19 15:01:19,058 | common.py:35 | Avg. local train loss : 6.037706941366196, train acc : 0.6688055555555557
INFO flwr 2023-08-19 15:01:21,690 | server.py:116 | fit progress: (7, 1.365871759033203, {'server_test_acc': 0.5565}, 622.4615007769316)
INFO flwr 2023-08-19 15:01:21,691 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-19 15:01:26,311 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=129564)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=129563)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:02:00,772 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-19 15:02:00,926 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=129565)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=129564)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=129563)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=129561)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=129568)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=129567)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=129569)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=129566)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=129565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=129568)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=129561)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=129566)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=129567)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=129569)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:02:52,633 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:02:52,633 | fed_df.py:547 | Average fusion training loss : 0.03262520404905081, val accuracy : 0.5494800000000001, best val accuracy : 0.5574
INFO flwr 2023-08-19 15:02:52,634 | common.py:35 | Avg. local train loss : 6.2660391159355635, train acc : 0.6454333333333333
INFO flwr 2023-08-19 15:02:55,284 | server.py:116 | fit progress: (8, 1.3774698364257814, {'server_test_acc': 0.5421}, 716.0549834920093)
INFO flwr 2023-08-19 15:02:55,284 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-19 15:02:59,896 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=262412)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:03:34,811 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-19 15:03:34,963 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=262412)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=262409)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=262406)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=262408)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=262410)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=262414)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=262411)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=262413)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=262413)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=262414)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=262409)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=262406)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=262411)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=262410)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=262408)[0m malloc_consolidate(): invalid chunk size
E0819 15:03:37.565386906   47437 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-19 15:04:22,070 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:04:22,070 | fed_df.py:547 | Average fusion training loss : 0.038709667675197124, val accuracy : 0.58144, best val accuracy : 0.5874
INFO flwr 2023-08-19 15:04:22,071 | common.py:35 | Avg. local train loss : 5.855562146008015, train acc : 0.6901222222222223
INFO flwr 2023-08-19 15:04:24,719 | server.py:116 | fit progress: (9, 1.3200352142333984, {'server_test_acc': 0.5721}, 805.4899982819334)
INFO flwr 2023-08-19 15:04:24,719 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-19 15:04:29,233 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=395360)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:05:03,299 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-19 15:05:03,410 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-19 15:05:03,506 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=395357)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=395360)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=395355)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=395365)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=395362)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=395363)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=395361)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=395364)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=395365)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=395355)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=395363)[0m malloc_consolidate(): invalid chunk size
E0819 15:05:04.629330116  317094 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=395357)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=395364)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=395361)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=395362)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:05:50,362 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:05:50,362 | fed_df.py:547 | Average fusion training loss : 0.05347590529918671, val accuracy : 0.60144, best val accuracy : 0.6128
INFO flwr 2023-08-19 15:05:50,363 | common.py:35 | Avg. local train loss : 5.692264331132174, train acc : 0.7062333333333334
INFO flwr 2023-08-19 15:05:52,995 | server.py:116 | fit progress: (10, 1.2975720947265625, {'server_test_acc': 0.595}, 893.7661929409951)
INFO flwr 2023-08-19 15:05:52,995 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-19 15:05:57,696 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:06:31,936 | server.py:229 | fit_round 11 received 8 results and 0 failures
INFO flwr 2023-08-19 15:06:32,091 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=528451)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=528450)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=528452)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=528458)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=528453)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=528459)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=528460)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=528454)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=528451)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=528450)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=528452)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=528459)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=528454)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=528460)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=528458)[0m malloc_consolidate(): invalid chunk size
E0819 15:06:34.211582005  583314 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=528453)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:07:19,138 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:07:19,139 | fed_df.py:547 | Average fusion training loss : 0.027005035296082495, val accuracy : 0.58256, best val accuracy : 0.5894
INFO flwr 2023-08-19 15:07:19,140 | common.py:35 | Avg. local train loss : 5.594137171655893, train acc : 0.7163388888888889
INFO flwr 2023-08-19 15:07:21,763 | server.py:116 | fit progress: (11, 1.3116632537841797, {'server_test_acc': 0.5799}, 982.5340924370103)
INFO flwr 2023-08-19 15:07:21,763 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-19 15:07:26,363 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=660953)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:08:00,089 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-19 15:08:00,242 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=660948)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=660950)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=660954)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=660949)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=660953)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=660956)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=660951)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=660952)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=660949)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=660949)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=660954)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=660951)[0m malloc_consolidate(): invalid chunk size
E0819 15:08:01.289361825  583856 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=660948)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=660956)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=660952)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:08:47,485 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:08:47,485 | fed_df.py:547 | Average fusion training loss : 0.018174198292195798, val accuracy : 0.61072, best val accuracy : 0.6208
INFO flwr 2023-08-19 15:08:47,487 | common.py:35 | Avg. local train loss : 5.706643695384264, train acc : 0.7037333333333334
INFO flwr 2023-08-19 15:08:50,120 | server.py:116 | fit progress: (12, 1.281612744140625, {'server_test_acc': 0.6074}, 1070.8908824091777)
INFO flwr 2023-08-19 15:08:50,120 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-19 15:08:54,830 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:09:28,485 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=813374)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 15:09:28,639 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=813375)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=813374)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=813381)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=813379)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=813373)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=813376)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=813383)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=813384)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=813381)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813375)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813379)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813383)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=813384)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813373)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813376)[0m malloc_consolidate(): invalid chunk size
E0819 15:09:32.236641935  716245 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
INFO flwr 2023-08-19 15:10:15,538 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:10:15,539 | fed_df.py:547 | Average fusion training loss : 0.026235458046197892, val accuracy : 0.60012, best val accuracy : 0.6054
INFO flwr 2023-08-19 15:10:15,540 | common.py:35 | Avg. local train loss : 5.529953046143055, train acc : 0.7209722222222222
INFO flwr 2023-08-19 15:10:18,153 | server.py:116 | fit progress: (13, 1.275920440673828, {'server_test_acc': 0.5886}, 1158.9237254569307)
INFO flwr 2023-08-19 15:10:18,153 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-19 15:10:22,773 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:10:56,160 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=955203)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 15:10:56,314 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=955203)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=955208)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=955210)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=955211)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=955214)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=955212)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=955207)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=955213)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=955212)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=955214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=955210)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=955208)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=955211)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=955213)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=955207)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:11:43,202 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:11:43,203 | fed_df.py:547 | Average fusion training loss : 0.02893978126347065, val accuracy : 0.5985999999999999, best val accuracy : 0.6112
INFO flwr 2023-08-19 15:11:43,204 | common.py:35 | Avg. local train loss : 5.485777045041322, train acc : 0.7265333333333334
INFO flwr 2023-08-19 15:11:45,930 | server.py:116 | fit progress: (14, 1.2521688262939452, {'server_test_acc': 0.6082}, 1246.7014865549281)
INFO flwr 2023-08-19 15:11:45,931 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-19 15:11:50,971 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1088177)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1088179)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:12:24,405 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-19 15:12:24,519 | fed_df.py:365 | Warm start at round 15
[2m[36m(launch_and_fit pid=1088180)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1088201)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:12:24,618 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1088177)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1088104)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1088179)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1088180)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1088200)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1088202)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1088182)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1088201)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1088200)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1088202)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1088182)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1088104)[0m malloc_consolidate(): invalid chunk size
E0819 15:12:26.571812225 1144269 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-19 15:13:11,303 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:13:11,303 | fed_df.py:547 | Average fusion training loss : 0.022930685505270956, val accuracy : 0.57428, best val accuracy : 0.5838
INFO flwr 2023-08-19 15:13:11,305 | common.py:35 | Avg. local train loss : 5.300233744084835, train acc : 0.7442277777777778
INFO flwr 2023-08-19 15:13:13,949 | server.py:116 | fit progress: (15, 1.2955298461914062, {'server_test_acc': 0.5827}, 1334.7204969702289)
INFO flwr 2023-08-19 15:13:13,950 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-19 15:13:18,895 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:13:52,709 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-19 15:13:52,864 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1220618)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1220615)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1220616)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1220610)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1220611)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1220617)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1220619)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1220620)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1220620)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220616)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1220610)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1220617)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1220618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220615)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1220619)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1220611)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:14:39,563 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:14:39,563 | fed_df.py:547 | Average fusion training loss : 0.01895490798726678, val accuracy : 0.59124, best val accuracy : 0.5974
INFO flwr 2023-08-19 15:14:39,564 | common.py:35 | Avg. local train loss : 5.197068098932505, train acc : 0.7543166666666666
INFO flwr 2023-08-19 15:14:42,211 | server.py:116 | fit progress: (16, 1.282725762939453, {'server_test_acc': 0.5905}, 1422.9816518970765)
INFO flwr 2023-08-19 15:14:42,211 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-19 15:14:46,740 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:15:19,957 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-19 15:15:20,110 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1353523)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1353521)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1353527)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1353524)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1353520)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1353528)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1353529)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1353530)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1353520)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353523)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1353530)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1353524)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353529)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1353527)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1353521)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1353528)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 15:16:11,509 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:16:11,509 | fed_df.py:547 | Average fusion training loss : 0.0293721372410655, val accuracy : 0.59844, best val accuracy : 0.6034
INFO flwr 2023-08-19 15:16:11,511 | common.py:35 | Avg. local train loss : 5.366787979751826, train acc : 0.7395166666666667
INFO flwr 2023-08-19 15:16:14,175 | server.py:116 | fit progress: (17, 1.3251280426025391, {'server_test_acc': 0.5893}, 1514.9458078979515)
INFO flwr 2023-08-19 15:16:14,175 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-19 15:16:18,815 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:16:51,916 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-19 15:16:52,073 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1488580)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1488577)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1488572)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1488574)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1488576)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1488578)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1488579)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1488575)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1488576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1488577)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1488575)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1488578)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1488579)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1488574)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1488580)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1488572)[0m malloc_consolidate(): invalid chunk size
E0819 15:17:01.142343481 1144940 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
INFO flwr 2023-08-19 15:17:43,838 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:17:43,839 | fed_df.py:547 | Average fusion training loss : 0.027729805640876293, val accuracy : 0.6322800000000001, best val accuracy : 0.6428
INFO flwr 2023-08-19 15:17:43,840 | common.py:35 | Avg. local train loss : 5.230202993750572, train acc : 0.7536
INFO flwr 2023-08-19 15:17:46,484 | server.py:116 | fit progress: (18, 1.220770147705078, {'server_test_acc': 0.6393}, 1607.2546525760554)
INFO flwr 2023-08-19 15:17:46,484 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-19 15:17:51,166 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1627267)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:18:24,662 | server.py:229 | fit_round 19 received 8 results and 0 failures
INFO flwr 2023-08-19 15:18:24,816 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1627267)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1627632)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1627513)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1627514)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1627634)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1627635)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1627435)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1627833)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1627833)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1627632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1627513)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1627435)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1627634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1627635)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1627514)[0m malloc_consolidate(): invalid chunk size
E0819 15:18:28.323936217 1558299 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
INFO flwr 2023-08-19 15:19:11,629 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:19:11,629 | fed_df.py:547 | Average fusion training loss : 0.023354506075382232, val accuracy : 0.6132799999999999, best val accuracy : 0.621
INFO flwr 2023-08-19 15:19:11,630 | common.py:35 | Avg. local train loss : 5.264833857119083, train acc : 0.7498944444444445
INFO flwr 2023-08-19 15:19:14,297 | server.py:116 | fit progress: (19, 1.276156591796875, {'server_test_acc': 0.6133}, 1695.0677602901123)
INFO flwr 2023-08-19 15:19:14,297 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-19 15:19:18,984 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:19:52,140 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-19 15:19:52,254 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-19 15:19:52,343 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1761312)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1761310)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1761545)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1761543)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1761528)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1761527)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1761544)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1761463)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1761310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1761543)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1761312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1761528)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1761527)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1761544)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1761463)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1761545)[0m double free or corruption (fasttop)
INFO flwr 2023-08-19 15:20:39,359 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:20:39,359 | fed_df.py:547 | Average fusion training loss : 0.0297204274982214, val accuracy : 0.6616, best val accuracy : 0.67
INFO flwr 2023-08-19 15:20:39,360 | common.py:35 | Avg. local train loss : 5.208135798573494, train acc : 0.7577222222222223
INFO flwr 2023-08-19 15:20:42,296 | server.py:116 | fit progress: (20, 1.1865874633789062, {'server_test_acc': 0.659}, 1783.0674903569743)
INFO flwr 2023-08-19 15:20:42,297 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-19 15:20:46,968 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1896893)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 15:21:20,665 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-19 15:21:20,809 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1896893)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1897015)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1897160)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1897161)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1897159)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1897164)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1897163)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1897165)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1897163)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1897164)[0m malloc_consolidate(): invalid chunk size
E0819 15:21:21.783031967 1822139 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1897015)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1897159)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1897160)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1897161)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1897165)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:22:07,610 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:22:07,611 | fed_df.py:547 | Average fusion training loss : 0.016253027249127628, val accuracy : 0.601, best val accuracy : 0.6086
INFO flwr 2023-08-19 15:22:07,612 | common.py:35 | Avg. local train loss : 5.0899775989353655, train acc : 0.7646611111111112
INFO flwr 2023-08-19 15:22:10,549 | server.py:116 | fit progress: (21, 1.2791460968017578, {'server_test_acc': 0.608}, 1871.3197625228204)
INFO flwr 2023-08-19 15:22:10,549 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-19 15:22:15,216 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2032244)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2032247)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-19 15:22:48,372 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-19 15:22:48,525 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2032244)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2032261)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2032247)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2032453)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2032246)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2032240)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2032245)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2032452)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2032261)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2032245)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2032453)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2032246)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2032452)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2032240)[0m double free or corruption (fasttop)
E0819 15:22:52.246705735 2092436 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 15:23:35,536 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:23:35,537 | fed_df.py:547 | Average fusion training loss : 0.029209578678011893, val accuracy : 0.65012, best val accuracy : 0.66
INFO flwr 2023-08-19 15:23:35,538 | common.py:35 | Avg. local train loss : 5.217666912078857, train acc : 0.7557611111111112
INFO flwr 2023-08-19 15:23:38,299 | server.py:116 | fit progress: (22, 1.2345009765625, {'server_test_acc': 0.6439}, 1959.0704666879028)
INFO flwr 2023-08-19 15:23:38,300 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-19 15:23:42,951 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2178634)[0m corrupted size vs. prev_size in fastbins
DEBUG flwr 2023-08-19 15:24:16,081 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-19 15:24:16,237 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2178629)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2178631)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2178625)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2178634)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2178629)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2178630)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2178633)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2178628)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2178632)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2178633)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2178631)[0m malloc_consolidate(): invalid chunk size
E0819 15:24:16.934131517 2093874 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2178625)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2178630)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2178632)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2178628)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:25:03,208 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:25:03,208 | fed_df.py:547 | Average fusion training loss : 0.027845044121146204, val accuracy : 0.6448400000000001, best val accuracy : 0.6514
INFO flwr 2023-08-19 15:25:03,210 | common.py:35 | Avg. local train loss : 5.365004599094391, train acc : 0.7403888888888889
INFO flwr 2023-08-19 15:25:06,150 | server.py:116 | fit progress: (23, 1.2506061126708985, {'server_test_acc': 0.6423}, 2046.9208936071955)
INFO flwr 2023-08-19 15:25:06,150 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-19 15:25:10,781 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:25:43,838 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-19 15:25:43,993 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2330255)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2330262)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2330259)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2330263)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2330260)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2330264)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2330256)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2330257)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2330259)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2330255)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2330262)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2330257)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2330256)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2330260)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2330264)[0m corrupted size vs. prev_size in fastbins
E0819 15:25:46.180729717 2242289 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2330263)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:26:31,012 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:26:31,012 | fed_df.py:547 | Average fusion training loss : 0.019947822220623492, val accuracy : 0.65296, best val accuracy : 0.6622
INFO flwr 2023-08-19 15:26:31,014 | common.py:35 | Avg. local train loss : 5.079569729417563, train acc : 0.7680444444444444
INFO flwr 2023-08-19 15:26:33,709 | server.py:116 | fit progress: (24, 1.2252261932373048, {'server_test_acc': 0.6431}, 2134.4805909278803)
INFO flwr 2023-08-19 15:26:33,710 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-19 15:26:38,584 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2465568)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:27:11,001 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-19 15:27:11,115 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=2465577)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:27:11,214 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2465568)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2465570)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2465575)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2465579)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2465578)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2465577)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2465580)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2465576)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2465580)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465575)[0m double free or corruption (fasttop)
E0819 15:27:12.181466528 2387499 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2465570)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465578)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2465579)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2465576)[0m malloc_consolidate(): invalid chunk size
E0819 15:27:13.384765095 2518879 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 15:27:58,445 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:27:58,445 | fed_df.py:547 | Average fusion training loss : 0.026982956364750864, val accuracy : 0.65268, best val accuracy : 0.6614
INFO flwr 2023-08-19 15:27:58,447 | common.py:35 | Avg. local train loss : 5.179167385399341, train acc : 0.7595333333333333
INFO flwr 2023-08-19 15:28:01,271 | server.py:116 | fit progress: (25, 1.2321489898681641, {'server_test_acc': 0.6471}, 2222.0418013539165)
INFO flwr 2023-08-19 15:28:01,271 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-19 15:28:05,905 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:28:37,975 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-19 15:28:38,129 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2600175)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2600179)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2600180)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2600177)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2600198)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2600200)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2600201)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2600199)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2600199)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2600180)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2600200)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2600179)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2600201)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2600198)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2600175)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2600177)[0m malloc_consolidate(): invalid chunk size
E0819 15:28:40.299142966 2654402 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 15:29:25,261 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:29:25,262 | fed_df.py:547 | Average fusion training loss : 0.017123778469860552, val accuracy : 0.6156400000000001, best val accuracy : 0.6248
INFO flwr 2023-08-19 15:29:25,263 | common.py:35 | Avg. local train loss : 5.074653334170581, train acc : 0.7662888888888888
INFO flwr 2023-08-19 15:29:27,962 | server.py:116 | fit progress: (26, 1.2426529541015625, {'server_test_acc': 0.6205}, 2308.7328019188717)
INFO flwr 2023-08-19 15:29:27,962 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-19 15:29:32,674 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:30:04,545 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-19 15:30:04,701 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2733261)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2733334)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2733262)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2733265)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2733335)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2733266)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2733264)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2733336)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2733261)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2733336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2733335)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2733265)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2733262)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2733334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2733266)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2733264)[0m malloc_consolidate(): invalid chunk size
E0819 15:30:06.790549625 2654739 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 15:30:52,155 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:30:52,155 | fed_df.py:547 | Average fusion training loss : 0.02505827233940363, val accuracy : 0.6758, best val accuracy : 0.684
INFO flwr 2023-08-19 15:30:52,156 | common.py:35 | Avg. local train loss : 5.0472999639809135, train acc : 0.7734500000000001
INFO flwr 2023-08-19 15:30:54,893 | server.py:116 | fit progress: (27, 1.18745087890625, {'server_test_acc': 0.6661}, 2395.6640449007973)
INFO flwr 2023-08-19 15:30:54,893 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-19 15:30:59,592 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:31:31,533 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-19 15:31:31,686 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2866855)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2866857)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2866936)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2866856)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2866960)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2866958)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2866858)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2866957)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2866858)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2866936)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2866960)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2866855)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2866856)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2866958)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2866857)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2866957)[0m malloc_consolidate(): invalid chunk size
E0819 15:31:35.167754178 2788320 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0819 15:32:13.241536150 2974400 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 15:32:19,263 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:32:19,263 | fed_df.py:547 | Average fusion training loss : 0.024965827569365502, val accuracy : 0.65952, best val accuracy : 0.6696
INFO flwr 2023-08-19 15:32:19,264 | common.py:35 | Avg. local train loss : 5.082260715961456, train acc : 0.7690722222222223
INFO flwr 2023-08-19 15:32:21,998 | server.py:116 | fit progress: (28, 1.235491241455078, {'server_test_acc': 0.6504}, 2482.7696121241897)
INFO flwr 2023-08-19 15:32:21,999 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-19 15:32:26,772 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2999890)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-19 15:32:58,401 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-19 15:32:58,563 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2999890)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2999963)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3000033)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3000032)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2999961)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2999960)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3000031)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2999962)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2999963)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3000033)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3000031)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999960)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2999961)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2999962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3000032)[0m malloc_consolidate(): invalid chunk size
E0819 15:33:01.255985280 3054125 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-19 15:33:51,402 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:33:51,402 | fed_df.py:547 | Average fusion training loss : 0.021553891722112892, val accuracy : 0.66812, best val accuracy : 0.6722
INFO flwr 2023-08-19 15:33:51,404 | common.py:35 | Avg. local train loss : 4.960921342670918, train acc : 0.7806000000000001
INFO flwr 2023-08-19 15:33:54,092 | server.py:116 | fit progress: (29, 1.2102150756835937, {'server_test_acc': 0.6619}, 2574.8628774811514)
INFO flwr 2023-08-19 15:33:54,092 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-19 15:33:58,743 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-19 15:34:30,670 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-19 15:34:30,784 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-19 15:34:30,882 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3137959)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3137963)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3137964)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3138101)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3137962)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3138032)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3138102)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3138033)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3137963)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3137962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3137959)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3138032)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3138101)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3138033)[0m double free or corruption (fasttop)
E0819 15:34:33.071473254 3192614 chttp2_transport.cc:1079]             ipv4:145.136.62.13:56979: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3137964)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3138102)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-19 15:35:16,580 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-19 15:35:16,580 | fed_df.py:547 | Average fusion training loss : 0.021137755636125802, val accuracy : 0.6158800000000001, best val accuracy : 0.624
INFO flwr 2023-08-19 15:35:16,582 | common.py:35 | Avg. local train loss : 4.966663216054439, train acc : 0.7790055555555555
INFO flwr 2023-08-19 15:35:19,194 | server.py:116 | fit progress: (30, 1.2796738708496094, {'server_test_acc': 0.616}, 2659.965030142106)
INFO flwr 2023-08-19 15:35:19,194 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-19 15:35:19,194 | server.py:144 | FL finished in 2659.9653808288276
INFO flwr 2023-08-19 15:35:19,194 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-19 15:35:19,195 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-19 15:35:19,196 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.817745880126953), (2, 1.848102978515625), (3, 1.7487741577148437), (4, 1.6199519104003905), (5, 1.5195803314208984), (6, 1.4482728424072266), (7, 1.365871759033203), (8, 1.3774698364257814), (9, 1.3200352142333984), (10, 1.2975720947265625), (11, 1.3116632537841797), (12, 1.281612744140625), (13, 1.275920440673828), (14, 1.2521688262939452), (15, 1.2955298461914062), (16, 1.282725762939453), (17, 1.3251280426025391), (18, 1.220770147705078), (19, 1.276156591796875), (20, 1.1865874633789062), (21, 1.2791460968017578), (22, 1.2345009765625), (23, 1.2506061126708985), (24, 1.2252261932373048), (25, 1.2321489898681641), (26, 1.2426529541015625), (27, 1.18745087890625), (28, 1.235491241455078), (29, 1.2102150756835937), (30, 1.2796738708496094)]
INFO flwr 2023-08-19 15:35:19,196 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.3088), (2, 0.3435), (3, 0.4078), (4, 0.4161), (5, 0.4621), (6, 0.5183), (7, 0.5565), (8, 0.5421), (9, 0.5721), (10, 0.595), (11, 0.5799), (12, 0.6074), (13, 0.5886), (14, 0.6082), (15, 0.5827), (16, 0.5905), (17, 0.5893), (18, 0.6393), (19, 0.6133), (20, 0.659), (21, 0.608), (22, 0.6439), (23, 0.6423), (24, 0.6431), (25, 0.6471), (26, 0.6205), (27, 0.6661), (28, 0.6504), (29, 0.6619), (30, 0.616)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn13: task 0: Aborted
srun: Terminating StepId=3422098.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3422098
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 01:49:14
CPU Efficiency: 12.49% of 14:34:48 core-walltime
Job Wall-clock time: 00:48:36
Memory Utilized: 47.41 GB
Memory Efficiency: 39.51% of 120.00 GB
