-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:100000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:5
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3342124/1692105346_890275208', seed=84, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3342124/1692105346_890275208/single_img_crops/crops
100000 took 0.70min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 15:16:45,263 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 15:16:45,263 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3342124/1692105346_890275208/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3342124/1692105346_890275208/cifar-10-python.tar.gz to /scratch-local/sunnys.3342124/1692105346_890275208
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [225 194 247 272 217 251 256 333 258 247]
INFO flwr 2023-08-15 15:19:03,468 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 15:19:06,347	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-15 15:19:07,399 | app.py:179 | Flower VCE: Ray initialized with resources: {'memory': 103079215104.0, 'GPU': 1.0, 'node:145.136.62.19': 1.0, 'accelerator_type:A100': 1.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0}
INFO flwr 2023-08-15 15:19:07,399 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 15:19:07,399 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 15:19:07,399 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 15:19:17,450 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-15 15:19:17,450 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 15:19:26,365 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:20:16,891 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-15 15:20:17,104 | fed_df.py:365 | Warm start at round 1
[2m[36m(launch_and_fit pid=755583)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:20:17,215 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=755584)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=755583)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=755586)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=755587)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=755590)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=755589)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=755588)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=755585)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=755586)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=755588)[0m malloc_consolidate(): invalid chunk size
E0815 15:20:17.939310829  752382 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
[2m[36m(launch_and_fit pid=755584)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=755585)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=755587)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=755590)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=755589)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:20:47,950 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:20:47,950 | fed_df.py:547 | Average fusion training loss : 0.05286400155723095, val accuracy : 0.38856, best val accuracy : 0.4108
INFO flwr 2023-08-15 15:20:47,951 | common.py:35 | Avg. local train loss : 8.834121184051037, train acc : 0.37654166666666666
INFO flwr 2023-08-15 15:20:50,523 | server.py:116 | fit progress: (1, 1.6451279907226561, {'server_test_acc': 0.4249}, 93.07212778413668)
INFO flwr 2023-08-15 15:20:50,523 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 15:20:59,702 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=830192)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=830194)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:21:47,826 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=830222)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:21:48,041 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-15 15:21:48,183 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=830217)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=830192)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=830194)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=830217)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=830218)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=830219)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=830221)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=830222)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=830220)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=830219)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=830220)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=830221)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=830218)[0m malloc_consolidate(): invalid chunk size
E0815 15:21:52.104958088  802919 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
INFO flwr 2023-08-15 15:22:21,812 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:22:21,812 | fed_df.py:547 | Average fusion training loss : 0.013782885357737541, val accuracy : 0.55428, best val accuracy : 0.5646
INFO flwr 2023-08-15 15:22:21,813 | common.py:35 | Avg. local train loss : 7.4936220571398735, train acc : 0.5236527777777777
INFO flwr 2023-08-15 15:22:24,633 | server.py:116 | fit progress: (2, 1.4187111236572265, {'server_test_acc': 0.558}, 187.18247443577275)
INFO flwr 2023-08-15 15:22:24,633 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 15:22:34,049 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=905160)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:23:23,195 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=905162)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:23:23,412 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 15:23:23,525 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=905157)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=905162)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=905163)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=905161)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=905156)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=905159)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=905158)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=905160)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=905156)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=905159)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=905157)[0m malloc_consolidate(): invalid chunk size
E0815 15:23:25.035711518  952699 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=905158)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=905163)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:23:58,467 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:23:58,468 | fed_df.py:547 | Average fusion training loss : 0.013274890074506402, val accuracy : 0.61404, best val accuracy : 0.624
INFO flwr 2023-08-15 15:23:58,469 | common.py:35 | Avg. local train loss : 6.345032532513142, train acc : 0.6539472222222222
INFO flwr 2023-08-15 15:24:01,437 | server.py:116 | fit progress: (3, 1.3571772216796876, {'server_test_acc': 0.6212}, 283.9863127861172)
INFO flwr 2023-08-15 15:24:01,437 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 15:24:10,960 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=979922)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:24:59,095 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=979927)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 15:24:59,312 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 15:24:59,423 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=979922)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=979926)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=979925)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=979927)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=979930)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=979929)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=979928)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=979931)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=979931)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=979929)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=979925)[0m double free or corruption (fasttop)
E0815 15:25:00.192176611 1027349 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=979930)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=979926)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=979928)[0m malloc_consolidate(): invalid chunk size
E0815 15:25:32.636392453 1027651 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-15 15:25:34,009 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:25:34,009 | fed_df.py:547 | Average fusion training loss : 0.013135236732661724, val accuracy : 0.6574800000000001, best val accuracy : 0.668
INFO flwr 2023-08-15 15:25:34,010 | common.py:35 | Avg. local train loss : 5.710540841519832, train acc : 0.718436111111111
INFO flwr 2023-08-15 15:25:36,927 | server.py:116 | fit progress: (4, 1.3466005798339844, {'server_test_acc': 0.6541}, 379.4770287219435)
INFO flwr 2023-08-15 15:25:36,928 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 15:25:46,489 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1054227)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:26:34,846 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1054224)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1054222)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:26:35,065 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 15:26:35,210 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1054220)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1054223)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1054225)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1054218)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1054222)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1054224)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1054226)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1054227)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1054226)[0m malloc_consolidate(): invalid chunk size
E0815 15:26:36.226678864 1101353 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=1054218)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1054225)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1054220)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1054223)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:27:10,788 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:27:10,789 | fed_df.py:547 | Average fusion training loss : 0.01351096011325717, val accuracy : 0.67644, best val accuracy : 0.6822
INFO flwr 2023-08-15 15:27:10,790 | common.py:35 | Avg. local train loss : 5.32083098962903, train acc : 0.7590666666666667
INFO flwr 2023-08-15 15:27:13,667 | server.py:116 | fit progress: (5, 1.3984463989257812, {'server_test_acc': 0.6756}, 476.2168768150732)
INFO flwr 2023-08-15 15:27:13,668 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 15:27:23,259 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1128219)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1128211)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:28:11,977 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1128217)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:28:12,194 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 15:28:12,304 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1128211)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1128213)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1128214)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1128215)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1128216)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1128218)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1128217)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1128219)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1128214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1128215)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1128218)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1128216)[0m double free or corruption (fasttop)
E0815 15:28:13.480136850 1101774 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=1128213)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:28:47,143 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:28:47,143 | fed_df.py:547 | Average fusion training loss : 0.011849419375881553, val accuracy : 0.69188, best val accuracy : 0.6976
INFO flwr 2023-08-15 15:28:47,145 | common.py:35 | Avg. local train loss : 5.097387240454554, train acc : 0.7813138888888889
INFO flwr 2023-08-15 15:28:50,046 | server.py:116 | fit progress: (6, 1.4672695922851562, {'server_test_acc': 0.695}, 572.5957478331402)
INFO flwr 2023-08-15 15:28:50,046 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 15:28:59,531 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:29:47,709 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1231504)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:29:47,927 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 15:29:48,037 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1231504)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1231671)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1231501)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1231525)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1231499)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1231565)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1231618)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1231644)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1231501)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1231671)[0m malloc_consolidate(): invalid chunk size
E0815 15:29:48.970890720 1287151 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=1231565)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1231525)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1231618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1231644)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1231499)[0m malloc_consolidate(): invalid chunk size
E0815 15:29:50.386924101 1288359 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
INFO flwr 2023-08-15 15:30:27,579 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:30:27,579 | fed_df.py:547 | Average fusion training loss : 0.012630618153139948, val accuracy : 0.70148, best val accuracy : 0.711
INFO flwr 2023-08-15 15:30:27,580 | common.py:35 | Avg. local train loss : 4.912904693931341, train acc : 0.8017916666666666
INFO flwr 2023-08-15 15:30:30,473 | server.py:116 | fit progress: (7, 1.4916955780029297, {'server_test_acc': 0.7139}, 673.0226984401233)
INFO flwr 2023-08-15 15:30:30,473 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 15:30:40,045 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1313861)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:31:28,601 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 15:31:28,818 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 15:31:28,930 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1313856)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1313862)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1313861)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1313860)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1313855)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1313864)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1313865)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1313863)[0m Fitting Client 2
E0815 15:31:29.378362676 1360656 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=1313865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1313856)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1313860)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1313864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1313863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1313855)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:32:03,555 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:32:03,555 | fed_df.py:547 | Average fusion training loss : 0.014622355844825507, val accuracy : 0.70624, best val accuracy : 0.7156
INFO flwr 2023-08-15 15:32:03,556 | common.py:35 | Avg. local train loss : 4.829583273828029, train acc : 0.8145361111111111
INFO flwr 2023-08-15 15:32:06,522 | server.py:116 | fit progress: (8, 1.5775339477539063, {'server_test_acc': 0.7147}, 769.0710825268179)
INFO flwr 2023-08-15 15:32:06,522 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 15:32:16,038 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:33:04,144 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-15 15:33:04,361 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-15 15:33:04,472 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1387884)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1387882)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1387880)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1387886)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1387887)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1387893)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1387894)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1387892)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1387892)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1387894)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1387886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1387882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1387884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1387880)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1387887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1387893)[0m malloc_consolidate(): invalid chunk size
E0815 15:33:06.750689526 1360995 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-15 15:33:38,922 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:33:38,923 | fed_df.py:547 | Average fusion training loss : 0.01327657355275005, val accuracy : 0.71052, best val accuracy : 0.722
INFO flwr 2023-08-15 15:33:38,924 | common.py:35 | Avg. local train loss : 4.758925753086805, train acc : 0.8249500000000001
INFO flwr 2023-08-15 15:33:41,769 | server.py:116 | fit progress: (9, 1.564435693359375, {'server_test_acc': 0.7283}, 864.3186159129255)
INFO flwr 2023-08-15 15:33:41,769 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 15:33:51,248 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1462060)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:34:39,502 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1462054)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:34:39,721 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 15:34:39,831 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1462056)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1462054)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1462060)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1462062)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1462059)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1462064)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1462063)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1462061)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1462061)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1462059)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1462056)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1462062)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1462063)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1462064)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:35:14,441 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:35:14,441 | fed_df.py:547 | Average fusion training loss : 0.011166370597667992, val accuracy : 0.7224400000000001, best val accuracy : 0.7354
INFO flwr 2023-08-15 15:35:14,443 | common.py:35 | Avg. local train loss : 4.687717378512025, train acc : 0.8350861111111111
INFO flwr 2023-08-15 15:35:17,340 | server.py:116 | fit progress: (10, 1.5797230346679687, {'server_test_acc': 0.7363}, 959.8897639731877)
INFO flwr 2023-08-15 15:35:17,340 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 15:35:26,826 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:36:14,881 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1536024)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1536020)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:36:15,100 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-15 15:36:15,214 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1536020)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1536022)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1536021)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1536025)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1536026)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1536027)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1536017)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1536024)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1536017)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1536027)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1536021)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1536022)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1536025)[0m malloc_consolidate(): invalid chunk size
E0815 15:36:16.473708216 1583836 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=1536026)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:36:50,166 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:36:50,167 | fed_df.py:547 | Average fusion training loss : 0.010993556003086269, val accuracy : 0.7308399999999999, best val accuracy : 0.741
INFO flwr 2023-08-15 15:36:50,168 | common.py:35 | Avg. local train loss : 4.616358998417854, train acc : 0.8431861111111112
INFO flwr 2023-08-15 15:36:53,100 | server.py:116 | fit progress: (11, 1.6609696502685547, {'server_test_acc': 0.7432}, 1055.6497657899745)
INFO flwr 2023-08-15 15:36:53,100 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 15:37:02,590 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1610555)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:37:50,330 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-15 15:37:50,548 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 15:37:50,662 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1610555)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1610553)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1610557)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1610558)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1610552)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1610561)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1610559)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1610560)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1610553)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1610560)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1610558)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1610552)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1610557)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1610561)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1610559)[0m malloc_consolidate(): invalid chunk size
E0815 15:37:52.017210957 1658610 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
E0815 15:37:52.017345790 1658610 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-15 15:38:24,996 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:38:24,997 | fed_df.py:547 | Average fusion training loss : 0.01071138765104115, val accuracy : 0.73848, best val accuracy : 0.752
INFO flwr 2023-08-15 15:38:24,998 | common.py:35 | Avg. local train loss : 4.613059141114355, train acc : 0.8465055555555554
INFO flwr 2023-08-15 15:38:27,936 | server.py:116 | fit progress: (12, 1.650117056274414, {'server_test_acc': 0.7546}, 1150.4850939237513)
INFO flwr 2023-08-15 15:38:27,936 | server.py:163 | evaluate_round 12: no clients selected, cancel
E0815 15:38:29.144867914 1683417 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
DEBUG flwr 2023-08-15 15:38:37,484 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1684495)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:39:24,875 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 15:39:25,093 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 15:39:25,221 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1684495)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1684501)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1684503)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1684504)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1684505)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1684499)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1684500)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1684502)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1684504)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1684502)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1684501)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=1684500)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1684503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1684499)[0m malloc_consolidate(): invalid chunk size
E0815 15:39:26.755970008 1732269 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=1684505)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 15:40:00,257 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:40:00,257 | fed_df.py:547 | Average fusion training loss : 0.010382583911530673, val accuracy : 0.7447199999999999, best val accuracy : 0.757
INFO flwr 2023-08-15 15:40:00,258 | common.py:35 | Avg. local train loss : 4.5404201105237005, train acc : 0.8545166666666668
INFO flwr 2023-08-15 15:40:03,208 | server.py:116 | fit progress: (13, 1.6469786254882812, {'server_test_acc': 0.7594}, 1245.7573595438153)
INFO flwr 2023-08-15 15:40:03,208 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 15:40:13,090 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1758510)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:41:00,897 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-15 15:41:01,114 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 15:41:01,261 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1758510)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1758512)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1758513)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1758515)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1758516)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1758517)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1758514)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1758518)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1758518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1758515)[0m double free or corruption (fasttop)
E0815 15:41:02.083318835 1806003 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1758513)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1758512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1758516)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1758514)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1758517)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:41:42,540 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:41:42,540 | fed_df.py:547 | Average fusion training loss : 0.0086283163074404, val accuracy : 0.75092, best val accuracy : 0.7618
INFO flwr 2023-08-15 15:41:42,542 | common.py:35 | Avg. local train loss : 4.414964477345348, train acc : 0.8688583333333333
INFO flwr 2023-08-15 15:41:45,508 | server.py:116 | fit progress: (14, 1.7005710327148438, {'server_test_acc': 0.7646}, 1348.0576558359899)
INFO flwr 2023-08-15 15:41:45,508 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 15:41:55,129 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1832907)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1832913)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:42:42,991 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-15 15:42:43,209 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-15 15:42:43,321 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1832907)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1832913)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1832911)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1832912)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1832914)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1832919)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1832920)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1832915)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1832914)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1832912)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1832911)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1832920)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1832919)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1832915)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:43:19,853 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:43:19,854 | fed_df.py:547 | Average fusion training loss : 0.008913435955531896, val accuracy : 0.7487199999999999, best val accuracy : 0.767
INFO flwr 2023-08-15 15:43:19,855 | common.py:35 | Avg. local train loss : 4.4284783590584995, train acc : 0.8661638888888888
INFO flwr 2023-08-15 15:43:22,817 | server.py:116 | fit progress: (15, 1.707369873046875, {'server_test_acc': 0.7639}, 1445.366166673135)
INFO flwr 2023-08-15 15:43:22,817 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 15:43:32,426 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1911689)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1911717)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:44:20,470 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-15 15:44:20,688 | fed_df.py:365 | Warm start at round 16
INFO flwr 2023-08-15 15:44:20,801 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1911689)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1911702)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1911717)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1911691)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1911718)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1911720)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1911719)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1911721)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1911702)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1911720)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1911718)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1911721)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1911691)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1911719)[0m double free or corruption (fasttop)
E0815 15:44:26.231808561 1979475 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:44:56,970 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:44:56,970 | fed_df.py:547 | Average fusion training loss : 0.01043601854145527, val accuracy : 0.75396, best val accuracy : 0.7678
INFO flwr 2023-08-15 15:44:56,972 | common.py:35 | Avg. local train loss : 4.394936773180961, train acc : 0.8703805555555555
INFO flwr 2023-08-15 15:44:59,955 | server.py:116 | fit progress: (16, 1.69414765625, {'server_test_acc': 0.7708}, 1542.504138811957)
INFO flwr 2023-08-15 15:44:59,955 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 15:45:09,607 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2018110)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:45:57,397 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-15 15:45:57,616 | fed_df.py:365 | Warm start at round 17
[2m[36m(launch_and_fit pid=2018111)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2018108)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:45:57,730 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2018111)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2018110)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2018108)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2018113)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2018114)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2018117)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2018116)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2018115)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2018113)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2018115)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2018117)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2018114)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2018116)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:46:39,385 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:46:39,385 | fed_df.py:547 | Average fusion training loss : 0.008293202862143516, val accuracy : 0.7514, best val accuracy : 0.7644
INFO flwr 2023-08-15 15:46:39,387 | common.py:35 | Avg. local train loss : 4.359194984287024, train acc : 0.8737027777777778
INFO flwr 2023-08-15 15:46:42,367 | server.py:116 | fit progress: (17, 1.7367924072265626, {'server_test_acc': 0.7704}, 1644.9160749930888)
INFO flwr 2023-08-15 15:46:42,367 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 15:46:51,996 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2092283)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:47:39,493 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2092282)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:47:39,713 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 15:47:39,829 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2092283)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2092282)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2092284)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2092285)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2092287)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2092288)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2092286)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2092289)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2092285)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2092284)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2092287)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2092289)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2092288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2092286)[0m double free or corruption (fasttop)
E0815 15:47:42.136440658 1980770 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:48:16,156 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:48:16,156 | fed_df.py:547 | Average fusion training loss : 0.009196197329089046, val accuracy : 0.7567600000000001, best val accuracy : 0.7734
INFO flwr 2023-08-15 15:48:16,158 | common.py:35 | Avg. local train loss : 4.319963960722089, train acc : 0.8798388888888888
INFO flwr 2023-08-15 15:48:19,123 | server.py:116 | fit progress: (18, 1.7196027160644531, {'server_test_acc': 0.7691}, 1741.6730155837722)
INFO flwr 2023-08-15 15:48:19,124 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 15:48:28,672 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2166044)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:49:16,401 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2166052)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:49:16,620 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 15:49:16,732 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2166044)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2166046)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2166048)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2166052)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2166055)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2166054)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2166053)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2166056)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2166046)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2166055)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2166048)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2166053)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2166056)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2166054)[0m double free or corruption (fasttop)
E0815 15:49:20.208687767 2140421 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:49:20.208764797 2140421 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:49:20.208775265 2140421 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:49:52,949 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:49:52,950 | fed_df.py:547 | Average fusion training loss : 0.00802807832416147, val accuracy : 0.7598799999999999, best val accuracy : 0.7712
INFO flwr 2023-08-15 15:49:52,951 | common.py:35 | Avg. local train loss : 4.289224613830448, train acc : 0.8815416666666667
INFO flwr 2023-08-15 15:49:55,887 | server.py:116 | fit progress: (19, 1.7186906860351563, {'server_test_acc': 0.7727}, 1838.4368961127475)
INFO flwr 2023-08-15 15:49:55,888 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 15:50:05,582 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2240581)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2240573)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:50:53,782 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 15:50:54,002 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 15:50:54,150 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2240571)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2240575)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2240573)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2240576)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2240582)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2240581)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2240579)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2240580)[0m Fitting Client 16
E0815 15:50:54.702366929 2287597 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2240580)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2240576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2240571)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2240579)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2240582)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:51:30,757 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:51:30,758 | fed_df.py:547 | Average fusion training loss : 0.008379250925965608, val accuracy : 0.76228, best val accuracy : 0.7732
INFO flwr 2023-08-15 15:51:30,759 | common.py:35 | Avg. local train loss : 4.276693855226041, train acc : 0.8828027777777778
INFO flwr 2023-08-15 15:51:33,785 | server.py:116 | fit progress: (20, 1.7239777221679689, {'server_test_acc': 0.7753}, 1936.3344155107625)
INFO flwr 2023-08-15 15:51:33,785 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 15:51:43,659 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:52:31,439 | server.py:229 | fit_round 21 received 8 results and 0 failures
INFO flwr 2023-08-15 15:52:31,663 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 15:52:31,813 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2314754)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2314753)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2314756)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2314758)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2314760)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2314761)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2314762)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2314763)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2314760)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2314753)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2314754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2314761)[0m malloc_consolidate(): invalid chunk size
E0815 15:52:32.501968812 2288022 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2314762)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2314756)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2314758)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2314763)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:53:08,742 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:53:08,742 | fed_df.py:547 | Average fusion training loss : 0.0077491686940193176, val accuracy : 0.7674000000000001, best val accuracy : 0.7744
INFO flwr 2023-08-15 15:53:08,743 | common.py:35 | Avg. local train loss : 4.227412341162562, train acc : 0.8875361111111112
INFO flwr 2023-08-15 15:53:11,745 | server.py:116 | fit progress: (21, 1.7117572845458984, {'server_test_acc': 0.7764}, 2034.2945854980499)
INFO flwr 2023-08-15 15:53:11,745 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 15:53:21,496 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:54:09,844 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-15 15:54:10,063 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 15:54:10,178 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2388860)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2388864)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2388865)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2388863)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2388866)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2388868)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2388862)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2388867)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2388864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2388860)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2388867)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2388865)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2388868)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2388862)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2388863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2388866)[0m double free or corruption (fasttop)
E0815 15:54:12.771841421 2437013 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:54:46,873 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:54:46,873 | fed_df.py:547 | Average fusion training loss : 0.007622949492186308, val accuracy : 0.7665599999999999, best val accuracy : 0.774
INFO flwr 2023-08-15 15:54:46,874 | common.py:35 | Avg. local train loss : 4.1825381379574536, train acc : 0.8937444444444445
INFO flwr 2023-08-15 15:54:49,868 | server.py:116 | fit progress: (22, 1.726216909790039, {'server_test_acc': 0.7792}, 2132.4175289231353)
INFO flwr 2023-08-15 15:54:49,868 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 15:54:59,450 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:55:47,491 | server.py:229 | fit_round 23 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2463139)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:55:47,711 | fed_df.py:365 | Warm start at round 23
[2m[36m(launch_and_fit pid=2463141)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:55:47,825 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2463139)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2463143)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2463145)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2463141)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2463146)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2463152)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2463150)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2463151)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2463143)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2463152)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2463146)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2463145)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2463150)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2463151)[0m malloc_consolidate(): invalid chunk size
E0815 15:55:49.453180183 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453260598 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453271583 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453279690 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453287501 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453295033 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453302653 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453310057 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453317522 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:55:49.453324998 2510965 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:56:24,538 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:56:24,538 | fed_df.py:547 | Average fusion training loss : 0.005848714453633875, val accuracy : 0.7718, best val accuracy : 0.7826
INFO flwr 2023-08-15 15:56:24,540 | common.py:35 | Avg. local train loss : 4.235118013992905, train acc : 0.8861416666666666
INFO flwr 2023-08-15 15:56:27,555 | server.py:116 | fit progress: (23, 1.7353561096191406, {'server_test_acc': 0.7811}, 2230.1048478549346)
INFO flwr 2023-08-15 15:56:27,556 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 15:56:37,313 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2537093)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:57:25,231 | server.py:229 | fit_round 24 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2537095)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:57:25,452 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 15:57:25,567 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2537093)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2537095)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2537097)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2537099)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2537100)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2537098)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2537101)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2537102)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2537097)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2537101)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2537102)[0m double free or corruption (fasttop)
E0815 15:57:26.398846140 2584324 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2537098)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2537100)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2537099)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:58:02,398 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:58:02,399 | fed_df.py:547 | Average fusion training loss : 0.00694708679523319, val accuracy : 0.77212, best val accuracy : 0.781
INFO flwr 2023-08-15 15:58:02,400 | common.py:35 | Avg. local train loss : 4.1641660366207365, train acc : 0.8938472222222221
INFO flwr 2023-08-15 15:58:05,397 | server.py:116 | fit progress: (24, 1.7195272918701172, {'server_test_acc': 0.7801}, 2327.9461656170897)
INFO flwr 2023-08-15 15:58:05,397 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 15:58:15,235 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2611105)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2611099)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2611107)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:59:03,295 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-15 15:59:03,514 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 15:59:03,627 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2611099)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2611101)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2611103)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2611105)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2611106)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2611109)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2611107)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2611108)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2611108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2611103)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2611106)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2611101)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2611109)[0m double free or corruption (fasttop)
E0815 15:59:05.037717691 2659162 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:59:40,868 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:59:40,868 | fed_df.py:547 | Average fusion training loss : 0.0069463458638638256, val accuracy : 0.78148, best val accuracy : 0.7866
INFO flwr 2023-08-15 15:59:40,870 | common.py:35 | Avg. local train loss : 4.18633986376226, train acc : 0.8907861111111112
INFO flwr 2023-08-15 15:59:43,857 | server.py:116 | fit progress: (25, 1.75392392578125, {'server_test_acc': 0.7861}, 2426.4068442047574)
INFO flwr 2023-08-15 15:59:43,858 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 15:59:53,461 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2709404)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2709408)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2709409)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:00:42,081 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-15 16:00:42,299 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 16:00:42,413 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2709404)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2709405)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2709406)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2709408)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2709412)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2709411)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2709409)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2709410)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2709405)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2709411)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2709412)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2709406)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2709410)[0m malloc_consolidate(): invalid chunk size
E0815 16:00:44.829081363 2659297 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 16:01:18,343 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:01:18,343 | fed_df.py:547 | Average fusion training loss : 0.006041082487441599, val accuracy : 0.7873599999999998, best val accuracy : 0.7928
INFO flwr 2023-08-15 16:01:18,345 | common.py:35 | Avg. local train loss : 4.176824731007218, train acc : 0.8928583333333333
INFO flwr 2023-08-15 16:01:21,324 | server.py:116 | fit progress: (26, 1.767733590698242, {'server_test_acc': 0.7839}, 2523.8738656858914)
INFO flwr 2023-08-15 16:01:21,325 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 16:01:30,921 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2797087)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 16:02:18,993 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 16:02:19,216 | fed_df.py:365 | Warm start at round 27
[2m[36m(launch_and_fit pid=2797125)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:02:19,329 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2797087)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2797124)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2797122)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2797125)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2797123)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2797146)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2797148)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2797147)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2797122)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2797123)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2797124)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2797148)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2797146)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2797147)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:02:55,000 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:02:55,001 | fed_df.py:547 | Average fusion training loss : 0.00796670928876847, val accuracy : 0.78272, best val accuracy : 0.7936
INFO flwr 2023-08-15 16:02:55,002 | common.py:35 | Avg. local train loss : 4.108380423486232, train acc : 0.8983750000000001
INFO flwr 2023-08-15 16:02:58,005 | server.py:116 | fit progress: (27, 1.6867338958740234, {'server_test_acc': 0.7926}, 2620.5540897399187)
INFO flwr 2023-08-15 16:02:58,005 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 16:03:07,735 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2871092)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:03:55,360 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-15 16:03:55,579 | fed_df.py:365 | Warm start at round 28
INFO flwr 2023-08-15 16:03:55,692 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2871092)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2871094)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2871096)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2871098)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2871097)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2871100)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2871099)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2871101)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2871096)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2871094)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871097)[0m corrupted size vs. prev_size in fastbins
E0815 16:03:56.336380519 2844405 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2871099)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2871098)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871101)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2871100)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:04:31,425 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:04:31,426 | fed_df.py:547 | Average fusion training loss : 0.008154837877489626, val accuracy : 0.78572, best val accuracy : 0.7916
INFO flwr 2023-08-15 16:04:31,427 | common.py:35 | Avg. local train loss : 4.1025891412049535, train acc : 0.8988916666666668
INFO flwr 2023-08-15 16:04:34,414 | server.py:116 | fit progress: (28, 1.7392057708740234, {'server_test_acc': 0.7884}, 2716.963143184781)
INFO flwr 2023-08-15 16:04:34,414 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 16:04:44,182 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2945874)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:05:31,905 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 16:05:32,126 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-15 16:05:32,241 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2945874)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2945872)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2945879)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2945880)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2945881)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2945878)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2945882)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2945883)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2945872)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2945883)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2945879)[0m malloc_consolidate(): invalid chunk size
E0815 16:05:32.963976291 2992805 chttp2_transport.cc:1079]             ipv4:145.136.62.19:58558: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2945878)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2945880)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2945881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2945882)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:06:08,626 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:06:08,626 | fed_df.py:547 | Average fusion training loss : 0.007581245984882116, val accuracy : 0.78836, best val accuracy : 0.792
INFO flwr 2023-08-15 16:06:08,628 | common.py:35 | Avg. local train loss : 4.018189680203795, train acc : 0.9076472222222223
INFO flwr 2023-08-15 16:06:11,643 | server.py:116 | fit progress: (29, 1.7047583923339844, {'server_test_acc': 0.7899}, 2814.192105898168)
INFO flwr 2023-08-15 16:06:11,643 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 16:06:21,348 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:07:09,944 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 16:07:10,165 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 16:07:10,282 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3020108)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3020111)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3020110)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3020109)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3020112)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3020113)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3020115)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3020114)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3020109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3020115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3020111)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3020113)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3020112)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3020114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3020110)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3020108)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:07:46,144 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:07:46,144 | fed_df.py:547 | Average fusion training loss : 0.00906375615298748, val accuracy : 0.79112, best val accuracy : 0.7964
INFO flwr 2023-08-15 16:07:46,146 | common.py:35 | Avg. local train loss : 3.9945489030331376, train acc : 0.9081527777777778
INFO flwr 2023-08-15 16:07:49,107 | server.py:116 | fit progress: (30, 1.7197585479736328, {'server_test_acc': 0.7936}, 2911.6566015691496)
INFO flwr 2023-08-15 16:07:49,107 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 16:07:49,107 | server.py:144 | FL finished in 2911.656982345041
INFO flwr 2023-08-15 16:07:49,108 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 16:07:49,109 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 16:07:49,109 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.6451279907226561), (2, 1.4187111236572265), (3, 1.3571772216796876), (4, 1.3466005798339844), (5, 1.3984463989257812), (6, 1.4672695922851562), (7, 1.4916955780029297), (8, 1.5775339477539063), (9, 1.564435693359375), (10, 1.5797230346679687), (11, 1.6609696502685547), (12, 1.650117056274414), (13, 1.6469786254882812), (14, 1.7005710327148438), (15, 1.707369873046875), (16, 1.69414765625), (17, 1.7367924072265626), (18, 1.7196027160644531), (19, 1.7186906860351563), (20, 1.7239777221679689), (21, 1.7117572845458984), (22, 1.726216909790039), (23, 1.7353561096191406), (24, 1.7195272918701172), (25, 1.75392392578125), (26, 1.767733590698242), (27, 1.6867338958740234), (28, 1.7392057708740234), (29, 1.7047583923339844), (30, 1.7197585479736328)]
INFO flwr 2023-08-15 16:07:49,109 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4249), (2, 0.558), (3, 0.6212), (4, 0.6541), (5, 0.6756), (6, 0.695), (7, 0.7139), (8, 0.7147), (9, 0.7283), (10, 0.7363), (11, 0.7432), (12, 0.7546), (13, 0.7594), (14, 0.7646), (15, 0.7639), (16, 0.7708), (17, 0.7704), (18, 0.7691), (19, 0.7727), (20, 0.7753), (21, 0.7764), (22, 0.7792), (23, 0.7811), (24, 0.7801), (25, 0.7861), (26, 0.7839), (27, 0.7926), (28, 0.7884), (29, 0.7899), (30, 0.7936)]}
double free or corruption (fasttop)
srun: error: gcn19: task 0: Aborted
srun: Terminating StepId=3342124.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3342124
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:02:39
CPU Efficiency: 12.63% of 16:10:48 core-walltime
Job Wall-clock time: 00:53:56
Memory Utilized: 62.55 GB
Memory Efficiency: 52.13% of 120.00 GB
