-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:100000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:100
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3342129/1692105348_172759817', seed=42, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3342129/1692105348_172759817/single_img_crops/crops
100000 took 1.05min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 15:17:07,633 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 15:17:07,633 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3342129/1692105348_172759817/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3342129/1692105348_172759817/cifar-10-python.tar.gz to /scratch-local/sunnys.3342129/1692105348_172759817
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [256 249 217 265 244 275 235 226 275 258]
INFO flwr 2023-08-15 15:17:52,984 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 15:17:56,838	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8266 [39m[22m
INFO flwr 2023-08-15 15:17:57,848 | app.py:179 | Flower VCE: Ray initialized with resources: {'accelerator_type:A100': 1.0, 'GPU': 1.0, 'memory': 103079215104.0, 'node:145.136.62.51': 1.0, 'object_store_memory': 61847529062.0, 'CPU': 18.0}
INFO flwr 2023-08-15 15:17:57,849 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 15:17:57,849 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 15:17:57,849 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 15:18:05,158 | server.py:91 | initial parameters (loss, other metrics): 2.3234217651367186, {'server_test_acc': 0.108}
INFO flwr 2023-08-15 15:18:05,158 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 15:18:13,944 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3222680)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:19:05,062 | server.py:229 | fit_round 1 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3222673)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3222675)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3222676)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:19:05,273 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-15 15:19:05,387 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3222673)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3222676)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3222677)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3222675)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3222679)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3222680)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3222674)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3222678)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3222679)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3222674)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3222678)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3222677)[0m malloc_consolidate(): invalid chunk size
E0815 15:19:09.389680111 3216472 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
INFO flwr 2023-08-15 15:19:38,055 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:19:38,055 | fed_df.py:547 | Average fusion training loss : 0.02706234512478113, val accuracy : 0.44016, best val accuracy : 0.4624
INFO flwr 2023-08-15 15:19:38,056 | common.py:35 | Avg. local train loss : 8.671029540151359, train acc : 0.4006694444444444
INFO flwr 2023-08-15 15:19:40,765 | server.py:116 | fit progress: (1, 1.5293584930419921, {'server_test_acc': 0.4542}, 95.60698134684935)
INFO flwr 2023-08-15 15:19:40,765 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-08-15 15:19:50,070 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3368883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368890)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:20:41,272 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3368905)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:20:41,483 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-15 15:20:41,594 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3368883)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3368890)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3368898)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3368899)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3368904)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3368902)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3368897)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3368905)[0m Fitting Client 10
E0815 15:20:42.047005173 3461695 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=3368898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368902)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3368904)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368897)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3368899)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:21:17,463 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:21:17,464 | fed_df.py:547 | Average fusion training loss : 0.01950757011026144, val accuracy : 0.54412, best val accuracy : 0.5488
INFO flwr 2023-08-15 15:21:17,466 | common.py:35 | Avg. local train loss : 7.204172242432832, train acc : 0.5583027777777777
INFO flwr 2023-08-15 15:21:20,381 | server.py:116 | fit progress: (2, 1.4167519409179687, {'server_test_acc': 0.5466}, 195.22305763093755)
INFO flwr 2023-08-15 15:21:20,381 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 15:21:29,917 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3515867)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3515866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3515868)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:22:21,189 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-15 15:22:21,402 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 15:22:21,513 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3515867)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3515866)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3515868)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3515870)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3515871)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3515869)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3515872)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3515873)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3515872)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3515873)[0m double free or corruption (fasttop)
E0815 15:22:22.337940127 3609275 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=3515871)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3515869)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3515870)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:22:56,982 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:22:56,982 | fed_df.py:547 | Average fusion training loss : 0.015343090737238526, val accuracy : 0.61492, best val accuracy : 0.6226
INFO flwr 2023-08-15 15:22:56,983 | common.py:35 | Avg. local train loss : 6.289587741345167, train acc : 0.6561472222222223
INFO flwr 2023-08-15 15:22:59,891 | server.py:116 | fit progress: (3, 1.402034817504883, {'server_test_acc': 0.6176}, 294.7332329368219)
INFO flwr 2023-08-15 15:22:59,891 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 15:23:09,352 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3662880)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:24:00,262 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3662887)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:24:00,477 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 15:24:00,589 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3662880)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3662881)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3662882)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3662887)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3662883)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3662885)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3662886)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3662884)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3662882)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3662881)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3662883)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3662884)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3662886)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3662885)[0m malloc_consolidate(): invalid chunk size
E0815 15:24:02.997873060 3757442 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-15 15:24:36,268 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:24:36,268 | fed_df.py:547 | Average fusion training loss : 0.013594797551631928, val accuracy : 0.6499599999999999, best val accuracy : 0.6596
INFO flwr 2023-08-15 15:24:36,269 | common.py:35 | Avg. local train loss : 5.698324155062438, train acc : 0.7185611111111111
INFO flwr 2023-08-15 15:24:39,185 | server.py:116 | fit progress: (4, 1.3667901519775392, {'server_test_acc': 0.6521}, 394.02700679702684)
INFO flwr 2023-08-15 15:24:39,185 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 15:24:48,675 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3809891)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:25:39,215 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-15 15:25:39,427 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 15:25:39,539 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3809884)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3809883)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3809885)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3809887)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3809886)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3809888)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3809890)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3809891)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3809887)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3809890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3809884)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3809885)[0m malloc_consolidate(): invalid chunk size
E0815 15:25:40.805988588 3758126 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
[2m[36m(launch_and_fit pid=3809886)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3809883)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3809888)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:26:15,415 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:26:15,415 | fed_df.py:547 | Average fusion training loss : 0.014841855190694333, val accuracy : 0.6744, best val accuracy : 0.6808
INFO flwr 2023-08-15 15:26:15,417 | common.py:35 | Avg. local train loss : 5.377052574977279, train acc : 0.7516638888888888
INFO flwr 2023-08-15 15:26:18,319 | server.py:116 | fit progress: (5, 1.3647979553222656, {'server_test_acc': 0.6814}, 493.16137413401157)
INFO flwr 2023-08-15 15:26:18,320 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 15:26:28,221 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3956725)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:27:18,865 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3956727)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:27:19,079 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 15:27:19,188 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3956725)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3956727)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3956730)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3956732)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3956733)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3956734)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3956741)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3956742)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3956730)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3956733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3956734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3956742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3956732)[0m malloc_consolidate(): invalid chunk size
E0815 15:27:20.889814953 3903558 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=3956741)[0m malloc_consolidate(): invalid chunk size
E0815 15:27:52.459346895 4054965 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-15 15:27:55,767 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:27:55,768 | fed_df.py:547 | Average fusion training loss : 0.01345597662217915, val accuracy : 0.6836, best val accuracy : 0.6944
INFO flwr 2023-08-15 15:27:55,769 | common.py:35 | Avg. local train loss : 5.076384034007788, train acc : 0.7834722222222221
INFO flwr 2023-08-15 15:27:58,934 | server.py:116 | fit progress: (6, 1.4470415069580078, {'server_test_acc': 0.6967}, 593.7762470217422)
INFO flwr 2023-08-15 15:27:58,934 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 15:28:08,499 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4123618)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123628)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:28:58,326 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-15 15:28:58,538 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 15:28:58,651 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4123618)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4123622)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4123623)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4123624)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4123626)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4123627)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4123625)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4123628)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4123624)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123622)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4123627)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123625)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4123625)[0m malloc_consolidate(): invalid chunk size
E0815 15:28:59.816291471   31554 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=4123623)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4123626)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:29:35,307 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:29:35,308 | fed_df.py:547 | Average fusion training loss : 0.014507779924198985, val accuracy : 0.70688, best val accuracy : 0.7164
INFO flwr 2023-08-15 15:29:35,309 | common.py:35 | Avg. local train loss : 4.973904945328832, train acc : 0.7961027777777777
INFO flwr 2023-08-15 15:29:38,263 | server.py:116 | fit progress: (7, 1.4770633514404297, {'server_test_acc': 0.7113}, 693.1054679057561)
INFO flwr 2023-08-15 15:29:38,264 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 15:29:47,811 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=86708)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=86714)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:30:37,923 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 15:30:38,137 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 15:30:38,247 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=86708)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=86711)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=86712)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=86714)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=86716)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=86715)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=86717)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=86713)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=86711)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=86713)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=86712)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=86716)[0m double free or corruption (fasttop)
E0815 15:30:39.844550020  179308 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=86715)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=86717)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:31:14,153 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:31:14,154 | fed_df.py:547 | Average fusion training loss : 0.014300717516802251, val accuracy : 0.71048, best val accuracy : 0.7184
INFO flwr 2023-08-15 15:31:14,156 | common.py:35 | Avg. local train loss : 4.923950558528303, train acc : 0.8040611111111111
INFO flwr 2023-08-15 15:31:17,066 | server.py:116 | fit progress: (8, 1.5094305603027345, {'server_test_acc': 0.7146}, 791.9078060127795)
INFO flwr 2023-08-15 15:31:17,066 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 15:31:26,599 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=233569)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:32:17,227 | server.py:229 | fit_round 9 received 8 results and 0 failures
INFO flwr 2023-08-15 15:32:17,442 | fed_df.py:365 | Warm start at round 9
INFO flwr 2023-08-15 15:32:17,555 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=233569)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=233573)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=233571)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=233570)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=233575)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=233576)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=233577)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=233578)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=233570)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=233571)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=233578)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=233573)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=233576)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=233577)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=233575)[0m malloc_consolidate(): invalid chunk size
E0815 15:32:18.993832041  180710 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
INFO flwr 2023-08-15 15:32:53,828 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:32:53,828 | fed_df.py:547 | Average fusion training loss : 0.013723461681045592, val accuracy : 0.7230800000000001, best val accuracy : 0.7328
INFO flwr 2023-08-15 15:32:53,830 | common.py:35 | Avg. local train loss : 4.835719669982791, train acc : 0.8150694444444445
INFO flwr 2023-08-15 15:32:56,771 | server.py:116 | fit progress: (9, 1.5016721984863282, {'server_test_acc': 0.7258}, 891.6129190828651)
INFO flwr 2023-08-15 15:32:56,771 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 15:33:06,391 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:33:57,177 | server.py:229 | fit_round 10 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=380834)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=380840)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=380843)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:33:57,395 | fed_df.py:365 | Warm start at round 10
[2m[36m(launch_and_fit pid=380836)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 15:33:57,509 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=380833)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=380836)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=380839)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=380834)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=380840)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=380841)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=380842)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=380843)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=380833)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=380839)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=380841)[0m malloc_consolidate(): invalid chunk size
E0815 15:33:58.923996759   81574 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
[2m[36m(launch_and_fit pid=380842)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:34:33,563 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:34:33,563 | fed_df.py:547 | Average fusion training loss : 0.013342922028154135, val accuracy : 0.7246, best val accuracy : 0.7332
INFO flwr 2023-08-15 15:34:33,565 | common.py:35 | Avg. local train loss : 4.777616390958428, train acc : 0.8218555555555556
INFO flwr 2023-08-15 15:34:36,500 | server.py:116 | fit progress: (10, 1.5551594055175781, {'server_test_acc': 0.7311}, 991.342599872034)
INFO flwr 2023-08-15 15:34:36,501 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 15:34:46,033 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=527393)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:35:36,953 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=527394)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:35:37,169 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-15 15:35:37,281 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=527387)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=527392)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=527390)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=527394)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=527393)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=527391)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=527389)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=527388)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=527390)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=527389)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=527387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=527392)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=527388)[0m malloc_consolidate(): invalid chunk size
E0815 15:35:38.694582370  474935 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=527391)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:36:13,540 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:36:13,540 | fed_df.py:547 | Average fusion training loss : 0.01325542180147022, val accuracy : 0.7359199999999999, best val accuracy : 0.7474
INFO flwr 2023-08-15 15:36:13,542 | common.py:35 | Avg. local train loss : 4.646095711365342, train acc : 0.8382
INFO flwr 2023-08-15 15:36:16,447 | server.py:116 | fit progress: (11, 1.5163972778320312, {'server_test_acc': 0.7392}, 1091.2888472308405)
INFO flwr 2023-08-15 15:36:16,447 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 15:36:25,955 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=674536)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=674531)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:37:16,097 | server.py:229 | fit_round 12 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=674529)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:37:16,313 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 15:37:16,424 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=674529)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=674533)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=674531)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=674532)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=674534)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=674536)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=674535)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=674537)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=674535)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=674537)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=674533)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=674534)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=674532)[0m double free or corruption (fasttop)
E0815 15:37:20.078807364  621731 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
E0815 15:37:20.078881953  621731 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-15 15:37:52,514 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:37:52,514 | fed_df.py:547 | Average fusion training loss : 0.013584703701548278, val accuracy : 0.7415200000000001, best val accuracy : 0.751
INFO flwr 2023-08-15 15:37:52,516 | common.py:35 | Avg. local train loss : 4.613162489980459, train acc : 0.8415222222222223
INFO flwr 2023-08-15 15:37:55,439 | server.py:116 | fit progress: (12, 1.5386027526855468, {'server_test_acc': 0.7401}, 1190.2809082739986)
INFO flwr 2023-08-15 15:37:55,439 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 15:38:05,258 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=821334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=821331)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:38:56,218 | server.py:229 | fit_round 13 received 8 results and 0 failures
INFO flwr 2023-08-15 15:38:56,432 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 15:38:56,543 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=821329)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=821331)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=821334)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=821337)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=821336)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=821338)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=821340)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=821339)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=821338)[0m malloc_consolidate(): invalid chunk size
E0815 15:38:57.284175011  912636 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=821340)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=821329)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=821336)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=821339)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=821337)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:39:31,601 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:39:31,602 | fed_df.py:547 | Average fusion training loss : 0.013842138812877238, val accuracy : 0.74488, best val accuracy : 0.7526
INFO flwr 2023-08-15 15:39:31,603 | common.py:35 | Avg. local train loss : 4.54099462106824, train acc : 0.8487805555555554
INFO flwr 2023-08-15 15:39:34,514 | server.py:116 | fit progress: (13, 1.5003117828369141, {'server_test_acc': 0.7456}, 1289.3556074770167)
INFO flwr 2023-08-15 15:39:34,514 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 15:39:43,983 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=967877)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:40:34,644 | server.py:229 | fit_round 14 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=967878)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:40:34,858 | fed_df.py:365 | Warm start at round 14
[2m[36m(launch_and_fit pid=967876)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:40:34,973 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=967872)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=967870)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=967876)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=967878)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=967874)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=967877)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=967879)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=967875)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=967870)[0m malloc_consolidate(): invalid chunk size
E0815 15:40:35.363597173  913669 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=967872)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=967875)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=967879)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=967874)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:41:11,210 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:41:11,210 | fed_df.py:547 | Average fusion training loss : 0.013412933992221952, val accuracy : 0.74488, best val accuracy : 0.7546
INFO flwr 2023-08-15 15:41:11,212 | common.py:35 | Avg. local train loss : 4.433043700829148, train acc : 0.857313888888889
INFO flwr 2023-08-15 15:41:14,126 | server.py:116 | fit progress: (14, 1.517740542602539, {'server_test_acc': 0.7468}, 1388.9683134639636)
INFO flwr 2023-08-15 15:41:14,126 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 15:41:23,572 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1114798)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:42:14,207 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1114802)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:42:14,422 | fed_df.py:365 | Warm start at round 15
[2m[36m(launch_and_fit pid=1114797)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:42:14,535 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1114795)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1114797)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1114800)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1114798)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1114799)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1114801)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1114802)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1114803)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1114803)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1114800)[0m double free or corruption (fasttop)
E0815 15:42:15.951689090 1058291 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=1114799)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1114801)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:42:50,829 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:42:50,830 | fed_df.py:547 | Average fusion training loss : 0.012366799714043737, val accuracy : 0.75032, best val accuracy : 0.7588
INFO flwr 2023-08-15 15:42:50,831 | common.py:35 | Avg. local train loss : 4.493084837496281, train acc : 0.8519583333333334
INFO flwr 2023-08-15 15:42:53,782 | server.py:116 | fit progress: (15, 1.543350637817383, {'server_test_acc': 0.7479}, 1488.6236681081355)
INFO flwr 2023-08-15 15:42:53,782 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 15:43:03,386 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:43:53,724 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-15 15:43:53,939 | fed_df.py:365 | Warm start at round 16
[2m[36m(launch_and_fit pid=1280288)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1280289)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:43:54,051 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1280288)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1280289)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1280293)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1280294)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1280286)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1280292)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1280291)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1280290)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1280294)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1280290)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1280291)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1280293)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1280286)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1280292)[0m double free or corruption (fasttop)
E0815 15:43:57.675774479 1383701 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:44:30,777 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:44:30,777 | fed_df.py:547 | Average fusion training loss : 0.011840785814449192, val accuracy : 0.75656, best val accuracy : 0.7664
INFO flwr 2023-08-15 15:44:30,779 | common.py:35 | Avg. local train loss : 4.34442489258945, train acc : 0.8680055555555555
INFO flwr 2023-08-15 15:44:33,731 | server.py:116 | fit progress: (16, 1.5492500244140626, {'server_test_acc': 0.755}, 1588.5729849678464)
INFO flwr 2023-08-15 15:44:33,731 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 15:44:43,248 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:45:33,300 | server.py:229 | fit_round 17 received 8 results and 0 failures
INFO flwr 2023-08-15 15:45:33,516 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 15:45:33,630 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1437465)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1437468)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1437467)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1437469)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1437471)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1437462)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1437470)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1437463)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1437465)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1437467)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1437469)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1437468)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1437470)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1437471)[0m malloc_consolidate(): invalid chunk size
E0815 15:45:35.292173287 1386326 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1437463)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1437462)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:46:15,170 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:46:15,170 | fed_df.py:547 | Average fusion training loss : 0.012437530590221286, val accuracy : 0.7554000000000001, best val accuracy : 0.767
INFO flwr 2023-08-15 15:46:15,172 | common.py:35 | Avg. local train loss : 4.2989945586770775, train acc : 0.8736055555555556
INFO flwr 2023-08-15 15:46:18,090 | server.py:116 | fit progress: (17, 1.5824893249511718, {'server_test_acc': 0.7502}, 1692.9325891770422)
INFO flwr 2023-08-15 15:46:18,091 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 15:46:27,692 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1585229)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1585228)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1585233)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1585227)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:47:18,404 | server.py:229 | fit_round 18 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1585224)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1585230)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:47:18,618 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 15:47:18,732 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1585224)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1585227)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1585228)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1585230)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1585233)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1585229)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1585226)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1585234)[0m Fitting Client 1
E0815 15:47:19.606527380 1531760 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1585234)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1585226)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:47:55,754 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:47:55,755 | fed_df.py:547 | Average fusion training loss : 0.011250935804098845, val accuracy : 0.7593599999999999, best val accuracy : 0.7642
INFO flwr 2023-08-15 15:47:55,756 | common.py:35 | Avg. local train loss : 4.322741586342454, train acc : 0.8729083333333333
INFO flwr 2023-08-15 15:47:59,148 | server.py:116 | fit progress: (18, 1.5789875030517577, {'server_test_acc': 0.7574}, 1793.9896320397966)
INFO flwr 2023-08-15 15:47:59,148 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 15:48:08,752 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1732209)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1732208)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:48:58,955 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1732205)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1732211)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:48:59,170 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 15:48:59,313 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1732205)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1732208)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1732209)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1732211)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1732213)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1732212)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1732215)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1732214)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1732214)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1732213)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1732212)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1732215)[0m malloc_consolidate(): invalid chunk size
E0815 15:49:01.687337189 1680869 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:49:35,694 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:49:35,694 | fed_df.py:547 | Average fusion training loss : 0.010749934983439744, val accuracy : 0.7656, best val accuracy : 0.774
INFO flwr 2023-08-15 15:49:35,696 | common.py:35 | Avg. local train loss : 4.251084691658616, train acc : 0.8801277777777777
INFO flwr 2023-08-15 15:49:38,622 | server.py:116 | fit progress: (19, 1.5845141632080078, {'server_test_acc': 0.7631}, 1893.4637473388575)
INFO flwr 2023-08-15 15:49:38,622 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 15:49:48,197 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1878795)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1878797)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:50:38,307 | server.py:229 | fit_round 20 received 8 results and 0 failures
INFO flwr 2023-08-15 15:50:38,520 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 15:50:38,632 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=1878795)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1878797)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1878799)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1878800)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1878803)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1878801)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1878798)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1878802)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1878802)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1878803)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1878800)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1878799)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1878798)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1878801)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:51:15,239 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:51:15,240 | fed_df.py:547 | Average fusion training loss : 0.010445770503021777, val accuracy : 0.7638, best val accuracy : 0.771
INFO flwr 2023-08-15 15:51:15,241 | common.py:35 | Avg. local train loss : 4.203931958973408, train acc : 0.8822249999999999
INFO flwr 2023-08-15 15:51:18,209 | server.py:116 | fit progress: (20, 1.5617139862060547, {'server_test_acc': 0.7655}, 1993.051021040883)
INFO flwr 2023-08-15 15:51:18,209 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 15:51:27,885 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:52:17,724 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2025912)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:52:17,939 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 15:52:18,103 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2025902)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2025906)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2025905)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2025909)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2025910)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2025911)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2025908)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2025912)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2025906)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2025902)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2025910)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2025911)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2025905)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2025909)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2025908)[0m malloc_consolidate(): invalid chunk size
E0815 15:52:22.320911385 2123880 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:52:54,390 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:52:54,390 | fed_df.py:547 | Average fusion training loss : 0.010464182192459702, val accuracy : 0.7672000000000001, best val accuracy : 0.778
INFO flwr 2023-08-15 15:52:54,392 | common.py:35 | Avg. local train loss : 4.252397248893977, train acc : 0.8778194444444445
INFO flwr 2023-08-15 15:52:57,322 | server.py:116 | fit progress: (21, 1.5881613464355469, {'server_test_acc': 0.7663}, 2092.1644351920113)
INFO flwr 2023-08-15 15:52:57,323 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 15:53:07,069 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2172732)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2172734)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2172736)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:53:57,577 | server.py:229 | fit_round 22 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2172738)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:53:57,792 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 15:53:57,905 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2172732)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2172734)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2172736)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2172738)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2172737)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2172741)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2172739)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2172740)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2172741)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2172737)[0m double free or corruption (fasttop)
E0815 15:53:58.877333255 2126888 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2172739)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2172740)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:54:34,303 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:54:34,303 | fed_df.py:547 | Average fusion training loss : 0.009701175881549716, val accuracy : 0.77912, best val accuracy : 0.7872
INFO flwr 2023-08-15 15:54:34,305 | common.py:35 | Avg. local train loss : 4.146758583933115, train acc : 0.8876944444444445
INFO flwr 2023-08-15 15:54:37,266 | server.py:116 | fit progress: (22, 1.5458397705078124, {'server_test_acc': 0.7712}, 2192.107735747006)
INFO flwr 2023-08-15 15:54:37,266 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 15:54:46,769 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2319254)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:55:36,623 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 15:55:36,840 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 15:55:36,984 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2319254)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2319253)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2319256)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2319257)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2319269)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2319255)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2319268)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2319267)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2319269)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2319256)[0m malloc_consolidate(): invalid chunk size
E0815 15:55:37.466295458 2268904 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2319253)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2319257)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2319267)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2319268)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2319255)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:56:13,303 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:56:13,303 | fed_df.py:547 | Average fusion training loss : 0.009388434841297567, val accuracy : 0.7776, best val accuracy : 0.7836
INFO flwr 2023-08-15 15:56:13,305 | common.py:35 | Avg. local train loss : 4.156401364505291, train acc : 0.8875833333333333
INFO flwr 2023-08-15 15:56:16,230 | server.py:116 | fit progress: (23, 1.5375355041503906, {'server_test_acc': 0.7708}, 2291.071794717107)
INFO flwr 2023-08-15 15:56:16,230 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 15:56:25,845 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2466269)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2466272)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:57:16,423 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 15:57:16,638 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 15:57:16,751 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2466269)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2466272)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2466277)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2466275)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2466276)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2466271)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2466273)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2466274)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2466277)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2466271)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2466274)[0m malloc_consolidate(): invalid chunk size
E0815 15:57:17.916730042 2562181 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2466276)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2466273)[0m double free or corruption (fasttop)
E0815 15:57:51.735508783 2562853 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:57:53,239 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:57:53,239 | fed_df.py:547 | Average fusion training loss : 0.01053362675011158, val accuracy : 0.7780400000000001, best val accuracy : 0.7858
INFO flwr 2023-08-15 15:57:53,241 | common.py:35 | Avg. local train loss : 4.119088441133499, train acc : 0.8908888888888888
INFO flwr 2023-08-15 15:57:56,200 | server.py:116 | fit progress: (24, 1.537358514404297, {'server_test_acc': 0.7701}, 2391.0422412878834)
INFO flwr 2023-08-15 15:57:56,200 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 15:58:06,197 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:58:55,854 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-15 15:58:56,070 | fed_df.py:365 | Warm start at round 25
[2m[36m(launch_and_fit pid=2617117)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:58:56,183 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2617109)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2617170)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2617196)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2617142)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2617117)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2617144)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2617143)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2617116)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2617170)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2617196)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2617109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2617142)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2617143)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2617116)[0m malloc_consolidate(): invalid chunk size
E0815 15:58:57.647134626 2607119 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2617144)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:59:32,941 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:59:32,942 | fed_df.py:547 | Average fusion training loss : 0.012339584227651358, val accuracy : 0.78132, best val accuracy : 0.7896
INFO flwr 2023-08-15 15:59:32,943 | common.py:35 | Avg. local train loss : 4.066242625936866, train acc : 0.8937
INFO flwr 2023-08-15 15:59:35,866 | server.py:116 | fit progress: (25, 1.5042369812011718, {'server_test_acc': 0.7725}, 2490.7083577420563)
INFO flwr 2023-08-15 15:59:35,867 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 15:59:45,429 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2788954)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:00:36,113 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-15 16:00:36,329 | fed_df.py:365 | Warm start at round 26
[2m[36m(launch_and_fit pid=2788953)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2788959)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:00:36,452 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2788954)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2788952)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2788953)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2788955)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2788958)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2788957)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2788959)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2788956)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2788956)[0m double free or corruption (fasttop)
E0815 16:00:37.000115550 2727952 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2788958)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2788955)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2788957)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2788952)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:01:12,759 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:01:12,760 | fed_df.py:547 | Average fusion training loss : 0.01135885993205011, val accuracy : 0.7863999999999999, best val accuracy : 0.7916
INFO flwr 2023-08-15 16:01:12,761 | common.py:35 | Avg. local train loss : 4.059311242029072, train acc : 0.8957694444444444
INFO flwr 2023-08-15 16:01:15,698 | server.py:116 | fit progress: (26, 1.539211245727539, {'server_test_acc': 0.7737}, 2590.5404390660115)
INFO flwr 2023-08-15 16:01:15,699 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 16:01:25,360 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2935863)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2935864)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2935870)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2935866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2935873)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:02:16,697 | server.py:229 | fit_round 27 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2935871)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:02:16,912 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-15 16:02:17,074 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2935864)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2935863)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2935866)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2935869)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2935870)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2935871)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2935872)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2935873)[0m Fitting Client 0
E0815 16:02:18.271992500 3032492 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2935869)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2935872)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:02:53,305 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:02:53,306 | fed_df.py:547 | Average fusion training loss : 0.011501772531308234, val accuracy : 0.78448, best val accuracy : 0.7882
INFO flwr 2023-08-15 16:02:53,307 | common.py:35 | Avg. local train loss : 4.075313502922654, train acc : 0.8929833333333334
INFO flwr 2023-08-15 16:02:56,217 | server.py:116 | fit progress: (27, 1.5519601440429687, {'server_test_acc': 0.7809}, 2691.0588610568084)
INFO flwr 2023-08-15 16:02:56,217 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 16:03:06,354 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3082970)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3082974)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3082975)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:03:56,227 | server.py:229 | fit_round 28 received 8 results and 0 failures
INFO flwr 2023-08-15 16:03:56,441 | fed_df.py:365 | Warm start at round 28
[2m[36m(launch_and_fit pid=3082979)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 16:03:56,608 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3082970)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3082974)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3082975)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3082979)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3082978)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3082977)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3082981)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3082980)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3082981)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3082977)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3082978)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3082980)[0m double free or corruption (fasttop)
E0815 16:03:58.332747640 3034648 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 16:04:33,104 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:04:33,104 | fed_df.py:547 | Average fusion training loss : 0.010886885106563568, val accuracy : 0.78996, best val accuracy : 0.7952
INFO flwr 2023-08-15 16:04:33,106 | common.py:35 | Avg. local train loss : 4.031278880313039, train acc : 0.8986388888888888
INFO flwr 2023-08-15 16:04:36,034 | server.py:116 | fit progress: (28, 1.5688713592529298, {'server_test_acc': 0.7786}, 2790.876019143965)
INFO flwr 2023-08-15 16:04:36,034 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 16:04:45,722 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:05:36,347 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 16:05:36,564 | fed_df.py:365 | Warm start at round 29
[2m[36m(launch_and_fit pid=3231063)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3231066)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:05:36,728 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3231062)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3230915)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3230916)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3231063)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3231064)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3231062)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3231066)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3231067)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3231065)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3231064)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3230915)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3231065)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3231067)[0m malloc_consolidate(): invalid chunk size
E0815 16:05:38.241436529 3327373 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3230916)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:06:12,924 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:06:12,924 | fed_df.py:547 | Average fusion training loss : 0.01327526967599988, val accuracy : 0.78636, best val accuracy : 0.7958
INFO flwr 2023-08-15 16:06:12,926 | common.py:35 | Avg. local train loss : 3.993613812699914, train acc : 0.9005305555555555
INFO flwr 2023-08-15 16:06:15,864 | server.py:116 | fit progress: (29, 1.4930942565917968, {'server_test_acc': 0.7858}, 2890.705962307751)
INFO flwr 2023-08-15 16:06:15,864 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 16:06:25,583 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3378079)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3378102)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:07:15,879 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 16:07:16,097 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 16:07:16,263 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3378079)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3378092)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3378094)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3378096)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3378097)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3378098)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3378101)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3378102)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3378097)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3378094)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3378092)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3378096)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3378101)[0m malloc_consolidate(): invalid chunk size
E0815 16:07:17.687264028 3474574 chttp2_transport.cc:1079]             ipv4:145.136.62.51:47397: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 16:07:52,597 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:07:52,598 | fed_df.py:547 | Average fusion training loss : 0.012162274369969963, val accuracy : 0.78856, best val accuracy : 0.7954
INFO flwr 2023-08-15 16:07:52,599 | common.py:35 | Avg. local train loss : 3.968458664044738, train acc : 0.9028388888888889
INFO flwr 2023-08-15 16:07:55,522 | server.py:116 | fit progress: (30, 1.492078436279297, {'server_test_acc': 0.7806}, 2990.3642998039722)
INFO flwr 2023-08-15 16:07:55,522 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 16:07:55,523 | server.py:144 | FL finished in 2990.3646837021224
INFO flwr 2023-08-15 16:07:55,523 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 16:07:55,524 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 16:07:55,524 | app.py:204 | app_fit: losses_centralized [(0, 2.3234217651367186), (1, 1.5293584930419921), (2, 1.4167519409179687), (3, 1.402034817504883), (4, 1.3667901519775392), (5, 1.3647979553222656), (6, 1.4470415069580078), (7, 1.4770633514404297), (8, 1.5094305603027345), (9, 1.5016721984863282), (10, 1.5551594055175781), (11, 1.5163972778320312), (12, 1.5386027526855468), (13, 1.5003117828369141), (14, 1.517740542602539), (15, 1.543350637817383), (16, 1.5492500244140626), (17, 1.5824893249511718), (18, 1.5789875030517577), (19, 1.5845141632080078), (20, 1.5617139862060547), (21, 1.5881613464355469), (22, 1.5458397705078124), (23, 1.5375355041503906), (24, 1.537358514404297), (25, 1.5042369812011718), (26, 1.539211245727539), (27, 1.5519601440429687), (28, 1.5688713592529298), (29, 1.4930942565917968), (30, 1.492078436279297)]
INFO flwr 2023-08-15 16:07:55,524 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.108), (1, 0.4542), (2, 0.5466), (3, 0.6176), (4, 0.6521), (5, 0.6814), (6, 0.6967), (7, 0.7113), (8, 0.7146), (9, 0.7258), (10, 0.7311), (11, 0.7392), (12, 0.7401), (13, 0.7456), (14, 0.7468), (15, 0.7479), (16, 0.755), (17, 0.7502), (18, 0.7574), (19, 0.7631), (20, 0.7655), (21, 0.7663), (22, 0.7712), (23, 0.7708), (24, 0.7701), (25, 0.7725), (26, 0.7737), (27, 0.7809), (28, 0.7786), (29, 0.7858), (30, 0.7806)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn51: task 0: Aborted
srun: Terminating StepId=3342129.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3342129
Cluster: snellius
User/Group: sunnys/sunnys
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 02:04:09
CPU Efficiency: 12.32% of 16:47:42 core-walltime
Job Wall-clock time: 00:55:59
Memory Utilized: 57.76 GB
Memory Efficiency: 48.13% of 120.00 GB
