-----BEGIN-----
-----SETTINGS-----
TOTAL CROPS:100000
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:cifar10
PARTITION_ALPHA:100.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:20
LOCAL_LR:0.01
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:250
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
USE_ADAPTIVE_LR_ROUND:False
SEED:84
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:ameyoko.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:1
KMEANS_N_CLUSTER:100
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
KMEANS_BALANCING:0.25
CONFIDENCE_THRESHOLD:0.1
CONFIDENCE_STRATEGY:top
CONFIDENCE_ADAPTIVE:True
CONFIDENCE_MAX_THRESH:0.5
CLIPPING_FACTOR:2.5
FEDPROX_FACTOR:0.0
FEDPROX_ADAPTIVE:False
USE_CLIPPING:True
USE_ENTROPY:False
USE_KMEANS:True
USE_FEDPROX:False
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/ameyoko.jpg', targetpath='/scratch-local/sunnys.3342130/1692105344_576115874', seed=84, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3342130/1692105344_576115874/single_img_crops/crops
100000 took 0.72min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-08-15 15:16:42,150 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-08-15 15:16:42,150 | simulate.py:55 | Reading args from argument parser
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /scratch-local/sunnys.3342130/1692105344_576115874/cifar-10-python.tar.gz
Extracting /scratch-local/sunnys.3342130/1692105344_576115874/cifar-10-python.tar.gz to /scratch-local/sunnys.3342130/1692105344_576115874
Generating unified cifar10 dataset
Class histogram for 0-th partition (alpha=100.0, 10 classes): [225 194 247 272 217 251 256 333 258 247]
INFO flwr 2023-08-15 15:17:07,111 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-08-15 15:17:09,859	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-08-15 15:17:10,865 | app.py:179 | Flower VCE: Ray initialized with resources: {'node:145.136.62.52': 1.0, 'GPU': 1.0, 'CPU': 18.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-08-15 15:17:10,866 | server.py:86 | Initializing global parameters
INFO flwr 2023-08-15 15:17:10,866 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-08-15 15:17:10,866 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-08-15 15:17:21,191 | server.py:91 | initial parameters (loss, other metrics): 2.319245477294922, {'server_test_acc': 0.0811}
INFO flwr 2023-08-15 15:17:21,191 | server.py:101 | FL starting
DEBUG flwr 2023-08-15 15:17:30,156 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2725794)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2725793)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2725795)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:18:21,570 | server.py:229 | fit_round 1 received 8 results and 0 failures
INFO flwr 2023-08-15 15:18:21,789 | fed_df.py:365 | Warm start at round 1
INFO flwr 2023-08-15 15:18:21,900 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2725788)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2725789)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2725790)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2725793)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2725792)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2725791)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2725794)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2725795)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2725789)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2725791)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2725788)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2725792)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2725790)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:18:56,949 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:18:56,950 | fed_df.py:547 | Average fusion training loss : 0.03571485164761543, val accuracy : 0.40548, best val accuracy : 0.4284
INFO flwr 2023-08-15 15:18:56,951 | common.py:35 | Avg. local train loss : 8.775659846514463, train acc : 0.3841388888888889
INFO flwr 2023-08-15 15:18:59,506 | server.py:116 | fit progress: (1, 1.5848587158203125, {'server_test_acc': 0.4379}, 98.31479674484581)
INFO flwr 2023-08-15 15:18:59,506 | server.py:163 | evaluate_round 1: no clients selected, cancel
E0815 15:19:02.213651558 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213824966 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213842110 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213853861 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213864067 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213875024 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213884756 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213894783 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213904328 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213912181 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0815 15:19:02.213920018 2718313 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
DEBUG flwr 2023-08-15 15:19:08,689 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2810096)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:19:55,883 | server.py:229 | fit_round 2 received 8 results and 0 failures
INFO flwr 2023-08-15 15:19:56,104 | fed_df.py:365 | Warm start at round 2
INFO flwr 2023-08-15 15:19:56,246 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2810096)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2810095)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2810100)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2810098)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2810103)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2810102)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2810099)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2810101)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2810102)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2810100)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2810095)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2810103)[0m double free or corruption (fasttop)
E0815 15:19:57.249213340 2809869 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2810098)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2810099)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2810101)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:20:29,020 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:20:29,021 | fed_df.py:547 | Average fusion training loss : 0.0238555310331285, val accuracy : 0.5435200000000001, best val accuracy : 0.5612
INFO flwr 2023-08-15 15:20:29,022 | common.py:35 | Avg. local train loss : 7.358892764896154, train acc : 0.5395083333333333
INFO flwr 2023-08-15 15:20:31,748 | server.py:116 | fit progress: (2, 1.393299298095703, {'server_test_acc': 0.5667}, 190.55730646499433)
INFO flwr 2023-08-15 15:20:31,749 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-08-15 15:20:41,192 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2883755)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:21:28,739 | server.py:229 | fit_round 3 received 8 results and 0 failures
INFO flwr 2023-08-15 15:21:28,960 | fed_df.py:365 | Warm start at round 3
INFO flwr 2023-08-15 15:21:29,069 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2883755)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2883754)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2883757)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2883759)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2883756)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2883758)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2883751)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2883760)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2883758)[0m malloc_consolidate(): invalid chunk size
E0815 15:21:30.129233887 2857311 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
[2m[36m(launch_and_fit pid=2883754)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2883757)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2883756)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2883759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2883760)[0m double free or corruption (fasttop)
E0815 15:21:31.576245048 2932115 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
INFO flwr 2023-08-15 15:22:01,739 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:22:01,740 | fed_df.py:547 | Average fusion training loss : 0.016040302423760294, val accuracy : 0.62324, best val accuracy : 0.6356
INFO flwr 2023-08-15 15:22:01,741 | common.py:35 | Avg. local train loss : 6.22663502432406, train acc : 0.6637694444444444
INFO flwr 2023-08-15 15:22:04,528 | server.py:116 | fit progress: (3, 1.3366265686035157, {'server_test_acc': 0.6304}, 283.33662692597136)
INFO flwr 2023-08-15 15:22:04,528 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-08-15 15:22:13,996 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2957518)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957521)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:23:00,876 | server.py:229 | fit_round 4 received 8 results and 0 failures
INFO flwr 2023-08-15 15:23:01,099 | fed_df.py:365 | Warm start at round 4
INFO flwr 2023-08-15 15:23:01,209 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=2957518)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=2957521)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2957524)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2957523)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2957526)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2957525)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2957527)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2957528)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2957524)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957525)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2957526)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957523)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957528)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2957527)[0m malloc_consolidate(): invalid chunk size
E0815 15:23:03.866324523 2932452 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
INFO flwr 2023-08-15 15:23:34,469 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:23:34,470 | fed_df.py:547 | Average fusion training loss : 0.014105328284204006, val accuracy : 0.65192, best val accuracy : 0.6612
INFO flwr 2023-08-15 15:23:34,471 | common.py:35 | Avg. local train loss : 5.657379085198044, train acc : 0.7204444444444446
INFO flwr 2023-08-15 15:23:37,231 | server.py:116 | fit progress: (4, 1.3009409912109375, {'server_test_acc': 0.6632}, 376.0401869069319)
INFO flwr 2023-08-15 15:23:37,232 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-08-15 15:23:46,704 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3031552)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3031558)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3031554)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:24:34,636 | server.py:229 | fit_round 5 received 8 results and 0 failures
INFO flwr 2023-08-15 15:24:34,858 | fed_df.py:365 | Warm start at round 5
INFO flwr 2023-08-15 15:24:34,967 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3031552)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3031554)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3031555)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3031559)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3031557)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3031558)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3031551)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3031556)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3031555)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3031559)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3031557)[0m malloc_consolidate(): invalid chunk size
E0815 15:24:35.797455199 3005968 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=3031556)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3031551)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:25:07,883 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:25:07,884 | fed_df.py:547 | Average fusion training loss : 0.011959847060963511, val accuracy : 0.66584, best val accuracy : 0.6744
INFO flwr 2023-08-15 15:25:07,885 | common.py:35 | Avg. local train loss : 5.263420935720205, train acc : 0.7620194444444445
INFO flwr 2023-08-15 15:25:10,865 | server.py:116 | fit progress: (5, 1.385491534423828, {'server_test_acc': 0.6739}, 469.6742103160359)
INFO flwr 2023-08-15 15:25:10,866 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-08-15 15:25:20,250 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3105624)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:26:07,654 | server.py:229 | fit_round 6 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3105633)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:26:07,878 | fed_df.py:365 | Warm start at round 6
INFO flwr 2023-08-15 15:26:07,989 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3105624)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3105630)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3105634)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3105635)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3105636)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3105631)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3105626)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3105633)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3105635)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3105630)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3105626)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3105636)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3105634)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3105631)[0m double free or corruption (fasttop)
E0815 15:26:11.738520253 3154663 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
INFO flwr 2023-08-15 15:26:39,722 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:26:39,723 | fed_df.py:547 | Average fusion training loss : 0.01299218499287963, val accuracy : 0.67652, best val accuracy : 0.6822
INFO flwr 2023-08-15 15:26:39,724 | common.py:35 | Avg. local train loss : 5.125620843842626, train acc : 0.7764694444444444
INFO flwr 2023-08-15 15:26:42,465 | server.py:116 | fit progress: (6, 1.4268705993652344, {'server_test_acc': 0.677}, 561.2741431200411)
INFO flwr 2023-08-15 15:26:42,465 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-08-15 15:26:51,777 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3179340)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:27:39,291 | server.py:229 | fit_round 7 received 8 results and 0 failures
INFO flwr 2023-08-15 15:27:39,513 | fed_df.py:365 | Warm start at round 7
INFO flwr 2023-08-15 15:27:39,622 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3179340)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3179339)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3179338)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3179345)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3179341)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3179343)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3179344)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3179342)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3179338)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3179344)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3179345)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3179339)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3179341)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3179343)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3179342)[0m malloc_consolidate(): invalid chunk size
E0815 15:27:41.778796336 3227283 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
INFO flwr 2023-08-15 15:28:11,390 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:28:11,391 | fed_df.py:547 | Average fusion training loss : 0.013112213407643139, val accuracy : 0.7001999999999999, best val accuracy : 0.707
INFO flwr 2023-08-15 15:28:11,392 | common.py:35 | Avg. local train loss : 4.92025613449514, train acc : 0.8010805555555556
INFO flwr 2023-08-15 15:28:14,092 | server.py:116 | fit progress: (7, 1.4762447814941406, {'server_test_acc': 0.7069}, 652.9008711159695)
INFO flwr 2023-08-15 15:28:14,092 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-08-15 15:28:23,354 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3253180)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3253177)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:29:11,098 | server.py:229 | fit_round 8 received 8 results and 0 failures
INFO flwr 2023-08-15 15:29:11,321 | fed_df.py:365 | Warm start at round 8
INFO flwr 2023-08-15 15:29:11,432 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3253176)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3253173)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3253177)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3253174)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3253180)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3253181)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3253178)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3253179)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3253176)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3253173)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3253178)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3253174)[0m double free or corruption (fasttop)
E0815 15:29:12.481854666 3300529 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
[2m[36m(launch_and_fit pid=3253179)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3253181)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:29:43,325 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:29:43,326 | fed_df.py:547 | Average fusion training loss : 0.013780039087869227, val accuracy : 0.69352, best val accuracy : 0.703
INFO flwr 2023-08-15 15:29:43,327 | common.py:35 | Avg. local train loss : 4.888628754019738, train acc : 0.8079666666666666
INFO flwr 2023-08-15 15:29:46,053 | server.py:116 | fit progress: (8, 1.5557923278808594, {'server_test_acc': 0.7046}, 744.8623931529)
INFO flwr 2023-08-15 15:29:46,054 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-08-15 15:29:55,425 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3326807)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3326809)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:30:43,404 | server.py:229 | fit_round 9 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3326812)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3326815)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3326816)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:30:43,634 | fed_df.py:365 | Warm start at round 9
[2m[36m(launch_and_fit pid=3326814)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:30:43,744 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3326809)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3326807)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3326812)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3326814)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3326815)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3326817)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3326818)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3326816)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3326818)[0m malloc_consolidate(): invalid chunk size
E0815 15:30:44.879759367 3300664 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
[2m[36m(launch_and_fit pid=3326817)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:31:16,856 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:31:16,856 | fed_df.py:547 | Average fusion training loss : 0.01490537859685719, val accuracy : 0.702, best val accuracy : 0.7134
INFO flwr 2023-08-15 15:31:16,858 | common.py:35 | Avg. local train loss : 4.764513026177883, train acc : 0.8236777777777777
INFO flwr 2023-08-15 15:31:19,615 | server.py:116 | fit progress: (9, 1.5278175598144532, {'server_test_acc': 0.7187}, 838.4240136959124)
INFO flwr 2023-08-15 15:31:19,615 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-08-15 15:31:28,970 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3400729)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:32:16,754 | server.py:229 | fit_round 10 received 8 results and 0 failures
INFO flwr 2023-08-15 15:32:16,979 | fed_df.py:365 | Warm start at round 10
INFO flwr 2023-08-15 15:32:17,089 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3400732)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3400729)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3400732)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3400735)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3400734)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3400736)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3400733)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3400737)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3400738)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3400734)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3400735)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3400738)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3400736)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3400733)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3400737)[0m corrupted size vs. prev_size in fastbins
INFO flwr 2023-08-15 15:32:50,733 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:32:50,734 | fed_df.py:547 | Average fusion training loss : 0.015077185111120344, val accuracy : 0.7168400000000001, best val accuracy : 0.7244
INFO flwr 2023-08-15 15:32:50,735 | common.py:35 | Avg. local train loss : 4.717041809111834, train acc : 0.8284472222222222
INFO flwr 2023-08-15 15:32:53,525 | server.py:116 | fit progress: (10, 1.5504868347167968, {'server_test_acc': 0.7308}, 932.3335768969264)
INFO flwr 2023-08-15 15:32:53,525 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-08-15 15:33:02,927 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3494383)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3494392)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:33:50,727 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3494387)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:33:50,952 | fed_df.py:365 | Warm start at round 11
INFO flwr 2023-08-15 15:33:51,064 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3494383)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3494387)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3494386)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3494388)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3494391)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3494390)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3494392)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3494389)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3494386)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3494391)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3494388)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3494389)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3494390)[0m double free or corruption (fasttop)
E0815 15:33:53.261219590 3374452 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
INFO flwr 2023-08-15 15:34:24,338 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:34:24,338 | fed_df.py:547 | Average fusion training loss : 0.014993857057765127, val accuracy : 0.7172399999999999, best val accuracy : 0.731
INFO flwr 2023-08-15 15:34:24,339 | common.py:35 | Avg. local train loss : 4.642303725332021, train acc : 0.837
INFO flwr 2023-08-15 15:34:27,096 | server.py:116 | fit progress: (11, 1.5214976684570312, {'server_test_acc': 0.7391}, 1025.905120533891)
INFO flwr 2023-08-15 15:34:27,096 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-08-15 15:34:36,438 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3577234)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3577229)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3577230)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:35:23,806 | server.py:229 | fit_round 12 received 8 results and 0 failures
INFO flwr 2023-08-15 15:35:24,031 | fed_df.py:365 | Warm start at round 12
INFO flwr 2023-08-15 15:35:24,143 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3577229)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3577234)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3577235)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3577233)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3577236)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3577237)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3577238)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3577230)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3577237)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3577238)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3577236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3577233)[0m double free or corruption (fasttop)
E0815 15:35:25.161362910 3551664 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
[2m[36m(launch_and_fit pid=3577235)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:35:57,543 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:35:57,544 | fed_df.py:547 | Average fusion training loss : 0.012461163440719247, val accuracy : 0.7251199999999999, best val accuracy : 0.7344
INFO flwr 2023-08-15 15:35:57,545 | common.py:35 | Avg. local train loss : 4.57890524379909, train acc : 0.8432999999999999
INFO flwr 2023-08-15 15:36:00,349 | server.py:116 | fit progress: (12, 1.579351788330078, {'server_test_acc': 0.7323}, 1119.1577001600526)
INFO flwr 2023-08-15 15:36:00,349 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-08-15 15:36:09,879 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3650959)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:36:57,097 | server.py:229 | fit_round 13 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3650957)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:36:57,323 | fed_df.py:365 | Warm start at round 13
INFO flwr 2023-08-15 15:36:57,433 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3650959)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3650957)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3650956)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3650963)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3650958)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3650960)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3650961)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3650962)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3650956)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650963)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650958)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650961)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3650960)[0m malloc_consolidate(): invalid chunk size
E0815 15:36:58.943142879 3624480 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
INFO flwr 2023-08-15 15:37:30,955 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:37:30,956 | fed_df.py:547 | Average fusion training loss : 0.013313048445619643, val accuracy : 0.72208, best val accuracy : 0.734
INFO flwr 2023-08-15 15:37:30,958 | common.py:35 | Avg. local train loss : 4.45658719278872, train acc : 0.8575888888888888
INFO flwr 2023-08-15 15:37:33,846 | server.py:116 | fit progress: (13, 1.6123265502929687, {'server_test_acc': 0.7305}, 1212.655364286853)
INFO flwr 2023-08-15 15:37:33,847 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-08-15 15:37:43,174 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3724667)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:38:30,414 | server.py:229 | fit_round 14 received 8 results and 0 failures
INFO flwr 2023-08-15 15:38:30,637 | fed_df.py:365 | Warm start at round 14
INFO flwr 2023-08-15 15:38:30,748 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3724672)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3724667)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3724669)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3724666)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3724671)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3724672)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3724673)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3724668)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3724670)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3724669)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3724666)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3724673)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3724671)[0m malloc_consolidate(): invalid chunk size
E0815 15:38:32.087747951 3698590 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
[2m[36m(launch_and_fit pid=3724670)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3724668)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:39:03,007 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:39:03,007 | fed_df.py:547 | Average fusion training loss : 0.012549732360057533, val accuracy : 0.72904, best val accuracy : 0.7414
INFO flwr 2023-08-15 15:39:03,009 | common.py:35 | Avg. local train loss : 4.472498075664044, train acc : 0.8553166666666667
INFO flwr 2023-08-15 15:39:05,791 | server.py:116 | fit progress: (14, 1.6529347259521485, {'server_test_acc': 0.7418}, 1304.600130073959)
INFO flwr 2023-08-15 15:39:05,791 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-08-15 15:39:15,143 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3798385)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798395)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:40:02,572 | server.py:229 | fit_round 15 received 8 results and 0 failures
INFO flwr 2023-08-15 15:40:02,798 | fed_df.py:365 | Warm start at round 15
INFO flwr 2023-08-15 15:40:02,909 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3798385)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3798389)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3798387)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3798392)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3798394)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3798395)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3798393)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3798396)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3798389)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3798387)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798393)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798394)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3798392)[0m malloc_consolidate(): invalid chunk size
E0815 15:40:04.065962412 3772690 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
[2m[36m(launch_and_fit pid=3798396)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:40:36,598 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:40:36,598 | fed_df.py:547 | Average fusion training loss : 0.012837395184673368, val accuracy : 0.7306, best val accuracy : 0.7446
INFO flwr 2023-08-15 15:40:36,600 | common.py:35 | Avg. local train loss : 4.431053421646356, train acc : 0.8615611111111111
INFO flwr 2023-08-15 15:40:39,420 | server.py:116 | fit progress: (15, 1.6120816497802735, {'server_test_acc': 0.7467}, 1398.2291164810304)
INFO flwr 2023-08-15 15:40:39,420 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-08-15 15:40:48,776 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3872051)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:41:36,024 | server.py:229 | fit_round 16 received 8 results and 0 failures
INFO flwr 2023-08-15 15:41:36,250 | fed_df.py:365 | Warm start at round 16
[2m[36m(launch_and_fit pid=3872047)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:41:36,363 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3872046)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3872049)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3872047)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3872048)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3872051)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3872050)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3872053)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3872052)[0m Fitting Client 9
E0815 15:41:36.804622594 3918835 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
[2m[36m(launch_and_fit pid=3872046)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3872048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3872049)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3872053)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3872050)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3872052)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:42:09,834 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:42:09,834 | fed_df.py:547 | Average fusion training loss : 0.011019957245327533, val accuracy : 0.7465599999999999, best val accuracy : 0.7552
INFO flwr 2023-08-15 15:42:09,836 | common.py:35 | Avg. local train loss : 4.41438058950007, train acc : 0.8620166666666667
INFO flwr 2023-08-15 15:42:12,625 | server.py:116 | fit progress: (16, 1.6557514709472656, {'server_test_acc': 0.7584}, 1491.434018637985)
INFO flwr 2023-08-15 15:42:12,625 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-08-15 15:42:22,078 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3945731)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3945736)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:43:09,273 | server.py:229 | fit_round 17 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3945738)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:43:09,503 | fed_df.py:365 | Warm start at round 17
INFO flwr 2023-08-15 15:43:09,616 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=3945731)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3945736)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3945737)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3945739)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3945742)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3945740)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3945738)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3945741)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3945742)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3945739)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3945737)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3945740)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3945741)[0m double free or corruption (fasttop)
E0815 15:43:11.742300634 3993901 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:43:43,146 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:43:43,146 | fed_df.py:547 | Average fusion training loss : 0.012278000970371067, val accuracy : 0.7457999999999999, best val accuracy : 0.7616
INFO flwr 2023-08-15 15:43:43,148 | common.py:35 | Avg. local train loss : 4.328040363267064, train acc : 0.8717888888888888
INFO flwr 2023-08-15 15:43:45,933 | server.py:116 | fit progress: (17, 1.6454512542724609, {'server_test_acc': 0.7568}, 1584.7416926929727)
INFO flwr 2023-08-15 15:43:45,933 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-08-15 15:43:55,381 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4019501)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4019499)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4019503)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:44:42,983 | server.py:229 | fit_round 18 received 8 results and 0 failures
INFO flwr 2023-08-15 15:44:43,210 | fed_df.py:365 | Warm start at round 18
INFO flwr 2023-08-15 15:44:43,321 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4019494)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4019497)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4019495)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=4019499)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=4019500)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4019501)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4019502)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=4019503)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4019500)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4019497)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4019495)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4019502)[0m double free or corruption (fasttop)
E0815 15:44:44.329103759 3994241 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4019494)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:45:17,027 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:45:17,028 | fed_df.py:547 | Average fusion training loss : 0.010127326576970517, val accuracy : 0.7480800000000001, best val accuracy : 0.757
INFO flwr 2023-08-15 15:45:17,029 | common.py:35 | Avg. local train loss : 4.297794768586755, train acc : 0.8747972222222221
INFO flwr 2023-08-15 15:45:19,827 | server.py:116 | fit progress: (18, 1.6443189239501954, {'server_test_acc': 0.7546}, 1678.6361630030442)
INFO flwr 2023-08-15 15:45:19,827 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-08-15 15:45:29,231 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4093510)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:46:16,578 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4093509)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:46:16,803 | fed_df.py:365 | Warm start at round 19
INFO flwr 2023-08-15 15:46:16,914 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4093503)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4093506)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4093507)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4093508)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4093510)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4093511)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4093512)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4093509)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=4093506)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093512)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093503)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4093507)[0m malloc_consolidate(): invalid chunk size
E0815 15:46:18.011990811 4067475 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4093508)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4093511)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:46:50,633 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:46:50,634 | fed_df.py:547 | Average fusion training loss : 0.010051200188696385, val accuracy : 0.75276, best val accuracy : 0.762
INFO flwr 2023-08-15 15:46:50,635 | common.py:35 | Avg. local train loss : 4.291718132421375, train acc : 0.8761083333333334
INFO flwr 2023-08-15 15:46:53,440 | server.py:116 | fit progress: (19, 1.601531948852539, {'server_test_acc': 0.7647}, 1772.2489398419857)
INFO flwr 2023-08-15 15:46:53,440 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-08-15 15:47:02,933 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4167387)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:47:50,690 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=4167389)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:47:50,916 | fed_df.py:365 | Warm start at round 20
INFO flwr 2023-08-15 15:47:51,027 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=4167386)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=4167385)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=4167389)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=4167385)[0m 
[2m[36m(launch_and_fit pid=4167387)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=4167388)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=4167391)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=4167392)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=4167390)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4167385)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4167392)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4167391)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4167386)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4167388)[0m malloc_consolidate(): invalid chunk size
E0815 15:47:52.276693263   29285 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=4167390)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:48:25,038 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:48:25,039 | fed_df.py:547 | Average fusion training loss : 0.010589128198102116, val accuracy : 0.7474399999999999, best val accuracy : 0.7554
INFO flwr 2023-08-15 15:48:25,040 | common.py:35 | Avg. local train loss : 4.266668852046132, train acc : 0.8792611111111112
INFO flwr 2023-08-15 15:48:27,835 | server.py:116 | fit progress: (20, 1.590177423095703, {'server_test_acc': 0.7573}, 1866.6442306509707)
INFO flwr 2023-08-15 15:48:27,836 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-08-15 15:48:37,376 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=70807)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=70810)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:49:24,546 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=70812)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:49:24,771 | fed_df.py:365 | Warm start at round 21
INFO flwr 2023-08-15 15:49:24,927 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=70807)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=70810)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=70812)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=70816)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=70815)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=70811)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=70814)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=70813)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=70811)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=70816)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=70813)[0m double free or corruption (fasttop)
E0815 15:49:25.937270561  124254 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=70814)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=70815)[0m malloc_consolidate(): invalid chunk size
E0815 15:49:29.361719312  124657 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0815 15:49:44.338528118  137419 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:49:59,007 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:49:59,008 | fed_df.py:547 | Average fusion training loss : 0.008853741564787925, val accuracy : 0.7562, best val accuracy : 0.7616
INFO flwr 2023-08-15 15:49:59,009 | common.py:35 | Avg. local train loss : 4.208720763400198, train acc : 0.8864555555555557
INFO flwr 2023-08-15 15:50:01,824 | server.py:116 | fit progress: (21, 1.7045772491455078, {'server_test_acc': 0.7679}, 1960.632755907951)
INFO flwr 2023-08-15 15:50:01,824 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-08-15 15:50:11,454 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=150998)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:50:58,699 | server.py:229 | fit_round 22 received 8 results and 0 failures
INFO flwr 2023-08-15 15:50:58,925 | fed_df.py:365 | Warm start at round 22
INFO flwr 2023-08-15 15:50:59,037 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=150998)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=151003)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=151000)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=151002)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=151001)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=151004)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=151005)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=151006)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=151003)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=151006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=151004)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=151001)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=151002)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=151000)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=151005)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:51:32,740 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:51:32,741 | fed_df.py:547 | Average fusion training loss : 0.011144207216799259, val accuracy : 0.76016, best val accuracy : 0.77
INFO flwr 2023-08-15 15:51:32,742 | common.py:35 | Avg. local train loss : 4.217235251516104, train acc : 0.8836055555555555
INFO flwr 2023-08-15 15:51:35,620 | server.py:116 | fit progress: (22, 1.64554130859375, {'server_test_acc': 0.7744}, 2054.4293164210394)
INFO flwr 2023-08-15 15:51:35,621 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-08-15 15:51:44,963 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=224909)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:52:32,106 | server.py:229 | fit_round 23 received 8 results and 0 failures
INFO flwr 2023-08-15 15:52:32,332 | fed_df.py:365 | Warm start at round 23
INFO flwr 2023-08-15 15:52:32,443 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=224909)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=224906)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=224913)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=224910)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=224912)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=224911)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=224908)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=224907)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=224907)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=224911)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=224906)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=224912)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=224908)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=224910)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=224913)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:53:06,327 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:53:06,327 | fed_df.py:547 | Average fusion training loss : 0.012237111479043961, val accuracy : 0.76004, best val accuracy : 0.7684
INFO flwr 2023-08-15 15:53:06,329 | common.py:35 | Avg. local train loss : 4.150545747950672, train acc : 0.8891166666666667
INFO flwr 2023-08-15 15:53:09,134 | server.py:116 | fit progress: (23, 1.6720373352050781, {'server_test_acc': 0.7678}, 2147.942601451883)
INFO flwr 2023-08-15 15:53:09,134 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-08-15 15:53:18,551 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=298828)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=298831)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=298836)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 15:54:06,088 | server.py:229 | fit_round 24 received 8 results and 0 failures
INFO flwr 2023-08-15 15:54:06,314 | fed_df.py:365 | Warm start at round 24
INFO flwr 2023-08-15 15:54:06,425 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=298828)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=298831)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=298833)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=298834)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=298835)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=298836)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=298837)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=298838)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=298833)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=298838)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=298834)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=298835)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=298837)[0m malloc_consolidate(): invalid chunk size
E0815 15:54:09.354791459  137759 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 15:54:40,379 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:54:40,380 | fed_df.py:547 | Average fusion training loss : 0.011824851550161839, val accuracy : 0.76536, best val accuracy : 0.7718
INFO flwr 2023-08-15 15:54:40,382 | common.py:35 | Avg. local train loss : 4.1758425332605835, train acc : 0.8871694444444446
INFO flwr 2023-08-15 15:54:43,192 | server.py:116 | fit progress: (24, 1.5789468200683594, {'server_test_acc': 0.7746}, 2242.0008974159136)
INFO flwr 2023-08-15 15:54:43,192 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-08-15 15:54:52,621 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=372530)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:55:39,875 | server.py:229 | fit_round 25 received 8 results and 0 failures
INFO flwr 2023-08-15 15:55:40,103 | fed_df.py:365 | Warm start at round 25
INFO flwr 2023-08-15 15:55:40,247 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=372530)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=372533)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=372532)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=372534)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=372531)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=372529)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=372535)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=372528)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=372532)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=372531)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=372535)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=372528)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=372533)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=372534)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=372529)[0m double free or corruption (fasttop)
INFO flwr 2023-08-15 15:56:13,964 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:56:13,964 | fed_df.py:547 | Average fusion training loss : 0.012086863685399294, val accuracy : 0.7684, best val accuracy : 0.7786
INFO flwr 2023-08-15 15:56:13,966 | common.py:35 | Avg. local train loss : 4.132423271983861, train acc : 0.8908611111111111
INFO flwr 2023-08-15 15:56:16,772 | server.py:116 | fit progress: (25, 1.589035546875, {'server_test_acc': 0.7774}, 2335.581259218976)
INFO flwr 2023-08-15 15:56:16,773 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-08-15 15:56:26,378 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 15:57:13,655 | server.py:229 | fit_round 26 received 8 results and 0 failures
INFO flwr 2023-08-15 15:57:13,881 | fed_df.py:365 | Warm start at round 26
INFO flwr 2023-08-15 15:57:14,028 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=446305)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=446307)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=446310)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=446311)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=446312)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=446313)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=446314)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=446315)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=446310)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=446307)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=446312)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=446313)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=446314)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=446315)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=446305)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=446311)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:57:47,795 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:57:47,796 | fed_df.py:547 | Average fusion training loss : 0.010738398557528853, val accuracy : 0.7697200000000001, best val accuracy : 0.7798
INFO flwr 2023-08-15 15:57:47,797 | common.py:35 | Avg. local train loss : 4.1168833442032335, train acc : 0.8928611111111111
INFO flwr 2023-08-15 15:57:50,603 | server.py:116 | fit progress: (26, 1.605681024169922, {'server_test_acc': 0.7782}, 2429.4119898399804)
INFO flwr 2023-08-15 15:57:50,603 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-08-15 15:58:00,124 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=520039)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520042)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 15:58:47,607 | server.py:229 | fit_round 27 received 8 results and 0 failures
INFO flwr 2023-08-15 15:58:47,831 | fed_df.py:365 | Warm start at round 27
INFO flwr 2023-08-15 15:58:47,942 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=520039)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=520045)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=520042)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=520043)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=520044)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=520046)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=520047)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=520048)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=520048)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520045)[0m malloc_consolidate(): invalid chunk size
E0815 15:58:48.689228854  498593 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=520043)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520044)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=520047)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=520046)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 15:59:20,710 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 15:59:20,711 | fed_df.py:547 | Average fusion training loss : 0.01177517325617373, val accuracy : 0.77348, best val accuracy : 0.7786
INFO flwr 2023-08-15 15:59:20,712 | common.py:35 | Avg. local train loss : 4.073238008841872, train acc : 0.8974944444444445
INFO flwr 2023-08-15 15:59:23,497 | server.py:116 | fit progress: (27, 1.567625799560547, {'server_test_acc': 0.779}, 2522.3060861548875)
INFO flwr 2023-08-15 15:59:23,497 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-08-15 15:59:32,924 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=594002)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-08-15 16:00:20,765 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=594005)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:00:20,991 | fed_df.py:365 | Warm start at round 28
[2m[36m(launch_and_fit pid=594004)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:00:21,148 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=594002)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=594006)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=594004)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=594005)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=594009)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=594010)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=594012)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=594011)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=594012)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=594011)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=594006)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=594010)[0m double free or corruption (fasttop)
E0815 16:00:22.365648816  641580 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=594009)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:00:53,834 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:00:53,835 | fed_df.py:547 | Average fusion training loss : 0.011726548746228218, val accuracy : 0.774, best val accuracy : 0.7784
INFO flwr 2023-08-15 16:00:53,836 | common.py:35 | Avg. local train loss : 4.003062076866627, train acc : 0.9035277777777778
INFO flwr 2023-08-15 16:00:56,621 | server.py:116 | fit progress: (28, 1.5223681579589843, {'server_test_acc': 0.7753}, 2615.4295275390614)
INFO flwr 2023-08-15 16:00:56,621 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-08-15 16:01:06,277 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=667755)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=667751)[0m double free or corruption (fasttop)
DEBUG flwr 2023-08-15 16:01:53,268 | server.py:229 | fit_round 29 received 8 results and 0 failures
INFO flwr 2023-08-15 16:01:53,493 | fed_df.py:365 | Warm start at round 29
INFO flwr 2023-08-15 16:01:53,605 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=667751)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=667755)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=667753)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=667756)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=667757)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=667760)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=667758)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=667759)[0m Fitting Client 3
E0815 16:01:54.265007859  641716 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=667753)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=667760)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=667758)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=667759)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=667757)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=667756)[0m malloc_consolidate(): invalid chunk size
INFO flwr 2023-08-15 16:02:32,947 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:02:32,947 | fed_df.py:547 | Average fusion training loss : 0.011939025664702058, val accuracy : 0.77644, best val accuracy : 0.782
INFO flwr 2023-08-15 16:02:32,949 | common.py:35 | Avg. local train loss : 3.9957878433167933, train acc : 0.9039777777777779
INFO flwr 2023-08-15 16:02:35,897 | server.py:116 | fit progress: (29, 1.5904539489746095, {'server_test_acc': 0.7782}, 2714.705854541855)
INFO flwr 2023-08-15 16:02:35,897 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-08-15 16:02:45,372 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-08-15 16:03:32,827 | server.py:229 | fit_round 30 received 8 results and 0 failures
INFO flwr 2023-08-15 16:03:33,052 | fed_df.py:365 | Warm start at round 30
INFO flwr 2023-08-15 16:03:33,165 | fed_df.py:463 | Performing server side distillation training...
[2m[36m(launch_and_fit pid=746332)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=746334)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=746353)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=746347)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=746350)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=746348)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=746333)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=746331)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=746332)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=746353)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=746347)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=746350)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=746333)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=746331)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=746348)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=746334)[0m double free or corruption (fasttop)
E0815 16:03:37.479630528  714865 chttp2_transport.cc:1079]             ipv4:145.136.62.52:61708: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
INFO flwr 2023-08-15 16:04:08,236 | fed_df.py:540 | Distillation training stopped at step number : 250
INFO flwr 2023-08-15 16:04:08,236 | fed_df.py:547 | Average fusion training loss : 0.011903054531663656, val accuracy : 0.78128, best val accuracy : 0.785
INFO flwr 2023-08-15 16:04:08,238 | common.py:35 | Avg. local train loss : 3.9987459436058996, train acc : 0.9045416666666667
INFO flwr 2023-08-15 16:04:11,098 | server.py:116 | fit progress: (30, 1.5571041595458985, {'server_test_acc': 0.7862}, 2809.906582741067)
INFO flwr 2023-08-15 16:04:11,098 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-08-15 16:04:11,098 | server.py:144 | FL finished in 2809.907005329849
INFO flwr 2023-08-15 16:04:11,098 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-08-15 16:04:11,099 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-08-15 16:04:11,099 | app.py:204 | app_fit: losses_centralized [(0, 2.319245477294922), (1, 1.5848587158203125), (2, 1.393299298095703), (3, 1.3366265686035157), (4, 1.3009409912109375), (5, 1.385491534423828), (6, 1.4268705993652344), (7, 1.4762447814941406), (8, 1.5557923278808594), (9, 1.5278175598144532), (10, 1.5504868347167968), (11, 1.5214976684570312), (12, 1.579351788330078), (13, 1.6123265502929687), (14, 1.6529347259521485), (15, 1.6120816497802735), (16, 1.6557514709472656), (17, 1.6454512542724609), (18, 1.6443189239501954), (19, 1.601531948852539), (20, 1.590177423095703), (21, 1.7045772491455078), (22, 1.64554130859375), (23, 1.6720373352050781), (24, 1.5789468200683594), (25, 1.589035546875), (26, 1.605681024169922), (27, 1.567625799560547), (28, 1.5223681579589843), (29, 1.5904539489746095), (30, 1.5571041595458985)]
INFO flwr 2023-08-15 16:04:11,100 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.0811), (1, 0.4379), (2, 0.5667), (3, 0.6304), (4, 0.6632), (5, 0.6739), (6, 0.677), (7, 0.7069), (8, 0.7046), (9, 0.7187), (10, 0.7308), (11, 0.7391), (12, 0.7323), (13, 0.7305), (14, 0.7418), (15, 0.7467), (16, 0.7584), (17, 0.7568), (18, 0.7546), (19, 0.7647), (20, 0.7573), (21, 0.7679), (22, 0.7744), (23, 0.7678), (24, 0.7746), (25, 0.7774), (26, 0.7782), (27, 0.779), (28, 0.7753), (29, 0.7782), (30, 0.7862)]}
corrupted size vs. prev_size in fastbins
srun: error: gcn52: task 0: Aborted
srun: Terminating StepId=3342130.1
-----EXPERIMENT ENDS-----
-----CLEANING UP DISK------
-----END-----

JOB STATISTICS
==============
Job ID: 3342130
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 01:59:55
CPU Efficiency: 13.50% of 14:48:18 core-walltime
Job Wall-clock time: 00:49:21
Memory Utilized: 63.92 GB
Memory Efficiency: 53.26% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
